"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 06"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_06:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_06 = {
    "CONCEPT_06_001": ClinicalConcept_06(
        concept_id="CONCEPT_06_001",
        loinc_num="16001-1",
        snomed_ct="100600001",
        component="Diagnostic Analyte Component 06-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_002": ClinicalConcept_06(
        concept_id="CONCEPT_06_002",
        loinc_num="16002-2",
        snomed_ct="100600002",
        component="Diagnostic Analyte Component 06-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_003": ClinicalConcept_06(
        concept_id="CONCEPT_06_003",
        loinc_num="16003-3",
        snomed_ct="100600003",
        component="Diagnostic Analyte Component 06-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_004": ClinicalConcept_06(
        concept_id="CONCEPT_06_004",
        loinc_num="16004-4",
        snomed_ct="100600004",
        component="Diagnostic Analyte Component 06-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_005": ClinicalConcept_06(
        concept_id="CONCEPT_06_005",
        loinc_num="16005-5",
        snomed_ct="100600005",
        component="Diagnostic Analyte Component 06-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_006": ClinicalConcept_06(
        concept_id="CONCEPT_06_006",
        loinc_num="16006-6",
        snomed_ct="100600006",
        component="Diagnostic Analyte Component 06-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_007": ClinicalConcept_06(
        concept_id="CONCEPT_06_007",
        loinc_num="16007-7",
        snomed_ct="100600007",
        component="Diagnostic Analyte Component 06-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_008": ClinicalConcept_06(
        concept_id="CONCEPT_06_008",
        loinc_num="16008-8",
        snomed_ct="100600008",
        component="Diagnostic Analyte Component 06-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_009": ClinicalConcept_06(
        concept_id="CONCEPT_06_009",
        loinc_num="16009-0",
        snomed_ct="100600009",
        component="Diagnostic Analyte Component 06-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_010": ClinicalConcept_06(
        concept_id="CONCEPT_06_010",
        loinc_num="16010-1",
        snomed_ct="100600010",
        component="Diagnostic Analyte Component 06-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_011": ClinicalConcept_06(
        concept_id="CONCEPT_06_011",
        loinc_num="16011-2",
        snomed_ct="100600011",
        component="Diagnostic Analyte Component 06-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_012": ClinicalConcept_06(
        concept_id="CONCEPT_06_012",
        loinc_num="16012-3",
        snomed_ct="100600012",
        component="Diagnostic Analyte Component 06-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_013": ClinicalConcept_06(
        concept_id="CONCEPT_06_013",
        loinc_num="16013-4",
        snomed_ct="100600013",
        component="Diagnostic Analyte Component 06-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_014": ClinicalConcept_06(
        concept_id="CONCEPT_06_014",
        loinc_num="16014-5",
        snomed_ct="100600014",
        component="Diagnostic Analyte Component 06-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_015": ClinicalConcept_06(
        concept_id="CONCEPT_06_015",
        loinc_num="16015-6",
        snomed_ct="100600015",
        component="Diagnostic Analyte Component 06-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_016": ClinicalConcept_06(
        concept_id="CONCEPT_06_016",
        loinc_num="16016-7",
        snomed_ct="100600016",
        component="Diagnostic Analyte Component 06-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_017": ClinicalConcept_06(
        concept_id="CONCEPT_06_017",
        loinc_num="16017-8",
        snomed_ct="100600017",
        component="Diagnostic Analyte Component 06-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_018": ClinicalConcept_06(
        concept_id="CONCEPT_06_018",
        loinc_num="16018-0",
        snomed_ct="100600018",
        component="Diagnostic Analyte Component 06-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_019": ClinicalConcept_06(
        concept_id="CONCEPT_06_019",
        loinc_num="16019-1",
        snomed_ct="100600019",
        component="Diagnostic Analyte Component 06-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_020": ClinicalConcept_06(
        concept_id="CONCEPT_06_020",
        loinc_num="16020-2",
        snomed_ct="100600020",
        component="Diagnostic Analyte Component 06-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_021": ClinicalConcept_06(
        concept_id="CONCEPT_06_021",
        loinc_num="16021-3",
        snomed_ct="100600021",
        component="Diagnostic Analyte Component 06-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_022": ClinicalConcept_06(
        concept_id="CONCEPT_06_022",
        loinc_num="16022-4",
        snomed_ct="100600022",
        component="Diagnostic Analyte Component 06-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_023": ClinicalConcept_06(
        concept_id="CONCEPT_06_023",
        loinc_num="16023-5",
        snomed_ct="100600023",
        component="Diagnostic Analyte Component 06-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_024": ClinicalConcept_06(
        concept_id="CONCEPT_06_024",
        loinc_num="16024-6",
        snomed_ct="100600024",
        component="Diagnostic Analyte Component 06-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_025": ClinicalConcept_06(
        concept_id="CONCEPT_06_025",
        loinc_num="16025-7",
        snomed_ct="100600025",
        component="Diagnostic Analyte Component 06-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_026": ClinicalConcept_06(
        concept_id="CONCEPT_06_026",
        loinc_num="16026-8",
        snomed_ct="100600026",
        component="Diagnostic Analyte Component 06-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_027": ClinicalConcept_06(
        concept_id="CONCEPT_06_027",
        loinc_num="16027-0",
        snomed_ct="100600027",
        component="Diagnostic Analyte Component 06-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_028": ClinicalConcept_06(
        concept_id="CONCEPT_06_028",
        loinc_num="16028-1",
        snomed_ct="100600028",
        component="Diagnostic Analyte Component 06-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_029": ClinicalConcept_06(
        concept_id="CONCEPT_06_029",
        loinc_num="16029-2",
        snomed_ct="100600029",
        component="Diagnostic Analyte Component 06-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_030": ClinicalConcept_06(
        concept_id="CONCEPT_06_030",
        loinc_num="16030-3",
        snomed_ct="100600030",
        component="Diagnostic Analyte Component 06-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_031": ClinicalConcept_06(
        concept_id="CONCEPT_06_031",
        loinc_num="16031-4",
        snomed_ct="100600031",
        component="Diagnostic Analyte Component 06-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_032": ClinicalConcept_06(
        concept_id="CONCEPT_06_032",
        loinc_num="16032-5",
        snomed_ct="100600032",
        component="Diagnostic Analyte Component 06-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_033": ClinicalConcept_06(
        concept_id="CONCEPT_06_033",
        loinc_num="16033-6",
        snomed_ct="100600033",
        component="Diagnostic Analyte Component 06-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_034": ClinicalConcept_06(
        concept_id="CONCEPT_06_034",
        loinc_num="16034-7",
        snomed_ct="100600034",
        component="Diagnostic Analyte Component 06-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_035": ClinicalConcept_06(
        concept_id="CONCEPT_06_035",
        loinc_num="16035-8",
        snomed_ct="100600035",
        component="Diagnostic Analyte Component 06-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_036": ClinicalConcept_06(
        concept_id="CONCEPT_06_036",
        loinc_num="16036-0",
        snomed_ct="100600036",
        component="Diagnostic Analyte Component 06-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_037": ClinicalConcept_06(
        concept_id="CONCEPT_06_037",
        loinc_num="16037-1",
        snomed_ct="100600037",
        component="Diagnostic Analyte Component 06-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_038": ClinicalConcept_06(
        concept_id="CONCEPT_06_038",
        loinc_num="16038-2",
        snomed_ct="100600038",
        component="Diagnostic Analyte Component 06-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_039": ClinicalConcept_06(
        concept_id="CONCEPT_06_039",
        loinc_num="16039-3",
        snomed_ct="100600039",
        component="Diagnostic Analyte Component 06-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_040": ClinicalConcept_06(
        concept_id="CONCEPT_06_040",
        loinc_num="16040-4",
        snomed_ct="100600040",
        component="Diagnostic Analyte Component 06-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_041": ClinicalConcept_06(
        concept_id="CONCEPT_06_041",
        loinc_num="16041-5",
        snomed_ct="100600041",
        component="Diagnostic Analyte Component 06-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_042": ClinicalConcept_06(
        concept_id="CONCEPT_06_042",
        loinc_num="16042-6",
        snomed_ct="100600042",
        component="Diagnostic Analyte Component 06-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_043": ClinicalConcept_06(
        concept_id="CONCEPT_06_043",
        loinc_num="16043-7",
        snomed_ct="100600043",
        component="Diagnostic Analyte Component 06-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_044": ClinicalConcept_06(
        concept_id="CONCEPT_06_044",
        loinc_num="16044-8",
        snomed_ct="100600044",
        component="Diagnostic Analyte Component 06-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_045": ClinicalConcept_06(
        concept_id="CONCEPT_06_045",
        loinc_num="16045-0",
        snomed_ct="100600045",
        component="Diagnostic Analyte Component 06-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_046": ClinicalConcept_06(
        concept_id="CONCEPT_06_046",
        loinc_num="16046-1",
        snomed_ct="100600046",
        component="Diagnostic Analyte Component 06-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_047": ClinicalConcept_06(
        concept_id="CONCEPT_06_047",
        loinc_num="16047-2",
        snomed_ct="100600047",
        component="Diagnostic Analyte Component 06-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_048": ClinicalConcept_06(
        concept_id="CONCEPT_06_048",
        loinc_num="16048-3",
        snomed_ct="100600048",
        component="Diagnostic Analyte Component 06-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_049": ClinicalConcept_06(
        concept_id="CONCEPT_06_049",
        loinc_num="16049-4",
        snomed_ct="100600049",
        component="Diagnostic Analyte Component 06-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_050": ClinicalConcept_06(
        concept_id="CONCEPT_06_050",
        loinc_num="16050-5",
        snomed_ct="100600050",
        component="Diagnostic Analyte Component 06-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_051": ClinicalConcept_06(
        concept_id="CONCEPT_06_051",
        loinc_num="16051-6",
        snomed_ct="100600051",
        component="Diagnostic Analyte Component 06-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_052": ClinicalConcept_06(
        concept_id="CONCEPT_06_052",
        loinc_num="16052-7",
        snomed_ct="100600052",
        component="Diagnostic Analyte Component 06-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_053": ClinicalConcept_06(
        concept_id="CONCEPT_06_053",
        loinc_num="16053-8",
        snomed_ct="100600053",
        component="Diagnostic Analyte Component 06-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_054": ClinicalConcept_06(
        concept_id="CONCEPT_06_054",
        loinc_num="16054-0",
        snomed_ct="100600054",
        component="Diagnostic Analyte Component 06-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_055": ClinicalConcept_06(
        concept_id="CONCEPT_06_055",
        loinc_num="16055-1",
        snomed_ct="100600055",
        component="Diagnostic Analyte Component 06-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_056": ClinicalConcept_06(
        concept_id="CONCEPT_06_056",
        loinc_num="16056-2",
        snomed_ct="100600056",
        component="Diagnostic Analyte Component 06-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_057": ClinicalConcept_06(
        concept_id="CONCEPT_06_057",
        loinc_num="16057-3",
        snomed_ct="100600057",
        component="Diagnostic Analyte Component 06-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_058": ClinicalConcept_06(
        concept_id="CONCEPT_06_058",
        loinc_num="16058-4",
        snomed_ct="100600058",
        component="Diagnostic Analyte Component 06-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_059": ClinicalConcept_06(
        concept_id="CONCEPT_06_059",
        loinc_num="16059-5",
        snomed_ct="100600059",
        component="Diagnostic Analyte Component 06-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_060": ClinicalConcept_06(
        concept_id="CONCEPT_06_060",
        loinc_num="16060-6",
        snomed_ct="100600060",
        component="Diagnostic Analyte Component 06-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_061": ClinicalConcept_06(
        concept_id="CONCEPT_06_061",
        loinc_num="16061-7",
        snomed_ct="100600061",
        component="Diagnostic Analyte Component 06-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_062": ClinicalConcept_06(
        concept_id="CONCEPT_06_062",
        loinc_num="16062-8",
        snomed_ct="100600062",
        component="Diagnostic Analyte Component 06-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_063": ClinicalConcept_06(
        concept_id="CONCEPT_06_063",
        loinc_num="16063-0",
        snomed_ct="100600063",
        component="Diagnostic Analyte Component 06-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_064": ClinicalConcept_06(
        concept_id="CONCEPT_06_064",
        loinc_num="16064-1",
        snomed_ct="100600064",
        component="Diagnostic Analyte Component 06-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_065": ClinicalConcept_06(
        concept_id="CONCEPT_06_065",
        loinc_num="16065-2",
        snomed_ct="100600065",
        component="Diagnostic Analyte Component 06-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_066": ClinicalConcept_06(
        concept_id="CONCEPT_06_066",
        loinc_num="16066-3",
        snomed_ct="100600066",
        component="Diagnostic Analyte Component 06-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_067": ClinicalConcept_06(
        concept_id="CONCEPT_06_067",
        loinc_num="16067-4",
        snomed_ct="100600067",
        component="Diagnostic Analyte Component 06-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_068": ClinicalConcept_06(
        concept_id="CONCEPT_06_068",
        loinc_num="16068-5",
        snomed_ct="100600068",
        component="Diagnostic Analyte Component 06-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_069": ClinicalConcept_06(
        concept_id="CONCEPT_06_069",
        loinc_num="16069-6",
        snomed_ct="100600069",
        component="Diagnostic Analyte Component 06-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_070": ClinicalConcept_06(
        concept_id="CONCEPT_06_070",
        loinc_num="16070-7",
        snomed_ct="100600070",
        component="Diagnostic Analyte Component 06-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_071": ClinicalConcept_06(
        concept_id="CONCEPT_06_071",
        loinc_num="16071-8",
        snomed_ct="100600071",
        component="Diagnostic Analyte Component 06-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_072": ClinicalConcept_06(
        concept_id="CONCEPT_06_072",
        loinc_num="16072-0",
        snomed_ct="100600072",
        component="Diagnostic Analyte Component 06-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_073": ClinicalConcept_06(
        concept_id="CONCEPT_06_073",
        loinc_num="16073-1",
        snomed_ct="100600073",
        component="Diagnostic Analyte Component 06-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_074": ClinicalConcept_06(
        concept_id="CONCEPT_06_074",
        loinc_num="16074-2",
        snomed_ct="100600074",
        component="Diagnostic Analyte Component 06-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_075": ClinicalConcept_06(
        concept_id="CONCEPT_06_075",
        loinc_num="16075-3",
        snomed_ct="100600075",
        component="Diagnostic Analyte Component 06-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_076": ClinicalConcept_06(
        concept_id="CONCEPT_06_076",
        loinc_num="16076-4",
        snomed_ct="100600076",
        component="Diagnostic Analyte Component 06-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_077": ClinicalConcept_06(
        concept_id="CONCEPT_06_077",
        loinc_num="16077-5",
        snomed_ct="100600077",
        component="Diagnostic Analyte Component 06-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_078": ClinicalConcept_06(
        concept_id="CONCEPT_06_078",
        loinc_num="16078-6",
        snomed_ct="100600078",
        component="Diagnostic Analyte Component 06-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_079": ClinicalConcept_06(
        concept_id="CONCEPT_06_079",
        loinc_num="16079-7",
        snomed_ct="100600079",
        component="Diagnostic Analyte Component 06-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_080": ClinicalConcept_06(
        concept_id="CONCEPT_06_080",
        loinc_num="16080-8",
        snomed_ct="100600080",
        component="Diagnostic Analyte Component 06-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_081": ClinicalConcept_06(
        concept_id="CONCEPT_06_081",
        loinc_num="16081-0",
        snomed_ct="100600081",
        component="Diagnostic Analyte Component 06-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_082": ClinicalConcept_06(
        concept_id="CONCEPT_06_082",
        loinc_num="16082-1",
        snomed_ct="100600082",
        component="Diagnostic Analyte Component 06-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_083": ClinicalConcept_06(
        concept_id="CONCEPT_06_083",
        loinc_num="16083-2",
        snomed_ct="100600083",
        component="Diagnostic Analyte Component 06-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_084": ClinicalConcept_06(
        concept_id="CONCEPT_06_084",
        loinc_num="16084-3",
        snomed_ct="100600084",
        component="Diagnostic Analyte Component 06-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_085": ClinicalConcept_06(
        concept_id="CONCEPT_06_085",
        loinc_num="16085-4",
        snomed_ct="100600085",
        component="Diagnostic Analyte Component 06-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_086": ClinicalConcept_06(
        concept_id="CONCEPT_06_086",
        loinc_num="16086-5",
        snomed_ct="100600086",
        component="Diagnostic Analyte Component 06-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_087": ClinicalConcept_06(
        concept_id="CONCEPT_06_087",
        loinc_num="16087-6",
        snomed_ct="100600087",
        component="Diagnostic Analyte Component 06-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_088": ClinicalConcept_06(
        concept_id="CONCEPT_06_088",
        loinc_num="16088-7",
        snomed_ct="100600088",
        component="Diagnostic Analyte Component 06-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_089": ClinicalConcept_06(
        concept_id="CONCEPT_06_089",
        loinc_num="16089-8",
        snomed_ct="100600089",
        component="Diagnostic Analyte Component 06-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_090": ClinicalConcept_06(
        concept_id="CONCEPT_06_090",
        loinc_num="16090-0",
        snomed_ct="100600090",
        component="Diagnostic Analyte Component 06-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_091": ClinicalConcept_06(
        concept_id="CONCEPT_06_091",
        loinc_num="16091-1",
        snomed_ct="100600091",
        component="Diagnostic Analyte Component 06-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_092": ClinicalConcept_06(
        concept_id="CONCEPT_06_092",
        loinc_num="16092-2",
        snomed_ct="100600092",
        component="Diagnostic Analyte Component 06-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_093": ClinicalConcept_06(
        concept_id="CONCEPT_06_093",
        loinc_num="16093-3",
        snomed_ct="100600093",
        component="Diagnostic Analyte Component 06-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_094": ClinicalConcept_06(
        concept_id="CONCEPT_06_094",
        loinc_num="16094-4",
        snomed_ct="100600094",
        component="Diagnostic Analyte Component 06-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_095": ClinicalConcept_06(
        concept_id="CONCEPT_06_095",
        loinc_num="16095-5",
        snomed_ct="100600095",
        component="Diagnostic Analyte Component 06-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_096": ClinicalConcept_06(
        concept_id="CONCEPT_06_096",
        loinc_num="16096-6",
        snomed_ct="100600096",
        component="Diagnostic Analyte Component 06-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_097": ClinicalConcept_06(
        concept_id="CONCEPT_06_097",
        loinc_num="16097-7",
        snomed_ct="100600097",
        component="Diagnostic Analyte Component 06-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_098": ClinicalConcept_06(
        concept_id="CONCEPT_06_098",
        loinc_num="16098-8",
        snomed_ct="100600098",
        component="Diagnostic Analyte Component 06-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_099": ClinicalConcept_06(
        concept_id="CONCEPT_06_099",
        loinc_num="16099-0",
        snomed_ct="100600099",
        component="Diagnostic Analyte Component 06-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_100": ClinicalConcept_06(
        concept_id="CONCEPT_06_100",
        loinc_num="16100-1",
        snomed_ct="100600100",
        component="Diagnostic Analyte Component 06-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_101": ClinicalConcept_06(
        concept_id="CONCEPT_06_101",
        loinc_num="16101-2",
        snomed_ct="100600101",
        component="Diagnostic Analyte Component 06-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_102": ClinicalConcept_06(
        concept_id="CONCEPT_06_102",
        loinc_num="16102-3",
        snomed_ct="100600102",
        component="Diagnostic Analyte Component 06-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_103": ClinicalConcept_06(
        concept_id="CONCEPT_06_103",
        loinc_num="16103-4",
        snomed_ct="100600103",
        component="Diagnostic Analyte Component 06-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_104": ClinicalConcept_06(
        concept_id="CONCEPT_06_104",
        loinc_num="16104-5",
        snomed_ct="100600104",
        component="Diagnostic Analyte Component 06-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_105": ClinicalConcept_06(
        concept_id="CONCEPT_06_105",
        loinc_num="16105-6",
        snomed_ct="100600105",
        component="Diagnostic Analyte Component 06-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_106": ClinicalConcept_06(
        concept_id="CONCEPT_06_106",
        loinc_num="16106-7",
        snomed_ct="100600106",
        component="Diagnostic Analyte Component 06-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_107": ClinicalConcept_06(
        concept_id="CONCEPT_06_107",
        loinc_num="16107-8",
        snomed_ct="100600107",
        component="Diagnostic Analyte Component 06-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_108": ClinicalConcept_06(
        concept_id="CONCEPT_06_108",
        loinc_num="16108-0",
        snomed_ct="100600108",
        component="Diagnostic Analyte Component 06-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_109": ClinicalConcept_06(
        concept_id="CONCEPT_06_109",
        loinc_num="16109-1",
        snomed_ct="100600109",
        component="Diagnostic Analyte Component 06-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_110": ClinicalConcept_06(
        concept_id="CONCEPT_06_110",
        loinc_num="16110-2",
        snomed_ct="100600110",
        component="Diagnostic Analyte Component 06-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_111": ClinicalConcept_06(
        concept_id="CONCEPT_06_111",
        loinc_num="16111-3",
        snomed_ct="100600111",
        component="Diagnostic Analyte Component 06-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_112": ClinicalConcept_06(
        concept_id="CONCEPT_06_112",
        loinc_num="16112-4",
        snomed_ct="100600112",
        component="Diagnostic Analyte Component 06-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_113": ClinicalConcept_06(
        concept_id="CONCEPT_06_113",
        loinc_num="16113-5",
        snomed_ct="100600113",
        component="Diagnostic Analyte Component 06-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_114": ClinicalConcept_06(
        concept_id="CONCEPT_06_114",
        loinc_num="16114-6",
        snomed_ct="100600114",
        component="Diagnostic Analyte Component 06-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_115": ClinicalConcept_06(
        concept_id="CONCEPT_06_115",
        loinc_num="16115-7",
        snomed_ct="100600115",
        component="Diagnostic Analyte Component 06-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_116": ClinicalConcept_06(
        concept_id="CONCEPT_06_116",
        loinc_num="16116-8",
        snomed_ct="100600116",
        component="Diagnostic Analyte Component 06-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_117": ClinicalConcept_06(
        concept_id="CONCEPT_06_117",
        loinc_num="16117-0",
        snomed_ct="100600117",
        component="Diagnostic Analyte Component 06-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_118": ClinicalConcept_06(
        concept_id="CONCEPT_06_118",
        loinc_num="16118-1",
        snomed_ct="100600118",
        component="Diagnostic Analyte Component 06-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_119": ClinicalConcept_06(
        concept_id="CONCEPT_06_119",
        loinc_num="16119-2",
        snomed_ct="100600119",
        component="Diagnostic Analyte Component 06-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_120": ClinicalConcept_06(
        concept_id="CONCEPT_06_120",
        loinc_num="16120-3",
        snomed_ct="100600120",
        component="Diagnostic Analyte Component 06-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_121": ClinicalConcept_06(
        concept_id="CONCEPT_06_121",
        loinc_num="16121-4",
        snomed_ct="100600121",
        component="Diagnostic Analyte Component 06-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_122": ClinicalConcept_06(
        concept_id="CONCEPT_06_122",
        loinc_num="16122-5",
        snomed_ct="100600122",
        component="Diagnostic Analyte Component 06-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_123": ClinicalConcept_06(
        concept_id="CONCEPT_06_123",
        loinc_num="16123-6",
        snomed_ct="100600123",
        component="Diagnostic Analyte Component 06-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_124": ClinicalConcept_06(
        concept_id="CONCEPT_06_124",
        loinc_num="16124-7",
        snomed_ct="100600124",
        component="Diagnostic Analyte Component 06-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_125": ClinicalConcept_06(
        concept_id="CONCEPT_06_125",
        loinc_num="16125-8",
        snomed_ct="100600125",
        component="Diagnostic Analyte Component 06-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_126": ClinicalConcept_06(
        concept_id="CONCEPT_06_126",
        loinc_num="16126-0",
        snomed_ct="100600126",
        component="Diagnostic Analyte Component 06-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_127": ClinicalConcept_06(
        concept_id="CONCEPT_06_127",
        loinc_num="16127-1",
        snomed_ct="100600127",
        component="Diagnostic Analyte Component 06-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_128": ClinicalConcept_06(
        concept_id="CONCEPT_06_128",
        loinc_num="16128-2",
        snomed_ct="100600128",
        component="Diagnostic Analyte Component 06-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_129": ClinicalConcept_06(
        concept_id="CONCEPT_06_129",
        loinc_num="16129-3",
        snomed_ct="100600129",
        component="Diagnostic Analyte Component 06-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_130": ClinicalConcept_06(
        concept_id="CONCEPT_06_130",
        loinc_num="16130-4",
        snomed_ct="100600130",
        component="Diagnostic Analyte Component 06-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_131": ClinicalConcept_06(
        concept_id="CONCEPT_06_131",
        loinc_num="16131-5",
        snomed_ct="100600131",
        component="Diagnostic Analyte Component 06-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_132": ClinicalConcept_06(
        concept_id="CONCEPT_06_132",
        loinc_num="16132-6",
        snomed_ct="100600132",
        component="Diagnostic Analyte Component 06-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_133": ClinicalConcept_06(
        concept_id="CONCEPT_06_133",
        loinc_num="16133-7",
        snomed_ct="100600133",
        component="Diagnostic Analyte Component 06-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_134": ClinicalConcept_06(
        concept_id="CONCEPT_06_134",
        loinc_num="16134-8",
        snomed_ct="100600134",
        component="Diagnostic Analyte Component 06-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_135": ClinicalConcept_06(
        concept_id="CONCEPT_06_135",
        loinc_num="16135-0",
        snomed_ct="100600135",
        component="Diagnostic Analyte Component 06-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_136": ClinicalConcept_06(
        concept_id="CONCEPT_06_136",
        loinc_num="16136-1",
        snomed_ct="100600136",
        component="Diagnostic Analyte Component 06-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_137": ClinicalConcept_06(
        concept_id="CONCEPT_06_137",
        loinc_num="16137-2",
        snomed_ct="100600137",
        component="Diagnostic Analyte Component 06-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_138": ClinicalConcept_06(
        concept_id="CONCEPT_06_138",
        loinc_num="16138-3",
        snomed_ct="100600138",
        component="Diagnostic Analyte Component 06-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_139": ClinicalConcept_06(
        concept_id="CONCEPT_06_139",
        loinc_num="16139-4",
        snomed_ct="100600139",
        component="Diagnostic Analyte Component 06-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_140": ClinicalConcept_06(
        concept_id="CONCEPT_06_140",
        loinc_num="16140-5",
        snomed_ct="100600140",
        component="Diagnostic Analyte Component 06-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_141": ClinicalConcept_06(
        concept_id="CONCEPT_06_141",
        loinc_num="16141-6",
        snomed_ct="100600141",
        component="Diagnostic Analyte Component 06-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_142": ClinicalConcept_06(
        concept_id="CONCEPT_06_142",
        loinc_num="16142-7",
        snomed_ct="100600142",
        component="Diagnostic Analyte Component 06-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_143": ClinicalConcept_06(
        concept_id="CONCEPT_06_143",
        loinc_num="16143-8",
        snomed_ct="100600143",
        component="Diagnostic Analyte Component 06-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_144": ClinicalConcept_06(
        concept_id="CONCEPT_06_144",
        loinc_num="16144-0",
        snomed_ct="100600144",
        component="Diagnostic Analyte Component 06-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_145": ClinicalConcept_06(
        concept_id="CONCEPT_06_145",
        loinc_num="16145-1",
        snomed_ct="100600145",
        component="Diagnostic Analyte Component 06-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_146": ClinicalConcept_06(
        concept_id="CONCEPT_06_146",
        loinc_num="16146-2",
        snomed_ct="100600146",
        component="Diagnostic Analyte Component 06-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_147": ClinicalConcept_06(
        concept_id="CONCEPT_06_147",
        loinc_num="16147-3",
        snomed_ct="100600147",
        component="Diagnostic Analyte Component 06-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_148": ClinicalConcept_06(
        concept_id="CONCEPT_06_148",
        loinc_num="16148-4",
        snomed_ct="100600148",
        component="Diagnostic Analyte Component 06-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_149": ClinicalConcept_06(
        concept_id="CONCEPT_06_149",
        loinc_num="16149-5",
        snomed_ct="100600149",
        component="Diagnostic Analyte Component 06-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_150": ClinicalConcept_06(
        concept_id="CONCEPT_06_150",
        loinc_num="16150-6",
        snomed_ct="100600150",
        component="Diagnostic Analyte Component 06-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_151": ClinicalConcept_06(
        concept_id="CONCEPT_06_151",
        loinc_num="16151-7",
        snomed_ct="100600151",
        component="Diagnostic Analyte Component 06-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_152": ClinicalConcept_06(
        concept_id="CONCEPT_06_152",
        loinc_num="16152-8",
        snomed_ct="100600152",
        component="Diagnostic Analyte Component 06-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_153": ClinicalConcept_06(
        concept_id="CONCEPT_06_153",
        loinc_num="16153-0",
        snomed_ct="100600153",
        component="Diagnostic Analyte Component 06-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_154": ClinicalConcept_06(
        concept_id="CONCEPT_06_154",
        loinc_num="16154-1",
        snomed_ct="100600154",
        component="Diagnostic Analyte Component 06-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_155": ClinicalConcept_06(
        concept_id="CONCEPT_06_155",
        loinc_num="16155-2",
        snomed_ct="100600155",
        component="Diagnostic Analyte Component 06-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_156": ClinicalConcept_06(
        concept_id="CONCEPT_06_156",
        loinc_num="16156-3",
        snomed_ct="100600156",
        component="Diagnostic Analyte Component 06-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_157": ClinicalConcept_06(
        concept_id="CONCEPT_06_157",
        loinc_num="16157-4",
        snomed_ct="100600157",
        component="Diagnostic Analyte Component 06-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_158": ClinicalConcept_06(
        concept_id="CONCEPT_06_158",
        loinc_num="16158-5",
        snomed_ct="100600158",
        component="Diagnostic Analyte Component 06-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_159": ClinicalConcept_06(
        concept_id="CONCEPT_06_159",
        loinc_num="16159-6",
        snomed_ct="100600159",
        component="Diagnostic Analyte Component 06-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_160": ClinicalConcept_06(
        concept_id="CONCEPT_06_160",
        loinc_num="16160-7",
        snomed_ct="100600160",
        component="Diagnostic Analyte Component 06-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_161": ClinicalConcept_06(
        concept_id="CONCEPT_06_161",
        loinc_num="16161-8",
        snomed_ct="100600161",
        component="Diagnostic Analyte Component 06-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_162": ClinicalConcept_06(
        concept_id="CONCEPT_06_162",
        loinc_num="16162-0",
        snomed_ct="100600162",
        component="Diagnostic Analyte Component 06-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_163": ClinicalConcept_06(
        concept_id="CONCEPT_06_163",
        loinc_num="16163-1",
        snomed_ct="100600163",
        component="Diagnostic Analyte Component 06-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_164": ClinicalConcept_06(
        concept_id="CONCEPT_06_164",
        loinc_num="16164-2",
        snomed_ct="100600164",
        component="Diagnostic Analyte Component 06-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_165": ClinicalConcept_06(
        concept_id="CONCEPT_06_165",
        loinc_num="16165-3",
        snomed_ct="100600165",
        component="Diagnostic Analyte Component 06-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_166": ClinicalConcept_06(
        concept_id="CONCEPT_06_166",
        loinc_num="16166-4",
        snomed_ct="100600166",
        component="Diagnostic Analyte Component 06-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_167": ClinicalConcept_06(
        concept_id="CONCEPT_06_167",
        loinc_num="16167-5",
        snomed_ct="100600167",
        component="Diagnostic Analyte Component 06-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_168": ClinicalConcept_06(
        concept_id="CONCEPT_06_168",
        loinc_num="16168-6",
        snomed_ct="100600168",
        component="Diagnostic Analyte Component 06-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_169": ClinicalConcept_06(
        concept_id="CONCEPT_06_169",
        loinc_num="16169-7",
        snomed_ct="100600169",
        component="Diagnostic Analyte Component 06-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_170": ClinicalConcept_06(
        concept_id="CONCEPT_06_170",
        loinc_num="16170-8",
        snomed_ct="100600170",
        component="Diagnostic Analyte Component 06-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_171": ClinicalConcept_06(
        concept_id="CONCEPT_06_171",
        loinc_num="16171-0",
        snomed_ct="100600171",
        component="Diagnostic Analyte Component 06-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_172": ClinicalConcept_06(
        concept_id="CONCEPT_06_172",
        loinc_num="16172-1",
        snomed_ct="100600172",
        component="Diagnostic Analyte Component 06-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_173": ClinicalConcept_06(
        concept_id="CONCEPT_06_173",
        loinc_num="16173-2",
        snomed_ct="100600173",
        component="Diagnostic Analyte Component 06-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_174": ClinicalConcept_06(
        concept_id="CONCEPT_06_174",
        loinc_num="16174-3",
        snomed_ct="100600174",
        component="Diagnostic Analyte Component 06-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_175": ClinicalConcept_06(
        concept_id="CONCEPT_06_175",
        loinc_num="16175-4",
        snomed_ct="100600175",
        component="Diagnostic Analyte Component 06-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_176": ClinicalConcept_06(
        concept_id="CONCEPT_06_176",
        loinc_num="16176-5",
        snomed_ct="100600176",
        component="Diagnostic Analyte Component 06-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_177": ClinicalConcept_06(
        concept_id="CONCEPT_06_177",
        loinc_num="16177-6",
        snomed_ct="100600177",
        component="Diagnostic Analyte Component 06-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_178": ClinicalConcept_06(
        concept_id="CONCEPT_06_178",
        loinc_num="16178-7",
        snomed_ct="100600178",
        component="Diagnostic Analyte Component 06-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_179": ClinicalConcept_06(
        concept_id="CONCEPT_06_179",
        loinc_num="16179-8",
        snomed_ct="100600179",
        component="Diagnostic Analyte Component 06-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_180": ClinicalConcept_06(
        concept_id="CONCEPT_06_180",
        loinc_num="16180-0",
        snomed_ct="100600180",
        component="Diagnostic Analyte Component 06-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_181": ClinicalConcept_06(
        concept_id="CONCEPT_06_181",
        loinc_num="16181-1",
        snomed_ct="100600181",
        component="Diagnostic Analyte Component 06-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_182": ClinicalConcept_06(
        concept_id="CONCEPT_06_182",
        loinc_num="16182-2",
        snomed_ct="100600182",
        component="Diagnostic Analyte Component 06-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_183": ClinicalConcept_06(
        concept_id="CONCEPT_06_183",
        loinc_num="16183-3",
        snomed_ct="100600183",
        component="Diagnostic Analyte Component 06-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_184": ClinicalConcept_06(
        concept_id="CONCEPT_06_184",
        loinc_num="16184-4",
        snomed_ct="100600184",
        component="Diagnostic Analyte Component 06-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_185": ClinicalConcept_06(
        concept_id="CONCEPT_06_185",
        loinc_num="16185-5",
        snomed_ct="100600185",
        component="Diagnostic Analyte Component 06-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_186": ClinicalConcept_06(
        concept_id="CONCEPT_06_186",
        loinc_num="16186-6",
        snomed_ct="100600186",
        component="Diagnostic Analyte Component 06-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_187": ClinicalConcept_06(
        concept_id="CONCEPT_06_187",
        loinc_num="16187-7",
        snomed_ct="100600187",
        component="Diagnostic Analyte Component 06-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_188": ClinicalConcept_06(
        concept_id="CONCEPT_06_188",
        loinc_num="16188-8",
        snomed_ct="100600188",
        component="Diagnostic Analyte Component 06-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_189": ClinicalConcept_06(
        concept_id="CONCEPT_06_189",
        loinc_num="16189-0",
        snomed_ct="100600189",
        component="Diagnostic Analyte Component 06-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_190": ClinicalConcept_06(
        concept_id="CONCEPT_06_190",
        loinc_num="16190-1",
        snomed_ct="100600190",
        component="Diagnostic Analyte Component 06-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_191": ClinicalConcept_06(
        concept_id="CONCEPT_06_191",
        loinc_num="16191-2",
        snomed_ct="100600191",
        component="Diagnostic Analyte Component 06-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_192": ClinicalConcept_06(
        concept_id="CONCEPT_06_192",
        loinc_num="16192-3",
        snomed_ct="100600192",
        component="Diagnostic Analyte Component 06-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_193": ClinicalConcept_06(
        concept_id="CONCEPT_06_193",
        loinc_num="16193-4",
        snomed_ct="100600193",
        component="Diagnostic Analyte Component 06-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_194": ClinicalConcept_06(
        concept_id="CONCEPT_06_194",
        loinc_num="16194-5",
        snomed_ct="100600194",
        component="Diagnostic Analyte Component 06-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_195": ClinicalConcept_06(
        concept_id="CONCEPT_06_195",
        loinc_num="16195-6",
        snomed_ct="100600195",
        component="Diagnostic Analyte Component 06-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_196": ClinicalConcept_06(
        concept_id="CONCEPT_06_196",
        loinc_num="16196-7",
        snomed_ct="100600196",
        component="Diagnostic Analyte Component 06-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_197": ClinicalConcept_06(
        concept_id="CONCEPT_06_197",
        loinc_num="16197-8",
        snomed_ct="100600197",
        component="Diagnostic Analyte Component 06-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_198": ClinicalConcept_06(
        concept_id="CONCEPT_06_198",
        loinc_num="16198-0",
        snomed_ct="100600198",
        component="Diagnostic Analyte Component 06-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_06_199": ClinicalConcept_06(
        concept_id="CONCEPT_06_199",
        loinc_num="16199-1",
        snomed_ct="100600199",
        component="Diagnostic Analyte Component 06-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
