"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 13"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_13:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_13 = {
    "CONCEPT_13_001": ClinicalConcept_13(
        concept_id="CONCEPT_13_001",
        loinc_num="23001-1",
        snomed_ct="101300001",
        component="Diagnostic Analyte Component 13-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_002": ClinicalConcept_13(
        concept_id="CONCEPT_13_002",
        loinc_num="23002-2",
        snomed_ct="101300002",
        component="Diagnostic Analyte Component 13-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_003": ClinicalConcept_13(
        concept_id="CONCEPT_13_003",
        loinc_num="23003-3",
        snomed_ct="101300003",
        component="Diagnostic Analyte Component 13-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_004": ClinicalConcept_13(
        concept_id="CONCEPT_13_004",
        loinc_num="23004-4",
        snomed_ct="101300004",
        component="Diagnostic Analyte Component 13-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_005": ClinicalConcept_13(
        concept_id="CONCEPT_13_005",
        loinc_num="23005-5",
        snomed_ct="101300005",
        component="Diagnostic Analyte Component 13-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_006": ClinicalConcept_13(
        concept_id="CONCEPT_13_006",
        loinc_num="23006-6",
        snomed_ct="101300006",
        component="Diagnostic Analyte Component 13-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_007": ClinicalConcept_13(
        concept_id="CONCEPT_13_007",
        loinc_num="23007-7",
        snomed_ct="101300007",
        component="Diagnostic Analyte Component 13-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_008": ClinicalConcept_13(
        concept_id="CONCEPT_13_008",
        loinc_num="23008-8",
        snomed_ct="101300008",
        component="Diagnostic Analyte Component 13-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_009": ClinicalConcept_13(
        concept_id="CONCEPT_13_009",
        loinc_num="23009-0",
        snomed_ct="101300009",
        component="Diagnostic Analyte Component 13-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_010": ClinicalConcept_13(
        concept_id="CONCEPT_13_010",
        loinc_num="23010-1",
        snomed_ct="101300010",
        component="Diagnostic Analyte Component 13-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_011": ClinicalConcept_13(
        concept_id="CONCEPT_13_011",
        loinc_num="23011-2",
        snomed_ct="101300011",
        component="Diagnostic Analyte Component 13-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_012": ClinicalConcept_13(
        concept_id="CONCEPT_13_012",
        loinc_num="23012-3",
        snomed_ct="101300012",
        component="Diagnostic Analyte Component 13-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_013": ClinicalConcept_13(
        concept_id="CONCEPT_13_013",
        loinc_num="23013-4",
        snomed_ct="101300013",
        component="Diagnostic Analyte Component 13-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_014": ClinicalConcept_13(
        concept_id="CONCEPT_13_014",
        loinc_num="23014-5",
        snomed_ct="101300014",
        component="Diagnostic Analyte Component 13-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_015": ClinicalConcept_13(
        concept_id="CONCEPT_13_015",
        loinc_num="23015-6",
        snomed_ct="101300015",
        component="Diagnostic Analyte Component 13-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_016": ClinicalConcept_13(
        concept_id="CONCEPT_13_016",
        loinc_num="23016-7",
        snomed_ct="101300016",
        component="Diagnostic Analyte Component 13-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_017": ClinicalConcept_13(
        concept_id="CONCEPT_13_017",
        loinc_num="23017-8",
        snomed_ct="101300017",
        component="Diagnostic Analyte Component 13-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_018": ClinicalConcept_13(
        concept_id="CONCEPT_13_018",
        loinc_num="23018-0",
        snomed_ct="101300018",
        component="Diagnostic Analyte Component 13-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_019": ClinicalConcept_13(
        concept_id="CONCEPT_13_019",
        loinc_num="23019-1",
        snomed_ct="101300019",
        component="Diagnostic Analyte Component 13-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_020": ClinicalConcept_13(
        concept_id="CONCEPT_13_020",
        loinc_num="23020-2",
        snomed_ct="101300020",
        component="Diagnostic Analyte Component 13-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_021": ClinicalConcept_13(
        concept_id="CONCEPT_13_021",
        loinc_num="23021-3",
        snomed_ct="101300021",
        component="Diagnostic Analyte Component 13-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_022": ClinicalConcept_13(
        concept_id="CONCEPT_13_022",
        loinc_num="23022-4",
        snomed_ct="101300022",
        component="Diagnostic Analyte Component 13-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_023": ClinicalConcept_13(
        concept_id="CONCEPT_13_023",
        loinc_num="23023-5",
        snomed_ct="101300023",
        component="Diagnostic Analyte Component 13-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_024": ClinicalConcept_13(
        concept_id="CONCEPT_13_024",
        loinc_num="23024-6",
        snomed_ct="101300024",
        component="Diagnostic Analyte Component 13-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_025": ClinicalConcept_13(
        concept_id="CONCEPT_13_025",
        loinc_num="23025-7",
        snomed_ct="101300025",
        component="Diagnostic Analyte Component 13-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_026": ClinicalConcept_13(
        concept_id="CONCEPT_13_026",
        loinc_num="23026-8",
        snomed_ct="101300026",
        component="Diagnostic Analyte Component 13-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_027": ClinicalConcept_13(
        concept_id="CONCEPT_13_027",
        loinc_num="23027-0",
        snomed_ct="101300027",
        component="Diagnostic Analyte Component 13-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_028": ClinicalConcept_13(
        concept_id="CONCEPT_13_028",
        loinc_num="23028-1",
        snomed_ct="101300028",
        component="Diagnostic Analyte Component 13-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_029": ClinicalConcept_13(
        concept_id="CONCEPT_13_029",
        loinc_num="23029-2",
        snomed_ct="101300029",
        component="Diagnostic Analyte Component 13-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_030": ClinicalConcept_13(
        concept_id="CONCEPT_13_030",
        loinc_num="23030-3",
        snomed_ct="101300030",
        component="Diagnostic Analyte Component 13-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_031": ClinicalConcept_13(
        concept_id="CONCEPT_13_031",
        loinc_num="23031-4",
        snomed_ct="101300031",
        component="Diagnostic Analyte Component 13-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_032": ClinicalConcept_13(
        concept_id="CONCEPT_13_032",
        loinc_num="23032-5",
        snomed_ct="101300032",
        component="Diagnostic Analyte Component 13-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_033": ClinicalConcept_13(
        concept_id="CONCEPT_13_033",
        loinc_num="23033-6",
        snomed_ct="101300033",
        component="Diagnostic Analyte Component 13-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_034": ClinicalConcept_13(
        concept_id="CONCEPT_13_034",
        loinc_num="23034-7",
        snomed_ct="101300034",
        component="Diagnostic Analyte Component 13-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_035": ClinicalConcept_13(
        concept_id="CONCEPT_13_035",
        loinc_num="23035-8",
        snomed_ct="101300035",
        component="Diagnostic Analyte Component 13-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_036": ClinicalConcept_13(
        concept_id="CONCEPT_13_036",
        loinc_num="23036-0",
        snomed_ct="101300036",
        component="Diagnostic Analyte Component 13-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_037": ClinicalConcept_13(
        concept_id="CONCEPT_13_037",
        loinc_num="23037-1",
        snomed_ct="101300037",
        component="Diagnostic Analyte Component 13-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_038": ClinicalConcept_13(
        concept_id="CONCEPT_13_038",
        loinc_num="23038-2",
        snomed_ct="101300038",
        component="Diagnostic Analyte Component 13-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_039": ClinicalConcept_13(
        concept_id="CONCEPT_13_039",
        loinc_num="23039-3",
        snomed_ct="101300039",
        component="Diagnostic Analyte Component 13-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_040": ClinicalConcept_13(
        concept_id="CONCEPT_13_040",
        loinc_num="23040-4",
        snomed_ct="101300040",
        component="Diagnostic Analyte Component 13-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_041": ClinicalConcept_13(
        concept_id="CONCEPT_13_041",
        loinc_num="23041-5",
        snomed_ct="101300041",
        component="Diagnostic Analyte Component 13-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_042": ClinicalConcept_13(
        concept_id="CONCEPT_13_042",
        loinc_num="23042-6",
        snomed_ct="101300042",
        component="Diagnostic Analyte Component 13-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_043": ClinicalConcept_13(
        concept_id="CONCEPT_13_043",
        loinc_num="23043-7",
        snomed_ct="101300043",
        component="Diagnostic Analyte Component 13-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_044": ClinicalConcept_13(
        concept_id="CONCEPT_13_044",
        loinc_num="23044-8",
        snomed_ct="101300044",
        component="Diagnostic Analyte Component 13-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_045": ClinicalConcept_13(
        concept_id="CONCEPT_13_045",
        loinc_num="23045-0",
        snomed_ct="101300045",
        component="Diagnostic Analyte Component 13-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_046": ClinicalConcept_13(
        concept_id="CONCEPT_13_046",
        loinc_num="23046-1",
        snomed_ct="101300046",
        component="Diagnostic Analyte Component 13-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_047": ClinicalConcept_13(
        concept_id="CONCEPT_13_047",
        loinc_num="23047-2",
        snomed_ct="101300047",
        component="Diagnostic Analyte Component 13-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_048": ClinicalConcept_13(
        concept_id="CONCEPT_13_048",
        loinc_num="23048-3",
        snomed_ct="101300048",
        component="Diagnostic Analyte Component 13-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_049": ClinicalConcept_13(
        concept_id="CONCEPT_13_049",
        loinc_num="23049-4",
        snomed_ct="101300049",
        component="Diagnostic Analyte Component 13-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_050": ClinicalConcept_13(
        concept_id="CONCEPT_13_050",
        loinc_num="23050-5",
        snomed_ct="101300050",
        component="Diagnostic Analyte Component 13-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_051": ClinicalConcept_13(
        concept_id="CONCEPT_13_051",
        loinc_num="23051-6",
        snomed_ct="101300051",
        component="Diagnostic Analyte Component 13-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_052": ClinicalConcept_13(
        concept_id="CONCEPT_13_052",
        loinc_num="23052-7",
        snomed_ct="101300052",
        component="Diagnostic Analyte Component 13-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_053": ClinicalConcept_13(
        concept_id="CONCEPT_13_053",
        loinc_num="23053-8",
        snomed_ct="101300053",
        component="Diagnostic Analyte Component 13-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_054": ClinicalConcept_13(
        concept_id="CONCEPT_13_054",
        loinc_num="23054-0",
        snomed_ct="101300054",
        component="Diagnostic Analyte Component 13-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_055": ClinicalConcept_13(
        concept_id="CONCEPT_13_055",
        loinc_num="23055-1",
        snomed_ct="101300055",
        component="Diagnostic Analyte Component 13-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_056": ClinicalConcept_13(
        concept_id="CONCEPT_13_056",
        loinc_num="23056-2",
        snomed_ct="101300056",
        component="Diagnostic Analyte Component 13-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_057": ClinicalConcept_13(
        concept_id="CONCEPT_13_057",
        loinc_num="23057-3",
        snomed_ct="101300057",
        component="Diagnostic Analyte Component 13-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_058": ClinicalConcept_13(
        concept_id="CONCEPT_13_058",
        loinc_num="23058-4",
        snomed_ct="101300058",
        component="Diagnostic Analyte Component 13-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_059": ClinicalConcept_13(
        concept_id="CONCEPT_13_059",
        loinc_num="23059-5",
        snomed_ct="101300059",
        component="Diagnostic Analyte Component 13-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_060": ClinicalConcept_13(
        concept_id="CONCEPT_13_060",
        loinc_num="23060-6",
        snomed_ct="101300060",
        component="Diagnostic Analyte Component 13-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_061": ClinicalConcept_13(
        concept_id="CONCEPT_13_061",
        loinc_num="23061-7",
        snomed_ct="101300061",
        component="Diagnostic Analyte Component 13-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_062": ClinicalConcept_13(
        concept_id="CONCEPT_13_062",
        loinc_num="23062-8",
        snomed_ct="101300062",
        component="Diagnostic Analyte Component 13-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_063": ClinicalConcept_13(
        concept_id="CONCEPT_13_063",
        loinc_num="23063-0",
        snomed_ct="101300063",
        component="Diagnostic Analyte Component 13-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_064": ClinicalConcept_13(
        concept_id="CONCEPT_13_064",
        loinc_num="23064-1",
        snomed_ct="101300064",
        component="Diagnostic Analyte Component 13-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_065": ClinicalConcept_13(
        concept_id="CONCEPT_13_065",
        loinc_num="23065-2",
        snomed_ct="101300065",
        component="Diagnostic Analyte Component 13-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_066": ClinicalConcept_13(
        concept_id="CONCEPT_13_066",
        loinc_num="23066-3",
        snomed_ct="101300066",
        component="Diagnostic Analyte Component 13-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_067": ClinicalConcept_13(
        concept_id="CONCEPT_13_067",
        loinc_num="23067-4",
        snomed_ct="101300067",
        component="Diagnostic Analyte Component 13-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_068": ClinicalConcept_13(
        concept_id="CONCEPT_13_068",
        loinc_num="23068-5",
        snomed_ct="101300068",
        component="Diagnostic Analyte Component 13-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_069": ClinicalConcept_13(
        concept_id="CONCEPT_13_069",
        loinc_num="23069-6",
        snomed_ct="101300069",
        component="Diagnostic Analyte Component 13-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_070": ClinicalConcept_13(
        concept_id="CONCEPT_13_070",
        loinc_num="23070-7",
        snomed_ct="101300070",
        component="Diagnostic Analyte Component 13-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_071": ClinicalConcept_13(
        concept_id="CONCEPT_13_071",
        loinc_num="23071-8",
        snomed_ct="101300071",
        component="Diagnostic Analyte Component 13-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_072": ClinicalConcept_13(
        concept_id="CONCEPT_13_072",
        loinc_num="23072-0",
        snomed_ct="101300072",
        component="Diagnostic Analyte Component 13-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_073": ClinicalConcept_13(
        concept_id="CONCEPT_13_073",
        loinc_num="23073-1",
        snomed_ct="101300073",
        component="Diagnostic Analyte Component 13-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_074": ClinicalConcept_13(
        concept_id="CONCEPT_13_074",
        loinc_num="23074-2",
        snomed_ct="101300074",
        component="Diagnostic Analyte Component 13-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_075": ClinicalConcept_13(
        concept_id="CONCEPT_13_075",
        loinc_num="23075-3",
        snomed_ct="101300075",
        component="Diagnostic Analyte Component 13-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_076": ClinicalConcept_13(
        concept_id="CONCEPT_13_076",
        loinc_num="23076-4",
        snomed_ct="101300076",
        component="Diagnostic Analyte Component 13-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_077": ClinicalConcept_13(
        concept_id="CONCEPT_13_077",
        loinc_num="23077-5",
        snomed_ct="101300077",
        component="Diagnostic Analyte Component 13-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_078": ClinicalConcept_13(
        concept_id="CONCEPT_13_078",
        loinc_num="23078-6",
        snomed_ct="101300078",
        component="Diagnostic Analyte Component 13-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_079": ClinicalConcept_13(
        concept_id="CONCEPT_13_079",
        loinc_num="23079-7",
        snomed_ct="101300079",
        component="Diagnostic Analyte Component 13-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_080": ClinicalConcept_13(
        concept_id="CONCEPT_13_080",
        loinc_num="23080-8",
        snomed_ct="101300080",
        component="Diagnostic Analyte Component 13-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_081": ClinicalConcept_13(
        concept_id="CONCEPT_13_081",
        loinc_num="23081-0",
        snomed_ct="101300081",
        component="Diagnostic Analyte Component 13-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_082": ClinicalConcept_13(
        concept_id="CONCEPT_13_082",
        loinc_num="23082-1",
        snomed_ct="101300082",
        component="Diagnostic Analyte Component 13-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_083": ClinicalConcept_13(
        concept_id="CONCEPT_13_083",
        loinc_num="23083-2",
        snomed_ct="101300083",
        component="Diagnostic Analyte Component 13-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_084": ClinicalConcept_13(
        concept_id="CONCEPT_13_084",
        loinc_num="23084-3",
        snomed_ct="101300084",
        component="Diagnostic Analyte Component 13-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_085": ClinicalConcept_13(
        concept_id="CONCEPT_13_085",
        loinc_num="23085-4",
        snomed_ct="101300085",
        component="Diagnostic Analyte Component 13-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_086": ClinicalConcept_13(
        concept_id="CONCEPT_13_086",
        loinc_num="23086-5",
        snomed_ct="101300086",
        component="Diagnostic Analyte Component 13-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_087": ClinicalConcept_13(
        concept_id="CONCEPT_13_087",
        loinc_num="23087-6",
        snomed_ct="101300087",
        component="Diagnostic Analyte Component 13-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_088": ClinicalConcept_13(
        concept_id="CONCEPT_13_088",
        loinc_num="23088-7",
        snomed_ct="101300088",
        component="Diagnostic Analyte Component 13-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_089": ClinicalConcept_13(
        concept_id="CONCEPT_13_089",
        loinc_num="23089-8",
        snomed_ct="101300089",
        component="Diagnostic Analyte Component 13-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_090": ClinicalConcept_13(
        concept_id="CONCEPT_13_090",
        loinc_num="23090-0",
        snomed_ct="101300090",
        component="Diagnostic Analyte Component 13-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_091": ClinicalConcept_13(
        concept_id="CONCEPT_13_091",
        loinc_num="23091-1",
        snomed_ct="101300091",
        component="Diagnostic Analyte Component 13-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_092": ClinicalConcept_13(
        concept_id="CONCEPT_13_092",
        loinc_num="23092-2",
        snomed_ct="101300092",
        component="Diagnostic Analyte Component 13-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_093": ClinicalConcept_13(
        concept_id="CONCEPT_13_093",
        loinc_num="23093-3",
        snomed_ct="101300093",
        component="Diagnostic Analyte Component 13-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_094": ClinicalConcept_13(
        concept_id="CONCEPT_13_094",
        loinc_num="23094-4",
        snomed_ct="101300094",
        component="Diagnostic Analyte Component 13-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_095": ClinicalConcept_13(
        concept_id="CONCEPT_13_095",
        loinc_num="23095-5",
        snomed_ct="101300095",
        component="Diagnostic Analyte Component 13-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_096": ClinicalConcept_13(
        concept_id="CONCEPT_13_096",
        loinc_num="23096-6",
        snomed_ct="101300096",
        component="Diagnostic Analyte Component 13-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_097": ClinicalConcept_13(
        concept_id="CONCEPT_13_097",
        loinc_num="23097-7",
        snomed_ct="101300097",
        component="Diagnostic Analyte Component 13-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_098": ClinicalConcept_13(
        concept_id="CONCEPT_13_098",
        loinc_num="23098-8",
        snomed_ct="101300098",
        component="Diagnostic Analyte Component 13-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_099": ClinicalConcept_13(
        concept_id="CONCEPT_13_099",
        loinc_num="23099-0",
        snomed_ct="101300099",
        component="Diagnostic Analyte Component 13-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_100": ClinicalConcept_13(
        concept_id="CONCEPT_13_100",
        loinc_num="23100-1",
        snomed_ct="101300100",
        component="Diagnostic Analyte Component 13-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_101": ClinicalConcept_13(
        concept_id="CONCEPT_13_101",
        loinc_num="23101-2",
        snomed_ct="101300101",
        component="Diagnostic Analyte Component 13-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_102": ClinicalConcept_13(
        concept_id="CONCEPT_13_102",
        loinc_num="23102-3",
        snomed_ct="101300102",
        component="Diagnostic Analyte Component 13-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_103": ClinicalConcept_13(
        concept_id="CONCEPT_13_103",
        loinc_num="23103-4",
        snomed_ct="101300103",
        component="Diagnostic Analyte Component 13-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_104": ClinicalConcept_13(
        concept_id="CONCEPT_13_104",
        loinc_num="23104-5",
        snomed_ct="101300104",
        component="Diagnostic Analyte Component 13-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_105": ClinicalConcept_13(
        concept_id="CONCEPT_13_105",
        loinc_num="23105-6",
        snomed_ct="101300105",
        component="Diagnostic Analyte Component 13-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_106": ClinicalConcept_13(
        concept_id="CONCEPT_13_106",
        loinc_num="23106-7",
        snomed_ct="101300106",
        component="Diagnostic Analyte Component 13-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_107": ClinicalConcept_13(
        concept_id="CONCEPT_13_107",
        loinc_num="23107-8",
        snomed_ct="101300107",
        component="Diagnostic Analyte Component 13-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_108": ClinicalConcept_13(
        concept_id="CONCEPT_13_108",
        loinc_num="23108-0",
        snomed_ct="101300108",
        component="Diagnostic Analyte Component 13-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_109": ClinicalConcept_13(
        concept_id="CONCEPT_13_109",
        loinc_num="23109-1",
        snomed_ct="101300109",
        component="Diagnostic Analyte Component 13-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_110": ClinicalConcept_13(
        concept_id="CONCEPT_13_110",
        loinc_num="23110-2",
        snomed_ct="101300110",
        component="Diagnostic Analyte Component 13-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_111": ClinicalConcept_13(
        concept_id="CONCEPT_13_111",
        loinc_num="23111-3",
        snomed_ct="101300111",
        component="Diagnostic Analyte Component 13-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_112": ClinicalConcept_13(
        concept_id="CONCEPT_13_112",
        loinc_num="23112-4",
        snomed_ct="101300112",
        component="Diagnostic Analyte Component 13-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_113": ClinicalConcept_13(
        concept_id="CONCEPT_13_113",
        loinc_num="23113-5",
        snomed_ct="101300113",
        component="Diagnostic Analyte Component 13-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_114": ClinicalConcept_13(
        concept_id="CONCEPT_13_114",
        loinc_num="23114-6",
        snomed_ct="101300114",
        component="Diagnostic Analyte Component 13-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_115": ClinicalConcept_13(
        concept_id="CONCEPT_13_115",
        loinc_num="23115-7",
        snomed_ct="101300115",
        component="Diagnostic Analyte Component 13-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_116": ClinicalConcept_13(
        concept_id="CONCEPT_13_116",
        loinc_num="23116-8",
        snomed_ct="101300116",
        component="Diagnostic Analyte Component 13-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_117": ClinicalConcept_13(
        concept_id="CONCEPT_13_117",
        loinc_num="23117-0",
        snomed_ct="101300117",
        component="Diagnostic Analyte Component 13-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_118": ClinicalConcept_13(
        concept_id="CONCEPT_13_118",
        loinc_num="23118-1",
        snomed_ct="101300118",
        component="Diagnostic Analyte Component 13-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_119": ClinicalConcept_13(
        concept_id="CONCEPT_13_119",
        loinc_num="23119-2",
        snomed_ct="101300119",
        component="Diagnostic Analyte Component 13-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_120": ClinicalConcept_13(
        concept_id="CONCEPT_13_120",
        loinc_num="23120-3",
        snomed_ct="101300120",
        component="Diagnostic Analyte Component 13-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_121": ClinicalConcept_13(
        concept_id="CONCEPT_13_121",
        loinc_num="23121-4",
        snomed_ct="101300121",
        component="Diagnostic Analyte Component 13-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_122": ClinicalConcept_13(
        concept_id="CONCEPT_13_122",
        loinc_num="23122-5",
        snomed_ct="101300122",
        component="Diagnostic Analyte Component 13-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_123": ClinicalConcept_13(
        concept_id="CONCEPT_13_123",
        loinc_num="23123-6",
        snomed_ct="101300123",
        component="Diagnostic Analyte Component 13-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_124": ClinicalConcept_13(
        concept_id="CONCEPT_13_124",
        loinc_num="23124-7",
        snomed_ct="101300124",
        component="Diagnostic Analyte Component 13-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_125": ClinicalConcept_13(
        concept_id="CONCEPT_13_125",
        loinc_num="23125-8",
        snomed_ct="101300125",
        component="Diagnostic Analyte Component 13-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_126": ClinicalConcept_13(
        concept_id="CONCEPT_13_126",
        loinc_num="23126-0",
        snomed_ct="101300126",
        component="Diagnostic Analyte Component 13-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_127": ClinicalConcept_13(
        concept_id="CONCEPT_13_127",
        loinc_num="23127-1",
        snomed_ct="101300127",
        component="Diagnostic Analyte Component 13-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_128": ClinicalConcept_13(
        concept_id="CONCEPT_13_128",
        loinc_num="23128-2",
        snomed_ct="101300128",
        component="Diagnostic Analyte Component 13-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_129": ClinicalConcept_13(
        concept_id="CONCEPT_13_129",
        loinc_num="23129-3",
        snomed_ct="101300129",
        component="Diagnostic Analyte Component 13-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_130": ClinicalConcept_13(
        concept_id="CONCEPT_13_130",
        loinc_num="23130-4",
        snomed_ct="101300130",
        component="Diagnostic Analyte Component 13-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_131": ClinicalConcept_13(
        concept_id="CONCEPT_13_131",
        loinc_num="23131-5",
        snomed_ct="101300131",
        component="Diagnostic Analyte Component 13-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_132": ClinicalConcept_13(
        concept_id="CONCEPT_13_132",
        loinc_num="23132-6",
        snomed_ct="101300132",
        component="Diagnostic Analyte Component 13-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_133": ClinicalConcept_13(
        concept_id="CONCEPT_13_133",
        loinc_num="23133-7",
        snomed_ct="101300133",
        component="Diagnostic Analyte Component 13-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_134": ClinicalConcept_13(
        concept_id="CONCEPT_13_134",
        loinc_num="23134-8",
        snomed_ct="101300134",
        component="Diagnostic Analyte Component 13-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_135": ClinicalConcept_13(
        concept_id="CONCEPT_13_135",
        loinc_num="23135-0",
        snomed_ct="101300135",
        component="Diagnostic Analyte Component 13-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_136": ClinicalConcept_13(
        concept_id="CONCEPT_13_136",
        loinc_num="23136-1",
        snomed_ct="101300136",
        component="Diagnostic Analyte Component 13-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_137": ClinicalConcept_13(
        concept_id="CONCEPT_13_137",
        loinc_num="23137-2",
        snomed_ct="101300137",
        component="Diagnostic Analyte Component 13-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_138": ClinicalConcept_13(
        concept_id="CONCEPT_13_138",
        loinc_num="23138-3",
        snomed_ct="101300138",
        component="Diagnostic Analyte Component 13-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_139": ClinicalConcept_13(
        concept_id="CONCEPT_13_139",
        loinc_num="23139-4",
        snomed_ct="101300139",
        component="Diagnostic Analyte Component 13-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_140": ClinicalConcept_13(
        concept_id="CONCEPT_13_140",
        loinc_num="23140-5",
        snomed_ct="101300140",
        component="Diagnostic Analyte Component 13-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_141": ClinicalConcept_13(
        concept_id="CONCEPT_13_141",
        loinc_num="23141-6",
        snomed_ct="101300141",
        component="Diagnostic Analyte Component 13-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_142": ClinicalConcept_13(
        concept_id="CONCEPT_13_142",
        loinc_num="23142-7",
        snomed_ct="101300142",
        component="Diagnostic Analyte Component 13-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_143": ClinicalConcept_13(
        concept_id="CONCEPT_13_143",
        loinc_num="23143-8",
        snomed_ct="101300143",
        component="Diagnostic Analyte Component 13-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_144": ClinicalConcept_13(
        concept_id="CONCEPT_13_144",
        loinc_num="23144-0",
        snomed_ct="101300144",
        component="Diagnostic Analyte Component 13-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_145": ClinicalConcept_13(
        concept_id="CONCEPT_13_145",
        loinc_num="23145-1",
        snomed_ct="101300145",
        component="Diagnostic Analyte Component 13-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_146": ClinicalConcept_13(
        concept_id="CONCEPT_13_146",
        loinc_num="23146-2",
        snomed_ct="101300146",
        component="Diagnostic Analyte Component 13-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_147": ClinicalConcept_13(
        concept_id="CONCEPT_13_147",
        loinc_num="23147-3",
        snomed_ct="101300147",
        component="Diagnostic Analyte Component 13-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_148": ClinicalConcept_13(
        concept_id="CONCEPT_13_148",
        loinc_num="23148-4",
        snomed_ct="101300148",
        component="Diagnostic Analyte Component 13-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_149": ClinicalConcept_13(
        concept_id="CONCEPT_13_149",
        loinc_num="23149-5",
        snomed_ct="101300149",
        component="Diagnostic Analyte Component 13-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_150": ClinicalConcept_13(
        concept_id="CONCEPT_13_150",
        loinc_num="23150-6",
        snomed_ct="101300150",
        component="Diagnostic Analyte Component 13-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_151": ClinicalConcept_13(
        concept_id="CONCEPT_13_151",
        loinc_num="23151-7",
        snomed_ct="101300151",
        component="Diagnostic Analyte Component 13-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_152": ClinicalConcept_13(
        concept_id="CONCEPT_13_152",
        loinc_num="23152-8",
        snomed_ct="101300152",
        component="Diagnostic Analyte Component 13-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_153": ClinicalConcept_13(
        concept_id="CONCEPT_13_153",
        loinc_num="23153-0",
        snomed_ct="101300153",
        component="Diagnostic Analyte Component 13-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_154": ClinicalConcept_13(
        concept_id="CONCEPT_13_154",
        loinc_num="23154-1",
        snomed_ct="101300154",
        component="Diagnostic Analyte Component 13-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_155": ClinicalConcept_13(
        concept_id="CONCEPT_13_155",
        loinc_num="23155-2",
        snomed_ct="101300155",
        component="Diagnostic Analyte Component 13-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_156": ClinicalConcept_13(
        concept_id="CONCEPT_13_156",
        loinc_num="23156-3",
        snomed_ct="101300156",
        component="Diagnostic Analyte Component 13-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_157": ClinicalConcept_13(
        concept_id="CONCEPT_13_157",
        loinc_num="23157-4",
        snomed_ct="101300157",
        component="Diagnostic Analyte Component 13-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_158": ClinicalConcept_13(
        concept_id="CONCEPT_13_158",
        loinc_num="23158-5",
        snomed_ct="101300158",
        component="Diagnostic Analyte Component 13-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_159": ClinicalConcept_13(
        concept_id="CONCEPT_13_159",
        loinc_num="23159-6",
        snomed_ct="101300159",
        component="Diagnostic Analyte Component 13-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_160": ClinicalConcept_13(
        concept_id="CONCEPT_13_160",
        loinc_num="23160-7",
        snomed_ct="101300160",
        component="Diagnostic Analyte Component 13-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_161": ClinicalConcept_13(
        concept_id="CONCEPT_13_161",
        loinc_num="23161-8",
        snomed_ct="101300161",
        component="Diagnostic Analyte Component 13-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_162": ClinicalConcept_13(
        concept_id="CONCEPT_13_162",
        loinc_num="23162-0",
        snomed_ct="101300162",
        component="Diagnostic Analyte Component 13-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_163": ClinicalConcept_13(
        concept_id="CONCEPT_13_163",
        loinc_num="23163-1",
        snomed_ct="101300163",
        component="Diagnostic Analyte Component 13-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_164": ClinicalConcept_13(
        concept_id="CONCEPT_13_164",
        loinc_num="23164-2",
        snomed_ct="101300164",
        component="Diagnostic Analyte Component 13-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_165": ClinicalConcept_13(
        concept_id="CONCEPT_13_165",
        loinc_num="23165-3",
        snomed_ct="101300165",
        component="Diagnostic Analyte Component 13-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_166": ClinicalConcept_13(
        concept_id="CONCEPT_13_166",
        loinc_num="23166-4",
        snomed_ct="101300166",
        component="Diagnostic Analyte Component 13-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_167": ClinicalConcept_13(
        concept_id="CONCEPT_13_167",
        loinc_num="23167-5",
        snomed_ct="101300167",
        component="Diagnostic Analyte Component 13-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_168": ClinicalConcept_13(
        concept_id="CONCEPT_13_168",
        loinc_num="23168-6",
        snomed_ct="101300168",
        component="Diagnostic Analyte Component 13-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_169": ClinicalConcept_13(
        concept_id="CONCEPT_13_169",
        loinc_num="23169-7",
        snomed_ct="101300169",
        component="Diagnostic Analyte Component 13-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_170": ClinicalConcept_13(
        concept_id="CONCEPT_13_170",
        loinc_num="23170-8",
        snomed_ct="101300170",
        component="Diagnostic Analyte Component 13-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_171": ClinicalConcept_13(
        concept_id="CONCEPT_13_171",
        loinc_num="23171-0",
        snomed_ct="101300171",
        component="Diagnostic Analyte Component 13-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_172": ClinicalConcept_13(
        concept_id="CONCEPT_13_172",
        loinc_num="23172-1",
        snomed_ct="101300172",
        component="Diagnostic Analyte Component 13-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_173": ClinicalConcept_13(
        concept_id="CONCEPT_13_173",
        loinc_num="23173-2",
        snomed_ct="101300173",
        component="Diagnostic Analyte Component 13-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_174": ClinicalConcept_13(
        concept_id="CONCEPT_13_174",
        loinc_num="23174-3",
        snomed_ct="101300174",
        component="Diagnostic Analyte Component 13-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_175": ClinicalConcept_13(
        concept_id="CONCEPT_13_175",
        loinc_num="23175-4",
        snomed_ct="101300175",
        component="Diagnostic Analyte Component 13-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_176": ClinicalConcept_13(
        concept_id="CONCEPT_13_176",
        loinc_num="23176-5",
        snomed_ct="101300176",
        component="Diagnostic Analyte Component 13-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_177": ClinicalConcept_13(
        concept_id="CONCEPT_13_177",
        loinc_num="23177-6",
        snomed_ct="101300177",
        component="Diagnostic Analyte Component 13-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_178": ClinicalConcept_13(
        concept_id="CONCEPT_13_178",
        loinc_num="23178-7",
        snomed_ct="101300178",
        component="Diagnostic Analyte Component 13-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_179": ClinicalConcept_13(
        concept_id="CONCEPT_13_179",
        loinc_num="23179-8",
        snomed_ct="101300179",
        component="Diagnostic Analyte Component 13-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_180": ClinicalConcept_13(
        concept_id="CONCEPT_13_180",
        loinc_num="23180-0",
        snomed_ct="101300180",
        component="Diagnostic Analyte Component 13-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_181": ClinicalConcept_13(
        concept_id="CONCEPT_13_181",
        loinc_num="23181-1",
        snomed_ct="101300181",
        component="Diagnostic Analyte Component 13-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_182": ClinicalConcept_13(
        concept_id="CONCEPT_13_182",
        loinc_num="23182-2",
        snomed_ct="101300182",
        component="Diagnostic Analyte Component 13-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_183": ClinicalConcept_13(
        concept_id="CONCEPT_13_183",
        loinc_num="23183-3",
        snomed_ct="101300183",
        component="Diagnostic Analyte Component 13-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_184": ClinicalConcept_13(
        concept_id="CONCEPT_13_184",
        loinc_num="23184-4",
        snomed_ct="101300184",
        component="Diagnostic Analyte Component 13-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_185": ClinicalConcept_13(
        concept_id="CONCEPT_13_185",
        loinc_num="23185-5",
        snomed_ct="101300185",
        component="Diagnostic Analyte Component 13-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_186": ClinicalConcept_13(
        concept_id="CONCEPT_13_186",
        loinc_num="23186-6",
        snomed_ct="101300186",
        component="Diagnostic Analyte Component 13-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_187": ClinicalConcept_13(
        concept_id="CONCEPT_13_187",
        loinc_num="23187-7",
        snomed_ct="101300187",
        component="Diagnostic Analyte Component 13-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_188": ClinicalConcept_13(
        concept_id="CONCEPT_13_188",
        loinc_num="23188-8",
        snomed_ct="101300188",
        component="Diagnostic Analyte Component 13-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_189": ClinicalConcept_13(
        concept_id="CONCEPT_13_189",
        loinc_num="23189-0",
        snomed_ct="101300189",
        component="Diagnostic Analyte Component 13-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_190": ClinicalConcept_13(
        concept_id="CONCEPT_13_190",
        loinc_num="23190-1",
        snomed_ct="101300190",
        component="Diagnostic Analyte Component 13-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_191": ClinicalConcept_13(
        concept_id="CONCEPT_13_191",
        loinc_num="23191-2",
        snomed_ct="101300191",
        component="Diagnostic Analyte Component 13-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_192": ClinicalConcept_13(
        concept_id="CONCEPT_13_192",
        loinc_num="23192-3",
        snomed_ct="101300192",
        component="Diagnostic Analyte Component 13-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_193": ClinicalConcept_13(
        concept_id="CONCEPT_13_193",
        loinc_num="23193-4",
        snomed_ct="101300193",
        component="Diagnostic Analyte Component 13-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_194": ClinicalConcept_13(
        concept_id="CONCEPT_13_194",
        loinc_num="23194-5",
        snomed_ct="101300194",
        component="Diagnostic Analyte Component 13-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_195": ClinicalConcept_13(
        concept_id="CONCEPT_13_195",
        loinc_num="23195-6",
        snomed_ct="101300195",
        component="Diagnostic Analyte Component 13-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_196": ClinicalConcept_13(
        concept_id="CONCEPT_13_196",
        loinc_num="23196-7",
        snomed_ct="101300196",
        component="Diagnostic Analyte Component 13-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_197": ClinicalConcept_13(
        concept_id="CONCEPT_13_197",
        loinc_num="23197-8",
        snomed_ct="101300197",
        component="Diagnostic Analyte Component 13-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_198": ClinicalConcept_13(
        concept_id="CONCEPT_13_198",
        loinc_num="23198-0",
        snomed_ct="101300198",
        component="Diagnostic Analyte Component 13-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_13_199": ClinicalConcept_13(
        concept_id="CONCEPT_13_199",
        loinc_num="23199-1",
        snomed_ct="101300199",
        component="Diagnostic Analyte Component 13-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
