"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 16"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_16:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_16 = {
    "CONCEPT_16_001": ClinicalConcept_16(
        concept_id="CONCEPT_16_001",
        loinc_num="26001-1",
        snomed_ct="101600001",
        component="Diagnostic Analyte Component 16-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_002": ClinicalConcept_16(
        concept_id="CONCEPT_16_002",
        loinc_num="26002-2",
        snomed_ct="101600002",
        component="Diagnostic Analyte Component 16-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_003": ClinicalConcept_16(
        concept_id="CONCEPT_16_003",
        loinc_num="26003-3",
        snomed_ct="101600003",
        component="Diagnostic Analyte Component 16-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_004": ClinicalConcept_16(
        concept_id="CONCEPT_16_004",
        loinc_num="26004-4",
        snomed_ct="101600004",
        component="Diagnostic Analyte Component 16-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_005": ClinicalConcept_16(
        concept_id="CONCEPT_16_005",
        loinc_num="26005-5",
        snomed_ct="101600005",
        component="Diagnostic Analyte Component 16-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_006": ClinicalConcept_16(
        concept_id="CONCEPT_16_006",
        loinc_num="26006-6",
        snomed_ct="101600006",
        component="Diagnostic Analyte Component 16-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_007": ClinicalConcept_16(
        concept_id="CONCEPT_16_007",
        loinc_num="26007-7",
        snomed_ct="101600007",
        component="Diagnostic Analyte Component 16-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_008": ClinicalConcept_16(
        concept_id="CONCEPT_16_008",
        loinc_num="26008-8",
        snomed_ct="101600008",
        component="Diagnostic Analyte Component 16-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_009": ClinicalConcept_16(
        concept_id="CONCEPT_16_009",
        loinc_num="26009-0",
        snomed_ct="101600009",
        component="Diagnostic Analyte Component 16-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_010": ClinicalConcept_16(
        concept_id="CONCEPT_16_010",
        loinc_num="26010-1",
        snomed_ct="101600010",
        component="Diagnostic Analyte Component 16-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_011": ClinicalConcept_16(
        concept_id="CONCEPT_16_011",
        loinc_num="26011-2",
        snomed_ct="101600011",
        component="Diagnostic Analyte Component 16-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_012": ClinicalConcept_16(
        concept_id="CONCEPT_16_012",
        loinc_num="26012-3",
        snomed_ct="101600012",
        component="Diagnostic Analyte Component 16-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_013": ClinicalConcept_16(
        concept_id="CONCEPT_16_013",
        loinc_num="26013-4",
        snomed_ct="101600013",
        component="Diagnostic Analyte Component 16-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_014": ClinicalConcept_16(
        concept_id="CONCEPT_16_014",
        loinc_num="26014-5",
        snomed_ct="101600014",
        component="Diagnostic Analyte Component 16-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_015": ClinicalConcept_16(
        concept_id="CONCEPT_16_015",
        loinc_num="26015-6",
        snomed_ct="101600015",
        component="Diagnostic Analyte Component 16-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_016": ClinicalConcept_16(
        concept_id="CONCEPT_16_016",
        loinc_num="26016-7",
        snomed_ct="101600016",
        component="Diagnostic Analyte Component 16-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_017": ClinicalConcept_16(
        concept_id="CONCEPT_16_017",
        loinc_num="26017-8",
        snomed_ct="101600017",
        component="Diagnostic Analyte Component 16-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_018": ClinicalConcept_16(
        concept_id="CONCEPT_16_018",
        loinc_num="26018-0",
        snomed_ct="101600018",
        component="Diagnostic Analyte Component 16-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_019": ClinicalConcept_16(
        concept_id="CONCEPT_16_019",
        loinc_num="26019-1",
        snomed_ct="101600019",
        component="Diagnostic Analyte Component 16-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_020": ClinicalConcept_16(
        concept_id="CONCEPT_16_020",
        loinc_num="26020-2",
        snomed_ct="101600020",
        component="Diagnostic Analyte Component 16-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_021": ClinicalConcept_16(
        concept_id="CONCEPT_16_021",
        loinc_num="26021-3",
        snomed_ct="101600021",
        component="Diagnostic Analyte Component 16-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_022": ClinicalConcept_16(
        concept_id="CONCEPT_16_022",
        loinc_num="26022-4",
        snomed_ct="101600022",
        component="Diagnostic Analyte Component 16-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_023": ClinicalConcept_16(
        concept_id="CONCEPT_16_023",
        loinc_num="26023-5",
        snomed_ct="101600023",
        component="Diagnostic Analyte Component 16-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_024": ClinicalConcept_16(
        concept_id="CONCEPT_16_024",
        loinc_num="26024-6",
        snomed_ct="101600024",
        component="Diagnostic Analyte Component 16-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_025": ClinicalConcept_16(
        concept_id="CONCEPT_16_025",
        loinc_num="26025-7",
        snomed_ct="101600025",
        component="Diagnostic Analyte Component 16-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_026": ClinicalConcept_16(
        concept_id="CONCEPT_16_026",
        loinc_num="26026-8",
        snomed_ct="101600026",
        component="Diagnostic Analyte Component 16-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_027": ClinicalConcept_16(
        concept_id="CONCEPT_16_027",
        loinc_num="26027-0",
        snomed_ct="101600027",
        component="Diagnostic Analyte Component 16-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_028": ClinicalConcept_16(
        concept_id="CONCEPT_16_028",
        loinc_num="26028-1",
        snomed_ct="101600028",
        component="Diagnostic Analyte Component 16-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_029": ClinicalConcept_16(
        concept_id="CONCEPT_16_029",
        loinc_num="26029-2",
        snomed_ct="101600029",
        component="Diagnostic Analyte Component 16-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_030": ClinicalConcept_16(
        concept_id="CONCEPT_16_030",
        loinc_num="26030-3",
        snomed_ct="101600030",
        component="Diagnostic Analyte Component 16-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_031": ClinicalConcept_16(
        concept_id="CONCEPT_16_031",
        loinc_num="26031-4",
        snomed_ct="101600031",
        component="Diagnostic Analyte Component 16-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_032": ClinicalConcept_16(
        concept_id="CONCEPT_16_032",
        loinc_num="26032-5",
        snomed_ct="101600032",
        component="Diagnostic Analyte Component 16-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_033": ClinicalConcept_16(
        concept_id="CONCEPT_16_033",
        loinc_num="26033-6",
        snomed_ct="101600033",
        component="Diagnostic Analyte Component 16-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_034": ClinicalConcept_16(
        concept_id="CONCEPT_16_034",
        loinc_num="26034-7",
        snomed_ct="101600034",
        component="Diagnostic Analyte Component 16-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_035": ClinicalConcept_16(
        concept_id="CONCEPT_16_035",
        loinc_num="26035-8",
        snomed_ct="101600035",
        component="Diagnostic Analyte Component 16-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_036": ClinicalConcept_16(
        concept_id="CONCEPT_16_036",
        loinc_num="26036-0",
        snomed_ct="101600036",
        component="Diagnostic Analyte Component 16-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_037": ClinicalConcept_16(
        concept_id="CONCEPT_16_037",
        loinc_num="26037-1",
        snomed_ct="101600037",
        component="Diagnostic Analyte Component 16-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_038": ClinicalConcept_16(
        concept_id="CONCEPT_16_038",
        loinc_num="26038-2",
        snomed_ct="101600038",
        component="Diagnostic Analyte Component 16-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_039": ClinicalConcept_16(
        concept_id="CONCEPT_16_039",
        loinc_num="26039-3",
        snomed_ct="101600039",
        component="Diagnostic Analyte Component 16-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_040": ClinicalConcept_16(
        concept_id="CONCEPT_16_040",
        loinc_num="26040-4",
        snomed_ct="101600040",
        component="Diagnostic Analyte Component 16-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_041": ClinicalConcept_16(
        concept_id="CONCEPT_16_041",
        loinc_num="26041-5",
        snomed_ct="101600041",
        component="Diagnostic Analyte Component 16-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_042": ClinicalConcept_16(
        concept_id="CONCEPT_16_042",
        loinc_num="26042-6",
        snomed_ct="101600042",
        component="Diagnostic Analyte Component 16-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_043": ClinicalConcept_16(
        concept_id="CONCEPT_16_043",
        loinc_num="26043-7",
        snomed_ct="101600043",
        component="Diagnostic Analyte Component 16-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_044": ClinicalConcept_16(
        concept_id="CONCEPT_16_044",
        loinc_num="26044-8",
        snomed_ct="101600044",
        component="Diagnostic Analyte Component 16-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_045": ClinicalConcept_16(
        concept_id="CONCEPT_16_045",
        loinc_num="26045-0",
        snomed_ct="101600045",
        component="Diagnostic Analyte Component 16-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_046": ClinicalConcept_16(
        concept_id="CONCEPT_16_046",
        loinc_num="26046-1",
        snomed_ct="101600046",
        component="Diagnostic Analyte Component 16-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_047": ClinicalConcept_16(
        concept_id="CONCEPT_16_047",
        loinc_num="26047-2",
        snomed_ct="101600047",
        component="Diagnostic Analyte Component 16-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_048": ClinicalConcept_16(
        concept_id="CONCEPT_16_048",
        loinc_num="26048-3",
        snomed_ct="101600048",
        component="Diagnostic Analyte Component 16-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_049": ClinicalConcept_16(
        concept_id="CONCEPT_16_049",
        loinc_num="26049-4",
        snomed_ct="101600049",
        component="Diagnostic Analyte Component 16-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_050": ClinicalConcept_16(
        concept_id="CONCEPT_16_050",
        loinc_num="26050-5",
        snomed_ct="101600050",
        component="Diagnostic Analyte Component 16-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_051": ClinicalConcept_16(
        concept_id="CONCEPT_16_051",
        loinc_num="26051-6",
        snomed_ct="101600051",
        component="Diagnostic Analyte Component 16-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_052": ClinicalConcept_16(
        concept_id="CONCEPT_16_052",
        loinc_num="26052-7",
        snomed_ct="101600052",
        component="Diagnostic Analyte Component 16-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_053": ClinicalConcept_16(
        concept_id="CONCEPT_16_053",
        loinc_num="26053-8",
        snomed_ct="101600053",
        component="Diagnostic Analyte Component 16-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_054": ClinicalConcept_16(
        concept_id="CONCEPT_16_054",
        loinc_num="26054-0",
        snomed_ct="101600054",
        component="Diagnostic Analyte Component 16-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_055": ClinicalConcept_16(
        concept_id="CONCEPT_16_055",
        loinc_num="26055-1",
        snomed_ct="101600055",
        component="Diagnostic Analyte Component 16-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_056": ClinicalConcept_16(
        concept_id="CONCEPT_16_056",
        loinc_num="26056-2",
        snomed_ct="101600056",
        component="Diagnostic Analyte Component 16-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_057": ClinicalConcept_16(
        concept_id="CONCEPT_16_057",
        loinc_num="26057-3",
        snomed_ct="101600057",
        component="Diagnostic Analyte Component 16-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_058": ClinicalConcept_16(
        concept_id="CONCEPT_16_058",
        loinc_num="26058-4",
        snomed_ct="101600058",
        component="Diagnostic Analyte Component 16-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_059": ClinicalConcept_16(
        concept_id="CONCEPT_16_059",
        loinc_num="26059-5",
        snomed_ct="101600059",
        component="Diagnostic Analyte Component 16-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_060": ClinicalConcept_16(
        concept_id="CONCEPT_16_060",
        loinc_num="26060-6",
        snomed_ct="101600060",
        component="Diagnostic Analyte Component 16-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_061": ClinicalConcept_16(
        concept_id="CONCEPT_16_061",
        loinc_num="26061-7",
        snomed_ct="101600061",
        component="Diagnostic Analyte Component 16-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_062": ClinicalConcept_16(
        concept_id="CONCEPT_16_062",
        loinc_num="26062-8",
        snomed_ct="101600062",
        component="Diagnostic Analyte Component 16-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_063": ClinicalConcept_16(
        concept_id="CONCEPT_16_063",
        loinc_num="26063-0",
        snomed_ct="101600063",
        component="Diagnostic Analyte Component 16-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_064": ClinicalConcept_16(
        concept_id="CONCEPT_16_064",
        loinc_num="26064-1",
        snomed_ct="101600064",
        component="Diagnostic Analyte Component 16-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_065": ClinicalConcept_16(
        concept_id="CONCEPT_16_065",
        loinc_num="26065-2",
        snomed_ct="101600065",
        component="Diagnostic Analyte Component 16-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_066": ClinicalConcept_16(
        concept_id="CONCEPT_16_066",
        loinc_num="26066-3",
        snomed_ct="101600066",
        component="Diagnostic Analyte Component 16-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_067": ClinicalConcept_16(
        concept_id="CONCEPT_16_067",
        loinc_num="26067-4",
        snomed_ct="101600067",
        component="Diagnostic Analyte Component 16-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_068": ClinicalConcept_16(
        concept_id="CONCEPT_16_068",
        loinc_num="26068-5",
        snomed_ct="101600068",
        component="Diagnostic Analyte Component 16-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_069": ClinicalConcept_16(
        concept_id="CONCEPT_16_069",
        loinc_num="26069-6",
        snomed_ct="101600069",
        component="Diagnostic Analyte Component 16-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_070": ClinicalConcept_16(
        concept_id="CONCEPT_16_070",
        loinc_num="26070-7",
        snomed_ct="101600070",
        component="Diagnostic Analyte Component 16-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_071": ClinicalConcept_16(
        concept_id="CONCEPT_16_071",
        loinc_num="26071-8",
        snomed_ct="101600071",
        component="Diagnostic Analyte Component 16-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_072": ClinicalConcept_16(
        concept_id="CONCEPT_16_072",
        loinc_num="26072-0",
        snomed_ct="101600072",
        component="Diagnostic Analyte Component 16-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_073": ClinicalConcept_16(
        concept_id="CONCEPT_16_073",
        loinc_num="26073-1",
        snomed_ct="101600073",
        component="Diagnostic Analyte Component 16-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_074": ClinicalConcept_16(
        concept_id="CONCEPT_16_074",
        loinc_num="26074-2",
        snomed_ct="101600074",
        component="Diagnostic Analyte Component 16-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_075": ClinicalConcept_16(
        concept_id="CONCEPT_16_075",
        loinc_num="26075-3",
        snomed_ct="101600075",
        component="Diagnostic Analyte Component 16-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_076": ClinicalConcept_16(
        concept_id="CONCEPT_16_076",
        loinc_num="26076-4",
        snomed_ct="101600076",
        component="Diagnostic Analyte Component 16-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_077": ClinicalConcept_16(
        concept_id="CONCEPT_16_077",
        loinc_num="26077-5",
        snomed_ct="101600077",
        component="Diagnostic Analyte Component 16-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_078": ClinicalConcept_16(
        concept_id="CONCEPT_16_078",
        loinc_num="26078-6",
        snomed_ct="101600078",
        component="Diagnostic Analyte Component 16-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_079": ClinicalConcept_16(
        concept_id="CONCEPT_16_079",
        loinc_num="26079-7",
        snomed_ct="101600079",
        component="Diagnostic Analyte Component 16-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_080": ClinicalConcept_16(
        concept_id="CONCEPT_16_080",
        loinc_num="26080-8",
        snomed_ct="101600080",
        component="Diagnostic Analyte Component 16-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_081": ClinicalConcept_16(
        concept_id="CONCEPT_16_081",
        loinc_num="26081-0",
        snomed_ct="101600081",
        component="Diagnostic Analyte Component 16-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_082": ClinicalConcept_16(
        concept_id="CONCEPT_16_082",
        loinc_num="26082-1",
        snomed_ct="101600082",
        component="Diagnostic Analyte Component 16-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_083": ClinicalConcept_16(
        concept_id="CONCEPT_16_083",
        loinc_num="26083-2",
        snomed_ct="101600083",
        component="Diagnostic Analyte Component 16-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_084": ClinicalConcept_16(
        concept_id="CONCEPT_16_084",
        loinc_num="26084-3",
        snomed_ct="101600084",
        component="Diagnostic Analyte Component 16-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_085": ClinicalConcept_16(
        concept_id="CONCEPT_16_085",
        loinc_num="26085-4",
        snomed_ct="101600085",
        component="Diagnostic Analyte Component 16-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_086": ClinicalConcept_16(
        concept_id="CONCEPT_16_086",
        loinc_num="26086-5",
        snomed_ct="101600086",
        component="Diagnostic Analyte Component 16-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_087": ClinicalConcept_16(
        concept_id="CONCEPT_16_087",
        loinc_num="26087-6",
        snomed_ct="101600087",
        component="Diagnostic Analyte Component 16-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_088": ClinicalConcept_16(
        concept_id="CONCEPT_16_088",
        loinc_num="26088-7",
        snomed_ct="101600088",
        component="Diagnostic Analyte Component 16-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_089": ClinicalConcept_16(
        concept_id="CONCEPT_16_089",
        loinc_num="26089-8",
        snomed_ct="101600089",
        component="Diagnostic Analyte Component 16-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_090": ClinicalConcept_16(
        concept_id="CONCEPT_16_090",
        loinc_num="26090-0",
        snomed_ct="101600090",
        component="Diagnostic Analyte Component 16-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_091": ClinicalConcept_16(
        concept_id="CONCEPT_16_091",
        loinc_num="26091-1",
        snomed_ct="101600091",
        component="Diagnostic Analyte Component 16-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_092": ClinicalConcept_16(
        concept_id="CONCEPT_16_092",
        loinc_num="26092-2",
        snomed_ct="101600092",
        component="Diagnostic Analyte Component 16-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_093": ClinicalConcept_16(
        concept_id="CONCEPT_16_093",
        loinc_num="26093-3",
        snomed_ct="101600093",
        component="Diagnostic Analyte Component 16-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_094": ClinicalConcept_16(
        concept_id="CONCEPT_16_094",
        loinc_num="26094-4",
        snomed_ct="101600094",
        component="Diagnostic Analyte Component 16-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_095": ClinicalConcept_16(
        concept_id="CONCEPT_16_095",
        loinc_num="26095-5",
        snomed_ct="101600095",
        component="Diagnostic Analyte Component 16-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_096": ClinicalConcept_16(
        concept_id="CONCEPT_16_096",
        loinc_num="26096-6",
        snomed_ct="101600096",
        component="Diagnostic Analyte Component 16-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_097": ClinicalConcept_16(
        concept_id="CONCEPT_16_097",
        loinc_num="26097-7",
        snomed_ct="101600097",
        component="Diagnostic Analyte Component 16-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_098": ClinicalConcept_16(
        concept_id="CONCEPT_16_098",
        loinc_num="26098-8",
        snomed_ct="101600098",
        component="Diagnostic Analyte Component 16-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_099": ClinicalConcept_16(
        concept_id="CONCEPT_16_099",
        loinc_num="26099-0",
        snomed_ct="101600099",
        component="Diagnostic Analyte Component 16-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_100": ClinicalConcept_16(
        concept_id="CONCEPT_16_100",
        loinc_num="26100-1",
        snomed_ct="101600100",
        component="Diagnostic Analyte Component 16-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_101": ClinicalConcept_16(
        concept_id="CONCEPT_16_101",
        loinc_num="26101-2",
        snomed_ct="101600101",
        component="Diagnostic Analyte Component 16-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_102": ClinicalConcept_16(
        concept_id="CONCEPT_16_102",
        loinc_num="26102-3",
        snomed_ct="101600102",
        component="Diagnostic Analyte Component 16-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_103": ClinicalConcept_16(
        concept_id="CONCEPT_16_103",
        loinc_num="26103-4",
        snomed_ct="101600103",
        component="Diagnostic Analyte Component 16-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_104": ClinicalConcept_16(
        concept_id="CONCEPT_16_104",
        loinc_num="26104-5",
        snomed_ct="101600104",
        component="Diagnostic Analyte Component 16-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_105": ClinicalConcept_16(
        concept_id="CONCEPT_16_105",
        loinc_num="26105-6",
        snomed_ct="101600105",
        component="Diagnostic Analyte Component 16-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_106": ClinicalConcept_16(
        concept_id="CONCEPT_16_106",
        loinc_num="26106-7",
        snomed_ct="101600106",
        component="Diagnostic Analyte Component 16-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_107": ClinicalConcept_16(
        concept_id="CONCEPT_16_107",
        loinc_num="26107-8",
        snomed_ct="101600107",
        component="Diagnostic Analyte Component 16-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_108": ClinicalConcept_16(
        concept_id="CONCEPT_16_108",
        loinc_num="26108-0",
        snomed_ct="101600108",
        component="Diagnostic Analyte Component 16-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_109": ClinicalConcept_16(
        concept_id="CONCEPT_16_109",
        loinc_num="26109-1",
        snomed_ct="101600109",
        component="Diagnostic Analyte Component 16-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_110": ClinicalConcept_16(
        concept_id="CONCEPT_16_110",
        loinc_num="26110-2",
        snomed_ct="101600110",
        component="Diagnostic Analyte Component 16-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_111": ClinicalConcept_16(
        concept_id="CONCEPT_16_111",
        loinc_num="26111-3",
        snomed_ct="101600111",
        component="Diagnostic Analyte Component 16-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_112": ClinicalConcept_16(
        concept_id="CONCEPT_16_112",
        loinc_num="26112-4",
        snomed_ct="101600112",
        component="Diagnostic Analyte Component 16-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_113": ClinicalConcept_16(
        concept_id="CONCEPT_16_113",
        loinc_num="26113-5",
        snomed_ct="101600113",
        component="Diagnostic Analyte Component 16-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_114": ClinicalConcept_16(
        concept_id="CONCEPT_16_114",
        loinc_num="26114-6",
        snomed_ct="101600114",
        component="Diagnostic Analyte Component 16-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_115": ClinicalConcept_16(
        concept_id="CONCEPT_16_115",
        loinc_num="26115-7",
        snomed_ct="101600115",
        component="Diagnostic Analyte Component 16-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_116": ClinicalConcept_16(
        concept_id="CONCEPT_16_116",
        loinc_num="26116-8",
        snomed_ct="101600116",
        component="Diagnostic Analyte Component 16-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_117": ClinicalConcept_16(
        concept_id="CONCEPT_16_117",
        loinc_num="26117-0",
        snomed_ct="101600117",
        component="Diagnostic Analyte Component 16-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_118": ClinicalConcept_16(
        concept_id="CONCEPT_16_118",
        loinc_num="26118-1",
        snomed_ct="101600118",
        component="Diagnostic Analyte Component 16-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_119": ClinicalConcept_16(
        concept_id="CONCEPT_16_119",
        loinc_num="26119-2",
        snomed_ct="101600119",
        component="Diagnostic Analyte Component 16-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_120": ClinicalConcept_16(
        concept_id="CONCEPT_16_120",
        loinc_num="26120-3",
        snomed_ct="101600120",
        component="Diagnostic Analyte Component 16-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_121": ClinicalConcept_16(
        concept_id="CONCEPT_16_121",
        loinc_num="26121-4",
        snomed_ct="101600121",
        component="Diagnostic Analyte Component 16-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_122": ClinicalConcept_16(
        concept_id="CONCEPT_16_122",
        loinc_num="26122-5",
        snomed_ct="101600122",
        component="Diagnostic Analyte Component 16-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_123": ClinicalConcept_16(
        concept_id="CONCEPT_16_123",
        loinc_num="26123-6",
        snomed_ct="101600123",
        component="Diagnostic Analyte Component 16-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_124": ClinicalConcept_16(
        concept_id="CONCEPT_16_124",
        loinc_num="26124-7",
        snomed_ct="101600124",
        component="Diagnostic Analyte Component 16-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_125": ClinicalConcept_16(
        concept_id="CONCEPT_16_125",
        loinc_num="26125-8",
        snomed_ct="101600125",
        component="Diagnostic Analyte Component 16-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_126": ClinicalConcept_16(
        concept_id="CONCEPT_16_126",
        loinc_num="26126-0",
        snomed_ct="101600126",
        component="Diagnostic Analyte Component 16-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_127": ClinicalConcept_16(
        concept_id="CONCEPT_16_127",
        loinc_num="26127-1",
        snomed_ct="101600127",
        component="Diagnostic Analyte Component 16-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_128": ClinicalConcept_16(
        concept_id="CONCEPT_16_128",
        loinc_num="26128-2",
        snomed_ct="101600128",
        component="Diagnostic Analyte Component 16-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_129": ClinicalConcept_16(
        concept_id="CONCEPT_16_129",
        loinc_num="26129-3",
        snomed_ct="101600129",
        component="Diagnostic Analyte Component 16-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_130": ClinicalConcept_16(
        concept_id="CONCEPT_16_130",
        loinc_num="26130-4",
        snomed_ct="101600130",
        component="Diagnostic Analyte Component 16-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_131": ClinicalConcept_16(
        concept_id="CONCEPT_16_131",
        loinc_num="26131-5",
        snomed_ct="101600131",
        component="Diagnostic Analyte Component 16-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_132": ClinicalConcept_16(
        concept_id="CONCEPT_16_132",
        loinc_num="26132-6",
        snomed_ct="101600132",
        component="Diagnostic Analyte Component 16-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_133": ClinicalConcept_16(
        concept_id="CONCEPT_16_133",
        loinc_num="26133-7",
        snomed_ct="101600133",
        component="Diagnostic Analyte Component 16-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_134": ClinicalConcept_16(
        concept_id="CONCEPT_16_134",
        loinc_num="26134-8",
        snomed_ct="101600134",
        component="Diagnostic Analyte Component 16-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_135": ClinicalConcept_16(
        concept_id="CONCEPT_16_135",
        loinc_num="26135-0",
        snomed_ct="101600135",
        component="Diagnostic Analyte Component 16-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_136": ClinicalConcept_16(
        concept_id="CONCEPT_16_136",
        loinc_num="26136-1",
        snomed_ct="101600136",
        component="Diagnostic Analyte Component 16-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_137": ClinicalConcept_16(
        concept_id="CONCEPT_16_137",
        loinc_num="26137-2",
        snomed_ct="101600137",
        component="Diagnostic Analyte Component 16-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_138": ClinicalConcept_16(
        concept_id="CONCEPT_16_138",
        loinc_num="26138-3",
        snomed_ct="101600138",
        component="Diagnostic Analyte Component 16-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_139": ClinicalConcept_16(
        concept_id="CONCEPT_16_139",
        loinc_num="26139-4",
        snomed_ct="101600139",
        component="Diagnostic Analyte Component 16-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_140": ClinicalConcept_16(
        concept_id="CONCEPT_16_140",
        loinc_num="26140-5",
        snomed_ct="101600140",
        component="Diagnostic Analyte Component 16-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_141": ClinicalConcept_16(
        concept_id="CONCEPT_16_141",
        loinc_num="26141-6",
        snomed_ct="101600141",
        component="Diagnostic Analyte Component 16-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_142": ClinicalConcept_16(
        concept_id="CONCEPT_16_142",
        loinc_num="26142-7",
        snomed_ct="101600142",
        component="Diagnostic Analyte Component 16-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_143": ClinicalConcept_16(
        concept_id="CONCEPT_16_143",
        loinc_num="26143-8",
        snomed_ct="101600143",
        component="Diagnostic Analyte Component 16-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_144": ClinicalConcept_16(
        concept_id="CONCEPT_16_144",
        loinc_num="26144-0",
        snomed_ct="101600144",
        component="Diagnostic Analyte Component 16-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_145": ClinicalConcept_16(
        concept_id="CONCEPT_16_145",
        loinc_num="26145-1",
        snomed_ct="101600145",
        component="Diagnostic Analyte Component 16-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_146": ClinicalConcept_16(
        concept_id="CONCEPT_16_146",
        loinc_num="26146-2",
        snomed_ct="101600146",
        component="Diagnostic Analyte Component 16-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_147": ClinicalConcept_16(
        concept_id="CONCEPT_16_147",
        loinc_num="26147-3",
        snomed_ct="101600147",
        component="Diagnostic Analyte Component 16-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_148": ClinicalConcept_16(
        concept_id="CONCEPT_16_148",
        loinc_num="26148-4",
        snomed_ct="101600148",
        component="Diagnostic Analyte Component 16-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_149": ClinicalConcept_16(
        concept_id="CONCEPT_16_149",
        loinc_num="26149-5",
        snomed_ct="101600149",
        component="Diagnostic Analyte Component 16-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_150": ClinicalConcept_16(
        concept_id="CONCEPT_16_150",
        loinc_num="26150-6",
        snomed_ct="101600150",
        component="Diagnostic Analyte Component 16-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_151": ClinicalConcept_16(
        concept_id="CONCEPT_16_151",
        loinc_num="26151-7",
        snomed_ct="101600151",
        component="Diagnostic Analyte Component 16-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_152": ClinicalConcept_16(
        concept_id="CONCEPT_16_152",
        loinc_num="26152-8",
        snomed_ct="101600152",
        component="Diagnostic Analyte Component 16-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_153": ClinicalConcept_16(
        concept_id="CONCEPT_16_153",
        loinc_num="26153-0",
        snomed_ct="101600153",
        component="Diagnostic Analyte Component 16-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_154": ClinicalConcept_16(
        concept_id="CONCEPT_16_154",
        loinc_num="26154-1",
        snomed_ct="101600154",
        component="Diagnostic Analyte Component 16-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_155": ClinicalConcept_16(
        concept_id="CONCEPT_16_155",
        loinc_num="26155-2",
        snomed_ct="101600155",
        component="Diagnostic Analyte Component 16-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_156": ClinicalConcept_16(
        concept_id="CONCEPT_16_156",
        loinc_num="26156-3",
        snomed_ct="101600156",
        component="Diagnostic Analyte Component 16-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_157": ClinicalConcept_16(
        concept_id="CONCEPT_16_157",
        loinc_num="26157-4",
        snomed_ct="101600157",
        component="Diagnostic Analyte Component 16-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_158": ClinicalConcept_16(
        concept_id="CONCEPT_16_158",
        loinc_num="26158-5",
        snomed_ct="101600158",
        component="Diagnostic Analyte Component 16-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_159": ClinicalConcept_16(
        concept_id="CONCEPT_16_159",
        loinc_num="26159-6",
        snomed_ct="101600159",
        component="Diagnostic Analyte Component 16-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_160": ClinicalConcept_16(
        concept_id="CONCEPT_16_160",
        loinc_num="26160-7",
        snomed_ct="101600160",
        component="Diagnostic Analyte Component 16-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_161": ClinicalConcept_16(
        concept_id="CONCEPT_16_161",
        loinc_num="26161-8",
        snomed_ct="101600161",
        component="Diagnostic Analyte Component 16-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_162": ClinicalConcept_16(
        concept_id="CONCEPT_16_162",
        loinc_num="26162-0",
        snomed_ct="101600162",
        component="Diagnostic Analyte Component 16-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_163": ClinicalConcept_16(
        concept_id="CONCEPT_16_163",
        loinc_num="26163-1",
        snomed_ct="101600163",
        component="Diagnostic Analyte Component 16-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_164": ClinicalConcept_16(
        concept_id="CONCEPT_16_164",
        loinc_num="26164-2",
        snomed_ct="101600164",
        component="Diagnostic Analyte Component 16-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_165": ClinicalConcept_16(
        concept_id="CONCEPT_16_165",
        loinc_num="26165-3",
        snomed_ct="101600165",
        component="Diagnostic Analyte Component 16-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_166": ClinicalConcept_16(
        concept_id="CONCEPT_16_166",
        loinc_num="26166-4",
        snomed_ct="101600166",
        component="Diagnostic Analyte Component 16-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_167": ClinicalConcept_16(
        concept_id="CONCEPT_16_167",
        loinc_num="26167-5",
        snomed_ct="101600167",
        component="Diagnostic Analyte Component 16-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_168": ClinicalConcept_16(
        concept_id="CONCEPT_16_168",
        loinc_num="26168-6",
        snomed_ct="101600168",
        component="Diagnostic Analyte Component 16-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_169": ClinicalConcept_16(
        concept_id="CONCEPT_16_169",
        loinc_num="26169-7",
        snomed_ct="101600169",
        component="Diagnostic Analyte Component 16-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_170": ClinicalConcept_16(
        concept_id="CONCEPT_16_170",
        loinc_num="26170-8",
        snomed_ct="101600170",
        component="Diagnostic Analyte Component 16-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_171": ClinicalConcept_16(
        concept_id="CONCEPT_16_171",
        loinc_num="26171-0",
        snomed_ct="101600171",
        component="Diagnostic Analyte Component 16-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_172": ClinicalConcept_16(
        concept_id="CONCEPT_16_172",
        loinc_num="26172-1",
        snomed_ct="101600172",
        component="Diagnostic Analyte Component 16-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_173": ClinicalConcept_16(
        concept_id="CONCEPT_16_173",
        loinc_num="26173-2",
        snomed_ct="101600173",
        component="Diagnostic Analyte Component 16-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_174": ClinicalConcept_16(
        concept_id="CONCEPT_16_174",
        loinc_num="26174-3",
        snomed_ct="101600174",
        component="Diagnostic Analyte Component 16-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_175": ClinicalConcept_16(
        concept_id="CONCEPT_16_175",
        loinc_num="26175-4",
        snomed_ct="101600175",
        component="Diagnostic Analyte Component 16-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_176": ClinicalConcept_16(
        concept_id="CONCEPT_16_176",
        loinc_num="26176-5",
        snomed_ct="101600176",
        component="Diagnostic Analyte Component 16-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_177": ClinicalConcept_16(
        concept_id="CONCEPT_16_177",
        loinc_num="26177-6",
        snomed_ct="101600177",
        component="Diagnostic Analyte Component 16-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_178": ClinicalConcept_16(
        concept_id="CONCEPT_16_178",
        loinc_num="26178-7",
        snomed_ct="101600178",
        component="Diagnostic Analyte Component 16-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_179": ClinicalConcept_16(
        concept_id="CONCEPT_16_179",
        loinc_num="26179-8",
        snomed_ct="101600179",
        component="Diagnostic Analyte Component 16-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_180": ClinicalConcept_16(
        concept_id="CONCEPT_16_180",
        loinc_num="26180-0",
        snomed_ct="101600180",
        component="Diagnostic Analyte Component 16-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_181": ClinicalConcept_16(
        concept_id="CONCEPT_16_181",
        loinc_num="26181-1",
        snomed_ct="101600181",
        component="Diagnostic Analyte Component 16-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_182": ClinicalConcept_16(
        concept_id="CONCEPT_16_182",
        loinc_num="26182-2",
        snomed_ct="101600182",
        component="Diagnostic Analyte Component 16-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_183": ClinicalConcept_16(
        concept_id="CONCEPT_16_183",
        loinc_num="26183-3",
        snomed_ct="101600183",
        component="Diagnostic Analyte Component 16-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_184": ClinicalConcept_16(
        concept_id="CONCEPT_16_184",
        loinc_num="26184-4",
        snomed_ct="101600184",
        component="Diagnostic Analyte Component 16-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_185": ClinicalConcept_16(
        concept_id="CONCEPT_16_185",
        loinc_num="26185-5",
        snomed_ct="101600185",
        component="Diagnostic Analyte Component 16-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_186": ClinicalConcept_16(
        concept_id="CONCEPT_16_186",
        loinc_num="26186-6",
        snomed_ct="101600186",
        component="Diagnostic Analyte Component 16-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_187": ClinicalConcept_16(
        concept_id="CONCEPT_16_187",
        loinc_num="26187-7",
        snomed_ct="101600187",
        component="Diagnostic Analyte Component 16-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_188": ClinicalConcept_16(
        concept_id="CONCEPT_16_188",
        loinc_num="26188-8",
        snomed_ct="101600188",
        component="Diagnostic Analyte Component 16-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_189": ClinicalConcept_16(
        concept_id="CONCEPT_16_189",
        loinc_num="26189-0",
        snomed_ct="101600189",
        component="Diagnostic Analyte Component 16-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_190": ClinicalConcept_16(
        concept_id="CONCEPT_16_190",
        loinc_num="26190-1",
        snomed_ct="101600190",
        component="Diagnostic Analyte Component 16-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_191": ClinicalConcept_16(
        concept_id="CONCEPT_16_191",
        loinc_num="26191-2",
        snomed_ct="101600191",
        component="Diagnostic Analyte Component 16-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_192": ClinicalConcept_16(
        concept_id="CONCEPT_16_192",
        loinc_num="26192-3",
        snomed_ct="101600192",
        component="Diagnostic Analyte Component 16-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_193": ClinicalConcept_16(
        concept_id="CONCEPT_16_193",
        loinc_num="26193-4",
        snomed_ct="101600193",
        component="Diagnostic Analyte Component 16-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_194": ClinicalConcept_16(
        concept_id="CONCEPT_16_194",
        loinc_num="26194-5",
        snomed_ct="101600194",
        component="Diagnostic Analyte Component 16-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_195": ClinicalConcept_16(
        concept_id="CONCEPT_16_195",
        loinc_num="26195-6",
        snomed_ct="101600195",
        component="Diagnostic Analyte Component 16-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_196": ClinicalConcept_16(
        concept_id="CONCEPT_16_196",
        loinc_num="26196-7",
        snomed_ct="101600196",
        component="Diagnostic Analyte Component 16-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_197": ClinicalConcept_16(
        concept_id="CONCEPT_16_197",
        loinc_num="26197-8",
        snomed_ct="101600197",
        component="Diagnostic Analyte Component 16-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_198": ClinicalConcept_16(
        concept_id="CONCEPT_16_198",
        loinc_num="26198-0",
        snomed_ct="101600198",
        component="Diagnostic Analyte Component 16-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_16_199": ClinicalConcept_16(
        concept_id="CONCEPT_16_199",
        loinc_num="26199-1",
        snomed_ct="101600199",
        component="Diagnostic Analyte Component 16-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
