"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 05"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_05:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_05 = {
    "CONCEPT_05_001": ClinicalConcept_05(
        concept_id="CONCEPT_05_001",
        loinc_num="15001-1",
        snomed_ct="100500001",
        component="Diagnostic Analyte Component 05-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_002": ClinicalConcept_05(
        concept_id="CONCEPT_05_002",
        loinc_num="15002-2",
        snomed_ct="100500002",
        component="Diagnostic Analyte Component 05-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_003": ClinicalConcept_05(
        concept_id="CONCEPT_05_003",
        loinc_num="15003-3",
        snomed_ct="100500003",
        component="Diagnostic Analyte Component 05-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_004": ClinicalConcept_05(
        concept_id="CONCEPT_05_004",
        loinc_num="15004-4",
        snomed_ct="100500004",
        component="Diagnostic Analyte Component 05-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_005": ClinicalConcept_05(
        concept_id="CONCEPT_05_005",
        loinc_num="15005-5",
        snomed_ct="100500005",
        component="Diagnostic Analyte Component 05-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_006": ClinicalConcept_05(
        concept_id="CONCEPT_05_006",
        loinc_num="15006-6",
        snomed_ct="100500006",
        component="Diagnostic Analyte Component 05-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_007": ClinicalConcept_05(
        concept_id="CONCEPT_05_007",
        loinc_num="15007-7",
        snomed_ct="100500007",
        component="Diagnostic Analyte Component 05-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_008": ClinicalConcept_05(
        concept_id="CONCEPT_05_008",
        loinc_num="15008-8",
        snomed_ct="100500008",
        component="Diagnostic Analyte Component 05-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_009": ClinicalConcept_05(
        concept_id="CONCEPT_05_009",
        loinc_num="15009-0",
        snomed_ct="100500009",
        component="Diagnostic Analyte Component 05-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_010": ClinicalConcept_05(
        concept_id="CONCEPT_05_010",
        loinc_num="15010-1",
        snomed_ct="100500010",
        component="Diagnostic Analyte Component 05-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_011": ClinicalConcept_05(
        concept_id="CONCEPT_05_011",
        loinc_num="15011-2",
        snomed_ct="100500011",
        component="Diagnostic Analyte Component 05-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_012": ClinicalConcept_05(
        concept_id="CONCEPT_05_012",
        loinc_num="15012-3",
        snomed_ct="100500012",
        component="Diagnostic Analyte Component 05-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_013": ClinicalConcept_05(
        concept_id="CONCEPT_05_013",
        loinc_num="15013-4",
        snomed_ct="100500013",
        component="Diagnostic Analyte Component 05-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_014": ClinicalConcept_05(
        concept_id="CONCEPT_05_014",
        loinc_num="15014-5",
        snomed_ct="100500014",
        component="Diagnostic Analyte Component 05-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_015": ClinicalConcept_05(
        concept_id="CONCEPT_05_015",
        loinc_num="15015-6",
        snomed_ct="100500015",
        component="Diagnostic Analyte Component 05-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_016": ClinicalConcept_05(
        concept_id="CONCEPT_05_016",
        loinc_num="15016-7",
        snomed_ct="100500016",
        component="Diagnostic Analyte Component 05-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_017": ClinicalConcept_05(
        concept_id="CONCEPT_05_017",
        loinc_num="15017-8",
        snomed_ct="100500017",
        component="Diagnostic Analyte Component 05-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_018": ClinicalConcept_05(
        concept_id="CONCEPT_05_018",
        loinc_num="15018-0",
        snomed_ct="100500018",
        component="Diagnostic Analyte Component 05-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_019": ClinicalConcept_05(
        concept_id="CONCEPT_05_019",
        loinc_num="15019-1",
        snomed_ct="100500019",
        component="Diagnostic Analyte Component 05-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_020": ClinicalConcept_05(
        concept_id="CONCEPT_05_020",
        loinc_num="15020-2",
        snomed_ct="100500020",
        component="Diagnostic Analyte Component 05-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_021": ClinicalConcept_05(
        concept_id="CONCEPT_05_021",
        loinc_num="15021-3",
        snomed_ct="100500021",
        component="Diagnostic Analyte Component 05-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_022": ClinicalConcept_05(
        concept_id="CONCEPT_05_022",
        loinc_num="15022-4",
        snomed_ct="100500022",
        component="Diagnostic Analyte Component 05-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_023": ClinicalConcept_05(
        concept_id="CONCEPT_05_023",
        loinc_num="15023-5",
        snomed_ct="100500023",
        component="Diagnostic Analyte Component 05-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_024": ClinicalConcept_05(
        concept_id="CONCEPT_05_024",
        loinc_num="15024-6",
        snomed_ct="100500024",
        component="Diagnostic Analyte Component 05-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_025": ClinicalConcept_05(
        concept_id="CONCEPT_05_025",
        loinc_num="15025-7",
        snomed_ct="100500025",
        component="Diagnostic Analyte Component 05-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_026": ClinicalConcept_05(
        concept_id="CONCEPT_05_026",
        loinc_num="15026-8",
        snomed_ct="100500026",
        component="Diagnostic Analyte Component 05-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_027": ClinicalConcept_05(
        concept_id="CONCEPT_05_027",
        loinc_num="15027-0",
        snomed_ct="100500027",
        component="Diagnostic Analyte Component 05-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_028": ClinicalConcept_05(
        concept_id="CONCEPT_05_028",
        loinc_num="15028-1",
        snomed_ct="100500028",
        component="Diagnostic Analyte Component 05-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_029": ClinicalConcept_05(
        concept_id="CONCEPT_05_029",
        loinc_num="15029-2",
        snomed_ct="100500029",
        component="Diagnostic Analyte Component 05-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_030": ClinicalConcept_05(
        concept_id="CONCEPT_05_030",
        loinc_num="15030-3",
        snomed_ct="100500030",
        component="Diagnostic Analyte Component 05-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_031": ClinicalConcept_05(
        concept_id="CONCEPT_05_031",
        loinc_num="15031-4",
        snomed_ct="100500031",
        component="Diagnostic Analyte Component 05-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_032": ClinicalConcept_05(
        concept_id="CONCEPT_05_032",
        loinc_num="15032-5",
        snomed_ct="100500032",
        component="Diagnostic Analyte Component 05-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_033": ClinicalConcept_05(
        concept_id="CONCEPT_05_033",
        loinc_num="15033-6",
        snomed_ct="100500033",
        component="Diagnostic Analyte Component 05-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_034": ClinicalConcept_05(
        concept_id="CONCEPT_05_034",
        loinc_num="15034-7",
        snomed_ct="100500034",
        component="Diagnostic Analyte Component 05-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_035": ClinicalConcept_05(
        concept_id="CONCEPT_05_035",
        loinc_num="15035-8",
        snomed_ct="100500035",
        component="Diagnostic Analyte Component 05-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_036": ClinicalConcept_05(
        concept_id="CONCEPT_05_036",
        loinc_num="15036-0",
        snomed_ct="100500036",
        component="Diagnostic Analyte Component 05-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_037": ClinicalConcept_05(
        concept_id="CONCEPT_05_037",
        loinc_num="15037-1",
        snomed_ct="100500037",
        component="Diagnostic Analyte Component 05-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_038": ClinicalConcept_05(
        concept_id="CONCEPT_05_038",
        loinc_num="15038-2",
        snomed_ct="100500038",
        component="Diagnostic Analyte Component 05-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_039": ClinicalConcept_05(
        concept_id="CONCEPT_05_039",
        loinc_num="15039-3",
        snomed_ct="100500039",
        component="Diagnostic Analyte Component 05-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_040": ClinicalConcept_05(
        concept_id="CONCEPT_05_040",
        loinc_num="15040-4",
        snomed_ct="100500040",
        component="Diagnostic Analyte Component 05-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_041": ClinicalConcept_05(
        concept_id="CONCEPT_05_041",
        loinc_num="15041-5",
        snomed_ct="100500041",
        component="Diagnostic Analyte Component 05-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_042": ClinicalConcept_05(
        concept_id="CONCEPT_05_042",
        loinc_num="15042-6",
        snomed_ct="100500042",
        component="Diagnostic Analyte Component 05-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_043": ClinicalConcept_05(
        concept_id="CONCEPT_05_043",
        loinc_num="15043-7",
        snomed_ct="100500043",
        component="Diagnostic Analyte Component 05-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_044": ClinicalConcept_05(
        concept_id="CONCEPT_05_044",
        loinc_num="15044-8",
        snomed_ct="100500044",
        component="Diagnostic Analyte Component 05-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_045": ClinicalConcept_05(
        concept_id="CONCEPT_05_045",
        loinc_num="15045-0",
        snomed_ct="100500045",
        component="Diagnostic Analyte Component 05-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_046": ClinicalConcept_05(
        concept_id="CONCEPT_05_046",
        loinc_num="15046-1",
        snomed_ct="100500046",
        component="Diagnostic Analyte Component 05-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_047": ClinicalConcept_05(
        concept_id="CONCEPT_05_047",
        loinc_num="15047-2",
        snomed_ct="100500047",
        component="Diagnostic Analyte Component 05-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_048": ClinicalConcept_05(
        concept_id="CONCEPT_05_048",
        loinc_num="15048-3",
        snomed_ct="100500048",
        component="Diagnostic Analyte Component 05-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_049": ClinicalConcept_05(
        concept_id="CONCEPT_05_049",
        loinc_num="15049-4",
        snomed_ct="100500049",
        component="Diagnostic Analyte Component 05-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_050": ClinicalConcept_05(
        concept_id="CONCEPT_05_050",
        loinc_num="15050-5",
        snomed_ct="100500050",
        component="Diagnostic Analyte Component 05-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_051": ClinicalConcept_05(
        concept_id="CONCEPT_05_051",
        loinc_num="15051-6",
        snomed_ct="100500051",
        component="Diagnostic Analyte Component 05-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_052": ClinicalConcept_05(
        concept_id="CONCEPT_05_052",
        loinc_num="15052-7",
        snomed_ct="100500052",
        component="Diagnostic Analyte Component 05-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_053": ClinicalConcept_05(
        concept_id="CONCEPT_05_053",
        loinc_num="15053-8",
        snomed_ct="100500053",
        component="Diagnostic Analyte Component 05-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_054": ClinicalConcept_05(
        concept_id="CONCEPT_05_054",
        loinc_num="15054-0",
        snomed_ct="100500054",
        component="Diagnostic Analyte Component 05-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_055": ClinicalConcept_05(
        concept_id="CONCEPT_05_055",
        loinc_num="15055-1",
        snomed_ct="100500055",
        component="Diagnostic Analyte Component 05-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_056": ClinicalConcept_05(
        concept_id="CONCEPT_05_056",
        loinc_num="15056-2",
        snomed_ct="100500056",
        component="Diagnostic Analyte Component 05-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_057": ClinicalConcept_05(
        concept_id="CONCEPT_05_057",
        loinc_num="15057-3",
        snomed_ct="100500057",
        component="Diagnostic Analyte Component 05-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_058": ClinicalConcept_05(
        concept_id="CONCEPT_05_058",
        loinc_num="15058-4",
        snomed_ct="100500058",
        component="Diagnostic Analyte Component 05-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_059": ClinicalConcept_05(
        concept_id="CONCEPT_05_059",
        loinc_num="15059-5",
        snomed_ct="100500059",
        component="Diagnostic Analyte Component 05-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_060": ClinicalConcept_05(
        concept_id="CONCEPT_05_060",
        loinc_num="15060-6",
        snomed_ct="100500060",
        component="Diagnostic Analyte Component 05-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_061": ClinicalConcept_05(
        concept_id="CONCEPT_05_061",
        loinc_num="15061-7",
        snomed_ct="100500061",
        component="Diagnostic Analyte Component 05-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_062": ClinicalConcept_05(
        concept_id="CONCEPT_05_062",
        loinc_num="15062-8",
        snomed_ct="100500062",
        component="Diagnostic Analyte Component 05-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_063": ClinicalConcept_05(
        concept_id="CONCEPT_05_063",
        loinc_num="15063-0",
        snomed_ct="100500063",
        component="Diagnostic Analyte Component 05-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_064": ClinicalConcept_05(
        concept_id="CONCEPT_05_064",
        loinc_num="15064-1",
        snomed_ct="100500064",
        component="Diagnostic Analyte Component 05-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_065": ClinicalConcept_05(
        concept_id="CONCEPT_05_065",
        loinc_num="15065-2",
        snomed_ct="100500065",
        component="Diagnostic Analyte Component 05-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_066": ClinicalConcept_05(
        concept_id="CONCEPT_05_066",
        loinc_num="15066-3",
        snomed_ct="100500066",
        component="Diagnostic Analyte Component 05-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_067": ClinicalConcept_05(
        concept_id="CONCEPT_05_067",
        loinc_num="15067-4",
        snomed_ct="100500067",
        component="Diagnostic Analyte Component 05-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_068": ClinicalConcept_05(
        concept_id="CONCEPT_05_068",
        loinc_num="15068-5",
        snomed_ct="100500068",
        component="Diagnostic Analyte Component 05-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_069": ClinicalConcept_05(
        concept_id="CONCEPT_05_069",
        loinc_num="15069-6",
        snomed_ct="100500069",
        component="Diagnostic Analyte Component 05-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_070": ClinicalConcept_05(
        concept_id="CONCEPT_05_070",
        loinc_num="15070-7",
        snomed_ct="100500070",
        component="Diagnostic Analyte Component 05-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_071": ClinicalConcept_05(
        concept_id="CONCEPT_05_071",
        loinc_num="15071-8",
        snomed_ct="100500071",
        component="Diagnostic Analyte Component 05-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_072": ClinicalConcept_05(
        concept_id="CONCEPT_05_072",
        loinc_num="15072-0",
        snomed_ct="100500072",
        component="Diagnostic Analyte Component 05-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_073": ClinicalConcept_05(
        concept_id="CONCEPT_05_073",
        loinc_num="15073-1",
        snomed_ct="100500073",
        component="Diagnostic Analyte Component 05-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_074": ClinicalConcept_05(
        concept_id="CONCEPT_05_074",
        loinc_num="15074-2",
        snomed_ct="100500074",
        component="Diagnostic Analyte Component 05-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_075": ClinicalConcept_05(
        concept_id="CONCEPT_05_075",
        loinc_num="15075-3",
        snomed_ct="100500075",
        component="Diagnostic Analyte Component 05-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_076": ClinicalConcept_05(
        concept_id="CONCEPT_05_076",
        loinc_num="15076-4",
        snomed_ct="100500076",
        component="Diagnostic Analyte Component 05-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_077": ClinicalConcept_05(
        concept_id="CONCEPT_05_077",
        loinc_num="15077-5",
        snomed_ct="100500077",
        component="Diagnostic Analyte Component 05-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_078": ClinicalConcept_05(
        concept_id="CONCEPT_05_078",
        loinc_num="15078-6",
        snomed_ct="100500078",
        component="Diagnostic Analyte Component 05-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_079": ClinicalConcept_05(
        concept_id="CONCEPT_05_079",
        loinc_num="15079-7",
        snomed_ct="100500079",
        component="Diagnostic Analyte Component 05-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_080": ClinicalConcept_05(
        concept_id="CONCEPT_05_080",
        loinc_num="15080-8",
        snomed_ct="100500080",
        component="Diagnostic Analyte Component 05-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_081": ClinicalConcept_05(
        concept_id="CONCEPT_05_081",
        loinc_num="15081-0",
        snomed_ct="100500081",
        component="Diagnostic Analyte Component 05-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_082": ClinicalConcept_05(
        concept_id="CONCEPT_05_082",
        loinc_num="15082-1",
        snomed_ct="100500082",
        component="Diagnostic Analyte Component 05-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_083": ClinicalConcept_05(
        concept_id="CONCEPT_05_083",
        loinc_num="15083-2",
        snomed_ct="100500083",
        component="Diagnostic Analyte Component 05-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_084": ClinicalConcept_05(
        concept_id="CONCEPT_05_084",
        loinc_num="15084-3",
        snomed_ct="100500084",
        component="Diagnostic Analyte Component 05-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_085": ClinicalConcept_05(
        concept_id="CONCEPT_05_085",
        loinc_num="15085-4",
        snomed_ct="100500085",
        component="Diagnostic Analyte Component 05-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_086": ClinicalConcept_05(
        concept_id="CONCEPT_05_086",
        loinc_num="15086-5",
        snomed_ct="100500086",
        component="Diagnostic Analyte Component 05-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_087": ClinicalConcept_05(
        concept_id="CONCEPT_05_087",
        loinc_num="15087-6",
        snomed_ct="100500087",
        component="Diagnostic Analyte Component 05-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_088": ClinicalConcept_05(
        concept_id="CONCEPT_05_088",
        loinc_num="15088-7",
        snomed_ct="100500088",
        component="Diagnostic Analyte Component 05-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_089": ClinicalConcept_05(
        concept_id="CONCEPT_05_089",
        loinc_num="15089-8",
        snomed_ct="100500089",
        component="Diagnostic Analyte Component 05-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_090": ClinicalConcept_05(
        concept_id="CONCEPT_05_090",
        loinc_num="15090-0",
        snomed_ct="100500090",
        component="Diagnostic Analyte Component 05-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_091": ClinicalConcept_05(
        concept_id="CONCEPT_05_091",
        loinc_num="15091-1",
        snomed_ct="100500091",
        component="Diagnostic Analyte Component 05-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_092": ClinicalConcept_05(
        concept_id="CONCEPT_05_092",
        loinc_num="15092-2",
        snomed_ct="100500092",
        component="Diagnostic Analyte Component 05-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_093": ClinicalConcept_05(
        concept_id="CONCEPT_05_093",
        loinc_num="15093-3",
        snomed_ct="100500093",
        component="Diagnostic Analyte Component 05-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_094": ClinicalConcept_05(
        concept_id="CONCEPT_05_094",
        loinc_num="15094-4",
        snomed_ct="100500094",
        component="Diagnostic Analyte Component 05-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_095": ClinicalConcept_05(
        concept_id="CONCEPT_05_095",
        loinc_num="15095-5",
        snomed_ct="100500095",
        component="Diagnostic Analyte Component 05-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_096": ClinicalConcept_05(
        concept_id="CONCEPT_05_096",
        loinc_num="15096-6",
        snomed_ct="100500096",
        component="Diagnostic Analyte Component 05-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_097": ClinicalConcept_05(
        concept_id="CONCEPT_05_097",
        loinc_num="15097-7",
        snomed_ct="100500097",
        component="Diagnostic Analyte Component 05-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_098": ClinicalConcept_05(
        concept_id="CONCEPT_05_098",
        loinc_num="15098-8",
        snomed_ct="100500098",
        component="Diagnostic Analyte Component 05-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_099": ClinicalConcept_05(
        concept_id="CONCEPT_05_099",
        loinc_num="15099-0",
        snomed_ct="100500099",
        component="Diagnostic Analyte Component 05-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_100": ClinicalConcept_05(
        concept_id="CONCEPT_05_100",
        loinc_num="15100-1",
        snomed_ct="100500100",
        component="Diagnostic Analyte Component 05-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_101": ClinicalConcept_05(
        concept_id="CONCEPT_05_101",
        loinc_num="15101-2",
        snomed_ct="100500101",
        component="Diagnostic Analyte Component 05-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_102": ClinicalConcept_05(
        concept_id="CONCEPT_05_102",
        loinc_num="15102-3",
        snomed_ct="100500102",
        component="Diagnostic Analyte Component 05-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_103": ClinicalConcept_05(
        concept_id="CONCEPT_05_103",
        loinc_num="15103-4",
        snomed_ct="100500103",
        component="Diagnostic Analyte Component 05-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_104": ClinicalConcept_05(
        concept_id="CONCEPT_05_104",
        loinc_num="15104-5",
        snomed_ct="100500104",
        component="Diagnostic Analyte Component 05-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_105": ClinicalConcept_05(
        concept_id="CONCEPT_05_105",
        loinc_num="15105-6",
        snomed_ct="100500105",
        component="Diagnostic Analyte Component 05-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_106": ClinicalConcept_05(
        concept_id="CONCEPT_05_106",
        loinc_num="15106-7",
        snomed_ct="100500106",
        component="Diagnostic Analyte Component 05-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_107": ClinicalConcept_05(
        concept_id="CONCEPT_05_107",
        loinc_num="15107-8",
        snomed_ct="100500107",
        component="Diagnostic Analyte Component 05-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_108": ClinicalConcept_05(
        concept_id="CONCEPT_05_108",
        loinc_num="15108-0",
        snomed_ct="100500108",
        component="Diagnostic Analyte Component 05-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_109": ClinicalConcept_05(
        concept_id="CONCEPT_05_109",
        loinc_num="15109-1",
        snomed_ct="100500109",
        component="Diagnostic Analyte Component 05-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_110": ClinicalConcept_05(
        concept_id="CONCEPT_05_110",
        loinc_num="15110-2",
        snomed_ct="100500110",
        component="Diagnostic Analyte Component 05-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_111": ClinicalConcept_05(
        concept_id="CONCEPT_05_111",
        loinc_num="15111-3",
        snomed_ct="100500111",
        component="Diagnostic Analyte Component 05-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_112": ClinicalConcept_05(
        concept_id="CONCEPT_05_112",
        loinc_num="15112-4",
        snomed_ct="100500112",
        component="Diagnostic Analyte Component 05-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_113": ClinicalConcept_05(
        concept_id="CONCEPT_05_113",
        loinc_num="15113-5",
        snomed_ct="100500113",
        component="Diagnostic Analyte Component 05-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_114": ClinicalConcept_05(
        concept_id="CONCEPT_05_114",
        loinc_num="15114-6",
        snomed_ct="100500114",
        component="Diagnostic Analyte Component 05-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_115": ClinicalConcept_05(
        concept_id="CONCEPT_05_115",
        loinc_num="15115-7",
        snomed_ct="100500115",
        component="Diagnostic Analyte Component 05-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_116": ClinicalConcept_05(
        concept_id="CONCEPT_05_116",
        loinc_num="15116-8",
        snomed_ct="100500116",
        component="Diagnostic Analyte Component 05-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_117": ClinicalConcept_05(
        concept_id="CONCEPT_05_117",
        loinc_num="15117-0",
        snomed_ct="100500117",
        component="Diagnostic Analyte Component 05-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_118": ClinicalConcept_05(
        concept_id="CONCEPT_05_118",
        loinc_num="15118-1",
        snomed_ct="100500118",
        component="Diagnostic Analyte Component 05-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_119": ClinicalConcept_05(
        concept_id="CONCEPT_05_119",
        loinc_num="15119-2",
        snomed_ct="100500119",
        component="Diagnostic Analyte Component 05-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_120": ClinicalConcept_05(
        concept_id="CONCEPT_05_120",
        loinc_num="15120-3",
        snomed_ct="100500120",
        component="Diagnostic Analyte Component 05-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_121": ClinicalConcept_05(
        concept_id="CONCEPT_05_121",
        loinc_num="15121-4",
        snomed_ct="100500121",
        component="Diagnostic Analyte Component 05-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_122": ClinicalConcept_05(
        concept_id="CONCEPT_05_122",
        loinc_num="15122-5",
        snomed_ct="100500122",
        component="Diagnostic Analyte Component 05-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_123": ClinicalConcept_05(
        concept_id="CONCEPT_05_123",
        loinc_num="15123-6",
        snomed_ct="100500123",
        component="Diagnostic Analyte Component 05-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_124": ClinicalConcept_05(
        concept_id="CONCEPT_05_124",
        loinc_num="15124-7",
        snomed_ct="100500124",
        component="Diagnostic Analyte Component 05-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_125": ClinicalConcept_05(
        concept_id="CONCEPT_05_125",
        loinc_num="15125-8",
        snomed_ct="100500125",
        component="Diagnostic Analyte Component 05-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_126": ClinicalConcept_05(
        concept_id="CONCEPT_05_126",
        loinc_num="15126-0",
        snomed_ct="100500126",
        component="Diagnostic Analyte Component 05-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_127": ClinicalConcept_05(
        concept_id="CONCEPT_05_127",
        loinc_num="15127-1",
        snomed_ct="100500127",
        component="Diagnostic Analyte Component 05-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_128": ClinicalConcept_05(
        concept_id="CONCEPT_05_128",
        loinc_num="15128-2",
        snomed_ct="100500128",
        component="Diagnostic Analyte Component 05-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_129": ClinicalConcept_05(
        concept_id="CONCEPT_05_129",
        loinc_num="15129-3",
        snomed_ct="100500129",
        component="Diagnostic Analyte Component 05-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_130": ClinicalConcept_05(
        concept_id="CONCEPT_05_130",
        loinc_num="15130-4",
        snomed_ct="100500130",
        component="Diagnostic Analyte Component 05-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_131": ClinicalConcept_05(
        concept_id="CONCEPT_05_131",
        loinc_num="15131-5",
        snomed_ct="100500131",
        component="Diagnostic Analyte Component 05-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_132": ClinicalConcept_05(
        concept_id="CONCEPT_05_132",
        loinc_num="15132-6",
        snomed_ct="100500132",
        component="Diagnostic Analyte Component 05-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_133": ClinicalConcept_05(
        concept_id="CONCEPT_05_133",
        loinc_num="15133-7",
        snomed_ct="100500133",
        component="Diagnostic Analyte Component 05-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_134": ClinicalConcept_05(
        concept_id="CONCEPT_05_134",
        loinc_num="15134-8",
        snomed_ct="100500134",
        component="Diagnostic Analyte Component 05-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_135": ClinicalConcept_05(
        concept_id="CONCEPT_05_135",
        loinc_num="15135-0",
        snomed_ct="100500135",
        component="Diagnostic Analyte Component 05-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_136": ClinicalConcept_05(
        concept_id="CONCEPT_05_136",
        loinc_num="15136-1",
        snomed_ct="100500136",
        component="Diagnostic Analyte Component 05-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_137": ClinicalConcept_05(
        concept_id="CONCEPT_05_137",
        loinc_num="15137-2",
        snomed_ct="100500137",
        component="Diagnostic Analyte Component 05-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_138": ClinicalConcept_05(
        concept_id="CONCEPT_05_138",
        loinc_num="15138-3",
        snomed_ct="100500138",
        component="Diagnostic Analyte Component 05-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_139": ClinicalConcept_05(
        concept_id="CONCEPT_05_139",
        loinc_num="15139-4",
        snomed_ct="100500139",
        component="Diagnostic Analyte Component 05-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_140": ClinicalConcept_05(
        concept_id="CONCEPT_05_140",
        loinc_num="15140-5",
        snomed_ct="100500140",
        component="Diagnostic Analyte Component 05-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_141": ClinicalConcept_05(
        concept_id="CONCEPT_05_141",
        loinc_num="15141-6",
        snomed_ct="100500141",
        component="Diagnostic Analyte Component 05-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_142": ClinicalConcept_05(
        concept_id="CONCEPT_05_142",
        loinc_num="15142-7",
        snomed_ct="100500142",
        component="Diagnostic Analyte Component 05-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_143": ClinicalConcept_05(
        concept_id="CONCEPT_05_143",
        loinc_num="15143-8",
        snomed_ct="100500143",
        component="Diagnostic Analyte Component 05-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_144": ClinicalConcept_05(
        concept_id="CONCEPT_05_144",
        loinc_num="15144-0",
        snomed_ct="100500144",
        component="Diagnostic Analyte Component 05-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_145": ClinicalConcept_05(
        concept_id="CONCEPT_05_145",
        loinc_num="15145-1",
        snomed_ct="100500145",
        component="Diagnostic Analyte Component 05-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_146": ClinicalConcept_05(
        concept_id="CONCEPT_05_146",
        loinc_num="15146-2",
        snomed_ct="100500146",
        component="Diagnostic Analyte Component 05-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_147": ClinicalConcept_05(
        concept_id="CONCEPT_05_147",
        loinc_num="15147-3",
        snomed_ct="100500147",
        component="Diagnostic Analyte Component 05-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_148": ClinicalConcept_05(
        concept_id="CONCEPT_05_148",
        loinc_num="15148-4",
        snomed_ct="100500148",
        component="Diagnostic Analyte Component 05-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_149": ClinicalConcept_05(
        concept_id="CONCEPT_05_149",
        loinc_num="15149-5",
        snomed_ct="100500149",
        component="Diagnostic Analyte Component 05-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_150": ClinicalConcept_05(
        concept_id="CONCEPT_05_150",
        loinc_num="15150-6",
        snomed_ct="100500150",
        component="Diagnostic Analyte Component 05-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_151": ClinicalConcept_05(
        concept_id="CONCEPT_05_151",
        loinc_num="15151-7",
        snomed_ct="100500151",
        component="Diagnostic Analyte Component 05-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_152": ClinicalConcept_05(
        concept_id="CONCEPT_05_152",
        loinc_num="15152-8",
        snomed_ct="100500152",
        component="Diagnostic Analyte Component 05-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_153": ClinicalConcept_05(
        concept_id="CONCEPT_05_153",
        loinc_num="15153-0",
        snomed_ct="100500153",
        component="Diagnostic Analyte Component 05-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_154": ClinicalConcept_05(
        concept_id="CONCEPT_05_154",
        loinc_num="15154-1",
        snomed_ct="100500154",
        component="Diagnostic Analyte Component 05-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_155": ClinicalConcept_05(
        concept_id="CONCEPT_05_155",
        loinc_num="15155-2",
        snomed_ct="100500155",
        component="Diagnostic Analyte Component 05-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_156": ClinicalConcept_05(
        concept_id="CONCEPT_05_156",
        loinc_num="15156-3",
        snomed_ct="100500156",
        component="Diagnostic Analyte Component 05-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_157": ClinicalConcept_05(
        concept_id="CONCEPT_05_157",
        loinc_num="15157-4",
        snomed_ct="100500157",
        component="Diagnostic Analyte Component 05-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_158": ClinicalConcept_05(
        concept_id="CONCEPT_05_158",
        loinc_num="15158-5",
        snomed_ct="100500158",
        component="Diagnostic Analyte Component 05-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_159": ClinicalConcept_05(
        concept_id="CONCEPT_05_159",
        loinc_num="15159-6",
        snomed_ct="100500159",
        component="Diagnostic Analyte Component 05-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_160": ClinicalConcept_05(
        concept_id="CONCEPT_05_160",
        loinc_num="15160-7",
        snomed_ct="100500160",
        component="Diagnostic Analyte Component 05-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_161": ClinicalConcept_05(
        concept_id="CONCEPT_05_161",
        loinc_num="15161-8",
        snomed_ct="100500161",
        component="Diagnostic Analyte Component 05-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_162": ClinicalConcept_05(
        concept_id="CONCEPT_05_162",
        loinc_num="15162-0",
        snomed_ct="100500162",
        component="Diagnostic Analyte Component 05-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_163": ClinicalConcept_05(
        concept_id="CONCEPT_05_163",
        loinc_num="15163-1",
        snomed_ct="100500163",
        component="Diagnostic Analyte Component 05-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_164": ClinicalConcept_05(
        concept_id="CONCEPT_05_164",
        loinc_num="15164-2",
        snomed_ct="100500164",
        component="Diagnostic Analyte Component 05-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_165": ClinicalConcept_05(
        concept_id="CONCEPT_05_165",
        loinc_num="15165-3",
        snomed_ct="100500165",
        component="Diagnostic Analyte Component 05-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_166": ClinicalConcept_05(
        concept_id="CONCEPT_05_166",
        loinc_num="15166-4",
        snomed_ct="100500166",
        component="Diagnostic Analyte Component 05-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_167": ClinicalConcept_05(
        concept_id="CONCEPT_05_167",
        loinc_num="15167-5",
        snomed_ct="100500167",
        component="Diagnostic Analyte Component 05-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_168": ClinicalConcept_05(
        concept_id="CONCEPT_05_168",
        loinc_num="15168-6",
        snomed_ct="100500168",
        component="Diagnostic Analyte Component 05-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_169": ClinicalConcept_05(
        concept_id="CONCEPT_05_169",
        loinc_num="15169-7",
        snomed_ct="100500169",
        component="Diagnostic Analyte Component 05-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_170": ClinicalConcept_05(
        concept_id="CONCEPT_05_170",
        loinc_num="15170-8",
        snomed_ct="100500170",
        component="Diagnostic Analyte Component 05-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_171": ClinicalConcept_05(
        concept_id="CONCEPT_05_171",
        loinc_num="15171-0",
        snomed_ct="100500171",
        component="Diagnostic Analyte Component 05-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_172": ClinicalConcept_05(
        concept_id="CONCEPT_05_172",
        loinc_num="15172-1",
        snomed_ct="100500172",
        component="Diagnostic Analyte Component 05-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_173": ClinicalConcept_05(
        concept_id="CONCEPT_05_173",
        loinc_num="15173-2",
        snomed_ct="100500173",
        component="Diagnostic Analyte Component 05-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_174": ClinicalConcept_05(
        concept_id="CONCEPT_05_174",
        loinc_num="15174-3",
        snomed_ct="100500174",
        component="Diagnostic Analyte Component 05-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_175": ClinicalConcept_05(
        concept_id="CONCEPT_05_175",
        loinc_num="15175-4",
        snomed_ct="100500175",
        component="Diagnostic Analyte Component 05-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_176": ClinicalConcept_05(
        concept_id="CONCEPT_05_176",
        loinc_num="15176-5",
        snomed_ct="100500176",
        component="Diagnostic Analyte Component 05-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_177": ClinicalConcept_05(
        concept_id="CONCEPT_05_177",
        loinc_num="15177-6",
        snomed_ct="100500177",
        component="Diagnostic Analyte Component 05-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_178": ClinicalConcept_05(
        concept_id="CONCEPT_05_178",
        loinc_num="15178-7",
        snomed_ct="100500178",
        component="Diagnostic Analyte Component 05-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_179": ClinicalConcept_05(
        concept_id="CONCEPT_05_179",
        loinc_num="15179-8",
        snomed_ct="100500179",
        component="Diagnostic Analyte Component 05-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_180": ClinicalConcept_05(
        concept_id="CONCEPT_05_180",
        loinc_num="15180-0",
        snomed_ct="100500180",
        component="Diagnostic Analyte Component 05-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_181": ClinicalConcept_05(
        concept_id="CONCEPT_05_181",
        loinc_num="15181-1",
        snomed_ct="100500181",
        component="Diagnostic Analyte Component 05-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_182": ClinicalConcept_05(
        concept_id="CONCEPT_05_182",
        loinc_num="15182-2",
        snomed_ct="100500182",
        component="Diagnostic Analyte Component 05-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_183": ClinicalConcept_05(
        concept_id="CONCEPT_05_183",
        loinc_num="15183-3",
        snomed_ct="100500183",
        component="Diagnostic Analyte Component 05-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_184": ClinicalConcept_05(
        concept_id="CONCEPT_05_184",
        loinc_num="15184-4",
        snomed_ct="100500184",
        component="Diagnostic Analyte Component 05-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_185": ClinicalConcept_05(
        concept_id="CONCEPT_05_185",
        loinc_num="15185-5",
        snomed_ct="100500185",
        component="Diagnostic Analyte Component 05-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_186": ClinicalConcept_05(
        concept_id="CONCEPT_05_186",
        loinc_num="15186-6",
        snomed_ct="100500186",
        component="Diagnostic Analyte Component 05-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_187": ClinicalConcept_05(
        concept_id="CONCEPT_05_187",
        loinc_num="15187-7",
        snomed_ct="100500187",
        component="Diagnostic Analyte Component 05-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_188": ClinicalConcept_05(
        concept_id="CONCEPT_05_188",
        loinc_num="15188-8",
        snomed_ct="100500188",
        component="Diagnostic Analyte Component 05-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_189": ClinicalConcept_05(
        concept_id="CONCEPT_05_189",
        loinc_num="15189-0",
        snomed_ct="100500189",
        component="Diagnostic Analyte Component 05-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_190": ClinicalConcept_05(
        concept_id="CONCEPT_05_190",
        loinc_num="15190-1",
        snomed_ct="100500190",
        component="Diagnostic Analyte Component 05-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_191": ClinicalConcept_05(
        concept_id="CONCEPT_05_191",
        loinc_num="15191-2",
        snomed_ct="100500191",
        component="Diagnostic Analyte Component 05-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_192": ClinicalConcept_05(
        concept_id="CONCEPT_05_192",
        loinc_num="15192-3",
        snomed_ct="100500192",
        component="Diagnostic Analyte Component 05-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_193": ClinicalConcept_05(
        concept_id="CONCEPT_05_193",
        loinc_num="15193-4",
        snomed_ct="100500193",
        component="Diagnostic Analyte Component 05-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_194": ClinicalConcept_05(
        concept_id="CONCEPT_05_194",
        loinc_num="15194-5",
        snomed_ct="100500194",
        component="Diagnostic Analyte Component 05-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_195": ClinicalConcept_05(
        concept_id="CONCEPT_05_195",
        loinc_num="15195-6",
        snomed_ct="100500195",
        component="Diagnostic Analyte Component 05-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_196": ClinicalConcept_05(
        concept_id="CONCEPT_05_196",
        loinc_num="15196-7",
        snomed_ct="100500196",
        component="Diagnostic Analyte Component 05-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_197": ClinicalConcept_05(
        concept_id="CONCEPT_05_197",
        loinc_num="15197-8",
        snomed_ct="100500197",
        component="Diagnostic Analyte Component 05-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_198": ClinicalConcept_05(
        concept_id="CONCEPT_05_198",
        loinc_num="15198-0",
        snomed_ct="100500198",
        component="Diagnostic Analyte Component 05-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_05_199": ClinicalConcept_05(
        concept_id="CONCEPT_05_199",
        loinc_num="15199-1",
        snomed_ct="100500199",
        component="Diagnostic Analyte Component 05-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
