"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 07"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_07:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_07 = {
    "CONCEPT_07_001": ClinicalConcept_07(
        concept_id="CONCEPT_07_001",
        loinc_num="17001-1",
        snomed_ct="100700001",
        component="Diagnostic Analyte Component 07-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_002": ClinicalConcept_07(
        concept_id="CONCEPT_07_002",
        loinc_num="17002-2",
        snomed_ct="100700002",
        component="Diagnostic Analyte Component 07-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_003": ClinicalConcept_07(
        concept_id="CONCEPT_07_003",
        loinc_num="17003-3",
        snomed_ct="100700003",
        component="Diagnostic Analyte Component 07-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_004": ClinicalConcept_07(
        concept_id="CONCEPT_07_004",
        loinc_num="17004-4",
        snomed_ct="100700004",
        component="Diagnostic Analyte Component 07-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_005": ClinicalConcept_07(
        concept_id="CONCEPT_07_005",
        loinc_num="17005-5",
        snomed_ct="100700005",
        component="Diagnostic Analyte Component 07-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_006": ClinicalConcept_07(
        concept_id="CONCEPT_07_006",
        loinc_num="17006-6",
        snomed_ct="100700006",
        component="Diagnostic Analyte Component 07-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_007": ClinicalConcept_07(
        concept_id="CONCEPT_07_007",
        loinc_num="17007-7",
        snomed_ct="100700007",
        component="Diagnostic Analyte Component 07-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_008": ClinicalConcept_07(
        concept_id="CONCEPT_07_008",
        loinc_num="17008-8",
        snomed_ct="100700008",
        component="Diagnostic Analyte Component 07-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_009": ClinicalConcept_07(
        concept_id="CONCEPT_07_009",
        loinc_num="17009-0",
        snomed_ct="100700009",
        component="Diagnostic Analyte Component 07-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_010": ClinicalConcept_07(
        concept_id="CONCEPT_07_010",
        loinc_num="17010-1",
        snomed_ct="100700010",
        component="Diagnostic Analyte Component 07-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_011": ClinicalConcept_07(
        concept_id="CONCEPT_07_011",
        loinc_num="17011-2",
        snomed_ct="100700011",
        component="Diagnostic Analyte Component 07-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_012": ClinicalConcept_07(
        concept_id="CONCEPT_07_012",
        loinc_num="17012-3",
        snomed_ct="100700012",
        component="Diagnostic Analyte Component 07-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_013": ClinicalConcept_07(
        concept_id="CONCEPT_07_013",
        loinc_num="17013-4",
        snomed_ct="100700013",
        component="Diagnostic Analyte Component 07-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_014": ClinicalConcept_07(
        concept_id="CONCEPT_07_014",
        loinc_num="17014-5",
        snomed_ct="100700014",
        component="Diagnostic Analyte Component 07-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_015": ClinicalConcept_07(
        concept_id="CONCEPT_07_015",
        loinc_num="17015-6",
        snomed_ct="100700015",
        component="Diagnostic Analyte Component 07-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_016": ClinicalConcept_07(
        concept_id="CONCEPT_07_016",
        loinc_num="17016-7",
        snomed_ct="100700016",
        component="Diagnostic Analyte Component 07-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_017": ClinicalConcept_07(
        concept_id="CONCEPT_07_017",
        loinc_num="17017-8",
        snomed_ct="100700017",
        component="Diagnostic Analyte Component 07-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_018": ClinicalConcept_07(
        concept_id="CONCEPT_07_018",
        loinc_num="17018-0",
        snomed_ct="100700018",
        component="Diagnostic Analyte Component 07-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_019": ClinicalConcept_07(
        concept_id="CONCEPT_07_019",
        loinc_num="17019-1",
        snomed_ct="100700019",
        component="Diagnostic Analyte Component 07-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_020": ClinicalConcept_07(
        concept_id="CONCEPT_07_020",
        loinc_num="17020-2",
        snomed_ct="100700020",
        component="Diagnostic Analyte Component 07-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_021": ClinicalConcept_07(
        concept_id="CONCEPT_07_021",
        loinc_num="17021-3",
        snomed_ct="100700021",
        component="Diagnostic Analyte Component 07-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_022": ClinicalConcept_07(
        concept_id="CONCEPT_07_022",
        loinc_num="17022-4",
        snomed_ct="100700022",
        component="Diagnostic Analyte Component 07-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_023": ClinicalConcept_07(
        concept_id="CONCEPT_07_023",
        loinc_num="17023-5",
        snomed_ct="100700023",
        component="Diagnostic Analyte Component 07-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_024": ClinicalConcept_07(
        concept_id="CONCEPT_07_024",
        loinc_num="17024-6",
        snomed_ct="100700024",
        component="Diagnostic Analyte Component 07-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_025": ClinicalConcept_07(
        concept_id="CONCEPT_07_025",
        loinc_num="17025-7",
        snomed_ct="100700025",
        component="Diagnostic Analyte Component 07-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_026": ClinicalConcept_07(
        concept_id="CONCEPT_07_026",
        loinc_num="17026-8",
        snomed_ct="100700026",
        component="Diagnostic Analyte Component 07-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_027": ClinicalConcept_07(
        concept_id="CONCEPT_07_027",
        loinc_num="17027-0",
        snomed_ct="100700027",
        component="Diagnostic Analyte Component 07-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_028": ClinicalConcept_07(
        concept_id="CONCEPT_07_028",
        loinc_num="17028-1",
        snomed_ct="100700028",
        component="Diagnostic Analyte Component 07-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_029": ClinicalConcept_07(
        concept_id="CONCEPT_07_029",
        loinc_num="17029-2",
        snomed_ct="100700029",
        component="Diagnostic Analyte Component 07-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_030": ClinicalConcept_07(
        concept_id="CONCEPT_07_030",
        loinc_num="17030-3",
        snomed_ct="100700030",
        component="Diagnostic Analyte Component 07-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_031": ClinicalConcept_07(
        concept_id="CONCEPT_07_031",
        loinc_num="17031-4",
        snomed_ct="100700031",
        component="Diagnostic Analyte Component 07-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_032": ClinicalConcept_07(
        concept_id="CONCEPT_07_032",
        loinc_num="17032-5",
        snomed_ct="100700032",
        component="Diagnostic Analyte Component 07-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_033": ClinicalConcept_07(
        concept_id="CONCEPT_07_033",
        loinc_num="17033-6",
        snomed_ct="100700033",
        component="Diagnostic Analyte Component 07-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_034": ClinicalConcept_07(
        concept_id="CONCEPT_07_034",
        loinc_num="17034-7",
        snomed_ct="100700034",
        component="Diagnostic Analyte Component 07-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_035": ClinicalConcept_07(
        concept_id="CONCEPT_07_035",
        loinc_num="17035-8",
        snomed_ct="100700035",
        component="Diagnostic Analyte Component 07-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_036": ClinicalConcept_07(
        concept_id="CONCEPT_07_036",
        loinc_num="17036-0",
        snomed_ct="100700036",
        component="Diagnostic Analyte Component 07-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_037": ClinicalConcept_07(
        concept_id="CONCEPT_07_037",
        loinc_num="17037-1",
        snomed_ct="100700037",
        component="Diagnostic Analyte Component 07-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_038": ClinicalConcept_07(
        concept_id="CONCEPT_07_038",
        loinc_num="17038-2",
        snomed_ct="100700038",
        component="Diagnostic Analyte Component 07-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_039": ClinicalConcept_07(
        concept_id="CONCEPT_07_039",
        loinc_num="17039-3",
        snomed_ct="100700039",
        component="Diagnostic Analyte Component 07-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_040": ClinicalConcept_07(
        concept_id="CONCEPT_07_040",
        loinc_num="17040-4",
        snomed_ct="100700040",
        component="Diagnostic Analyte Component 07-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_041": ClinicalConcept_07(
        concept_id="CONCEPT_07_041",
        loinc_num="17041-5",
        snomed_ct="100700041",
        component="Diagnostic Analyte Component 07-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_042": ClinicalConcept_07(
        concept_id="CONCEPT_07_042",
        loinc_num="17042-6",
        snomed_ct="100700042",
        component="Diagnostic Analyte Component 07-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_043": ClinicalConcept_07(
        concept_id="CONCEPT_07_043",
        loinc_num="17043-7",
        snomed_ct="100700043",
        component="Diagnostic Analyte Component 07-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_044": ClinicalConcept_07(
        concept_id="CONCEPT_07_044",
        loinc_num="17044-8",
        snomed_ct="100700044",
        component="Diagnostic Analyte Component 07-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_045": ClinicalConcept_07(
        concept_id="CONCEPT_07_045",
        loinc_num="17045-0",
        snomed_ct="100700045",
        component="Diagnostic Analyte Component 07-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_046": ClinicalConcept_07(
        concept_id="CONCEPT_07_046",
        loinc_num="17046-1",
        snomed_ct="100700046",
        component="Diagnostic Analyte Component 07-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_047": ClinicalConcept_07(
        concept_id="CONCEPT_07_047",
        loinc_num="17047-2",
        snomed_ct="100700047",
        component="Diagnostic Analyte Component 07-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_048": ClinicalConcept_07(
        concept_id="CONCEPT_07_048",
        loinc_num="17048-3",
        snomed_ct="100700048",
        component="Diagnostic Analyte Component 07-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_049": ClinicalConcept_07(
        concept_id="CONCEPT_07_049",
        loinc_num="17049-4",
        snomed_ct="100700049",
        component="Diagnostic Analyte Component 07-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_050": ClinicalConcept_07(
        concept_id="CONCEPT_07_050",
        loinc_num="17050-5",
        snomed_ct="100700050",
        component="Diagnostic Analyte Component 07-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_051": ClinicalConcept_07(
        concept_id="CONCEPT_07_051",
        loinc_num="17051-6",
        snomed_ct="100700051",
        component="Diagnostic Analyte Component 07-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_052": ClinicalConcept_07(
        concept_id="CONCEPT_07_052",
        loinc_num="17052-7",
        snomed_ct="100700052",
        component="Diagnostic Analyte Component 07-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_053": ClinicalConcept_07(
        concept_id="CONCEPT_07_053",
        loinc_num="17053-8",
        snomed_ct="100700053",
        component="Diagnostic Analyte Component 07-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_054": ClinicalConcept_07(
        concept_id="CONCEPT_07_054",
        loinc_num="17054-0",
        snomed_ct="100700054",
        component="Diagnostic Analyte Component 07-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_055": ClinicalConcept_07(
        concept_id="CONCEPT_07_055",
        loinc_num="17055-1",
        snomed_ct="100700055",
        component="Diagnostic Analyte Component 07-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_056": ClinicalConcept_07(
        concept_id="CONCEPT_07_056",
        loinc_num="17056-2",
        snomed_ct="100700056",
        component="Diagnostic Analyte Component 07-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_057": ClinicalConcept_07(
        concept_id="CONCEPT_07_057",
        loinc_num="17057-3",
        snomed_ct="100700057",
        component="Diagnostic Analyte Component 07-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_058": ClinicalConcept_07(
        concept_id="CONCEPT_07_058",
        loinc_num="17058-4",
        snomed_ct="100700058",
        component="Diagnostic Analyte Component 07-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_059": ClinicalConcept_07(
        concept_id="CONCEPT_07_059",
        loinc_num="17059-5",
        snomed_ct="100700059",
        component="Diagnostic Analyte Component 07-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_060": ClinicalConcept_07(
        concept_id="CONCEPT_07_060",
        loinc_num="17060-6",
        snomed_ct="100700060",
        component="Diagnostic Analyte Component 07-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_061": ClinicalConcept_07(
        concept_id="CONCEPT_07_061",
        loinc_num="17061-7",
        snomed_ct="100700061",
        component="Diagnostic Analyte Component 07-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_062": ClinicalConcept_07(
        concept_id="CONCEPT_07_062",
        loinc_num="17062-8",
        snomed_ct="100700062",
        component="Diagnostic Analyte Component 07-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_063": ClinicalConcept_07(
        concept_id="CONCEPT_07_063",
        loinc_num="17063-0",
        snomed_ct="100700063",
        component="Diagnostic Analyte Component 07-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_064": ClinicalConcept_07(
        concept_id="CONCEPT_07_064",
        loinc_num="17064-1",
        snomed_ct="100700064",
        component="Diagnostic Analyte Component 07-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_065": ClinicalConcept_07(
        concept_id="CONCEPT_07_065",
        loinc_num="17065-2",
        snomed_ct="100700065",
        component="Diagnostic Analyte Component 07-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_066": ClinicalConcept_07(
        concept_id="CONCEPT_07_066",
        loinc_num="17066-3",
        snomed_ct="100700066",
        component="Diagnostic Analyte Component 07-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_067": ClinicalConcept_07(
        concept_id="CONCEPT_07_067",
        loinc_num="17067-4",
        snomed_ct="100700067",
        component="Diagnostic Analyte Component 07-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_068": ClinicalConcept_07(
        concept_id="CONCEPT_07_068",
        loinc_num="17068-5",
        snomed_ct="100700068",
        component="Diagnostic Analyte Component 07-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_069": ClinicalConcept_07(
        concept_id="CONCEPT_07_069",
        loinc_num="17069-6",
        snomed_ct="100700069",
        component="Diagnostic Analyte Component 07-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_070": ClinicalConcept_07(
        concept_id="CONCEPT_07_070",
        loinc_num="17070-7",
        snomed_ct="100700070",
        component="Diagnostic Analyte Component 07-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_071": ClinicalConcept_07(
        concept_id="CONCEPT_07_071",
        loinc_num="17071-8",
        snomed_ct="100700071",
        component="Diagnostic Analyte Component 07-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_072": ClinicalConcept_07(
        concept_id="CONCEPT_07_072",
        loinc_num="17072-0",
        snomed_ct="100700072",
        component="Diagnostic Analyte Component 07-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_073": ClinicalConcept_07(
        concept_id="CONCEPT_07_073",
        loinc_num="17073-1",
        snomed_ct="100700073",
        component="Diagnostic Analyte Component 07-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_074": ClinicalConcept_07(
        concept_id="CONCEPT_07_074",
        loinc_num="17074-2",
        snomed_ct="100700074",
        component="Diagnostic Analyte Component 07-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_075": ClinicalConcept_07(
        concept_id="CONCEPT_07_075",
        loinc_num="17075-3",
        snomed_ct="100700075",
        component="Diagnostic Analyte Component 07-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_076": ClinicalConcept_07(
        concept_id="CONCEPT_07_076",
        loinc_num="17076-4",
        snomed_ct="100700076",
        component="Diagnostic Analyte Component 07-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_077": ClinicalConcept_07(
        concept_id="CONCEPT_07_077",
        loinc_num="17077-5",
        snomed_ct="100700077",
        component="Diagnostic Analyte Component 07-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_078": ClinicalConcept_07(
        concept_id="CONCEPT_07_078",
        loinc_num="17078-6",
        snomed_ct="100700078",
        component="Diagnostic Analyte Component 07-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_079": ClinicalConcept_07(
        concept_id="CONCEPT_07_079",
        loinc_num="17079-7",
        snomed_ct="100700079",
        component="Diagnostic Analyte Component 07-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_080": ClinicalConcept_07(
        concept_id="CONCEPT_07_080",
        loinc_num="17080-8",
        snomed_ct="100700080",
        component="Diagnostic Analyte Component 07-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_081": ClinicalConcept_07(
        concept_id="CONCEPT_07_081",
        loinc_num="17081-0",
        snomed_ct="100700081",
        component="Diagnostic Analyte Component 07-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_082": ClinicalConcept_07(
        concept_id="CONCEPT_07_082",
        loinc_num="17082-1",
        snomed_ct="100700082",
        component="Diagnostic Analyte Component 07-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_083": ClinicalConcept_07(
        concept_id="CONCEPT_07_083",
        loinc_num="17083-2",
        snomed_ct="100700083",
        component="Diagnostic Analyte Component 07-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_084": ClinicalConcept_07(
        concept_id="CONCEPT_07_084",
        loinc_num="17084-3",
        snomed_ct="100700084",
        component="Diagnostic Analyte Component 07-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_085": ClinicalConcept_07(
        concept_id="CONCEPT_07_085",
        loinc_num="17085-4",
        snomed_ct="100700085",
        component="Diagnostic Analyte Component 07-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_086": ClinicalConcept_07(
        concept_id="CONCEPT_07_086",
        loinc_num="17086-5",
        snomed_ct="100700086",
        component="Diagnostic Analyte Component 07-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_087": ClinicalConcept_07(
        concept_id="CONCEPT_07_087",
        loinc_num="17087-6",
        snomed_ct="100700087",
        component="Diagnostic Analyte Component 07-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_088": ClinicalConcept_07(
        concept_id="CONCEPT_07_088",
        loinc_num="17088-7",
        snomed_ct="100700088",
        component="Diagnostic Analyte Component 07-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_089": ClinicalConcept_07(
        concept_id="CONCEPT_07_089",
        loinc_num="17089-8",
        snomed_ct="100700089",
        component="Diagnostic Analyte Component 07-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_090": ClinicalConcept_07(
        concept_id="CONCEPT_07_090",
        loinc_num="17090-0",
        snomed_ct="100700090",
        component="Diagnostic Analyte Component 07-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_091": ClinicalConcept_07(
        concept_id="CONCEPT_07_091",
        loinc_num="17091-1",
        snomed_ct="100700091",
        component="Diagnostic Analyte Component 07-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_092": ClinicalConcept_07(
        concept_id="CONCEPT_07_092",
        loinc_num="17092-2",
        snomed_ct="100700092",
        component="Diagnostic Analyte Component 07-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_093": ClinicalConcept_07(
        concept_id="CONCEPT_07_093",
        loinc_num="17093-3",
        snomed_ct="100700093",
        component="Diagnostic Analyte Component 07-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_094": ClinicalConcept_07(
        concept_id="CONCEPT_07_094",
        loinc_num="17094-4",
        snomed_ct="100700094",
        component="Diagnostic Analyte Component 07-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_095": ClinicalConcept_07(
        concept_id="CONCEPT_07_095",
        loinc_num="17095-5",
        snomed_ct="100700095",
        component="Diagnostic Analyte Component 07-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_096": ClinicalConcept_07(
        concept_id="CONCEPT_07_096",
        loinc_num="17096-6",
        snomed_ct="100700096",
        component="Diagnostic Analyte Component 07-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_097": ClinicalConcept_07(
        concept_id="CONCEPT_07_097",
        loinc_num="17097-7",
        snomed_ct="100700097",
        component="Diagnostic Analyte Component 07-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_098": ClinicalConcept_07(
        concept_id="CONCEPT_07_098",
        loinc_num="17098-8",
        snomed_ct="100700098",
        component="Diagnostic Analyte Component 07-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_099": ClinicalConcept_07(
        concept_id="CONCEPT_07_099",
        loinc_num="17099-0",
        snomed_ct="100700099",
        component="Diagnostic Analyte Component 07-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_100": ClinicalConcept_07(
        concept_id="CONCEPT_07_100",
        loinc_num="17100-1",
        snomed_ct="100700100",
        component="Diagnostic Analyte Component 07-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_101": ClinicalConcept_07(
        concept_id="CONCEPT_07_101",
        loinc_num="17101-2",
        snomed_ct="100700101",
        component="Diagnostic Analyte Component 07-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_102": ClinicalConcept_07(
        concept_id="CONCEPT_07_102",
        loinc_num="17102-3",
        snomed_ct="100700102",
        component="Diagnostic Analyte Component 07-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_103": ClinicalConcept_07(
        concept_id="CONCEPT_07_103",
        loinc_num="17103-4",
        snomed_ct="100700103",
        component="Diagnostic Analyte Component 07-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_104": ClinicalConcept_07(
        concept_id="CONCEPT_07_104",
        loinc_num="17104-5",
        snomed_ct="100700104",
        component="Diagnostic Analyte Component 07-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_105": ClinicalConcept_07(
        concept_id="CONCEPT_07_105",
        loinc_num="17105-6",
        snomed_ct="100700105",
        component="Diagnostic Analyte Component 07-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_106": ClinicalConcept_07(
        concept_id="CONCEPT_07_106",
        loinc_num="17106-7",
        snomed_ct="100700106",
        component="Diagnostic Analyte Component 07-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_107": ClinicalConcept_07(
        concept_id="CONCEPT_07_107",
        loinc_num="17107-8",
        snomed_ct="100700107",
        component="Diagnostic Analyte Component 07-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_108": ClinicalConcept_07(
        concept_id="CONCEPT_07_108",
        loinc_num="17108-0",
        snomed_ct="100700108",
        component="Diagnostic Analyte Component 07-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_109": ClinicalConcept_07(
        concept_id="CONCEPT_07_109",
        loinc_num="17109-1",
        snomed_ct="100700109",
        component="Diagnostic Analyte Component 07-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_110": ClinicalConcept_07(
        concept_id="CONCEPT_07_110",
        loinc_num="17110-2",
        snomed_ct="100700110",
        component="Diagnostic Analyte Component 07-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_111": ClinicalConcept_07(
        concept_id="CONCEPT_07_111",
        loinc_num="17111-3",
        snomed_ct="100700111",
        component="Diagnostic Analyte Component 07-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_112": ClinicalConcept_07(
        concept_id="CONCEPT_07_112",
        loinc_num="17112-4",
        snomed_ct="100700112",
        component="Diagnostic Analyte Component 07-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_113": ClinicalConcept_07(
        concept_id="CONCEPT_07_113",
        loinc_num="17113-5",
        snomed_ct="100700113",
        component="Diagnostic Analyte Component 07-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_114": ClinicalConcept_07(
        concept_id="CONCEPT_07_114",
        loinc_num="17114-6",
        snomed_ct="100700114",
        component="Diagnostic Analyte Component 07-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_115": ClinicalConcept_07(
        concept_id="CONCEPT_07_115",
        loinc_num="17115-7",
        snomed_ct="100700115",
        component="Diagnostic Analyte Component 07-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_116": ClinicalConcept_07(
        concept_id="CONCEPT_07_116",
        loinc_num="17116-8",
        snomed_ct="100700116",
        component="Diagnostic Analyte Component 07-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_117": ClinicalConcept_07(
        concept_id="CONCEPT_07_117",
        loinc_num="17117-0",
        snomed_ct="100700117",
        component="Diagnostic Analyte Component 07-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_118": ClinicalConcept_07(
        concept_id="CONCEPT_07_118",
        loinc_num="17118-1",
        snomed_ct="100700118",
        component="Diagnostic Analyte Component 07-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_119": ClinicalConcept_07(
        concept_id="CONCEPT_07_119",
        loinc_num="17119-2",
        snomed_ct="100700119",
        component="Diagnostic Analyte Component 07-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_120": ClinicalConcept_07(
        concept_id="CONCEPT_07_120",
        loinc_num="17120-3",
        snomed_ct="100700120",
        component="Diagnostic Analyte Component 07-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_121": ClinicalConcept_07(
        concept_id="CONCEPT_07_121",
        loinc_num="17121-4",
        snomed_ct="100700121",
        component="Diagnostic Analyte Component 07-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_122": ClinicalConcept_07(
        concept_id="CONCEPT_07_122",
        loinc_num="17122-5",
        snomed_ct="100700122",
        component="Diagnostic Analyte Component 07-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_123": ClinicalConcept_07(
        concept_id="CONCEPT_07_123",
        loinc_num="17123-6",
        snomed_ct="100700123",
        component="Diagnostic Analyte Component 07-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_124": ClinicalConcept_07(
        concept_id="CONCEPT_07_124",
        loinc_num="17124-7",
        snomed_ct="100700124",
        component="Diagnostic Analyte Component 07-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_125": ClinicalConcept_07(
        concept_id="CONCEPT_07_125",
        loinc_num="17125-8",
        snomed_ct="100700125",
        component="Diagnostic Analyte Component 07-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_126": ClinicalConcept_07(
        concept_id="CONCEPT_07_126",
        loinc_num="17126-0",
        snomed_ct="100700126",
        component="Diagnostic Analyte Component 07-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_127": ClinicalConcept_07(
        concept_id="CONCEPT_07_127",
        loinc_num="17127-1",
        snomed_ct="100700127",
        component="Diagnostic Analyte Component 07-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_128": ClinicalConcept_07(
        concept_id="CONCEPT_07_128",
        loinc_num="17128-2",
        snomed_ct="100700128",
        component="Diagnostic Analyte Component 07-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_129": ClinicalConcept_07(
        concept_id="CONCEPT_07_129",
        loinc_num="17129-3",
        snomed_ct="100700129",
        component="Diagnostic Analyte Component 07-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_130": ClinicalConcept_07(
        concept_id="CONCEPT_07_130",
        loinc_num="17130-4",
        snomed_ct="100700130",
        component="Diagnostic Analyte Component 07-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_131": ClinicalConcept_07(
        concept_id="CONCEPT_07_131",
        loinc_num="17131-5",
        snomed_ct="100700131",
        component="Diagnostic Analyte Component 07-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_132": ClinicalConcept_07(
        concept_id="CONCEPT_07_132",
        loinc_num="17132-6",
        snomed_ct="100700132",
        component="Diagnostic Analyte Component 07-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_133": ClinicalConcept_07(
        concept_id="CONCEPT_07_133",
        loinc_num="17133-7",
        snomed_ct="100700133",
        component="Diagnostic Analyte Component 07-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_134": ClinicalConcept_07(
        concept_id="CONCEPT_07_134",
        loinc_num="17134-8",
        snomed_ct="100700134",
        component="Diagnostic Analyte Component 07-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_135": ClinicalConcept_07(
        concept_id="CONCEPT_07_135",
        loinc_num="17135-0",
        snomed_ct="100700135",
        component="Diagnostic Analyte Component 07-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_136": ClinicalConcept_07(
        concept_id="CONCEPT_07_136",
        loinc_num="17136-1",
        snomed_ct="100700136",
        component="Diagnostic Analyte Component 07-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_137": ClinicalConcept_07(
        concept_id="CONCEPT_07_137",
        loinc_num="17137-2",
        snomed_ct="100700137",
        component="Diagnostic Analyte Component 07-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_138": ClinicalConcept_07(
        concept_id="CONCEPT_07_138",
        loinc_num="17138-3",
        snomed_ct="100700138",
        component="Diagnostic Analyte Component 07-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_139": ClinicalConcept_07(
        concept_id="CONCEPT_07_139",
        loinc_num="17139-4",
        snomed_ct="100700139",
        component="Diagnostic Analyte Component 07-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_140": ClinicalConcept_07(
        concept_id="CONCEPT_07_140",
        loinc_num="17140-5",
        snomed_ct="100700140",
        component="Diagnostic Analyte Component 07-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_141": ClinicalConcept_07(
        concept_id="CONCEPT_07_141",
        loinc_num="17141-6",
        snomed_ct="100700141",
        component="Diagnostic Analyte Component 07-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_142": ClinicalConcept_07(
        concept_id="CONCEPT_07_142",
        loinc_num="17142-7",
        snomed_ct="100700142",
        component="Diagnostic Analyte Component 07-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_143": ClinicalConcept_07(
        concept_id="CONCEPT_07_143",
        loinc_num="17143-8",
        snomed_ct="100700143",
        component="Diagnostic Analyte Component 07-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_144": ClinicalConcept_07(
        concept_id="CONCEPT_07_144",
        loinc_num="17144-0",
        snomed_ct="100700144",
        component="Diagnostic Analyte Component 07-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_145": ClinicalConcept_07(
        concept_id="CONCEPT_07_145",
        loinc_num="17145-1",
        snomed_ct="100700145",
        component="Diagnostic Analyte Component 07-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_146": ClinicalConcept_07(
        concept_id="CONCEPT_07_146",
        loinc_num="17146-2",
        snomed_ct="100700146",
        component="Diagnostic Analyte Component 07-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_147": ClinicalConcept_07(
        concept_id="CONCEPT_07_147",
        loinc_num="17147-3",
        snomed_ct="100700147",
        component="Diagnostic Analyte Component 07-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_148": ClinicalConcept_07(
        concept_id="CONCEPT_07_148",
        loinc_num="17148-4",
        snomed_ct="100700148",
        component="Diagnostic Analyte Component 07-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_149": ClinicalConcept_07(
        concept_id="CONCEPT_07_149",
        loinc_num="17149-5",
        snomed_ct="100700149",
        component="Diagnostic Analyte Component 07-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_150": ClinicalConcept_07(
        concept_id="CONCEPT_07_150",
        loinc_num="17150-6",
        snomed_ct="100700150",
        component="Diagnostic Analyte Component 07-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_151": ClinicalConcept_07(
        concept_id="CONCEPT_07_151",
        loinc_num="17151-7",
        snomed_ct="100700151",
        component="Diagnostic Analyte Component 07-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_152": ClinicalConcept_07(
        concept_id="CONCEPT_07_152",
        loinc_num="17152-8",
        snomed_ct="100700152",
        component="Diagnostic Analyte Component 07-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_153": ClinicalConcept_07(
        concept_id="CONCEPT_07_153",
        loinc_num="17153-0",
        snomed_ct="100700153",
        component="Diagnostic Analyte Component 07-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_154": ClinicalConcept_07(
        concept_id="CONCEPT_07_154",
        loinc_num="17154-1",
        snomed_ct="100700154",
        component="Diagnostic Analyte Component 07-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_155": ClinicalConcept_07(
        concept_id="CONCEPT_07_155",
        loinc_num="17155-2",
        snomed_ct="100700155",
        component="Diagnostic Analyte Component 07-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_156": ClinicalConcept_07(
        concept_id="CONCEPT_07_156",
        loinc_num="17156-3",
        snomed_ct="100700156",
        component="Diagnostic Analyte Component 07-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_157": ClinicalConcept_07(
        concept_id="CONCEPT_07_157",
        loinc_num="17157-4",
        snomed_ct="100700157",
        component="Diagnostic Analyte Component 07-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_158": ClinicalConcept_07(
        concept_id="CONCEPT_07_158",
        loinc_num="17158-5",
        snomed_ct="100700158",
        component="Diagnostic Analyte Component 07-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_159": ClinicalConcept_07(
        concept_id="CONCEPT_07_159",
        loinc_num="17159-6",
        snomed_ct="100700159",
        component="Diagnostic Analyte Component 07-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_160": ClinicalConcept_07(
        concept_id="CONCEPT_07_160",
        loinc_num="17160-7",
        snomed_ct="100700160",
        component="Diagnostic Analyte Component 07-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_161": ClinicalConcept_07(
        concept_id="CONCEPT_07_161",
        loinc_num="17161-8",
        snomed_ct="100700161",
        component="Diagnostic Analyte Component 07-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_162": ClinicalConcept_07(
        concept_id="CONCEPT_07_162",
        loinc_num="17162-0",
        snomed_ct="100700162",
        component="Diagnostic Analyte Component 07-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_163": ClinicalConcept_07(
        concept_id="CONCEPT_07_163",
        loinc_num="17163-1",
        snomed_ct="100700163",
        component="Diagnostic Analyte Component 07-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_164": ClinicalConcept_07(
        concept_id="CONCEPT_07_164",
        loinc_num="17164-2",
        snomed_ct="100700164",
        component="Diagnostic Analyte Component 07-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_165": ClinicalConcept_07(
        concept_id="CONCEPT_07_165",
        loinc_num="17165-3",
        snomed_ct="100700165",
        component="Diagnostic Analyte Component 07-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_166": ClinicalConcept_07(
        concept_id="CONCEPT_07_166",
        loinc_num="17166-4",
        snomed_ct="100700166",
        component="Diagnostic Analyte Component 07-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_167": ClinicalConcept_07(
        concept_id="CONCEPT_07_167",
        loinc_num="17167-5",
        snomed_ct="100700167",
        component="Diagnostic Analyte Component 07-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_168": ClinicalConcept_07(
        concept_id="CONCEPT_07_168",
        loinc_num="17168-6",
        snomed_ct="100700168",
        component="Diagnostic Analyte Component 07-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_169": ClinicalConcept_07(
        concept_id="CONCEPT_07_169",
        loinc_num="17169-7",
        snomed_ct="100700169",
        component="Diagnostic Analyte Component 07-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_170": ClinicalConcept_07(
        concept_id="CONCEPT_07_170",
        loinc_num="17170-8",
        snomed_ct="100700170",
        component="Diagnostic Analyte Component 07-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_171": ClinicalConcept_07(
        concept_id="CONCEPT_07_171",
        loinc_num="17171-0",
        snomed_ct="100700171",
        component="Diagnostic Analyte Component 07-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_172": ClinicalConcept_07(
        concept_id="CONCEPT_07_172",
        loinc_num="17172-1",
        snomed_ct="100700172",
        component="Diagnostic Analyte Component 07-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_173": ClinicalConcept_07(
        concept_id="CONCEPT_07_173",
        loinc_num="17173-2",
        snomed_ct="100700173",
        component="Diagnostic Analyte Component 07-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_174": ClinicalConcept_07(
        concept_id="CONCEPT_07_174",
        loinc_num="17174-3",
        snomed_ct="100700174",
        component="Diagnostic Analyte Component 07-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_175": ClinicalConcept_07(
        concept_id="CONCEPT_07_175",
        loinc_num="17175-4",
        snomed_ct="100700175",
        component="Diagnostic Analyte Component 07-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_176": ClinicalConcept_07(
        concept_id="CONCEPT_07_176",
        loinc_num="17176-5",
        snomed_ct="100700176",
        component="Diagnostic Analyte Component 07-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_177": ClinicalConcept_07(
        concept_id="CONCEPT_07_177",
        loinc_num="17177-6",
        snomed_ct="100700177",
        component="Diagnostic Analyte Component 07-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_178": ClinicalConcept_07(
        concept_id="CONCEPT_07_178",
        loinc_num="17178-7",
        snomed_ct="100700178",
        component="Diagnostic Analyte Component 07-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_179": ClinicalConcept_07(
        concept_id="CONCEPT_07_179",
        loinc_num="17179-8",
        snomed_ct="100700179",
        component="Diagnostic Analyte Component 07-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_180": ClinicalConcept_07(
        concept_id="CONCEPT_07_180",
        loinc_num="17180-0",
        snomed_ct="100700180",
        component="Diagnostic Analyte Component 07-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_181": ClinicalConcept_07(
        concept_id="CONCEPT_07_181",
        loinc_num="17181-1",
        snomed_ct="100700181",
        component="Diagnostic Analyte Component 07-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_182": ClinicalConcept_07(
        concept_id="CONCEPT_07_182",
        loinc_num="17182-2",
        snomed_ct="100700182",
        component="Diagnostic Analyte Component 07-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_183": ClinicalConcept_07(
        concept_id="CONCEPT_07_183",
        loinc_num="17183-3",
        snomed_ct="100700183",
        component="Diagnostic Analyte Component 07-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_184": ClinicalConcept_07(
        concept_id="CONCEPT_07_184",
        loinc_num="17184-4",
        snomed_ct="100700184",
        component="Diagnostic Analyte Component 07-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_185": ClinicalConcept_07(
        concept_id="CONCEPT_07_185",
        loinc_num="17185-5",
        snomed_ct="100700185",
        component="Diagnostic Analyte Component 07-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_186": ClinicalConcept_07(
        concept_id="CONCEPT_07_186",
        loinc_num="17186-6",
        snomed_ct="100700186",
        component="Diagnostic Analyte Component 07-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_187": ClinicalConcept_07(
        concept_id="CONCEPT_07_187",
        loinc_num="17187-7",
        snomed_ct="100700187",
        component="Diagnostic Analyte Component 07-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_188": ClinicalConcept_07(
        concept_id="CONCEPT_07_188",
        loinc_num="17188-8",
        snomed_ct="100700188",
        component="Diagnostic Analyte Component 07-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_189": ClinicalConcept_07(
        concept_id="CONCEPT_07_189",
        loinc_num="17189-0",
        snomed_ct="100700189",
        component="Diagnostic Analyte Component 07-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_190": ClinicalConcept_07(
        concept_id="CONCEPT_07_190",
        loinc_num="17190-1",
        snomed_ct="100700190",
        component="Diagnostic Analyte Component 07-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_191": ClinicalConcept_07(
        concept_id="CONCEPT_07_191",
        loinc_num="17191-2",
        snomed_ct="100700191",
        component="Diagnostic Analyte Component 07-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_192": ClinicalConcept_07(
        concept_id="CONCEPT_07_192",
        loinc_num="17192-3",
        snomed_ct="100700192",
        component="Diagnostic Analyte Component 07-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_193": ClinicalConcept_07(
        concept_id="CONCEPT_07_193",
        loinc_num="17193-4",
        snomed_ct="100700193",
        component="Diagnostic Analyte Component 07-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_194": ClinicalConcept_07(
        concept_id="CONCEPT_07_194",
        loinc_num="17194-5",
        snomed_ct="100700194",
        component="Diagnostic Analyte Component 07-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_195": ClinicalConcept_07(
        concept_id="CONCEPT_07_195",
        loinc_num="17195-6",
        snomed_ct="100700195",
        component="Diagnostic Analyte Component 07-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_196": ClinicalConcept_07(
        concept_id="CONCEPT_07_196",
        loinc_num="17196-7",
        snomed_ct="100700196",
        component="Diagnostic Analyte Component 07-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_197": ClinicalConcept_07(
        concept_id="CONCEPT_07_197",
        loinc_num="17197-8",
        snomed_ct="100700197",
        component="Diagnostic Analyte Component 07-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_198": ClinicalConcept_07(
        concept_id="CONCEPT_07_198",
        loinc_num="17198-0",
        snomed_ct="100700198",
        component="Diagnostic Analyte Component 07-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_07_199": ClinicalConcept_07(
        concept_id="CONCEPT_07_199",
        loinc_num="17199-1",
        snomed_ct="100700199",
        component="Diagnostic Analyte Component 07-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
