"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 08"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_08:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_08 = {
    "CONCEPT_08_001": ClinicalConcept_08(
        concept_id="CONCEPT_08_001",
        loinc_num="18001-1",
        snomed_ct="100800001",
        component="Diagnostic Analyte Component 08-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_002": ClinicalConcept_08(
        concept_id="CONCEPT_08_002",
        loinc_num="18002-2",
        snomed_ct="100800002",
        component="Diagnostic Analyte Component 08-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_003": ClinicalConcept_08(
        concept_id="CONCEPT_08_003",
        loinc_num="18003-3",
        snomed_ct="100800003",
        component="Diagnostic Analyte Component 08-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_004": ClinicalConcept_08(
        concept_id="CONCEPT_08_004",
        loinc_num="18004-4",
        snomed_ct="100800004",
        component="Diagnostic Analyte Component 08-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_005": ClinicalConcept_08(
        concept_id="CONCEPT_08_005",
        loinc_num="18005-5",
        snomed_ct="100800005",
        component="Diagnostic Analyte Component 08-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_006": ClinicalConcept_08(
        concept_id="CONCEPT_08_006",
        loinc_num="18006-6",
        snomed_ct="100800006",
        component="Diagnostic Analyte Component 08-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_007": ClinicalConcept_08(
        concept_id="CONCEPT_08_007",
        loinc_num="18007-7",
        snomed_ct="100800007",
        component="Diagnostic Analyte Component 08-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_008": ClinicalConcept_08(
        concept_id="CONCEPT_08_008",
        loinc_num="18008-8",
        snomed_ct="100800008",
        component="Diagnostic Analyte Component 08-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_009": ClinicalConcept_08(
        concept_id="CONCEPT_08_009",
        loinc_num="18009-0",
        snomed_ct="100800009",
        component="Diagnostic Analyte Component 08-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_010": ClinicalConcept_08(
        concept_id="CONCEPT_08_010",
        loinc_num="18010-1",
        snomed_ct="100800010",
        component="Diagnostic Analyte Component 08-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_011": ClinicalConcept_08(
        concept_id="CONCEPT_08_011",
        loinc_num="18011-2",
        snomed_ct="100800011",
        component="Diagnostic Analyte Component 08-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_012": ClinicalConcept_08(
        concept_id="CONCEPT_08_012",
        loinc_num="18012-3",
        snomed_ct="100800012",
        component="Diagnostic Analyte Component 08-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_013": ClinicalConcept_08(
        concept_id="CONCEPT_08_013",
        loinc_num="18013-4",
        snomed_ct="100800013",
        component="Diagnostic Analyte Component 08-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_014": ClinicalConcept_08(
        concept_id="CONCEPT_08_014",
        loinc_num="18014-5",
        snomed_ct="100800014",
        component="Diagnostic Analyte Component 08-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_015": ClinicalConcept_08(
        concept_id="CONCEPT_08_015",
        loinc_num="18015-6",
        snomed_ct="100800015",
        component="Diagnostic Analyte Component 08-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_016": ClinicalConcept_08(
        concept_id="CONCEPT_08_016",
        loinc_num="18016-7",
        snomed_ct="100800016",
        component="Diagnostic Analyte Component 08-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_017": ClinicalConcept_08(
        concept_id="CONCEPT_08_017",
        loinc_num="18017-8",
        snomed_ct="100800017",
        component="Diagnostic Analyte Component 08-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_018": ClinicalConcept_08(
        concept_id="CONCEPT_08_018",
        loinc_num="18018-0",
        snomed_ct="100800018",
        component="Diagnostic Analyte Component 08-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_019": ClinicalConcept_08(
        concept_id="CONCEPT_08_019",
        loinc_num="18019-1",
        snomed_ct="100800019",
        component="Diagnostic Analyte Component 08-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_020": ClinicalConcept_08(
        concept_id="CONCEPT_08_020",
        loinc_num="18020-2",
        snomed_ct="100800020",
        component="Diagnostic Analyte Component 08-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_021": ClinicalConcept_08(
        concept_id="CONCEPT_08_021",
        loinc_num="18021-3",
        snomed_ct="100800021",
        component="Diagnostic Analyte Component 08-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_022": ClinicalConcept_08(
        concept_id="CONCEPT_08_022",
        loinc_num="18022-4",
        snomed_ct="100800022",
        component="Diagnostic Analyte Component 08-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_023": ClinicalConcept_08(
        concept_id="CONCEPT_08_023",
        loinc_num="18023-5",
        snomed_ct="100800023",
        component="Diagnostic Analyte Component 08-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_024": ClinicalConcept_08(
        concept_id="CONCEPT_08_024",
        loinc_num="18024-6",
        snomed_ct="100800024",
        component="Diagnostic Analyte Component 08-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_025": ClinicalConcept_08(
        concept_id="CONCEPT_08_025",
        loinc_num="18025-7",
        snomed_ct="100800025",
        component="Diagnostic Analyte Component 08-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_026": ClinicalConcept_08(
        concept_id="CONCEPT_08_026",
        loinc_num="18026-8",
        snomed_ct="100800026",
        component="Diagnostic Analyte Component 08-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_027": ClinicalConcept_08(
        concept_id="CONCEPT_08_027",
        loinc_num="18027-0",
        snomed_ct="100800027",
        component="Diagnostic Analyte Component 08-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_028": ClinicalConcept_08(
        concept_id="CONCEPT_08_028",
        loinc_num="18028-1",
        snomed_ct="100800028",
        component="Diagnostic Analyte Component 08-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_029": ClinicalConcept_08(
        concept_id="CONCEPT_08_029",
        loinc_num="18029-2",
        snomed_ct="100800029",
        component="Diagnostic Analyte Component 08-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_030": ClinicalConcept_08(
        concept_id="CONCEPT_08_030",
        loinc_num="18030-3",
        snomed_ct="100800030",
        component="Diagnostic Analyte Component 08-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_031": ClinicalConcept_08(
        concept_id="CONCEPT_08_031",
        loinc_num="18031-4",
        snomed_ct="100800031",
        component="Diagnostic Analyte Component 08-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_032": ClinicalConcept_08(
        concept_id="CONCEPT_08_032",
        loinc_num="18032-5",
        snomed_ct="100800032",
        component="Diagnostic Analyte Component 08-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_033": ClinicalConcept_08(
        concept_id="CONCEPT_08_033",
        loinc_num="18033-6",
        snomed_ct="100800033",
        component="Diagnostic Analyte Component 08-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_034": ClinicalConcept_08(
        concept_id="CONCEPT_08_034",
        loinc_num="18034-7",
        snomed_ct="100800034",
        component="Diagnostic Analyte Component 08-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_035": ClinicalConcept_08(
        concept_id="CONCEPT_08_035",
        loinc_num="18035-8",
        snomed_ct="100800035",
        component="Diagnostic Analyte Component 08-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_036": ClinicalConcept_08(
        concept_id="CONCEPT_08_036",
        loinc_num="18036-0",
        snomed_ct="100800036",
        component="Diagnostic Analyte Component 08-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_037": ClinicalConcept_08(
        concept_id="CONCEPT_08_037",
        loinc_num="18037-1",
        snomed_ct="100800037",
        component="Diagnostic Analyte Component 08-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_038": ClinicalConcept_08(
        concept_id="CONCEPT_08_038",
        loinc_num="18038-2",
        snomed_ct="100800038",
        component="Diagnostic Analyte Component 08-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_039": ClinicalConcept_08(
        concept_id="CONCEPT_08_039",
        loinc_num="18039-3",
        snomed_ct="100800039",
        component="Diagnostic Analyte Component 08-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_040": ClinicalConcept_08(
        concept_id="CONCEPT_08_040",
        loinc_num="18040-4",
        snomed_ct="100800040",
        component="Diagnostic Analyte Component 08-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_041": ClinicalConcept_08(
        concept_id="CONCEPT_08_041",
        loinc_num="18041-5",
        snomed_ct="100800041",
        component="Diagnostic Analyte Component 08-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_042": ClinicalConcept_08(
        concept_id="CONCEPT_08_042",
        loinc_num="18042-6",
        snomed_ct="100800042",
        component="Diagnostic Analyte Component 08-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_043": ClinicalConcept_08(
        concept_id="CONCEPT_08_043",
        loinc_num="18043-7",
        snomed_ct="100800043",
        component="Diagnostic Analyte Component 08-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_044": ClinicalConcept_08(
        concept_id="CONCEPT_08_044",
        loinc_num="18044-8",
        snomed_ct="100800044",
        component="Diagnostic Analyte Component 08-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_045": ClinicalConcept_08(
        concept_id="CONCEPT_08_045",
        loinc_num="18045-0",
        snomed_ct="100800045",
        component="Diagnostic Analyte Component 08-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_046": ClinicalConcept_08(
        concept_id="CONCEPT_08_046",
        loinc_num="18046-1",
        snomed_ct="100800046",
        component="Diagnostic Analyte Component 08-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_047": ClinicalConcept_08(
        concept_id="CONCEPT_08_047",
        loinc_num="18047-2",
        snomed_ct="100800047",
        component="Diagnostic Analyte Component 08-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_048": ClinicalConcept_08(
        concept_id="CONCEPT_08_048",
        loinc_num="18048-3",
        snomed_ct="100800048",
        component="Diagnostic Analyte Component 08-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_049": ClinicalConcept_08(
        concept_id="CONCEPT_08_049",
        loinc_num="18049-4",
        snomed_ct="100800049",
        component="Diagnostic Analyte Component 08-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_050": ClinicalConcept_08(
        concept_id="CONCEPT_08_050",
        loinc_num="18050-5",
        snomed_ct="100800050",
        component="Diagnostic Analyte Component 08-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_051": ClinicalConcept_08(
        concept_id="CONCEPT_08_051",
        loinc_num="18051-6",
        snomed_ct="100800051",
        component="Diagnostic Analyte Component 08-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_052": ClinicalConcept_08(
        concept_id="CONCEPT_08_052",
        loinc_num="18052-7",
        snomed_ct="100800052",
        component="Diagnostic Analyte Component 08-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_053": ClinicalConcept_08(
        concept_id="CONCEPT_08_053",
        loinc_num="18053-8",
        snomed_ct="100800053",
        component="Diagnostic Analyte Component 08-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_054": ClinicalConcept_08(
        concept_id="CONCEPT_08_054",
        loinc_num="18054-0",
        snomed_ct="100800054",
        component="Diagnostic Analyte Component 08-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_055": ClinicalConcept_08(
        concept_id="CONCEPT_08_055",
        loinc_num="18055-1",
        snomed_ct="100800055",
        component="Diagnostic Analyte Component 08-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_056": ClinicalConcept_08(
        concept_id="CONCEPT_08_056",
        loinc_num="18056-2",
        snomed_ct="100800056",
        component="Diagnostic Analyte Component 08-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_057": ClinicalConcept_08(
        concept_id="CONCEPT_08_057",
        loinc_num="18057-3",
        snomed_ct="100800057",
        component="Diagnostic Analyte Component 08-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_058": ClinicalConcept_08(
        concept_id="CONCEPT_08_058",
        loinc_num="18058-4",
        snomed_ct="100800058",
        component="Diagnostic Analyte Component 08-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_059": ClinicalConcept_08(
        concept_id="CONCEPT_08_059",
        loinc_num="18059-5",
        snomed_ct="100800059",
        component="Diagnostic Analyte Component 08-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_060": ClinicalConcept_08(
        concept_id="CONCEPT_08_060",
        loinc_num="18060-6",
        snomed_ct="100800060",
        component="Diagnostic Analyte Component 08-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_061": ClinicalConcept_08(
        concept_id="CONCEPT_08_061",
        loinc_num="18061-7",
        snomed_ct="100800061",
        component="Diagnostic Analyte Component 08-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_062": ClinicalConcept_08(
        concept_id="CONCEPT_08_062",
        loinc_num="18062-8",
        snomed_ct="100800062",
        component="Diagnostic Analyte Component 08-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_063": ClinicalConcept_08(
        concept_id="CONCEPT_08_063",
        loinc_num="18063-0",
        snomed_ct="100800063",
        component="Diagnostic Analyte Component 08-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_064": ClinicalConcept_08(
        concept_id="CONCEPT_08_064",
        loinc_num="18064-1",
        snomed_ct="100800064",
        component="Diagnostic Analyte Component 08-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_065": ClinicalConcept_08(
        concept_id="CONCEPT_08_065",
        loinc_num="18065-2",
        snomed_ct="100800065",
        component="Diagnostic Analyte Component 08-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_066": ClinicalConcept_08(
        concept_id="CONCEPT_08_066",
        loinc_num="18066-3",
        snomed_ct="100800066",
        component="Diagnostic Analyte Component 08-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_067": ClinicalConcept_08(
        concept_id="CONCEPT_08_067",
        loinc_num="18067-4",
        snomed_ct="100800067",
        component="Diagnostic Analyte Component 08-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_068": ClinicalConcept_08(
        concept_id="CONCEPT_08_068",
        loinc_num="18068-5",
        snomed_ct="100800068",
        component="Diagnostic Analyte Component 08-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_069": ClinicalConcept_08(
        concept_id="CONCEPT_08_069",
        loinc_num="18069-6",
        snomed_ct="100800069",
        component="Diagnostic Analyte Component 08-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_070": ClinicalConcept_08(
        concept_id="CONCEPT_08_070",
        loinc_num="18070-7",
        snomed_ct="100800070",
        component="Diagnostic Analyte Component 08-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_071": ClinicalConcept_08(
        concept_id="CONCEPT_08_071",
        loinc_num="18071-8",
        snomed_ct="100800071",
        component="Diagnostic Analyte Component 08-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_072": ClinicalConcept_08(
        concept_id="CONCEPT_08_072",
        loinc_num="18072-0",
        snomed_ct="100800072",
        component="Diagnostic Analyte Component 08-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_073": ClinicalConcept_08(
        concept_id="CONCEPT_08_073",
        loinc_num="18073-1",
        snomed_ct="100800073",
        component="Diagnostic Analyte Component 08-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_074": ClinicalConcept_08(
        concept_id="CONCEPT_08_074",
        loinc_num="18074-2",
        snomed_ct="100800074",
        component="Diagnostic Analyte Component 08-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_075": ClinicalConcept_08(
        concept_id="CONCEPT_08_075",
        loinc_num="18075-3",
        snomed_ct="100800075",
        component="Diagnostic Analyte Component 08-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_076": ClinicalConcept_08(
        concept_id="CONCEPT_08_076",
        loinc_num="18076-4",
        snomed_ct="100800076",
        component="Diagnostic Analyte Component 08-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_077": ClinicalConcept_08(
        concept_id="CONCEPT_08_077",
        loinc_num="18077-5",
        snomed_ct="100800077",
        component="Diagnostic Analyte Component 08-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_078": ClinicalConcept_08(
        concept_id="CONCEPT_08_078",
        loinc_num="18078-6",
        snomed_ct="100800078",
        component="Diagnostic Analyte Component 08-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_079": ClinicalConcept_08(
        concept_id="CONCEPT_08_079",
        loinc_num="18079-7",
        snomed_ct="100800079",
        component="Diagnostic Analyte Component 08-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_080": ClinicalConcept_08(
        concept_id="CONCEPT_08_080",
        loinc_num="18080-8",
        snomed_ct="100800080",
        component="Diagnostic Analyte Component 08-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_081": ClinicalConcept_08(
        concept_id="CONCEPT_08_081",
        loinc_num="18081-0",
        snomed_ct="100800081",
        component="Diagnostic Analyte Component 08-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_082": ClinicalConcept_08(
        concept_id="CONCEPT_08_082",
        loinc_num="18082-1",
        snomed_ct="100800082",
        component="Diagnostic Analyte Component 08-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_083": ClinicalConcept_08(
        concept_id="CONCEPT_08_083",
        loinc_num="18083-2",
        snomed_ct="100800083",
        component="Diagnostic Analyte Component 08-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_084": ClinicalConcept_08(
        concept_id="CONCEPT_08_084",
        loinc_num="18084-3",
        snomed_ct="100800084",
        component="Diagnostic Analyte Component 08-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_085": ClinicalConcept_08(
        concept_id="CONCEPT_08_085",
        loinc_num="18085-4",
        snomed_ct="100800085",
        component="Diagnostic Analyte Component 08-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_086": ClinicalConcept_08(
        concept_id="CONCEPT_08_086",
        loinc_num="18086-5",
        snomed_ct="100800086",
        component="Diagnostic Analyte Component 08-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_087": ClinicalConcept_08(
        concept_id="CONCEPT_08_087",
        loinc_num="18087-6",
        snomed_ct="100800087",
        component="Diagnostic Analyte Component 08-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_088": ClinicalConcept_08(
        concept_id="CONCEPT_08_088",
        loinc_num="18088-7",
        snomed_ct="100800088",
        component="Diagnostic Analyte Component 08-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_089": ClinicalConcept_08(
        concept_id="CONCEPT_08_089",
        loinc_num="18089-8",
        snomed_ct="100800089",
        component="Diagnostic Analyte Component 08-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_090": ClinicalConcept_08(
        concept_id="CONCEPT_08_090",
        loinc_num="18090-0",
        snomed_ct="100800090",
        component="Diagnostic Analyte Component 08-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_091": ClinicalConcept_08(
        concept_id="CONCEPT_08_091",
        loinc_num="18091-1",
        snomed_ct="100800091",
        component="Diagnostic Analyte Component 08-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_092": ClinicalConcept_08(
        concept_id="CONCEPT_08_092",
        loinc_num="18092-2",
        snomed_ct="100800092",
        component="Diagnostic Analyte Component 08-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_093": ClinicalConcept_08(
        concept_id="CONCEPT_08_093",
        loinc_num="18093-3",
        snomed_ct="100800093",
        component="Diagnostic Analyte Component 08-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_094": ClinicalConcept_08(
        concept_id="CONCEPT_08_094",
        loinc_num="18094-4",
        snomed_ct="100800094",
        component="Diagnostic Analyte Component 08-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_095": ClinicalConcept_08(
        concept_id="CONCEPT_08_095",
        loinc_num="18095-5",
        snomed_ct="100800095",
        component="Diagnostic Analyte Component 08-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_096": ClinicalConcept_08(
        concept_id="CONCEPT_08_096",
        loinc_num="18096-6",
        snomed_ct="100800096",
        component="Diagnostic Analyte Component 08-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_097": ClinicalConcept_08(
        concept_id="CONCEPT_08_097",
        loinc_num="18097-7",
        snomed_ct="100800097",
        component="Diagnostic Analyte Component 08-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_098": ClinicalConcept_08(
        concept_id="CONCEPT_08_098",
        loinc_num="18098-8",
        snomed_ct="100800098",
        component="Diagnostic Analyte Component 08-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_099": ClinicalConcept_08(
        concept_id="CONCEPT_08_099",
        loinc_num="18099-0",
        snomed_ct="100800099",
        component="Diagnostic Analyte Component 08-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_100": ClinicalConcept_08(
        concept_id="CONCEPT_08_100",
        loinc_num="18100-1",
        snomed_ct="100800100",
        component="Diagnostic Analyte Component 08-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_101": ClinicalConcept_08(
        concept_id="CONCEPT_08_101",
        loinc_num="18101-2",
        snomed_ct="100800101",
        component="Diagnostic Analyte Component 08-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_102": ClinicalConcept_08(
        concept_id="CONCEPT_08_102",
        loinc_num="18102-3",
        snomed_ct="100800102",
        component="Diagnostic Analyte Component 08-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_103": ClinicalConcept_08(
        concept_id="CONCEPT_08_103",
        loinc_num="18103-4",
        snomed_ct="100800103",
        component="Diagnostic Analyte Component 08-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_104": ClinicalConcept_08(
        concept_id="CONCEPT_08_104",
        loinc_num="18104-5",
        snomed_ct="100800104",
        component="Diagnostic Analyte Component 08-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_105": ClinicalConcept_08(
        concept_id="CONCEPT_08_105",
        loinc_num="18105-6",
        snomed_ct="100800105",
        component="Diagnostic Analyte Component 08-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_106": ClinicalConcept_08(
        concept_id="CONCEPT_08_106",
        loinc_num="18106-7",
        snomed_ct="100800106",
        component="Diagnostic Analyte Component 08-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_107": ClinicalConcept_08(
        concept_id="CONCEPT_08_107",
        loinc_num="18107-8",
        snomed_ct="100800107",
        component="Diagnostic Analyte Component 08-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_108": ClinicalConcept_08(
        concept_id="CONCEPT_08_108",
        loinc_num="18108-0",
        snomed_ct="100800108",
        component="Diagnostic Analyte Component 08-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_109": ClinicalConcept_08(
        concept_id="CONCEPT_08_109",
        loinc_num="18109-1",
        snomed_ct="100800109",
        component="Diagnostic Analyte Component 08-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_110": ClinicalConcept_08(
        concept_id="CONCEPT_08_110",
        loinc_num="18110-2",
        snomed_ct="100800110",
        component="Diagnostic Analyte Component 08-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_111": ClinicalConcept_08(
        concept_id="CONCEPT_08_111",
        loinc_num="18111-3",
        snomed_ct="100800111",
        component="Diagnostic Analyte Component 08-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_112": ClinicalConcept_08(
        concept_id="CONCEPT_08_112",
        loinc_num="18112-4",
        snomed_ct="100800112",
        component="Diagnostic Analyte Component 08-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_113": ClinicalConcept_08(
        concept_id="CONCEPT_08_113",
        loinc_num="18113-5",
        snomed_ct="100800113",
        component="Diagnostic Analyte Component 08-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_114": ClinicalConcept_08(
        concept_id="CONCEPT_08_114",
        loinc_num="18114-6",
        snomed_ct="100800114",
        component="Diagnostic Analyte Component 08-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_115": ClinicalConcept_08(
        concept_id="CONCEPT_08_115",
        loinc_num="18115-7",
        snomed_ct="100800115",
        component="Diagnostic Analyte Component 08-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_116": ClinicalConcept_08(
        concept_id="CONCEPT_08_116",
        loinc_num="18116-8",
        snomed_ct="100800116",
        component="Diagnostic Analyte Component 08-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_117": ClinicalConcept_08(
        concept_id="CONCEPT_08_117",
        loinc_num="18117-0",
        snomed_ct="100800117",
        component="Diagnostic Analyte Component 08-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_118": ClinicalConcept_08(
        concept_id="CONCEPT_08_118",
        loinc_num="18118-1",
        snomed_ct="100800118",
        component="Diagnostic Analyte Component 08-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_119": ClinicalConcept_08(
        concept_id="CONCEPT_08_119",
        loinc_num="18119-2",
        snomed_ct="100800119",
        component="Diagnostic Analyte Component 08-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_120": ClinicalConcept_08(
        concept_id="CONCEPT_08_120",
        loinc_num="18120-3",
        snomed_ct="100800120",
        component="Diagnostic Analyte Component 08-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_121": ClinicalConcept_08(
        concept_id="CONCEPT_08_121",
        loinc_num="18121-4",
        snomed_ct="100800121",
        component="Diagnostic Analyte Component 08-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_122": ClinicalConcept_08(
        concept_id="CONCEPT_08_122",
        loinc_num="18122-5",
        snomed_ct="100800122",
        component="Diagnostic Analyte Component 08-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_123": ClinicalConcept_08(
        concept_id="CONCEPT_08_123",
        loinc_num="18123-6",
        snomed_ct="100800123",
        component="Diagnostic Analyte Component 08-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_124": ClinicalConcept_08(
        concept_id="CONCEPT_08_124",
        loinc_num="18124-7",
        snomed_ct="100800124",
        component="Diagnostic Analyte Component 08-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_125": ClinicalConcept_08(
        concept_id="CONCEPT_08_125",
        loinc_num="18125-8",
        snomed_ct="100800125",
        component="Diagnostic Analyte Component 08-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_126": ClinicalConcept_08(
        concept_id="CONCEPT_08_126",
        loinc_num="18126-0",
        snomed_ct="100800126",
        component="Diagnostic Analyte Component 08-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_127": ClinicalConcept_08(
        concept_id="CONCEPT_08_127",
        loinc_num="18127-1",
        snomed_ct="100800127",
        component="Diagnostic Analyte Component 08-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_128": ClinicalConcept_08(
        concept_id="CONCEPT_08_128",
        loinc_num="18128-2",
        snomed_ct="100800128",
        component="Diagnostic Analyte Component 08-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_129": ClinicalConcept_08(
        concept_id="CONCEPT_08_129",
        loinc_num="18129-3",
        snomed_ct="100800129",
        component="Diagnostic Analyte Component 08-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_130": ClinicalConcept_08(
        concept_id="CONCEPT_08_130",
        loinc_num="18130-4",
        snomed_ct="100800130",
        component="Diagnostic Analyte Component 08-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_131": ClinicalConcept_08(
        concept_id="CONCEPT_08_131",
        loinc_num="18131-5",
        snomed_ct="100800131",
        component="Diagnostic Analyte Component 08-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_132": ClinicalConcept_08(
        concept_id="CONCEPT_08_132",
        loinc_num="18132-6",
        snomed_ct="100800132",
        component="Diagnostic Analyte Component 08-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_133": ClinicalConcept_08(
        concept_id="CONCEPT_08_133",
        loinc_num="18133-7",
        snomed_ct="100800133",
        component="Diagnostic Analyte Component 08-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_134": ClinicalConcept_08(
        concept_id="CONCEPT_08_134",
        loinc_num="18134-8",
        snomed_ct="100800134",
        component="Diagnostic Analyte Component 08-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_135": ClinicalConcept_08(
        concept_id="CONCEPT_08_135",
        loinc_num="18135-0",
        snomed_ct="100800135",
        component="Diagnostic Analyte Component 08-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_136": ClinicalConcept_08(
        concept_id="CONCEPT_08_136",
        loinc_num="18136-1",
        snomed_ct="100800136",
        component="Diagnostic Analyte Component 08-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_137": ClinicalConcept_08(
        concept_id="CONCEPT_08_137",
        loinc_num="18137-2",
        snomed_ct="100800137",
        component="Diagnostic Analyte Component 08-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_138": ClinicalConcept_08(
        concept_id="CONCEPT_08_138",
        loinc_num="18138-3",
        snomed_ct="100800138",
        component="Diagnostic Analyte Component 08-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_139": ClinicalConcept_08(
        concept_id="CONCEPT_08_139",
        loinc_num="18139-4",
        snomed_ct="100800139",
        component="Diagnostic Analyte Component 08-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_140": ClinicalConcept_08(
        concept_id="CONCEPT_08_140",
        loinc_num="18140-5",
        snomed_ct="100800140",
        component="Diagnostic Analyte Component 08-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_141": ClinicalConcept_08(
        concept_id="CONCEPT_08_141",
        loinc_num="18141-6",
        snomed_ct="100800141",
        component="Diagnostic Analyte Component 08-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_142": ClinicalConcept_08(
        concept_id="CONCEPT_08_142",
        loinc_num="18142-7",
        snomed_ct="100800142",
        component="Diagnostic Analyte Component 08-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_143": ClinicalConcept_08(
        concept_id="CONCEPT_08_143",
        loinc_num="18143-8",
        snomed_ct="100800143",
        component="Diagnostic Analyte Component 08-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_144": ClinicalConcept_08(
        concept_id="CONCEPT_08_144",
        loinc_num="18144-0",
        snomed_ct="100800144",
        component="Diagnostic Analyte Component 08-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_145": ClinicalConcept_08(
        concept_id="CONCEPT_08_145",
        loinc_num="18145-1",
        snomed_ct="100800145",
        component="Diagnostic Analyte Component 08-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_146": ClinicalConcept_08(
        concept_id="CONCEPT_08_146",
        loinc_num="18146-2",
        snomed_ct="100800146",
        component="Diagnostic Analyte Component 08-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_147": ClinicalConcept_08(
        concept_id="CONCEPT_08_147",
        loinc_num="18147-3",
        snomed_ct="100800147",
        component="Diagnostic Analyte Component 08-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_148": ClinicalConcept_08(
        concept_id="CONCEPT_08_148",
        loinc_num="18148-4",
        snomed_ct="100800148",
        component="Diagnostic Analyte Component 08-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_149": ClinicalConcept_08(
        concept_id="CONCEPT_08_149",
        loinc_num="18149-5",
        snomed_ct="100800149",
        component="Diagnostic Analyte Component 08-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_150": ClinicalConcept_08(
        concept_id="CONCEPT_08_150",
        loinc_num="18150-6",
        snomed_ct="100800150",
        component="Diagnostic Analyte Component 08-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_151": ClinicalConcept_08(
        concept_id="CONCEPT_08_151",
        loinc_num="18151-7",
        snomed_ct="100800151",
        component="Diagnostic Analyte Component 08-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_152": ClinicalConcept_08(
        concept_id="CONCEPT_08_152",
        loinc_num="18152-8",
        snomed_ct="100800152",
        component="Diagnostic Analyte Component 08-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_153": ClinicalConcept_08(
        concept_id="CONCEPT_08_153",
        loinc_num="18153-0",
        snomed_ct="100800153",
        component="Diagnostic Analyte Component 08-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_154": ClinicalConcept_08(
        concept_id="CONCEPT_08_154",
        loinc_num="18154-1",
        snomed_ct="100800154",
        component="Diagnostic Analyte Component 08-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_155": ClinicalConcept_08(
        concept_id="CONCEPT_08_155",
        loinc_num="18155-2",
        snomed_ct="100800155",
        component="Diagnostic Analyte Component 08-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_156": ClinicalConcept_08(
        concept_id="CONCEPT_08_156",
        loinc_num="18156-3",
        snomed_ct="100800156",
        component="Diagnostic Analyte Component 08-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_157": ClinicalConcept_08(
        concept_id="CONCEPT_08_157",
        loinc_num="18157-4",
        snomed_ct="100800157",
        component="Diagnostic Analyte Component 08-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_158": ClinicalConcept_08(
        concept_id="CONCEPT_08_158",
        loinc_num="18158-5",
        snomed_ct="100800158",
        component="Diagnostic Analyte Component 08-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_159": ClinicalConcept_08(
        concept_id="CONCEPT_08_159",
        loinc_num="18159-6",
        snomed_ct="100800159",
        component="Diagnostic Analyte Component 08-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_160": ClinicalConcept_08(
        concept_id="CONCEPT_08_160",
        loinc_num="18160-7",
        snomed_ct="100800160",
        component="Diagnostic Analyte Component 08-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_161": ClinicalConcept_08(
        concept_id="CONCEPT_08_161",
        loinc_num="18161-8",
        snomed_ct="100800161",
        component="Diagnostic Analyte Component 08-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_162": ClinicalConcept_08(
        concept_id="CONCEPT_08_162",
        loinc_num="18162-0",
        snomed_ct="100800162",
        component="Diagnostic Analyte Component 08-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_163": ClinicalConcept_08(
        concept_id="CONCEPT_08_163",
        loinc_num="18163-1",
        snomed_ct="100800163",
        component="Diagnostic Analyte Component 08-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_164": ClinicalConcept_08(
        concept_id="CONCEPT_08_164",
        loinc_num="18164-2",
        snomed_ct="100800164",
        component="Diagnostic Analyte Component 08-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_165": ClinicalConcept_08(
        concept_id="CONCEPT_08_165",
        loinc_num="18165-3",
        snomed_ct="100800165",
        component="Diagnostic Analyte Component 08-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_166": ClinicalConcept_08(
        concept_id="CONCEPT_08_166",
        loinc_num="18166-4",
        snomed_ct="100800166",
        component="Diagnostic Analyte Component 08-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_167": ClinicalConcept_08(
        concept_id="CONCEPT_08_167",
        loinc_num="18167-5",
        snomed_ct="100800167",
        component="Diagnostic Analyte Component 08-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_168": ClinicalConcept_08(
        concept_id="CONCEPT_08_168",
        loinc_num="18168-6",
        snomed_ct="100800168",
        component="Diagnostic Analyte Component 08-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_169": ClinicalConcept_08(
        concept_id="CONCEPT_08_169",
        loinc_num="18169-7",
        snomed_ct="100800169",
        component="Diagnostic Analyte Component 08-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_170": ClinicalConcept_08(
        concept_id="CONCEPT_08_170",
        loinc_num="18170-8",
        snomed_ct="100800170",
        component="Diagnostic Analyte Component 08-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_171": ClinicalConcept_08(
        concept_id="CONCEPT_08_171",
        loinc_num="18171-0",
        snomed_ct="100800171",
        component="Diagnostic Analyte Component 08-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_172": ClinicalConcept_08(
        concept_id="CONCEPT_08_172",
        loinc_num="18172-1",
        snomed_ct="100800172",
        component="Diagnostic Analyte Component 08-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_173": ClinicalConcept_08(
        concept_id="CONCEPT_08_173",
        loinc_num="18173-2",
        snomed_ct="100800173",
        component="Diagnostic Analyte Component 08-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_174": ClinicalConcept_08(
        concept_id="CONCEPT_08_174",
        loinc_num="18174-3",
        snomed_ct="100800174",
        component="Diagnostic Analyte Component 08-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_175": ClinicalConcept_08(
        concept_id="CONCEPT_08_175",
        loinc_num="18175-4",
        snomed_ct="100800175",
        component="Diagnostic Analyte Component 08-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_176": ClinicalConcept_08(
        concept_id="CONCEPT_08_176",
        loinc_num="18176-5",
        snomed_ct="100800176",
        component="Diagnostic Analyte Component 08-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_177": ClinicalConcept_08(
        concept_id="CONCEPT_08_177",
        loinc_num="18177-6",
        snomed_ct="100800177",
        component="Diagnostic Analyte Component 08-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_178": ClinicalConcept_08(
        concept_id="CONCEPT_08_178",
        loinc_num="18178-7",
        snomed_ct="100800178",
        component="Diagnostic Analyte Component 08-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_179": ClinicalConcept_08(
        concept_id="CONCEPT_08_179",
        loinc_num="18179-8",
        snomed_ct="100800179",
        component="Diagnostic Analyte Component 08-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_180": ClinicalConcept_08(
        concept_id="CONCEPT_08_180",
        loinc_num="18180-0",
        snomed_ct="100800180",
        component="Diagnostic Analyte Component 08-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_181": ClinicalConcept_08(
        concept_id="CONCEPT_08_181",
        loinc_num="18181-1",
        snomed_ct="100800181",
        component="Diagnostic Analyte Component 08-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_182": ClinicalConcept_08(
        concept_id="CONCEPT_08_182",
        loinc_num="18182-2",
        snomed_ct="100800182",
        component="Diagnostic Analyte Component 08-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_183": ClinicalConcept_08(
        concept_id="CONCEPT_08_183",
        loinc_num="18183-3",
        snomed_ct="100800183",
        component="Diagnostic Analyte Component 08-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_184": ClinicalConcept_08(
        concept_id="CONCEPT_08_184",
        loinc_num="18184-4",
        snomed_ct="100800184",
        component="Diagnostic Analyte Component 08-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_185": ClinicalConcept_08(
        concept_id="CONCEPT_08_185",
        loinc_num="18185-5",
        snomed_ct="100800185",
        component="Diagnostic Analyte Component 08-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_186": ClinicalConcept_08(
        concept_id="CONCEPT_08_186",
        loinc_num="18186-6",
        snomed_ct="100800186",
        component="Diagnostic Analyte Component 08-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_187": ClinicalConcept_08(
        concept_id="CONCEPT_08_187",
        loinc_num="18187-7",
        snomed_ct="100800187",
        component="Diagnostic Analyte Component 08-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_188": ClinicalConcept_08(
        concept_id="CONCEPT_08_188",
        loinc_num="18188-8",
        snomed_ct="100800188",
        component="Diagnostic Analyte Component 08-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_189": ClinicalConcept_08(
        concept_id="CONCEPT_08_189",
        loinc_num="18189-0",
        snomed_ct="100800189",
        component="Diagnostic Analyte Component 08-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_190": ClinicalConcept_08(
        concept_id="CONCEPT_08_190",
        loinc_num="18190-1",
        snomed_ct="100800190",
        component="Diagnostic Analyte Component 08-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_191": ClinicalConcept_08(
        concept_id="CONCEPT_08_191",
        loinc_num="18191-2",
        snomed_ct="100800191",
        component="Diagnostic Analyte Component 08-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_192": ClinicalConcept_08(
        concept_id="CONCEPT_08_192",
        loinc_num="18192-3",
        snomed_ct="100800192",
        component="Diagnostic Analyte Component 08-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_193": ClinicalConcept_08(
        concept_id="CONCEPT_08_193",
        loinc_num="18193-4",
        snomed_ct="100800193",
        component="Diagnostic Analyte Component 08-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_194": ClinicalConcept_08(
        concept_id="CONCEPT_08_194",
        loinc_num="18194-5",
        snomed_ct="100800194",
        component="Diagnostic Analyte Component 08-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_195": ClinicalConcept_08(
        concept_id="CONCEPT_08_195",
        loinc_num="18195-6",
        snomed_ct="100800195",
        component="Diagnostic Analyte Component 08-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_196": ClinicalConcept_08(
        concept_id="CONCEPT_08_196",
        loinc_num="18196-7",
        snomed_ct="100800196",
        component="Diagnostic Analyte Component 08-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_197": ClinicalConcept_08(
        concept_id="CONCEPT_08_197",
        loinc_num="18197-8",
        snomed_ct="100800197",
        component="Diagnostic Analyte Component 08-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_198": ClinicalConcept_08(
        concept_id="CONCEPT_08_198",
        loinc_num="18198-0",
        snomed_ct="100800198",
        component="Diagnostic Analyte Component 08-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_08_199": ClinicalConcept_08(
        concept_id="CONCEPT_08_199",
        loinc_num="18199-1",
        snomed_ct="100800199",
        component="Diagnostic Analyte Component 08-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
