"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 09"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_09:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_09 = {
    "CONCEPT_09_001": ClinicalConcept_09(
        concept_id="CONCEPT_09_001",
        loinc_num="19001-1",
        snomed_ct="100900001",
        component="Diagnostic Analyte Component 09-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_002": ClinicalConcept_09(
        concept_id="CONCEPT_09_002",
        loinc_num="19002-2",
        snomed_ct="100900002",
        component="Diagnostic Analyte Component 09-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_003": ClinicalConcept_09(
        concept_id="CONCEPT_09_003",
        loinc_num="19003-3",
        snomed_ct="100900003",
        component="Diagnostic Analyte Component 09-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_004": ClinicalConcept_09(
        concept_id="CONCEPT_09_004",
        loinc_num="19004-4",
        snomed_ct="100900004",
        component="Diagnostic Analyte Component 09-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_005": ClinicalConcept_09(
        concept_id="CONCEPT_09_005",
        loinc_num="19005-5",
        snomed_ct="100900005",
        component="Diagnostic Analyte Component 09-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_006": ClinicalConcept_09(
        concept_id="CONCEPT_09_006",
        loinc_num="19006-6",
        snomed_ct="100900006",
        component="Diagnostic Analyte Component 09-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_007": ClinicalConcept_09(
        concept_id="CONCEPT_09_007",
        loinc_num="19007-7",
        snomed_ct="100900007",
        component="Diagnostic Analyte Component 09-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_008": ClinicalConcept_09(
        concept_id="CONCEPT_09_008",
        loinc_num="19008-8",
        snomed_ct="100900008",
        component="Diagnostic Analyte Component 09-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_009": ClinicalConcept_09(
        concept_id="CONCEPT_09_009",
        loinc_num="19009-0",
        snomed_ct="100900009",
        component="Diagnostic Analyte Component 09-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_010": ClinicalConcept_09(
        concept_id="CONCEPT_09_010",
        loinc_num="19010-1",
        snomed_ct="100900010",
        component="Diagnostic Analyte Component 09-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_011": ClinicalConcept_09(
        concept_id="CONCEPT_09_011",
        loinc_num="19011-2",
        snomed_ct="100900011",
        component="Diagnostic Analyte Component 09-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_012": ClinicalConcept_09(
        concept_id="CONCEPT_09_012",
        loinc_num="19012-3",
        snomed_ct="100900012",
        component="Diagnostic Analyte Component 09-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_013": ClinicalConcept_09(
        concept_id="CONCEPT_09_013",
        loinc_num="19013-4",
        snomed_ct="100900013",
        component="Diagnostic Analyte Component 09-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_014": ClinicalConcept_09(
        concept_id="CONCEPT_09_014",
        loinc_num="19014-5",
        snomed_ct="100900014",
        component="Diagnostic Analyte Component 09-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_015": ClinicalConcept_09(
        concept_id="CONCEPT_09_015",
        loinc_num="19015-6",
        snomed_ct="100900015",
        component="Diagnostic Analyte Component 09-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_016": ClinicalConcept_09(
        concept_id="CONCEPT_09_016",
        loinc_num="19016-7",
        snomed_ct="100900016",
        component="Diagnostic Analyte Component 09-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_017": ClinicalConcept_09(
        concept_id="CONCEPT_09_017",
        loinc_num="19017-8",
        snomed_ct="100900017",
        component="Diagnostic Analyte Component 09-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_018": ClinicalConcept_09(
        concept_id="CONCEPT_09_018",
        loinc_num="19018-0",
        snomed_ct="100900018",
        component="Diagnostic Analyte Component 09-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_019": ClinicalConcept_09(
        concept_id="CONCEPT_09_019",
        loinc_num="19019-1",
        snomed_ct="100900019",
        component="Diagnostic Analyte Component 09-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_020": ClinicalConcept_09(
        concept_id="CONCEPT_09_020",
        loinc_num="19020-2",
        snomed_ct="100900020",
        component="Diagnostic Analyte Component 09-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_021": ClinicalConcept_09(
        concept_id="CONCEPT_09_021",
        loinc_num="19021-3",
        snomed_ct="100900021",
        component="Diagnostic Analyte Component 09-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_022": ClinicalConcept_09(
        concept_id="CONCEPT_09_022",
        loinc_num="19022-4",
        snomed_ct="100900022",
        component="Diagnostic Analyte Component 09-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_023": ClinicalConcept_09(
        concept_id="CONCEPT_09_023",
        loinc_num="19023-5",
        snomed_ct="100900023",
        component="Diagnostic Analyte Component 09-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_024": ClinicalConcept_09(
        concept_id="CONCEPT_09_024",
        loinc_num="19024-6",
        snomed_ct="100900024",
        component="Diagnostic Analyte Component 09-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_025": ClinicalConcept_09(
        concept_id="CONCEPT_09_025",
        loinc_num="19025-7",
        snomed_ct="100900025",
        component="Diagnostic Analyte Component 09-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_026": ClinicalConcept_09(
        concept_id="CONCEPT_09_026",
        loinc_num="19026-8",
        snomed_ct="100900026",
        component="Diagnostic Analyte Component 09-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_027": ClinicalConcept_09(
        concept_id="CONCEPT_09_027",
        loinc_num="19027-0",
        snomed_ct="100900027",
        component="Diagnostic Analyte Component 09-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_028": ClinicalConcept_09(
        concept_id="CONCEPT_09_028",
        loinc_num="19028-1",
        snomed_ct="100900028",
        component="Diagnostic Analyte Component 09-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_029": ClinicalConcept_09(
        concept_id="CONCEPT_09_029",
        loinc_num="19029-2",
        snomed_ct="100900029",
        component="Diagnostic Analyte Component 09-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_030": ClinicalConcept_09(
        concept_id="CONCEPT_09_030",
        loinc_num="19030-3",
        snomed_ct="100900030",
        component="Diagnostic Analyte Component 09-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_031": ClinicalConcept_09(
        concept_id="CONCEPT_09_031",
        loinc_num="19031-4",
        snomed_ct="100900031",
        component="Diagnostic Analyte Component 09-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_032": ClinicalConcept_09(
        concept_id="CONCEPT_09_032",
        loinc_num="19032-5",
        snomed_ct="100900032",
        component="Diagnostic Analyte Component 09-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_033": ClinicalConcept_09(
        concept_id="CONCEPT_09_033",
        loinc_num="19033-6",
        snomed_ct="100900033",
        component="Diagnostic Analyte Component 09-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_034": ClinicalConcept_09(
        concept_id="CONCEPT_09_034",
        loinc_num="19034-7",
        snomed_ct="100900034",
        component="Diagnostic Analyte Component 09-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_035": ClinicalConcept_09(
        concept_id="CONCEPT_09_035",
        loinc_num="19035-8",
        snomed_ct="100900035",
        component="Diagnostic Analyte Component 09-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_036": ClinicalConcept_09(
        concept_id="CONCEPT_09_036",
        loinc_num="19036-0",
        snomed_ct="100900036",
        component="Diagnostic Analyte Component 09-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_037": ClinicalConcept_09(
        concept_id="CONCEPT_09_037",
        loinc_num="19037-1",
        snomed_ct="100900037",
        component="Diagnostic Analyte Component 09-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_038": ClinicalConcept_09(
        concept_id="CONCEPT_09_038",
        loinc_num="19038-2",
        snomed_ct="100900038",
        component="Diagnostic Analyte Component 09-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_039": ClinicalConcept_09(
        concept_id="CONCEPT_09_039",
        loinc_num="19039-3",
        snomed_ct="100900039",
        component="Diagnostic Analyte Component 09-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_040": ClinicalConcept_09(
        concept_id="CONCEPT_09_040",
        loinc_num="19040-4",
        snomed_ct="100900040",
        component="Diagnostic Analyte Component 09-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_041": ClinicalConcept_09(
        concept_id="CONCEPT_09_041",
        loinc_num="19041-5",
        snomed_ct="100900041",
        component="Diagnostic Analyte Component 09-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_042": ClinicalConcept_09(
        concept_id="CONCEPT_09_042",
        loinc_num="19042-6",
        snomed_ct="100900042",
        component="Diagnostic Analyte Component 09-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_043": ClinicalConcept_09(
        concept_id="CONCEPT_09_043",
        loinc_num="19043-7",
        snomed_ct="100900043",
        component="Diagnostic Analyte Component 09-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_044": ClinicalConcept_09(
        concept_id="CONCEPT_09_044",
        loinc_num="19044-8",
        snomed_ct="100900044",
        component="Diagnostic Analyte Component 09-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_045": ClinicalConcept_09(
        concept_id="CONCEPT_09_045",
        loinc_num="19045-0",
        snomed_ct="100900045",
        component="Diagnostic Analyte Component 09-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_046": ClinicalConcept_09(
        concept_id="CONCEPT_09_046",
        loinc_num="19046-1",
        snomed_ct="100900046",
        component="Diagnostic Analyte Component 09-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_047": ClinicalConcept_09(
        concept_id="CONCEPT_09_047",
        loinc_num="19047-2",
        snomed_ct="100900047",
        component="Diagnostic Analyte Component 09-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_048": ClinicalConcept_09(
        concept_id="CONCEPT_09_048",
        loinc_num="19048-3",
        snomed_ct="100900048",
        component="Diagnostic Analyte Component 09-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_049": ClinicalConcept_09(
        concept_id="CONCEPT_09_049",
        loinc_num="19049-4",
        snomed_ct="100900049",
        component="Diagnostic Analyte Component 09-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_050": ClinicalConcept_09(
        concept_id="CONCEPT_09_050",
        loinc_num="19050-5",
        snomed_ct="100900050",
        component="Diagnostic Analyte Component 09-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_051": ClinicalConcept_09(
        concept_id="CONCEPT_09_051",
        loinc_num="19051-6",
        snomed_ct="100900051",
        component="Diagnostic Analyte Component 09-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_052": ClinicalConcept_09(
        concept_id="CONCEPT_09_052",
        loinc_num="19052-7",
        snomed_ct="100900052",
        component="Diagnostic Analyte Component 09-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_053": ClinicalConcept_09(
        concept_id="CONCEPT_09_053",
        loinc_num="19053-8",
        snomed_ct="100900053",
        component="Diagnostic Analyte Component 09-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_054": ClinicalConcept_09(
        concept_id="CONCEPT_09_054",
        loinc_num="19054-0",
        snomed_ct="100900054",
        component="Diagnostic Analyte Component 09-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_055": ClinicalConcept_09(
        concept_id="CONCEPT_09_055",
        loinc_num="19055-1",
        snomed_ct="100900055",
        component="Diagnostic Analyte Component 09-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_056": ClinicalConcept_09(
        concept_id="CONCEPT_09_056",
        loinc_num="19056-2",
        snomed_ct="100900056",
        component="Diagnostic Analyte Component 09-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_057": ClinicalConcept_09(
        concept_id="CONCEPT_09_057",
        loinc_num="19057-3",
        snomed_ct="100900057",
        component="Diagnostic Analyte Component 09-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_058": ClinicalConcept_09(
        concept_id="CONCEPT_09_058",
        loinc_num="19058-4",
        snomed_ct="100900058",
        component="Diagnostic Analyte Component 09-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_059": ClinicalConcept_09(
        concept_id="CONCEPT_09_059",
        loinc_num="19059-5",
        snomed_ct="100900059",
        component="Diagnostic Analyte Component 09-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_060": ClinicalConcept_09(
        concept_id="CONCEPT_09_060",
        loinc_num="19060-6",
        snomed_ct="100900060",
        component="Diagnostic Analyte Component 09-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_061": ClinicalConcept_09(
        concept_id="CONCEPT_09_061",
        loinc_num="19061-7",
        snomed_ct="100900061",
        component="Diagnostic Analyte Component 09-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_062": ClinicalConcept_09(
        concept_id="CONCEPT_09_062",
        loinc_num="19062-8",
        snomed_ct="100900062",
        component="Diagnostic Analyte Component 09-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_063": ClinicalConcept_09(
        concept_id="CONCEPT_09_063",
        loinc_num="19063-0",
        snomed_ct="100900063",
        component="Diagnostic Analyte Component 09-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_064": ClinicalConcept_09(
        concept_id="CONCEPT_09_064",
        loinc_num="19064-1",
        snomed_ct="100900064",
        component="Diagnostic Analyte Component 09-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_065": ClinicalConcept_09(
        concept_id="CONCEPT_09_065",
        loinc_num="19065-2",
        snomed_ct="100900065",
        component="Diagnostic Analyte Component 09-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_066": ClinicalConcept_09(
        concept_id="CONCEPT_09_066",
        loinc_num="19066-3",
        snomed_ct="100900066",
        component="Diagnostic Analyte Component 09-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_067": ClinicalConcept_09(
        concept_id="CONCEPT_09_067",
        loinc_num="19067-4",
        snomed_ct="100900067",
        component="Diagnostic Analyte Component 09-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_068": ClinicalConcept_09(
        concept_id="CONCEPT_09_068",
        loinc_num="19068-5",
        snomed_ct="100900068",
        component="Diagnostic Analyte Component 09-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_069": ClinicalConcept_09(
        concept_id="CONCEPT_09_069",
        loinc_num="19069-6",
        snomed_ct="100900069",
        component="Diagnostic Analyte Component 09-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_070": ClinicalConcept_09(
        concept_id="CONCEPT_09_070",
        loinc_num="19070-7",
        snomed_ct="100900070",
        component="Diagnostic Analyte Component 09-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_071": ClinicalConcept_09(
        concept_id="CONCEPT_09_071",
        loinc_num="19071-8",
        snomed_ct="100900071",
        component="Diagnostic Analyte Component 09-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_072": ClinicalConcept_09(
        concept_id="CONCEPT_09_072",
        loinc_num="19072-0",
        snomed_ct="100900072",
        component="Diagnostic Analyte Component 09-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_073": ClinicalConcept_09(
        concept_id="CONCEPT_09_073",
        loinc_num="19073-1",
        snomed_ct="100900073",
        component="Diagnostic Analyte Component 09-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_074": ClinicalConcept_09(
        concept_id="CONCEPT_09_074",
        loinc_num="19074-2",
        snomed_ct="100900074",
        component="Diagnostic Analyte Component 09-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_075": ClinicalConcept_09(
        concept_id="CONCEPT_09_075",
        loinc_num="19075-3",
        snomed_ct="100900075",
        component="Diagnostic Analyte Component 09-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_076": ClinicalConcept_09(
        concept_id="CONCEPT_09_076",
        loinc_num="19076-4",
        snomed_ct="100900076",
        component="Diagnostic Analyte Component 09-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_077": ClinicalConcept_09(
        concept_id="CONCEPT_09_077",
        loinc_num="19077-5",
        snomed_ct="100900077",
        component="Diagnostic Analyte Component 09-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_078": ClinicalConcept_09(
        concept_id="CONCEPT_09_078",
        loinc_num="19078-6",
        snomed_ct="100900078",
        component="Diagnostic Analyte Component 09-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_079": ClinicalConcept_09(
        concept_id="CONCEPT_09_079",
        loinc_num="19079-7",
        snomed_ct="100900079",
        component="Diagnostic Analyte Component 09-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_080": ClinicalConcept_09(
        concept_id="CONCEPT_09_080",
        loinc_num="19080-8",
        snomed_ct="100900080",
        component="Diagnostic Analyte Component 09-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_081": ClinicalConcept_09(
        concept_id="CONCEPT_09_081",
        loinc_num="19081-0",
        snomed_ct="100900081",
        component="Diagnostic Analyte Component 09-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_082": ClinicalConcept_09(
        concept_id="CONCEPT_09_082",
        loinc_num="19082-1",
        snomed_ct="100900082",
        component="Diagnostic Analyte Component 09-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_083": ClinicalConcept_09(
        concept_id="CONCEPT_09_083",
        loinc_num="19083-2",
        snomed_ct="100900083",
        component="Diagnostic Analyte Component 09-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_084": ClinicalConcept_09(
        concept_id="CONCEPT_09_084",
        loinc_num="19084-3",
        snomed_ct="100900084",
        component="Diagnostic Analyte Component 09-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_085": ClinicalConcept_09(
        concept_id="CONCEPT_09_085",
        loinc_num="19085-4",
        snomed_ct="100900085",
        component="Diagnostic Analyte Component 09-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_086": ClinicalConcept_09(
        concept_id="CONCEPT_09_086",
        loinc_num="19086-5",
        snomed_ct="100900086",
        component="Diagnostic Analyte Component 09-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_087": ClinicalConcept_09(
        concept_id="CONCEPT_09_087",
        loinc_num="19087-6",
        snomed_ct="100900087",
        component="Diagnostic Analyte Component 09-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_088": ClinicalConcept_09(
        concept_id="CONCEPT_09_088",
        loinc_num="19088-7",
        snomed_ct="100900088",
        component="Diagnostic Analyte Component 09-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_089": ClinicalConcept_09(
        concept_id="CONCEPT_09_089",
        loinc_num="19089-8",
        snomed_ct="100900089",
        component="Diagnostic Analyte Component 09-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_090": ClinicalConcept_09(
        concept_id="CONCEPT_09_090",
        loinc_num="19090-0",
        snomed_ct="100900090",
        component="Diagnostic Analyte Component 09-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_091": ClinicalConcept_09(
        concept_id="CONCEPT_09_091",
        loinc_num="19091-1",
        snomed_ct="100900091",
        component="Diagnostic Analyte Component 09-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_092": ClinicalConcept_09(
        concept_id="CONCEPT_09_092",
        loinc_num="19092-2",
        snomed_ct="100900092",
        component="Diagnostic Analyte Component 09-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_093": ClinicalConcept_09(
        concept_id="CONCEPT_09_093",
        loinc_num="19093-3",
        snomed_ct="100900093",
        component="Diagnostic Analyte Component 09-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_094": ClinicalConcept_09(
        concept_id="CONCEPT_09_094",
        loinc_num="19094-4",
        snomed_ct="100900094",
        component="Diagnostic Analyte Component 09-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_095": ClinicalConcept_09(
        concept_id="CONCEPT_09_095",
        loinc_num="19095-5",
        snomed_ct="100900095",
        component="Diagnostic Analyte Component 09-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_096": ClinicalConcept_09(
        concept_id="CONCEPT_09_096",
        loinc_num="19096-6",
        snomed_ct="100900096",
        component="Diagnostic Analyte Component 09-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_097": ClinicalConcept_09(
        concept_id="CONCEPT_09_097",
        loinc_num="19097-7",
        snomed_ct="100900097",
        component="Diagnostic Analyte Component 09-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_098": ClinicalConcept_09(
        concept_id="CONCEPT_09_098",
        loinc_num="19098-8",
        snomed_ct="100900098",
        component="Diagnostic Analyte Component 09-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_099": ClinicalConcept_09(
        concept_id="CONCEPT_09_099",
        loinc_num="19099-0",
        snomed_ct="100900099",
        component="Diagnostic Analyte Component 09-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_100": ClinicalConcept_09(
        concept_id="CONCEPT_09_100",
        loinc_num="19100-1",
        snomed_ct="100900100",
        component="Diagnostic Analyte Component 09-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_101": ClinicalConcept_09(
        concept_id="CONCEPT_09_101",
        loinc_num="19101-2",
        snomed_ct="100900101",
        component="Diagnostic Analyte Component 09-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_102": ClinicalConcept_09(
        concept_id="CONCEPT_09_102",
        loinc_num="19102-3",
        snomed_ct="100900102",
        component="Diagnostic Analyte Component 09-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_103": ClinicalConcept_09(
        concept_id="CONCEPT_09_103",
        loinc_num="19103-4",
        snomed_ct="100900103",
        component="Diagnostic Analyte Component 09-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_104": ClinicalConcept_09(
        concept_id="CONCEPT_09_104",
        loinc_num="19104-5",
        snomed_ct="100900104",
        component="Diagnostic Analyte Component 09-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_105": ClinicalConcept_09(
        concept_id="CONCEPT_09_105",
        loinc_num="19105-6",
        snomed_ct="100900105",
        component="Diagnostic Analyte Component 09-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_106": ClinicalConcept_09(
        concept_id="CONCEPT_09_106",
        loinc_num="19106-7",
        snomed_ct="100900106",
        component="Diagnostic Analyte Component 09-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_107": ClinicalConcept_09(
        concept_id="CONCEPT_09_107",
        loinc_num="19107-8",
        snomed_ct="100900107",
        component="Diagnostic Analyte Component 09-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_108": ClinicalConcept_09(
        concept_id="CONCEPT_09_108",
        loinc_num="19108-0",
        snomed_ct="100900108",
        component="Diagnostic Analyte Component 09-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_109": ClinicalConcept_09(
        concept_id="CONCEPT_09_109",
        loinc_num="19109-1",
        snomed_ct="100900109",
        component="Diagnostic Analyte Component 09-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_110": ClinicalConcept_09(
        concept_id="CONCEPT_09_110",
        loinc_num="19110-2",
        snomed_ct="100900110",
        component="Diagnostic Analyte Component 09-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_111": ClinicalConcept_09(
        concept_id="CONCEPT_09_111",
        loinc_num="19111-3",
        snomed_ct="100900111",
        component="Diagnostic Analyte Component 09-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_112": ClinicalConcept_09(
        concept_id="CONCEPT_09_112",
        loinc_num="19112-4",
        snomed_ct="100900112",
        component="Diagnostic Analyte Component 09-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_113": ClinicalConcept_09(
        concept_id="CONCEPT_09_113",
        loinc_num="19113-5",
        snomed_ct="100900113",
        component="Diagnostic Analyte Component 09-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_114": ClinicalConcept_09(
        concept_id="CONCEPT_09_114",
        loinc_num="19114-6",
        snomed_ct="100900114",
        component="Diagnostic Analyte Component 09-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_115": ClinicalConcept_09(
        concept_id="CONCEPT_09_115",
        loinc_num="19115-7",
        snomed_ct="100900115",
        component="Diagnostic Analyte Component 09-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_116": ClinicalConcept_09(
        concept_id="CONCEPT_09_116",
        loinc_num="19116-8",
        snomed_ct="100900116",
        component="Diagnostic Analyte Component 09-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_117": ClinicalConcept_09(
        concept_id="CONCEPT_09_117",
        loinc_num="19117-0",
        snomed_ct="100900117",
        component="Diagnostic Analyte Component 09-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_118": ClinicalConcept_09(
        concept_id="CONCEPT_09_118",
        loinc_num="19118-1",
        snomed_ct="100900118",
        component="Diagnostic Analyte Component 09-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_119": ClinicalConcept_09(
        concept_id="CONCEPT_09_119",
        loinc_num="19119-2",
        snomed_ct="100900119",
        component="Diagnostic Analyte Component 09-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_120": ClinicalConcept_09(
        concept_id="CONCEPT_09_120",
        loinc_num="19120-3",
        snomed_ct="100900120",
        component="Diagnostic Analyte Component 09-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_121": ClinicalConcept_09(
        concept_id="CONCEPT_09_121",
        loinc_num="19121-4",
        snomed_ct="100900121",
        component="Diagnostic Analyte Component 09-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_122": ClinicalConcept_09(
        concept_id="CONCEPT_09_122",
        loinc_num="19122-5",
        snomed_ct="100900122",
        component="Diagnostic Analyte Component 09-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_123": ClinicalConcept_09(
        concept_id="CONCEPT_09_123",
        loinc_num="19123-6",
        snomed_ct="100900123",
        component="Diagnostic Analyte Component 09-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_124": ClinicalConcept_09(
        concept_id="CONCEPT_09_124",
        loinc_num="19124-7",
        snomed_ct="100900124",
        component="Diagnostic Analyte Component 09-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_125": ClinicalConcept_09(
        concept_id="CONCEPT_09_125",
        loinc_num="19125-8",
        snomed_ct="100900125",
        component="Diagnostic Analyte Component 09-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_126": ClinicalConcept_09(
        concept_id="CONCEPT_09_126",
        loinc_num="19126-0",
        snomed_ct="100900126",
        component="Diagnostic Analyte Component 09-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_127": ClinicalConcept_09(
        concept_id="CONCEPT_09_127",
        loinc_num="19127-1",
        snomed_ct="100900127",
        component="Diagnostic Analyte Component 09-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_128": ClinicalConcept_09(
        concept_id="CONCEPT_09_128",
        loinc_num="19128-2",
        snomed_ct="100900128",
        component="Diagnostic Analyte Component 09-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_129": ClinicalConcept_09(
        concept_id="CONCEPT_09_129",
        loinc_num="19129-3",
        snomed_ct="100900129",
        component="Diagnostic Analyte Component 09-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_130": ClinicalConcept_09(
        concept_id="CONCEPT_09_130",
        loinc_num="19130-4",
        snomed_ct="100900130",
        component="Diagnostic Analyte Component 09-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_131": ClinicalConcept_09(
        concept_id="CONCEPT_09_131",
        loinc_num="19131-5",
        snomed_ct="100900131",
        component="Diagnostic Analyte Component 09-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_132": ClinicalConcept_09(
        concept_id="CONCEPT_09_132",
        loinc_num="19132-6",
        snomed_ct="100900132",
        component="Diagnostic Analyte Component 09-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_133": ClinicalConcept_09(
        concept_id="CONCEPT_09_133",
        loinc_num="19133-7",
        snomed_ct="100900133",
        component="Diagnostic Analyte Component 09-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_134": ClinicalConcept_09(
        concept_id="CONCEPT_09_134",
        loinc_num="19134-8",
        snomed_ct="100900134",
        component="Diagnostic Analyte Component 09-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_135": ClinicalConcept_09(
        concept_id="CONCEPT_09_135",
        loinc_num="19135-0",
        snomed_ct="100900135",
        component="Diagnostic Analyte Component 09-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_136": ClinicalConcept_09(
        concept_id="CONCEPT_09_136",
        loinc_num="19136-1",
        snomed_ct="100900136",
        component="Diagnostic Analyte Component 09-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_137": ClinicalConcept_09(
        concept_id="CONCEPT_09_137",
        loinc_num="19137-2",
        snomed_ct="100900137",
        component="Diagnostic Analyte Component 09-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_138": ClinicalConcept_09(
        concept_id="CONCEPT_09_138",
        loinc_num="19138-3",
        snomed_ct="100900138",
        component="Diagnostic Analyte Component 09-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_139": ClinicalConcept_09(
        concept_id="CONCEPT_09_139",
        loinc_num="19139-4",
        snomed_ct="100900139",
        component="Diagnostic Analyte Component 09-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_140": ClinicalConcept_09(
        concept_id="CONCEPT_09_140",
        loinc_num="19140-5",
        snomed_ct="100900140",
        component="Diagnostic Analyte Component 09-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_141": ClinicalConcept_09(
        concept_id="CONCEPT_09_141",
        loinc_num="19141-6",
        snomed_ct="100900141",
        component="Diagnostic Analyte Component 09-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_142": ClinicalConcept_09(
        concept_id="CONCEPT_09_142",
        loinc_num="19142-7",
        snomed_ct="100900142",
        component="Diagnostic Analyte Component 09-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_143": ClinicalConcept_09(
        concept_id="CONCEPT_09_143",
        loinc_num="19143-8",
        snomed_ct="100900143",
        component="Diagnostic Analyte Component 09-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_144": ClinicalConcept_09(
        concept_id="CONCEPT_09_144",
        loinc_num="19144-0",
        snomed_ct="100900144",
        component="Diagnostic Analyte Component 09-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_145": ClinicalConcept_09(
        concept_id="CONCEPT_09_145",
        loinc_num="19145-1",
        snomed_ct="100900145",
        component="Diagnostic Analyte Component 09-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_146": ClinicalConcept_09(
        concept_id="CONCEPT_09_146",
        loinc_num="19146-2",
        snomed_ct="100900146",
        component="Diagnostic Analyte Component 09-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_147": ClinicalConcept_09(
        concept_id="CONCEPT_09_147",
        loinc_num="19147-3",
        snomed_ct="100900147",
        component="Diagnostic Analyte Component 09-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_148": ClinicalConcept_09(
        concept_id="CONCEPT_09_148",
        loinc_num="19148-4",
        snomed_ct="100900148",
        component="Diagnostic Analyte Component 09-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_149": ClinicalConcept_09(
        concept_id="CONCEPT_09_149",
        loinc_num="19149-5",
        snomed_ct="100900149",
        component="Diagnostic Analyte Component 09-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_150": ClinicalConcept_09(
        concept_id="CONCEPT_09_150",
        loinc_num="19150-6",
        snomed_ct="100900150",
        component="Diagnostic Analyte Component 09-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_151": ClinicalConcept_09(
        concept_id="CONCEPT_09_151",
        loinc_num="19151-7",
        snomed_ct="100900151",
        component="Diagnostic Analyte Component 09-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_152": ClinicalConcept_09(
        concept_id="CONCEPT_09_152",
        loinc_num="19152-8",
        snomed_ct="100900152",
        component="Diagnostic Analyte Component 09-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_153": ClinicalConcept_09(
        concept_id="CONCEPT_09_153",
        loinc_num="19153-0",
        snomed_ct="100900153",
        component="Diagnostic Analyte Component 09-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_154": ClinicalConcept_09(
        concept_id="CONCEPT_09_154",
        loinc_num="19154-1",
        snomed_ct="100900154",
        component="Diagnostic Analyte Component 09-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_155": ClinicalConcept_09(
        concept_id="CONCEPT_09_155",
        loinc_num="19155-2",
        snomed_ct="100900155",
        component="Diagnostic Analyte Component 09-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_156": ClinicalConcept_09(
        concept_id="CONCEPT_09_156",
        loinc_num="19156-3",
        snomed_ct="100900156",
        component="Diagnostic Analyte Component 09-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_157": ClinicalConcept_09(
        concept_id="CONCEPT_09_157",
        loinc_num="19157-4",
        snomed_ct="100900157",
        component="Diagnostic Analyte Component 09-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_158": ClinicalConcept_09(
        concept_id="CONCEPT_09_158",
        loinc_num="19158-5",
        snomed_ct="100900158",
        component="Diagnostic Analyte Component 09-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_159": ClinicalConcept_09(
        concept_id="CONCEPT_09_159",
        loinc_num="19159-6",
        snomed_ct="100900159",
        component="Diagnostic Analyte Component 09-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_160": ClinicalConcept_09(
        concept_id="CONCEPT_09_160",
        loinc_num="19160-7",
        snomed_ct="100900160",
        component="Diagnostic Analyte Component 09-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_161": ClinicalConcept_09(
        concept_id="CONCEPT_09_161",
        loinc_num="19161-8",
        snomed_ct="100900161",
        component="Diagnostic Analyte Component 09-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_162": ClinicalConcept_09(
        concept_id="CONCEPT_09_162",
        loinc_num="19162-0",
        snomed_ct="100900162",
        component="Diagnostic Analyte Component 09-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_163": ClinicalConcept_09(
        concept_id="CONCEPT_09_163",
        loinc_num="19163-1",
        snomed_ct="100900163",
        component="Diagnostic Analyte Component 09-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_164": ClinicalConcept_09(
        concept_id="CONCEPT_09_164",
        loinc_num="19164-2",
        snomed_ct="100900164",
        component="Diagnostic Analyte Component 09-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_165": ClinicalConcept_09(
        concept_id="CONCEPT_09_165",
        loinc_num="19165-3",
        snomed_ct="100900165",
        component="Diagnostic Analyte Component 09-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_166": ClinicalConcept_09(
        concept_id="CONCEPT_09_166",
        loinc_num="19166-4",
        snomed_ct="100900166",
        component="Diagnostic Analyte Component 09-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_167": ClinicalConcept_09(
        concept_id="CONCEPT_09_167",
        loinc_num="19167-5",
        snomed_ct="100900167",
        component="Diagnostic Analyte Component 09-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_168": ClinicalConcept_09(
        concept_id="CONCEPT_09_168",
        loinc_num="19168-6",
        snomed_ct="100900168",
        component="Diagnostic Analyte Component 09-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_169": ClinicalConcept_09(
        concept_id="CONCEPT_09_169",
        loinc_num="19169-7",
        snomed_ct="100900169",
        component="Diagnostic Analyte Component 09-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_170": ClinicalConcept_09(
        concept_id="CONCEPT_09_170",
        loinc_num="19170-8",
        snomed_ct="100900170",
        component="Diagnostic Analyte Component 09-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_171": ClinicalConcept_09(
        concept_id="CONCEPT_09_171",
        loinc_num="19171-0",
        snomed_ct="100900171",
        component="Diagnostic Analyte Component 09-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_172": ClinicalConcept_09(
        concept_id="CONCEPT_09_172",
        loinc_num="19172-1",
        snomed_ct="100900172",
        component="Diagnostic Analyte Component 09-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_173": ClinicalConcept_09(
        concept_id="CONCEPT_09_173",
        loinc_num="19173-2",
        snomed_ct="100900173",
        component="Diagnostic Analyte Component 09-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_174": ClinicalConcept_09(
        concept_id="CONCEPT_09_174",
        loinc_num="19174-3",
        snomed_ct="100900174",
        component="Diagnostic Analyte Component 09-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_175": ClinicalConcept_09(
        concept_id="CONCEPT_09_175",
        loinc_num="19175-4",
        snomed_ct="100900175",
        component="Diagnostic Analyte Component 09-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_176": ClinicalConcept_09(
        concept_id="CONCEPT_09_176",
        loinc_num="19176-5",
        snomed_ct="100900176",
        component="Diagnostic Analyte Component 09-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_177": ClinicalConcept_09(
        concept_id="CONCEPT_09_177",
        loinc_num="19177-6",
        snomed_ct="100900177",
        component="Diagnostic Analyte Component 09-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_178": ClinicalConcept_09(
        concept_id="CONCEPT_09_178",
        loinc_num="19178-7",
        snomed_ct="100900178",
        component="Diagnostic Analyte Component 09-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_179": ClinicalConcept_09(
        concept_id="CONCEPT_09_179",
        loinc_num="19179-8",
        snomed_ct="100900179",
        component="Diagnostic Analyte Component 09-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_180": ClinicalConcept_09(
        concept_id="CONCEPT_09_180",
        loinc_num="19180-0",
        snomed_ct="100900180",
        component="Diagnostic Analyte Component 09-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_181": ClinicalConcept_09(
        concept_id="CONCEPT_09_181",
        loinc_num="19181-1",
        snomed_ct="100900181",
        component="Diagnostic Analyte Component 09-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_182": ClinicalConcept_09(
        concept_id="CONCEPT_09_182",
        loinc_num="19182-2",
        snomed_ct="100900182",
        component="Diagnostic Analyte Component 09-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_183": ClinicalConcept_09(
        concept_id="CONCEPT_09_183",
        loinc_num="19183-3",
        snomed_ct="100900183",
        component="Diagnostic Analyte Component 09-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_184": ClinicalConcept_09(
        concept_id="CONCEPT_09_184",
        loinc_num="19184-4",
        snomed_ct="100900184",
        component="Diagnostic Analyte Component 09-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_185": ClinicalConcept_09(
        concept_id="CONCEPT_09_185",
        loinc_num="19185-5",
        snomed_ct="100900185",
        component="Diagnostic Analyte Component 09-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_186": ClinicalConcept_09(
        concept_id="CONCEPT_09_186",
        loinc_num="19186-6",
        snomed_ct="100900186",
        component="Diagnostic Analyte Component 09-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_187": ClinicalConcept_09(
        concept_id="CONCEPT_09_187",
        loinc_num="19187-7",
        snomed_ct="100900187",
        component="Diagnostic Analyte Component 09-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_188": ClinicalConcept_09(
        concept_id="CONCEPT_09_188",
        loinc_num="19188-8",
        snomed_ct="100900188",
        component="Diagnostic Analyte Component 09-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_189": ClinicalConcept_09(
        concept_id="CONCEPT_09_189",
        loinc_num="19189-0",
        snomed_ct="100900189",
        component="Diagnostic Analyte Component 09-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_190": ClinicalConcept_09(
        concept_id="CONCEPT_09_190",
        loinc_num="19190-1",
        snomed_ct="100900190",
        component="Diagnostic Analyte Component 09-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_191": ClinicalConcept_09(
        concept_id="CONCEPT_09_191",
        loinc_num="19191-2",
        snomed_ct="100900191",
        component="Diagnostic Analyte Component 09-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_192": ClinicalConcept_09(
        concept_id="CONCEPT_09_192",
        loinc_num="19192-3",
        snomed_ct="100900192",
        component="Diagnostic Analyte Component 09-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_193": ClinicalConcept_09(
        concept_id="CONCEPT_09_193",
        loinc_num="19193-4",
        snomed_ct="100900193",
        component="Diagnostic Analyte Component 09-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_194": ClinicalConcept_09(
        concept_id="CONCEPT_09_194",
        loinc_num="19194-5",
        snomed_ct="100900194",
        component="Diagnostic Analyte Component 09-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_195": ClinicalConcept_09(
        concept_id="CONCEPT_09_195",
        loinc_num="19195-6",
        snomed_ct="100900195",
        component="Diagnostic Analyte Component 09-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_196": ClinicalConcept_09(
        concept_id="CONCEPT_09_196",
        loinc_num="19196-7",
        snomed_ct="100900196",
        component="Diagnostic Analyte Component 09-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_197": ClinicalConcept_09(
        concept_id="CONCEPT_09_197",
        loinc_num="19197-8",
        snomed_ct="100900197",
        component="Diagnostic Analyte Component 09-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_198": ClinicalConcept_09(
        concept_id="CONCEPT_09_198",
        loinc_num="19198-0",
        snomed_ct="100900198",
        component="Diagnostic Analyte Component 09-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_09_199": ClinicalConcept_09(
        concept_id="CONCEPT_09_199",
        loinc_num="19199-1",
        snomed_ct="100900199",
        component="Diagnostic Analyte Component 09-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
