"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 15"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_15:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_15 = {
    "CONCEPT_15_001": ClinicalConcept_15(
        concept_id="CONCEPT_15_001",
        loinc_num="25001-1",
        snomed_ct="101500001",
        component="Diagnostic Analyte Component 15-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_002": ClinicalConcept_15(
        concept_id="CONCEPT_15_002",
        loinc_num="25002-2",
        snomed_ct="101500002",
        component="Diagnostic Analyte Component 15-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_003": ClinicalConcept_15(
        concept_id="CONCEPT_15_003",
        loinc_num="25003-3",
        snomed_ct="101500003",
        component="Diagnostic Analyte Component 15-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_004": ClinicalConcept_15(
        concept_id="CONCEPT_15_004",
        loinc_num="25004-4",
        snomed_ct="101500004",
        component="Diagnostic Analyte Component 15-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_005": ClinicalConcept_15(
        concept_id="CONCEPT_15_005",
        loinc_num="25005-5",
        snomed_ct="101500005",
        component="Diagnostic Analyte Component 15-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_006": ClinicalConcept_15(
        concept_id="CONCEPT_15_006",
        loinc_num="25006-6",
        snomed_ct="101500006",
        component="Diagnostic Analyte Component 15-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_007": ClinicalConcept_15(
        concept_id="CONCEPT_15_007",
        loinc_num="25007-7",
        snomed_ct="101500007",
        component="Diagnostic Analyte Component 15-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_008": ClinicalConcept_15(
        concept_id="CONCEPT_15_008",
        loinc_num="25008-8",
        snomed_ct="101500008",
        component="Diagnostic Analyte Component 15-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_009": ClinicalConcept_15(
        concept_id="CONCEPT_15_009",
        loinc_num="25009-0",
        snomed_ct="101500009",
        component="Diagnostic Analyte Component 15-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_010": ClinicalConcept_15(
        concept_id="CONCEPT_15_010",
        loinc_num="25010-1",
        snomed_ct="101500010",
        component="Diagnostic Analyte Component 15-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_011": ClinicalConcept_15(
        concept_id="CONCEPT_15_011",
        loinc_num="25011-2",
        snomed_ct="101500011",
        component="Diagnostic Analyte Component 15-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_012": ClinicalConcept_15(
        concept_id="CONCEPT_15_012",
        loinc_num="25012-3",
        snomed_ct="101500012",
        component="Diagnostic Analyte Component 15-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_013": ClinicalConcept_15(
        concept_id="CONCEPT_15_013",
        loinc_num="25013-4",
        snomed_ct="101500013",
        component="Diagnostic Analyte Component 15-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_014": ClinicalConcept_15(
        concept_id="CONCEPT_15_014",
        loinc_num="25014-5",
        snomed_ct="101500014",
        component="Diagnostic Analyte Component 15-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_015": ClinicalConcept_15(
        concept_id="CONCEPT_15_015",
        loinc_num="25015-6",
        snomed_ct="101500015",
        component="Diagnostic Analyte Component 15-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_016": ClinicalConcept_15(
        concept_id="CONCEPT_15_016",
        loinc_num="25016-7",
        snomed_ct="101500016",
        component="Diagnostic Analyte Component 15-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_017": ClinicalConcept_15(
        concept_id="CONCEPT_15_017",
        loinc_num="25017-8",
        snomed_ct="101500017",
        component="Diagnostic Analyte Component 15-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_018": ClinicalConcept_15(
        concept_id="CONCEPT_15_018",
        loinc_num="25018-0",
        snomed_ct="101500018",
        component="Diagnostic Analyte Component 15-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_019": ClinicalConcept_15(
        concept_id="CONCEPT_15_019",
        loinc_num="25019-1",
        snomed_ct="101500019",
        component="Diagnostic Analyte Component 15-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_020": ClinicalConcept_15(
        concept_id="CONCEPT_15_020",
        loinc_num="25020-2",
        snomed_ct="101500020",
        component="Diagnostic Analyte Component 15-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_021": ClinicalConcept_15(
        concept_id="CONCEPT_15_021",
        loinc_num="25021-3",
        snomed_ct="101500021",
        component="Diagnostic Analyte Component 15-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_022": ClinicalConcept_15(
        concept_id="CONCEPT_15_022",
        loinc_num="25022-4",
        snomed_ct="101500022",
        component="Diagnostic Analyte Component 15-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_023": ClinicalConcept_15(
        concept_id="CONCEPT_15_023",
        loinc_num="25023-5",
        snomed_ct="101500023",
        component="Diagnostic Analyte Component 15-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_024": ClinicalConcept_15(
        concept_id="CONCEPT_15_024",
        loinc_num="25024-6",
        snomed_ct="101500024",
        component="Diagnostic Analyte Component 15-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_025": ClinicalConcept_15(
        concept_id="CONCEPT_15_025",
        loinc_num="25025-7",
        snomed_ct="101500025",
        component="Diagnostic Analyte Component 15-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_026": ClinicalConcept_15(
        concept_id="CONCEPT_15_026",
        loinc_num="25026-8",
        snomed_ct="101500026",
        component="Diagnostic Analyte Component 15-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_027": ClinicalConcept_15(
        concept_id="CONCEPT_15_027",
        loinc_num="25027-0",
        snomed_ct="101500027",
        component="Diagnostic Analyte Component 15-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_028": ClinicalConcept_15(
        concept_id="CONCEPT_15_028",
        loinc_num="25028-1",
        snomed_ct="101500028",
        component="Diagnostic Analyte Component 15-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_029": ClinicalConcept_15(
        concept_id="CONCEPT_15_029",
        loinc_num="25029-2",
        snomed_ct="101500029",
        component="Diagnostic Analyte Component 15-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_030": ClinicalConcept_15(
        concept_id="CONCEPT_15_030",
        loinc_num="25030-3",
        snomed_ct="101500030",
        component="Diagnostic Analyte Component 15-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_031": ClinicalConcept_15(
        concept_id="CONCEPT_15_031",
        loinc_num="25031-4",
        snomed_ct="101500031",
        component="Diagnostic Analyte Component 15-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_032": ClinicalConcept_15(
        concept_id="CONCEPT_15_032",
        loinc_num="25032-5",
        snomed_ct="101500032",
        component="Diagnostic Analyte Component 15-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_033": ClinicalConcept_15(
        concept_id="CONCEPT_15_033",
        loinc_num="25033-6",
        snomed_ct="101500033",
        component="Diagnostic Analyte Component 15-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_034": ClinicalConcept_15(
        concept_id="CONCEPT_15_034",
        loinc_num="25034-7",
        snomed_ct="101500034",
        component="Diagnostic Analyte Component 15-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_035": ClinicalConcept_15(
        concept_id="CONCEPT_15_035",
        loinc_num="25035-8",
        snomed_ct="101500035",
        component="Diagnostic Analyte Component 15-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_036": ClinicalConcept_15(
        concept_id="CONCEPT_15_036",
        loinc_num="25036-0",
        snomed_ct="101500036",
        component="Diagnostic Analyte Component 15-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_037": ClinicalConcept_15(
        concept_id="CONCEPT_15_037",
        loinc_num="25037-1",
        snomed_ct="101500037",
        component="Diagnostic Analyte Component 15-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_038": ClinicalConcept_15(
        concept_id="CONCEPT_15_038",
        loinc_num="25038-2",
        snomed_ct="101500038",
        component="Diagnostic Analyte Component 15-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_039": ClinicalConcept_15(
        concept_id="CONCEPT_15_039",
        loinc_num="25039-3",
        snomed_ct="101500039",
        component="Diagnostic Analyte Component 15-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_040": ClinicalConcept_15(
        concept_id="CONCEPT_15_040",
        loinc_num="25040-4",
        snomed_ct="101500040",
        component="Diagnostic Analyte Component 15-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_041": ClinicalConcept_15(
        concept_id="CONCEPT_15_041",
        loinc_num="25041-5",
        snomed_ct="101500041",
        component="Diagnostic Analyte Component 15-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_042": ClinicalConcept_15(
        concept_id="CONCEPT_15_042",
        loinc_num="25042-6",
        snomed_ct="101500042",
        component="Diagnostic Analyte Component 15-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_043": ClinicalConcept_15(
        concept_id="CONCEPT_15_043",
        loinc_num="25043-7",
        snomed_ct="101500043",
        component="Diagnostic Analyte Component 15-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_044": ClinicalConcept_15(
        concept_id="CONCEPT_15_044",
        loinc_num="25044-8",
        snomed_ct="101500044",
        component="Diagnostic Analyte Component 15-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_045": ClinicalConcept_15(
        concept_id="CONCEPT_15_045",
        loinc_num="25045-0",
        snomed_ct="101500045",
        component="Diagnostic Analyte Component 15-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_046": ClinicalConcept_15(
        concept_id="CONCEPT_15_046",
        loinc_num="25046-1",
        snomed_ct="101500046",
        component="Diagnostic Analyte Component 15-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_047": ClinicalConcept_15(
        concept_id="CONCEPT_15_047",
        loinc_num="25047-2",
        snomed_ct="101500047",
        component="Diagnostic Analyte Component 15-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_048": ClinicalConcept_15(
        concept_id="CONCEPT_15_048",
        loinc_num="25048-3",
        snomed_ct="101500048",
        component="Diagnostic Analyte Component 15-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_049": ClinicalConcept_15(
        concept_id="CONCEPT_15_049",
        loinc_num="25049-4",
        snomed_ct="101500049",
        component="Diagnostic Analyte Component 15-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_050": ClinicalConcept_15(
        concept_id="CONCEPT_15_050",
        loinc_num="25050-5",
        snomed_ct="101500050",
        component="Diagnostic Analyte Component 15-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_051": ClinicalConcept_15(
        concept_id="CONCEPT_15_051",
        loinc_num="25051-6",
        snomed_ct="101500051",
        component="Diagnostic Analyte Component 15-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_052": ClinicalConcept_15(
        concept_id="CONCEPT_15_052",
        loinc_num="25052-7",
        snomed_ct="101500052",
        component="Diagnostic Analyte Component 15-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_053": ClinicalConcept_15(
        concept_id="CONCEPT_15_053",
        loinc_num="25053-8",
        snomed_ct="101500053",
        component="Diagnostic Analyte Component 15-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_054": ClinicalConcept_15(
        concept_id="CONCEPT_15_054",
        loinc_num="25054-0",
        snomed_ct="101500054",
        component="Diagnostic Analyte Component 15-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_055": ClinicalConcept_15(
        concept_id="CONCEPT_15_055",
        loinc_num="25055-1",
        snomed_ct="101500055",
        component="Diagnostic Analyte Component 15-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_056": ClinicalConcept_15(
        concept_id="CONCEPT_15_056",
        loinc_num="25056-2",
        snomed_ct="101500056",
        component="Diagnostic Analyte Component 15-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_057": ClinicalConcept_15(
        concept_id="CONCEPT_15_057",
        loinc_num="25057-3",
        snomed_ct="101500057",
        component="Diagnostic Analyte Component 15-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_058": ClinicalConcept_15(
        concept_id="CONCEPT_15_058",
        loinc_num="25058-4",
        snomed_ct="101500058",
        component="Diagnostic Analyte Component 15-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_059": ClinicalConcept_15(
        concept_id="CONCEPT_15_059",
        loinc_num="25059-5",
        snomed_ct="101500059",
        component="Diagnostic Analyte Component 15-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_060": ClinicalConcept_15(
        concept_id="CONCEPT_15_060",
        loinc_num="25060-6",
        snomed_ct="101500060",
        component="Diagnostic Analyte Component 15-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_061": ClinicalConcept_15(
        concept_id="CONCEPT_15_061",
        loinc_num="25061-7",
        snomed_ct="101500061",
        component="Diagnostic Analyte Component 15-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_062": ClinicalConcept_15(
        concept_id="CONCEPT_15_062",
        loinc_num="25062-8",
        snomed_ct="101500062",
        component="Diagnostic Analyte Component 15-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_063": ClinicalConcept_15(
        concept_id="CONCEPT_15_063",
        loinc_num="25063-0",
        snomed_ct="101500063",
        component="Diagnostic Analyte Component 15-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_064": ClinicalConcept_15(
        concept_id="CONCEPT_15_064",
        loinc_num="25064-1",
        snomed_ct="101500064",
        component="Diagnostic Analyte Component 15-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_065": ClinicalConcept_15(
        concept_id="CONCEPT_15_065",
        loinc_num="25065-2",
        snomed_ct="101500065",
        component="Diagnostic Analyte Component 15-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_066": ClinicalConcept_15(
        concept_id="CONCEPT_15_066",
        loinc_num="25066-3",
        snomed_ct="101500066",
        component="Diagnostic Analyte Component 15-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_067": ClinicalConcept_15(
        concept_id="CONCEPT_15_067",
        loinc_num="25067-4",
        snomed_ct="101500067",
        component="Diagnostic Analyte Component 15-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_068": ClinicalConcept_15(
        concept_id="CONCEPT_15_068",
        loinc_num="25068-5",
        snomed_ct="101500068",
        component="Diagnostic Analyte Component 15-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_069": ClinicalConcept_15(
        concept_id="CONCEPT_15_069",
        loinc_num="25069-6",
        snomed_ct="101500069",
        component="Diagnostic Analyte Component 15-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_070": ClinicalConcept_15(
        concept_id="CONCEPT_15_070",
        loinc_num="25070-7",
        snomed_ct="101500070",
        component="Diagnostic Analyte Component 15-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_071": ClinicalConcept_15(
        concept_id="CONCEPT_15_071",
        loinc_num="25071-8",
        snomed_ct="101500071",
        component="Diagnostic Analyte Component 15-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_072": ClinicalConcept_15(
        concept_id="CONCEPT_15_072",
        loinc_num="25072-0",
        snomed_ct="101500072",
        component="Diagnostic Analyte Component 15-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_073": ClinicalConcept_15(
        concept_id="CONCEPT_15_073",
        loinc_num="25073-1",
        snomed_ct="101500073",
        component="Diagnostic Analyte Component 15-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_074": ClinicalConcept_15(
        concept_id="CONCEPT_15_074",
        loinc_num="25074-2",
        snomed_ct="101500074",
        component="Diagnostic Analyte Component 15-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_075": ClinicalConcept_15(
        concept_id="CONCEPT_15_075",
        loinc_num="25075-3",
        snomed_ct="101500075",
        component="Diagnostic Analyte Component 15-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_076": ClinicalConcept_15(
        concept_id="CONCEPT_15_076",
        loinc_num="25076-4",
        snomed_ct="101500076",
        component="Diagnostic Analyte Component 15-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_077": ClinicalConcept_15(
        concept_id="CONCEPT_15_077",
        loinc_num="25077-5",
        snomed_ct="101500077",
        component="Diagnostic Analyte Component 15-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_078": ClinicalConcept_15(
        concept_id="CONCEPT_15_078",
        loinc_num="25078-6",
        snomed_ct="101500078",
        component="Diagnostic Analyte Component 15-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_079": ClinicalConcept_15(
        concept_id="CONCEPT_15_079",
        loinc_num="25079-7",
        snomed_ct="101500079",
        component="Diagnostic Analyte Component 15-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_080": ClinicalConcept_15(
        concept_id="CONCEPT_15_080",
        loinc_num="25080-8",
        snomed_ct="101500080",
        component="Diagnostic Analyte Component 15-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_081": ClinicalConcept_15(
        concept_id="CONCEPT_15_081",
        loinc_num="25081-0",
        snomed_ct="101500081",
        component="Diagnostic Analyte Component 15-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_082": ClinicalConcept_15(
        concept_id="CONCEPT_15_082",
        loinc_num="25082-1",
        snomed_ct="101500082",
        component="Diagnostic Analyte Component 15-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_083": ClinicalConcept_15(
        concept_id="CONCEPT_15_083",
        loinc_num="25083-2",
        snomed_ct="101500083",
        component="Diagnostic Analyte Component 15-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_084": ClinicalConcept_15(
        concept_id="CONCEPT_15_084",
        loinc_num="25084-3",
        snomed_ct="101500084",
        component="Diagnostic Analyte Component 15-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_085": ClinicalConcept_15(
        concept_id="CONCEPT_15_085",
        loinc_num="25085-4",
        snomed_ct="101500085",
        component="Diagnostic Analyte Component 15-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_086": ClinicalConcept_15(
        concept_id="CONCEPT_15_086",
        loinc_num="25086-5",
        snomed_ct="101500086",
        component="Diagnostic Analyte Component 15-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_087": ClinicalConcept_15(
        concept_id="CONCEPT_15_087",
        loinc_num="25087-6",
        snomed_ct="101500087",
        component="Diagnostic Analyte Component 15-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_088": ClinicalConcept_15(
        concept_id="CONCEPT_15_088",
        loinc_num="25088-7",
        snomed_ct="101500088",
        component="Diagnostic Analyte Component 15-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_089": ClinicalConcept_15(
        concept_id="CONCEPT_15_089",
        loinc_num="25089-8",
        snomed_ct="101500089",
        component="Diagnostic Analyte Component 15-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_090": ClinicalConcept_15(
        concept_id="CONCEPT_15_090",
        loinc_num="25090-0",
        snomed_ct="101500090",
        component="Diagnostic Analyte Component 15-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_091": ClinicalConcept_15(
        concept_id="CONCEPT_15_091",
        loinc_num="25091-1",
        snomed_ct="101500091",
        component="Diagnostic Analyte Component 15-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_092": ClinicalConcept_15(
        concept_id="CONCEPT_15_092",
        loinc_num="25092-2",
        snomed_ct="101500092",
        component="Diagnostic Analyte Component 15-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_093": ClinicalConcept_15(
        concept_id="CONCEPT_15_093",
        loinc_num="25093-3",
        snomed_ct="101500093",
        component="Diagnostic Analyte Component 15-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_094": ClinicalConcept_15(
        concept_id="CONCEPT_15_094",
        loinc_num="25094-4",
        snomed_ct="101500094",
        component="Diagnostic Analyte Component 15-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_095": ClinicalConcept_15(
        concept_id="CONCEPT_15_095",
        loinc_num="25095-5",
        snomed_ct="101500095",
        component="Diagnostic Analyte Component 15-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_096": ClinicalConcept_15(
        concept_id="CONCEPT_15_096",
        loinc_num="25096-6",
        snomed_ct="101500096",
        component="Diagnostic Analyte Component 15-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_097": ClinicalConcept_15(
        concept_id="CONCEPT_15_097",
        loinc_num="25097-7",
        snomed_ct="101500097",
        component="Diagnostic Analyte Component 15-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_098": ClinicalConcept_15(
        concept_id="CONCEPT_15_098",
        loinc_num="25098-8",
        snomed_ct="101500098",
        component="Diagnostic Analyte Component 15-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_099": ClinicalConcept_15(
        concept_id="CONCEPT_15_099",
        loinc_num="25099-0",
        snomed_ct="101500099",
        component="Diagnostic Analyte Component 15-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_100": ClinicalConcept_15(
        concept_id="CONCEPT_15_100",
        loinc_num="25100-1",
        snomed_ct="101500100",
        component="Diagnostic Analyte Component 15-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_101": ClinicalConcept_15(
        concept_id="CONCEPT_15_101",
        loinc_num="25101-2",
        snomed_ct="101500101",
        component="Diagnostic Analyte Component 15-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_102": ClinicalConcept_15(
        concept_id="CONCEPT_15_102",
        loinc_num="25102-3",
        snomed_ct="101500102",
        component="Diagnostic Analyte Component 15-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_103": ClinicalConcept_15(
        concept_id="CONCEPT_15_103",
        loinc_num="25103-4",
        snomed_ct="101500103",
        component="Diagnostic Analyte Component 15-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_104": ClinicalConcept_15(
        concept_id="CONCEPT_15_104",
        loinc_num="25104-5",
        snomed_ct="101500104",
        component="Diagnostic Analyte Component 15-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_105": ClinicalConcept_15(
        concept_id="CONCEPT_15_105",
        loinc_num="25105-6",
        snomed_ct="101500105",
        component="Diagnostic Analyte Component 15-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_106": ClinicalConcept_15(
        concept_id="CONCEPT_15_106",
        loinc_num="25106-7",
        snomed_ct="101500106",
        component="Diagnostic Analyte Component 15-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_107": ClinicalConcept_15(
        concept_id="CONCEPT_15_107",
        loinc_num="25107-8",
        snomed_ct="101500107",
        component="Diagnostic Analyte Component 15-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_108": ClinicalConcept_15(
        concept_id="CONCEPT_15_108",
        loinc_num="25108-0",
        snomed_ct="101500108",
        component="Diagnostic Analyte Component 15-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_109": ClinicalConcept_15(
        concept_id="CONCEPT_15_109",
        loinc_num="25109-1",
        snomed_ct="101500109",
        component="Diagnostic Analyte Component 15-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_110": ClinicalConcept_15(
        concept_id="CONCEPT_15_110",
        loinc_num="25110-2",
        snomed_ct="101500110",
        component="Diagnostic Analyte Component 15-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_111": ClinicalConcept_15(
        concept_id="CONCEPT_15_111",
        loinc_num="25111-3",
        snomed_ct="101500111",
        component="Diagnostic Analyte Component 15-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_112": ClinicalConcept_15(
        concept_id="CONCEPT_15_112",
        loinc_num="25112-4",
        snomed_ct="101500112",
        component="Diagnostic Analyte Component 15-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_113": ClinicalConcept_15(
        concept_id="CONCEPT_15_113",
        loinc_num="25113-5",
        snomed_ct="101500113",
        component="Diagnostic Analyte Component 15-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_114": ClinicalConcept_15(
        concept_id="CONCEPT_15_114",
        loinc_num="25114-6",
        snomed_ct="101500114",
        component="Diagnostic Analyte Component 15-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_115": ClinicalConcept_15(
        concept_id="CONCEPT_15_115",
        loinc_num="25115-7",
        snomed_ct="101500115",
        component="Diagnostic Analyte Component 15-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_116": ClinicalConcept_15(
        concept_id="CONCEPT_15_116",
        loinc_num="25116-8",
        snomed_ct="101500116",
        component="Diagnostic Analyte Component 15-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_117": ClinicalConcept_15(
        concept_id="CONCEPT_15_117",
        loinc_num="25117-0",
        snomed_ct="101500117",
        component="Diagnostic Analyte Component 15-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_118": ClinicalConcept_15(
        concept_id="CONCEPT_15_118",
        loinc_num="25118-1",
        snomed_ct="101500118",
        component="Diagnostic Analyte Component 15-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_119": ClinicalConcept_15(
        concept_id="CONCEPT_15_119",
        loinc_num="25119-2",
        snomed_ct="101500119",
        component="Diagnostic Analyte Component 15-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_120": ClinicalConcept_15(
        concept_id="CONCEPT_15_120",
        loinc_num="25120-3",
        snomed_ct="101500120",
        component="Diagnostic Analyte Component 15-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_121": ClinicalConcept_15(
        concept_id="CONCEPT_15_121",
        loinc_num="25121-4",
        snomed_ct="101500121",
        component="Diagnostic Analyte Component 15-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_122": ClinicalConcept_15(
        concept_id="CONCEPT_15_122",
        loinc_num="25122-5",
        snomed_ct="101500122",
        component="Diagnostic Analyte Component 15-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_123": ClinicalConcept_15(
        concept_id="CONCEPT_15_123",
        loinc_num="25123-6",
        snomed_ct="101500123",
        component="Diagnostic Analyte Component 15-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_124": ClinicalConcept_15(
        concept_id="CONCEPT_15_124",
        loinc_num="25124-7",
        snomed_ct="101500124",
        component="Diagnostic Analyte Component 15-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_125": ClinicalConcept_15(
        concept_id="CONCEPT_15_125",
        loinc_num="25125-8",
        snomed_ct="101500125",
        component="Diagnostic Analyte Component 15-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_126": ClinicalConcept_15(
        concept_id="CONCEPT_15_126",
        loinc_num="25126-0",
        snomed_ct="101500126",
        component="Diagnostic Analyte Component 15-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_127": ClinicalConcept_15(
        concept_id="CONCEPT_15_127",
        loinc_num="25127-1",
        snomed_ct="101500127",
        component="Diagnostic Analyte Component 15-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_128": ClinicalConcept_15(
        concept_id="CONCEPT_15_128",
        loinc_num="25128-2",
        snomed_ct="101500128",
        component="Diagnostic Analyte Component 15-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_129": ClinicalConcept_15(
        concept_id="CONCEPT_15_129",
        loinc_num="25129-3",
        snomed_ct="101500129",
        component="Diagnostic Analyte Component 15-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_130": ClinicalConcept_15(
        concept_id="CONCEPT_15_130",
        loinc_num="25130-4",
        snomed_ct="101500130",
        component="Diagnostic Analyte Component 15-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_131": ClinicalConcept_15(
        concept_id="CONCEPT_15_131",
        loinc_num="25131-5",
        snomed_ct="101500131",
        component="Diagnostic Analyte Component 15-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_132": ClinicalConcept_15(
        concept_id="CONCEPT_15_132",
        loinc_num="25132-6",
        snomed_ct="101500132",
        component="Diagnostic Analyte Component 15-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_133": ClinicalConcept_15(
        concept_id="CONCEPT_15_133",
        loinc_num="25133-7",
        snomed_ct="101500133",
        component="Diagnostic Analyte Component 15-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_134": ClinicalConcept_15(
        concept_id="CONCEPT_15_134",
        loinc_num="25134-8",
        snomed_ct="101500134",
        component="Diagnostic Analyte Component 15-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_135": ClinicalConcept_15(
        concept_id="CONCEPT_15_135",
        loinc_num="25135-0",
        snomed_ct="101500135",
        component="Diagnostic Analyte Component 15-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_136": ClinicalConcept_15(
        concept_id="CONCEPT_15_136",
        loinc_num="25136-1",
        snomed_ct="101500136",
        component="Diagnostic Analyte Component 15-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_137": ClinicalConcept_15(
        concept_id="CONCEPT_15_137",
        loinc_num="25137-2",
        snomed_ct="101500137",
        component="Diagnostic Analyte Component 15-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_138": ClinicalConcept_15(
        concept_id="CONCEPT_15_138",
        loinc_num="25138-3",
        snomed_ct="101500138",
        component="Diagnostic Analyte Component 15-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_139": ClinicalConcept_15(
        concept_id="CONCEPT_15_139",
        loinc_num="25139-4",
        snomed_ct="101500139",
        component="Diagnostic Analyte Component 15-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_140": ClinicalConcept_15(
        concept_id="CONCEPT_15_140",
        loinc_num="25140-5",
        snomed_ct="101500140",
        component="Diagnostic Analyte Component 15-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_141": ClinicalConcept_15(
        concept_id="CONCEPT_15_141",
        loinc_num="25141-6",
        snomed_ct="101500141",
        component="Diagnostic Analyte Component 15-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_142": ClinicalConcept_15(
        concept_id="CONCEPT_15_142",
        loinc_num="25142-7",
        snomed_ct="101500142",
        component="Diagnostic Analyte Component 15-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_143": ClinicalConcept_15(
        concept_id="CONCEPT_15_143",
        loinc_num="25143-8",
        snomed_ct="101500143",
        component="Diagnostic Analyte Component 15-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_144": ClinicalConcept_15(
        concept_id="CONCEPT_15_144",
        loinc_num="25144-0",
        snomed_ct="101500144",
        component="Diagnostic Analyte Component 15-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_145": ClinicalConcept_15(
        concept_id="CONCEPT_15_145",
        loinc_num="25145-1",
        snomed_ct="101500145",
        component="Diagnostic Analyte Component 15-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_146": ClinicalConcept_15(
        concept_id="CONCEPT_15_146",
        loinc_num="25146-2",
        snomed_ct="101500146",
        component="Diagnostic Analyte Component 15-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_147": ClinicalConcept_15(
        concept_id="CONCEPT_15_147",
        loinc_num="25147-3",
        snomed_ct="101500147",
        component="Diagnostic Analyte Component 15-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_148": ClinicalConcept_15(
        concept_id="CONCEPT_15_148",
        loinc_num="25148-4",
        snomed_ct="101500148",
        component="Diagnostic Analyte Component 15-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_149": ClinicalConcept_15(
        concept_id="CONCEPT_15_149",
        loinc_num="25149-5",
        snomed_ct="101500149",
        component="Diagnostic Analyte Component 15-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_150": ClinicalConcept_15(
        concept_id="CONCEPT_15_150",
        loinc_num="25150-6",
        snomed_ct="101500150",
        component="Diagnostic Analyte Component 15-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_151": ClinicalConcept_15(
        concept_id="CONCEPT_15_151",
        loinc_num="25151-7",
        snomed_ct="101500151",
        component="Diagnostic Analyte Component 15-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_152": ClinicalConcept_15(
        concept_id="CONCEPT_15_152",
        loinc_num="25152-8",
        snomed_ct="101500152",
        component="Diagnostic Analyte Component 15-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_153": ClinicalConcept_15(
        concept_id="CONCEPT_15_153",
        loinc_num="25153-0",
        snomed_ct="101500153",
        component="Diagnostic Analyte Component 15-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_154": ClinicalConcept_15(
        concept_id="CONCEPT_15_154",
        loinc_num="25154-1",
        snomed_ct="101500154",
        component="Diagnostic Analyte Component 15-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_155": ClinicalConcept_15(
        concept_id="CONCEPT_15_155",
        loinc_num="25155-2",
        snomed_ct="101500155",
        component="Diagnostic Analyte Component 15-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_156": ClinicalConcept_15(
        concept_id="CONCEPT_15_156",
        loinc_num="25156-3",
        snomed_ct="101500156",
        component="Diagnostic Analyte Component 15-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_157": ClinicalConcept_15(
        concept_id="CONCEPT_15_157",
        loinc_num="25157-4",
        snomed_ct="101500157",
        component="Diagnostic Analyte Component 15-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_158": ClinicalConcept_15(
        concept_id="CONCEPT_15_158",
        loinc_num="25158-5",
        snomed_ct="101500158",
        component="Diagnostic Analyte Component 15-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_159": ClinicalConcept_15(
        concept_id="CONCEPT_15_159",
        loinc_num="25159-6",
        snomed_ct="101500159",
        component="Diagnostic Analyte Component 15-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_160": ClinicalConcept_15(
        concept_id="CONCEPT_15_160",
        loinc_num="25160-7",
        snomed_ct="101500160",
        component="Diagnostic Analyte Component 15-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_161": ClinicalConcept_15(
        concept_id="CONCEPT_15_161",
        loinc_num="25161-8",
        snomed_ct="101500161",
        component="Diagnostic Analyte Component 15-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_162": ClinicalConcept_15(
        concept_id="CONCEPT_15_162",
        loinc_num="25162-0",
        snomed_ct="101500162",
        component="Diagnostic Analyte Component 15-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_163": ClinicalConcept_15(
        concept_id="CONCEPT_15_163",
        loinc_num="25163-1",
        snomed_ct="101500163",
        component="Diagnostic Analyte Component 15-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_164": ClinicalConcept_15(
        concept_id="CONCEPT_15_164",
        loinc_num="25164-2",
        snomed_ct="101500164",
        component="Diagnostic Analyte Component 15-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_165": ClinicalConcept_15(
        concept_id="CONCEPT_15_165",
        loinc_num="25165-3",
        snomed_ct="101500165",
        component="Diagnostic Analyte Component 15-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_166": ClinicalConcept_15(
        concept_id="CONCEPT_15_166",
        loinc_num="25166-4",
        snomed_ct="101500166",
        component="Diagnostic Analyte Component 15-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_167": ClinicalConcept_15(
        concept_id="CONCEPT_15_167",
        loinc_num="25167-5",
        snomed_ct="101500167",
        component="Diagnostic Analyte Component 15-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_168": ClinicalConcept_15(
        concept_id="CONCEPT_15_168",
        loinc_num="25168-6",
        snomed_ct="101500168",
        component="Diagnostic Analyte Component 15-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_169": ClinicalConcept_15(
        concept_id="CONCEPT_15_169",
        loinc_num="25169-7",
        snomed_ct="101500169",
        component="Diagnostic Analyte Component 15-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_170": ClinicalConcept_15(
        concept_id="CONCEPT_15_170",
        loinc_num="25170-8",
        snomed_ct="101500170",
        component="Diagnostic Analyte Component 15-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_171": ClinicalConcept_15(
        concept_id="CONCEPT_15_171",
        loinc_num="25171-0",
        snomed_ct="101500171",
        component="Diagnostic Analyte Component 15-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_172": ClinicalConcept_15(
        concept_id="CONCEPT_15_172",
        loinc_num="25172-1",
        snomed_ct="101500172",
        component="Diagnostic Analyte Component 15-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_173": ClinicalConcept_15(
        concept_id="CONCEPT_15_173",
        loinc_num="25173-2",
        snomed_ct="101500173",
        component="Diagnostic Analyte Component 15-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_174": ClinicalConcept_15(
        concept_id="CONCEPT_15_174",
        loinc_num="25174-3",
        snomed_ct="101500174",
        component="Diagnostic Analyte Component 15-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_175": ClinicalConcept_15(
        concept_id="CONCEPT_15_175",
        loinc_num="25175-4",
        snomed_ct="101500175",
        component="Diagnostic Analyte Component 15-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_176": ClinicalConcept_15(
        concept_id="CONCEPT_15_176",
        loinc_num="25176-5",
        snomed_ct="101500176",
        component="Diagnostic Analyte Component 15-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_177": ClinicalConcept_15(
        concept_id="CONCEPT_15_177",
        loinc_num="25177-6",
        snomed_ct="101500177",
        component="Diagnostic Analyte Component 15-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_178": ClinicalConcept_15(
        concept_id="CONCEPT_15_178",
        loinc_num="25178-7",
        snomed_ct="101500178",
        component="Diagnostic Analyte Component 15-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_179": ClinicalConcept_15(
        concept_id="CONCEPT_15_179",
        loinc_num="25179-8",
        snomed_ct="101500179",
        component="Diagnostic Analyte Component 15-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_180": ClinicalConcept_15(
        concept_id="CONCEPT_15_180",
        loinc_num="25180-0",
        snomed_ct="101500180",
        component="Diagnostic Analyte Component 15-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_181": ClinicalConcept_15(
        concept_id="CONCEPT_15_181",
        loinc_num="25181-1",
        snomed_ct="101500181",
        component="Diagnostic Analyte Component 15-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_182": ClinicalConcept_15(
        concept_id="CONCEPT_15_182",
        loinc_num="25182-2",
        snomed_ct="101500182",
        component="Diagnostic Analyte Component 15-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_183": ClinicalConcept_15(
        concept_id="CONCEPT_15_183",
        loinc_num="25183-3",
        snomed_ct="101500183",
        component="Diagnostic Analyte Component 15-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_184": ClinicalConcept_15(
        concept_id="CONCEPT_15_184",
        loinc_num="25184-4",
        snomed_ct="101500184",
        component="Diagnostic Analyte Component 15-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_185": ClinicalConcept_15(
        concept_id="CONCEPT_15_185",
        loinc_num="25185-5",
        snomed_ct="101500185",
        component="Diagnostic Analyte Component 15-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_186": ClinicalConcept_15(
        concept_id="CONCEPT_15_186",
        loinc_num="25186-6",
        snomed_ct="101500186",
        component="Diagnostic Analyte Component 15-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_187": ClinicalConcept_15(
        concept_id="CONCEPT_15_187",
        loinc_num="25187-7",
        snomed_ct="101500187",
        component="Diagnostic Analyte Component 15-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_188": ClinicalConcept_15(
        concept_id="CONCEPT_15_188",
        loinc_num="25188-8",
        snomed_ct="101500188",
        component="Diagnostic Analyte Component 15-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_189": ClinicalConcept_15(
        concept_id="CONCEPT_15_189",
        loinc_num="25189-0",
        snomed_ct="101500189",
        component="Diagnostic Analyte Component 15-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_190": ClinicalConcept_15(
        concept_id="CONCEPT_15_190",
        loinc_num="25190-1",
        snomed_ct="101500190",
        component="Diagnostic Analyte Component 15-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_191": ClinicalConcept_15(
        concept_id="CONCEPT_15_191",
        loinc_num="25191-2",
        snomed_ct="101500191",
        component="Diagnostic Analyte Component 15-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_192": ClinicalConcept_15(
        concept_id="CONCEPT_15_192",
        loinc_num="25192-3",
        snomed_ct="101500192",
        component="Diagnostic Analyte Component 15-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_193": ClinicalConcept_15(
        concept_id="CONCEPT_15_193",
        loinc_num="25193-4",
        snomed_ct="101500193",
        component="Diagnostic Analyte Component 15-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_194": ClinicalConcept_15(
        concept_id="CONCEPT_15_194",
        loinc_num="25194-5",
        snomed_ct="101500194",
        component="Diagnostic Analyte Component 15-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_195": ClinicalConcept_15(
        concept_id="CONCEPT_15_195",
        loinc_num="25195-6",
        snomed_ct="101500195",
        component="Diagnostic Analyte Component 15-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_196": ClinicalConcept_15(
        concept_id="CONCEPT_15_196",
        loinc_num="25196-7",
        snomed_ct="101500196",
        component="Diagnostic Analyte Component 15-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_197": ClinicalConcept_15(
        concept_id="CONCEPT_15_197",
        loinc_num="25197-8",
        snomed_ct="101500197",
        component="Diagnostic Analyte Component 15-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_198": ClinicalConcept_15(
        concept_id="CONCEPT_15_198",
        loinc_num="25198-0",
        snomed_ct="101500198",
        component="Diagnostic Analyte Component 15-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_15_199": ClinicalConcept_15(
        concept_id="CONCEPT_15_199",
        loinc_num="25199-1",
        snomed_ct="101500199",
        component="Diagnostic Analyte Component 15-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
