"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 01"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_01:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_01 = {
    "CONCEPT_01_001": ClinicalConcept_01(
        concept_id="CONCEPT_01_001",
        loinc_num="11001-1",
        snomed_ct="100100001",
        component="Diagnostic Analyte Component 01-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_002": ClinicalConcept_01(
        concept_id="CONCEPT_01_002",
        loinc_num="11002-2",
        snomed_ct="100100002",
        component="Diagnostic Analyte Component 01-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_003": ClinicalConcept_01(
        concept_id="CONCEPT_01_003",
        loinc_num="11003-3",
        snomed_ct="100100003",
        component="Diagnostic Analyte Component 01-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_004": ClinicalConcept_01(
        concept_id="CONCEPT_01_004",
        loinc_num="11004-4",
        snomed_ct="100100004",
        component="Diagnostic Analyte Component 01-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_005": ClinicalConcept_01(
        concept_id="CONCEPT_01_005",
        loinc_num="11005-5",
        snomed_ct="100100005",
        component="Diagnostic Analyte Component 01-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_006": ClinicalConcept_01(
        concept_id="CONCEPT_01_006",
        loinc_num="11006-6",
        snomed_ct="100100006",
        component="Diagnostic Analyte Component 01-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_007": ClinicalConcept_01(
        concept_id="CONCEPT_01_007",
        loinc_num="11007-7",
        snomed_ct="100100007",
        component="Diagnostic Analyte Component 01-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_008": ClinicalConcept_01(
        concept_id="CONCEPT_01_008",
        loinc_num="11008-8",
        snomed_ct="100100008",
        component="Diagnostic Analyte Component 01-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_009": ClinicalConcept_01(
        concept_id="CONCEPT_01_009",
        loinc_num="11009-0",
        snomed_ct="100100009",
        component="Diagnostic Analyte Component 01-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_010": ClinicalConcept_01(
        concept_id="CONCEPT_01_010",
        loinc_num="11010-1",
        snomed_ct="100100010",
        component="Diagnostic Analyte Component 01-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_011": ClinicalConcept_01(
        concept_id="CONCEPT_01_011",
        loinc_num="11011-2",
        snomed_ct="100100011",
        component="Diagnostic Analyte Component 01-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_012": ClinicalConcept_01(
        concept_id="CONCEPT_01_012",
        loinc_num="11012-3",
        snomed_ct="100100012",
        component="Diagnostic Analyte Component 01-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_013": ClinicalConcept_01(
        concept_id="CONCEPT_01_013",
        loinc_num="11013-4",
        snomed_ct="100100013",
        component="Diagnostic Analyte Component 01-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_014": ClinicalConcept_01(
        concept_id="CONCEPT_01_014",
        loinc_num="11014-5",
        snomed_ct="100100014",
        component="Diagnostic Analyte Component 01-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_015": ClinicalConcept_01(
        concept_id="CONCEPT_01_015",
        loinc_num="11015-6",
        snomed_ct="100100015",
        component="Diagnostic Analyte Component 01-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_016": ClinicalConcept_01(
        concept_id="CONCEPT_01_016",
        loinc_num="11016-7",
        snomed_ct="100100016",
        component="Diagnostic Analyte Component 01-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_017": ClinicalConcept_01(
        concept_id="CONCEPT_01_017",
        loinc_num="11017-8",
        snomed_ct="100100017",
        component="Diagnostic Analyte Component 01-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_018": ClinicalConcept_01(
        concept_id="CONCEPT_01_018",
        loinc_num="11018-0",
        snomed_ct="100100018",
        component="Diagnostic Analyte Component 01-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_019": ClinicalConcept_01(
        concept_id="CONCEPT_01_019",
        loinc_num="11019-1",
        snomed_ct="100100019",
        component="Diagnostic Analyte Component 01-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_020": ClinicalConcept_01(
        concept_id="CONCEPT_01_020",
        loinc_num="11020-2",
        snomed_ct="100100020",
        component="Diagnostic Analyte Component 01-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_021": ClinicalConcept_01(
        concept_id="CONCEPT_01_021",
        loinc_num="11021-3",
        snomed_ct="100100021",
        component="Diagnostic Analyte Component 01-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_022": ClinicalConcept_01(
        concept_id="CONCEPT_01_022",
        loinc_num="11022-4",
        snomed_ct="100100022",
        component="Diagnostic Analyte Component 01-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_023": ClinicalConcept_01(
        concept_id="CONCEPT_01_023",
        loinc_num="11023-5",
        snomed_ct="100100023",
        component="Diagnostic Analyte Component 01-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_024": ClinicalConcept_01(
        concept_id="CONCEPT_01_024",
        loinc_num="11024-6",
        snomed_ct="100100024",
        component="Diagnostic Analyte Component 01-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_025": ClinicalConcept_01(
        concept_id="CONCEPT_01_025",
        loinc_num="11025-7",
        snomed_ct="100100025",
        component="Diagnostic Analyte Component 01-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_026": ClinicalConcept_01(
        concept_id="CONCEPT_01_026",
        loinc_num="11026-8",
        snomed_ct="100100026",
        component="Diagnostic Analyte Component 01-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_027": ClinicalConcept_01(
        concept_id="CONCEPT_01_027",
        loinc_num="11027-0",
        snomed_ct="100100027",
        component="Diagnostic Analyte Component 01-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_028": ClinicalConcept_01(
        concept_id="CONCEPT_01_028",
        loinc_num="11028-1",
        snomed_ct="100100028",
        component="Diagnostic Analyte Component 01-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_029": ClinicalConcept_01(
        concept_id="CONCEPT_01_029",
        loinc_num="11029-2",
        snomed_ct="100100029",
        component="Diagnostic Analyte Component 01-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_030": ClinicalConcept_01(
        concept_id="CONCEPT_01_030",
        loinc_num="11030-3",
        snomed_ct="100100030",
        component="Diagnostic Analyte Component 01-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_031": ClinicalConcept_01(
        concept_id="CONCEPT_01_031",
        loinc_num="11031-4",
        snomed_ct="100100031",
        component="Diagnostic Analyte Component 01-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_032": ClinicalConcept_01(
        concept_id="CONCEPT_01_032",
        loinc_num="11032-5",
        snomed_ct="100100032",
        component="Diagnostic Analyte Component 01-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_033": ClinicalConcept_01(
        concept_id="CONCEPT_01_033",
        loinc_num="11033-6",
        snomed_ct="100100033",
        component="Diagnostic Analyte Component 01-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_034": ClinicalConcept_01(
        concept_id="CONCEPT_01_034",
        loinc_num="11034-7",
        snomed_ct="100100034",
        component="Diagnostic Analyte Component 01-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_035": ClinicalConcept_01(
        concept_id="CONCEPT_01_035",
        loinc_num="11035-8",
        snomed_ct="100100035",
        component="Diagnostic Analyte Component 01-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_036": ClinicalConcept_01(
        concept_id="CONCEPT_01_036",
        loinc_num="11036-0",
        snomed_ct="100100036",
        component="Diagnostic Analyte Component 01-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_037": ClinicalConcept_01(
        concept_id="CONCEPT_01_037",
        loinc_num="11037-1",
        snomed_ct="100100037",
        component="Diagnostic Analyte Component 01-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_038": ClinicalConcept_01(
        concept_id="CONCEPT_01_038",
        loinc_num="11038-2",
        snomed_ct="100100038",
        component="Diagnostic Analyte Component 01-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_039": ClinicalConcept_01(
        concept_id="CONCEPT_01_039",
        loinc_num="11039-3",
        snomed_ct="100100039",
        component="Diagnostic Analyte Component 01-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_040": ClinicalConcept_01(
        concept_id="CONCEPT_01_040",
        loinc_num="11040-4",
        snomed_ct="100100040",
        component="Diagnostic Analyte Component 01-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_041": ClinicalConcept_01(
        concept_id="CONCEPT_01_041",
        loinc_num="11041-5",
        snomed_ct="100100041",
        component="Diagnostic Analyte Component 01-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_042": ClinicalConcept_01(
        concept_id="CONCEPT_01_042",
        loinc_num="11042-6",
        snomed_ct="100100042",
        component="Diagnostic Analyte Component 01-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_043": ClinicalConcept_01(
        concept_id="CONCEPT_01_043",
        loinc_num="11043-7",
        snomed_ct="100100043",
        component="Diagnostic Analyte Component 01-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_044": ClinicalConcept_01(
        concept_id="CONCEPT_01_044",
        loinc_num="11044-8",
        snomed_ct="100100044",
        component="Diagnostic Analyte Component 01-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_045": ClinicalConcept_01(
        concept_id="CONCEPT_01_045",
        loinc_num="11045-0",
        snomed_ct="100100045",
        component="Diagnostic Analyte Component 01-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_046": ClinicalConcept_01(
        concept_id="CONCEPT_01_046",
        loinc_num="11046-1",
        snomed_ct="100100046",
        component="Diagnostic Analyte Component 01-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_047": ClinicalConcept_01(
        concept_id="CONCEPT_01_047",
        loinc_num="11047-2",
        snomed_ct="100100047",
        component="Diagnostic Analyte Component 01-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_048": ClinicalConcept_01(
        concept_id="CONCEPT_01_048",
        loinc_num="11048-3",
        snomed_ct="100100048",
        component="Diagnostic Analyte Component 01-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_049": ClinicalConcept_01(
        concept_id="CONCEPT_01_049",
        loinc_num="11049-4",
        snomed_ct="100100049",
        component="Diagnostic Analyte Component 01-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_050": ClinicalConcept_01(
        concept_id="CONCEPT_01_050",
        loinc_num="11050-5",
        snomed_ct="100100050",
        component="Diagnostic Analyte Component 01-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_051": ClinicalConcept_01(
        concept_id="CONCEPT_01_051",
        loinc_num="11051-6",
        snomed_ct="100100051",
        component="Diagnostic Analyte Component 01-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_052": ClinicalConcept_01(
        concept_id="CONCEPT_01_052",
        loinc_num="11052-7",
        snomed_ct="100100052",
        component="Diagnostic Analyte Component 01-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_053": ClinicalConcept_01(
        concept_id="CONCEPT_01_053",
        loinc_num="11053-8",
        snomed_ct="100100053",
        component="Diagnostic Analyte Component 01-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_054": ClinicalConcept_01(
        concept_id="CONCEPT_01_054",
        loinc_num="11054-0",
        snomed_ct="100100054",
        component="Diagnostic Analyte Component 01-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_055": ClinicalConcept_01(
        concept_id="CONCEPT_01_055",
        loinc_num="11055-1",
        snomed_ct="100100055",
        component="Diagnostic Analyte Component 01-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_056": ClinicalConcept_01(
        concept_id="CONCEPT_01_056",
        loinc_num="11056-2",
        snomed_ct="100100056",
        component="Diagnostic Analyte Component 01-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_057": ClinicalConcept_01(
        concept_id="CONCEPT_01_057",
        loinc_num="11057-3",
        snomed_ct="100100057",
        component="Diagnostic Analyte Component 01-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_058": ClinicalConcept_01(
        concept_id="CONCEPT_01_058",
        loinc_num="11058-4",
        snomed_ct="100100058",
        component="Diagnostic Analyte Component 01-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_059": ClinicalConcept_01(
        concept_id="CONCEPT_01_059",
        loinc_num="11059-5",
        snomed_ct="100100059",
        component="Diagnostic Analyte Component 01-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_060": ClinicalConcept_01(
        concept_id="CONCEPT_01_060",
        loinc_num="11060-6",
        snomed_ct="100100060",
        component="Diagnostic Analyte Component 01-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_061": ClinicalConcept_01(
        concept_id="CONCEPT_01_061",
        loinc_num="11061-7",
        snomed_ct="100100061",
        component="Diagnostic Analyte Component 01-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_062": ClinicalConcept_01(
        concept_id="CONCEPT_01_062",
        loinc_num="11062-8",
        snomed_ct="100100062",
        component="Diagnostic Analyte Component 01-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_063": ClinicalConcept_01(
        concept_id="CONCEPT_01_063",
        loinc_num="11063-0",
        snomed_ct="100100063",
        component="Diagnostic Analyte Component 01-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_064": ClinicalConcept_01(
        concept_id="CONCEPT_01_064",
        loinc_num="11064-1",
        snomed_ct="100100064",
        component="Diagnostic Analyte Component 01-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_065": ClinicalConcept_01(
        concept_id="CONCEPT_01_065",
        loinc_num="11065-2",
        snomed_ct="100100065",
        component="Diagnostic Analyte Component 01-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_066": ClinicalConcept_01(
        concept_id="CONCEPT_01_066",
        loinc_num="11066-3",
        snomed_ct="100100066",
        component="Diagnostic Analyte Component 01-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_067": ClinicalConcept_01(
        concept_id="CONCEPT_01_067",
        loinc_num="11067-4",
        snomed_ct="100100067",
        component="Diagnostic Analyte Component 01-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_068": ClinicalConcept_01(
        concept_id="CONCEPT_01_068",
        loinc_num="11068-5",
        snomed_ct="100100068",
        component="Diagnostic Analyte Component 01-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_069": ClinicalConcept_01(
        concept_id="CONCEPT_01_069",
        loinc_num="11069-6",
        snomed_ct="100100069",
        component="Diagnostic Analyte Component 01-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_070": ClinicalConcept_01(
        concept_id="CONCEPT_01_070",
        loinc_num="11070-7",
        snomed_ct="100100070",
        component="Diagnostic Analyte Component 01-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_071": ClinicalConcept_01(
        concept_id="CONCEPT_01_071",
        loinc_num="11071-8",
        snomed_ct="100100071",
        component="Diagnostic Analyte Component 01-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_072": ClinicalConcept_01(
        concept_id="CONCEPT_01_072",
        loinc_num="11072-0",
        snomed_ct="100100072",
        component="Diagnostic Analyte Component 01-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_073": ClinicalConcept_01(
        concept_id="CONCEPT_01_073",
        loinc_num="11073-1",
        snomed_ct="100100073",
        component="Diagnostic Analyte Component 01-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_074": ClinicalConcept_01(
        concept_id="CONCEPT_01_074",
        loinc_num="11074-2",
        snomed_ct="100100074",
        component="Diagnostic Analyte Component 01-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_075": ClinicalConcept_01(
        concept_id="CONCEPT_01_075",
        loinc_num="11075-3",
        snomed_ct="100100075",
        component="Diagnostic Analyte Component 01-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_076": ClinicalConcept_01(
        concept_id="CONCEPT_01_076",
        loinc_num="11076-4",
        snomed_ct="100100076",
        component="Diagnostic Analyte Component 01-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_077": ClinicalConcept_01(
        concept_id="CONCEPT_01_077",
        loinc_num="11077-5",
        snomed_ct="100100077",
        component="Diagnostic Analyte Component 01-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_078": ClinicalConcept_01(
        concept_id="CONCEPT_01_078",
        loinc_num="11078-6",
        snomed_ct="100100078",
        component="Diagnostic Analyte Component 01-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_079": ClinicalConcept_01(
        concept_id="CONCEPT_01_079",
        loinc_num="11079-7",
        snomed_ct="100100079",
        component="Diagnostic Analyte Component 01-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_080": ClinicalConcept_01(
        concept_id="CONCEPT_01_080",
        loinc_num="11080-8",
        snomed_ct="100100080",
        component="Diagnostic Analyte Component 01-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_081": ClinicalConcept_01(
        concept_id="CONCEPT_01_081",
        loinc_num="11081-0",
        snomed_ct="100100081",
        component="Diagnostic Analyte Component 01-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_082": ClinicalConcept_01(
        concept_id="CONCEPT_01_082",
        loinc_num="11082-1",
        snomed_ct="100100082",
        component="Diagnostic Analyte Component 01-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_083": ClinicalConcept_01(
        concept_id="CONCEPT_01_083",
        loinc_num="11083-2",
        snomed_ct="100100083",
        component="Diagnostic Analyte Component 01-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_084": ClinicalConcept_01(
        concept_id="CONCEPT_01_084",
        loinc_num="11084-3",
        snomed_ct="100100084",
        component="Diagnostic Analyte Component 01-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_085": ClinicalConcept_01(
        concept_id="CONCEPT_01_085",
        loinc_num="11085-4",
        snomed_ct="100100085",
        component="Diagnostic Analyte Component 01-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_086": ClinicalConcept_01(
        concept_id="CONCEPT_01_086",
        loinc_num="11086-5",
        snomed_ct="100100086",
        component="Diagnostic Analyte Component 01-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_087": ClinicalConcept_01(
        concept_id="CONCEPT_01_087",
        loinc_num="11087-6",
        snomed_ct="100100087",
        component="Diagnostic Analyte Component 01-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_088": ClinicalConcept_01(
        concept_id="CONCEPT_01_088",
        loinc_num="11088-7",
        snomed_ct="100100088",
        component="Diagnostic Analyte Component 01-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_089": ClinicalConcept_01(
        concept_id="CONCEPT_01_089",
        loinc_num="11089-8",
        snomed_ct="100100089",
        component="Diagnostic Analyte Component 01-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_090": ClinicalConcept_01(
        concept_id="CONCEPT_01_090",
        loinc_num="11090-0",
        snomed_ct="100100090",
        component="Diagnostic Analyte Component 01-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_091": ClinicalConcept_01(
        concept_id="CONCEPT_01_091",
        loinc_num="11091-1",
        snomed_ct="100100091",
        component="Diagnostic Analyte Component 01-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_092": ClinicalConcept_01(
        concept_id="CONCEPT_01_092",
        loinc_num="11092-2",
        snomed_ct="100100092",
        component="Diagnostic Analyte Component 01-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_093": ClinicalConcept_01(
        concept_id="CONCEPT_01_093",
        loinc_num="11093-3",
        snomed_ct="100100093",
        component="Diagnostic Analyte Component 01-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_094": ClinicalConcept_01(
        concept_id="CONCEPT_01_094",
        loinc_num="11094-4",
        snomed_ct="100100094",
        component="Diagnostic Analyte Component 01-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_095": ClinicalConcept_01(
        concept_id="CONCEPT_01_095",
        loinc_num="11095-5",
        snomed_ct="100100095",
        component="Diagnostic Analyte Component 01-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_096": ClinicalConcept_01(
        concept_id="CONCEPT_01_096",
        loinc_num="11096-6",
        snomed_ct="100100096",
        component="Diagnostic Analyte Component 01-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_097": ClinicalConcept_01(
        concept_id="CONCEPT_01_097",
        loinc_num="11097-7",
        snomed_ct="100100097",
        component="Diagnostic Analyte Component 01-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_098": ClinicalConcept_01(
        concept_id="CONCEPT_01_098",
        loinc_num="11098-8",
        snomed_ct="100100098",
        component="Diagnostic Analyte Component 01-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_099": ClinicalConcept_01(
        concept_id="CONCEPT_01_099",
        loinc_num="11099-0",
        snomed_ct="100100099",
        component="Diagnostic Analyte Component 01-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_100": ClinicalConcept_01(
        concept_id="CONCEPT_01_100",
        loinc_num="11100-1",
        snomed_ct="100100100",
        component="Diagnostic Analyte Component 01-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_101": ClinicalConcept_01(
        concept_id="CONCEPT_01_101",
        loinc_num="11101-2",
        snomed_ct="100100101",
        component="Diagnostic Analyte Component 01-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_102": ClinicalConcept_01(
        concept_id="CONCEPT_01_102",
        loinc_num="11102-3",
        snomed_ct="100100102",
        component="Diagnostic Analyte Component 01-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_103": ClinicalConcept_01(
        concept_id="CONCEPT_01_103",
        loinc_num="11103-4",
        snomed_ct="100100103",
        component="Diagnostic Analyte Component 01-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_104": ClinicalConcept_01(
        concept_id="CONCEPT_01_104",
        loinc_num="11104-5",
        snomed_ct="100100104",
        component="Diagnostic Analyte Component 01-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_105": ClinicalConcept_01(
        concept_id="CONCEPT_01_105",
        loinc_num="11105-6",
        snomed_ct="100100105",
        component="Diagnostic Analyte Component 01-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_106": ClinicalConcept_01(
        concept_id="CONCEPT_01_106",
        loinc_num="11106-7",
        snomed_ct="100100106",
        component="Diagnostic Analyte Component 01-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_107": ClinicalConcept_01(
        concept_id="CONCEPT_01_107",
        loinc_num="11107-8",
        snomed_ct="100100107",
        component="Diagnostic Analyte Component 01-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_108": ClinicalConcept_01(
        concept_id="CONCEPT_01_108",
        loinc_num="11108-0",
        snomed_ct="100100108",
        component="Diagnostic Analyte Component 01-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_109": ClinicalConcept_01(
        concept_id="CONCEPT_01_109",
        loinc_num="11109-1",
        snomed_ct="100100109",
        component="Diagnostic Analyte Component 01-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_110": ClinicalConcept_01(
        concept_id="CONCEPT_01_110",
        loinc_num="11110-2",
        snomed_ct="100100110",
        component="Diagnostic Analyte Component 01-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_111": ClinicalConcept_01(
        concept_id="CONCEPT_01_111",
        loinc_num="11111-3",
        snomed_ct="100100111",
        component="Diagnostic Analyte Component 01-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_112": ClinicalConcept_01(
        concept_id="CONCEPT_01_112",
        loinc_num="11112-4",
        snomed_ct="100100112",
        component="Diagnostic Analyte Component 01-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_113": ClinicalConcept_01(
        concept_id="CONCEPT_01_113",
        loinc_num="11113-5",
        snomed_ct="100100113",
        component="Diagnostic Analyte Component 01-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_114": ClinicalConcept_01(
        concept_id="CONCEPT_01_114",
        loinc_num="11114-6",
        snomed_ct="100100114",
        component="Diagnostic Analyte Component 01-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_115": ClinicalConcept_01(
        concept_id="CONCEPT_01_115",
        loinc_num="11115-7",
        snomed_ct="100100115",
        component="Diagnostic Analyte Component 01-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_116": ClinicalConcept_01(
        concept_id="CONCEPT_01_116",
        loinc_num="11116-8",
        snomed_ct="100100116",
        component="Diagnostic Analyte Component 01-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_117": ClinicalConcept_01(
        concept_id="CONCEPT_01_117",
        loinc_num="11117-0",
        snomed_ct="100100117",
        component="Diagnostic Analyte Component 01-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_118": ClinicalConcept_01(
        concept_id="CONCEPT_01_118",
        loinc_num="11118-1",
        snomed_ct="100100118",
        component="Diagnostic Analyte Component 01-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_119": ClinicalConcept_01(
        concept_id="CONCEPT_01_119",
        loinc_num="11119-2",
        snomed_ct="100100119",
        component="Diagnostic Analyte Component 01-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_120": ClinicalConcept_01(
        concept_id="CONCEPT_01_120",
        loinc_num="11120-3",
        snomed_ct="100100120",
        component="Diagnostic Analyte Component 01-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_121": ClinicalConcept_01(
        concept_id="CONCEPT_01_121",
        loinc_num="11121-4",
        snomed_ct="100100121",
        component="Diagnostic Analyte Component 01-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_122": ClinicalConcept_01(
        concept_id="CONCEPT_01_122",
        loinc_num="11122-5",
        snomed_ct="100100122",
        component="Diagnostic Analyte Component 01-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_123": ClinicalConcept_01(
        concept_id="CONCEPT_01_123",
        loinc_num="11123-6",
        snomed_ct="100100123",
        component="Diagnostic Analyte Component 01-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_124": ClinicalConcept_01(
        concept_id="CONCEPT_01_124",
        loinc_num="11124-7",
        snomed_ct="100100124",
        component="Diagnostic Analyte Component 01-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_125": ClinicalConcept_01(
        concept_id="CONCEPT_01_125",
        loinc_num="11125-8",
        snomed_ct="100100125",
        component="Diagnostic Analyte Component 01-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_126": ClinicalConcept_01(
        concept_id="CONCEPT_01_126",
        loinc_num="11126-0",
        snomed_ct="100100126",
        component="Diagnostic Analyte Component 01-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_127": ClinicalConcept_01(
        concept_id="CONCEPT_01_127",
        loinc_num="11127-1",
        snomed_ct="100100127",
        component="Diagnostic Analyte Component 01-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_128": ClinicalConcept_01(
        concept_id="CONCEPT_01_128",
        loinc_num="11128-2",
        snomed_ct="100100128",
        component="Diagnostic Analyte Component 01-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_129": ClinicalConcept_01(
        concept_id="CONCEPT_01_129",
        loinc_num="11129-3",
        snomed_ct="100100129",
        component="Diagnostic Analyte Component 01-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_130": ClinicalConcept_01(
        concept_id="CONCEPT_01_130",
        loinc_num="11130-4",
        snomed_ct="100100130",
        component="Diagnostic Analyte Component 01-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_131": ClinicalConcept_01(
        concept_id="CONCEPT_01_131",
        loinc_num="11131-5",
        snomed_ct="100100131",
        component="Diagnostic Analyte Component 01-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_132": ClinicalConcept_01(
        concept_id="CONCEPT_01_132",
        loinc_num="11132-6",
        snomed_ct="100100132",
        component="Diagnostic Analyte Component 01-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_133": ClinicalConcept_01(
        concept_id="CONCEPT_01_133",
        loinc_num="11133-7",
        snomed_ct="100100133",
        component="Diagnostic Analyte Component 01-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_134": ClinicalConcept_01(
        concept_id="CONCEPT_01_134",
        loinc_num="11134-8",
        snomed_ct="100100134",
        component="Diagnostic Analyte Component 01-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_135": ClinicalConcept_01(
        concept_id="CONCEPT_01_135",
        loinc_num="11135-0",
        snomed_ct="100100135",
        component="Diagnostic Analyte Component 01-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_136": ClinicalConcept_01(
        concept_id="CONCEPT_01_136",
        loinc_num="11136-1",
        snomed_ct="100100136",
        component="Diagnostic Analyte Component 01-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_137": ClinicalConcept_01(
        concept_id="CONCEPT_01_137",
        loinc_num="11137-2",
        snomed_ct="100100137",
        component="Diagnostic Analyte Component 01-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_138": ClinicalConcept_01(
        concept_id="CONCEPT_01_138",
        loinc_num="11138-3",
        snomed_ct="100100138",
        component="Diagnostic Analyte Component 01-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_139": ClinicalConcept_01(
        concept_id="CONCEPT_01_139",
        loinc_num="11139-4",
        snomed_ct="100100139",
        component="Diagnostic Analyte Component 01-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_140": ClinicalConcept_01(
        concept_id="CONCEPT_01_140",
        loinc_num="11140-5",
        snomed_ct="100100140",
        component="Diagnostic Analyte Component 01-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_141": ClinicalConcept_01(
        concept_id="CONCEPT_01_141",
        loinc_num="11141-6",
        snomed_ct="100100141",
        component="Diagnostic Analyte Component 01-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_142": ClinicalConcept_01(
        concept_id="CONCEPT_01_142",
        loinc_num="11142-7",
        snomed_ct="100100142",
        component="Diagnostic Analyte Component 01-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_143": ClinicalConcept_01(
        concept_id="CONCEPT_01_143",
        loinc_num="11143-8",
        snomed_ct="100100143",
        component="Diagnostic Analyte Component 01-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_144": ClinicalConcept_01(
        concept_id="CONCEPT_01_144",
        loinc_num="11144-0",
        snomed_ct="100100144",
        component="Diagnostic Analyte Component 01-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_145": ClinicalConcept_01(
        concept_id="CONCEPT_01_145",
        loinc_num="11145-1",
        snomed_ct="100100145",
        component="Diagnostic Analyte Component 01-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_146": ClinicalConcept_01(
        concept_id="CONCEPT_01_146",
        loinc_num="11146-2",
        snomed_ct="100100146",
        component="Diagnostic Analyte Component 01-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_147": ClinicalConcept_01(
        concept_id="CONCEPT_01_147",
        loinc_num="11147-3",
        snomed_ct="100100147",
        component="Diagnostic Analyte Component 01-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_148": ClinicalConcept_01(
        concept_id="CONCEPT_01_148",
        loinc_num="11148-4",
        snomed_ct="100100148",
        component="Diagnostic Analyte Component 01-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_149": ClinicalConcept_01(
        concept_id="CONCEPT_01_149",
        loinc_num="11149-5",
        snomed_ct="100100149",
        component="Diagnostic Analyte Component 01-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_150": ClinicalConcept_01(
        concept_id="CONCEPT_01_150",
        loinc_num="11150-6",
        snomed_ct="100100150",
        component="Diagnostic Analyte Component 01-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_151": ClinicalConcept_01(
        concept_id="CONCEPT_01_151",
        loinc_num="11151-7",
        snomed_ct="100100151",
        component="Diagnostic Analyte Component 01-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_152": ClinicalConcept_01(
        concept_id="CONCEPT_01_152",
        loinc_num="11152-8",
        snomed_ct="100100152",
        component="Diagnostic Analyte Component 01-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_153": ClinicalConcept_01(
        concept_id="CONCEPT_01_153",
        loinc_num="11153-0",
        snomed_ct="100100153",
        component="Diagnostic Analyte Component 01-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_154": ClinicalConcept_01(
        concept_id="CONCEPT_01_154",
        loinc_num="11154-1",
        snomed_ct="100100154",
        component="Diagnostic Analyte Component 01-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_155": ClinicalConcept_01(
        concept_id="CONCEPT_01_155",
        loinc_num="11155-2",
        snomed_ct="100100155",
        component="Diagnostic Analyte Component 01-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_156": ClinicalConcept_01(
        concept_id="CONCEPT_01_156",
        loinc_num="11156-3",
        snomed_ct="100100156",
        component="Diagnostic Analyte Component 01-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_157": ClinicalConcept_01(
        concept_id="CONCEPT_01_157",
        loinc_num="11157-4",
        snomed_ct="100100157",
        component="Diagnostic Analyte Component 01-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_158": ClinicalConcept_01(
        concept_id="CONCEPT_01_158",
        loinc_num="11158-5",
        snomed_ct="100100158",
        component="Diagnostic Analyte Component 01-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_159": ClinicalConcept_01(
        concept_id="CONCEPT_01_159",
        loinc_num="11159-6",
        snomed_ct="100100159",
        component="Diagnostic Analyte Component 01-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_160": ClinicalConcept_01(
        concept_id="CONCEPT_01_160",
        loinc_num="11160-7",
        snomed_ct="100100160",
        component="Diagnostic Analyte Component 01-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_161": ClinicalConcept_01(
        concept_id="CONCEPT_01_161",
        loinc_num="11161-8",
        snomed_ct="100100161",
        component="Diagnostic Analyte Component 01-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_162": ClinicalConcept_01(
        concept_id="CONCEPT_01_162",
        loinc_num="11162-0",
        snomed_ct="100100162",
        component="Diagnostic Analyte Component 01-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_163": ClinicalConcept_01(
        concept_id="CONCEPT_01_163",
        loinc_num="11163-1",
        snomed_ct="100100163",
        component="Diagnostic Analyte Component 01-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_164": ClinicalConcept_01(
        concept_id="CONCEPT_01_164",
        loinc_num="11164-2",
        snomed_ct="100100164",
        component="Diagnostic Analyte Component 01-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_165": ClinicalConcept_01(
        concept_id="CONCEPT_01_165",
        loinc_num="11165-3",
        snomed_ct="100100165",
        component="Diagnostic Analyte Component 01-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_166": ClinicalConcept_01(
        concept_id="CONCEPT_01_166",
        loinc_num="11166-4",
        snomed_ct="100100166",
        component="Diagnostic Analyte Component 01-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_167": ClinicalConcept_01(
        concept_id="CONCEPT_01_167",
        loinc_num="11167-5",
        snomed_ct="100100167",
        component="Diagnostic Analyte Component 01-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_168": ClinicalConcept_01(
        concept_id="CONCEPT_01_168",
        loinc_num="11168-6",
        snomed_ct="100100168",
        component="Diagnostic Analyte Component 01-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_169": ClinicalConcept_01(
        concept_id="CONCEPT_01_169",
        loinc_num="11169-7",
        snomed_ct="100100169",
        component="Diagnostic Analyte Component 01-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_170": ClinicalConcept_01(
        concept_id="CONCEPT_01_170",
        loinc_num="11170-8",
        snomed_ct="100100170",
        component="Diagnostic Analyte Component 01-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_171": ClinicalConcept_01(
        concept_id="CONCEPT_01_171",
        loinc_num="11171-0",
        snomed_ct="100100171",
        component="Diagnostic Analyte Component 01-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_172": ClinicalConcept_01(
        concept_id="CONCEPT_01_172",
        loinc_num="11172-1",
        snomed_ct="100100172",
        component="Diagnostic Analyte Component 01-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_173": ClinicalConcept_01(
        concept_id="CONCEPT_01_173",
        loinc_num="11173-2",
        snomed_ct="100100173",
        component="Diagnostic Analyte Component 01-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_174": ClinicalConcept_01(
        concept_id="CONCEPT_01_174",
        loinc_num="11174-3",
        snomed_ct="100100174",
        component="Diagnostic Analyte Component 01-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_175": ClinicalConcept_01(
        concept_id="CONCEPT_01_175",
        loinc_num="11175-4",
        snomed_ct="100100175",
        component="Diagnostic Analyte Component 01-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_176": ClinicalConcept_01(
        concept_id="CONCEPT_01_176",
        loinc_num="11176-5",
        snomed_ct="100100176",
        component="Diagnostic Analyte Component 01-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_177": ClinicalConcept_01(
        concept_id="CONCEPT_01_177",
        loinc_num="11177-6",
        snomed_ct="100100177",
        component="Diagnostic Analyte Component 01-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_178": ClinicalConcept_01(
        concept_id="CONCEPT_01_178",
        loinc_num="11178-7",
        snomed_ct="100100178",
        component="Diagnostic Analyte Component 01-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_179": ClinicalConcept_01(
        concept_id="CONCEPT_01_179",
        loinc_num="11179-8",
        snomed_ct="100100179",
        component="Diagnostic Analyte Component 01-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_180": ClinicalConcept_01(
        concept_id="CONCEPT_01_180",
        loinc_num="11180-0",
        snomed_ct="100100180",
        component="Diagnostic Analyte Component 01-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_181": ClinicalConcept_01(
        concept_id="CONCEPT_01_181",
        loinc_num="11181-1",
        snomed_ct="100100181",
        component="Diagnostic Analyte Component 01-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_182": ClinicalConcept_01(
        concept_id="CONCEPT_01_182",
        loinc_num="11182-2",
        snomed_ct="100100182",
        component="Diagnostic Analyte Component 01-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_183": ClinicalConcept_01(
        concept_id="CONCEPT_01_183",
        loinc_num="11183-3",
        snomed_ct="100100183",
        component="Diagnostic Analyte Component 01-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_184": ClinicalConcept_01(
        concept_id="CONCEPT_01_184",
        loinc_num="11184-4",
        snomed_ct="100100184",
        component="Diagnostic Analyte Component 01-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_185": ClinicalConcept_01(
        concept_id="CONCEPT_01_185",
        loinc_num="11185-5",
        snomed_ct="100100185",
        component="Diagnostic Analyte Component 01-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_186": ClinicalConcept_01(
        concept_id="CONCEPT_01_186",
        loinc_num="11186-6",
        snomed_ct="100100186",
        component="Diagnostic Analyte Component 01-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_187": ClinicalConcept_01(
        concept_id="CONCEPT_01_187",
        loinc_num="11187-7",
        snomed_ct="100100187",
        component="Diagnostic Analyte Component 01-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_188": ClinicalConcept_01(
        concept_id="CONCEPT_01_188",
        loinc_num="11188-8",
        snomed_ct="100100188",
        component="Diagnostic Analyte Component 01-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_189": ClinicalConcept_01(
        concept_id="CONCEPT_01_189",
        loinc_num="11189-0",
        snomed_ct="100100189",
        component="Diagnostic Analyte Component 01-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_190": ClinicalConcept_01(
        concept_id="CONCEPT_01_190",
        loinc_num="11190-1",
        snomed_ct="100100190",
        component="Diagnostic Analyte Component 01-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_191": ClinicalConcept_01(
        concept_id="CONCEPT_01_191",
        loinc_num="11191-2",
        snomed_ct="100100191",
        component="Diagnostic Analyte Component 01-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_192": ClinicalConcept_01(
        concept_id="CONCEPT_01_192",
        loinc_num="11192-3",
        snomed_ct="100100192",
        component="Diagnostic Analyte Component 01-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_193": ClinicalConcept_01(
        concept_id="CONCEPT_01_193",
        loinc_num="11193-4",
        snomed_ct="100100193",
        component="Diagnostic Analyte Component 01-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_194": ClinicalConcept_01(
        concept_id="CONCEPT_01_194",
        loinc_num="11194-5",
        snomed_ct="100100194",
        component="Diagnostic Analyte Component 01-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_195": ClinicalConcept_01(
        concept_id="CONCEPT_01_195",
        loinc_num="11195-6",
        snomed_ct="100100195",
        component="Diagnostic Analyte Component 01-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_196": ClinicalConcept_01(
        concept_id="CONCEPT_01_196",
        loinc_num="11196-7",
        snomed_ct="100100196",
        component="Diagnostic Analyte Component 01-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_197": ClinicalConcept_01(
        concept_id="CONCEPT_01_197",
        loinc_num="11197-8",
        snomed_ct="100100197",
        component="Diagnostic Analyte Component 01-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_198": ClinicalConcept_01(
        concept_id="CONCEPT_01_198",
        loinc_num="11198-0",
        snomed_ct="100100198",
        component="Diagnostic Analyte Component 01-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_01_199": ClinicalConcept_01(
        concept_id="CONCEPT_01_199",
        loinc_num="11199-1",
        snomed_ct="100100199",
        component="Diagnostic Analyte Component 01-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
