"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 23"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_23:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_23 = {
    "CONCEPT_23_001": ClinicalConcept_23(
        concept_id="CONCEPT_23_001",
        loinc_num="33001-1",
        snomed_ct="102300001",
        component="Diagnostic Analyte Component 23-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_002": ClinicalConcept_23(
        concept_id="CONCEPT_23_002",
        loinc_num="33002-2",
        snomed_ct="102300002",
        component="Diagnostic Analyte Component 23-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_003": ClinicalConcept_23(
        concept_id="CONCEPT_23_003",
        loinc_num="33003-3",
        snomed_ct="102300003",
        component="Diagnostic Analyte Component 23-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_004": ClinicalConcept_23(
        concept_id="CONCEPT_23_004",
        loinc_num="33004-4",
        snomed_ct="102300004",
        component="Diagnostic Analyte Component 23-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_005": ClinicalConcept_23(
        concept_id="CONCEPT_23_005",
        loinc_num="33005-5",
        snomed_ct="102300005",
        component="Diagnostic Analyte Component 23-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_006": ClinicalConcept_23(
        concept_id="CONCEPT_23_006",
        loinc_num="33006-6",
        snomed_ct="102300006",
        component="Diagnostic Analyte Component 23-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_007": ClinicalConcept_23(
        concept_id="CONCEPT_23_007",
        loinc_num="33007-7",
        snomed_ct="102300007",
        component="Diagnostic Analyte Component 23-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_008": ClinicalConcept_23(
        concept_id="CONCEPT_23_008",
        loinc_num="33008-8",
        snomed_ct="102300008",
        component="Diagnostic Analyte Component 23-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_009": ClinicalConcept_23(
        concept_id="CONCEPT_23_009",
        loinc_num="33009-0",
        snomed_ct="102300009",
        component="Diagnostic Analyte Component 23-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_010": ClinicalConcept_23(
        concept_id="CONCEPT_23_010",
        loinc_num="33010-1",
        snomed_ct="102300010",
        component="Diagnostic Analyte Component 23-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_011": ClinicalConcept_23(
        concept_id="CONCEPT_23_011",
        loinc_num="33011-2",
        snomed_ct="102300011",
        component="Diagnostic Analyte Component 23-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_012": ClinicalConcept_23(
        concept_id="CONCEPT_23_012",
        loinc_num="33012-3",
        snomed_ct="102300012",
        component="Diagnostic Analyte Component 23-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_013": ClinicalConcept_23(
        concept_id="CONCEPT_23_013",
        loinc_num="33013-4",
        snomed_ct="102300013",
        component="Diagnostic Analyte Component 23-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_014": ClinicalConcept_23(
        concept_id="CONCEPT_23_014",
        loinc_num="33014-5",
        snomed_ct="102300014",
        component="Diagnostic Analyte Component 23-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_015": ClinicalConcept_23(
        concept_id="CONCEPT_23_015",
        loinc_num="33015-6",
        snomed_ct="102300015",
        component="Diagnostic Analyte Component 23-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_016": ClinicalConcept_23(
        concept_id="CONCEPT_23_016",
        loinc_num="33016-7",
        snomed_ct="102300016",
        component="Diagnostic Analyte Component 23-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_017": ClinicalConcept_23(
        concept_id="CONCEPT_23_017",
        loinc_num="33017-8",
        snomed_ct="102300017",
        component="Diagnostic Analyte Component 23-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_018": ClinicalConcept_23(
        concept_id="CONCEPT_23_018",
        loinc_num="33018-0",
        snomed_ct="102300018",
        component="Diagnostic Analyte Component 23-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_019": ClinicalConcept_23(
        concept_id="CONCEPT_23_019",
        loinc_num="33019-1",
        snomed_ct="102300019",
        component="Diagnostic Analyte Component 23-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_020": ClinicalConcept_23(
        concept_id="CONCEPT_23_020",
        loinc_num="33020-2",
        snomed_ct="102300020",
        component="Diagnostic Analyte Component 23-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_021": ClinicalConcept_23(
        concept_id="CONCEPT_23_021",
        loinc_num="33021-3",
        snomed_ct="102300021",
        component="Diagnostic Analyte Component 23-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_022": ClinicalConcept_23(
        concept_id="CONCEPT_23_022",
        loinc_num="33022-4",
        snomed_ct="102300022",
        component="Diagnostic Analyte Component 23-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_023": ClinicalConcept_23(
        concept_id="CONCEPT_23_023",
        loinc_num="33023-5",
        snomed_ct="102300023",
        component="Diagnostic Analyte Component 23-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_024": ClinicalConcept_23(
        concept_id="CONCEPT_23_024",
        loinc_num="33024-6",
        snomed_ct="102300024",
        component="Diagnostic Analyte Component 23-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_025": ClinicalConcept_23(
        concept_id="CONCEPT_23_025",
        loinc_num="33025-7",
        snomed_ct="102300025",
        component="Diagnostic Analyte Component 23-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_026": ClinicalConcept_23(
        concept_id="CONCEPT_23_026",
        loinc_num="33026-8",
        snomed_ct="102300026",
        component="Diagnostic Analyte Component 23-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_027": ClinicalConcept_23(
        concept_id="CONCEPT_23_027",
        loinc_num="33027-0",
        snomed_ct="102300027",
        component="Diagnostic Analyte Component 23-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_028": ClinicalConcept_23(
        concept_id="CONCEPT_23_028",
        loinc_num="33028-1",
        snomed_ct="102300028",
        component="Diagnostic Analyte Component 23-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_029": ClinicalConcept_23(
        concept_id="CONCEPT_23_029",
        loinc_num="33029-2",
        snomed_ct="102300029",
        component="Diagnostic Analyte Component 23-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_030": ClinicalConcept_23(
        concept_id="CONCEPT_23_030",
        loinc_num="33030-3",
        snomed_ct="102300030",
        component="Diagnostic Analyte Component 23-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_031": ClinicalConcept_23(
        concept_id="CONCEPT_23_031",
        loinc_num="33031-4",
        snomed_ct="102300031",
        component="Diagnostic Analyte Component 23-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_032": ClinicalConcept_23(
        concept_id="CONCEPT_23_032",
        loinc_num="33032-5",
        snomed_ct="102300032",
        component="Diagnostic Analyte Component 23-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_033": ClinicalConcept_23(
        concept_id="CONCEPT_23_033",
        loinc_num="33033-6",
        snomed_ct="102300033",
        component="Diagnostic Analyte Component 23-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_034": ClinicalConcept_23(
        concept_id="CONCEPT_23_034",
        loinc_num="33034-7",
        snomed_ct="102300034",
        component="Diagnostic Analyte Component 23-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_035": ClinicalConcept_23(
        concept_id="CONCEPT_23_035",
        loinc_num="33035-8",
        snomed_ct="102300035",
        component="Diagnostic Analyte Component 23-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_036": ClinicalConcept_23(
        concept_id="CONCEPT_23_036",
        loinc_num="33036-0",
        snomed_ct="102300036",
        component="Diagnostic Analyte Component 23-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_037": ClinicalConcept_23(
        concept_id="CONCEPT_23_037",
        loinc_num="33037-1",
        snomed_ct="102300037",
        component="Diagnostic Analyte Component 23-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_038": ClinicalConcept_23(
        concept_id="CONCEPT_23_038",
        loinc_num="33038-2",
        snomed_ct="102300038",
        component="Diagnostic Analyte Component 23-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_039": ClinicalConcept_23(
        concept_id="CONCEPT_23_039",
        loinc_num="33039-3",
        snomed_ct="102300039",
        component="Diagnostic Analyte Component 23-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_040": ClinicalConcept_23(
        concept_id="CONCEPT_23_040",
        loinc_num="33040-4",
        snomed_ct="102300040",
        component="Diagnostic Analyte Component 23-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_041": ClinicalConcept_23(
        concept_id="CONCEPT_23_041",
        loinc_num="33041-5",
        snomed_ct="102300041",
        component="Diagnostic Analyte Component 23-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_042": ClinicalConcept_23(
        concept_id="CONCEPT_23_042",
        loinc_num="33042-6",
        snomed_ct="102300042",
        component="Diagnostic Analyte Component 23-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_043": ClinicalConcept_23(
        concept_id="CONCEPT_23_043",
        loinc_num="33043-7",
        snomed_ct="102300043",
        component="Diagnostic Analyte Component 23-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_044": ClinicalConcept_23(
        concept_id="CONCEPT_23_044",
        loinc_num="33044-8",
        snomed_ct="102300044",
        component="Diagnostic Analyte Component 23-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_045": ClinicalConcept_23(
        concept_id="CONCEPT_23_045",
        loinc_num="33045-0",
        snomed_ct="102300045",
        component="Diagnostic Analyte Component 23-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_046": ClinicalConcept_23(
        concept_id="CONCEPT_23_046",
        loinc_num="33046-1",
        snomed_ct="102300046",
        component="Diagnostic Analyte Component 23-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_047": ClinicalConcept_23(
        concept_id="CONCEPT_23_047",
        loinc_num="33047-2",
        snomed_ct="102300047",
        component="Diagnostic Analyte Component 23-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_048": ClinicalConcept_23(
        concept_id="CONCEPT_23_048",
        loinc_num="33048-3",
        snomed_ct="102300048",
        component="Diagnostic Analyte Component 23-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_049": ClinicalConcept_23(
        concept_id="CONCEPT_23_049",
        loinc_num="33049-4",
        snomed_ct="102300049",
        component="Diagnostic Analyte Component 23-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_050": ClinicalConcept_23(
        concept_id="CONCEPT_23_050",
        loinc_num="33050-5",
        snomed_ct="102300050",
        component="Diagnostic Analyte Component 23-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_051": ClinicalConcept_23(
        concept_id="CONCEPT_23_051",
        loinc_num="33051-6",
        snomed_ct="102300051",
        component="Diagnostic Analyte Component 23-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_052": ClinicalConcept_23(
        concept_id="CONCEPT_23_052",
        loinc_num="33052-7",
        snomed_ct="102300052",
        component="Diagnostic Analyte Component 23-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_053": ClinicalConcept_23(
        concept_id="CONCEPT_23_053",
        loinc_num="33053-8",
        snomed_ct="102300053",
        component="Diagnostic Analyte Component 23-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_054": ClinicalConcept_23(
        concept_id="CONCEPT_23_054",
        loinc_num="33054-0",
        snomed_ct="102300054",
        component="Diagnostic Analyte Component 23-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_055": ClinicalConcept_23(
        concept_id="CONCEPT_23_055",
        loinc_num="33055-1",
        snomed_ct="102300055",
        component="Diagnostic Analyte Component 23-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_056": ClinicalConcept_23(
        concept_id="CONCEPT_23_056",
        loinc_num="33056-2",
        snomed_ct="102300056",
        component="Diagnostic Analyte Component 23-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_057": ClinicalConcept_23(
        concept_id="CONCEPT_23_057",
        loinc_num="33057-3",
        snomed_ct="102300057",
        component="Diagnostic Analyte Component 23-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_058": ClinicalConcept_23(
        concept_id="CONCEPT_23_058",
        loinc_num="33058-4",
        snomed_ct="102300058",
        component="Diagnostic Analyte Component 23-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_059": ClinicalConcept_23(
        concept_id="CONCEPT_23_059",
        loinc_num="33059-5",
        snomed_ct="102300059",
        component="Diagnostic Analyte Component 23-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_060": ClinicalConcept_23(
        concept_id="CONCEPT_23_060",
        loinc_num="33060-6",
        snomed_ct="102300060",
        component="Diagnostic Analyte Component 23-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_061": ClinicalConcept_23(
        concept_id="CONCEPT_23_061",
        loinc_num="33061-7",
        snomed_ct="102300061",
        component="Diagnostic Analyte Component 23-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_062": ClinicalConcept_23(
        concept_id="CONCEPT_23_062",
        loinc_num="33062-8",
        snomed_ct="102300062",
        component="Diagnostic Analyte Component 23-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_063": ClinicalConcept_23(
        concept_id="CONCEPT_23_063",
        loinc_num="33063-0",
        snomed_ct="102300063",
        component="Diagnostic Analyte Component 23-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_064": ClinicalConcept_23(
        concept_id="CONCEPT_23_064",
        loinc_num="33064-1",
        snomed_ct="102300064",
        component="Diagnostic Analyte Component 23-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_065": ClinicalConcept_23(
        concept_id="CONCEPT_23_065",
        loinc_num="33065-2",
        snomed_ct="102300065",
        component="Diagnostic Analyte Component 23-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_066": ClinicalConcept_23(
        concept_id="CONCEPT_23_066",
        loinc_num="33066-3",
        snomed_ct="102300066",
        component="Diagnostic Analyte Component 23-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_067": ClinicalConcept_23(
        concept_id="CONCEPT_23_067",
        loinc_num="33067-4",
        snomed_ct="102300067",
        component="Diagnostic Analyte Component 23-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_068": ClinicalConcept_23(
        concept_id="CONCEPT_23_068",
        loinc_num="33068-5",
        snomed_ct="102300068",
        component="Diagnostic Analyte Component 23-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_069": ClinicalConcept_23(
        concept_id="CONCEPT_23_069",
        loinc_num="33069-6",
        snomed_ct="102300069",
        component="Diagnostic Analyte Component 23-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_070": ClinicalConcept_23(
        concept_id="CONCEPT_23_070",
        loinc_num="33070-7",
        snomed_ct="102300070",
        component="Diagnostic Analyte Component 23-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_071": ClinicalConcept_23(
        concept_id="CONCEPT_23_071",
        loinc_num="33071-8",
        snomed_ct="102300071",
        component="Diagnostic Analyte Component 23-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_072": ClinicalConcept_23(
        concept_id="CONCEPT_23_072",
        loinc_num="33072-0",
        snomed_ct="102300072",
        component="Diagnostic Analyte Component 23-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_073": ClinicalConcept_23(
        concept_id="CONCEPT_23_073",
        loinc_num="33073-1",
        snomed_ct="102300073",
        component="Diagnostic Analyte Component 23-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_074": ClinicalConcept_23(
        concept_id="CONCEPT_23_074",
        loinc_num="33074-2",
        snomed_ct="102300074",
        component="Diagnostic Analyte Component 23-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_075": ClinicalConcept_23(
        concept_id="CONCEPT_23_075",
        loinc_num="33075-3",
        snomed_ct="102300075",
        component="Diagnostic Analyte Component 23-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_076": ClinicalConcept_23(
        concept_id="CONCEPT_23_076",
        loinc_num="33076-4",
        snomed_ct="102300076",
        component="Diagnostic Analyte Component 23-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_077": ClinicalConcept_23(
        concept_id="CONCEPT_23_077",
        loinc_num="33077-5",
        snomed_ct="102300077",
        component="Diagnostic Analyte Component 23-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_078": ClinicalConcept_23(
        concept_id="CONCEPT_23_078",
        loinc_num="33078-6",
        snomed_ct="102300078",
        component="Diagnostic Analyte Component 23-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_079": ClinicalConcept_23(
        concept_id="CONCEPT_23_079",
        loinc_num="33079-7",
        snomed_ct="102300079",
        component="Diagnostic Analyte Component 23-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_080": ClinicalConcept_23(
        concept_id="CONCEPT_23_080",
        loinc_num="33080-8",
        snomed_ct="102300080",
        component="Diagnostic Analyte Component 23-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_081": ClinicalConcept_23(
        concept_id="CONCEPT_23_081",
        loinc_num="33081-0",
        snomed_ct="102300081",
        component="Diagnostic Analyte Component 23-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_082": ClinicalConcept_23(
        concept_id="CONCEPT_23_082",
        loinc_num="33082-1",
        snomed_ct="102300082",
        component="Diagnostic Analyte Component 23-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_083": ClinicalConcept_23(
        concept_id="CONCEPT_23_083",
        loinc_num="33083-2",
        snomed_ct="102300083",
        component="Diagnostic Analyte Component 23-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_084": ClinicalConcept_23(
        concept_id="CONCEPT_23_084",
        loinc_num="33084-3",
        snomed_ct="102300084",
        component="Diagnostic Analyte Component 23-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_085": ClinicalConcept_23(
        concept_id="CONCEPT_23_085",
        loinc_num="33085-4",
        snomed_ct="102300085",
        component="Diagnostic Analyte Component 23-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_086": ClinicalConcept_23(
        concept_id="CONCEPT_23_086",
        loinc_num="33086-5",
        snomed_ct="102300086",
        component="Diagnostic Analyte Component 23-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_087": ClinicalConcept_23(
        concept_id="CONCEPT_23_087",
        loinc_num="33087-6",
        snomed_ct="102300087",
        component="Diagnostic Analyte Component 23-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_088": ClinicalConcept_23(
        concept_id="CONCEPT_23_088",
        loinc_num="33088-7",
        snomed_ct="102300088",
        component="Diagnostic Analyte Component 23-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_089": ClinicalConcept_23(
        concept_id="CONCEPT_23_089",
        loinc_num="33089-8",
        snomed_ct="102300089",
        component="Diagnostic Analyte Component 23-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_090": ClinicalConcept_23(
        concept_id="CONCEPT_23_090",
        loinc_num="33090-0",
        snomed_ct="102300090",
        component="Diagnostic Analyte Component 23-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_091": ClinicalConcept_23(
        concept_id="CONCEPT_23_091",
        loinc_num="33091-1",
        snomed_ct="102300091",
        component="Diagnostic Analyte Component 23-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_092": ClinicalConcept_23(
        concept_id="CONCEPT_23_092",
        loinc_num="33092-2",
        snomed_ct="102300092",
        component="Diagnostic Analyte Component 23-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_093": ClinicalConcept_23(
        concept_id="CONCEPT_23_093",
        loinc_num="33093-3",
        snomed_ct="102300093",
        component="Diagnostic Analyte Component 23-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_094": ClinicalConcept_23(
        concept_id="CONCEPT_23_094",
        loinc_num="33094-4",
        snomed_ct="102300094",
        component="Diagnostic Analyte Component 23-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_095": ClinicalConcept_23(
        concept_id="CONCEPT_23_095",
        loinc_num="33095-5",
        snomed_ct="102300095",
        component="Diagnostic Analyte Component 23-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_096": ClinicalConcept_23(
        concept_id="CONCEPT_23_096",
        loinc_num="33096-6",
        snomed_ct="102300096",
        component="Diagnostic Analyte Component 23-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_097": ClinicalConcept_23(
        concept_id="CONCEPT_23_097",
        loinc_num="33097-7",
        snomed_ct="102300097",
        component="Diagnostic Analyte Component 23-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_098": ClinicalConcept_23(
        concept_id="CONCEPT_23_098",
        loinc_num="33098-8",
        snomed_ct="102300098",
        component="Diagnostic Analyte Component 23-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_099": ClinicalConcept_23(
        concept_id="CONCEPT_23_099",
        loinc_num="33099-0",
        snomed_ct="102300099",
        component="Diagnostic Analyte Component 23-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_100": ClinicalConcept_23(
        concept_id="CONCEPT_23_100",
        loinc_num="33100-1",
        snomed_ct="102300100",
        component="Diagnostic Analyte Component 23-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_101": ClinicalConcept_23(
        concept_id="CONCEPT_23_101",
        loinc_num="33101-2",
        snomed_ct="102300101",
        component="Diagnostic Analyte Component 23-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_102": ClinicalConcept_23(
        concept_id="CONCEPT_23_102",
        loinc_num="33102-3",
        snomed_ct="102300102",
        component="Diagnostic Analyte Component 23-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_103": ClinicalConcept_23(
        concept_id="CONCEPT_23_103",
        loinc_num="33103-4",
        snomed_ct="102300103",
        component="Diagnostic Analyte Component 23-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_104": ClinicalConcept_23(
        concept_id="CONCEPT_23_104",
        loinc_num="33104-5",
        snomed_ct="102300104",
        component="Diagnostic Analyte Component 23-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_105": ClinicalConcept_23(
        concept_id="CONCEPT_23_105",
        loinc_num="33105-6",
        snomed_ct="102300105",
        component="Diagnostic Analyte Component 23-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_106": ClinicalConcept_23(
        concept_id="CONCEPT_23_106",
        loinc_num="33106-7",
        snomed_ct="102300106",
        component="Diagnostic Analyte Component 23-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_107": ClinicalConcept_23(
        concept_id="CONCEPT_23_107",
        loinc_num="33107-8",
        snomed_ct="102300107",
        component="Diagnostic Analyte Component 23-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_108": ClinicalConcept_23(
        concept_id="CONCEPT_23_108",
        loinc_num="33108-0",
        snomed_ct="102300108",
        component="Diagnostic Analyte Component 23-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_109": ClinicalConcept_23(
        concept_id="CONCEPT_23_109",
        loinc_num="33109-1",
        snomed_ct="102300109",
        component="Diagnostic Analyte Component 23-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_110": ClinicalConcept_23(
        concept_id="CONCEPT_23_110",
        loinc_num="33110-2",
        snomed_ct="102300110",
        component="Diagnostic Analyte Component 23-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_111": ClinicalConcept_23(
        concept_id="CONCEPT_23_111",
        loinc_num="33111-3",
        snomed_ct="102300111",
        component="Diagnostic Analyte Component 23-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_112": ClinicalConcept_23(
        concept_id="CONCEPT_23_112",
        loinc_num="33112-4",
        snomed_ct="102300112",
        component="Diagnostic Analyte Component 23-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_113": ClinicalConcept_23(
        concept_id="CONCEPT_23_113",
        loinc_num="33113-5",
        snomed_ct="102300113",
        component="Diagnostic Analyte Component 23-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_114": ClinicalConcept_23(
        concept_id="CONCEPT_23_114",
        loinc_num="33114-6",
        snomed_ct="102300114",
        component="Diagnostic Analyte Component 23-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_115": ClinicalConcept_23(
        concept_id="CONCEPT_23_115",
        loinc_num="33115-7",
        snomed_ct="102300115",
        component="Diagnostic Analyte Component 23-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_116": ClinicalConcept_23(
        concept_id="CONCEPT_23_116",
        loinc_num="33116-8",
        snomed_ct="102300116",
        component="Diagnostic Analyte Component 23-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_117": ClinicalConcept_23(
        concept_id="CONCEPT_23_117",
        loinc_num="33117-0",
        snomed_ct="102300117",
        component="Diagnostic Analyte Component 23-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_118": ClinicalConcept_23(
        concept_id="CONCEPT_23_118",
        loinc_num="33118-1",
        snomed_ct="102300118",
        component="Diagnostic Analyte Component 23-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_119": ClinicalConcept_23(
        concept_id="CONCEPT_23_119",
        loinc_num="33119-2",
        snomed_ct="102300119",
        component="Diagnostic Analyte Component 23-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_120": ClinicalConcept_23(
        concept_id="CONCEPT_23_120",
        loinc_num="33120-3",
        snomed_ct="102300120",
        component="Diagnostic Analyte Component 23-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_121": ClinicalConcept_23(
        concept_id="CONCEPT_23_121",
        loinc_num="33121-4",
        snomed_ct="102300121",
        component="Diagnostic Analyte Component 23-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_122": ClinicalConcept_23(
        concept_id="CONCEPT_23_122",
        loinc_num="33122-5",
        snomed_ct="102300122",
        component="Diagnostic Analyte Component 23-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_123": ClinicalConcept_23(
        concept_id="CONCEPT_23_123",
        loinc_num="33123-6",
        snomed_ct="102300123",
        component="Diagnostic Analyte Component 23-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_124": ClinicalConcept_23(
        concept_id="CONCEPT_23_124",
        loinc_num="33124-7",
        snomed_ct="102300124",
        component="Diagnostic Analyte Component 23-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_125": ClinicalConcept_23(
        concept_id="CONCEPT_23_125",
        loinc_num="33125-8",
        snomed_ct="102300125",
        component="Diagnostic Analyte Component 23-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_126": ClinicalConcept_23(
        concept_id="CONCEPT_23_126",
        loinc_num="33126-0",
        snomed_ct="102300126",
        component="Diagnostic Analyte Component 23-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_127": ClinicalConcept_23(
        concept_id="CONCEPT_23_127",
        loinc_num="33127-1",
        snomed_ct="102300127",
        component="Diagnostic Analyte Component 23-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_128": ClinicalConcept_23(
        concept_id="CONCEPT_23_128",
        loinc_num="33128-2",
        snomed_ct="102300128",
        component="Diagnostic Analyte Component 23-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_129": ClinicalConcept_23(
        concept_id="CONCEPT_23_129",
        loinc_num="33129-3",
        snomed_ct="102300129",
        component="Diagnostic Analyte Component 23-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_130": ClinicalConcept_23(
        concept_id="CONCEPT_23_130",
        loinc_num="33130-4",
        snomed_ct="102300130",
        component="Diagnostic Analyte Component 23-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_131": ClinicalConcept_23(
        concept_id="CONCEPT_23_131",
        loinc_num="33131-5",
        snomed_ct="102300131",
        component="Diagnostic Analyte Component 23-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_132": ClinicalConcept_23(
        concept_id="CONCEPT_23_132",
        loinc_num="33132-6",
        snomed_ct="102300132",
        component="Diagnostic Analyte Component 23-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_133": ClinicalConcept_23(
        concept_id="CONCEPT_23_133",
        loinc_num="33133-7",
        snomed_ct="102300133",
        component="Diagnostic Analyte Component 23-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_134": ClinicalConcept_23(
        concept_id="CONCEPT_23_134",
        loinc_num="33134-8",
        snomed_ct="102300134",
        component="Diagnostic Analyte Component 23-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_135": ClinicalConcept_23(
        concept_id="CONCEPT_23_135",
        loinc_num="33135-0",
        snomed_ct="102300135",
        component="Diagnostic Analyte Component 23-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_136": ClinicalConcept_23(
        concept_id="CONCEPT_23_136",
        loinc_num="33136-1",
        snomed_ct="102300136",
        component="Diagnostic Analyte Component 23-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_137": ClinicalConcept_23(
        concept_id="CONCEPT_23_137",
        loinc_num="33137-2",
        snomed_ct="102300137",
        component="Diagnostic Analyte Component 23-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_138": ClinicalConcept_23(
        concept_id="CONCEPT_23_138",
        loinc_num="33138-3",
        snomed_ct="102300138",
        component="Diagnostic Analyte Component 23-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_139": ClinicalConcept_23(
        concept_id="CONCEPT_23_139",
        loinc_num="33139-4",
        snomed_ct="102300139",
        component="Diagnostic Analyte Component 23-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_140": ClinicalConcept_23(
        concept_id="CONCEPT_23_140",
        loinc_num="33140-5",
        snomed_ct="102300140",
        component="Diagnostic Analyte Component 23-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_141": ClinicalConcept_23(
        concept_id="CONCEPT_23_141",
        loinc_num="33141-6",
        snomed_ct="102300141",
        component="Diagnostic Analyte Component 23-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_142": ClinicalConcept_23(
        concept_id="CONCEPT_23_142",
        loinc_num="33142-7",
        snomed_ct="102300142",
        component="Diagnostic Analyte Component 23-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_143": ClinicalConcept_23(
        concept_id="CONCEPT_23_143",
        loinc_num="33143-8",
        snomed_ct="102300143",
        component="Diagnostic Analyte Component 23-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_144": ClinicalConcept_23(
        concept_id="CONCEPT_23_144",
        loinc_num="33144-0",
        snomed_ct="102300144",
        component="Diagnostic Analyte Component 23-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_145": ClinicalConcept_23(
        concept_id="CONCEPT_23_145",
        loinc_num="33145-1",
        snomed_ct="102300145",
        component="Diagnostic Analyte Component 23-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_146": ClinicalConcept_23(
        concept_id="CONCEPT_23_146",
        loinc_num="33146-2",
        snomed_ct="102300146",
        component="Diagnostic Analyte Component 23-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_147": ClinicalConcept_23(
        concept_id="CONCEPT_23_147",
        loinc_num="33147-3",
        snomed_ct="102300147",
        component="Diagnostic Analyte Component 23-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_148": ClinicalConcept_23(
        concept_id="CONCEPT_23_148",
        loinc_num="33148-4",
        snomed_ct="102300148",
        component="Diagnostic Analyte Component 23-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_149": ClinicalConcept_23(
        concept_id="CONCEPT_23_149",
        loinc_num="33149-5",
        snomed_ct="102300149",
        component="Diagnostic Analyte Component 23-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_150": ClinicalConcept_23(
        concept_id="CONCEPT_23_150",
        loinc_num="33150-6",
        snomed_ct="102300150",
        component="Diagnostic Analyte Component 23-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_151": ClinicalConcept_23(
        concept_id="CONCEPT_23_151",
        loinc_num="33151-7",
        snomed_ct="102300151",
        component="Diagnostic Analyte Component 23-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_152": ClinicalConcept_23(
        concept_id="CONCEPT_23_152",
        loinc_num="33152-8",
        snomed_ct="102300152",
        component="Diagnostic Analyte Component 23-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_153": ClinicalConcept_23(
        concept_id="CONCEPT_23_153",
        loinc_num="33153-0",
        snomed_ct="102300153",
        component="Diagnostic Analyte Component 23-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_154": ClinicalConcept_23(
        concept_id="CONCEPT_23_154",
        loinc_num="33154-1",
        snomed_ct="102300154",
        component="Diagnostic Analyte Component 23-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_155": ClinicalConcept_23(
        concept_id="CONCEPT_23_155",
        loinc_num="33155-2",
        snomed_ct="102300155",
        component="Diagnostic Analyte Component 23-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_156": ClinicalConcept_23(
        concept_id="CONCEPT_23_156",
        loinc_num="33156-3",
        snomed_ct="102300156",
        component="Diagnostic Analyte Component 23-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_157": ClinicalConcept_23(
        concept_id="CONCEPT_23_157",
        loinc_num="33157-4",
        snomed_ct="102300157",
        component="Diagnostic Analyte Component 23-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_158": ClinicalConcept_23(
        concept_id="CONCEPT_23_158",
        loinc_num="33158-5",
        snomed_ct="102300158",
        component="Diagnostic Analyte Component 23-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_159": ClinicalConcept_23(
        concept_id="CONCEPT_23_159",
        loinc_num="33159-6",
        snomed_ct="102300159",
        component="Diagnostic Analyte Component 23-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_160": ClinicalConcept_23(
        concept_id="CONCEPT_23_160",
        loinc_num="33160-7",
        snomed_ct="102300160",
        component="Diagnostic Analyte Component 23-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_161": ClinicalConcept_23(
        concept_id="CONCEPT_23_161",
        loinc_num="33161-8",
        snomed_ct="102300161",
        component="Diagnostic Analyte Component 23-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_162": ClinicalConcept_23(
        concept_id="CONCEPT_23_162",
        loinc_num="33162-0",
        snomed_ct="102300162",
        component="Diagnostic Analyte Component 23-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_163": ClinicalConcept_23(
        concept_id="CONCEPT_23_163",
        loinc_num="33163-1",
        snomed_ct="102300163",
        component="Diagnostic Analyte Component 23-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_164": ClinicalConcept_23(
        concept_id="CONCEPT_23_164",
        loinc_num="33164-2",
        snomed_ct="102300164",
        component="Diagnostic Analyte Component 23-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_165": ClinicalConcept_23(
        concept_id="CONCEPT_23_165",
        loinc_num="33165-3",
        snomed_ct="102300165",
        component="Diagnostic Analyte Component 23-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_166": ClinicalConcept_23(
        concept_id="CONCEPT_23_166",
        loinc_num="33166-4",
        snomed_ct="102300166",
        component="Diagnostic Analyte Component 23-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_167": ClinicalConcept_23(
        concept_id="CONCEPT_23_167",
        loinc_num="33167-5",
        snomed_ct="102300167",
        component="Diagnostic Analyte Component 23-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_168": ClinicalConcept_23(
        concept_id="CONCEPT_23_168",
        loinc_num="33168-6",
        snomed_ct="102300168",
        component="Diagnostic Analyte Component 23-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_169": ClinicalConcept_23(
        concept_id="CONCEPT_23_169",
        loinc_num="33169-7",
        snomed_ct="102300169",
        component="Diagnostic Analyte Component 23-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_170": ClinicalConcept_23(
        concept_id="CONCEPT_23_170",
        loinc_num="33170-8",
        snomed_ct="102300170",
        component="Diagnostic Analyte Component 23-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_171": ClinicalConcept_23(
        concept_id="CONCEPT_23_171",
        loinc_num="33171-0",
        snomed_ct="102300171",
        component="Diagnostic Analyte Component 23-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_172": ClinicalConcept_23(
        concept_id="CONCEPT_23_172",
        loinc_num="33172-1",
        snomed_ct="102300172",
        component="Diagnostic Analyte Component 23-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_173": ClinicalConcept_23(
        concept_id="CONCEPT_23_173",
        loinc_num="33173-2",
        snomed_ct="102300173",
        component="Diagnostic Analyte Component 23-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_174": ClinicalConcept_23(
        concept_id="CONCEPT_23_174",
        loinc_num="33174-3",
        snomed_ct="102300174",
        component="Diagnostic Analyte Component 23-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_175": ClinicalConcept_23(
        concept_id="CONCEPT_23_175",
        loinc_num="33175-4",
        snomed_ct="102300175",
        component="Diagnostic Analyte Component 23-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_176": ClinicalConcept_23(
        concept_id="CONCEPT_23_176",
        loinc_num="33176-5",
        snomed_ct="102300176",
        component="Diagnostic Analyte Component 23-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_177": ClinicalConcept_23(
        concept_id="CONCEPT_23_177",
        loinc_num="33177-6",
        snomed_ct="102300177",
        component="Diagnostic Analyte Component 23-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_178": ClinicalConcept_23(
        concept_id="CONCEPT_23_178",
        loinc_num="33178-7",
        snomed_ct="102300178",
        component="Diagnostic Analyte Component 23-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_179": ClinicalConcept_23(
        concept_id="CONCEPT_23_179",
        loinc_num="33179-8",
        snomed_ct="102300179",
        component="Diagnostic Analyte Component 23-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_180": ClinicalConcept_23(
        concept_id="CONCEPT_23_180",
        loinc_num="33180-0",
        snomed_ct="102300180",
        component="Diagnostic Analyte Component 23-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_181": ClinicalConcept_23(
        concept_id="CONCEPT_23_181",
        loinc_num="33181-1",
        snomed_ct="102300181",
        component="Diagnostic Analyte Component 23-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_182": ClinicalConcept_23(
        concept_id="CONCEPT_23_182",
        loinc_num="33182-2",
        snomed_ct="102300182",
        component="Diagnostic Analyte Component 23-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_183": ClinicalConcept_23(
        concept_id="CONCEPT_23_183",
        loinc_num="33183-3",
        snomed_ct="102300183",
        component="Diagnostic Analyte Component 23-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_184": ClinicalConcept_23(
        concept_id="CONCEPT_23_184",
        loinc_num="33184-4",
        snomed_ct="102300184",
        component="Diagnostic Analyte Component 23-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_185": ClinicalConcept_23(
        concept_id="CONCEPT_23_185",
        loinc_num="33185-5",
        snomed_ct="102300185",
        component="Diagnostic Analyte Component 23-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_186": ClinicalConcept_23(
        concept_id="CONCEPT_23_186",
        loinc_num="33186-6",
        snomed_ct="102300186",
        component="Diagnostic Analyte Component 23-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_187": ClinicalConcept_23(
        concept_id="CONCEPT_23_187",
        loinc_num="33187-7",
        snomed_ct="102300187",
        component="Diagnostic Analyte Component 23-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_188": ClinicalConcept_23(
        concept_id="CONCEPT_23_188",
        loinc_num="33188-8",
        snomed_ct="102300188",
        component="Diagnostic Analyte Component 23-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_189": ClinicalConcept_23(
        concept_id="CONCEPT_23_189",
        loinc_num="33189-0",
        snomed_ct="102300189",
        component="Diagnostic Analyte Component 23-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_190": ClinicalConcept_23(
        concept_id="CONCEPT_23_190",
        loinc_num="33190-1",
        snomed_ct="102300190",
        component="Diagnostic Analyte Component 23-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_191": ClinicalConcept_23(
        concept_id="CONCEPT_23_191",
        loinc_num="33191-2",
        snomed_ct="102300191",
        component="Diagnostic Analyte Component 23-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_192": ClinicalConcept_23(
        concept_id="CONCEPT_23_192",
        loinc_num="33192-3",
        snomed_ct="102300192",
        component="Diagnostic Analyte Component 23-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_193": ClinicalConcept_23(
        concept_id="CONCEPT_23_193",
        loinc_num="33193-4",
        snomed_ct="102300193",
        component="Diagnostic Analyte Component 23-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_194": ClinicalConcept_23(
        concept_id="CONCEPT_23_194",
        loinc_num="33194-5",
        snomed_ct="102300194",
        component="Diagnostic Analyte Component 23-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_195": ClinicalConcept_23(
        concept_id="CONCEPT_23_195",
        loinc_num="33195-6",
        snomed_ct="102300195",
        component="Diagnostic Analyte Component 23-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_196": ClinicalConcept_23(
        concept_id="CONCEPT_23_196",
        loinc_num="33196-7",
        snomed_ct="102300196",
        component="Diagnostic Analyte Component 23-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_197": ClinicalConcept_23(
        concept_id="CONCEPT_23_197",
        loinc_num="33197-8",
        snomed_ct="102300197",
        component="Diagnostic Analyte Component 23-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_198": ClinicalConcept_23(
        concept_id="CONCEPT_23_198",
        loinc_num="33198-0",
        snomed_ct="102300198",
        component="Diagnostic Analyte Component 23-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_23_199": ClinicalConcept_23(
        concept_id="CONCEPT_23_199",
        loinc_num="33199-1",
        snomed_ct="102300199",
        component="Diagnostic Analyte Component 23-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
