"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 03"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_03:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_03 = {
    "CONCEPT_03_001": ClinicalConcept_03(
        concept_id="CONCEPT_03_001",
        loinc_num="13001-1",
        snomed_ct="100300001",
        component="Diagnostic Analyte Component 03-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_002": ClinicalConcept_03(
        concept_id="CONCEPT_03_002",
        loinc_num="13002-2",
        snomed_ct="100300002",
        component="Diagnostic Analyte Component 03-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_003": ClinicalConcept_03(
        concept_id="CONCEPT_03_003",
        loinc_num="13003-3",
        snomed_ct="100300003",
        component="Diagnostic Analyte Component 03-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_004": ClinicalConcept_03(
        concept_id="CONCEPT_03_004",
        loinc_num="13004-4",
        snomed_ct="100300004",
        component="Diagnostic Analyte Component 03-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_005": ClinicalConcept_03(
        concept_id="CONCEPT_03_005",
        loinc_num="13005-5",
        snomed_ct="100300005",
        component="Diagnostic Analyte Component 03-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_006": ClinicalConcept_03(
        concept_id="CONCEPT_03_006",
        loinc_num="13006-6",
        snomed_ct="100300006",
        component="Diagnostic Analyte Component 03-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_007": ClinicalConcept_03(
        concept_id="CONCEPT_03_007",
        loinc_num="13007-7",
        snomed_ct="100300007",
        component="Diagnostic Analyte Component 03-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_008": ClinicalConcept_03(
        concept_id="CONCEPT_03_008",
        loinc_num="13008-8",
        snomed_ct="100300008",
        component="Diagnostic Analyte Component 03-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_009": ClinicalConcept_03(
        concept_id="CONCEPT_03_009",
        loinc_num="13009-0",
        snomed_ct="100300009",
        component="Diagnostic Analyte Component 03-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_010": ClinicalConcept_03(
        concept_id="CONCEPT_03_010",
        loinc_num="13010-1",
        snomed_ct="100300010",
        component="Diagnostic Analyte Component 03-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_011": ClinicalConcept_03(
        concept_id="CONCEPT_03_011",
        loinc_num="13011-2",
        snomed_ct="100300011",
        component="Diagnostic Analyte Component 03-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_012": ClinicalConcept_03(
        concept_id="CONCEPT_03_012",
        loinc_num="13012-3",
        snomed_ct="100300012",
        component="Diagnostic Analyte Component 03-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_013": ClinicalConcept_03(
        concept_id="CONCEPT_03_013",
        loinc_num="13013-4",
        snomed_ct="100300013",
        component="Diagnostic Analyte Component 03-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_014": ClinicalConcept_03(
        concept_id="CONCEPT_03_014",
        loinc_num="13014-5",
        snomed_ct="100300014",
        component="Diagnostic Analyte Component 03-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_015": ClinicalConcept_03(
        concept_id="CONCEPT_03_015",
        loinc_num="13015-6",
        snomed_ct="100300015",
        component="Diagnostic Analyte Component 03-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_016": ClinicalConcept_03(
        concept_id="CONCEPT_03_016",
        loinc_num="13016-7",
        snomed_ct="100300016",
        component="Diagnostic Analyte Component 03-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_017": ClinicalConcept_03(
        concept_id="CONCEPT_03_017",
        loinc_num="13017-8",
        snomed_ct="100300017",
        component="Diagnostic Analyte Component 03-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_018": ClinicalConcept_03(
        concept_id="CONCEPT_03_018",
        loinc_num="13018-0",
        snomed_ct="100300018",
        component="Diagnostic Analyte Component 03-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_019": ClinicalConcept_03(
        concept_id="CONCEPT_03_019",
        loinc_num="13019-1",
        snomed_ct="100300019",
        component="Diagnostic Analyte Component 03-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_020": ClinicalConcept_03(
        concept_id="CONCEPT_03_020",
        loinc_num="13020-2",
        snomed_ct="100300020",
        component="Diagnostic Analyte Component 03-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_021": ClinicalConcept_03(
        concept_id="CONCEPT_03_021",
        loinc_num="13021-3",
        snomed_ct="100300021",
        component="Diagnostic Analyte Component 03-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_022": ClinicalConcept_03(
        concept_id="CONCEPT_03_022",
        loinc_num="13022-4",
        snomed_ct="100300022",
        component="Diagnostic Analyte Component 03-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_023": ClinicalConcept_03(
        concept_id="CONCEPT_03_023",
        loinc_num="13023-5",
        snomed_ct="100300023",
        component="Diagnostic Analyte Component 03-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_024": ClinicalConcept_03(
        concept_id="CONCEPT_03_024",
        loinc_num="13024-6",
        snomed_ct="100300024",
        component="Diagnostic Analyte Component 03-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_025": ClinicalConcept_03(
        concept_id="CONCEPT_03_025",
        loinc_num="13025-7",
        snomed_ct="100300025",
        component="Diagnostic Analyte Component 03-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_026": ClinicalConcept_03(
        concept_id="CONCEPT_03_026",
        loinc_num="13026-8",
        snomed_ct="100300026",
        component="Diagnostic Analyte Component 03-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_027": ClinicalConcept_03(
        concept_id="CONCEPT_03_027",
        loinc_num="13027-0",
        snomed_ct="100300027",
        component="Diagnostic Analyte Component 03-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_028": ClinicalConcept_03(
        concept_id="CONCEPT_03_028",
        loinc_num="13028-1",
        snomed_ct="100300028",
        component="Diagnostic Analyte Component 03-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_029": ClinicalConcept_03(
        concept_id="CONCEPT_03_029",
        loinc_num="13029-2",
        snomed_ct="100300029",
        component="Diagnostic Analyte Component 03-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_030": ClinicalConcept_03(
        concept_id="CONCEPT_03_030",
        loinc_num="13030-3",
        snomed_ct="100300030",
        component="Diagnostic Analyte Component 03-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_031": ClinicalConcept_03(
        concept_id="CONCEPT_03_031",
        loinc_num="13031-4",
        snomed_ct="100300031",
        component="Diagnostic Analyte Component 03-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_032": ClinicalConcept_03(
        concept_id="CONCEPT_03_032",
        loinc_num="13032-5",
        snomed_ct="100300032",
        component="Diagnostic Analyte Component 03-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_033": ClinicalConcept_03(
        concept_id="CONCEPT_03_033",
        loinc_num="13033-6",
        snomed_ct="100300033",
        component="Diagnostic Analyte Component 03-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_034": ClinicalConcept_03(
        concept_id="CONCEPT_03_034",
        loinc_num="13034-7",
        snomed_ct="100300034",
        component="Diagnostic Analyte Component 03-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_035": ClinicalConcept_03(
        concept_id="CONCEPT_03_035",
        loinc_num="13035-8",
        snomed_ct="100300035",
        component="Diagnostic Analyte Component 03-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_036": ClinicalConcept_03(
        concept_id="CONCEPT_03_036",
        loinc_num="13036-0",
        snomed_ct="100300036",
        component="Diagnostic Analyte Component 03-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_037": ClinicalConcept_03(
        concept_id="CONCEPT_03_037",
        loinc_num="13037-1",
        snomed_ct="100300037",
        component="Diagnostic Analyte Component 03-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_038": ClinicalConcept_03(
        concept_id="CONCEPT_03_038",
        loinc_num="13038-2",
        snomed_ct="100300038",
        component="Diagnostic Analyte Component 03-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_039": ClinicalConcept_03(
        concept_id="CONCEPT_03_039",
        loinc_num="13039-3",
        snomed_ct="100300039",
        component="Diagnostic Analyte Component 03-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_040": ClinicalConcept_03(
        concept_id="CONCEPT_03_040",
        loinc_num="13040-4",
        snomed_ct="100300040",
        component="Diagnostic Analyte Component 03-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_041": ClinicalConcept_03(
        concept_id="CONCEPT_03_041",
        loinc_num="13041-5",
        snomed_ct="100300041",
        component="Diagnostic Analyte Component 03-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_042": ClinicalConcept_03(
        concept_id="CONCEPT_03_042",
        loinc_num="13042-6",
        snomed_ct="100300042",
        component="Diagnostic Analyte Component 03-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_043": ClinicalConcept_03(
        concept_id="CONCEPT_03_043",
        loinc_num="13043-7",
        snomed_ct="100300043",
        component="Diagnostic Analyte Component 03-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_044": ClinicalConcept_03(
        concept_id="CONCEPT_03_044",
        loinc_num="13044-8",
        snomed_ct="100300044",
        component="Diagnostic Analyte Component 03-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_045": ClinicalConcept_03(
        concept_id="CONCEPT_03_045",
        loinc_num="13045-0",
        snomed_ct="100300045",
        component="Diagnostic Analyte Component 03-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_046": ClinicalConcept_03(
        concept_id="CONCEPT_03_046",
        loinc_num="13046-1",
        snomed_ct="100300046",
        component="Diagnostic Analyte Component 03-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_047": ClinicalConcept_03(
        concept_id="CONCEPT_03_047",
        loinc_num="13047-2",
        snomed_ct="100300047",
        component="Diagnostic Analyte Component 03-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_048": ClinicalConcept_03(
        concept_id="CONCEPT_03_048",
        loinc_num="13048-3",
        snomed_ct="100300048",
        component="Diagnostic Analyte Component 03-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_049": ClinicalConcept_03(
        concept_id="CONCEPT_03_049",
        loinc_num="13049-4",
        snomed_ct="100300049",
        component="Diagnostic Analyte Component 03-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_050": ClinicalConcept_03(
        concept_id="CONCEPT_03_050",
        loinc_num="13050-5",
        snomed_ct="100300050",
        component="Diagnostic Analyte Component 03-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_051": ClinicalConcept_03(
        concept_id="CONCEPT_03_051",
        loinc_num="13051-6",
        snomed_ct="100300051",
        component="Diagnostic Analyte Component 03-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_052": ClinicalConcept_03(
        concept_id="CONCEPT_03_052",
        loinc_num="13052-7",
        snomed_ct="100300052",
        component="Diagnostic Analyte Component 03-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_053": ClinicalConcept_03(
        concept_id="CONCEPT_03_053",
        loinc_num="13053-8",
        snomed_ct="100300053",
        component="Diagnostic Analyte Component 03-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_054": ClinicalConcept_03(
        concept_id="CONCEPT_03_054",
        loinc_num="13054-0",
        snomed_ct="100300054",
        component="Diagnostic Analyte Component 03-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_055": ClinicalConcept_03(
        concept_id="CONCEPT_03_055",
        loinc_num="13055-1",
        snomed_ct="100300055",
        component="Diagnostic Analyte Component 03-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_056": ClinicalConcept_03(
        concept_id="CONCEPT_03_056",
        loinc_num="13056-2",
        snomed_ct="100300056",
        component="Diagnostic Analyte Component 03-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_057": ClinicalConcept_03(
        concept_id="CONCEPT_03_057",
        loinc_num="13057-3",
        snomed_ct="100300057",
        component="Diagnostic Analyte Component 03-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_058": ClinicalConcept_03(
        concept_id="CONCEPT_03_058",
        loinc_num="13058-4",
        snomed_ct="100300058",
        component="Diagnostic Analyte Component 03-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_059": ClinicalConcept_03(
        concept_id="CONCEPT_03_059",
        loinc_num="13059-5",
        snomed_ct="100300059",
        component="Diagnostic Analyte Component 03-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_060": ClinicalConcept_03(
        concept_id="CONCEPT_03_060",
        loinc_num="13060-6",
        snomed_ct="100300060",
        component="Diagnostic Analyte Component 03-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_061": ClinicalConcept_03(
        concept_id="CONCEPT_03_061",
        loinc_num="13061-7",
        snomed_ct="100300061",
        component="Diagnostic Analyte Component 03-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_062": ClinicalConcept_03(
        concept_id="CONCEPT_03_062",
        loinc_num="13062-8",
        snomed_ct="100300062",
        component="Diagnostic Analyte Component 03-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_063": ClinicalConcept_03(
        concept_id="CONCEPT_03_063",
        loinc_num="13063-0",
        snomed_ct="100300063",
        component="Diagnostic Analyte Component 03-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_064": ClinicalConcept_03(
        concept_id="CONCEPT_03_064",
        loinc_num="13064-1",
        snomed_ct="100300064",
        component="Diagnostic Analyte Component 03-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_065": ClinicalConcept_03(
        concept_id="CONCEPT_03_065",
        loinc_num="13065-2",
        snomed_ct="100300065",
        component="Diagnostic Analyte Component 03-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_066": ClinicalConcept_03(
        concept_id="CONCEPT_03_066",
        loinc_num="13066-3",
        snomed_ct="100300066",
        component="Diagnostic Analyte Component 03-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_067": ClinicalConcept_03(
        concept_id="CONCEPT_03_067",
        loinc_num="13067-4",
        snomed_ct="100300067",
        component="Diagnostic Analyte Component 03-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_068": ClinicalConcept_03(
        concept_id="CONCEPT_03_068",
        loinc_num="13068-5",
        snomed_ct="100300068",
        component="Diagnostic Analyte Component 03-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_069": ClinicalConcept_03(
        concept_id="CONCEPT_03_069",
        loinc_num="13069-6",
        snomed_ct="100300069",
        component="Diagnostic Analyte Component 03-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_070": ClinicalConcept_03(
        concept_id="CONCEPT_03_070",
        loinc_num="13070-7",
        snomed_ct="100300070",
        component="Diagnostic Analyte Component 03-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_071": ClinicalConcept_03(
        concept_id="CONCEPT_03_071",
        loinc_num="13071-8",
        snomed_ct="100300071",
        component="Diagnostic Analyte Component 03-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_072": ClinicalConcept_03(
        concept_id="CONCEPT_03_072",
        loinc_num="13072-0",
        snomed_ct="100300072",
        component="Diagnostic Analyte Component 03-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_073": ClinicalConcept_03(
        concept_id="CONCEPT_03_073",
        loinc_num="13073-1",
        snomed_ct="100300073",
        component="Diagnostic Analyte Component 03-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_074": ClinicalConcept_03(
        concept_id="CONCEPT_03_074",
        loinc_num="13074-2",
        snomed_ct="100300074",
        component="Diagnostic Analyte Component 03-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_075": ClinicalConcept_03(
        concept_id="CONCEPT_03_075",
        loinc_num="13075-3",
        snomed_ct="100300075",
        component="Diagnostic Analyte Component 03-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_076": ClinicalConcept_03(
        concept_id="CONCEPT_03_076",
        loinc_num="13076-4",
        snomed_ct="100300076",
        component="Diagnostic Analyte Component 03-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_077": ClinicalConcept_03(
        concept_id="CONCEPT_03_077",
        loinc_num="13077-5",
        snomed_ct="100300077",
        component="Diagnostic Analyte Component 03-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_078": ClinicalConcept_03(
        concept_id="CONCEPT_03_078",
        loinc_num="13078-6",
        snomed_ct="100300078",
        component="Diagnostic Analyte Component 03-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_079": ClinicalConcept_03(
        concept_id="CONCEPT_03_079",
        loinc_num="13079-7",
        snomed_ct="100300079",
        component="Diagnostic Analyte Component 03-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_080": ClinicalConcept_03(
        concept_id="CONCEPT_03_080",
        loinc_num="13080-8",
        snomed_ct="100300080",
        component="Diagnostic Analyte Component 03-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_081": ClinicalConcept_03(
        concept_id="CONCEPT_03_081",
        loinc_num="13081-0",
        snomed_ct="100300081",
        component="Diagnostic Analyte Component 03-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_082": ClinicalConcept_03(
        concept_id="CONCEPT_03_082",
        loinc_num="13082-1",
        snomed_ct="100300082",
        component="Diagnostic Analyte Component 03-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_083": ClinicalConcept_03(
        concept_id="CONCEPT_03_083",
        loinc_num="13083-2",
        snomed_ct="100300083",
        component="Diagnostic Analyte Component 03-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_084": ClinicalConcept_03(
        concept_id="CONCEPT_03_084",
        loinc_num="13084-3",
        snomed_ct="100300084",
        component="Diagnostic Analyte Component 03-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_085": ClinicalConcept_03(
        concept_id="CONCEPT_03_085",
        loinc_num="13085-4",
        snomed_ct="100300085",
        component="Diagnostic Analyte Component 03-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_086": ClinicalConcept_03(
        concept_id="CONCEPT_03_086",
        loinc_num="13086-5",
        snomed_ct="100300086",
        component="Diagnostic Analyte Component 03-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_087": ClinicalConcept_03(
        concept_id="CONCEPT_03_087",
        loinc_num="13087-6",
        snomed_ct="100300087",
        component="Diagnostic Analyte Component 03-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_088": ClinicalConcept_03(
        concept_id="CONCEPT_03_088",
        loinc_num="13088-7",
        snomed_ct="100300088",
        component="Diagnostic Analyte Component 03-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_089": ClinicalConcept_03(
        concept_id="CONCEPT_03_089",
        loinc_num="13089-8",
        snomed_ct="100300089",
        component="Diagnostic Analyte Component 03-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_090": ClinicalConcept_03(
        concept_id="CONCEPT_03_090",
        loinc_num="13090-0",
        snomed_ct="100300090",
        component="Diagnostic Analyte Component 03-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_091": ClinicalConcept_03(
        concept_id="CONCEPT_03_091",
        loinc_num="13091-1",
        snomed_ct="100300091",
        component="Diagnostic Analyte Component 03-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_092": ClinicalConcept_03(
        concept_id="CONCEPT_03_092",
        loinc_num="13092-2",
        snomed_ct="100300092",
        component="Diagnostic Analyte Component 03-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_093": ClinicalConcept_03(
        concept_id="CONCEPT_03_093",
        loinc_num="13093-3",
        snomed_ct="100300093",
        component="Diagnostic Analyte Component 03-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_094": ClinicalConcept_03(
        concept_id="CONCEPT_03_094",
        loinc_num="13094-4",
        snomed_ct="100300094",
        component="Diagnostic Analyte Component 03-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_095": ClinicalConcept_03(
        concept_id="CONCEPT_03_095",
        loinc_num="13095-5",
        snomed_ct="100300095",
        component="Diagnostic Analyte Component 03-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_096": ClinicalConcept_03(
        concept_id="CONCEPT_03_096",
        loinc_num="13096-6",
        snomed_ct="100300096",
        component="Diagnostic Analyte Component 03-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_097": ClinicalConcept_03(
        concept_id="CONCEPT_03_097",
        loinc_num="13097-7",
        snomed_ct="100300097",
        component="Diagnostic Analyte Component 03-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_098": ClinicalConcept_03(
        concept_id="CONCEPT_03_098",
        loinc_num="13098-8",
        snomed_ct="100300098",
        component="Diagnostic Analyte Component 03-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_099": ClinicalConcept_03(
        concept_id="CONCEPT_03_099",
        loinc_num="13099-0",
        snomed_ct="100300099",
        component="Diagnostic Analyte Component 03-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_100": ClinicalConcept_03(
        concept_id="CONCEPT_03_100",
        loinc_num="13100-1",
        snomed_ct="100300100",
        component="Diagnostic Analyte Component 03-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_101": ClinicalConcept_03(
        concept_id="CONCEPT_03_101",
        loinc_num="13101-2",
        snomed_ct="100300101",
        component="Diagnostic Analyte Component 03-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_102": ClinicalConcept_03(
        concept_id="CONCEPT_03_102",
        loinc_num="13102-3",
        snomed_ct="100300102",
        component="Diagnostic Analyte Component 03-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_103": ClinicalConcept_03(
        concept_id="CONCEPT_03_103",
        loinc_num="13103-4",
        snomed_ct="100300103",
        component="Diagnostic Analyte Component 03-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_104": ClinicalConcept_03(
        concept_id="CONCEPT_03_104",
        loinc_num="13104-5",
        snomed_ct="100300104",
        component="Diagnostic Analyte Component 03-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_105": ClinicalConcept_03(
        concept_id="CONCEPT_03_105",
        loinc_num="13105-6",
        snomed_ct="100300105",
        component="Diagnostic Analyte Component 03-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_106": ClinicalConcept_03(
        concept_id="CONCEPT_03_106",
        loinc_num="13106-7",
        snomed_ct="100300106",
        component="Diagnostic Analyte Component 03-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_107": ClinicalConcept_03(
        concept_id="CONCEPT_03_107",
        loinc_num="13107-8",
        snomed_ct="100300107",
        component="Diagnostic Analyte Component 03-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_108": ClinicalConcept_03(
        concept_id="CONCEPT_03_108",
        loinc_num="13108-0",
        snomed_ct="100300108",
        component="Diagnostic Analyte Component 03-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_109": ClinicalConcept_03(
        concept_id="CONCEPT_03_109",
        loinc_num="13109-1",
        snomed_ct="100300109",
        component="Diagnostic Analyte Component 03-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_110": ClinicalConcept_03(
        concept_id="CONCEPT_03_110",
        loinc_num="13110-2",
        snomed_ct="100300110",
        component="Diagnostic Analyte Component 03-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_111": ClinicalConcept_03(
        concept_id="CONCEPT_03_111",
        loinc_num="13111-3",
        snomed_ct="100300111",
        component="Diagnostic Analyte Component 03-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_112": ClinicalConcept_03(
        concept_id="CONCEPT_03_112",
        loinc_num="13112-4",
        snomed_ct="100300112",
        component="Diagnostic Analyte Component 03-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_113": ClinicalConcept_03(
        concept_id="CONCEPT_03_113",
        loinc_num="13113-5",
        snomed_ct="100300113",
        component="Diagnostic Analyte Component 03-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_114": ClinicalConcept_03(
        concept_id="CONCEPT_03_114",
        loinc_num="13114-6",
        snomed_ct="100300114",
        component="Diagnostic Analyte Component 03-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_115": ClinicalConcept_03(
        concept_id="CONCEPT_03_115",
        loinc_num="13115-7",
        snomed_ct="100300115",
        component="Diagnostic Analyte Component 03-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_116": ClinicalConcept_03(
        concept_id="CONCEPT_03_116",
        loinc_num="13116-8",
        snomed_ct="100300116",
        component="Diagnostic Analyte Component 03-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_117": ClinicalConcept_03(
        concept_id="CONCEPT_03_117",
        loinc_num="13117-0",
        snomed_ct="100300117",
        component="Diagnostic Analyte Component 03-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_118": ClinicalConcept_03(
        concept_id="CONCEPT_03_118",
        loinc_num="13118-1",
        snomed_ct="100300118",
        component="Diagnostic Analyte Component 03-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_119": ClinicalConcept_03(
        concept_id="CONCEPT_03_119",
        loinc_num="13119-2",
        snomed_ct="100300119",
        component="Diagnostic Analyte Component 03-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_120": ClinicalConcept_03(
        concept_id="CONCEPT_03_120",
        loinc_num="13120-3",
        snomed_ct="100300120",
        component="Diagnostic Analyte Component 03-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_121": ClinicalConcept_03(
        concept_id="CONCEPT_03_121",
        loinc_num="13121-4",
        snomed_ct="100300121",
        component="Diagnostic Analyte Component 03-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_122": ClinicalConcept_03(
        concept_id="CONCEPT_03_122",
        loinc_num="13122-5",
        snomed_ct="100300122",
        component="Diagnostic Analyte Component 03-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_123": ClinicalConcept_03(
        concept_id="CONCEPT_03_123",
        loinc_num="13123-6",
        snomed_ct="100300123",
        component="Diagnostic Analyte Component 03-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_124": ClinicalConcept_03(
        concept_id="CONCEPT_03_124",
        loinc_num="13124-7",
        snomed_ct="100300124",
        component="Diagnostic Analyte Component 03-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_125": ClinicalConcept_03(
        concept_id="CONCEPT_03_125",
        loinc_num="13125-8",
        snomed_ct="100300125",
        component="Diagnostic Analyte Component 03-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_126": ClinicalConcept_03(
        concept_id="CONCEPT_03_126",
        loinc_num="13126-0",
        snomed_ct="100300126",
        component="Diagnostic Analyte Component 03-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_127": ClinicalConcept_03(
        concept_id="CONCEPT_03_127",
        loinc_num="13127-1",
        snomed_ct="100300127",
        component="Diagnostic Analyte Component 03-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_128": ClinicalConcept_03(
        concept_id="CONCEPT_03_128",
        loinc_num="13128-2",
        snomed_ct="100300128",
        component="Diagnostic Analyte Component 03-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_129": ClinicalConcept_03(
        concept_id="CONCEPT_03_129",
        loinc_num="13129-3",
        snomed_ct="100300129",
        component="Diagnostic Analyte Component 03-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_130": ClinicalConcept_03(
        concept_id="CONCEPT_03_130",
        loinc_num="13130-4",
        snomed_ct="100300130",
        component="Diagnostic Analyte Component 03-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_131": ClinicalConcept_03(
        concept_id="CONCEPT_03_131",
        loinc_num="13131-5",
        snomed_ct="100300131",
        component="Diagnostic Analyte Component 03-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_132": ClinicalConcept_03(
        concept_id="CONCEPT_03_132",
        loinc_num="13132-6",
        snomed_ct="100300132",
        component="Diagnostic Analyte Component 03-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_133": ClinicalConcept_03(
        concept_id="CONCEPT_03_133",
        loinc_num="13133-7",
        snomed_ct="100300133",
        component="Diagnostic Analyte Component 03-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_134": ClinicalConcept_03(
        concept_id="CONCEPT_03_134",
        loinc_num="13134-8",
        snomed_ct="100300134",
        component="Diagnostic Analyte Component 03-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_135": ClinicalConcept_03(
        concept_id="CONCEPT_03_135",
        loinc_num="13135-0",
        snomed_ct="100300135",
        component="Diagnostic Analyte Component 03-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_136": ClinicalConcept_03(
        concept_id="CONCEPT_03_136",
        loinc_num="13136-1",
        snomed_ct="100300136",
        component="Diagnostic Analyte Component 03-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_137": ClinicalConcept_03(
        concept_id="CONCEPT_03_137",
        loinc_num="13137-2",
        snomed_ct="100300137",
        component="Diagnostic Analyte Component 03-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_138": ClinicalConcept_03(
        concept_id="CONCEPT_03_138",
        loinc_num="13138-3",
        snomed_ct="100300138",
        component="Diagnostic Analyte Component 03-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_139": ClinicalConcept_03(
        concept_id="CONCEPT_03_139",
        loinc_num="13139-4",
        snomed_ct="100300139",
        component="Diagnostic Analyte Component 03-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_140": ClinicalConcept_03(
        concept_id="CONCEPT_03_140",
        loinc_num="13140-5",
        snomed_ct="100300140",
        component="Diagnostic Analyte Component 03-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_141": ClinicalConcept_03(
        concept_id="CONCEPT_03_141",
        loinc_num="13141-6",
        snomed_ct="100300141",
        component="Diagnostic Analyte Component 03-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_142": ClinicalConcept_03(
        concept_id="CONCEPT_03_142",
        loinc_num="13142-7",
        snomed_ct="100300142",
        component="Diagnostic Analyte Component 03-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_143": ClinicalConcept_03(
        concept_id="CONCEPT_03_143",
        loinc_num="13143-8",
        snomed_ct="100300143",
        component="Diagnostic Analyte Component 03-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_144": ClinicalConcept_03(
        concept_id="CONCEPT_03_144",
        loinc_num="13144-0",
        snomed_ct="100300144",
        component="Diagnostic Analyte Component 03-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_145": ClinicalConcept_03(
        concept_id="CONCEPT_03_145",
        loinc_num="13145-1",
        snomed_ct="100300145",
        component="Diagnostic Analyte Component 03-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_146": ClinicalConcept_03(
        concept_id="CONCEPT_03_146",
        loinc_num="13146-2",
        snomed_ct="100300146",
        component="Diagnostic Analyte Component 03-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_147": ClinicalConcept_03(
        concept_id="CONCEPT_03_147",
        loinc_num="13147-3",
        snomed_ct="100300147",
        component="Diagnostic Analyte Component 03-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_148": ClinicalConcept_03(
        concept_id="CONCEPT_03_148",
        loinc_num="13148-4",
        snomed_ct="100300148",
        component="Diagnostic Analyte Component 03-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_149": ClinicalConcept_03(
        concept_id="CONCEPT_03_149",
        loinc_num="13149-5",
        snomed_ct="100300149",
        component="Diagnostic Analyte Component 03-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_150": ClinicalConcept_03(
        concept_id="CONCEPT_03_150",
        loinc_num="13150-6",
        snomed_ct="100300150",
        component="Diagnostic Analyte Component 03-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_151": ClinicalConcept_03(
        concept_id="CONCEPT_03_151",
        loinc_num="13151-7",
        snomed_ct="100300151",
        component="Diagnostic Analyte Component 03-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_152": ClinicalConcept_03(
        concept_id="CONCEPT_03_152",
        loinc_num="13152-8",
        snomed_ct="100300152",
        component="Diagnostic Analyte Component 03-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_153": ClinicalConcept_03(
        concept_id="CONCEPT_03_153",
        loinc_num="13153-0",
        snomed_ct="100300153",
        component="Diagnostic Analyte Component 03-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_154": ClinicalConcept_03(
        concept_id="CONCEPT_03_154",
        loinc_num="13154-1",
        snomed_ct="100300154",
        component="Diagnostic Analyte Component 03-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_155": ClinicalConcept_03(
        concept_id="CONCEPT_03_155",
        loinc_num="13155-2",
        snomed_ct="100300155",
        component="Diagnostic Analyte Component 03-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_156": ClinicalConcept_03(
        concept_id="CONCEPT_03_156",
        loinc_num="13156-3",
        snomed_ct="100300156",
        component="Diagnostic Analyte Component 03-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_157": ClinicalConcept_03(
        concept_id="CONCEPT_03_157",
        loinc_num="13157-4",
        snomed_ct="100300157",
        component="Diagnostic Analyte Component 03-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_158": ClinicalConcept_03(
        concept_id="CONCEPT_03_158",
        loinc_num="13158-5",
        snomed_ct="100300158",
        component="Diagnostic Analyte Component 03-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_159": ClinicalConcept_03(
        concept_id="CONCEPT_03_159",
        loinc_num="13159-6",
        snomed_ct="100300159",
        component="Diagnostic Analyte Component 03-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_160": ClinicalConcept_03(
        concept_id="CONCEPT_03_160",
        loinc_num="13160-7",
        snomed_ct="100300160",
        component="Diagnostic Analyte Component 03-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_161": ClinicalConcept_03(
        concept_id="CONCEPT_03_161",
        loinc_num="13161-8",
        snomed_ct="100300161",
        component="Diagnostic Analyte Component 03-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_162": ClinicalConcept_03(
        concept_id="CONCEPT_03_162",
        loinc_num="13162-0",
        snomed_ct="100300162",
        component="Diagnostic Analyte Component 03-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_163": ClinicalConcept_03(
        concept_id="CONCEPT_03_163",
        loinc_num="13163-1",
        snomed_ct="100300163",
        component="Diagnostic Analyte Component 03-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_164": ClinicalConcept_03(
        concept_id="CONCEPT_03_164",
        loinc_num="13164-2",
        snomed_ct="100300164",
        component="Diagnostic Analyte Component 03-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_165": ClinicalConcept_03(
        concept_id="CONCEPT_03_165",
        loinc_num="13165-3",
        snomed_ct="100300165",
        component="Diagnostic Analyte Component 03-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_166": ClinicalConcept_03(
        concept_id="CONCEPT_03_166",
        loinc_num="13166-4",
        snomed_ct="100300166",
        component="Diagnostic Analyte Component 03-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_167": ClinicalConcept_03(
        concept_id="CONCEPT_03_167",
        loinc_num="13167-5",
        snomed_ct="100300167",
        component="Diagnostic Analyte Component 03-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_168": ClinicalConcept_03(
        concept_id="CONCEPT_03_168",
        loinc_num="13168-6",
        snomed_ct="100300168",
        component="Diagnostic Analyte Component 03-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_169": ClinicalConcept_03(
        concept_id="CONCEPT_03_169",
        loinc_num="13169-7",
        snomed_ct="100300169",
        component="Diagnostic Analyte Component 03-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_170": ClinicalConcept_03(
        concept_id="CONCEPT_03_170",
        loinc_num="13170-8",
        snomed_ct="100300170",
        component="Diagnostic Analyte Component 03-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_171": ClinicalConcept_03(
        concept_id="CONCEPT_03_171",
        loinc_num="13171-0",
        snomed_ct="100300171",
        component="Diagnostic Analyte Component 03-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_172": ClinicalConcept_03(
        concept_id="CONCEPT_03_172",
        loinc_num="13172-1",
        snomed_ct="100300172",
        component="Diagnostic Analyte Component 03-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_173": ClinicalConcept_03(
        concept_id="CONCEPT_03_173",
        loinc_num="13173-2",
        snomed_ct="100300173",
        component="Diagnostic Analyte Component 03-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_174": ClinicalConcept_03(
        concept_id="CONCEPT_03_174",
        loinc_num="13174-3",
        snomed_ct="100300174",
        component="Diagnostic Analyte Component 03-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_175": ClinicalConcept_03(
        concept_id="CONCEPT_03_175",
        loinc_num="13175-4",
        snomed_ct="100300175",
        component="Diagnostic Analyte Component 03-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_176": ClinicalConcept_03(
        concept_id="CONCEPT_03_176",
        loinc_num="13176-5",
        snomed_ct="100300176",
        component="Diagnostic Analyte Component 03-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_177": ClinicalConcept_03(
        concept_id="CONCEPT_03_177",
        loinc_num="13177-6",
        snomed_ct="100300177",
        component="Diagnostic Analyte Component 03-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_178": ClinicalConcept_03(
        concept_id="CONCEPT_03_178",
        loinc_num="13178-7",
        snomed_ct="100300178",
        component="Diagnostic Analyte Component 03-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_179": ClinicalConcept_03(
        concept_id="CONCEPT_03_179",
        loinc_num="13179-8",
        snomed_ct="100300179",
        component="Diagnostic Analyte Component 03-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_180": ClinicalConcept_03(
        concept_id="CONCEPT_03_180",
        loinc_num="13180-0",
        snomed_ct="100300180",
        component="Diagnostic Analyte Component 03-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_181": ClinicalConcept_03(
        concept_id="CONCEPT_03_181",
        loinc_num="13181-1",
        snomed_ct="100300181",
        component="Diagnostic Analyte Component 03-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_182": ClinicalConcept_03(
        concept_id="CONCEPT_03_182",
        loinc_num="13182-2",
        snomed_ct="100300182",
        component="Diagnostic Analyte Component 03-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_183": ClinicalConcept_03(
        concept_id="CONCEPT_03_183",
        loinc_num="13183-3",
        snomed_ct="100300183",
        component="Diagnostic Analyte Component 03-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_184": ClinicalConcept_03(
        concept_id="CONCEPT_03_184",
        loinc_num="13184-4",
        snomed_ct="100300184",
        component="Diagnostic Analyte Component 03-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_185": ClinicalConcept_03(
        concept_id="CONCEPT_03_185",
        loinc_num="13185-5",
        snomed_ct="100300185",
        component="Diagnostic Analyte Component 03-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_186": ClinicalConcept_03(
        concept_id="CONCEPT_03_186",
        loinc_num="13186-6",
        snomed_ct="100300186",
        component="Diagnostic Analyte Component 03-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_187": ClinicalConcept_03(
        concept_id="CONCEPT_03_187",
        loinc_num="13187-7",
        snomed_ct="100300187",
        component="Diagnostic Analyte Component 03-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_188": ClinicalConcept_03(
        concept_id="CONCEPT_03_188",
        loinc_num="13188-8",
        snomed_ct="100300188",
        component="Diagnostic Analyte Component 03-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_189": ClinicalConcept_03(
        concept_id="CONCEPT_03_189",
        loinc_num="13189-0",
        snomed_ct="100300189",
        component="Diagnostic Analyte Component 03-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_190": ClinicalConcept_03(
        concept_id="CONCEPT_03_190",
        loinc_num="13190-1",
        snomed_ct="100300190",
        component="Diagnostic Analyte Component 03-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_191": ClinicalConcept_03(
        concept_id="CONCEPT_03_191",
        loinc_num="13191-2",
        snomed_ct="100300191",
        component="Diagnostic Analyte Component 03-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_192": ClinicalConcept_03(
        concept_id="CONCEPT_03_192",
        loinc_num="13192-3",
        snomed_ct="100300192",
        component="Diagnostic Analyte Component 03-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_193": ClinicalConcept_03(
        concept_id="CONCEPT_03_193",
        loinc_num="13193-4",
        snomed_ct="100300193",
        component="Diagnostic Analyte Component 03-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_194": ClinicalConcept_03(
        concept_id="CONCEPT_03_194",
        loinc_num="13194-5",
        snomed_ct="100300194",
        component="Diagnostic Analyte Component 03-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_195": ClinicalConcept_03(
        concept_id="CONCEPT_03_195",
        loinc_num="13195-6",
        snomed_ct="100300195",
        component="Diagnostic Analyte Component 03-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_196": ClinicalConcept_03(
        concept_id="CONCEPT_03_196",
        loinc_num="13196-7",
        snomed_ct="100300196",
        component="Diagnostic Analyte Component 03-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_197": ClinicalConcept_03(
        concept_id="CONCEPT_03_197",
        loinc_num="13197-8",
        snomed_ct="100300197",
        component="Diagnostic Analyte Component 03-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_198": ClinicalConcept_03(
        concept_id="CONCEPT_03_198",
        loinc_num="13198-0",
        snomed_ct="100300198",
        component="Diagnostic Analyte Component 03-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_03_199": ClinicalConcept_03(
        concept_id="CONCEPT_03_199",
        loinc_num="13199-1",
        snomed_ct="100300199",
        component="Diagnostic Analyte Component 03-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
