"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 20"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_20:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_20 = {
    "CONCEPT_20_001": ClinicalConcept_20(
        concept_id="CONCEPT_20_001",
        loinc_num="30001-1",
        snomed_ct="102000001",
        component="Diagnostic Analyte Component 20-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_002": ClinicalConcept_20(
        concept_id="CONCEPT_20_002",
        loinc_num="30002-2",
        snomed_ct="102000002",
        component="Diagnostic Analyte Component 20-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_003": ClinicalConcept_20(
        concept_id="CONCEPT_20_003",
        loinc_num="30003-3",
        snomed_ct="102000003",
        component="Diagnostic Analyte Component 20-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_004": ClinicalConcept_20(
        concept_id="CONCEPT_20_004",
        loinc_num="30004-4",
        snomed_ct="102000004",
        component="Diagnostic Analyte Component 20-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_005": ClinicalConcept_20(
        concept_id="CONCEPT_20_005",
        loinc_num="30005-5",
        snomed_ct="102000005",
        component="Diagnostic Analyte Component 20-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_006": ClinicalConcept_20(
        concept_id="CONCEPT_20_006",
        loinc_num="30006-6",
        snomed_ct="102000006",
        component="Diagnostic Analyte Component 20-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_007": ClinicalConcept_20(
        concept_id="CONCEPT_20_007",
        loinc_num="30007-7",
        snomed_ct="102000007",
        component="Diagnostic Analyte Component 20-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_008": ClinicalConcept_20(
        concept_id="CONCEPT_20_008",
        loinc_num="30008-8",
        snomed_ct="102000008",
        component="Diagnostic Analyte Component 20-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_009": ClinicalConcept_20(
        concept_id="CONCEPT_20_009",
        loinc_num="30009-0",
        snomed_ct="102000009",
        component="Diagnostic Analyte Component 20-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_010": ClinicalConcept_20(
        concept_id="CONCEPT_20_010",
        loinc_num="30010-1",
        snomed_ct="102000010",
        component="Diagnostic Analyte Component 20-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_011": ClinicalConcept_20(
        concept_id="CONCEPT_20_011",
        loinc_num="30011-2",
        snomed_ct="102000011",
        component="Diagnostic Analyte Component 20-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_012": ClinicalConcept_20(
        concept_id="CONCEPT_20_012",
        loinc_num="30012-3",
        snomed_ct="102000012",
        component="Diagnostic Analyte Component 20-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_013": ClinicalConcept_20(
        concept_id="CONCEPT_20_013",
        loinc_num="30013-4",
        snomed_ct="102000013",
        component="Diagnostic Analyte Component 20-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_014": ClinicalConcept_20(
        concept_id="CONCEPT_20_014",
        loinc_num="30014-5",
        snomed_ct="102000014",
        component="Diagnostic Analyte Component 20-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_015": ClinicalConcept_20(
        concept_id="CONCEPT_20_015",
        loinc_num="30015-6",
        snomed_ct="102000015",
        component="Diagnostic Analyte Component 20-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_016": ClinicalConcept_20(
        concept_id="CONCEPT_20_016",
        loinc_num="30016-7",
        snomed_ct="102000016",
        component="Diagnostic Analyte Component 20-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_017": ClinicalConcept_20(
        concept_id="CONCEPT_20_017",
        loinc_num="30017-8",
        snomed_ct="102000017",
        component="Diagnostic Analyte Component 20-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_018": ClinicalConcept_20(
        concept_id="CONCEPT_20_018",
        loinc_num="30018-0",
        snomed_ct="102000018",
        component="Diagnostic Analyte Component 20-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_019": ClinicalConcept_20(
        concept_id="CONCEPT_20_019",
        loinc_num="30019-1",
        snomed_ct="102000019",
        component="Diagnostic Analyte Component 20-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_020": ClinicalConcept_20(
        concept_id="CONCEPT_20_020",
        loinc_num="30020-2",
        snomed_ct="102000020",
        component="Diagnostic Analyte Component 20-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_021": ClinicalConcept_20(
        concept_id="CONCEPT_20_021",
        loinc_num="30021-3",
        snomed_ct="102000021",
        component="Diagnostic Analyte Component 20-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_022": ClinicalConcept_20(
        concept_id="CONCEPT_20_022",
        loinc_num="30022-4",
        snomed_ct="102000022",
        component="Diagnostic Analyte Component 20-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_023": ClinicalConcept_20(
        concept_id="CONCEPT_20_023",
        loinc_num="30023-5",
        snomed_ct="102000023",
        component="Diagnostic Analyte Component 20-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_024": ClinicalConcept_20(
        concept_id="CONCEPT_20_024",
        loinc_num="30024-6",
        snomed_ct="102000024",
        component="Diagnostic Analyte Component 20-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_025": ClinicalConcept_20(
        concept_id="CONCEPT_20_025",
        loinc_num="30025-7",
        snomed_ct="102000025",
        component="Diagnostic Analyte Component 20-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_026": ClinicalConcept_20(
        concept_id="CONCEPT_20_026",
        loinc_num="30026-8",
        snomed_ct="102000026",
        component="Diagnostic Analyte Component 20-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_027": ClinicalConcept_20(
        concept_id="CONCEPT_20_027",
        loinc_num="30027-0",
        snomed_ct="102000027",
        component="Diagnostic Analyte Component 20-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_028": ClinicalConcept_20(
        concept_id="CONCEPT_20_028",
        loinc_num="30028-1",
        snomed_ct="102000028",
        component="Diagnostic Analyte Component 20-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_029": ClinicalConcept_20(
        concept_id="CONCEPT_20_029",
        loinc_num="30029-2",
        snomed_ct="102000029",
        component="Diagnostic Analyte Component 20-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_030": ClinicalConcept_20(
        concept_id="CONCEPT_20_030",
        loinc_num="30030-3",
        snomed_ct="102000030",
        component="Diagnostic Analyte Component 20-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_031": ClinicalConcept_20(
        concept_id="CONCEPT_20_031",
        loinc_num="30031-4",
        snomed_ct="102000031",
        component="Diagnostic Analyte Component 20-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_032": ClinicalConcept_20(
        concept_id="CONCEPT_20_032",
        loinc_num="30032-5",
        snomed_ct="102000032",
        component="Diagnostic Analyte Component 20-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_033": ClinicalConcept_20(
        concept_id="CONCEPT_20_033",
        loinc_num="30033-6",
        snomed_ct="102000033",
        component="Diagnostic Analyte Component 20-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_034": ClinicalConcept_20(
        concept_id="CONCEPT_20_034",
        loinc_num="30034-7",
        snomed_ct="102000034",
        component="Diagnostic Analyte Component 20-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_035": ClinicalConcept_20(
        concept_id="CONCEPT_20_035",
        loinc_num="30035-8",
        snomed_ct="102000035",
        component="Diagnostic Analyte Component 20-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_036": ClinicalConcept_20(
        concept_id="CONCEPT_20_036",
        loinc_num="30036-0",
        snomed_ct="102000036",
        component="Diagnostic Analyte Component 20-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_037": ClinicalConcept_20(
        concept_id="CONCEPT_20_037",
        loinc_num="30037-1",
        snomed_ct="102000037",
        component="Diagnostic Analyte Component 20-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_038": ClinicalConcept_20(
        concept_id="CONCEPT_20_038",
        loinc_num="30038-2",
        snomed_ct="102000038",
        component="Diagnostic Analyte Component 20-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_039": ClinicalConcept_20(
        concept_id="CONCEPT_20_039",
        loinc_num="30039-3",
        snomed_ct="102000039",
        component="Diagnostic Analyte Component 20-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_040": ClinicalConcept_20(
        concept_id="CONCEPT_20_040",
        loinc_num="30040-4",
        snomed_ct="102000040",
        component="Diagnostic Analyte Component 20-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_041": ClinicalConcept_20(
        concept_id="CONCEPT_20_041",
        loinc_num="30041-5",
        snomed_ct="102000041",
        component="Diagnostic Analyte Component 20-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_042": ClinicalConcept_20(
        concept_id="CONCEPT_20_042",
        loinc_num="30042-6",
        snomed_ct="102000042",
        component="Diagnostic Analyte Component 20-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_043": ClinicalConcept_20(
        concept_id="CONCEPT_20_043",
        loinc_num="30043-7",
        snomed_ct="102000043",
        component="Diagnostic Analyte Component 20-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_044": ClinicalConcept_20(
        concept_id="CONCEPT_20_044",
        loinc_num="30044-8",
        snomed_ct="102000044",
        component="Diagnostic Analyte Component 20-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_045": ClinicalConcept_20(
        concept_id="CONCEPT_20_045",
        loinc_num="30045-0",
        snomed_ct="102000045",
        component="Diagnostic Analyte Component 20-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_046": ClinicalConcept_20(
        concept_id="CONCEPT_20_046",
        loinc_num="30046-1",
        snomed_ct="102000046",
        component="Diagnostic Analyte Component 20-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_047": ClinicalConcept_20(
        concept_id="CONCEPT_20_047",
        loinc_num="30047-2",
        snomed_ct="102000047",
        component="Diagnostic Analyte Component 20-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_048": ClinicalConcept_20(
        concept_id="CONCEPT_20_048",
        loinc_num="30048-3",
        snomed_ct="102000048",
        component="Diagnostic Analyte Component 20-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_049": ClinicalConcept_20(
        concept_id="CONCEPT_20_049",
        loinc_num="30049-4",
        snomed_ct="102000049",
        component="Diagnostic Analyte Component 20-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_050": ClinicalConcept_20(
        concept_id="CONCEPT_20_050",
        loinc_num="30050-5",
        snomed_ct="102000050",
        component="Diagnostic Analyte Component 20-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_051": ClinicalConcept_20(
        concept_id="CONCEPT_20_051",
        loinc_num="30051-6",
        snomed_ct="102000051",
        component="Diagnostic Analyte Component 20-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_052": ClinicalConcept_20(
        concept_id="CONCEPT_20_052",
        loinc_num="30052-7",
        snomed_ct="102000052",
        component="Diagnostic Analyte Component 20-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_053": ClinicalConcept_20(
        concept_id="CONCEPT_20_053",
        loinc_num="30053-8",
        snomed_ct="102000053",
        component="Diagnostic Analyte Component 20-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_054": ClinicalConcept_20(
        concept_id="CONCEPT_20_054",
        loinc_num="30054-0",
        snomed_ct="102000054",
        component="Diagnostic Analyte Component 20-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_055": ClinicalConcept_20(
        concept_id="CONCEPT_20_055",
        loinc_num="30055-1",
        snomed_ct="102000055",
        component="Diagnostic Analyte Component 20-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_056": ClinicalConcept_20(
        concept_id="CONCEPT_20_056",
        loinc_num="30056-2",
        snomed_ct="102000056",
        component="Diagnostic Analyte Component 20-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_057": ClinicalConcept_20(
        concept_id="CONCEPT_20_057",
        loinc_num="30057-3",
        snomed_ct="102000057",
        component="Diagnostic Analyte Component 20-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_058": ClinicalConcept_20(
        concept_id="CONCEPT_20_058",
        loinc_num="30058-4",
        snomed_ct="102000058",
        component="Diagnostic Analyte Component 20-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_059": ClinicalConcept_20(
        concept_id="CONCEPT_20_059",
        loinc_num="30059-5",
        snomed_ct="102000059",
        component="Diagnostic Analyte Component 20-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_060": ClinicalConcept_20(
        concept_id="CONCEPT_20_060",
        loinc_num="30060-6",
        snomed_ct="102000060",
        component="Diagnostic Analyte Component 20-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_061": ClinicalConcept_20(
        concept_id="CONCEPT_20_061",
        loinc_num="30061-7",
        snomed_ct="102000061",
        component="Diagnostic Analyte Component 20-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_062": ClinicalConcept_20(
        concept_id="CONCEPT_20_062",
        loinc_num="30062-8",
        snomed_ct="102000062",
        component="Diagnostic Analyte Component 20-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_063": ClinicalConcept_20(
        concept_id="CONCEPT_20_063",
        loinc_num="30063-0",
        snomed_ct="102000063",
        component="Diagnostic Analyte Component 20-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_064": ClinicalConcept_20(
        concept_id="CONCEPT_20_064",
        loinc_num="30064-1",
        snomed_ct="102000064",
        component="Diagnostic Analyte Component 20-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_065": ClinicalConcept_20(
        concept_id="CONCEPT_20_065",
        loinc_num="30065-2",
        snomed_ct="102000065",
        component="Diagnostic Analyte Component 20-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_066": ClinicalConcept_20(
        concept_id="CONCEPT_20_066",
        loinc_num="30066-3",
        snomed_ct="102000066",
        component="Diagnostic Analyte Component 20-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_067": ClinicalConcept_20(
        concept_id="CONCEPT_20_067",
        loinc_num="30067-4",
        snomed_ct="102000067",
        component="Diagnostic Analyte Component 20-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_068": ClinicalConcept_20(
        concept_id="CONCEPT_20_068",
        loinc_num="30068-5",
        snomed_ct="102000068",
        component="Diagnostic Analyte Component 20-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_069": ClinicalConcept_20(
        concept_id="CONCEPT_20_069",
        loinc_num="30069-6",
        snomed_ct="102000069",
        component="Diagnostic Analyte Component 20-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_070": ClinicalConcept_20(
        concept_id="CONCEPT_20_070",
        loinc_num="30070-7",
        snomed_ct="102000070",
        component="Diagnostic Analyte Component 20-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_071": ClinicalConcept_20(
        concept_id="CONCEPT_20_071",
        loinc_num="30071-8",
        snomed_ct="102000071",
        component="Diagnostic Analyte Component 20-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_072": ClinicalConcept_20(
        concept_id="CONCEPT_20_072",
        loinc_num="30072-0",
        snomed_ct="102000072",
        component="Diagnostic Analyte Component 20-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_073": ClinicalConcept_20(
        concept_id="CONCEPT_20_073",
        loinc_num="30073-1",
        snomed_ct="102000073",
        component="Diagnostic Analyte Component 20-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_074": ClinicalConcept_20(
        concept_id="CONCEPT_20_074",
        loinc_num="30074-2",
        snomed_ct="102000074",
        component="Diagnostic Analyte Component 20-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_075": ClinicalConcept_20(
        concept_id="CONCEPT_20_075",
        loinc_num="30075-3",
        snomed_ct="102000075",
        component="Diagnostic Analyte Component 20-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_076": ClinicalConcept_20(
        concept_id="CONCEPT_20_076",
        loinc_num="30076-4",
        snomed_ct="102000076",
        component="Diagnostic Analyte Component 20-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_077": ClinicalConcept_20(
        concept_id="CONCEPT_20_077",
        loinc_num="30077-5",
        snomed_ct="102000077",
        component="Diagnostic Analyte Component 20-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_078": ClinicalConcept_20(
        concept_id="CONCEPT_20_078",
        loinc_num="30078-6",
        snomed_ct="102000078",
        component="Diagnostic Analyte Component 20-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_079": ClinicalConcept_20(
        concept_id="CONCEPT_20_079",
        loinc_num="30079-7",
        snomed_ct="102000079",
        component="Diagnostic Analyte Component 20-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_080": ClinicalConcept_20(
        concept_id="CONCEPT_20_080",
        loinc_num="30080-8",
        snomed_ct="102000080",
        component="Diagnostic Analyte Component 20-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_081": ClinicalConcept_20(
        concept_id="CONCEPT_20_081",
        loinc_num="30081-0",
        snomed_ct="102000081",
        component="Diagnostic Analyte Component 20-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_082": ClinicalConcept_20(
        concept_id="CONCEPT_20_082",
        loinc_num="30082-1",
        snomed_ct="102000082",
        component="Diagnostic Analyte Component 20-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_083": ClinicalConcept_20(
        concept_id="CONCEPT_20_083",
        loinc_num="30083-2",
        snomed_ct="102000083",
        component="Diagnostic Analyte Component 20-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_084": ClinicalConcept_20(
        concept_id="CONCEPT_20_084",
        loinc_num="30084-3",
        snomed_ct="102000084",
        component="Diagnostic Analyte Component 20-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_085": ClinicalConcept_20(
        concept_id="CONCEPT_20_085",
        loinc_num="30085-4",
        snomed_ct="102000085",
        component="Diagnostic Analyte Component 20-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_086": ClinicalConcept_20(
        concept_id="CONCEPT_20_086",
        loinc_num="30086-5",
        snomed_ct="102000086",
        component="Diagnostic Analyte Component 20-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_087": ClinicalConcept_20(
        concept_id="CONCEPT_20_087",
        loinc_num="30087-6",
        snomed_ct="102000087",
        component="Diagnostic Analyte Component 20-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_088": ClinicalConcept_20(
        concept_id="CONCEPT_20_088",
        loinc_num="30088-7",
        snomed_ct="102000088",
        component="Diagnostic Analyte Component 20-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_089": ClinicalConcept_20(
        concept_id="CONCEPT_20_089",
        loinc_num="30089-8",
        snomed_ct="102000089",
        component="Diagnostic Analyte Component 20-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_090": ClinicalConcept_20(
        concept_id="CONCEPT_20_090",
        loinc_num="30090-0",
        snomed_ct="102000090",
        component="Diagnostic Analyte Component 20-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_091": ClinicalConcept_20(
        concept_id="CONCEPT_20_091",
        loinc_num="30091-1",
        snomed_ct="102000091",
        component="Diagnostic Analyte Component 20-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_092": ClinicalConcept_20(
        concept_id="CONCEPT_20_092",
        loinc_num="30092-2",
        snomed_ct="102000092",
        component="Diagnostic Analyte Component 20-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_093": ClinicalConcept_20(
        concept_id="CONCEPT_20_093",
        loinc_num="30093-3",
        snomed_ct="102000093",
        component="Diagnostic Analyte Component 20-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_094": ClinicalConcept_20(
        concept_id="CONCEPT_20_094",
        loinc_num="30094-4",
        snomed_ct="102000094",
        component="Diagnostic Analyte Component 20-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_095": ClinicalConcept_20(
        concept_id="CONCEPT_20_095",
        loinc_num="30095-5",
        snomed_ct="102000095",
        component="Diagnostic Analyte Component 20-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_096": ClinicalConcept_20(
        concept_id="CONCEPT_20_096",
        loinc_num="30096-6",
        snomed_ct="102000096",
        component="Diagnostic Analyte Component 20-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_097": ClinicalConcept_20(
        concept_id="CONCEPT_20_097",
        loinc_num="30097-7",
        snomed_ct="102000097",
        component="Diagnostic Analyte Component 20-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_098": ClinicalConcept_20(
        concept_id="CONCEPT_20_098",
        loinc_num="30098-8",
        snomed_ct="102000098",
        component="Diagnostic Analyte Component 20-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_099": ClinicalConcept_20(
        concept_id="CONCEPT_20_099",
        loinc_num="30099-0",
        snomed_ct="102000099",
        component="Diagnostic Analyte Component 20-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_100": ClinicalConcept_20(
        concept_id="CONCEPT_20_100",
        loinc_num="30100-1",
        snomed_ct="102000100",
        component="Diagnostic Analyte Component 20-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_101": ClinicalConcept_20(
        concept_id="CONCEPT_20_101",
        loinc_num="30101-2",
        snomed_ct="102000101",
        component="Diagnostic Analyte Component 20-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_102": ClinicalConcept_20(
        concept_id="CONCEPT_20_102",
        loinc_num="30102-3",
        snomed_ct="102000102",
        component="Diagnostic Analyte Component 20-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_103": ClinicalConcept_20(
        concept_id="CONCEPT_20_103",
        loinc_num="30103-4",
        snomed_ct="102000103",
        component="Diagnostic Analyte Component 20-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_104": ClinicalConcept_20(
        concept_id="CONCEPT_20_104",
        loinc_num="30104-5",
        snomed_ct="102000104",
        component="Diagnostic Analyte Component 20-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_105": ClinicalConcept_20(
        concept_id="CONCEPT_20_105",
        loinc_num="30105-6",
        snomed_ct="102000105",
        component="Diagnostic Analyte Component 20-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_106": ClinicalConcept_20(
        concept_id="CONCEPT_20_106",
        loinc_num="30106-7",
        snomed_ct="102000106",
        component="Diagnostic Analyte Component 20-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_107": ClinicalConcept_20(
        concept_id="CONCEPT_20_107",
        loinc_num="30107-8",
        snomed_ct="102000107",
        component="Diagnostic Analyte Component 20-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_108": ClinicalConcept_20(
        concept_id="CONCEPT_20_108",
        loinc_num="30108-0",
        snomed_ct="102000108",
        component="Diagnostic Analyte Component 20-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_109": ClinicalConcept_20(
        concept_id="CONCEPT_20_109",
        loinc_num="30109-1",
        snomed_ct="102000109",
        component="Diagnostic Analyte Component 20-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_110": ClinicalConcept_20(
        concept_id="CONCEPT_20_110",
        loinc_num="30110-2",
        snomed_ct="102000110",
        component="Diagnostic Analyte Component 20-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_111": ClinicalConcept_20(
        concept_id="CONCEPT_20_111",
        loinc_num="30111-3",
        snomed_ct="102000111",
        component="Diagnostic Analyte Component 20-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_112": ClinicalConcept_20(
        concept_id="CONCEPT_20_112",
        loinc_num="30112-4",
        snomed_ct="102000112",
        component="Diagnostic Analyte Component 20-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_113": ClinicalConcept_20(
        concept_id="CONCEPT_20_113",
        loinc_num="30113-5",
        snomed_ct="102000113",
        component="Diagnostic Analyte Component 20-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_114": ClinicalConcept_20(
        concept_id="CONCEPT_20_114",
        loinc_num="30114-6",
        snomed_ct="102000114",
        component="Diagnostic Analyte Component 20-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_115": ClinicalConcept_20(
        concept_id="CONCEPT_20_115",
        loinc_num="30115-7",
        snomed_ct="102000115",
        component="Diagnostic Analyte Component 20-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_116": ClinicalConcept_20(
        concept_id="CONCEPT_20_116",
        loinc_num="30116-8",
        snomed_ct="102000116",
        component="Diagnostic Analyte Component 20-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_117": ClinicalConcept_20(
        concept_id="CONCEPT_20_117",
        loinc_num="30117-0",
        snomed_ct="102000117",
        component="Diagnostic Analyte Component 20-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_118": ClinicalConcept_20(
        concept_id="CONCEPT_20_118",
        loinc_num="30118-1",
        snomed_ct="102000118",
        component="Diagnostic Analyte Component 20-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_119": ClinicalConcept_20(
        concept_id="CONCEPT_20_119",
        loinc_num="30119-2",
        snomed_ct="102000119",
        component="Diagnostic Analyte Component 20-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_120": ClinicalConcept_20(
        concept_id="CONCEPT_20_120",
        loinc_num="30120-3",
        snomed_ct="102000120",
        component="Diagnostic Analyte Component 20-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_121": ClinicalConcept_20(
        concept_id="CONCEPT_20_121",
        loinc_num="30121-4",
        snomed_ct="102000121",
        component="Diagnostic Analyte Component 20-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_122": ClinicalConcept_20(
        concept_id="CONCEPT_20_122",
        loinc_num="30122-5",
        snomed_ct="102000122",
        component="Diagnostic Analyte Component 20-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_123": ClinicalConcept_20(
        concept_id="CONCEPT_20_123",
        loinc_num="30123-6",
        snomed_ct="102000123",
        component="Diagnostic Analyte Component 20-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_124": ClinicalConcept_20(
        concept_id="CONCEPT_20_124",
        loinc_num="30124-7",
        snomed_ct="102000124",
        component="Diagnostic Analyte Component 20-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_125": ClinicalConcept_20(
        concept_id="CONCEPT_20_125",
        loinc_num="30125-8",
        snomed_ct="102000125",
        component="Diagnostic Analyte Component 20-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_126": ClinicalConcept_20(
        concept_id="CONCEPT_20_126",
        loinc_num="30126-0",
        snomed_ct="102000126",
        component="Diagnostic Analyte Component 20-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_127": ClinicalConcept_20(
        concept_id="CONCEPT_20_127",
        loinc_num="30127-1",
        snomed_ct="102000127",
        component="Diagnostic Analyte Component 20-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_128": ClinicalConcept_20(
        concept_id="CONCEPT_20_128",
        loinc_num="30128-2",
        snomed_ct="102000128",
        component="Diagnostic Analyte Component 20-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_129": ClinicalConcept_20(
        concept_id="CONCEPT_20_129",
        loinc_num="30129-3",
        snomed_ct="102000129",
        component="Diagnostic Analyte Component 20-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_130": ClinicalConcept_20(
        concept_id="CONCEPT_20_130",
        loinc_num="30130-4",
        snomed_ct="102000130",
        component="Diagnostic Analyte Component 20-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_131": ClinicalConcept_20(
        concept_id="CONCEPT_20_131",
        loinc_num="30131-5",
        snomed_ct="102000131",
        component="Diagnostic Analyte Component 20-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_132": ClinicalConcept_20(
        concept_id="CONCEPT_20_132",
        loinc_num="30132-6",
        snomed_ct="102000132",
        component="Diagnostic Analyte Component 20-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_133": ClinicalConcept_20(
        concept_id="CONCEPT_20_133",
        loinc_num="30133-7",
        snomed_ct="102000133",
        component="Diagnostic Analyte Component 20-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_134": ClinicalConcept_20(
        concept_id="CONCEPT_20_134",
        loinc_num="30134-8",
        snomed_ct="102000134",
        component="Diagnostic Analyte Component 20-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_135": ClinicalConcept_20(
        concept_id="CONCEPT_20_135",
        loinc_num="30135-0",
        snomed_ct="102000135",
        component="Diagnostic Analyte Component 20-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_136": ClinicalConcept_20(
        concept_id="CONCEPT_20_136",
        loinc_num="30136-1",
        snomed_ct="102000136",
        component="Diagnostic Analyte Component 20-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_137": ClinicalConcept_20(
        concept_id="CONCEPT_20_137",
        loinc_num="30137-2",
        snomed_ct="102000137",
        component="Diagnostic Analyte Component 20-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_138": ClinicalConcept_20(
        concept_id="CONCEPT_20_138",
        loinc_num="30138-3",
        snomed_ct="102000138",
        component="Diagnostic Analyte Component 20-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_139": ClinicalConcept_20(
        concept_id="CONCEPT_20_139",
        loinc_num="30139-4",
        snomed_ct="102000139",
        component="Diagnostic Analyte Component 20-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_140": ClinicalConcept_20(
        concept_id="CONCEPT_20_140",
        loinc_num="30140-5",
        snomed_ct="102000140",
        component="Diagnostic Analyte Component 20-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_141": ClinicalConcept_20(
        concept_id="CONCEPT_20_141",
        loinc_num="30141-6",
        snomed_ct="102000141",
        component="Diagnostic Analyte Component 20-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_142": ClinicalConcept_20(
        concept_id="CONCEPT_20_142",
        loinc_num="30142-7",
        snomed_ct="102000142",
        component="Diagnostic Analyte Component 20-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_143": ClinicalConcept_20(
        concept_id="CONCEPT_20_143",
        loinc_num="30143-8",
        snomed_ct="102000143",
        component="Diagnostic Analyte Component 20-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_144": ClinicalConcept_20(
        concept_id="CONCEPT_20_144",
        loinc_num="30144-0",
        snomed_ct="102000144",
        component="Diagnostic Analyte Component 20-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_145": ClinicalConcept_20(
        concept_id="CONCEPT_20_145",
        loinc_num="30145-1",
        snomed_ct="102000145",
        component="Diagnostic Analyte Component 20-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_146": ClinicalConcept_20(
        concept_id="CONCEPT_20_146",
        loinc_num="30146-2",
        snomed_ct="102000146",
        component="Diagnostic Analyte Component 20-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_147": ClinicalConcept_20(
        concept_id="CONCEPT_20_147",
        loinc_num="30147-3",
        snomed_ct="102000147",
        component="Diagnostic Analyte Component 20-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_148": ClinicalConcept_20(
        concept_id="CONCEPT_20_148",
        loinc_num="30148-4",
        snomed_ct="102000148",
        component="Diagnostic Analyte Component 20-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_149": ClinicalConcept_20(
        concept_id="CONCEPT_20_149",
        loinc_num="30149-5",
        snomed_ct="102000149",
        component="Diagnostic Analyte Component 20-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_150": ClinicalConcept_20(
        concept_id="CONCEPT_20_150",
        loinc_num="30150-6",
        snomed_ct="102000150",
        component="Diagnostic Analyte Component 20-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_151": ClinicalConcept_20(
        concept_id="CONCEPT_20_151",
        loinc_num="30151-7",
        snomed_ct="102000151",
        component="Diagnostic Analyte Component 20-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_152": ClinicalConcept_20(
        concept_id="CONCEPT_20_152",
        loinc_num="30152-8",
        snomed_ct="102000152",
        component="Diagnostic Analyte Component 20-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_153": ClinicalConcept_20(
        concept_id="CONCEPT_20_153",
        loinc_num="30153-0",
        snomed_ct="102000153",
        component="Diagnostic Analyte Component 20-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_154": ClinicalConcept_20(
        concept_id="CONCEPT_20_154",
        loinc_num="30154-1",
        snomed_ct="102000154",
        component="Diagnostic Analyte Component 20-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_155": ClinicalConcept_20(
        concept_id="CONCEPT_20_155",
        loinc_num="30155-2",
        snomed_ct="102000155",
        component="Diagnostic Analyte Component 20-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_156": ClinicalConcept_20(
        concept_id="CONCEPT_20_156",
        loinc_num="30156-3",
        snomed_ct="102000156",
        component="Diagnostic Analyte Component 20-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_157": ClinicalConcept_20(
        concept_id="CONCEPT_20_157",
        loinc_num="30157-4",
        snomed_ct="102000157",
        component="Diagnostic Analyte Component 20-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_158": ClinicalConcept_20(
        concept_id="CONCEPT_20_158",
        loinc_num="30158-5",
        snomed_ct="102000158",
        component="Diagnostic Analyte Component 20-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_159": ClinicalConcept_20(
        concept_id="CONCEPT_20_159",
        loinc_num="30159-6",
        snomed_ct="102000159",
        component="Diagnostic Analyte Component 20-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_160": ClinicalConcept_20(
        concept_id="CONCEPT_20_160",
        loinc_num="30160-7",
        snomed_ct="102000160",
        component="Diagnostic Analyte Component 20-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_161": ClinicalConcept_20(
        concept_id="CONCEPT_20_161",
        loinc_num="30161-8",
        snomed_ct="102000161",
        component="Diagnostic Analyte Component 20-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_162": ClinicalConcept_20(
        concept_id="CONCEPT_20_162",
        loinc_num="30162-0",
        snomed_ct="102000162",
        component="Diagnostic Analyte Component 20-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_163": ClinicalConcept_20(
        concept_id="CONCEPT_20_163",
        loinc_num="30163-1",
        snomed_ct="102000163",
        component="Diagnostic Analyte Component 20-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_164": ClinicalConcept_20(
        concept_id="CONCEPT_20_164",
        loinc_num="30164-2",
        snomed_ct="102000164",
        component="Diagnostic Analyte Component 20-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_165": ClinicalConcept_20(
        concept_id="CONCEPT_20_165",
        loinc_num="30165-3",
        snomed_ct="102000165",
        component="Diagnostic Analyte Component 20-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_166": ClinicalConcept_20(
        concept_id="CONCEPT_20_166",
        loinc_num="30166-4",
        snomed_ct="102000166",
        component="Diagnostic Analyte Component 20-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_167": ClinicalConcept_20(
        concept_id="CONCEPT_20_167",
        loinc_num="30167-5",
        snomed_ct="102000167",
        component="Diagnostic Analyte Component 20-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_168": ClinicalConcept_20(
        concept_id="CONCEPT_20_168",
        loinc_num="30168-6",
        snomed_ct="102000168",
        component="Diagnostic Analyte Component 20-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_169": ClinicalConcept_20(
        concept_id="CONCEPT_20_169",
        loinc_num="30169-7",
        snomed_ct="102000169",
        component="Diagnostic Analyte Component 20-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_170": ClinicalConcept_20(
        concept_id="CONCEPT_20_170",
        loinc_num="30170-8",
        snomed_ct="102000170",
        component="Diagnostic Analyte Component 20-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_171": ClinicalConcept_20(
        concept_id="CONCEPT_20_171",
        loinc_num="30171-0",
        snomed_ct="102000171",
        component="Diagnostic Analyte Component 20-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_172": ClinicalConcept_20(
        concept_id="CONCEPT_20_172",
        loinc_num="30172-1",
        snomed_ct="102000172",
        component="Diagnostic Analyte Component 20-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_173": ClinicalConcept_20(
        concept_id="CONCEPT_20_173",
        loinc_num="30173-2",
        snomed_ct="102000173",
        component="Diagnostic Analyte Component 20-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_174": ClinicalConcept_20(
        concept_id="CONCEPT_20_174",
        loinc_num="30174-3",
        snomed_ct="102000174",
        component="Diagnostic Analyte Component 20-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_175": ClinicalConcept_20(
        concept_id="CONCEPT_20_175",
        loinc_num="30175-4",
        snomed_ct="102000175",
        component="Diagnostic Analyte Component 20-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_176": ClinicalConcept_20(
        concept_id="CONCEPT_20_176",
        loinc_num="30176-5",
        snomed_ct="102000176",
        component="Diagnostic Analyte Component 20-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_177": ClinicalConcept_20(
        concept_id="CONCEPT_20_177",
        loinc_num="30177-6",
        snomed_ct="102000177",
        component="Diagnostic Analyte Component 20-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_178": ClinicalConcept_20(
        concept_id="CONCEPT_20_178",
        loinc_num="30178-7",
        snomed_ct="102000178",
        component="Diagnostic Analyte Component 20-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_179": ClinicalConcept_20(
        concept_id="CONCEPT_20_179",
        loinc_num="30179-8",
        snomed_ct="102000179",
        component="Diagnostic Analyte Component 20-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_180": ClinicalConcept_20(
        concept_id="CONCEPT_20_180",
        loinc_num="30180-0",
        snomed_ct="102000180",
        component="Diagnostic Analyte Component 20-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_181": ClinicalConcept_20(
        concept_id="CONCEPT_20_181",
        loinc_num="30181-1",
        snomed_ct="102000181",
        component="Diagnostic Analyte Component 20-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_182": ClinicalConcept_20(
        concept_id="CONCEPT_20_182",
        loinc_num="30182-2",
        snomed_ct="102000182",
        component="Diagnostic Analyte Component 20-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_183": ClinicalConcept_20(
        concept_id="CONCEPT_20_183",
        loinc_num="30183-3",
        snomed_ct="102000183",
        component="Diagnostic Analyte Component 20-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_184": ClinicalConcept_20(
        concept_id="CONCEPT_20_184",
        loinc_num="30184-4",
        snomed_ct="102000184",
        component="Diagnostic Analyte Component 20-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_185": ClinicalConcept_20(
        concept_id="CONCEPT_20_185",
        loinc_num="30185-5",
        snomed_ct="102000185",
        component="Diagnostic Analyte Component 20-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_186": ClinicalConcept_20(
        concept_id="CONCEPT_20_186",
        loinc_num="30186-6",
        snomed_ct="102000186",
        component="Diagnostic Analyte Component 20-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_187": ClinicalConcept_20(
        concept_id="CONCEPT_20_187",
        loinc_num="30187-7",
        snomed_ct="102000187",
        component="Diagnostic Analyte Component 20-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_188": ClinicalConcept_20(
        concept_id="CONCEPT_20_188",
        loinc_num="30188-8",
        snomed_ct="102000188",
        component="Diagnostic Analyte Component 20-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_189": ClinicalConcept_20(
        concept_id="CONCEPT_20_189",
        loinc_num="30189-0",
        snomed_ct="102000189",
        component="Diagnostic Analyte Component 20-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_190": ClinicalConcept_20(
        concept_id="CONCEPT_20_190",
        loinc_num="30190-1",
        snomed_ct="102000190",
        component="Diagnostic Analyte Component 20-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_191": ClinicalConcept_20(
        concept_id="CONCEPT_20_191",
        loinc_num="30191-2",
        snomed_ct="102000191",
        component="Diagnostic Analyte Component 20-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_192": ClinicalConcept_20(
        concept_id="CONCEPT_20_192",
        loinc_num="30192-3",
        snomed_ct="102000192",
        component="Diagnostic Analyte Component 20-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_193": ClinicalConcept_20(
        concept_id="CONCEPT_20_193",
        loinc_num="30193-4",
        snomed_ct="102000193",
        component="Diagnostic Analyte Component 20-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_194": ClinicalConcept_20(
        concept_id="CONCEPT_20_194",
        loinc_num="30194-5",
        snomed_ct="102000194",
        component="Diagnostic Analyte Component 20-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_195": ClinicalConcept_20(
        concept_id="CONCEPT_20_195",
        loinc_num="30195-6",
        snomed_ct="102000195",
        component="Diagnostic Analyte Component 20-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_196": ClinicalConcept_20(
        concept_id="CONCEPT_20_196",
        loinc_num="30196-7",
        snomed_ct="102000196",
        component="Diagnostic Analyte Component 20-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_197": ClinicalConcept_20(
        concept_id="CONCEPT_20_197",
        loinc_num="30197-8",
        snomed_ct="102000197",
        component="Diagnostic Analyte Component 20-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_198": ClinicalConcept_20(
        concept_id="CONCEPT_20_198",
        loinc_num="30198-0",
        snomed_ct="102000198",
        component="Diagnostic Analyte Component 20-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_20_199": ClinicalConcept_20(
        concept_id="CONCEPT_20_199",
        loinc_num="30199-1",
        snomed_ct="102000199",
        component="Diagnostic Analyte Component 20-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
