"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 04"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_04:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_04 = {
    "CONCEPT_04_001": ClinicalConcept_04(
        concept_id="CONCEPT_04_001",
        loinc_num="14001-1",
        snomed_ct="100400001",
        component="Diagnostic Analyte Component 04-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_002": ClinicalConcept_04(
        concept_id="CONCEPT_04_002",
        loinc_num="14002-2",
        snomed_ct="100400002",
        component="Diagnostic Analyte Component 04-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_003": ClinicalConcept_04(
        concept_id="CONCEPT_04_003",
        loinc_num="14003-3",
        snomed_ct="100400003",
        component="Diagnostic Analyte Component 04-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_004": ClinicalConcept_04(
        concept_id="CONCEPT_04_004",
        loinc_num="14004-4",
        snomed_ct="100400004",
        component="Diagnostic Analyte Component 04-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_005": ClinicalConcept_04(
        concept_id="CONCEPT_04_005",
        loinc_num="14005-5",
        snomed_ct="100400005",
        component="Diagnostic Analyte Component 04-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_006": ClinicalConcept_04(
        concept_id="CONCEPT_04_006",
        loinc_num="14006-6",
        snomed_ct="100400006",
        component="Diagnostic Analyte Component 04-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_007": ClinicalConcept_04(
        concept_id="CONCEPT_04_007",
        loinc_num="14007-7",
        snomed_ct="100400007",
        component="Diagnostic Analyte Component 04-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_008": ClinicalConcept_04(
        concept_id="CONCEPT_04_008",
        loinc_num="14008-8",
        snomed_ct="100400008",
        component="Diagnostic Analyte Component 04-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_009": ClinicalConcept_04(
        concept_id="CONCEPT_04_009",
        loinc_num="14009-0",
        snomed_ct="100400009",
        component="Diagnostic Analyte Component 04-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_010": ClinicalConcept_04(
        concept_id="CONCEPT_04_010",
        loinc_num="14010-1",
        snomed_ct="100400010",
        component="Diagnostic Analyte Component 04-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_011": ClinicalConcept_04(
        concept_id="CONCEPT_04_011",
        loinc_num="14011-2",
        snomed_ct="100400011",
        component="Diagnostic Analyte Component 04-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_012": ClinicalConcept_04(
        concept_id="CONCEPT_04_012",
        loinc_num="14012-3",
        snomed_ct="100400012",
        component="Diagnostic Analyte Component 04-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_013": ClinicalConcept_04(
        concept_id="CONCEPT_04_013",
        loinc_num="14013-4",
        snomed_ct="100400013",
        component="Diagnostic Analyte Component 04-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_014": ClinicalConcept_04(
        concept_id="CONCEPT_04_014",
        loinc_num="14014-5",
        snomed_ct="100400014",
        component="Diagnostic Analyte Component 04-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_015": ClinicalConcept_04(
        concept_id="CONCEPT_04_015",
        loinc_num="14015-6",
        snomed_ct="100400015",
        component="Diagnostic Analyte Component 04-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_016": ClinicalConcept_04(
        concept_id="CONCEPT_04_016",
        loinc_num="14016-7",
        snomed_ct="100400016",
        component="Diagnostic Analyte Component 04-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_017": ClinicalConcept_04(
        concept_id="CONCEPT_04_017",
        loinc_num="14017-8",
        snomed_ct="100400017",
        component="Diagnostic Analyte Component 04-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_018": ClinicalConcept_04(
        concept_id="CONCEPT_04_018",
        loinc_num="14018-0",
        snomed_ct="100400018",
        component="Diagnostic Analyte Component 04-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_019": ClinicalConcept_04(
        concept_id="CONCEPT_04_019",
        loinc_num="14019-1",
        snomed_ct="100400019",
        component="Diagnostic Analyte Component 04-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_020": ClinicalConcept_04(
        concept_id="CONCEPT_04_020",
        loinc_num="14020-2",
        snomed_ct="100400020",
        component="Diagnostic Analyte Component 04-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_021": ClinicalConcept_04(
        concept_id="CONCEPT_04_021",
        loinc_num="14021-3",
        snomed_ct="100400021",
        component="Diagnostic Analyte Component 04-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_022": ClinicalConcept_04(
        concept_id="CONCEPT_04_022",
        loinc_num="14022-4",
        snomed_ct="100400022",
        component="Diagnostic Analyte Component 04-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_023": ClinicalConcept_04(
        concept_id="CONCEPT_04_023",
        loinc_num="14023-5",
        snomed_ct="100400023",
        component="Diagnostic Analyte Component 04-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_024": ClinicalConcept_04(
        concept_id="CONCEPT_04_024",
        loinc_num="14024-6",
        snomed_ct="100400024",
        component="Diagnostic Analyte Component 04-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_025": ClinicalConcept_04(
        concept_id="CONCEPT_04_025",
        loinc_num="14025-7",
        snomed_ct="100400025",
        component="Diagnostic Analyte Component 04-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_026": ClinicalConcept_04(
        concept_id="CONCEPT_04_026",
        loinc_num="14026-8",
        snomed_ct="100400026",
        component="Diagnostic Analyte Component 04-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_027": ClinicalConcept_04(
        concept_id="CONCEPT_04_027",
        loinc_num="14027-0",
        snomed_ct="100400027",
        component="Diagnostic Analyte Component 04-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_028": ClinicalConcept_04(
        concept_id="CONCEPT_04_028",
        loinc_num="14028-1",
        snomed_ct="100400028",
        component="Diagnostic Analyte Component 04-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_029": ClinicalConcept_04(
        concept_id="CONCEPT_04_029",
        loinc_num="14029-2",
        snomed_ct="100400029",
        component="Diagnostic Analyte Component 04-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_030": ClinicalConcept_04(
        concept_id="CONCEPT_04_030",
        loinc_num="14030-3",
        snomed_ct="100400030",
        component="Diagnostic Analyte Component 04-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_031": ClinicalConcept_04(
        concept_id="CONCEPT_04_031",
        loinc_num="14031-4",
        snomed_ct="100400031",
        component="Diagnostic Analyte Component 04-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_032": ClinicalConcept_04(
        concept_id="CONCEPT_04_032",
        loinc_num="14032-5",
        snomed_ct="100400032",
        component="Diagnostic Analyte Component 04-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_033": ClinicalConcept_04(
        concept_id="CONCEPT_04_033",
        loinc_num="14033-6",
        snomed_ct="100400033",
        component="Diagnostic Analyte Component 04-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_034": ClinicalConcept_04(
        concept_id="CONCEPT_04_034",
        loinc_num="14034-7",
        snomed_ct="100400034",
        component="Diagnostic Analyte Component 04-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_035": ClinicalConcept_04(
        concept_id="CONCEPT_04_035",
        loinc_num="14035-8",
        snomed_ct="100400035",
        component="Diagnostic Analyte Component 04-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_036": ClinicalConcept_04(
        concept_id="CONCEPT_04_036",
        loinc_num="14036-0",
        snomed_ct="100400036",
        component="Diagnostic Analyte Component 04-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_037": ClinicalConcept_04(
        concept_id="CONCEPT_04_037",
        loinc_num="14037-1",
        snomed_ct="100400037",
        component="Diagnostic Analyte Component 04-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_038": ClinicalConcept_04(
        concept_id="CONCEPT_04_038",
        loinc_num="14038-2",
        snomed_ct="100400038",
        component="Diagnostic Analyte Component 04-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_039": ClinicalConcept_04(
        concept_id="CONCEPT_04_039",
        loinc_num="14039-3",
        snomed_ct="100400039",
        component="Diagnostic Analyte Component 04-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_040": ClinicalConcept_04(
        concept_id="CONCEPT_04_040",
        loinc_num="14040-4",
        snomed_ct="100400040",
        component="Diagnostic Analyte Component 04-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_041": ClinicalConcept_04(
        concept_id="CONCEPT_04_041",
        loinc_num="14041-5",
        snomed_ct="100400041",
        component="Diagnostic Analyte Component 04-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_042": ClinicalConcept_04(
        concept_id="CONCEPT_04_042",
        loinc_num="14042-6",
        snomed_ct="100400042",
        component="Diagnostic Analyte Component 04-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_043": ClinicalConcept_04(
        concept_id="CONCEPT_04_043",
        loinc_num="14043-7",
        snomed_ct="100400043",
        component="Diagnostic Analyte Component 04-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_044": ClinicalConcept_04(
        concept_id="CONCEPT_04_044",
        loinc_num="14044-8",
        snomed_ct="100400044",
        component="Diagnostic Analyte Component 04-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_045": ClinicalConcept_04(
        concept_id="CONCEPT_04_045",
        loinc_num="14045-0",
        snomed_ct="100400045",
        component="Diagnostic Analyte Component 04-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_046": ClinicalConcept_04(
        concept_id="CONCEPT_04_046",
        loinc_num="14046-1",
        snomed_ct="100400046",
        component="Diagnostic Analyte Component 04-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_047": ClinicalConcept_04(
        concept_id="CONCEPT_04_047",
        loinc_num="14047-2",
        snomed_ct="100400047",
        component="Diagnostic Analyte Component 04-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_048": ClinicalConcept_04(
        concept_id="CONCEPT_04_048",
        loinc_num="14048-3",
        snomed_ct="100400048",
        component="Diagnostic Analyte Component 04-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_049": ClinicalConcept_04(
        concept_id="CONCEPT_04_049",
        loinc_num="14049-4",
        snomed_ct="100400049",
        component="Diagnostic Analyte Component 04-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_050": ClinicalConcept_04(
        concept_id="CONCEPT_04_050",
        loinc_num="14050-5",
        snomed_ct="100400050",
        component="Diagnostic Analyte Component 04-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_051": ClinicalConcept_04(
        concept_id="CONCEPT_04_051",
        loinc_num="14051-6",
        snomed_ct="100400051",
        component="Diagnostic Analyte Component 04-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_052": ClinicalConcept_04(
        concept_id="CONCEPT_04_052",
        loinc_num="14052-7",
        snomed_ct="100400052",
        component="Diagnostic Analyte Component 04-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_053": ClinicalConcept_04(
        concept_id="CONCEPT_04_053",
        loinc_num="14053-8",
        snomed_ct="100400053",
        component="Diagnostic Analyte Component 04-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_054": ClinicalConcept_04(
        concept_id="CONCEPT_04_054",
        loinc_num="14054-0",
        snomed_ct="100400054",
        component="Diagnostic Analyte Component 04-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_055": ClinicalConcept_04(
        concept_id="CONCEPT_04_055",
        loinc_num="14055-1",
        snomed_ct="100400055",
        component="Diagnostic Analyte Component 04-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_056": ClinicalConcept_04(
        concept_id="CONCEPT_04_056",
        loinc_num="14056-2",
        snomed_ct="100400056",
        component="Diagnostic Analyte Component 04-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_057": ClinicalConcept_04(
        concept_id="CONCEPT_04_057",
        loinc_num="14057-3",
        snomed_ct="100400057",
        component="Diagnostic Analyte Component 04-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_058": ClinicalConcept_04(
        concept_id="CONCEPT_04_058",
        loinc_num="14058-4",
        snomed_ct="100400058",
        component="Diagnostic Analyte Component 04-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_059": ClinicalConcept_04(
        concept_id="CONCEPT_04_059",
        loinc_num="14059-5",
        snomed_ct="100400059",
        component="Diagnostic Analyte Component 04-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_060": ClinicalConcept_04(
        concept_id="CONCEPT_04_060",
        loinc_num="14060-6",
        snomed_ct="100400060",
        component="Diagnostic Analyte Component 04-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_061": ClinicalConcept_04(
        concept_id="CONCEPT_04_061",
        loinc_num="14061-7",
        snomed_ct="100400061",
        component="Diagnostic Analyte Component 04-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_062": ClinicalConcept_04(
        concept_id="CONCEPT_04_062",
        loinc_num="14062-8",
        snomed_ct="100400062",
        component="Diagnostic Analyte Component 04-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_063": ClinicalConcept_04(
        concept_id="CONCEPT_04_063",
        loinc_num="14063-0",
        snomed_ct="100400063",
        component="Diagnostic Analyte Component 04-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_064": ClinicalConcept_04(
        concept_id="CONCEPT_04_064",
        loinc_num="14064-1",
        snomed_ct="100400064",
        component="Diagnostic Analyte Component 04-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_065": ClinicalConcept_04(
        concept_id="CONCEPT_04_065",
        loinc_num="14065-2",
        snomed_ct="100400065",
        component="Diagnostic Analyte Component 04-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_066": ClinicalConcept_04(
        concept_id="CONCEPT_04_066",
        loinc_num="14066-3",
        snomed_ct="100400066",
        component="Diagnostic Analyte Component 04-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_067": ClinicalConcept_04(
        concept_id="CONCEPT_04_067",
        loinc_num="14067-4",
        snomed_ct="100400067",
        component="Diagnostic Analyte Component 04-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_068": ClinicalConcept_04(
        concept_id="CONCEPT_04_068",
        loinc_num="14068-5",
        snomed_ct="100400068",
        component="Diagnostic Analyte Component 04-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_069": ClinicalConcept_04(
        concept_id="CONCEPT_04_069",
        loinc_num="14069-6",
        snomed_ct="100400069",
        component="Diagnostic Analyte Component 04-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_070": ClinicalConcept_04(
        concept_id="CONCEPT_04_070",
        loinc_num="14070-7",
        snomed_ct="100400070",
        component="Diagnostic Analyte Component 04-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_071": ClinicalConcept_04(
        concept_id="CONCEPT_04_071",
        loinc_num="14071-8",
        snomed_ct="100400071",
        component="Diagnostic Analyte Component 04-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_072": ClinicalConcept_04(
        concept_id="CONCEPT_04_072",
        loinc_num="14072-0",
        snomed_ct="100400072",
        component="Diagnostic Analyte Component 04-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_073": ClinicalConcept_04(
        concept_id="CONCEPT_04_073",
        loinc_num="14073-1",
        snomed_ct="100400073",
        component="Diagnostic Analyte Component 04-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_074": ClinicalConcept_04(
        concept_id="CONCEPT_04_074",
        loinc_num="14074-2",
        snomed_ct="100400074",
        component="Diagnostic Analyte Component 04-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_075": ClinicalConcept_04(
        concept_id="CONCEPT_04_075",
        loinc_num="14075-3",
        snomed_ct="100400075",
        component="Diagnostic Analyte Component 04-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_076": ClinicalConcept_04(
        concept_id="CONCEPT_04_076",
        loinc_num="14076-4",
        snomed_ct="100400076",
        component="Diagnostic Analyte Component 04-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_077": ClinicalConcept_04(
        concept_id="CONCEPT_04_077",
        loinc_num="14077-5",
        snomed_ct="100400077",
        component="Diagnostic Analyte Component 04-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_078": ClinicalConcept_04(
        concept_id="CONCEPT_04_078",
        loinc_num="14078-6",
        snomed_ct="100400078",
        component="Diagnostic Analyte Component 04-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_079": ClinicalConcept_04(
        concept_id="CONCEPT_04_079",
        loinc_num="14079-7",
        snomed_ct="100400079",
        component="Diagnostic Analyte Component 04-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_080": ClinicalConcept_04(
        concept_id="CONCEPT_04_080",
        loinc_num="14080-8",
        snomed_ct="100400080",
        component="Diagnostic Analyte Component 04-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_081": ClinicalConcept_04(
        concept_id="CONCEPT_04_081",
        loinc_num="14081-0",
        snomed_ct="100400081",
        component="Diagnostic Analyte Component 04-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_082": ClinicalConcept_04(
        concept_id="CONCEPT_04_082",
        loinc_num="14082-1",
        snomed_ct="100400082",
        component="Diagnostic Analyte Component 04-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_083": ClinicalConcept_04(
        concept_id="CONCEPT_04_083",
        loinc_num="14083-2",
        snomed_ct="100400083",
        component="Diagnostic Analyte Component 04-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_084": ClinicalConcept_04(
        concept_id="CONCEPT_04_084",
        loinc_num="14084-3",
        snomed_ct="100400084",
        component="Diagnostic Analyte Component 04-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_085": ClinicalConcept_04(
        concept_id="CONCEPT_04_085",
        loinc_num="14085-4",
        snomed_ct="100400085",
        component="Diagnostic Analyte Component 04-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_086": ClinicalConcept_04(
        concept_id="CONCEPT_04_086",
        loinc_num="14086-5",
        snomed_ct="100400086",
        component="Diagnostic Analyte Component 04-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_087": ClinicalConcept_04(
        concept_id="CONCEPT_04_087",
        loinc_num="14087-6",
        snomed_ct="100400087",
        component="Diagnostic Analyte Component 04-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_088": ClinicalConcept_04(
        concept_id="CONCEPT_04_088",
        loinc_num="14088-7",
        snomed_ct="100400088",
        component="Diagnostic Analyte Component 04-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_089": ClinicalConcept_04(
        concept_id="CONCEPT_04_089",
        loinc_num="14089-8",
        snomed_ct="100400089",
        component="Diagnostic Analyte Component 04-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_090": ClinicalConcept_04(
        concept_id="CONCEPT_04_090",
        loinc_num="14090-0",
        snomed_ct="100400090",
        component="Diagnostic Analyte Component 04-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_091": ClinicalConcept_04(
        concept_id="CONCEPT_04_091",
        loinc_num="14091-1",
        snomed_ct="100400091",
        component="Diagnostic Analyte Component 04-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_092": ClinicalConcept_04(
        concept_id="CONCEPT_04_092",
        loinc_num="14092-2",
        snomed_ct="100400092",
        component="Diagnostic Analyte Component 04-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_093": ClinicalConcept_04(
        concept_id="CONCEPT_04_093",
        loinc_num="14093-3",
        snomed_ct="100400093",
        component="Diagnostic Analyte Component 04-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_094": ClinicalConcept_04(
        concept_id="CONCEPT_04_094",
        loinc_num="14094-4",
        snomed_ct="100400094",
        component="Diagnostic Analyte Component 04-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_095": ClinicalConcept_04(
        concept_id="CONCEPT_04_095",
        loinc_num="14095-5",
        snomed_ct="100400095",
        component="Diagnostic Analyte Component 04-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_096": ClinicalConcept_04(
        concept_id="CONCEPT_04_096",
        loinc_num="14096-6",
        snomed_ct="100400096",
        component="Diagnostic Analyte Component 04-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_097": ClinicalConcept_04(
        concept_id="CONCEPT_04_097",
        loinc_num="14097-7",
        snomed_ct="100400097",
        component="Diagnostic Analyte Component 04-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_098": ClinicalConcept_04(
        concept_id="CONCEPT_04_098",
        loinc_num="14098-8",
        snomed_ct="100400098",
        component="Diagnostic Analyte Component 04-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_099": ClinicalConcept_04(
        concept_id="CONCEPT_04_099",
        loinc_num="14099-0",
        snomed_ct="100400099",
        component="Diagnostic Analyte Component 04-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_100": ClinicalConcept_04(
        concept_id="CONCEPT_04_100",
        loinc_num="14100-1",
        snomed_ct="100400100",
        component="Diagnostic Analyte Component 04-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_101": ClinicalConcept_04(
        concept_id="CONCEPT_04_101",
        loinc_num="14101-2",
        snomed_ct="100400101",
        component="Diagnostic Analyte Component 04-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_102": ClinicalConcept_04(
        concept_id="CONCEPT_04_102",
        loinc_num="14102-3",
        snomed_ct="100400102",
        component="Diagnostic Analyte Component 04-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_103": ClinicalConcept_04(
        concept_id="CONCEPT_04_103",
        loinc_num="14103-4",
        snomed_ct="100400103",
        component="Diagnostic Analyte Component 04-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_104": ClinicalConcept_04(
        concept_id="CONCEPT_04_104",
        loinc_num="14104-5",
        snomed_ct="100400104",
        component="Diagnostic Analyte Component 04-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_105": ClinicalConcept_04(
        concept_id="CONCEPT_04_105",
        loinc_num="14105-6",
        snomed_ct="100400105",
        component="Diagnostic Analyte Component 04-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_106": ClinicalConcept_04(
        concept_id="CONCEPT_04_106",
        loinc_num="14106-7",
        snomed_ct="100400106",
        component="Diagnostic Analyte Component 04-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_107": ClinicalConcept_04(
        concept_id="CONCEPT_04_107",
        loinc_num="14107-8",
        snomed_ct="100400107",
        component="Diagnostic Analyte Component 04-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_108": ClinicalConcept_04(
        concept_id="CONCEPT_04_108",
        loinc_num="14108-0",
        snomed_ct="100400108",
        component="Diagnostic Analyte Component 04-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_109": ClinicalConcept_04(
        concept_id="CONCEPT_04_109",
        loinc_num="14109-1",
        snomed_ct="100400109",
        component="Diagnostic Analyte Component 04-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_110": ClinicalConcept_04(
        concept_id="CONCEPT_04_110",
        loinc_num="14110-2",
        snomed_ct="100400110",
        component="Diagnostic Analyte Component 04-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_111": ClinicalConcept_04(
        concept_id="CONCEPT_04_111",
        loinc_num="14111-3",
        snomed_ct="100400111",
        component="Diagnostic Analyte Component 04-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_112": ClinicalConcept_04(
        concept_id="CONCEPT_04_112",
        loinc_num="14112-4",
        snomed_ct="100400112",
        component="Diagnostic Analyte Component 04-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_113": ClinicalConcept_04(
        concept_id="CONCEPT_04_113",
        loinc_num="14113-5",
        snomed_ct="100400113",
        component="Diagnostic Analyte Component 04-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_114": ClinicalConcept_04(
        concept_id="CONCEPT_04_114",
        loinc_num="14114-6",
        snomed_ct="100400114",
        component="Diagnostic Analyte Component 04-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_115": ClinicalConcept_04(
        concept_id="CONCEPT_04_115",
        loinc_num="14115-7",
        snomed_ct="100400115",
        component="Diagnostic Analyte Component 04-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_116": ClinicalConcept_04(
        concept_id="CONCEPT_04_116",
        loinc_num="14116-8",
        snomed_ct="100400116",
        component="Diagnostic Analyte Component 04-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_117": ClinicalConcept_04(
        concept_id="CONCEPT_04_117",
        loinc_num="14117-0",
        snomed_ct="100400117",
        component="Diagnostic Analyte Component 04-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_118": ClinicalConcept_04(
        concept_id="CONCEPT_04_118",
        loinc_num="14118-1",
        snomed_ct="100400118",
        component="Diagnostic Analyte Component 04-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_119": ClinicalConcept_04(
        concept_id="CONCEPT_04_119",
        loinc_num="14119-2",
        snomed_ct="100400119",
        component="Diagnostic Analyte Component 04-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_120": ClinicalConcept_04(
        concept_id="CONCEPT_04_120",
        loinc_num="14120-3",
        snomed_ct="100400120",
        component="Diagnostic Analyte Component 04-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_121": ClinicalConcept_04(
        concept_id="CONCEPT_04_121",
        loinc_num="14121-4",
        snomed_ct="100400121",
        component="Diagnostic Analyte Component 04-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_122": ClinicalConcept_04(
        concept_id="CONCEPT_04_122",
        loinc_num="14122-5",
        snomed_ct="100400122",
        component="Diagnostic Analyte Component 04-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_123": ClinicalConcept_04(
        concept_id="CONCEPT_04_123",
        loinc_num="14123-6",
        snomed_ct="100400123",
        component="Diagnostic Analyte Component 04-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_124": ClinicalConcept_04(
        concept_id="CONCEPT_04_124",
        loinc_num="14124-7",
        snomed_ct="100400124",
        component="Diagnostic Analyte Component 04-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_125": ClinicalConcept_04(
        concept_id="CONCEPT_04_125",
        loinc_num="14125-8",
        snomed_ct="100400125",
        component="Diagnostic Analyte Component 04-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_126": ClinicalConcept_04(
        concept_id="CONCEPT_04_126",
        loinc_num="14126-0",
        snomed_ct="100400126",
        component="Diagnostic Analyte Component 04-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_127": ClinicalConcept_04(
        concept_id="CONCEPT_04_127",
        loinc_num="14127-1",
        snomed_ct="100400127",
        component="Diagnostic Analyte Component 04-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_128": ClinicalConcept_04(
        concept_id="CONCEPT_04_128",
        loinc_num="14128-2",
        snomed_ct="100400128",
        component="Diagnostic Analyte Component 04-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_129": ClinicalConcept_04(
        concept_id="CONCEPT_04_129",
        loinc_num="14129-3",
        snomed_ct="100400129",
        component="Diagnostic Analyte Component 04-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_130": ClinicalConcept_04(
        concept_id="CONCEPT_04_130",
        loinc_num="14130-4",
        snomed_ct="100400130",
        component="Diagnostic Analyte Component 04-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_131": ClinicalConcept_04(
        concept_id="CONCEPT_04_131",
        loinc_num="14131-5",
        snomed_ct="100400131",
        component="Diagnostic Analyte Component 04-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_132": ClinicalConcept_04(
        concept_id="CONCEPT_04_132",
        loinc_num="14132-6",
        snomed_ct="100400132",
        component="Diagnostic Analyte Component 04-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_133": ClinicalConcept_04(
        concept_id="CONCEPT_04_133",
        loinc_num="14133-7",
        snomed_ct="100400133",
        component="Diagnostic Analyte Component 04-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_134": ClinicalConcept_04(
        concept_id="CONCEPT_04_134",
        loinc_num="14134-8",
        snomed_ct="100400134",
        component="Diagnostic Analyte Component 04-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_135": ClinicalConcept_04(
        concept_id="CONCEPT_04_135",
        loinc_num="14135-0",
        snomed_ct="100400135",
        component="Diagnostic Analyte Component 04-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_136": ClinicalConcept_04(
        concept_id="CONCEPT_04_136",
        loinc_num="14136-1",
        snomed_ct="100400136",
        component="Diagnostic Analyte Component 04-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_137": ClinicalConcept_04(
        concept_id="CONCEPT_04_137",
        loinc_num="14137-2",
        snomed_ct="100400137",
        component="Diagnostic Analyte Component 04-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_138": ClinicalConcept_04(
        concept_id="CONCEPT_04_138",
        loinc_num="14138-3",
        snomed_ct="100400138",
        component="Diagnostic Analyte Component 04-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_139": ClinicalConcept_04(
        concept_id="CONCEPT_04_139",
        loinc_num="14139-4",
        snomed_ct="100400139",
        component="Diagnostic Analyte Component 04-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_140": ClinicalConcept_04(
        concept_id="CONCEPT_04_140",
        loinc_num="14140-5",
        snomed_ct="100400140",
        component="Diagnostic Analyte Component 04-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_141": ClinicalConcept_04(
        concept_id="CONCEPT_04_141",
        loinc_num="14141-6",
        snomed_ct="100400141",
        component="Diagnostic Analyte Component 04-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_142": ClinicalConcept_04(
        concept_id="CONCEPT_04_142",
        loinc_num="14142-7",
        snomed_ct="100400142",
        component="Diagnostic Analyte Component 04-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_143": ClinicalConcept_04(
        concept_id="CONCEPT_04_143",
        loinc_num="14143-8",
        snomed_ct="100400143",
        component="Diagnostic Analyte Component 04-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_144": ClinicalConcept_04(
        concept_id="CONCEPT_04_144",
        loinc_num="14144-0",
        snomed_ct="100400144",
        component="Diagnostic Analyte Component 04-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_145": ClinicalConcept_04(
        concept_id="CONCEPT_04_145",
        loinc_num="14145-1",
        snomed_ct="100400145",
        component="Diagnostic Analyte Component 04-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_146": ClinicalConcept_04(
        concept_id="CONCEPT_04_146",
        loinc_num="14146-2",
        snomed_ct="100400146",
        component="Diagnostic Analyte Component 04-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_147": ClinicalConcept_04(
        concept_id="CONCEPT_04_147",
        loinc_num="14147-3",
        snomed_ct="100400147",
        component="Diagnostic Analyte Component 04-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_148": ClinicalConcept_04(
        concept_id="CONCEPT_04_148",
        loinc_num="14148-4",
        snomed_ct="100400148",
        component="Diagnostic Analyte Component 04-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_149": ClinicalConcept_04(
        concept_id="CONCEPT_04_149",
        loinc_num="14149-5",
        snomed_ct="100400149",
        component="Diagnostic Analyte Component 04-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_150": ClinicalConcept_04(
        concept_id="CONCEPT_04_150",
        loinc_num="14150-6",
        snomed_ct="100400150",
        component="Diagnostic Analyte Component 04-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_151": ClinicalConcept_04(
        concept_id="CONCEPT_04_151",
        loinc_num="14151-7",
        snomed_ct="100400151",
        component="Diagnostic Analyte Component 04-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_152": ClinicalConcept_04(
        concept_id="CONCEPT_04_152",
        loinc_num="14152-8",
        snomed_ct="100400152",
        component="Diagnostic Analyte Component 04-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_153": ClinicalConcept_04(
        concept_id="CONCEPT_04_153",
        loinc_num="14153-0",
        snomed_ct="100400153",
        component="Diagnostic Analyte Component 04-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_154": ClinicalConcept_04(
        concept_id="CONCEPT_04_154",
        loinc_num="14154-1",
        snomed_ct="100400154",
        component="Diagnostic Analyte Component 04-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_155": ClinicalConcept_04(
        concept_id="CONCEPT_04_155",
        loinc_num="14155-2",
        snomed_ct="100400155",
        component="Diagnostic Analyte Component 04-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_156": ClinicalConcept_04(
        concept_id="CONCEPT_04_156",
        loinc_num="14156-3",
        snomed_ct="100400156",
        component="Diagnostic Analyte Component 04-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_157": ClinicalConcept_04(
        concept_id="CONCEPT_04_157",
        loinc_num="14157-4",
        snomed_ct="100400157",
        component="Diagnostic Analyte Component 04-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_158": ClinicalConcept_04(
        concept_id="CONCEPT_04_158",
        loinc_num="14158-5",
        snomed_ct="100400158",
        component="Diagnostic Analyte Component 04-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_159": ClinicalConcept_04(
        concept_id="CONCEPT_04_159",
        loinc_num="14159-6",
        snomed_ct="100400159",
        component="Diagnostic Analyte Component 04-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_160": ClinicalConcept_04(
        concept_id="CONCEPT_04_160",
        loinc_num="14160-7",
        snomed_ct="100400160",
        component="Diagnostic Analyte Component 04-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_161": ClinicalConcept_04(
        concept_id="CONCEPT_04_161",
        loinc_num="14161-8",
        snomed_ct="100400161",
        component="Diagnostic Analyte Component 04-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_162": ClinicalConcept_04(
        concept_id="CONCEPT_04_162",
        loinc_num="14162-0",
        snomed_ct="100400162",
        component="Diagnostic Analyte Component 04-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_163": ClinicalConcept_04(
        concept_id="CONCEPT_04_163",
        loinc_num="14163-1",
        snomed_ct="100400163",
        component="Diagnostic Analyte Component 04-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_164": ClinicalConcept_04(
        concept_id="CONCEPT_04_164",
        loinc_num="14164-2",
        snomed_ct="100400164",
        component="Diagnostic Analyte Component 04-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_165": ClinicalConcept_04(
        concept_id="CONCEPT_04_165",
        loinc_num="14165-3",
        snomed_ct="100400165",
        component="Diagnostic Analyte Component 04-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_166": ClinicalConcept_04(
        concept_id="CONCEPT_04_166",
        loinc_num="14166-4",
        snomed_ct="100400166",
        component="Diagnostic Analyte Component 04-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_167": ClinicalConcept_04(
        concept_id="CONCEPT_04_167",
        loinc_num="14167-5",
        snomed_ct="100400167",
        component="Diagnostic Analyte Component 04-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_168": ClinicalConcept_04(
        concept_id="CONCEPT_04_168",
        loinc_num="14168-6",
        snomed_ct="100400168",
        component="Diagnostic Analyte Component 04-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_169": ClinicalConcept_04(
        concept_id="CONCEPT_04_169",
        loinc_num="14169-7",
        snomed_ct="100400169",
        component="Diagnostic Analyte Component 04-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_170": ClinicalConcept_04(
        concept_id="CONCEPT_04_170",
        loinc_num="14170-8",
        snomed_ct="100400170",
        component="Diagnostic Analyte Component 04-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_171": ClinicalConcept_04(
        concept_id="CONCEPT_04_171",
        loinc_num="14171-0",
        snomed_ct="100400171",
        component="Diagnostic Analyte Component 04-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_172": ClinicalConcept_04(
        concept_id="CONCEPT_04_172",
        loinc_num="14172-1",
        snomed_ct="100400172",
        component="Diagnostic Analyte Component 04-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_173": ClinicalConcept_04(
        concept_id="CONCEPT_04_173",
        loinc_num="14173-2",
        snomed_ct="100400173",
        component="Diagnostic Analyte Component 04-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_174": ClinicalConcept_04(
        concept_id="CONCEPT_04_174",
        loinc_num="14174-3",
        snomed_ct="100400174",
        component="Diagnostic Analyte Component 04-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_175": ClinicalConcept_04(
        concept_id="CONCEPT_04_175",
        loinc_num="14175-4",
        snomed_ct="100400175",
        component="Diagnostic Analyte Component 04-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_176": ClinicalConcept_04(
        concept_id="CONCEPT_04_176",
        loinc_num="14176-5",
        snomed_ct="100400176",
        component="Diagnostic Analyte Component 04-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_177": ClinicalConcept_04(
        concept_id="CONCEPT_04_177",
        loinc_num="14177-6",
        snomed_ct="100400177",
        component="Diagnostic Analyte Component 04-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_178": ClinicalConcept_04(
        concept_id="CONCEPT_04_178",
        loinc_num="14178-7",
        snomed_ct="100400178",
        component="Diagnostic Analyte Component 04-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_179": ClinicalConcept_04(
        concept_id="CONCEPT_04_179",
        loinc_num="14179-8",
        snomed_ct="100400179",
        component="Diagnostic Analyte Component 04-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_180": ClinicalConcept_04(
        concept_id="CONCEPT_04_180",
        loinc_num="14180-0",
        snomed_ct="100400180",
        component="Diagnostic Analyte Component 04-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_181": ClinicalConcept_04(
        concept_id="CONCEPT_04_181",
        loinc_num="14181-1",
        snomed_ct="100400181",
        component="Diagnostic Analyte Component 04-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_182": ClinicalConcept_04(
        concept_id="CONCEPT_04_182",
        loinc_num="14182-2",
        snomed_ct="100400182",
        component="Diagnostic Analyte Component 04-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_183": ClinicalConcept_04(
        concept_id="CONCEPT_04_183",
        loinc_num="14183-3",
        snomed_ct="100400183",
        component="Diagnostic Analyte Component 04-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_184": ClinicalConcept_04(
        concept_id="CONCEPT_04_184",
        loinc_num="14184-4",
        snomed_ct="100400184",
        component="Diagnostic Analyte Component 04-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_185": ClinicalConcept_04(
        concept_id="CONCEPT_04_185",
        loinc_num="14185-5",
        snomed_ct="100400185",
        component="Diagnostic Analyte Component 04-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_186": ClinicalConcept_04(
        concept_id="CONCEPT_04_186",
        loinc_num="14186-6",
        snomed_ct="100400186",
        component="Diagnostic Analyte Component 04-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_187": ClinicalConcept_04(
        concept_id="CONCEPT_04_187",
        loinc_num="14187-7",
        snomed_ct="100400187",
        component="Diagnostic Analyte Component 04-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_188": ClinicalConcept_04(
        concept_id="CONCEPT_04_188",
        loinc_num="14188-8",
        snomed_ct="100400188",
        component="Diagnostic Analyte Component 04-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_189": ClinicalConcept_04(
        concept_id="CONCEPT_04_189",
        loinc_num="14189-0",
        snomed_ct="100400189",
        component="Diagnostic Analyte Component 04-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_190": ClinicalConcept_04(
        concept_id="CONCEPT_04_190",
        loinc_num="14190-1",
        snomed_ct="100400190",
        component="Diagnostic Analyte Component 04-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_191": ClinicalConcept_04(
        concept_id="CONCEPT_04_191",
        loinc_num="14191-2",
        snomed_ct="100400191",
        component="Diagnostic Analyte Component 04-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_192": ClinicalConcept_04(
        concept_id="CONCEPT_04_192",
        loinc_num="14192-3",
        snomed_ct="100400192",
        component="Diagnostic Analyte Component 04-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_193": ClinicalConcept_04(
        concept_id="CONCEPT_04_193",
        loinc_num="14193-4",
        snomed_ct="100400193",
        component="Diagnostic Analyte Component 04-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_194": ClinicalConcept_04(
        concept_id="CONCEPT_04_194",
        loinc_num="14194-5",
        snomed_ct="100400194",
        component="Diagnostic Analyte Component 04-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_195": ClinicalConcept_04(
        concept_id="CONCEPT_04_195",
        loinc_num="14195-6",
        snomed_ct="100400195",
        component="Diagnostic Analyte Component 04-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_196": ClinicalConcept_04(
        concept_id="CONCEPT_04_196",
        loinc_num="14196-7",
        snomed_ct="100400196",
        component="Diagnostic Analyte Component 04-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_197": ClinicalConcept_04(
        concept_id="CONCEPT_04_197",
        loinc_num="14197-8",
        snomed_ct="100400197",
        component="Diagnostic Analyte Component 04-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_198": ClinicalConcept_04(
        concept_id="CONCEPT_04_198",
        loinc_num="14198-0",
        snomed_ct="100400198",
        component="Diagnostic Analyte Component 04-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_04_199": ClinicalConcept_04(
        concept_id="CONCEPT_04_199",
        loinc_num="14199-1",
        snomed_ct="100400199",
        component="Diagnostic Analyte Component 04-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
