"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 14"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_14:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_14 = {
    "CONCEPT_14_001": ClinicalConcept_14(
        concept_id="CONCEPT_14_001",
        loinc_num="24001-1",
        snomed_ct="101400001",
        component="Diagnostic Analyte Component 14-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_002": ClinicalConcept_14(
        concept_id="CONCEPT_14_002",
        loinc_num="24002-2",
        snomed_ct="101400002",
        component="Diagnostic Analyte Component 14-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_003": ClinicalConcept_14(
        concept_id="CONCEPT_14_003",
        loinc_num="24003-3",
        snomed_ct="101400003",
        component="Diagnostic Analyte Component 14-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_004": ClinicalConcept_14(
        concept_id="CONCEPT_14_004",
        loinc_num="24004-4",
        snomed_ct="101400004",
        component="Diagnostic Analyte Component 14-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_005": ClinicalConcept_14(
        concept_id="CONCEPT_14_005",
        loinc_num="24005-5",
        snomed_ct="101400005",
        component="Diagnostic Analyte Component 14-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_006": ClinicalConcept_14(
        concept_id="CONCEPT_14_006",
        loinc_num="24006-6",
        snomed_ct="101400006",
        component="Diagnostic Analyte Component 14-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_007": ClinicalConcept_14(
        concept_id="CONCEPT_14_007",
        loinc_num="24007-7",
        snomed_ct="101400007",
        component="Diagnostic Analyte Component 14-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_008": ClinicalConcept_14(
        concept_id="CONCEPT_14_008",
        loinc_num="24008-8",
        snomed_ct="101400008",
        component="Diagnostic Analyte Component 14-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_009": ClinicalConcept_14(
        concept_id="CONCEPT_14_009",
        loinc_num="24009-0",
        snomed_ct="101400009",
        component="Diagnostic Analyte Component 14-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_010": ClinicalConcept_14(
        concept_id="CONCEPT_14_010",
        loinc_num="24010-1",
        snomed_ct="101400010",
        component="Diagnostic Analyte Component 14-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_011": ClinicalConcept_14(
        concept_id="CONCEPT_14_011",
        loinc_num="24011-2",
        snomed_ct="101400011",
        component="Diagnostic Analyte Component 14-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_012": ClinicalConcept_14(
        concept_id="CONCEPT_14_012",
        loinc_num="24012-3",
        snomed_ct="101400012",
        component="Diagnostic Analyte Component 14-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_013": ClinicalConcept_14(
        concept_id="CONCEPT_14_013",
        loinc_num="24013-4",
        snomed_ct="101400013",
        component="Diagnostic Analyte Component 14-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_014": ClinicalConcept_14(
        concept_id="CONCEPT_14_014",
        loinc_num="24014-5",
        snomed_ct="101400014",
        component="Diagnostic Analyte Component 14-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_015": ClinicalConcept_14(
        concept_id="CONCEPT_14_015",
        loinc_num="24015-6",
        snomed_ct="101400015",
        component="Diagnostic Analyte Component 14-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_016": ClinicalConcept_14(
        concept_id="CONCEPT_14_016",
        loinc_num="24016-7",
        snomed_ct="101400016",
        component="Diagnostic Analyte Component 14-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_017": ClinicalConcept_14(
        concept_id="CONCEPT_14_017",
        loinc_num="24017-8",
        snomed_ct="101400017",
        component="Diagnostic Analyte Component 14-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_018": ClinicalConcept_14(
        concept_id="CONCEPT_14_018",
        loinc_num="24018-0",
        snomed_ct="101400018",
        component="Diagnostic Analyte Component 14-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_019": ClinicalConcept_14(
        concept_id="CONCEPT_14_019",
        loinc_num="24019-1",
        snomed_ct="101400019",
        component="Diagnostic Analyte Component 14-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_020": ClinicalConcept_14(
        concept_id="CONCEPT_14_020",
        loinc_num="24020-2",
        snomed_ct="101400020",
        component="Diagnostic Analyte Component 14-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_021": ClinicalConcept_14(
        concept_id="CONCEPT_14_021",
        loinc_num="24021-3",
        snomed_ct="101400021",
        component="Diagnostic Analyte Component 14-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_022": ClinicalConcept_14(
        concept_id="CONCEPT_14_022",
        loinc_num="24022-4",
        snomed_ct="101400022",
        component="Diagnostic Analyte Component 14-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_023": ClinicalConcept_14(
        concept_id="CONCEPT_14_023",
        loinc_num="24023-5",
        snomed_ct="101400023",
        component="Diagnostic Analyte Component 14-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_024": ClinicalConcept_14(
        concept_id="CONCEPT_14_024",
        loinc_num="24024-6",
        snomed_ct="101400024",
        component="Diagnostic Analyte Component 14-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_025": ClinicalConcept_14(
        concept_id="CONCEPT_14_025",
        loinc_num="24025-7",
        snomed_ct="101400025",
        component="Diagnostic Analyte Component 14-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_026": ClinicalConcept_14(
        concept_id="CONCEPT_14_026",
        loinc_num="24026-8",
        snomed_ct="101400026",
        component="Diagnostic Analyte Component 14-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_027": ClinicalConcept_14(
        concept_id="CONCEPT_14_027",
        loinc_num="24027-0",
        snomed_ct="101400027",
        component="Diagnostic Analyte Component 14-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_028": ClinicalConcept_14(
        concept_id="CONCEPT_14_028",
        loinc_num="24028-1",
        snomed_ct="101400028",
        component="Diagnostic Analyte Component 14-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_029": ClinicalConcept_14(
        concept_id="CONCEPT_14_029",
        loinc_num="24029-2",
        snomed_ct="101400029",
        component="Diagnostic Analyte Component 14-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_030": ClinicalConcept_14(
        concept_id="CONCEPT_14_030",
        loinc_num="24030-3",
        snomed_ct="101400030",
        component="Diagnostic Analyte Component 14-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_031": ClinicalConcept_14(
        concept_id="CONCEPT_14_031",
        loinc_num="24031-4",
        snomed_ct="101400031",
        component="Diagnostic Analyte Component 14-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_032": ClinicalConcept_14(
        concept_id="CONCEPT_14_032",
        loinc_num="24032-5",
        snomed_ct="101400032",
        component="Diagnostic Analyte Component 14-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_033": ClinicalConcept_14(
        concept_id="CONCEPT_14_033",
        loinc_num="24033-6",
        snomed_ct="101400033",
        component="Diagnostic Analyte Component 14-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_034": ClinicalConcept_14(
        concept_id="CONCEPT_14_034",
        loinc_num="24034-7",
        snomed_ct="101400034",
        component="Diagnostic Analyte Component 14-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_035": ClinicalConcept_14(
        concept_id="CONCEPT_14_035",
        loinc_num="24035-8",
        snomed_ct="101400035",
        component="Diagnostic Analyte Component 14-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_036": ClinicalConcept_14(
        concept_id="CONCEPT_14_036",
        loinc_num="24036-0",
        snomed_ct="101400036",
        component="Diagnostic Analyte Component 14-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_037": ClinicalConcept_14(
        concept_id="CONCEPT_14_037",
        loinc_num="24037-1",
        snomed_ct="101400037",
        component="Diagnostic Analyte Component 14-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_038": ClinicalConcept_14(
        concept_id="CONCEPT_14_038",
        loinc_num="24038-2",
        snomed_ct="101400038",
        component="Diagnostic Analyte Component 14-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_039": ClinicalConcept_14(
        concept_id="CONCEPT_14_039",
        loinc_num="24039-3",
        snomed_ct="101400039",
        component="Diagnostic Analyte Component 14-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_040": ClinicalConcept_14(
        concept_id="CONCEPT_14_040",
        loinc_num="24040-4",
        snomed_ct="101400040",
        component="Diagnostic Analyte Component 14-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_041": ClinicalConcept_14(
        concept_id="CONCEPT_14_041",
        loinc_num="24041-5",
        snomed_ct="101400041",
        component="Diagnostic Analyte Component 14-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_042": ClinicalConcept_14(
        concept_id="CONCEPT_14_042",
        loinc_num="24042-6",
        snomed_ct="101400042",
        component="Diagnostic Analyte Component 14-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_043": ClinicalConcept_14(
        concept_id="CONCEPT_14_043",
        loinc_num="24043-7",
        snomed_ct="101400043",
        component="Diagnostic Analyte Component 14-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_044": ClinicalConcept_14(
        concept_id="CONCEPT_14_044",
        loinc_num="24044-8",
        snomed_ct="101400044",
        component="Diagnostic Analyte Component 14-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_045": ClinicalConcept_14(
        concept_id="CONCEPT_14_045",
        loinc_num="24045-0",
        snomed_ct="101400045",
        component="Diagnostic Analyte Component 14-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_046": ClinicalConcept_14(
        concept_id="CONCEPT_14_046",
        loinc_num="24046-1",
        snomed_ct="101400046",
        component="Diagnostic Analyte Component 14-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_047": ClinicalConcept_14(
        concept_id="CONCEPT_14_047",
        loinc_num="24047-2",
        snomed_ct="101400047",
        component="Diagnostic Analyte Component 14-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_048": ClinicalConcept_14(
        concept_id="CONCEPT_14_048",
        loinc_num="24048-3",
        snomed_ct="101400048",
        component="Diagnostic Analyte Component 14-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_049": ClinicalConcept_14(
        concept_id="CONCEPT_14_049",
        loinc_num="24049-4",
        snomed_ct="101400049",
        component="Diagnostic Analyte Component 14-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_050": ClinicalConcept_14(
        concept_id="CONCEPT_14_050",
        loinc_num="24050-5",
        snomed_ct="101400050",
        component="Diagnostic Analyte Component 14-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_051": ClinicalConcept_14(
        concept_id="CONCEPT_14_051",
        loinc_num="24051-6",
        snomed_ct="101400051",
        component="Diagnostic Analyte Component 14-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_052": ClinicalConcept_14(
        concept_id="CONCEPT_14_052",
        loinc_num="24052-7",
        snomed_ct="101400052",
        component="Diagnostic Analyte Component 14-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_053": ClinicalConcept_14(
        concept_id="CONCEPT_14_053",
        loinc_num="24053-8",
        snomed_ct="101400053",
        component="Diagnostic Analyte Component 14-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_054": ClinicalConcept_14(
        concept_id="CONCEPT_14_054",
        loinc_num="24054-0",
        snomed_ct="101400054",
        component="Diagnostic Analyte Component 14-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_055": ClinicalConcept_14(
        concept_id="CONCEPT_14_055",
        loinc_num="24055-1",
        snomed_ct="101400055",
        component="Diagnostic Analyte Component 14-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_056": ClinicalConcept_14(
        concept_id="CONCEPT_14_056",
        loinc_num="24056-2",
        snomed_ct="101400056",
        component="Diagnostic Analyte Component 14-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_057": ClinicalConcept_14(
        concept_id="CONCEPT_14_057",
        loinc_num="24057-3",
        snomed_ct="101400057",
        component="Diagnostic Analyte Component 14-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_058": ClinicalConcept_14(
        concept_id="CONCEPT_14_058",
        loinc_num="24058-4",
        snomed_ct="101400058",
        component="Diagnostic Analyte Component 14-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_059": ClinicalConcept_14(
        concept_id="CONCEPT_14_059",
        loinc_num="24059-5",
        snomed_ct="101400059",
        component="Diagnostic Analyte Component 14-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_060": ClinicalConcept_14(
        concept_id="CONCEPT_14_060",
        loinc_num="24060-6",
        snomed_ct="101400060",
        component="Diagnostic Analyte Component 14-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_061": ClinicalConcept_14(
        concept_id="CONCEPT_14_061",
        loinc_num="24061-7",
        snomed_ct="101400061",
        component="Diagnostic Analyte Component 14-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_062": ClinicalConcept_14(
        concept_id="CONCEPT_14_062",
        loinc_num="24062-8",
        snomed_ct="101400062",
        component="Diagnostic Analyte Component 14-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_063": ClinicalConcept_14(
        concept_id="CONCEPT_14_063",
        loinc_num="24063-0",
        snomed_ct="101400063",
        component="Diagnostic Analyte Component 14-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_064": ClinicalConcept_14(
        concept_id="CONCEPT_14_064",
        loinc_num="24064-1",
        snomed_ct="101400064",
        component="Diagnostic Analyte Component 14-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_065": ClinicalConcept_14(
        concept_id="CONCEPT_14_065",
        loinc_num="24065-2",
        snomed_ct="101400065",
        component="Diagnostic Analyte Component 14-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_066": ClinicalConcept_14(
        concept_id="CONCEPT_14_066",
        loinc_num="24066-3",
        snomed_ct="101400066",
        component="Diagnostic Analyte Component 14-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_067": ClinicalConcept_14(
        concept_id="CONCEPT_14_067",
        loinc_num="24067-4",
        snomed_ct="101400067",
        component="Diagnostic Analyte Component 14-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_068": ClinicalConcept_14(
        concept_id="CONCEPT_14_068",
        loinc_num="24068-5",
        snomed_ct="101400068",
        component="Diagnostic Analyte Component 14-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_069": ClinicalConcept_14(
        concept_id="CONCEPT_14_069",
        loinc_num="24069-6",
        snomed_ct="101400069",
        component="Diagnostic Analyte Component 14-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_070": ClinicalConcept_14(
        concept_id="CONCEPT_14_070",
        loinc_num="24070-7",
        snomed_ct="101400070",
        component="Diagnostic Analyte Component 14-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_071": ClinicalConcept_14(
        concept_id="CONCEPT_14_071",
        loinc_num="24071-8",
        snomed_ct="101400071",
        component="Diagnostic Analyte Component 14-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_072": ClinicalConcept_14(
        concept_id="CONCEPT_14_072",
        loinc_num="24072-0",
        snomed_ct="101400072",
        component="Diagnostic Analyte Component 14-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_073": ClinicalConcept_14(
        concept_id="CONCEPT_14_073",
        loinc_num="24073-1",
        snomed_ct="101400073",
        component="Diagnostic Analyte Component 14-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_074": ClinicalConcept_14(
        concept_id="CONCEPT_14_074",
        loinc_num="24074-2",
        snomed_ct="101400074",
        component="Diagnostic Analyte Component 14-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_075": ClinicalConcept_14(
        concept_id="CONCEPT_14_075",
        loinc_num="24075-3",
        snomed_ct="101400075",
        component="Diagnostic Analyte Component 14-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_076": ClinicalConcept_14(
        concept_id="CONCEPT_14_076",
        loinc_num="24076-4",
        snomed_ct="101400076",
        component="Diagnostic Analyte Component 14-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_077": ClinicalConcept_14(
        concept_id="CONCEPT_14_077",
        loinc_num="24077-5",
        snomed_ct="101400077",
        component="Diagnostic Analyte Component 14-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_078": ClinicalConcept_14(
        concept_id="CONCEPT_14_078",
        loinc_num="24078-6",
        snomed_ct="101400078",
        component="Diagnostic Analyte Component 14-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_079": ClinicalConcept_14(
        concept_id="CONCEPT_14_079",
        loinc_num="24079-7",
        snomed_ct="101400079",
        component="Diagnostic Analyte Component 14-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_080": ClinicalConcept_14(
        concept_id="CONCEPT_14_080",
        loinc_num="24080-8",
        snomed_ct="101400080",
        component="Diagnostic Analyte Component 14-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_081": ClinicalConcept_14(
        concept_id="CONCEPT_14_081",
        loinc_num="24081-0",
        snomed_ct="101400081",
        component="Diagnostic Analyte Component 14-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_082": ClinicalConcept_14(
        concept_id="CONCEPT_14_082",
        loinc_num="24082-1",
        snomed_ct="101400082",
        component="Diagnostic Analyte Component 14-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_083": ClinicalConcept_14(
        concept_id="CONCEPT_14_083",
        loinc_num="24083-2",
        snomed_ct="101400083",
        component="Diagnostic Analyte Component 14-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_084": ClinicalConcept_14(
        concept_id="CONCEPT_14_084",
        loinc_num="24084-3",
        snomed_ct="101400084",
        component="Diagnostic Analyte Component 14-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_085": ClinicalConcept_14(
        concept_id="CONCEPT_14_085",
        loinc_num="24085-4",
        snomed_ct="101400085",
        component="Diagnostic Analyte Component 14-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_086": ClinicalConcept_14(
        concept_id="CONCEPT_14_086",
        loinc_num="24086-5",
        snomed_ct="101400086",
        component="Diagnostic Analyte Component 14-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_087": ClinicalConcept_14(
        concept_id="CONCEPT_14_087",
        loinc_num="24087-6",
        snomed_ct="101400087",
        component="Diagnostic Analyte Component 14-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_088": ClinicalConcept_14(
        concept_id="CONCEPT_14_088",
        loinc_num="24088-7",
        snomed_ct="101400088",
        component="Diagnostic Analyte Component 14-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_089": ClinicalConcept_14(
        concept_id="CONCEPT_14_089",
        loinc_num="24089-8",
        snomed_ct="101400089",
        component="Diagnostic Analyte Component 14-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_090": ClinicalConcept_14(
        concept_id="CONCEPT_14_090",
        loinc_num="24090-0",
        snomed_ct="101400090",
        component="Diagnostic Analyte Component 14-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_091": ClinicalConcept_14(
        concept_id="CONCEPT_14_091",
        loinc_num="24091-1",
        snomed_ct="101400091",
        component="Diagnostic Analyte Component 14-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_092": ClinicalConcept_14(
        concept_id="CONCEPT_14_092",
        loinc_num="24092-2",
        snomed_ct="101400092",
        component="Diagnostic Analyte Component 14-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_093": ClinicalConcept_14(
        concept_id="CONCEPT_14_093",
        loinc_num="24093-3",
        snomed_ct="101400093",
        component="Diagnostic Analyte Component 14-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_094": ClinicalConcept_14(
        concept_id="CONCEPT_14_094",
        loinc_num="24094-4",
        snomed_ct="101400094",
        component="Diagnostic Analyte Component 14-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_095": ClinicalConcept_14(
        concept_id="CONCEPT_14_095",
        loinc_num="24095-5",
        snomed_ct="101400095",
        component="Diagnostic Analyte Component 14-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_096": ClinicalConcept_14(
        concept_id="CONCEPT_14_096",
        loinc_num="24096-6",
        snomed_ct="101400096",
        component="Diagnostic Analyte Component 14-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_097": ClinicalConcept_14(
        concept_id="CONCEPT_14_097",
        loinc_num="24097-7",
        snomed_ct="101400097",
        component="Diagnostic Analyte Component 14-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_098": ClinicalConcept_14(
        concept_id="CONCEPT_14_098",
        loinc_num="24098-8",
        snomed_ct="101400098",
        component="Diagnostic Analyte Component 14-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_099": ClinicalConcept_14(
        concept_id="CONCEPT_14_099",
        loinc_num="24099-0",
        snomed_ct="101400099",
        component="Diagnostic Analyte Component 14-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_100": ClinicalConcept_14(
        concept_id="CONCEPT_14_100",
        loinc_num="24100-1",
        snomed_ct="101400100",
        component="Diagnostic Analyte Component 14-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_101": ClinicalConcept_14(
        concept_id="CONCEPT_14_101",
        loinc_num="24101-2",
        snomed_ct="101400101",
        component="Diagnostic Analyte Component 14-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_102": ClinicalConcept_14(
        concept_id="CONCEPT_14_102",
        loinc_num="24102-3",
        snomed_ct="101400102",
        component="Diagnostic Analyte Component 14-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_103": ClinicalConcept_14(
        concept_id="CONCEPT_14_103",
        loinc_num="24103-4",
        snomed_ct="101400103",
        component="Diagnostic Analyte Component 14-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_104": ClinicalConcept_14(
        concept_id="CONCEPT_14_104",
        loinc_num="24104-5",
        snomed_ct="101400104",
        component="Diagnostic Analyte Component 14-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_105": ClinicalConcept_14(
        concept_id="CONCEPT_14_105",
        loinc_num="24105-6",
        snomed_ct="101400105",
        component="Diagnostic Analyte Component 14-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_106": ClinicalConcept_14(
        concept_id="CONCEPT_14_106",
        loinc_num="24106-7",
        snomed_ct="101400106",
        component="Diagnostic Analyte Component 14-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_107": ClinicalConcept_14(
        concept_id="CONCEPT_14_107",
        loinc_num="24107-8",
        snomed_ct="101400107",
        component="Diagnostic Analyte Component 14-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_108": ClinicalConcept_14(
        concept_id="CONCEPT_14_108",
        loinc_num="24108-0",
        snomed_ct="101400108",
        component="Diagnostic Analyte Component 14-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_109": ClinicalConcept_14(
        concept_id="CONCEPT_14_109",
        loinc_num="24109-1",
        snomed_ct="101400109",
        component="Diagnostic Analyte Component 14-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_110": ClinicalConcept_14(
        concept_id="CONCEPT_14_110",
        loinc_num="24110-2",
        snomed_ct="101400110",
        component="Diagnostic Analyte Component 14-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_111": ClinicalConcept_14(
        concept_id="CONCEPT_14_111",
        loinc_num="24111-3",
        snomed_ct="101400111",
        component="Diagnostic Analyte Component 14-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_112": ClinicalConcept_14(
        concept_id="CONCEPT_14_112",
        loinc_num="24112-4",
        snomed_ct="101400112",
        component="Diagnostic Analyte Component 14-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_113": ClinicalConcept_14(
        concept_id="CONCEPT_14_113",
        loinc_num="24113-5",
        snomed_ct="101400113",
        component="Diagnostic Analyte Component 14-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_114": ClinicalConcept_14(
        concept_id="CONCEPT_14_114",
        loinc_num="24114-6",
        snomed_ct="101400114",
        component="Diagnostic Analyte Component 14-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_115": ClinicalConcept_14(
        concept_id="CONCEPT_14_115",
        loinc_num="24115-7",
        snomed_ct="101400115",
        component="Diagnostic Analyte Component 14-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_116": ClinicalConcept_14(
        concept_id="CONCEPT_14_116",
        loinc_num="24116-8",
        snomed_ct="101400116",
        component="Diagnostic Analyte Component 14-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_117": ClinicalConcept_14(
        concept_id="CONCEPT_14_117",
        loinc_num="24117-0",
        snomed_ct="101400117",
        component="Diagnostic Analyte Component 14-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_118": ClinicalConcept_14(
        concept_id="CONCEPT_14_118",
        loinc_num="24118-1",
        snomed_ct="101400118",
        component="Diagnostic Analyte Component 14-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_119": ClinicalConcept_14(
        concept_id="CONCEPT_14_119",
        loinc_num="24119-2",
        snomed_ct="101400119",
        component="Diagnostic Analyte Component 14-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_120": ClinicalConcept_14(
        concept_id="CONCEPT_14_120",
        loinc_num="24120-3",
        snomed_ct="101400120",
        component="Diagnostic Analyte Component 14-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_121": ClinicalConcept_14(
        concept_id="CONCEPT_14_121",
        loinc_num="24121-4",
        snomed_ct="101400121",
        component="Diagnostic Analyte Component 14-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_122": ClinicalConcept_14(
        concept_id="CONCEPT_14_122",
        loinc_num="24122-5",
        snomed_ct="101400122",
        component="Diagnostic Analyte Component 14-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_123": ClinicalConcept_14(
        concept_id="CONCEPT_14_123",
        loinc_num="24123-6",
        snomed_ct="101400123",
        component="Diagnostic Analyte Component 14-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_124": ClinicalConcept_14(
        concept_id="CONCEPT_14_124",
        loinc_num="24124-7",
        snomed_ct="101400124",
        component="Diagnostic Analyte Component 14-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_125": ClinicalConcept_14(
        concept_id="CONCEPT_14_125",
        loinc_num="24125-8",
        snomed_ct="101400125",
        component="Diagnostic Analyte Component 14-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_126": ClinicalConcept_14(
        concept_id="CONCEPT_14_126",
        loinc_num="24126-0",
        snomed_ct="101400126",
        component="Diagnostic Analyte Component 14-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_127": ClinicalConcept_14(
        concept_id="CONCEPT_14_127",
        loinc_num="24127-1",
        snomed_ct="101400127",
        component="Diagnostic Analyte Component 14-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_128": ClinicalConcept_14(
        concept_id="CONCEPT_14_128",
        loinc_num="24128-2",
        snomed_ct="101400128",
        component="Diagnostic Analyte Component 14-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_129": ClinicalConcept_14(
        concept_id="CONCEPT_14_129",
        loinc_num="24129-3",
        snomed_ct="101400129",
        component="Diagnostic Analyte Component 14-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_130": ClinicalConcept_14(
        concept_id="CONCEPT_14_130",
        loinc_num="24130-4",
        snomed_ct="101400130",
        component="Diagnostic Analyte Component 14-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_131": ClinicalConcept_14(
        concept_id="CONCEPT_14_131",
        loinc_num="24131-5",
        snomed_ct="101400131",
        component="Diagnostic Analyte Component 14-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_132": ClinicalConcept_14(
        concept_id="CONCEPT_14_132",
        loinc_num="24132-6",
        snomed_ct="101400132",
        component="Diagnostic Analyte Component 14-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_133": ClinicalConcept_14(
        concept_id="CONCEPT_14_133",
        loinc_num="24133-7",
        snomed_ct="101400133",
        component="Diagnostic Analyte Component 14-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_134": ClinicalConcept_14(
        concept_id="CONCEPT_14_134",
        loinc_num="24134-8",
        snomed_ct="101400134",
        component="Diagnostic Analyte Component 14-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_135": ClinicalConcept_14(
        concept_id="CONCEPT_14_135",
        loinc_num="24135-0",
        snomed_ct="101400135",
        component="Diagnostic Analyte Component 14-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_136": ClinicalConcept_14(
        concept_id="CONCEPT_14_136",
        loinc_num="24136-1",
        snomed_ct="101400136",
        component="Diagnostic Analyte Component 14-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_137": ClinicalConcept_14(
        concept_id="CONCEPT_14_137",
        loinc_num="24137-2",
        snomed_ct="101400137",
        component="Diagnostic Analyte Component 14-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_138": ClinicalConcept_14(
        concept_id="CONCEPT_14_138",
        loinc_num="24138-3",
        snomed_ct="101400138",
        component="Diagnostic Analyte Component 14-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_139": ClinicalConcept_14(
        concept_id="CONCEPT_14_139",
        loinc_num="24139-4",
        snomed_ct="101400139",
        component="Diagnostic Analyte Component 14-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_140": ClinicalConcept_14(
        concept_id="CONCEPT_14_140",
        loinc_num="24140-5",
        snomed_ct="101400140",
        component="Diagnostic Analyte Component 14-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_141": ClinicalConcept_14(
        concept_id="CONCEPT_14_141",
        loinc_num="24141-6",
        snomed_ct="101400141",
        component="Diagnostic Analyte Component 14-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_142": ClinicalConcept_14(
        concept_id="CONCEPT_14_142",
        loinc_num="24142-7",
        snomed_ct="101400142",
        component="Diagnostic Analyte Component 14-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_143": ClinicalConcept_14(
        concept_id="CONCEPT_14_143",
        loinc_num="24143-8",
        snomed_ct="101400143",
        component="Diagnostic Analyte Component 14-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_144": ClinicalConcept_14(
        concept_id="CONCEPT_14_144",
        loinc_num="24144-0",
        snomed_ct="101400144",
        component="Diagnostic Analyte Component 14-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_145": ClinicalConcept_14(
        concept_id="CONCEPT_14_145",
        loinc_num="24145-1",
        snomed_ct="101400145",
        component="Diagnostic Analyte Component 14-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_146": ClinicalConcept_14(
        concept_id="CONCEPT_14_146",
        loinc_num="24146-2",
        snomed_ct="101400146",
        component="Diagnostic Analyte Component 14-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_147": ClinicalConcept_14(
        concept_id="CONCEPT_14_147",
        loinc_num="24147-3",
        snomed_ct="101400147",
        component="Diagnostic Analyte Component 14-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_148": ClinicalConcept_14(
        concept_id="CONCEPT_14_148",
        loinc_num="24148-4",
        snomed_ct="101400148",
        component="Diagnostic Analyte Component 14-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_149": ClinicalConcept_14(
        concept_id="CONCEPT_14_149",
        loinc_num="24149-5",
        snomed_ct="101400149",
        component="Diagnostic Analyte Component 14-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_150": ClinicalConcept_14(
        concept_id="CONCEPT_14_150",
        loinc_num="24150-6",
        snomed_ct="101400150",
        component="Diagnostic Analyte Component 14-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_151": ClinicalConcept_14(
        concept_id="CONCEPT_14_151",
        loinc_num="24151-7",
        snomed_ct="101400151",
        component="Diagnostic Analyte Component 14-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_152": ClinicalConcept_14(
        concept_id="CONCEPT_14_152",
        loinc_num="24152-8",
        snomed_ct="101400152",
        component="Diagnostic Analyte Component 14-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_153": ClinicalConcept_14(
        concept_id="CONCEPT_14_153",
        loinc_num="24153-0",
        snomed_ct="101400153",
        component="Diagnostic Analyte Component 14-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_154": ClinicalConcept_14(
        concept_id="CONCEPT_14_154",
        loinc_num="24154-1",
        snomed_ct="101400154",
        component="Diagnostic Analyte Component 14-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_155": ClinicalConcept_14(
        concept_id="CONCEPT_14_155",
        loinc_num="24155-2",
        snomed_ct="101400155",
        component="Diagnostic Analyte Component 14-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_156": ClinicalConcept_14(
        concept_id="CONCEPT_14_156",
        loinc_num="24156-3",
        snomed_ct="101400156",
        component="Diagnostic Analyte Component 14-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_157": ClinicalConcept_14(
        concept_id="CONCEPT_14_157",
        loinc_num="24157-4",
        snomed_ct="101400157",
        component="Diagnostic Analyte Component 14-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_158": ClinicalConcept_14(
        concept_id="CONCEPT_14_158",
        loinc_num="24158-5",
        snomed_ct="101400158",
        component="Diagnostic Analyte Component 14-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_159": ClinicalConcept_14(
        concept_id="CONCEPT_14_159",
        loinc_num="24159-6",
        snomed_ct="101400159",
        component="Diagnostic Analyte Component 14-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_160": ClinicalConcept_14(
        concept_id="CONCEPT_14_160",
        loinc_num="24160-7",
        snomed_ct="101400160",
        component="Diagnostic Analyte Component 14-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_161": ClinicalConcept_14(
        concept_id="CONCEPT_14_161",
        loinc_num="24161-8",
        snomed_ct="101400161",
        component="Diagnostic Analyte Component 14-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_162": ClinicalConcept_14(
        concept_id="CONCEPT_14_162",
        loinc_num="24162-0",
        snomed_ct="101400162",
        component="Diagnostic Analyte Component 14-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_163": ClinicalConcept_14(
        concept_id="CONCEPT_14_163",
        loinc_num="24163-1",
        snomed_ct="101400163",
        component="Diagnostic Analyte Component 14-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_164": ClinicalConcept_14(
        concept_id="CONCEPT_14_164",
        loinc_num="24164-2",
        snomed_ct="101400164",
        component="Diagnostic Analyte Component 14-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_165": ClinicalConcept_14(
        concept_id="CONCEPT_14_165",
        loinc_num="24165-3",
        snomed_ct="101400165",
        component="Diagnostic Analyte Component 14-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_166": ClinicalConcept_14(
        concept_id="CONCEPT_14_166",
        loinc_num="24166-4",
        snomed_ct="101400166",
        component="Diagnostic Analyte Component 14-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_167": ClinicalConcept_14(
        concept_id="CONCEPT_14_167",
        loinc_num="24167-5",
        snomed_ct="101400167",
        component="Diagnostic Analyte Component 14-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_168": ClinicalConcept_14(
        concept_id="CONCEPT_14_168",
        loinc_num="24168-6",
        snomed_ct="101400168",
        component="Diagnostic Analyte Component 14-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_169": ClinicalConcept_14(
        concept_id="CONCEPT_14_169",
        loinc_num="24169-7",
        snomed_ct="101400169",
        component="Diagnostic Analyte Component 14-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_170": ClinicalConcept_14(
        concept_id="CONCEPT_14_170",
        loinc_num="24170-8",
        snomed_ct="101400170",
        component="Diagnostic Analyte Component 14-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_171": ClinicalConcept_14(
        concept_id="CONCEPT_14_171",
        loinc_num="24171-0",
        snomed_ct="101400171",
        component="Diagnostic Analyte Component 14-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_172": ClinicalConcept_14(
        concept_id="CONCEPT_14_172",
        loinc_num="24172-1",
        snomed_ct="101400172",
        component="Diagnostic Analyte Component 14-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_173": ClinicalConcept_14(
        concept_id="CONCEPT_14_173",
        loinc_num="24173-2",
        snomed_ct="101400173",
        component="Diagnostic Analyte Component 14-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_174": ClinicalConcept_14(
        concept_id="CONCEPT_14_174",
        loinc_num="24174-3",
        snomed_ct="101400174",
        component="Diagnostic Analyte Component 14-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_175": ClinicalConcept_14(
        concept_id="CONCEPT_14_175",
        loinc_num="24175-4",
        snomed_ct="101400175",
        component="Diagnostic Analyte Component 14-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_176": ClinicalConcept_14(
        concept_id="CONCEPT_14_176",
        loinc_num="24176-5",
        snomed_ct="101400176",
        component="Diagnostic Analyte Component 14-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_177": ClinicalConcept_14(
        concept_id="CONCEPT_14_177",
        loinc_num="24177-6",
        snomed_ct="101400177",
        component="Diagnostic Analyte Component 14-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_178": ClinicalConcept_14(
        concept_id="CONCEPT_14_178",
        loinc_num="24178-7",
        snomed_ct="101400178",
        component="Diagnostic Analyte Component 14-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_179": ClinicalConcept_14(
        concept_id="CONCEPT_14_179",
        loinc_num="24179-8",
        snomed_ct="101400179",
        component="Diagnostic Analyte Component 14-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_180": ClinicalConcept_14(
        concept_id="CONCEPT_14_180",
        loinc_num="24180-0",
        snomed_ct="101400180",
        component="Diagnostic Analyte Component 14-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_181": ClinicalConcept_14(
        concept_id="CONCEPT_14_181",
        loinc_num="24181-1",
        snomed_ct="101400181",
        component="Diagnostic Analyte Component 14-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_182": ClinicalConcept_14(
        concept_id="CONCEPT_14_182",
        loinc_num="24182-2",
        snomed_ct="101400182",
        component="Diagnostic Analyte Component 14-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_183": ClinicalConcept_14(
        concept_id="CONCEPT_14_183",
        loinc_num="24183-3",
        snomed_ct="101400183",
        component="Diagnostic Analyte Component 14-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_184": ClinicalConcept_14(
        concept_id="CONCEPT_14_184",
        loinc_num="24184-4",
        snomed_ct="101400184",
        component="Diagnostic Analyte Component 14-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_185": ClinicalConcept_14(
        concept_id="CONCEPT_14_185",
        loinc_num="24185-5",
        snomed_ct="101400185",
        component="Diagnostic Analyte Component 14-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_186": ClinicalConcept_14(
        concept_id="CONCEPT_14_186",
        loinc_num="24186-6",
        snomed_ct="101400186",
        component="Diagnostic Analyte Component 14-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_187": ClinicalConcept_14(
        concept_id="CONCEPT_14_187",
        loinc_num="24187-7",
        snomed_ct="101400187",
        component="Diagnostic Analyte Component 14-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_188": ClinicalConcept_14(
        concept_id="CONCEPT_14_188",
        loinc_num="24188-8",
        snomed_ct="101400188",
        component="Diagnostic Analyte Component 14-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_189": ClinicalConcept_14(
        concept_id="CONCEPT_14_189",
        loinc_num="24189-0",
        snomed_ct="101400189",
        component="Diagnostic Analyte Component 14-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_190": ClinicalConcept_14(
        concept_id="CONCEPT_14_190",
        loinc_num="24190-1",
        snomed_ct="101400190",
        component="Diagnostic Analyte Component 14-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_191": ClinicalConcept_14(
        concept_id="CONCEPT_14_191",
        loinc_num="24191-2",
        snomed_ct="101400191",
        component="Diagnostic Analyte Component 14-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_192": ClinicalConcept_14(
        concept_id="CONCEPT_14_192",
        loinc_num="24192-3",
        snomed_ct="101400192",
        component="Diagnostic Analyte Component 14-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_193": ClinicalConcept_14(
        concept_id="CONCEPT_14_193",
        loinc_num="24193-4",
        snomed_ct="101400193",
        component="Diagnostic Analyte Component 14-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_194": ClinicalConcept_14(
        concept_id="CONCEPT_14_194",
        loinc_num="24194-5",
        snomed_ct="101400194",
        component="Diagnostic Analyte Component 14-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_195": ClinicalConcept_14(
        concept_id="CONCEPT_14_195",
        loinc_num="24195-6",
        snomed_ct="101400195",
        component="Diagnostic Analyte Component 14-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_196": ClinicalConcept_14(
        concept_id="CONCEPT_14_196",
        loinc_num="24196-7",
        snomed_ct="101400196",
        component="Diagnostic Analyte Component 14-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_197": ClinicalConcept_14(
        concept_id="CONCEPT_14_197",
        loinc_num="24197-8",
        snomed_ct="101400197",
        component="Diagnostic Analyte Component 14-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_198": ClinicalConcept_14(
        concept_id="CONCEPT_14_198",
        loinc_num="24198-0",
        snomed_ct="101400198",
        component="Diagnostic Analyte Component 14-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_14_199": ClinicalConcept_14(
        concept_id="CONCEPT_14_199",
        loinc_num="24199-1",
        snomed_ct="101400199",
        component="Diagnostic Analyte Component 14-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
