"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 11"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_11:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_11 = {
    "CONCEPT_11_001": ClinicalConcept_11(
        concept_id="CONCEPT_11_001",
        loinc_num="21001-1",
        snomed_ct="101100001",
        component="Diagnostic Analyte Component 11-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_002": ClinicalConcept_11(
        concept_id="CONCEPT_11_002",
        loinc_num="21002-2",
        snomed_ct="101100002",
        component="Diagnostic Analyte Component 11-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_003": ClinicalConcept_11(
        concept_id="CONCEPT_11_003",
        loinc_num="21003-3",
        snomed_ct="101100003",
        component="Diagnostic Analyte Component 11-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_004": ClinicalConcept_11(
        concept_id="CONCEPT_11_004",
        loinc_num="21004-4",
        snomed_ct="101100004",
        component="Diagnostic Analyte Component 11-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_005": ClinicalConcept_11(
        concept_id="CONCEPT_11_005",
        loinc_num="21005-5",
        snomed_ct="101100005",
        component="Diagnostic Analyte Component 11-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_006": ClinicalConcept_11(
        concept_id="CONCEPT_11_006",
        loinc_num="21006-6",
        snomed_ct="101100006",
        component="Diagnostic Analyte Component 11-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_007": ClinicalConcept_11(
        concept_id="CONCEPT_11_007",
        loinc_num="21007-7",
        snomed_ct="101100007",
        component="Diagnostic Analyte Component 11-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_008": ClinicalConcept_11(
        concept_id="CONCEPT_11_008",
        loinc_num="21008-8",
        snomed_ct="101100008",
        component="Diagnostic Analyte Component 11-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_009": ClinicalConcept_11(
        concept_id="CONCEPT_11_009",
        loinc_num="21009-0",
        snomed_ct="101100009",
        component="Diagnostic Analyte Component 11-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_010": ClinicalConcept_11(
        concept_id="CONCEPT_11_010",
        loinc_num="21010-1",
        snomed_ct="101100010",
        component="Diagnostic Analyte Component 11-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_011": ClinicalConcept_11(
        concept_id="CONCEPT_11_011",
        loinc_num="21011-2",
        snomed_ct="101100011",
        component="Diagnostic Analyte Component 11-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_012": ClinicalConcept_11(
        concept_id="CONCEPT_11_012",
        loinc_num="21012-3",
        snomed_ct="101100012",
        component="Diagnostic Analyte Component 11-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_013": ClinicalConcept_11(
        concept_id="CONCEPT_11_013",
        loinc_num="21013-4",
        snomed_ct="101100013",
        component="Diagnostic Analyte Component 11-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_014": ClinicalConcept_11(
        concept_id="CONCEPT_11_014",
        loinc_num="21014-5",
        snomed_ct="101100014",
        component="Diagnostic Analyte Component 11-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_015": ClinicalConcept_11(
        concept_id="CONCEPT_11_015",
        loinc_num="21015-6",
        snomed_ct="101100015",
        component="Diagnostic Analyte Component 11-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_016": ClinicalConcept_11(
        concept_id="CONCEPT_11_016",
        loinc_num="21016-7",
        snomed_ct="101100016",
        component="Diagnostic Analyte Component 11-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_017": ClinicalConcept_11(
        concept_id="CONCEPT_11_017",
        loinc_num="21017-8",
        snomed_ct="101100017",
        component="Diagnostic Analyte Component 11-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_018": ClinicalConcept_11(
        concept_id="CONCEPT_11_018",
        loinc_num="21018-0",
        snomed_ct="101100018",
        component="Diagnostic Analyte Component 11-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_019": ClinicalConcept_11(
        concept_id="CONCEPT_11_019",
        loinc_num="21019-1",
        snomed_ct="101100019",
        component="Diagnostic Analyte Component 11-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_020": ClinicalConcept_11(
        concept_id="CONCEPT_11_020",
        loinc_num="21020-2",
        snomed_ct="101100020",
        component="Diagnostic Analyte Component 11-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_021": ClinicalConcept_11(
        concept_id="CONCEPT_11_021",
        loinc_num="21021-3",
        snomed_ct="101100021",
        component="Diagnostic Analyte Component 11-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_022": ClinicalConcept_11(
        concept_id="CONCEPT_11_022",
        loinc_num="21022-4",
        snomed_ct="101100022",
        component="Diagnostic Analyte Component 11-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_023": ClinicalConcept_11(
        concept_id="CONCEPT_11_023",
        loinc_num="21023-5",
        snomed_ct="101100023",
        component="Diagnostic Analyte Component 11-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_024": ClinicalConcept_11(
        concept_id="CONCEPT_11_024",
        loinc_num="21024-6",
        snomed_ct="101100024",
        component="Diagnostic Analyte Component 11-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_025": ClinicalConcept_11(
        concept_id="CONCEPT_11_025",
        loinc_num="21025-7",
        snomed_ct="101100025",
        component="Diagnostic Analyte Component 11-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_026": ClinicalConcept_11(
        concept_id="CONCEPT_11_026",
        loinc_num="21026-8",
        snomed_ct="101100026",
        component="Diagnostic Analyte Component 11-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_027": ClinicalConcept_11(
        concept_id="CONCEPT_11_027",
        loinc_num="21027-0",
        snomed_ct="101100027",
        component="Diagnostic Analyte Component 11-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_028": ClinicalConcept_11(
        concept_id="CONCEPT_11_028",
        loinc_num="21028-1",
        snomed_ct="101100028",
        component="Diagnostic Analyte Component 11-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_029": ClinicalConcept_11(
        concept_id="CONCEPT_11_029",
        loinc_num="21029-2",
        snomed_ct="101100029",
        component="Diagnostic Analyte Component 11-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_030": ClinicalConcept_11(
        concept_id="CONCEPT_11_030",
        loinc_num="21030-3",
        snomed_ct="101100030",
        component="Diagnostic Analyte Component 11-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_031": ClinicalConcept_11(
        concept_id="CONCEPT_11_031",
        loinc_num="21031-4",
        snomed_ct="101100031",
        component="Diagnostic Analyte Component 11-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_032": ClinicalConcept_11(
        concept_id="CONCEPT_11_032",
        loinc_num="21032-5",
        snomed_ct="101100032",
        component="Diagnostic Analyte Component 11-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_033": ClinicalConcept_11(
        concept_id="CONCEPT_11_033",
        loinc_num="21033-6",
        snomed_ct="101100033",
        component="Diagnostic Analyte Component 11-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_034": ClinicalConcept_11(
        concept_id="CONCEPT_11_034",
        loinc_num="21034-7",
        snomed_ct="101100034",
        component="Diagnostic Analyte Component 11-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_035": ClinicalConcept_11(
        concept_id="CONCEPT_11_035",
        loinc_num="21035-8",
        snomed_ct="101100035",
        component="Diagnostic Analyte Component 11-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_036": ClinicalConcept_11(
        concept_id="CONCEPT_11_036",
        loinc_num="21036-0",
        snomed_ct="101100036",
        component="Diagnostic Analyte Component 11-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_037": ClinicalConcept_11(
        concept_id="CONCEPT_11_037",
        loinc_num="21037-1",
        snomed_ct="101100037",
        component="Diagnostic Analyte Component 11-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_038": ClinicalConcept_11(
        concept_id="CONCEPT_11_038",
        loinc_num="21038-2",
        snomed_ct="101100038",
        component="Diagnostic Analyte Component 11-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_039": ClinicalConcept_11(
        concept_id="CONCEPT_11_039",
        loinc_num="21039-3",
        snomed_ct="101100039",
        component="Diagnostic Analyte Component 11-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_040": ClinicalConcept_11(
        concept_id="CONCEPT_11_040",
        loinc_num="21040-4",
        snomed_ct="101100040",
        component="Diagnostic Analyte Component 11-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_041": ClinicalConcept_11(
        concept_id="CONCEPT_11_041",
        loinc_num="21041-5",
        snomed_ct="101100041",
        component="Diagnostic Analyte Component 11-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_042": ClinicalConcept_11(
        concept_id="CONCEPT_11_042",
        loinc_num="21042-6",
        snomed_ct="101100042",
        component="Diagnostic Analyte Component 11-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_043": ClinicalConcept_11(
        concept_id="CONCEPT_11_043",
        loinc_num="21043-7",
        snomed_ct="101100043",
        component="Diagnostic Analyte Component 11-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_044": ClinicalConcept_11(
        concept_id="CONCEPT_11_044",
        loinc_num="21044-8",
        snomed_ct="101100044",
        component="Diagnostic Analyte Component 11-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_045": ClinicalConcept_11(
        concept_id="CONCEPT_11_045",
        loinc_num="21045-0",
        snomed_ct="101100045",
        component="Diagnostic Analyte Component 11-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_046": ClinicalConcept_11(
        concept_id="CONCEPT_11_046",
        loinc_num="21046-1",
        snomed_ct="101100046",
        component="Diagnostic Analyte Component 11-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_047": ClinicalConcept_11(
        concept_id="CONCEPT_11_047",
        loinc_num="21047-2",
        snomed_ct="101100047",
        component="Diagnostic Analyte Component 11-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_048": ClinicalConcept_11(
        concept_id="CONCEPT_11_048",
        loinc_num="21048-3",
        snomed_ct="101100048",
        component="Diagnostic Analyte Component 11-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_049": ClinicalConcept_11(
        concept_id="CONCEPT_11_049",
        loinc_num="21049-4",
        snomed_ct="101100049",
        component="Diagnostic Analyte Component 11-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_050": ClinicalConcept_11(
        concept_id="CONCEPT_11_050",
        loinc_num="21050-5",
        snomed_ct="101100050",
        component="Diagnostic Analyte Component 11-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_051": ClinicalConcept_11(
        concept_id="CONCEPT_11_051",
        loinc_num="21051-6",
        snomed_ct="101100051",
        component="Diagnostic Analyte Component 11-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_052": ClinicalConcept_11(
        concept_id="CONCEPT_11_052",
        loinc_num="21052-7",
        snomed_ct="101100052",
        component="Diagnostic Analyte Component 11-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_053": ClinicalConcept_11(
        concept_id="CONCEPT_11_053",
        loinc_num="21053-8",
        snomed_ct="101100053",
        component="Diagnostic Analyte Component 11-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_054": ClinicalConcept_11(
        concept_id="CONCEPT_11_054",
        loinc_num="21054-0",
        snomed_ct="101100054",
        component="Diagnostic Analyte Component 11-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_055": ClinicalConcept_11(
        concept_id="CONCEPT_11_055",
        loinc_num="21055-1",
        snomed_ct="101100055",
        component="Diagnostic Analyte Component 11-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_056": ClinicalConcept_11(
        concept_id="CONCEPT_11_056",
        loinc_num="21056-2",
        snomed_ct="101100056",
        component="Diagnostic Analyte Component 11-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_057": ClinicalConcept_11(
        concept_id="CONCEPT_11_057",
        loinc_num="21057-3",
        snomed_ct="101100057",
        component="Diagnostic Analyte Component 11-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_058": ClinicalConcept_11(
        concept_id="CONCEPT_11_058",
        loinc_num="21058-4",
        snomed_ct="101100058",
        component="Diagnostic Analyte Component 11-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_059": ClinicalConcept_11(
        concept_id="CONCEPT_11_059",
        loinc_num="21059-5",
        snomed_ct="101100059",
        component="Diagnostic Analyte Component 11-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_060": ClinicalConcept_11(
        concept_id="CONCEPT_11_060",
        loinc_num="21060-6",
        snomed_ct="101100060",
        component="Diagnostic Analyte Component 11-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_061": ClinicalConcept_11(
        concept_id="CONCEPT_11_061",
        loinc_num="21061-7",
        snomed_ct="101100061",
        component="Diagnostic Analyte Component 11-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_062": ClinicalConcept_11(
        concept_id="CONCEPT_11_062",
        loinc_num="21062-8",
        snomed_ct="101100062",
        component="Diagnostic Analyte Component 11-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_063": ClinicalConcept_11(
        concept_id="CONCEPT_11_063",
        loinc_num="21063-0",
        snomed_ct="101100063",
        component="Diagnostic Analyte Component 11-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_064": ClinicalConcept_11(
        concept_id="CONCEPT_11_064",
        loinc_num="21064-1",
        snomed_ct="101100064",
        component="Diagnostic Analyte Component 11-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_065": ClinicalConcept_11(
        concept_id="CONCEPT_11_065",
        loinc_num="21065-2",
        snomed_ct="101100065",
        component="Diagnostic Analyte Component 11-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_066": ClinicalConcept_11(
        concept_id="CONCEPT_11_066",
        loinc_num="21066-3",
        snomed_ct="101100066",
        component="Diagnostic Analyte Component 11-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_067": ClinicalConcept_11(
        concept_id="CONCEPT_11_067",
        loinc_num="21067-4",
        snomed_ct="101100067",
        component="Diagnostic Analyte Component 11-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_068": ClinicalConcept_11(
        concept_id="CONCEPT_11_068",
        loinc_num="21068-5",
        snomed_ct="101100068",
        component="Diagnostic Analyte Component 11-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_069": ClinicalConcept_11(
        concept_id="CONCEPT_11_069",
        loinc_num="21069-6",
        snomed_ct="101100069",
        component="Diagnostic Analyte Component 11-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_070": ClinicalConcept_11(
        concept_id="CONCEPT_11_070",
        loinc_num="21070-7",
        snomed_ct="101100070",
        component="Diagnostic Analyte Component 11-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_071": ClinicalConcept_11(
        concept_id="CONCEPT_11_071",
        loinc_num="21071-8",
        snomed_ct="101100071",
        component="Diagnostic Analyte Component 11-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_072": ClinicalConcept_11(
        concept_id="CONCEPT_11_072",
        loinc_num="21072-0",
        snomed_ct="101100072",
        component="Diagnostic Analyte Component 11-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_073": ClinicalConcept_11(
        concept_id="CONCEPT_11_073",
        loinc_num="21073-1",
        snomed_ct="101100073",
        component="Diagnostic Analyte Component 11-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_074": ClinicalConcept_11(
        concept_id="CONCEPT_11_074",
        loinc_num="21074-2",
        snomed_ct="101100074",
        component="Diagnostic Analyte Component 11-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_075": ClinicalConcept_11(
        concept_id="CONCEPT_11_075",
        loinc_num="21075-3",
        snomed_ct="101100075",
        component="Diagnostic Analyte Component 11-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_076": ClinicalConcept_11(
        concept_id="CONCEPT_11_076",
        loinc_num="21076-4",
        snomed_ct="101100076",
        component="Diagnostic Analyte Component 11-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_077": ClinicalConcept_11(
        concept_id="CONCEPT_11_077",
        loinc_num="21077-5",
        snomed_ct="101100077",
        component="Diagnostic Analyte Component 11-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_078": ClinicalConcept_11(
        concept_id="CONCEPT_11_078",
        loinc_num="21078-6",
        snomed_ct="101100078",
        component="Diagnostic Analyte Component 11-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_079": ClinicalConcept_11(
        concept_id="CONCEPT_11_079",
        loinc_num="21079-7",
        snomed_ct="101100079",
        component="Diagnostic Analyte Component 11-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_080": ClinicalConcept_11(
        concept_id="CONCEPT_11_080",
        loinc_num="21080-8",
        snomed_ct="101100080",
        component="Diagnostic Analyte Component 11-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_081": ClinicalConcept_11(
        concept_id="CONCEPT_11_081",
        loinc_num="21081-0",
        snomed_ct="101100081",
        component="Diagnostic Analyte Component 11-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_082": ClinicalConcept_11(
        concept_id="CONCEPT_11_082",
        loinc_num="21082-1",
        snomed_ct="101100082",
        component="Diagnostic Analyte Component 11-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_083": ClinicalConcept_11(
        concept_id="CONCEPT_11_083",
        loinc_num="21083-2",
        snomed_ct="101100083",
        component="Diagnostic Analyte Component 11-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_084": ClinicalConcept_11(
        concept_id="CONCEPT_11_084",
        loinc_num="21084-3",
        snomed_ct="101100084",
        component="Diagnostic Analyte Component 11-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_085": ClinicalConcept_11(
        concept_id="CONCEPT_11_085",
        loinc_num="21085-4",
        snomed_ct="101100085",
        component="Diagnostic Analyte Component 11-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_086": ClinicalConcept_11(
        concept_id="CONCEPT_11_086",
        loinc_num="21086-5",
        snomed_ct="101100086",
        component="Diagnostic Analyte Component 11-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_087": ClinicalConcept_11(
        concept_id="CONCEPT_11_087",
        loinc_num="21087-6",
        snomed_ct="101100087",
        component="Diagnostic Analyte Component 11-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_088": ClinicalConcept_11(
        concept_id="CONCEPT_11_088",
        loinc_num="21088-7",
        snomed_ct="101100088",
        component="Diagnostic Analyte Component 11-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_089": ClinicalConcept_11(
        concept_id="CONCEPT_11_089",
        loinc_num="21089-8",
        snomed_ct="101100089",
        component="Diagnostic Analyte Component 11-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_090": ClinicalConcept_11(
        concept_id="CONCEPT_11_090",
        loinc_num="21090-0",
        snomed_ct="101100090",
        component="Diagnostic Analyte Component 11-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_091": ClinicalConcept_11(
        concept_id="CONCEPT_11_091",
        loinc_num="21091-1",
        snomed_ct="101100091",
        component="Diagnostic Analyte Component 11-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_092": ClinicalConcept_11(
        concept_id="CONCEPT_11_092",
        loinc_num="21092-2",
        snomed_ct="101100092",
        component="Diagnostic Analyte Component 11-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_093": ClinicalConcept_11(
        concept_id="CONCEPT_11_093",
        loinc_num="21093-3",
        snomed_ct="101100093",
        component="Diagnostic Analyte Component 11-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_094": ClinicalConcept_11(
        concept_id="CONCEPT_11_094",
        loinc_num="21094-4",
        snomed_ct="101100094",
        component="Diagnostic Analyte Component 11-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_095": ClinicalConcept_11(
        concept_id="CONCEPT_11_095",
        loinc_num="21095-5",
        snomed_ct="101100095",
        component="Diagnostic Analyte Component 11-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_096": ClinicalConcept_11(
        concept_id="CONCEPT_11_096",
        loinc_num="21096-6",
        snomed_ct="101100096",
        component="Diagnostic Analyte Component 11-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_097": ClinicalConcept_11(
        concept_id="CONCEPT_11_097",
        loinc_num="21097-7",
        snomed_ct="101100097",
        component="Diagnostic Analyte Component 11-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_098": ClinicalConcept_11(
        concept_id="CONCEPT_11_098",
        loinc_num="21098-8",
        snomed_ct="101100098",
        component="Diagnostic Analyte Component 11-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_099": ClinicalConcept_11(
        concept_id="CONCEPT_11_099",
        loinc_num="21099-0",
        snomed_ct="101100099",
        component="Diagnostic Analyte Component 11-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_100": ClinicalConcept_11(
        concept_id="CONCEPT_11_100",
        loinc_num="21100-1",
        snomed_ct="101100100",
        component="Diagnostic Analyte Component 11-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_101": ClinicalConcept_11(
        concept_id="CONCEPT_11_101",
        loinc_num="21101-2",
        snomed_ct="101100101",
        component="Diagnostic Analyte Component 11-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_102": ClinicalConcept_11(
        concept_id="CONCEPT_11_102",
        loinc_num="21102-3",
        snomed_ct="101100102",
        component="Diagnostic Analyte Component 11-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_103": ClinicalConcept_11(
        concept_id="CONCEPT_11_103",
        loinc_num="21103-4",
        snomed_ct="101100103",
        component="Diagnostic Analyte Component 11-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_104": ClinicalConcept_11(
        concept_id="CONCEPT_11_104",
        loinc_num="21104-5",
        snomed_ct="101100104",
        component="Diagnostic Analyte Component 11-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_105": ClinicalConcept_11(
        concept_id="CONCEPT_11_105",
        loinc_num="21105-6",
        snomed_ct="101100105",
        component="Diagnostic Analyte Component 11-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_106": ClinicalConcept_11(
        concept_id="CONCEPT_11_106",
        loinc_num="21106-7",
        snomed_ct="101100106",
        component="Diagnostic Analyte Component 11-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_107": ClinicalConcept_11(
        concept_id="CONCEPT_11_107",
        loinc_num="21107-8",
        snomed_ct="101100107",
        component="Diagnostic Analyte Component 11-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_108": ClinicalConcept_11(
        concept_id="CONCEPT_11_108",
        loinc_num="21108-0",
        snomed_ct="101100108",
        component="Diagnostic Analyte Component 11-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_109": ClinicalConcept_11(
        concept_id="CONCEPT_11_109",
        loinc_num="21109-1",
        snomed_ct="101100109",
        component="Diagnostic Analyte Component 11-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_110": ClinicalConcept_11(
        concept_id="CONCEPT_11_110",
        loinc_num="21110-2",
        snomed_ct="101100110",
        component="Diagnostic Analyte Component 11-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_111": ClinicalConcept_11(
        concept_id="CONCEPT_11_111",
        loinc_num="21111-3",
        snomed_ct="101100111",
        component="Diagnostic Analyte Component 11-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_112": ClinicalConcept_11(
        concept_id="CONCEPT_11_112",
        loinc_num="21112-4",
        snomed_ct="101100112",
        component="Diagnostic Analyte Component 11-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_113": ClinicalConcept_11(
        concept_id="CONCEPT_11_113",
        loinc_num="21113-5",
        snomed_ct="101100113",
        component="Diagnostic Analyte Component 11-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_114": ClinicalConcept_11(
        concept_id="CONCEPT_11_114",
        loinc_num="21114-6",
        snomed_ct="101100114",
        component="Diagnostic Analyte Component 11-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_115": ClinicalConcept_11(
        concept_id="CONCEPT_11_115",
        loinc_num="21115-7",
        snomed_ct="101100115",
        component="Diagnostic Analyte Component 11-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_116": ClinicalConcept_11(
        concept_id="CONCEPT_11_116",
        loinc_num="21116-8",
        snomed_ct="101100116",
        component="Diagnostic Analyte Component 11-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_117": ClinicalConcept_11(
        concept_id="CONCEPT_11_117",
        loinc_num="21117-0",
        snomed_ct="101100117",
        component="Diagnostic Analyte Component 11-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_118": ClinicalConcept_11(
        concept_id="CONCEPT_11_118",
        loinc_num="21118-1",
        snomed_ct="101100118",
        component="Diagnostic Analyte Component 11-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_119": ClinicalConcept_11(
        concept_id="CONCEPT_11_119",
        loinc_num="21119-2",
        snomed_ct="101100119",
        component="Diagnostic Analyte Component 11-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_120": ClinicalConcept_11(
        concept_id="CONCEPT_11_120",
        loinc_num="21120-3",
        snomed_ct="101100120",
        component="Diagnostic Analyte Component 11-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_121": ClinicalConcept_11(
        concept_id="CONCEPT_11_121",
        loinc_num="21121-4",
        snomed_ct="101100121",
        component="Diagnostic Analyte Component 11-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_122": ClinicalConcept_11(
        concept_id="CONCEPT_11_122",
        loinc_num="21122-5",
        snomed_ct="101100122",
        component="Diagnostic Analyte Component 11-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_123": ClinicalConcept_11(
        concept_id="CONCEPT_11_123",
        loinc_num="21123-6",
        snomed_ct="101100123",
        component="Diagnostic Analyte Component 11-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_124": ClinicalConcept_11(
        concept_id="CONCEPT_11_124",
        loinc_num="21124-7",
        snomed_ct="101100124",
        component="Diagnostic Analyte Component 11-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_125": ClinicalConcept_11(
        concept_id="CONCEPT_11_125",
        loinc_num="21125-8",
        snomed_ct="101100125",
        component="Diagnostic Analyte Component 11-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_126": ClinicalConcept_11(
        concept_id="CONCEPT_11_126",
        loinc_num="21126-0",
        snomed_ct="101100126",
        component="Diagnostic Analyte Component 11-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_127": ClinicalConcept_11(
        concept_id="CONCEPT_11_127",
        loinc_num="21127-1",
        snomed_ct="101100127",
        component="Diagnostic Analyte Component 11-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_128": ClinicalConcept_11(
        concept_id="CONCEPT_11_128",
        loinc_num="21128-2",
        snomed_ct="101100128",
        component="Diagnostic Analyte Component 11-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_129": ClinicalConcept_11(
        concept_id="CONCEPT_11_129",
        loinc_num="21129-3",
        snomed_ct="101100129",
        component="Diagnostic Analyte Component 11-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_130": ClinicalConcept_11(
        concept_id="CONCEPT_11_130",
        loinc_num="21130-4",
        snomed_ct="101100130",
        component="Diagnostic Analyte Component 11-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_131": ClinicalConcept_11(
        concept_id="CONCEPT_11_131",
        loinc_num="21131-5",
        snomed_ct="101100131",
        component="Diagnostic Analyte Component 11-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_132": ClinicalConcept_11(
        concept_id="CONCEPT_11_132",
        loinc_num="21132-6",
        snomed_ct="101100132",
        component="Diagnostic Analyte Component 11-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_133": ClinicalConcept_11(
        concept_id="CONCEPT_11_133",
        loinc_num="21133-7",
        snomed_ct="101100133",
        component="Diagnostic Analyte Component 11-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_134": ClinicalConcept_11(
        concept_id="CONCEPT_11_134",
        loinc_num="21134-8",
        snomed_ct="101100134",
        component="Diagnostic Analyte Component 11-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_135": ClinicalConcept_11(
        concept_id="CONCEPT_11_135",
        loinc_num="21135-0",
        snomed_ct="101100135",
        component="Diagnostic Analyte Component 11-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_136": ClinicalConcept_11(
        concept_id="CONCEPT_11_136",
        loinc_num="21136-1",
        snomed_ct="101100136",
        component="Diagnostic Analyte Component 11-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_137": ClinicalConcept_11(
        concept_id="CONCEPT_11_137",
        loinc_num="21137-2",
        snomed_ct="101100137",
        component="Diagnostic Analyte Component 11-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_138": ClinicalConcept_11(
        concept_id="CONCEPT_11_138",
        loinc_num="21138-3",
        snomed_ct="101100138",
        component="Diagnostic Analyte Component 11-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_139": ClinicalConcept_11(
        concept_id="CONCEPT_11_139",
        loinc_num="21139-4",
        snomed_ct="101100139",
        component="Diagnostic Analyte Component 11-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_140": ClinicalConcept_11(
        concept_id="CONCEPT_11_140",
        loinc_num="21140-5",
        snomed_ct="101100140",
        component="Diagnostic Analyte Component 11-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_141": ClinicalConcept_11(
        concept_id="CONCEPT_11_141",
        loinc_num="21141-6",
        snomed_ct="101100141",
        component="Diagnostic Analyte Component 11-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_142": ClinicalConcept_11(
        concept_id="CONCEPT_11_142",
        loinc_num="21142-7",
        snomed_ct="101100142",
        component="Diagnostic Analyte Component 11-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_143": ClinicalConcept_11(
        concept_id="CONCEPT_11_143",
        loinc_num="21143-8",
        snomed_ct="101100143",
        component="Diagnostic Analyte Component 11-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_144": ClinicalConcept_11(
        concept_id="CONCEPT_11_144",
        loinc_num="21144-0",
        snomed_ct="101100144",
        component="Diagnostic Analyte Component 11-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_145": ClinicalConcept_11(
        concept_id="CONCEPT_11_145",
        loinc_num="21145-1",
        snomed_ct="101100145",
        component="Diagnostic Analyte Component 11-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_146": ClinicalConcept_11(
        concept_id="CONCEPT_11_146",
        loinc_num="21146-2",
        snomed_ct="101100146",
        component="Diagnostic Analyte Component 11-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_147": ClinicalConcept_11(
        concept_id="CONCEPT_11_147",
        loinc_num="21147-3",
        snomed_ct="101100147",
        component="Diagnostic Analyte Component 11-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_148": ClinicalConcept_11(
        concept_id="CONCEPT_11_148",
        loinc_num="21148-4",
        snomed_ct="101100148",
        component="Diagnostic Analyte Component 11-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_149": ClinicalConcept_11(
        concept_id="CONCEPT_11_149",
        loinc_num="21149-5",
        snomed_ct="101100149",
        component="Diagnostic Analyte Component 11-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_150": ClinicalConcept_11(
        concept_id="CONCEPT_11_150",
        loinc_num="21150-6",
        snomed_ct="101100150",
        component="Diagnostic Analyte Component 11-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_151": ClinicalConcept_11(
        concept_id="CONCEPT_11_151",
        loinc_num="21151-7",
        snomed_ct="101100151",
        component="Diagnostic Analyte Component 11-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_152": ClinicalConcept_11(
        concept_id="CONCEPT_11_152",
        loinc_num="21152-8",
        snomed_ct="101100152",
        component="Diagnostic Analyte Component 11-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_153": ClinicalConcept_11(
        concept_id="CONCEPT_11_153",
        loinc_num="21153-0",
        snomed_ct="101100153",
        component="Diagnostic Analyte Component 11-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_154": ClinicalConcept_11(
        concept_id="CONCEPT_11_154",
        loinc_num="21154-1",
        snomed_ct="101100154",
        component="Diagnostic Analyte Component 11-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_155": ClinicalConcept_11(
        concept_id="CONCEPT_11_155",
        loinc_num="21155-2",
        snomed_ct="101100155",
        component="Diagnostic Analyte Component 11-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_156": ClinicalConcept_11(
        concept_id="CONCEPT_11_156",
        loinc_num="21156-3",
        snomed_ct="101100156",
        component="Diagnostic Analyte Component 11-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_157": ClinicalConcept_11(
        concept_id="CONCEPT_11_157",
        loinc_num="21157-4",
        snomed_ct="101100157",
        component="Diagnostic Analyte Component 11-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_158": ClinicalConcept_11(
        concept_id="CONCEPT_11_158",
        loinc_num="21158-5",
        snomed_ct="101100158",
        component="Diagnostic Analyte Component 11-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_159": ClinicalConcept_11(
        concept_id="CONCEPT_11_159",
        loinc_num="21159-6",
        snomed_ct="101100159",
        component="Diagnostic Analyte Component 11-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_160": ClinicalConcept_11(
        concept_id="CONCEPT_11_160",
        loinc_num="21160-7",
        snomed_ct="101100160",
        component="Diagnostic Analyte Component 11-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_161": ClinicalConcept_11(
        concept_id="CONCEPT_11_161",
        loinc_num="21161-8",
        snomed_ct="101100161",
        component="Diagnostic Analyte Component 11-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_162": ClinicalConcept_11(
        concept_id="CONCEPT_11_162",
        loinc_num="21162-0",
        snomed_ct="101100162",
        component="Diagnostic Analyte Component 11-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_163": ClinicalConcept_11(
        concept_id="CONCEPT_11_163",
        loinc_num="21163-1",
        snomed_ct="101100163",
        component="Diagnostic Analyte Component 11-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_164": ClinicalConcept_11(
        concept_id="CONCEPT_11_164",
        loinc_num="21164-2",
        snomed_ct="101100164",
        component="Diagnostic Analyte Component 11-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_165": ClinicalConcept_11(
        concept_id="CONCEPT_11_165",
        loinc_num="21165-3",
        snomed_ct="101100165",
        component="Diagnostic Analyte Component 11-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_166": ClinicalConcept_11(
        concept_id="CONCEPT_11_166",
        loinc_num="21166-4",
        snomed_ct="101100166",
        component="Diagnostic Analyte Component 11-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_167": ClinicalConcept_11(
        concept_id="CONCEPT_11_167",
        loinc_num="21167-5",
        snomed_ct="101100167",
        component="Diagnostic Analyte Component 11-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_168": ClinicalConcept_11(
        concept_id="CONCEPT_11_168",
        loinc_num="21168-6",
        snomed_ct="101100168",
        component="Diagnostic Analyte Component 11-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_169": ClinicalConcept_11(
        concept_id="CONCEPT_11_169",
        loinc_num="21169-7",
        snomed_ct="101100169",
        component="Diagnostic Analyte Component 11-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_170": ClinicalConcept_11(
        concept_id="CONCEPT_11_170",
        loinc_num="21170-8",
        snomed_ct="101100170",
        component="Diagnostic Analyte Component 11-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_171": ClinicalConcept_11(
        concept_id="CONCEPT_11_171",
        loinc_num="21171-0",
        snomed_ct="101100171",
        component="Diagnostic Analyte Component 11-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_172": ClinicalConcept_11(
        concept_id="CONCEPT_11_172",
        loinc_num="21172-1",
        snomed_ct="101100172",
        component="Diagnostic Analyte Component 11-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_173": ClinicalConcept_11(
        concept_id="CONCEPT_11_173",
        loinc_num="21173-2",
        snomed_ct="101100173",
        component="Diagnostic Analyte Component 11-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_174": ClinicalConcept_11(
        concept_id="CONCEPT_11_174",
        loinc_num="21174-3",
        snomed_ct="101100174",
        component="Diagnostic Analyte Component 11-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_175": ClinicalConcept_11(
        concept_id="CONCEPT_11_175",
        loinc_num="21175-4",
        snomed_ct="101100175",
        component="Diagnostic Analyte Component 11-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_176": ClinicalConcept_11(
        concept_id="CONCEPT_11_176",
        loinc_num="21176-5",
        snomed_ct="101100176",
        component="Diagnostic Analyte Component 11-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_177": ClinicalConcept_11(
        concept_id="CONCEPT_11_177",
        loinc_num="21177-6",
        snomed_ct="101100177",
        component="Diagnostic Analyte Component 11-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_178": ClinicalConcept_11(
        concept_id="CONCEPT_11_178",
        loinc_num="21178-7",
        snomed_ct="101100178",
        component="Diagnostic Analyte Component 11-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_179": ClinicalConcept_11(
        concept_id="CONCEPT_11_179",
        loinc_num="21179-8",
        snomed_ct="101100179",
        component="Diagnostic Analyte Component 11-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_180": ClinicalConcept_11(
        concept_id="CONCEPT_11_180",
        loinc_num="21180-0",
        snomed_ct="101100180",
        component="Diagnostic Analyte Component 11-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_181": ClinicalConcept_11(
        concept_id="CONCEPT_11_181",
        loinc_num="21181-1",
        snomed_ct="101100181",
        component="Diagnostic Analyte Component 11-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_182": ClinicalConcept_11(
        concept_id="CONCEPT_11_182",
        loinc_num="21182-2",
        snomed_ct="101100182",
        component="Diagnostic Analyte Component 11-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_183": ClinicalConcept_11(
        concept_id="CONCEPT_11_183",
        loinc_num="21183-3",
        snomed_ct="101100183",
        component="Diagnostic Analyte Component 11-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_184": ClinicalConcept_11(
        concept_id="CONCEPT_11_184",
        loinc_num="21184-4",
        snomed_ct="101100184",
        component="Diagnostic Analyte Component 11-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_185": ClinicalConcept_11(
        concept_id="CONCEPT_11_185",
        loinc_num="21185-5",
        snomed_ct="101100185",
        component="Diagnostic Analyte Component 11-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_186": ClinicalConcept_11(
        concept_id="CONCEPT_11_186",
        loinc_num="21186-6",
        snomed_ct="101100186",
        component="Diagnostic Analyte Component 11-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_187": ClinicalConcept_11(
        concept_id="CONCEPT_11_187",
        loinc_num="21187-7",
        snomed_ct="101100187",
        component="Diagnostic Analyte Component 11-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_188": ClinicalConcept_11(
        concept_id="CONCEPT_11_188",
        loinc_num="21188-8",
        snomed_ct="101100188",
        component="Diagnostic Analyte Component 11-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_189": ClinicalConcept_11(
        concept_id="CONCEPT_11_189",
        loinc_num="21189-0",
        snomed_ct="101100189",
        component="Diagnostic Analyte Component 11-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_190": ClinicalConcept_11(
        concept_id="CONCEPT_11_190",
        loinc_num="21190-1",
        snomed_ct="101100190",
        component="Diagnostic Analyte Component 11-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_191": ClinicalConcept_11(
        concept_id="CONCEPT_11_191",
        loinc_num="21191-2",
        snomed_ct="101100191",
        component="Diagnostic Analyte Component 11-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_192": ClinicalConcept_11(
        concept_id="CONCEPT_11_192",
        loinc_num="21192-3",
        snomed_ct="101100192",
        component="Diagnostic Analyte Component 11-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_193": ClinicalConcept_11(
        concept_id="CONCEPT_11_193",
        loinc_num="21193-4",
        snomed_ct="101100193",
        component="Diagnostic Analyte Component 11-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_194": ClinicalConcept_11(
        concept_id="CONCEPT_11_194",
        loinc_num="21194-5",
        snomed_ct="101100194",
        component="Diagnostic Analyte Component 11-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_195": ClinicalConcept_11(
        concept_id="CONCEPT_11_195",
        loinc_num="21195-6",
        snomed_ct="101100195",
        component="Diagnostic Analyte Component 11-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_196": ClinicalConcept_11(
        concept_id="CONCEPT_11_196",
        loinc_num="21196-7",
        snomed_ct="101100196",
        component="Diagnostic Analyte Component 11-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_197": ClinicalConcept_11(
        concept_id="CONCEPT_11_197",
        loinc_num="21197-8",
        snomed_ct="101100197",
        component="Diagnostic Analyte Component 11-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_198": ClinicalConcept_11(
        concept_id="CONCEPT_11_198",
        loinc_num="21198-0",
        snomed_ct="101100198",
        component="Diagnostic Analyte Component 11-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_11_199": ClinicalConcept_11(
        concept_id="CONCEPT_11_199",
        loinc_num="21199-1",
        snomed_ct="101100199",
        component="Diagnostic Analyte Component 11-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
