"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 02"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_02:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_02 = {
    "CONCEPT_02_001": ClinicalConcept_02(
        concept_id="CONCEPT_02_001",
        loinc_num="12001-1",
        snomed_ct="100200001",
        component="Diagnostic Analyte Component 02-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_002": ClinicalConcept_02(
        concept_id="CONCEPT_02_002",
        loinc_num="12002-2",
        snomed_ct="100200002",
        component="Diagnostic Analyte Component 02-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_003": ClinicalConcept_02(
        concept_id="CONCEPT_02_003",
        loinc_num="12003-3",
        snomed_ct="100200003",
        component="Diagnostic Analyte Component 02-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_004": ClinicalConcept_02(
        concept_id="CONCEPT_02_004",
        loinc_num="12004-4",
        snomed_ct="100200004",
        component="Diagnostic Analyte Component 02-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_005": ClinicalConcept_02(
        concept_id="CONCEPT_02_005",
        loinc_num="12005-5",
        snomed_ct="100200005",
        component="Diagnostic Analyte Component 02-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_006": ClinicalConcept_02(
        concept_id="CONCEPT_02_006",
        loinc_num="12006-6",
        snomed_ct="100200006",
        component="Diagnostic Analyte Component 02-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_007": ClinicalConcept_02(
        concept_id="CONCEPT_02_007",
        loinc_num="12007-7",
        snomed_ct="100200007",
        component="Diagnostic Analyte Component 02-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_008": ClinicalConcept_02(
        concept_id="CONCEPT_02_008",
        loinc_num="12008-8",
        snomed_ct="100200008",
        component="Diagnostic Analyte Component 02-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_009": ClinicalConcept_02(
        concept_id="CONCEPT_02_009",
        loinc_num="12009-0",
        snomed_ct="100200009",
        component="Diagnostic Analyte Component 02-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_010": ClinicalConcept_02(
        concept_id="CONCEPT_02_010",
        loinc_num="12010-1",
        snomed_ct="100200010",
        component="Diagnostic Analyte Component 02-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_011": ClinicalConcept_02(
        concept_id="CONCEPT_02_011",
        loinc_num="12011-2",
        snomed_ct="100200011",
        component="Diagnostic Analyte Component 02-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_012": ClinicalConcept_02(
        concept_id="CONCEPT_02_012",
        loinc_num="12012-3",
        snomed_ct="100200012",
        component="Diagnostic Analyte Component 02-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_013": ClinicalConcept_02(
        concept_id="CONCEPT_02_013",
        loinc_num="12013-4",
        snomed_ct="100200013",
        component="Diagnostic Analyte Component 02-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_014": ClinicalConcept_02(
        concept_id="CONCEPT_02_014",
        loinc_num="12014-5",
        snomed_ct="100200014",
        component="Diagnostic Analyte Component 02-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_015": ClinicalConcept_02(
        concept_id="CONCEPT_02_015",
        loinc_num="12015-6",
        snomed_ct="100200015",
        component="Diagnostic Analyte Component 02-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_016": ClinicalConcept_02(
        concept_id="CONCEPT_02_016",
        loinc_num="12016-7",
        snomed_ct="100200016",
        component="Diagnostic Analyte Component 02-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_017": ClinicalConcept_02(
        concept_id="CONCEPT_02_017",
        loinc_num="12017-8",
        snomed_ct="100200017",
        component="Diagnostic Analyte Component 02-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_018": ClinicalConcept_02(
        concept_id="CONCEPT_02_018",
        loinc_num="12018-0",
        snomed_ct="100200018",
        component="Diagnostic Analyte Component 02-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_019": ClinicalConcept_02(
        concept_id="CONCEPT_02_019",
        loinc_num="12019-1",
        snomed_ct="100200019",
        component="Diagnostic Analyte Component 02-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_020": ClinicalConcept_02(
        concept_id="CONCEPT_02_020",
        loinc_num="12020-2",
        snomed_ct="100200020",
        component="Diagnostic Analyte Component 02-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_021": ClinicalConcept_02(
        concept_id="CONCEPT_02_021",
        loinc_num="12021-3",
        snomed_ct="100200021",
        component="Diagnostic Analyte Component 02-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_022": ClinicalConcept_02(
        concept_id="CONCEPT_02_022",
        loinc_num="12022-4",
        snomed_ct="100200022",
        component="Diagnostic Analyte Component 02-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_023": ClinicalConcept_02(
        concept_id="CONCEPT_02_023",
        loinc_num="12023-5",
        snomed_ct="100200023",
        component="Diagnostic Analyte Component 02-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_024": ClinicalConcept_02(
        concept_id="CONCEPT_02_024",
        loinc_num="12024-6",
        snomed_ct="100200024",
        component="Diagnostic Analyte Component 02-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_025": ClinicalConcept_02(
        concept_id="CONCEPT_02_025",
        loinc_num="12025-7",
        snomed_ct="100200025",
        component="Diagnostic Analyte Component 02-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_026": ClinicalConcept_02(
        concept_id="CONCEPT_02_026",
        loinc_num="12026-8",
        snomed_ct="100200026",
        component="Diagnostic Analyte Component 02-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_027": ClinicalConcept_02(
        concept_id="CONCEPT_02_027",
        loinc_num="12027-0",
        snomed_ct="100200027",
        component="Diagnostic Analyte Component 02-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_028": ClinicalConcept_02(
        concept_id="CONCEPT_02_028",
        loinc_num="12028-1",
        snomed_ct="100200028",
        component="Diagnostic Analyte Component 02-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_029": ClinicalConcept_02(
        concept_id="CONCEPT_02_029",
        loinc_num="12029-2",
        snomed_ct="100200029",
        component="Diagnostic Analyte Component 02-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_030": ClinicalConcept_02(
        concept_id="CONCEPT_02_030",
        loinc_num="12030-3",
        snomed_ct="100200030",
        component="Diagnostic Analyte Component 02-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_031": ClinicalConcept_02(
        concept_id="CONCEPT_02_031",
        loinc_num="12031-4",
        snomed_ct="100200031",
        component="Diagnostic Analyte Component 02-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_032": ClinicalConcept_02(
        concept_id="CONCEPT_02_032",
        loinc_num="12032-5",
        snomed_ct="100200032",
        component="Diagnostic Analyte Component 02-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_033": ClinicalConcept_02(
        concept_id="CONCEPT_02_033",
        loinc_num="12033-6",
        snomed_ct="100200033",
        component="Diagnostic Analyte Component 02-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_034": ClinicalConcept_02(
        concept_id="CONCEPT_02_034",
        loinc_num="12034-7",
        snomed_ct="100200034",
        component="Diagnostic Analyte Component 02-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_035": ClinicalConcept_02(
        concept_id="CONCEPT_02_035",
        loinc_num="12035-8",
        snomed_ct="100200035",
        component="Diagnostic Analyte Component 02-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_036": ClinicalConcept_02(
        concept_id="CONCEPT_02_036",
        loinc_num="12036-0",
        snomed_ct="100200036",
        component="Diagnostic Analyte Component 02-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_037": ClinicalConcept_02(
        concept_id="CONCEPT_02_037",
        loinc_num="12037-1",
        snomed_ct="100200037",
        component="Diagnostic Analyte Component 02-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_038": ClinicalConcept_02(
        concept_id="CONCEPT_02_038",
        loinc_num="12038-2",
        snomed_ct="100200038",
        component="Diagnostic Analyte Component 02-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_039": ClinicalConcept_02(
        concept_id="CONCEPT_02_039",
        loinc_num="12039-3",
        snomed_ct="100200039",
        component="Diagnostic Analyte Component 02-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_040": ClinicalConcept_02(
        concept_id="CONCEPT_02_040",
        loinc_num="12040-4",
        snomed_ct="100200040",
        component="Diagnostic Analyte Component 02-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_041": ClinicalConcept_02(
        concept_id="CONCEPT_02_041",
        loinc_num="12041-5",
        snomed_ct="100200041",
        component="Diagnostic Analyte Component 02-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_042": ClinicalConcept_02(
        concept_id="CONCEPT_02_042",
        loinc_num="12042-6",
        snomed_ct="100200042",
        component="Diagnostic Analyte Component 02-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_043": ClinicalConcept_02(
        concept_id="CONCEPT_02_043",
        loinc_num="12043-7",
        snomed_ct="100200043",
        component="Diagnostic Analyte Component 02-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_044": ClinicalConcept_02(
        concept_id="CONCEPT_02_044",
        loinc_num="12044-8",
        snomed_ct="100200044",
        component="Diagnostic Analyte Component 02-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_045": ClinicalConcept_02(
        concept_id="CONCEPT_02_045",
        loinc_num="12045-0",
        snomed_ct="100200045",
        component="Diagnostic Analyte Component 02-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_046": ClinicalConcept_02(
        concept_id="CONCEPT_02_046",
        loinc_num="12046-1",
        snomed_ct="100200046",
        component="Diagnostic Analyte Component 02-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_047": ClinicalConcept_02(
        concept_id="CONCEPT_02_047",
        loinc_num="12047-2",
        snomed_ct="100200047",
        component="Diagnostic Analyte Component 02-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_048": ClinicalConcept_02(
        concept_id="CONCEPT_02_048",
        loinc_num="12048-3",
        snomed_ct="100200048",
        component="Diagnostic Analyte Component 02-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_049": ClinicalConcept_02(
        concept_id="CONCEPT_02_049",
        loinc_num="12049-4",
        snomed_ct="100200049",
        component="Diagnostic Analyte Component 02-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_050": ClinicalConcept_02(
        concept_id="CONCEPT_02_050",
        loinc_num="12050-5",
        snomed_ct="100200050",
        component="Diagnostic Analyte Component 02-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_051": ClinicalConcept_02(
        concept_id="CONCEPT_02_051",
        loinc_num="12051-6",
        snomed_ct="100200051",
        component="Diagnostic Analyte Component 02-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_052": ClinicalConcept_02(
        concept_id="CONCEPT_02_052",
        loinc_num="12052-7",
        snomed_ct="100200052",
        component="Diagnostic Analyte Component 02-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_053": ClinicalConcept_02(
        concept_id="CONCEPT_02_053",
        loinc_num="12053-8",
        snomed_ct="100200053",
        component="Diagnostic Analyte Component 02-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_054": ClinicalConcept_02(
        concept_id="CONCEPT_02_054",
        loinc_num="12054-0",
        snomed_ct="100200054",
        component="Diagnostic Analyte Component 02-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_055": ClinicalConcept_02(
        concept_id="CONCEPT_02_055",
        loinc_num="12055-1",
        snomed_ct="100200055",
        component="Diagnostic Analyte Component 02-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_056": ClinicalConcept_02(
        concept_id="CONCEPT_02_056",
        loinc_num="12056-2",
        snomed_ct="100200056",
        component="Diagnostic Analyte Component 02-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_057": ClinicalConcept_02(
        concept_id="CONCEPT_02_057",
        loinc_num="12057-3",
        snomed_ct="100200057",
        component="Diagnostic Analyte Component 02-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_058": ClinicalConcept_02(
        concept_id="CONCEPT_02_058",
        loinc_num="12058-4",
        snomed_ct="100200058",
        component="Diagnostic Analyte Component 02-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_059": ClinicalConcept_02(
        concept_id="CONCEPT_02_059",
        loinc_num="12059-5",
        snomed_ct="100200059",
        component="Diagnostic Analyte Component 02-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_060": ClinicalConcept_02(
        concept_id="CONCEPT_02_060",
        loinc_num="12060-6",
        snomed_ct="100200060",
        component="Diagnostic Analyte Component 02-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_061": ClinicalConcept_02(
        concept_id="CONCEPT_02_061",
        loinc_num="12061-7",
        snomed_ct="100200061",
        component="Diagnostic Analyte Component 02-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_062": ClinicalConcept_02(
        concept_id="CONCEPT_02_062",
        loinc_num="12062-8",
        snomed_ct="100200062",
        component="Diagnostic Analyte Component 02-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_063": ClinicalConcept_02(
        concept_id="CONCEPT_02_063",
        loinc_num="12063-0",
        snomed_ct="100200063",
        component="Diagnostic Analyte Component 02-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_064": ClinicalConcept_02(
        concept_id="CONCEPT_02_064",
        loinc_num="12064-1",
        snomed_ct="100200064",
        component="Diagnostic Analyte Component 02-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_065": ClinicalConcept_02(
        concept_id="CONCEPT_02_065",
        loinc_num="12065-2",
        snomed_ct="100200065",
        component="Diagnostic Analyte Component 02-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_066": ClinicalConcept_02(
        concept_id="CONCEPT_02_066",
        loinc_num="12066-3",
        snomed_ct="100200066",
        component="Diagnostic Analyte Component 02-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_067": ClinicalConcept_02(
        concept_id="CONCEPT_02_067",
        loinc_num="12067-4",
        snomed_ct="100200067",
        component="Diagnostic Analyte Component 02-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_068": ClinicalConcept_02(
        concept_id="CONCEPT_02_068",
        loinc_num="12068-5",
        snomed_ct="100200068",
        component="Diagnostic Analyte Component 02-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_069": ClinicalConcept_02(
        concept_id="CONCEPT_02_069",
        loinc_num="12069-6",
        snomed_ct="100200069",
        component="Diagnostic Analyte Component 02-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_070": ClinicalConcept_02(
        concept_id="CONCEPT_02_070",
        loinc_num="12070-7",
        snomed_ct="100200070",
        component="Diagnostic Analyte Component 02-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_071": ClinicalConcept_02(
        concept_id="CONCEPT_02_071",
        loinc_num="12071-8",
        snomed_ct="100200071",
        component="Diagnostic Analyte Component 02-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_072": ClinicalConcept_02(
        concept_id="CONCEPT_02_072",
        loinc_num="12072-0",
        snomed_ct="100200072",
        component="Diagnostic Analyte Component 02-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_073": ClinicalConcept_02(
        concept_id="CONCEPT_02_073",
        loinc_num="12073-1",
        snomed_ct="100200073",
        component="Diagnostic Analyte Component 02-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_074": ClinicalConcept_02(
        concept_id="CONCEPT_02_074",
        loinc_num="12074-2",
        snomed_ct="100200074",
        component="Diagnostic Analyte Component 02-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_075": ClinicalConcept_02(
        concept_id="CONCEPT_02_075",
        loinc_num="12075-3",
        snomed_ct="100200075",
        component="Diagnostic Analyte Component 02-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_076": ClinicalConcept_02(
        concept_id="CONCEPT_02_076",
        loinc_num="12076-4",
        snomed_ct="100200076",
        component="Diagnostic Analyte Component 02-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_077": ClinicalConcept_02(
        concept_id="CONCEPT_02_077",
        loinc_num="12077-5",
        snomed_ct="100200077",
        component="Diagnostic Analyte Component 02-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_078": ClinicalConcept_02(
        concept_id="CONCEPT_02_078",
        loinc_num="12078-6",
        snomed_ct="100200078",
        component="Diagnostic Analyte Component 02-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_079": ClinicalConcept_02(
        concept_id="CONCEPT_02_079",
        loinc_num="12079-7",
        snomed_ct="100200079",
        component="Diagnostic Analyte Component 02-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_080": ClinicalConcept_02(
        concept_id="CONCEPT_02_080",
        loinc_num="12080-8",
        snomed_ct="100200080",
        component="Diagnostic Analyte Component 02-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_081": ClinicalConcept_02(
        concept_id="CONCEPT_02_081",
        loinc_num="12081-0",
        snomed_ct="100200081",
        component="Diagnostic Analyte Component 02-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_082": ClinicalConcept_02(
        concept_id="CONCEPT_02_082",
        loinc_num="12082-1",
        snomed_ct="100200082",
        component="Diagnostic Analyte Component 02-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_083": ClinicalConcept_02(
        concept_id="CONCEPT_02_083",
        loinc_num="12083-2",
        snomed_ct="100200083",
        component="Diagnostic Analyte Component 02-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_084": ClinicalConcept_02(
        concept_id="CONCEPT_02_084",
        loinc_num="12084-3",
        snomed_ct="100200084",
        component="Diagnostic Analyte Component 02-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_085": ClinicalConcept_02(
        concept_id="CONCEPT_02_085",
        loinc_num="12085-4",
        snomed_ct="100200085",
        component="Diagnostic Analyte Component 02-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_086": ClinicalConcept_02(
        concept_id="CONCEPT_02_086",
        loinc_num="12086-5",
        snomed_ct="100200086",
        component="Diagnostic Analyte Component 02-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_087": ClinicalConcept_02(
        concept_id="CONCEPT_02_087",
        loinc_num="12087-6",
        snomed_ct="100200087",
        component="Diagnostic Analyte Component 02-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_088": ClinicalConcept_02(
        concept_id="CONCEPT_02_088",
        loinc_num="12088-7",
        snomed_ct="100200088",
        component="Diagnostic Analyte Component 02-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_089": ClinicalConcept_02(
        concept_id="CONCEPT_02_089",
        loinc_num="12089-8",
        snomed_ct="100200089",
        component="Diagnostic Analyte Component 02-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_090": ClinicalConcept_02(
        concept_id="CONCEPT_02_090",
        loinc_num="12090-0",
        snomed_ct="100200090",
        component="Diagnostic Analyte Component 02-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_091": ClinicalConcept_02(
        concept_id="CONCEPT_02_091",
        loinc_num="12091-1",
        snomed_ct="100200091",
        component="Diagnostic Analyte Component 02-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_092": ClinicalConcept_02(
        concept_id="CONCEPT_02_092",
        loinc_num="12092-2",
        snomed_ct="100200092",
        component="Diagnostic Analyte Component 02-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_093": ClinicalConcept_02(
        concept_id="CONCEPT_02_093",
        loinc_num="12093-3",
        snomed_ct="100200093",
        component="Diagnostic Analyte Component 02-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_094": ClinicalConcept_02(
        concept_id="CONCEPT_02_094",
        loinc_num="12094-4",
        snomed_ct="100200094",
        component="Diagnostic Analyte Component 02-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_095": ClinicalConcept_02(
        concept_id="CONCEPT_02_095",
        loinc_num="12095-5",
        snomed_ct="100200095",
        component="Diagnostic Analyte Component 02-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_096": ClinicalConcept_02(
        concept_id="CONCEPT_02_096",
        loinc_num="12096-6",
        snomed_ct="100200096",
        component="Diagnostic Analyte Component 02-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_097": ClinicalConcept_02(
        concept_id="CONCEPT_02_097",
        loinc_num="12097-7",
        snomed_ct="100200097",
        component="Diagnostic Analyte Component 02-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_098": ClinicalConcept_02(
        concept_id="CONCEPT_02_098",
        loinc_num="12098-8",
        snomed_ct="100200098",
        component="Diagnostic Analyte Component 02-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_099": ClinicalConcept_02(
        concept_id="CONCEPT_02_099",
        loinc_num="12099-0",
        snomed_ct="100200099",
        component="Diagnostic Analyte Component 02-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_100": ClinicalConcept_02(
        concept_id="CONCEPT_02_100",
        loinc_num="12100-1",
        snomed_ct="100200100",
        component="Diagnostic Analyte Component 02-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_101": ClinicalConcept_02(
        concept_id="CONCEPT_02_101",
        loinc_num="12101-2",
        snomed_ct="100200101",
        component="Diagnostic Analyte Component 02-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_102": ClinicalConcept_02(
        concept_id="CONCEPT_02_102",
        loinc_num="12102-3",
        snomed_ct="100200102",
        component="Diagnostic Analyte Component 02-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_103": ClinicalConcept_02(
        concept_id="CONCEPT_02_103",
        loinc_num="12103-4",
        snomed_ct="100200103",
        component="Diagnostic Analyte Component 02-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_104": ClinicalConcept_02(
        concept_id="CONCEPT_02_104",
        loinc_num="12104-5",
        snomed_ct="100200104",
        component="Diagnostic Analyte Component 02-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_105": ClinicalConcept_02(
        concept_id="CONCEPT_02_105",
        loinc_num="12105-6",
        snomed_ct="100200105",
        component="Diagnostic Analyte Component 02-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_106": ClinicalConcept_02(
        concept_id="CONCEPT_02_106",
        loinc_num="12106-7",
        snomed_ct="100200106",
        component="Diagnostic Analyte Component 02-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_107": ClinicalConcept_02(
        concept_id="CONCEPT_02_107",
        loinc_num="12107-8",
        snomed_ct="100200107",
        component="Diagnostic Analyte Component 02-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_108": ClinicalConcept_02(
        concept_id="CONCEPT_02_108",
        loinc_num="12108-0",
        snomed_ct="100200108",
        component="Diagnostic Analyte Component 02-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_109": ClinicalConcept_02(
        concept_id="CONCEPT_02_109",
        loinc_num="12109-1",
        snomed_ct="100200109",
        component="Diagnostic Analyte Component 02-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_110": ClinicalConcept_02(
        concept_id="CONCEPT_02_110",
        loinc_num="12110-2",
        snomed_ct="100200110",
        component="Diagnostic Analyte Component 02-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_111": ClinicalConcept_02(
        concept_id="CONCEPT_02_111",
        loinc_num="12111-3",
        snomed_ct="100200111",
        component="Diagnostic Analyte Component 02-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_112": ClinicalConcept_02(
        concept_id="CONCEPT_02_112",
        loinc_num="12112-4",
        snomed_ct="100200112",
        component="Diagnostic Analyte Component 02-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_113": ClinicalConcept_02(
        concept_id="CONCEPT_02_113",
        loinc_num="12113-5",
        snomed_ct="100200113",
        component="Diagnostic Analyte Component 02-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_114": ClinicalConcept_02(
        concept_id="CONCEPT_02_114",
        loinc_num="12114-6",
        snomed_ct="100200114",
        component="Diagnostic Analyte Component 02-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_115": ClinicalConcept_02(
        concept_id="CONCEPT_02_115",
        loinc_num="12115-7",
        snomed_ct="100200115",
        component="Diagnostic Analyte Component 02-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_116": ClinicalConcept_02(
        concept_id="CONCEPT_02_116",
        loinc_num="12116-8",
        snomed_ct="100200116",
        component="Diagnostic Analyte Component 02-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_117": ClinicalConcept_02(
        concept_id="CONCEPT_02_117",
        loinc_num="12117-0",
        snomed_ct="100200117",
        component="Diagnostic Analyte Component 02-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_118": ClinicalConcept_02(
        concept_id="CONCEPT_02_118",
        loinc_num="12118-1",
        snomed_ct="100200118",
        component="Diagnostic Analyte Component 02-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_119": ClinicalConcept_02(
        concept_id="CONCEPT_02_119",
        loinc_num="12119-2",
        snomed_ct="100200119",
        component="Diagnostic Analyte Component 02-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_120": ClinicalConcept_02(
        concept_id="CONCEPT_02_120",
        loinc_num="12120-3",
        snomed_ct="100200120",
        component="Diagnostic Analyte Component 02-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_121": ClinicalConcept_02(
        concept_id="CONCEPT_02_121",
        loinc_num="12121-4",
        snomed_ct="100200121",
        component="Diagnostic Analyte Component 02-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_122": ClinicalConcept_02(
        concept_id="CONCEPT_02_122",
        loinc_num="12122-5",
        snomed_ct="100200122",
        component="Diagnostic Analyte Component 02-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_123": ClinicalConcept_02(
        concept_id="CONCEPT_02_123",
        loinc_num="12123-6",
        snomed_ct="100200123",
        component="Diagnostic Analyte Component 02-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_124": ClinicalConcept_02(
        concept_id="CONCEPT_02_124",
        loinc_num="12124-7",
        snomed_ct="100200124",
        component="Diagnostic Analyte Component 02-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_125": ClinicalConcept_02(
        concept_id="CONCEPT_02_125",
        loinc_num="12125-8",
        snomed_ct="100200125",
        component="Diagnostic Analyte Component 02-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_126": ClinicalConcept_02(
        concept_id="CONCEPT_02_126",
        loinc_num="12126-0",
        snomed_ct="100200126",
        component="Diagnostic Analyte Component 02-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_127": ClinicalConcept_02(
        concept_id="CONCEPT_02_127",
        loinc_num="12127-1",
        snomed_ct="100200127",
        component="Diagnostic Analyte Component 02-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_128": ClinicalConcept_02(
        concept_id="CONCEPT_02_128",
        loinc_num="12128-2",
        snomed_ct="100200128",
        component="Diagnostic Analyte Component 02-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_129": ClinicalConcept_02(
        concept_id="CONCEPT_02_129",
        loinc_num="12129-3",
        snomed_ct="100200129",
        component="Diagnostic Analyte Component 02-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_130": ClinicalConcept_02(
        concept_id="CONCEPT_02_130",
        loinc_num="12130-4",
        snomed_ct="100200130",
        component="Diagnostic Analyte Component 02-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_131": ClinicalConcept_02(
        concept_id="CONCEPT_02_131",
        loinc_num="12131-5",
        snomed_ct="100200131",
        component="Diagnostic Analyte Component 02-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_132": ClinicalConcept_02(
        concept_id="CONCEPT_02_132",
        loinc_num="12132-6",
        snomed_ct="100200132",
        component="Diagnostic Analyte Component 02-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_133": ClinicalConcept_02(
        concept_id="CONCEPT_02_133",
        loinc_num="12133-7",
        snomed_ct="100200133",
        component="Diagnostic Analyte Component 02-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_134": ClinicalConcept_02(
        concept_id="CONCEPT_02_134",
        loinc_num="12134-8",
        snomed_ct="100200134",
        component="Diagnostic Analyte Component 02-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_135": ClinicalConcept_02(
        concept_id="CONCEPT_02_135",
        loinc_num="12135-0",
        snomed_ct="100200135",
        component="Diagnostic Analyte Component 02-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_136": ClinicalConcept_02(
        concept_id="CONCEPT_02_136",
        loinc_num="12136-1",
        snomed_ct="100200136",
        component="Diagnostic Analyte Component 02-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_137": ClinicalConcept_02(
        concept_id="CONCEPT_02_137",
        loinc_num="12137-2",
        snomed_ct="100200137",
        component="Diagnostic Analyte Component 02-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_138": ClinicalConcept_02(
        concept_id="CONCEPT_02_138",
        loinc_num="12138-3",
        snomed_ct="100200138",
        component="Diagnostic Analyte Component 02-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_139": ClinicalConcept_02(
        concept_id="CONCEPT_02_139",
        loinc_num="12139-4",
        snomed_ct="100200139",
        component="Diagnostic Analyte Component 02-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_140": ClinicalConcept_02(
        concept_id="CONCEPT_02_140",
        loinc_num="12140-5",
        snomed_ct="100200140",
        component="Diagnostic Analyte Component 02-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_141": ClinicalConcept_02(
        concept_id="CONCEPT_02_141",
        loinc_num="12141-6",
        snomed_ct="100200141",
        component="Diagnostic Analyte Component 02-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_142": ClinicalConcept_02(
        concept_id="CONCEPT_02_142",
        loinc_num="12142-7",
        snomed_ct="100200142",
        component="Diagnostic Analyte Component 02-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_143": ClinicalConcept_02(
        concept_id="CONCEPT_02_143",
        loinc_num="12143-8",
        snomed_ct="100200143",
        component="Diagnostic Analyte Component 02-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_144": ClinicalConcept_02(
        concept_id="CONCEPT_02_144",
        loinc_num="12144-0",
        snomed_ct="100200144",
        component="Diagnostic Analyte Component 02-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_145": ClinicalConcept_02(
        concept_id="CONCEPT_02_145",
        loinc_num="12145-1",
        snomed_ct="100200145",
        component="Diagnostic Analyte Component 02-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_146": ClinicalConcept_02(
        concept_id="CONCEPT_02_146",
        loinc_num="12146-2",
        snomed_ct="100200146",
        component="Diagnostic Analyte Component 02-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_147": ClinicalConcept_02(
        concept_id="CONCEPT_02_147",
        loinc_num="12147-3",
        snomed_ct="100200147",
        component="Diagnostic Analyte Component 02-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_148": ClinicalConcept_02(
        concept_id="CONCEPT_02_148",
        loinc_num="12148-4",
        snomed_ct="100200148",
        component="Diagnostic Analyte Component 02-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_149": ClinicalConcept_02(
        concept_id="CONCEPT_02_149",
        loinc_num="12149-5",
        snomed_ct="100200149",
        component="Diagnostic Analyte Component 02-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_150": ClinicalConcept_02(
        concept_id="CONCEPT_02_150",
        loinc_num="12150-6",
        snomed_ct="100200150",
        component="Diagnostic Analyte Component 02-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_151": ClinicalConcept_02(
        concept_id="CONCEPT_02_151",
        loinc_num="12151-7",
        snomed_ct="100200151",
        component="Diagnostic Analyte Component 02-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_152": ClinicalConcept_02(
        concept_id="CONCEPT_02_152",
        loinc_num="12152-8",
        snomed_ct="100200152",
        component="Diagnostic Analyte Component 02-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_153": ClinicalConcept_02(
        concept_id="CONCEPT_02_153",
        loinc_num="12153-0",
        snomed_ct="100200153",
        component="Diagnostic Analyte Component 02-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_154": ClinicalConcept_02(
        concept_id="CONCEPT_02_154",
        loinc_num="12154-1",
        snomed_ct="100200154",
        component="Diagnostic Analyte Component 02-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_155": ClinicalConcept_02(
        concept_id="CONCEPT_02_155",
        loinc_num="12155-2",
        snomed_ct="100200155",
        component="Diagnostic Analyte Component 02-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_156": ClinicalConcept_02(
        concept_id="CONCEPT_02_156",
        loinc_num="12156-3",
        snomed_ct="100200156",
        component="Diagnostic Analyte Component 02-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_157": ClinicalConcept_02(
        concept_id="CONCEPT_02_157",
        loinc_num="12157-4",
        snomed_ct="100200157",
        component="Diagnostic Analyte Component 02-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_158": ClinicalConcept_02(
        concept_id="CONCEPT_02_158",
        loinc_num="12158-5",
        snomed_ct="100200158",
        component="Diagnostic Analyte Component 02-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_159": ClinicalConcept_02(
        concept_id="CONCEPT_02_159",
        loinc_num="12159-6",
        snomed_ct="100200159",
        component="Diagnostic Analyte Component 02-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_160": ClinicalConcept_02(
        concept_id="CONCEPT_02_160",
        loinc_num="12160-7",
        snomed_ct="100200160",
        component="Diagnostic Analyte Component 02-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_161": ClinicalConcept_02(
        concept_id="CONCEPT_02_161",
        loinc_num="12161-8",
        snomed_ct="100200161",
        component="Diagnostic Analyte Component 02-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_162": ClinicalConcept_02(
        concept_id="CONCEPT_02_162",
        loinc_num="12162-0",
        snomed_ct="100200162",
        component="Diagnostic Analyte Component 02-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_163": ClinicalConcept_02(
        concept_id="CONCEPT_02_163",
        loinc_num="12163-1",
        snomed_ct="100200163",
        component="Diagnostic Analyte Component 02-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_164": ClinicalConcept_02(
        concept_id="CONCEPT_02_164",
        loinc_num="12164-2",
        snomed_ct="100200164",
        component="Diagnostic Analyte Component 02-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_165": ClinicalConcept_02(
        concept_id="CONCEPT_02_165",
        loinc_num="12165-3",
        snomed_ct="100200165",
        component="Diagnostic Analyte Component 02-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_166": ClinicalConcept_02(
        concept_id="CONCEPT_02_166",
        loinc_num="12166-4",
        snomed_ct="100200166",
        component="Diagnostic Analyte Component 02-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_167": ClinicalConcept_02(
        concept_id="CONCEPT_02_167",
        loinc_num="12167-5",
        snomed_ct="100200167",
        component="Diagnostic Analyte Component 02-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_168": ClinicalConcept_02(
        concept_id="CONCEPT_02_168",
        loinc_num="12168-6",
        snomed_ct="100200168",
        component="Diagnostic Analyte Component 02-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_169": ClinicalConcept_02(
        concept_id="CONCEPT_02_169",
        loinc_num="12169-7",
        snomed_ct="100200169",
        component="Diagnostic Analyte Component 02-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_170": ClinicalConcept_02(
        concept_id="CONCEPT_02_170",
        loinc_num="12170-8",
        snomed_ct="100200170",
        component="Diagnostic Analyte Component 02-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_171": ClinicalConcept_02(
        concept_id="CONCEPT_02_171",
        loinc_num="12171-0",
        snomed_ct="100200171",
        component="Diagnostic Analyte Component 02-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_172": ClinicalConcept_02(
        concept_id="CONCEPT_02_172",
        loinc_num="12172-1",
        snomed_ct="100200172",
        component="Diagnostic Analyte Component 02-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_173": ClinicalConcept_02(
        concept_id="CONCEPT_02_173",
        loinc_num="12173-2",
        snomed_ct="100200173",
        component="Diagnostic Analyte Component 02-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_174": ClinicalConcept_02(
        concept_id="CONCEPT_02_174",
        loinc_num="12174-3",
        snomed_ct="100200174",
        component="Diagnostic Analyte Component 02-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_175": ClinicalConcept_02(
        concept_id="CONCEPT_02_175",
        loinc_num="12175-4",
        snomed_ct="100200175",
        component="Diagnostic Analyte Component 02-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_176": ClinicalConcept_02(
        concept_id="CONCEPT_02_176",
        loinc_num="12176-5",
        snomed_ct="100200176",
        component="Diagnostic Analyte Component 02-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_177": ClinicalConcept_02(
        concept_id="CONCEPT_02_177",
        loinc_num="12177-6",
        snomed_ct="100200177",
        component="Diagnostic Analyte Component 02-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_178": ClinicalConcept_02(
        concept_id="CONCEPT_02_178",
        loinc_num="12178-7",
        snomed_ct="100200178",
        component="Diagnostic Analyte Component 02-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_179": ClinicalConcept_02(
        concept_id="CONCEPT_02_179",
        loinc_num="12179-8",
        snomed_ct="100200179",
        component="Diagnostic Analyte Component 02-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_180": ClinicalConcept_02(
        concept_id="CONCEPT_02_180",
        loinc_num="12180-0",
        snomed_ct="100200180",
        component="Diagnostic Analyte Component 02-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_181": ClinicalConcept_02(
        concept_id="CONCEPT_02_181",
        loinc_num="12181-1",
        snomed_ct="100200181",
        component="Diagnostic Analyte Component 02-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_182": ClinicalConcept_02(
        concept_id="CONCEPT_02_182",
        loinc_num="12182-2",
        snomed_ct="100200182",
        component="Diagnostic Analyte Component 02-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_183": ClinicalConcept_02(
        concept_id="CONCEPT_02_183",
        loinc_num="12183-3",
        snomed_ct="100200183",
        component="Diagnostic Analyte Component 02-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_184": ClinicalConcept_02(
        concept_id="CONCEPT_02_184",
        loinc_num="12184-4",
        snomed_ct="100200184",
        component="Diagnostic Analyte Component 02-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_185": ClinicalConcept_02(
        concept_id="CONCEPT_02_185",
        loinc_num="12185-5",
        snomed_ct="100200185",
        component="Diagnostic Analyte Component 02-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_186": ClinicalConcept_02(
        concept_id="CONCEPT_02_186",
        loinc_num="12186-6",
        snomed_ct="100200186",
        component="Diagnostic Analyte Component 02-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_187": ClinicalConcept_02(
        concept_id="CONCEPT_02_187",
        loinc_num="12187-7",
        snomed_ct="100200187",
        component="Diagnostic Analyte Component 02-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_188": ClinicalConcept_02(
        concept_id="CONCEPT_02_188",
        loinc_num="12188-8",
        snomed_ct="100200188",
        component="Diagnostic Analyte Component 02-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_189": ClinicalConcept_02(
        concept_id="CONCEPT_02_189",
        loinc_num="12189-0",
        snomed_ct="100200189",
        component="Diagnostic Analyte Component 02-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_190": ClinicalConcept_02(
        concept_id="CONCEPT_02_190",
        loinc_num="12190-1",
        snomed_ct="100200190",
        component="Diagnostic Analyte Component 02-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_191": ClinicalConcept_02(
        concept_id="CONCEPT_02_191",
        loinc_num="12191-2",
        snomed_ct="100200191",
        component="Diagnostic Analyte Component 02-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_192": ClinicalConcept_02(
        concept_id="CONCEPT_02_192",
        loinc_num="12192-3",
        snomed_ct="100200192",
        component="Diagnostic Analyte Component 02-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_193": ClinicalConcept_02(
        concept_id="CONCEPT_02_193",
        loinc_num="12193-4",
        snomed_ct="100200193",
        component="Diagnostic Analyte Component 02-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_194": ClinicalConcept_02(
        concept_id="CONCEPT_02_194",
        loinc_num="12194-5",
        snomed_ct="100200194",
        component="Diagnostic Analyte Component 02-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_195": ClinicalConcept_02(
        concept_id="CONCEPT_02_195",
        loinc_num="12195-6",
        snomed_ct="100200195",
        component="Diagnostic Analyte Component 02-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_196": ClinicalConcept_02(
        concept_id="CONCEPT_02_196",
        loinc_num="12196-7",
        snomed_ct="100200196",
        component="Diagnostic Analyte Component 02-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_197": ClinicalConcept_02(
        concept_id="CONCEPT_02_197",
        loinc_num="12197-8",
        snomed_ct="100200197",
        component="Diagnostic Analyte Component 02-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_198": ClinicalConcept_02(
        concept_id="CONCEPT_02_198",
        loinc_num="12198-0",
        snomed_ct="100200198",
        component="Diagnostic Analyte Component 02-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_02_199": ClinicalConcept_02(
        concept_id="CONCEPT_02_199",
        loinc_num="12199-1",
        snomed_ct="100200199",
        component="Diagnostic Analyte Component 02-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
