"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 17"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_17:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_17 = {
    "CONCEPT_17_001": ClinicalConcept_17(
        concept_id="CONCEPT_17_001",
        loinc_num="27001-1",
        snomed_ct="101700001",
        component="Diagnostic Analyte Component 17-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_002": ClinicalConcept_17(
        concept_id="CONCEPT_17_002",
        loinc_num="27002-2",
        snomed_ct="101700002",
        component="Diagnostic Analyte Component 17-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_003": ClinicalConcept_17(
        concept_id="CONCEPT_17_003",
        loinc_num="27003-3",
        snomed_ct="101700003",
        component="Diagnostic Analyte Component 17-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_004": ClinicalConcept_17(
        concept_id="CONCEPT_17_004",
        loinc_num="27004-4",
        snomed_ct="101700004",
        component="Diagnostic Analyte Component 17-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_005": ClinicalConcept_17(
        concept_id="CONCEPT_17_005",
        loinc_num="27005-5",
        snomed_ct="101700005",
        component="Diagnostic Analyte Component 17-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_006": ClinicalConcept_17(
        concept_id="CONCEPT_17_006",
        loinc_num="27006-6",
        snomed_ct="101700006",
        component="Diagnostic Analyte Component 17-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_007": ClinicalConcept_17(
        concept_id="CONCEPT_17_007",
        loinc_num="27007-7",
        snomed_ct="101700007",
        component="Diagnostic Analyte Component 17-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_008": ClinicalConcept_17(
        concept_id="CONCEPT_17_008",
        loinc_num="27008-8",
        snomed_ct="101700008",
        component="Diagnostic Analyte Component 17-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_009": ClinicalConcept_17(
        concept_id="CONCEPT_17_009",
        loinc_num="27009-0",
        snomed_ct="101700009",
        component="Diagnostic Analyte Component 17-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_010": ClinicalConcept_17(
        concept_id="CONCEPT_17_010",
        loinc_num="27010-1",
        snomed_ct="101700010",
        component="Diagnostic Analyte Component 17-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_011": ClinicalConcept_17(
        concept_id="CONCEPT_17_011",
        loinc_num="27011-2",
        snomed_ct="101700011",
        component="Diagnostic Analyte Component 17-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_012": ClinicalConcept_17(
        concept_id="CONCEPT_17_012",
        loinc_num="27012-3",
        snomed_ct="101700012",
        component="Diagnostic Analyte Component 17-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_013": ClinicalConcept_17(
        concept_id="CONCEPT_17_013",
        loinc_num="27013-4",
        snomed_ct="101700013",
        component="Diagnostic Analyte Component 17-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_014": ClinicalConcept_17(
        concept_id="CONCEPT_17_014",
        loinc_num="27014-5",
        snomed_ct="101700014",
        component="Diagnostic Analyte Component 17-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_015": ClinicalConcept_17(
        concept_id="CONCEPT_17_015",
        loinc_num="27015-6",
        snomed_ct="101700015",
        component="Diagnostic Analyte Component 17-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_016": ClinicalConcept_17(
        concept_id="CONCEPT_17_016",
        loinc_num="27016-7",
        snomed_ct="101700016",
        component="Diagnostic Analyte Component 17-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_017": ClinicalConcept_17(
        concept_id="CONCEPT_17_017",
        loinc_num="27017-8",
        snomed_ct="101700017",
        component="Diagnostic Analyte Component 17-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_018": ClinicalConcept_17(
        concept_id="CONCEPT_17_018",
        loinc_num="27018-0",
        snomed_ct="101700018",
        component="Diagnostic Analyte Component 17-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_019": ClinicalConcept_17(
        concept_id="CONCEPT_17_019",
        loinc_num="27019-1",
        snomed_ct="101700019",
        component="Diagnostic Analyte Component 17-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_020": ClinicalConcept_17(
        concept_id="CONCEPT_17_020",
        loinc_num="27020-2",
        snomed_ct="101700020",
        component="Diagnostic Analyte Component 17-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_021": ClinicalConcept_17(
        concept_id="CONCEPT_17_021",
        loinc_num="27021-3",
        snomed_ct="101700021",
        component="Diagnostic Analyte Component 17-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_022": ClinicalConcept_17(
        concept_id="CONCEPT_17_022",
        loinc_num="27022-4",
        snomed_ct="101700022",
        component="Diagnostic Analyte Component 17-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_023": ClinicalConcept_17(
        concept_id="CONCEPT_17_023",
        loinc_num="27023-5",
        snomed_ct="101700023",
        component="Diagnostic Analyte Component 17-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_024": ClinicalConcept_17(
        concept_id="CONCEPT_17_024",
        loinc_num="27024-6",
        snomed_ct="101700024",
        component="Diagnostic Analyte Component 17-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_025": ClinicalConcept_17(
        concept_id="CONCEPT_17_025",
        loinc_num="27025-7",
        snomed_ct="101700025",
        component="Diagnostic Analyte Component 17-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_026": ClinicalConcept_17(
        concept_id="CONCEPT_17_026",
        loinc_num="27026-8",
        snomed_ct="101700026",
        component="Diagnostic Analyte Component 17-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_027": ClinicalConcept_17(
        concept_id="CONCEPT_17_027",
        loinc_num="27027-0",
        snomed_ct="101700027",
        component="Diagnostic Analyte Component 17-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_028": ClinicalConcept_17(
        concept_id="CONCEPT_17_028",
        loinc_num="27028-1",
        snomed_ct="101700028",
        component="Diagnostic Analyte Component 17-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_029": ClinicalConcept_17(
        concept_id="CONCEPT_17_029",
        loinc_num="27029-2",
        snomed_ct="101700029",
        component="Diagnostic Analyte Component 17-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_030": ClinicalConcept_17(
        concept_id="CONCEPT_17_030",
        loinc_num="27030-3",
        snomed_ct="101700030",
        component="Diagnostic Analyte Component 17-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_031": ClinicalConcept_17(
        concept_id="CONCEPT_17_031",
        loinc_num="27031-4",
        snomed_ct="101700031",
        component="Diagnostic Analyte Component 17-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_032": ClinicalConcept_17(
        concept_id="CONCEPT_17_032",
        loinc_num="27032-5",
        snomed_ct="101700032",
        component="Diagnostic Analyte Component 17-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_033": ClinicalConcept_17(
        concept_id="CONCEPT_17_033",
        loinc_num="27033-6",
        snomed_ct="101700033",
        component="Diagnostic Analyte Component 17-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_034": ClinicalConcept_17(
        concept_id="CONCEPT_17_034",
        loinc_num="27034-7",
        snomed_ct="101700034",
        component="Diagnostic Analyte Component 17-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_035": ClinicalConcept_17(
        concept_id="CONCEPT_17_035",
        loinc_num="27035-8",
        snomed_ct="101700035",
        component="Diagnostic Analyte Component 17-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_036": ClinicalConcept_17(
        concept_id="CONCEPT_17_036",
        loinc_num="27036-0",
        snomed_ct="101700036",
        component="Diagnostic Analyte Component 17-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_037": ClinicalConcept_17(
        concept_id="CONCEPT_17_037",
        loinc_num="27037-1",
        snomed_ct="101700037",
        component="Diagnostic Analyte Component 17-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_038": ClinicalConcept_17(
        concept_id="CONCEPT_17_038",
        loinc_num="27038-2",
        snomed_ct="101700038",
        component="Diagnostic Analyte Component 17-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_039": ClinicalConcept_17(
        concept_id="CONCEPT_17_039",
        loinc_num="27039-3",
        snomed_ct="101700039",
        component="Diagnostic Analyte Component 17-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_040": ClinicalConcept_17(
        concept_id="CONCEPT_17_040",
        loinc_num="27040-4",
        snomed_ct="101700040",
        component="Diagnostic Analyte Component 17-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_041": ClinicalConcept_17(
        concept_id="CONCEPT_17_041",
        loinc_num="27041-5",
        snomed_ct="101700041",
        component="Diagnostic Analyte Component 17-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_042": ClinicalConcept_17(
        concept_id="CONCEPT_17_042",
        loinc_num="27042-6",
        snomed_ct="101700042",
        component="Diagnostic Analyte Component 17-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_043": ClinicalConcept_17(
        concept_id="CONCEPT_17_043",
        loinc_num="27043-7",
        snomed_ct="101700043",
        component="Diagnostic Analyte Component 17-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_044": ClinicalConcept_17(
        concept_id="CONCEPT_17_044",
        loinc_num="27044-8",
        snomed_ct="101700044",
        component="Diagnostic Analyte Component 17-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_045": ClinicalConcept_17(
        concept_id="CONCEPT_17_045",
        loinc_num="27045-0",
        snomed_ct="101700045",
        component="Diagnostic Analyte Component 17-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_046": ClinicalConcept_17(
        concept_id="CONCEPT_17_046",
        loinc_num="27046-1",
        snomed_ct="101700046",
        component="Diagnostic Analyte Component 17-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_047": ClinicalConcept_17(
        concept_id="CONCEPT_17_047",
        loinc_num="27047-2",
        snomed_ct="101700047",
        component="Diagnostic Analyte Component 17-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_048": ClinicalConcept_17(
        concept_id="CONCEPT_17_048",
        loinc_num="27048-3",
        snomed_ct="101700048",
        component="Diagnostic Analyte Component 17-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_049": ClinicalConcept_17(
        concept_id="CONCEPT_17_049",
        loinc_num="27049-4",
        snomed_ct="101700049",
        component="Diagnostic Analyte Component 17-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_050": ClinicalConcept_17(
        concept_id="CONCEPT_17_050",
        loinc_num="27050-5",
        snomed_ct="101700050",
        component="Diagnostic Analyte Component 17-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_051": ClinicalConcept_17(
        concept_id="CONCEPT_17_051",
        loinc_num="27051-6",
        snomed_ct="101700051",
        component="Diagnostic Analyte Component 17-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_052": ClinicalConcept_17(
        concept_id="CONCEPT_17_052",
        loinc_num="27052-7",
        snomed_ct="101700052",
        component="Diagnostic Analyte Component 17-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_053": ClinicalConcept_17(
        concept_id="CONCEPT_17_053",
        loinc_num="27053-8",
        snomed_ct="101700053",
        component="Diagnostic Analyte Component 17-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_054": ClinicalConcept_17(
        concept_id="CONCEPT_17_054",
        loinc_num="27054-0",
        snomed_ct="101700054",
        component="Diagnostic Analyte Component 17-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_055": ClinicalConcept_17(
        concept_id="CONCEPT_17_055",
        loinc_num="27055-1",
        snomed_ct="101700055",
        component="Diagnostic Analyte Component 17-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_056": ClinicalConcept_17(
        concept_id="CONCEPT_17_056",
        loinc_num="27056-2",
        snomed_ct="101700056",
        component="Diagnostic Analyte Component 17-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_057": ClinicalConcept_17(
        concept_id="CONCEPT_17_057",
        loinc_num="27057-3",
        snomed_ct="101700057",
        component="Diagnostic Analyte Component 17-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_058": ClinicalConcept_17(
        concept_id="CONCEPT_17_058",
        loinc_num="27058-4",
        snomed_ct="101700058",
        component="Diagnostic Analyte Component 17-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_059": ClinicalConcept_17(
        concept_id="CONCEPT_17_059",
        loinc_num="27059-5",
        snomed_ct="101700059",
        component="Diagnostic Analyte Component 17-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_060": ClinicalConcept_17(
        concept_id="CONCEPT_17_060",
        loinc_num="27060-6",
        snomed_ct="101700060",
        component="Diagnostic Analyte Component 17-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_061": ClinicalConcept_17(
        concept_id="CONCEPT_17_061",
        loinc_num="27061-7",
        snomed_ct="101700061",
        component="Diagnostic Analyte Component 17-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_062": ClinicalConcept_17(
        concept_id="CONCEPT_17_062",
        loinc_num="27062-8",
        snomed_ct="101700062",
        component="Diagnostic Analyte Component 17-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_063": ClinicalConcept_17(
        concept_id="CONCEPT_17_063",
        loinc_num="27063-0",
        snomed_ct="101700063",
        component="Diagnostic Analyte Component 17-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_064": ClinicalConcept_17(
        concept_id="CONCEPT_17_064",
        loinc_num="27064-1",
        snomed_ct="101700064",
        component="Diagnostic Analyte Component 17-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_065": ClinicalConcept_17(
        concept_id="CONCEPT_17_065",
        loinc_num="27065-2",
        snomed_ct="101700065",
        component="Diagnostic Analyte Component 17-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_066": ClinicalConcept_17(
        concept_id="CONCEPT_17_066",
        loinc_num="27066-3",
        snomed_ct="101700066",
        component="Diagnostic Analyte Component 17-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_067": ClinicalConcept_17(
        concept_id="CONCEPT_17_067",
        loinc_num="27067-4",
        snomed_ct="101700067",
        component="Diagnostic Analyte Component 17-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_068": ClinicalConcept_17(
        concept_id="CONCEPT_17_068",
        loinc_num="27068-5",
        snomed_ct="101700068",
        component="Diagnostic Analyte Component 17-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_069": ClinicalConcept_17(
        concept_id="CONCEPT_17_069",
        loinc_num="27069-6",
        snomed_ct="101700069",
        component="Diagnostic Analyte Component 17-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_070": ClinicalConcept_17(
        concept_id="CONCEPT_17_070",
        loinc_num="27070-7",
        snomed_ct="101700070",
        component="Diagnostic Analyte Component 17-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_071": ClinicalConcept_17(
        concept_id="CONCEPT_17_071",
        loinc_num="27071-8",
        snomed_ct="101700071",
        component="Diagnostic Analyte Component 17-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_072": ClinicalConcept_17(
        concept_id="CONCEPT_17_072",
        loinc_num="27072-0",
        snomed_ct="101700072",
        component="Diagnostic Analyte Component 17-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_073": ClinicalConcept_17(
        concept_id="CONCEPT_17_073",
        loinc_num="27073-1",
        snomed_ct="101700073",
        component="Diagnostic Analyte Component 17-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_074": ClinicalConcept_17(
        concept_id="CONCEPT_17_074",
        loinc_num="27074-2",
        snomed_ct="101700074",
        component="Diagnostic Analyte Component 17-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_075": ClinicalConcept_17(
        concept_id="CONCEPT_17_075",
        loinc_num="27075-3",
        snomed_ct="101700075",
        component="Diagnostic Analyte Component 17-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_076": ClinicalConcept_17(
        concept_id="CONCEPT_17_076",
        loinc_num="27076-4",
        snomed_ct="101700076",
        component="Diagnostic Analyte Component 17-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_077": ClinicalConcept_17(
        concept_id="CONCEPT_17_077",
        loinc_num="27077-5",
        snomed_ct="101700077",
        component="Diagnostic Analyte Component 17-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_078": ClinicalConcept_17(
        concept_id="CONCEPT_17_078",
        loinc_num="27078-6",
        snomed_ct="101700078",
        component="Diagnostic Analyte Component 17-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_079": ClinicalConcept_17(
        concept_id="CONCEPT_17_079",
        loinc_num="27079-7",
        snomed_ct="101700079",
        component="Diagnostic Analyte Component 17-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_080": ClinicalConcept_17(
        concept_id="CONCEPT_17_080",
        loinc_num="27080-8",
        snomed_ct="101700080",
        component="Diagnostic Analyte Component 17-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_081": ClinicalConcept_17(
        concept_id="CONCEPT_17_081",
        loinc_num="27081-0",
        snomed_ct="101700081",
        component="Diagnostic Analyte Component 17-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_082": ClinicalConcept_17(
        concept_id="CONCEPT_17_082",
        loinc_num="27082-1",
        snomed_ct="101700082",
        component="Diagnostic Analyte Component 17-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_083": ClinicalConcept_17(
        concept_id="CONCEPT_17_083",
        loinc_num="27083-2",
        snomed_ct="101700083",
        component="Diagnostic Analyte Component 17-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_084": ClinicalConcept_17(
        concept_id="CONCEPT_17_084",
        loinc_num="27084-3",
        snomed_ct="101700084",
        component="Diagnostic Analyte Component 17-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_085": ClinicalConcept_17(
        concept_id="CONCEPT_17_085",
        loinc_num="27085-4",
        snomed_ct="101700085",
        component="Diagnostic Analyte Component 17-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_086": ClinicalConcept_17(
        concept_id="CONCEPT_17_086",
        loinc_num="27086-5",
        snomed_ct="101700086",
        component="Diagnostic Analyte Component 17-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_087": ClinicalConcept_17(
        concept_id="CONCEPT_17_087",
        loinc_num="27087-6",
        snomed_ct="101700087",
        component="Diagnostic Analyte Component 17-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_088": ClinicalConcept_17(
        concept_id="CONCEPT_17_088",
        loinc_num="27088-7",
        snomed_ct="101700088",
        component="Diagnostic Analyte Component 17-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_089": ClinicalConcept_17(
        concept_id="CONCEPT_17_089",
        loinc_num="27089-8",
        snomed_ct="101700089",
        component="Diagnostic Analyte Component 17-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_090": ClinicalConcept_17(
        concept_id="CONCEPT_17_090",
        loinc_num="27090-0",
        snomed_ct="101700090",
        component="Diagnostic Analyte Component 17-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_091": ClinicalConcept_17(
        concept_id="CONCEPT_17_091",
        loinc_num="27091-1",
        snomed_ct="101700091",
        component="Diagnostic Analyte Component 17-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_092": ClinicalConcept_17(
        concept_id="CONCEPT_17_092",
        loinc_num="27092-2",
        snomed_ct="101700092",
        component="Diagnostic Analyte Component 17-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_093": ClinicalConcept_17(
        concept_id="CONCEPT_17_093",
        loinc_num="27093-3",
        snomed_ct="101700093",
        component="Diagnostic Analyte Component 17-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_094": ClinicalConcept_17(
        concept_id="CONCEPT_17_094",
        loinc_num="27094-4",
        snomed_ct="101700094",
        component="Diagnostic Analyte Component 17-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_095": ClinicalConcept_17(
        concept_id="CONCEPT_17_095",
        loinc_num="27095-5",
        snomed_ct="101700095",
        component="Diagnostic Analyte Component 17-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_096": ClinicalConcept_17(
        concept_id="CONCEPT_17_096",
        loinc_num="27096-6",
        snomed_ct="101700096",
        component="Diagnostic Analyte Component 17-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_097": ClinicalConcept_17(
        concept_id="CONCEPT_17_097",
        loinc_num="27097-7",
        snomed_ct="101700097",
        component="Diagnostic Analyte Component 17-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_098": ClinicalConcept_17(
        concept_id="CONCEPT_17_098",
        loinc_num="27098-8",
        snomed_ct="101700098",
        component="Diagnostic Analyte Component 17-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_099": ClinicalConcept_17(
        concept_id="CONCEPT_17_099",
        loinc_num="27099-0",
        snomed_ct="101700099",
        component="Diagnostic Analyte Component 17-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_100": ClinicalConcept_17(
        concept_id="CONCEPT_17_100",
        loinc_num="27100-1",
        snomed_ct="101700100",
        component="Diagnostic Analyte Component 17-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_101": ClinicalConcept_17(
        concept_id="CONCEPT_17_101",
        loinc_num="27101-2",
        snomed_ct="101700101",
        component="Diagnostic Analyte Component 17-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_102": ClinicalConcept_17(
        concept_id="CONCEPT_17_102",
        loinc_num="27102-3",
        snomed_ct="101700102",
        component="Diagnostic Analyte Component 17-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_103": ClinicalConcept_17(
        concept_id="CONCEPT_17_103",
        loinc_num="27103-4",
        snomed_ct="101700103",
        component="Diagnostic Analyte Component 17-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_104": ClinicalConcept_17(
        concept_id="CONCEPT_17_104",
        loinc_num="27104-5",
        snomed_ct="101700104",
        component="Diagnostic Analyte Component 17-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_105": ClinicalConcept_17(
        concept_id="CONCEPT_17_105",
        loinc_num="27105-6",
        snomed_ct="101700105",
        component="Diagnostic Analyte Component 17-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_106": ClinicalConcept_17(
        concept_id="CONCEPT_17_106",
        loinc_num="27106-7",
        snomed_ct="101700106",
        component="Diagnostic Analyte Component 17-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_107": ClinicalConcept_17(
        concept_id="CONCEPT_17_107",
        loinc_num="27107-8",
        snomed_ct="101700107",
        component="Diagnostic Analyte Component 17-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_108": ClinicalConcept_17(
        concept_id="CONCEPT_17_108",
        loinc_num="27108-0",
        snomed_ct="101700108",
        component="Diagnostic Analyte Component 17-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_109": ClinicalConcept_17(
        concept_id="CONCEPT_17_109",
        loinc_num="27109-1",
        snomed_ct="101700109",
        component="Diagnostic Analyte Component 17-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_110": ClinicalConcept_17(
        concept_id="CONCEPT_17_110",
        loinc_num="27110-2",
        snomed_ct="101700110",
        component="Diagnostic Analyte Component 17-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_111": ClinicalConcept_17(
        concept_id="CONCEPT_17_111",
        loinc_num="27111-3",
        snomed_ct="101700111",
        component="Diagnostic Analyte Component 17-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_112": ClinicalConcept_17(
        concept_id="CONCEPT_17_112",
        loinc_num="27112-4",
        snomed_ct="101700112",
        component="Diagnostic Analyte Component 17-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_113": ClinicalConcept_17(
        concept_id="CONCEPT_17_113",
        loinc_num="27113-5",
        snomed_ct="101700113",
        component="Diagnostic Analyte Component 17-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_114": ClinicalConcept_17(
        concept_id="CONCEPT_17_114",
        loinc_num="27114-6",
        snomed_ct="101700114",
        component="Diagnostic Analyte Component 17-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_115": ClinicalConcept_17(
        concept_id="CONCEPT_17_115",
        loinc_num="27115-7",
        snomed_ct="101700115",
        component="Diagnostic Analyte Component 17-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_116": ClinicalConcept_17(
        concept_id="CONCEPT_17_116",
        loinc_num="27116-8",
        snomed_ct="101700116",
        component="Diagnostic Analyte Component 17-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_117": ClinicalConcept_17(
        concept_id="CONCEPT_17_117",
        loinc_num="27117-0",
        snomed_ct="101700117",
        component="Diagnostic Analyte Component 17-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_118": ClinicalConcept_17(
        concept_id="CONCEPT_17_118",
        loinc_num="27118-1",
        snomed_ct="101700118",
        component="Diagnostic Analyte Component 17-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_119": ClinicalConcept_17(
        concept_id="CONCEPT_17_119",
        loinc_num="27119-2",
        snomed_ct="101700119",
        component="Diagnostic Analyte Component 17-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_120": ClinicalConcept_17(
        concept_id="CONCEPT_17_120",
        loinc_num="27120-3",
        snomed_ct="101700120",
        component="Diagnostic Analyte Component 17-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_121": ClinicalConcept_17(
        concept_id="CONCEPT_17_121",
        loinc_num="27121-4",
        snomed_ct="101700121",
        component="Diagnostic Analyte Component 17-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_122": ClinicalConcept_17(
        concept_id="CONCEPT_17_122",
        loinc_num="27122-5",
        snomed_ct="101700122",
        component="Diagnostic Analyte Component 17-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_123": ClinicalConcept_17(
        concept_id="CONCEPT_17_123",
        loinc_num="27123-6",
        snomed_ct="101700123",
        component="Diagnostic Analyte Component 17-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_124": ClinicalConcept_17(
        concept_id="CONCEPT_17_124",
        loinc_num="27124-7",
        snomed_ct="101700124",
        component="Diagnostic Analyte Component 17-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_125": ClinicalConcept_17(
        concept_id="CONCEPT_17_125",
        loinc_num="27125-8",
        snomed_ct="101700125",
        component="Diagnostic Analyte Component 17-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_126": ClinicalConcept_17(
        concept_id="CONCEPT_17_126",
        loinc_num="27126-0",
        snomed_ct="101700126",
        component="Diagnostic Analyte Component 17-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_127": ClinicalConcept_17(
        concept_id="CONCEPT_17_127",
        loinc_num="27127-1",
        snomed_ct="101700127",
        component="Diagnostic Analyte Component 17-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_128": ClinicalConcept_17(
        concept_id="CONCEPT_17_128",
        loinc_num="27128-2",
        snomed_ct="101700128",
        component="Diagnostic Analyte Component 17-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_129": ClinicalConcept_17(
        concept_id="CONCEPT_17_129",
        loinc_num="27129-3",
        snomed_ct="101700129",
        component="Diagnostic Analyte Component 17-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_130": ClinicalConcept_17(
        concept_id="CONCEPT_17_130",
        loinc_num="27130-4",
        snomed_ct="101700130",
        component="Diagnostic Analyte Component 17-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_131": ClinicalConcept_17(
        concept_id="CONCEPT_17_131",
        loinc_num="27131-5",
        snomed_ct="101700131",
        component="Diagnostic Analyte Component 17-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_132": ClinicalConcept_17(
        concept_id="CONCEPT_17_132",
        loinc_num="27132-6",
        snomed_ct="101700132",
        component="Diagnostic Analyte Component 17-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_133": ClinicalConcept_17(
        concept_id="CONCEPT_17_133",
        loinc_num="27133-7",
        snomed_ct="101700133",
        component="Diagnostic Analyte Component 17-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_134": ClinicalConcept_17(
        concept_id="CONCEPT_17_134",
        loinc_num="27134-8",
        snomed_ct="101700134",
        component="Diagnostic Analyte Component 17-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_135": ClinicalConcept_17(
        concept_id="CONCEPT_17_135",
        loinc_num="27135-0",
        snomed_ct="101700135",
        component="Diagnostic Analyte Component 17-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_136": ClinicalConcept_17(
        concept_id="CONCEPT_17_136",
        loinc_num="27136-1",
        snomed_ct="101700136",
        component="Diagnostic Analyte Component 17-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_137": ClinicalConcept_17(
        concept_id="CONCEPT_17_137",
        loinc_num="27137-2",
        snomed_ct="101700137",
        component="Diagnostic Analyte Component 17-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_138": ClinicalConcept_17(
        concept_id="CONCEPT_17_138",
        loinc_num="27138-3",
        snomed_ct="101700138",
        component="Diagnostic Analyte Component 17-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_139": ClinicalConcept_17(
        concept_id="CONCEPT_17_139",
        loinc_num="27139-4",
        snomed_ct="101700139",
        component="Diagnostic Analyte Component 17-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_140": ClinicalConcept_17(
        concept_id="CONCEPT_17_140",
        loinc_num="27140-5",
        snomed_ct="101700140",
        component="Diagnostic Analyte Component 17-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_141": ClinicalConcept_17(
        concept_id="CONCEPT_17_141",
        loinc_num="27141-6",
        snomed_ct="101700141",
        component="Diagnostic Analyte Component 17-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_142": ClinicalConcept_17(
        concept_id="CONCEPT_17_142",
        loinc_num="27142-7",
        snomed_ct="101700142",
        component="Diagnostic Analyte Component 17-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_143": ClinicalConcept_17(
        concept_id="CONCEPT_17_143",
        loinc_num="27143-8",
        snomed_ct="101700143",
        component="Diagnostic Analyte Component 17-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_144": ClinicalConcept_17(
        concept_id="CONCEPT_17_144",
        loinc_num="27144-0",
        snomed_ct="101700144",
        component="Diagnostic Analyte Component 17-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_145": ClinicalConcept_17(
        concept_id="CONCEPT_17_145",
        loinc_num="27145-1",
        snomed_ct="101700145",
        component="Diagnostic Analyte Component 17-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_146": ClinicalConcept_17(
        concept_id="CONCEPT_17_146",
        loinc_num="27146-2",
        snomed_ct="101700146",
        component="Diagnostic Analyte Component 17-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_147": ClinicalConcept_17(
        concept_id="CONCEPT_17_147",
        loinc_num="27147-3",
        snomed_ct="101700147",
        component="Diagnostic Analyte Component 17-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_148": ClinicalConcept_17(
        concept_id="CONCEPT_17_148",
        loinc_num="27148-4",
        snomed_ct="101700148",
        component="Diagnostic Analyte Component 17-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_149": ClinicalConcept_17(
        concept_id="CONCEPT_17_149",
        loinc_num="27149-5",
        snomed_ct="101700149",
        component="Diagnostic Analyte Component 17-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_150": ClinicalConcept_17(
        concept_id="CONCEPT_17_150",
        loinc_num="27150-6",
        snomed_ct="101700150",
        component="Diagnostic Analyte Component 17-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_151": ClinicalConcept_17(
        concept_id="CONCEPT_17_151",
        loinc_num="27151-7",
        snomed_ct="101700151",
        component="Diagnostic Analyte Component 17-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_152": ClinicalConcept_17(
        concept_id="CONCEPT_17_152",
        loinc_num="27152-8",
        snomed_ct="101700152",
        component="Diagnostic Analyte Component 17-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_153": ClinicalConcept_17(
        concept_id="CONCEPT_17_153",
        loinc_num="27153-0",
        snomed_ct="101700153",
        component="Diagnostic Analyte Component 17-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_154": ClinicalConcept_17(
        concept_id="CONCEPT_17_154",
        loinc_num="27154-1",
        snomed_ct="101700154",
        component="Diagnostic Analyte Component 17-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_155": ClinicalConcept_17(
        concept_id="CONCEPT_17_155",
        loinc_num="27155-2",
        snomed_ct="101700155",
        component="Diagnostic Analyte Component 17-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_156": ClinicalConcept_17(
        concept_id="CONCEPT_17_156",
        loinc_num="27156-3",
        snomed_ct="101700156",
        component="Diagnostic Analyte Component 17-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_157": ClinicalConcept_17(
        concept_id="CONCEPT_17_157",
        loinc_num="27157-4",
        snomed_ct="101700157",
        component="Diagnostic Analyte Component 17-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_158": ClinicalConcept_17(
        concept_id="CONCEPT_17_158",
        loinc_num="27158-5",
        snomed_ct="101700158",
        component="Diagnostic Analyte Component 17-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_159": ClinicalConcept_17(
        concept_id="CONCEPT_17_159",
        loinc_num="27159-6",
        snomed_ct="101700159",
        component="Diagnostic Analyte Component 17-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_160": ClinicalConcept_17(
        concept_id="CONCEPT_17_160",
        loinc_num="27160-7",
        snomed_ct="101700160",
        component="Diagnostic Analyte Component 17-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_161": ClinicalConcept_17(
        concept_id="CONCEPT_17_161",
        loinc_num="27161-8",
        snomed_ct="101700161",
        component="Diagnostic Analyte Component 17-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_162": ClinicalConcept_17(
        concept_id="CONCEPT_17_162",
        loinc_num="27162-0",
        snomed_ct="101700162",
        component="Diagnostic Analyte Component 17-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_163": ClinicalConcept_17(
        concept_id="CONCEPT_17_163",
        loinc_num="27163-1",
        snomed_ct="101700163",
        component="Diagnostic Analyte Component 17-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_164": ClinicalConcept_17(
        concept_id="CONCEPT_17_164",
        loinc_num="27164-2",
        snomed_ct="101700164",
        component="Diagnostic Analyte Component 17-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_165": ClinicalConcept_17(
        concept_id="CONCEPT_17_165",
        loinc_num="27165-3",
        snomed_ct="101700165",
        component="Diagnostic Analyte Component 17-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_166": ClinicalConcept_17(
        concept_id="CONCEPT_17_166",
        loinc_num="27166-4",
        snomed_ct="101700166",
        component="Diagnostic Analyte Component 17-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_167": ClinicalConcept_17(
        concept_id="CONCEPT_17_167",
        loinc_num="27167-5",
        snomed_ct="101700167",
        component="Diagnostic Analyte Component 17-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_168": ClinicalConcept_17(
        concept_id="CONCEPT_17_168",
        loinc_num="27168-6",
        snomed_ct="101700168",
        component="Diagnostic Analyte Component 17-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_169": ClinicalConcept_17(
        concept_id="CONCEPT_17_169",
        loinc_num="27169-7",
        snomed_ct="101700169",
        component="Diagnostic Analyte Component 17-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_170": ClinicalConcept_17(
        concept_id="CONCEPT_17_170",
        loinc_num="27170-8",
        snomed_ct="101700170",
        component="Diagnostic Analyte Component 17-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_171": ClinicalConcept_17(
        concept_id="CONCEPT_17_171",
        loinc_num="27171-0",
        snomed_ct="101700171",
        component="Diagnostic Analyte Component 17-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_172": ClinicalConcept_17(
        concept_id="CONCEPT_17_172",
        loinc_num="27172-1",
        snomed_ct="101700172",
        component="Diagnostic Analyte Component 17-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_173": ClinicalConcept_17(
        concept_id="CONCEPT_17_173",
        loinc_num="27173-2",
        snomed_ct="101700173",
        component="Diagnostic Analyte Component 17-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_174": ClinicalConcept_17(
        concept_id="CONCEPT_17_174",
        loinc_num="27174-3",
        snomed_ct="101700174",
        component="Diagnostic Analyte Component 17-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_175": ClinicalConcept_17(
        concept_id="CONCEPT_17_175",
        loinc_num="27175-4",
        snomed_ct="101700175",
        component="Diagnostic Analyte Component 17-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_176": ClinicalConcept_17(
        concept_id="CONCEPT_17_176",
        loinc_num="27176-5",
        snomed_ct="101700176",
        component="Diagnostic Analyte Component 17-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_177": ClinicalConcept_17(
        concept_id="CONCEPT_17_177",
        loinc_num="27177-6",
        snomed_ct="101700177",
        component="Diagnostic Analyte Component 17-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_178": ClinicalConcept_17(
        concept_id="CONCEPT_17_178",
        loinc_num="27178-7",
        snomed_ct="101700178",
        component="Diagnostic Analyte Component 17-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_179": ClinicalConcept_17(
        concept_id="CONCEPT_17_179",
        loinc_num="27179-8",
        snomed_ct="101700179",
        component="Diagnostic Analyte Component 17-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_180": ClinicalConcept_17(
        concept_id="CONCEPT_17_180",
        loinc_num="27180-0",
        snomed_ct="101700180",
        component="Diagnostic Analyte Component 17-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_181": ClinicalConcept_17(
        concept_id="CONCEPT_17_181",
        loinc_num="27181-1",
        snomed_ct="101700181",
        component="Diagnostic Analyte Component 17-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_182": ClinicalConcept_17(
        concept_id="CONCEPT_17_182",
        loinc_num="27182-2",
        snomed_ct="101700182",
        component="Diagnostic Analyte Component 17-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_183": ClinicalConcept_17(
        concept_id="CONCEPT_17_183",
        loinc_num="27183-3",
        snomed_ct="101700183",
        component="Diagnostic Analyte Component 17-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_184": ClinicalConcept_17(
        concept_id="CONCEPT_17_184",
        loinc_num="27184-4",
        snomed_ct="101700184",
        component="Diagnostic Analyte Component 17-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_185": ClinicalConcept_17(
        concept_id="CONCEPT_17_185",
        loinc_num="27185-5",
        snomed_ct="101700185",
        component="Diagnostic Analyte Component 17-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_186": ClinicalConcept_17(
        concept_id="CONCEPT_17_186",
        loinc_num="27186-6",
        snomed_ct="101700186",
        component="Diagnostic Analyte Component 17-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_187": ClinicalConcept_17(
        concept_id="CONCEPT_17_187",
        loinc_num="27187-7",
        snomed_ct="101700187",
        component="Diagnostic Analyte Component 17-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_188": ClinicalConcept_17(
        concept_id="CONCEPT_17_188",
        loinc_num="27188-8",
        snomed_ct="101700188",
        component="Diagnostic Analyte Component 17-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_189": ClinicalConcept_17(
        concept_id="CONCEPT_17_189",
        loinc_num="27189-0",
        snomed_ct="101700189",
        component="Diagnostic Analyte Component 17-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_190": ClinicalConcept_17(
        concept_id="CONCEPT_17_190",
        loinc_num="27190-1",
        snomed_ct="101700190",
        component="Diagnostic Analyte Component 17-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_191": ClinicalConcept_17(
        concept_id="CONCEPT_17_191",
        loinc_num="27191-2",
        snomed_ct="101700191",
        component="Diagnostic Analyte Component 17-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_192": ClinicalConcept_17(
        concept_id="CONCEPT_17_192",
        loinc_num="27192-3",
        snomed_ct="101700192",
        component="Diagnostic Analyte Component 17-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_193": ClinicalConcept_17(
        concept_id="CONCEPT_17_193",
        loinc_num="27193-4",
        snomed_ct="101700193",
        component="Diagnostic Analyte Component 17-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_194": ClinicalConcept_17(
        concept_id="CONCEPT_17_194",
        loinc_num="27194-5",
        snomed_ct="101700194",
        component="Diagnostic Analyte Component 17-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_195": ClinicalConcept_17(
        concept_id="CONCEPT_17_195",
        loinc_num="27195-6",
        snomed_ct="101700195",
        component="Diagnostic Analyte Component 17-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_196": ClinicalConcept_17(
        concept_id="CONCEPT_17_196",
        loinc_num="27196-7",
        snomed_ct="101700196",
        component="Diagnostic Analyte Component 17-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_197": ClinicalConcept_17(
        concept_id="CONCEPT_17_197",
        loinc_num="27197-8",
        snomed_ct="101700197",
        component="Diagnostic Analyte Component 17-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_198": ClinicalConcept_17(
        concept_id="CONCEPT_17_198",
        loinc_num="27198-0",
        snomed_ct="101700198",
        component="Diagnostic Analyte Component 17-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_17_199": ClinicalConcept_17(
        concept_id="CONCEPT_17_199",
        loinc_num="27199-1",
        snomed_ct="101700199",
        component="Diagnostic Analyte Component 17-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
