"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 19"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_19:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_19 = {
    "CONCEPT_19_001": ClinicalConcept_19(
        concept_id="CONCEPT_19_001",
        loinc_num="29001-1",
        snomed_ct="101900001",
        component="Diagnostic Analyte Component 19-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_002": ClinicalConcept_19(
        concept_id="CONCEPT_19_002",
        loinc_num="29002-2",
        snomed_ct="101900002",
        component="Diagnostic Analyte Component 19-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_003": ClinicalConcept_19(
        concept_id="CONCEPT_19_003",
        loinc_num="29003-3",
        snomed_ct="101900003",
        component="Diagnostic Analyte Component 19-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_004": ClinicalConcept_19(
        concept_id="CONCEPT_19_004",
        loinc_num="29004-4",
        snomed_ct="101900004",
        component="Diagnostic Analyte Component 19-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_005": ClinicalConcept_19(
        concept_id="CONCEPT_19_005",
        loinc_num="29005-5",
        snomed_ct="101900005",
        component="Diagnostic Analyte Component 19-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_006": ClinicalConcept_19(
        concept_id="CONCEPT_19_006",
        loinc_num="29006-6",
        snomed_ct="101900006",
        component="Diagnostic Analyte Component 19-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_007": ClinicalConcept_19(
        concept_id="CONCEPT_19_007",
        loinc_num="29007-7",
        snomed_ct="101900007",
        component="Diagnostic Analyte Component 19-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_008": ClinicalConcept_19(
        concept_id="CONCEPT_19_008",
        loinc_num="29008-8",
        snomed_ct="101900008",
        component="Diagnostic Analyte Component 19-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_009": ClinicalConcept_19(
        concept_id="CONCEPT_19_009",
        loinc_num="29009-0",
        snomed_ct="101900009",
        component="Diagnostic Analyte Component 19-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_010": ClinicalConcept_19(
        concept_id="CONCEPT_19_010",
        loinc_num="29010-1",
        snomed_ct="101900010",
        component="Diagnostic Analyte Component 19-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_011": ClinicalConcept_19(
        concept_id="CONCEPT_19_011",
        loinc_num="29011-2",
        snomed_ct="101900011",
        component="Diagnostic Analyte Component 19-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_012": ClinicalConcept_19(
        concept_id="CONCEPT_19_012",
        loinc_num="29012-3",
        snomed_ct="101900012",
        component="Diagnostic Analyte Component 19-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_013": ClinicalConcept_19(
        concept_id="CONCEPT_19_013",
        loinc_num="29013-4",
        snomed_ct="101900013",
        component="Diagnostic Analyte Component 19-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_014": ClinicalConcept_19(
        concept_id="CONCEPT_19_014",
        loinc_num="29014-5",
        snomed_ct="101900014",
        component="Diagnostic Analyte Component 19-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_015": ClinicalConcept_19(
        concept_id="CONCEPT_19_015",
        loinc_num="29015-6",
        snomed_ct="101900015",
        component="Diagnostic Analyte Component 19-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_016": ClinicalConcept_19(
        concept_id="CONCEPT_19_016",
        loinc_num="29016-7",
        snomed_ct="101900016",
        component="Diagnostic Analyte Component 19-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_017": ClinicalConcept_19(
        concept_id="CONCEPT_19_017",
        loinc_num="29017-8",
        snomed_ct="101900017",
        component="Diagnostic Analyte Component 19-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_018": ClinicalConcept_19(
        concept_id="CONCEPT_19_018",
        loinc_num="29018-0",
        snomed_ct="101900018",
        component="Diagnostic Analyte Component 19-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_019": ClinicalConcept_19(
        concept_id="CONCEPT_19_019",
        loinc_num="29019-1",
        snomed_ct="101900019",
        component="Diagnostic Analyte Component 19-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_020": ClinicalConcept_19(
        concept_id="CONCEPT_19_020",
        loinc_num="29020-2",
        snomed_ct="101900020",
        component="Diagnostic Analyte Component 19-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_021": ClinicalConcept_19(
        concept_id="CONCEPT_19_021",
        loinc_num="29021-3",
        snomed_ct="101900021",
        component="Diagnostic Analyte Component 19-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_022": ClinicalConcept_19(
        concept_id="CONCEPT_19_022",
        loinc_num="29022-4",
        snomed_ct="101900022",
        component="Diagnostic Analyte Component 19-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_023": ClinicalConcept_19(
        concept_id="CONCEPT_19_023",
        loinc_num="29023-5",
        snomed_ct="101900023",
        component="Diagnostic Analyte Component 19-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_024": ClinicalConcept_19(
        concept_id="CONCEPT_19_024",
        loinc_num="29024-6",
        snomed_ct="101900024",
        component="Diagnostic Analyte Component 19-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_025": ClinicalConcept_19(
        concept_id="CONCEPT_19_025",
        loinc_num="29025-7",
        snomed_ct="101900025",
        component="Diagnostic Analyte Component 19-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_026": ClinicalConcept_19(
        concept_id="CONCEPT_19_026",
        loinc_num="29026-8",
        snomed_ct="101900026",
        component="Diagnostic Analyte Component 19-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_027": ClinicalConcept_19(
        concept_id="CONCEPT_19_027",
        loinc_num="29027-0",
        snomed_ct="101900027",
        component="Diagnostic Analyte Component 19-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_028": ClinicalConcept_19(
        concept_id="CONCEPT_19_028",
        loinc_num="29028-1",
        snomed_ct="101900028",
        component="Diagnostic Analyte Component 19-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_029": ClinicalConcept_19(
        concept_id="CONCEPT_19_029",
        loinc_num="29029-2",
        snomed_ct="101900029",
        component="Diagnostic Analyte Component 19-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_030": ClinicalConcept_19(
        concept_id="CONCEPT_19_030",
        loinc_num="29030-3",
        snomed_ct="101900030",
        component="Diagnostic Analyte Component 19-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_031": ClinicalConcept_19(
        concept_id="CONCEPT_19_031",
        loinc_num="29031-4",
        snomed_ct="101900031",
        component="Diagnostic Analyte Component 19-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_032": ClinicalConcept_19(
        concept_id="CONCEPT_19_032",
        loinc_num="29032-5",
        snomed_ct="101900032",
        component="Diagnostic Analyte Component 19-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_033": ClinicalConcept_19(
        concept_id="CONCEPT_19_033",
        loinc_num="29033-6",
        snomed_ct="101900033",
        component="Diagnostic Analyte Component 19-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_034": ClinicalConcept_19(
        concept_id="CONCEPT_19_034",
        loinc_num="29034-7",
        snomed_ct="101900034",
        component="Diagnostic Analyte Component 19-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_035": ClinicalConcept_19(
        concept_id="CONCEPT_19_035",
        loinc_num="29035-8",
        snomed_ct="101900035",
        component="Diagnostic Analyte Component 19-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_036": ClinicalConcept_19(
        concept_id="CONCEPT_19_036",
        loinc_num="29036-0",
        snomed_ct="101900036",
        component="Diagnostic Analyte Component 19-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_037": ClinicalConcept_19(
        concept_id="CONCEPT_19_037",
        loinc_num="29037-1",
        snomed_ct="101900037",
        component="Diagnostic Analyte Component 19-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_038": ClinicalConcept_19(
        concept_id="CONCEPT_19_038",
        loinc_num="29038-2",
        snomed_ct="101900038",
        component="Diagnostic Analyte Component 19-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_039": ClinicalConcept_19(
        concept_id="CONCEPT_19_039",
        loinc_num="29039-3",
        snomed_ct="101900039",
        component="Diagnostic Analyte Component 19-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_040": ClinicalConcept_19(
        concept_id="CONCEPT_19_040",
        loinc_num="29040-4",
        snomed_ct="101900040",
        component="Diagnostic Analyte Component 19-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_041": ClinicalConcept_19(
        concept_id="CONCEPT_19_041",
        loinc_num="29041-5",
        snomed_ct="101900041",
        component="Diagnostic Analyte Component 19-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_042": ClinicalConcept_19(
        concept_id="CONCEPT_19_042",
        loinc_num="29042-6",
        snomed_ct="101900042",
        component="Diagnostic Analyte Component 19-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_043": ClinicalConcept_19(
        concept_id="CONCEPT_19_043",
        loinc_num="29043-7",
        snomed_ct="101900043",
        component="Diagnostic Analyte Component 19-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_044": ClinicalConcept_19(
        concept_id="CONCEPT_19_044",
        loinc_num="29044-8",
        snomed_ct="101900044",
        component="Diagnostic Analyte Component 19-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_045": ClinicalConcept_19(
        concept_id="CONCEPT_19_045",
        loinc_num="29045-0",
        snomed_ct="101900045",
        component="Diagnostic Analyte Component 19-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_046": ClinicalConcept_19(
        concept_id="CONCEPT_19_046",
        loinc_num="29046-1",
        snomed_ct="101900046",
        component="Diagnostic Analyte Component 19-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_047": ClinicalConcept_19(
        concept_id="CONCEPT_19_047",
        loinc_num="29047-2",
        snomed_ct="101900047",
        component="Diagnostic Analyte Component 19-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_048": ClinicalConcept_19(
        concept_id="CONCEPT_19_048",
        loinc_num="29048-3",
        snomed_ct="101900048",
        component="Diagnostic Analyte Component 19-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_049": ClinicalConcept_19(
        concept_id="CONCEPT_19_049",
        loinc_num="29049-4",
        snomed_ct="101900049",
        component="Diagnostic Analyte Component 19-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_050": ClinicalConcept_19(
        concept_id="CONCEPT_19_050",
        loinc_num="29050-5",
        snomed_ct="101900050",
        component="Diagnostic Analyte Component 19-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_051": ClinicalConcept_19(
        concept_id="CONCEPT_19_051",
        loinc_num="29051-6",
        snomed_ct="101900051",
        component="Diagnostic Analyte Component 19-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_052": ClinicalConcept_19(
        concept_id="CONCEPT_19_052",
        loinc_num="29052-7",
        snomed_ct="101900052",
        component="Diagnostic Analyte Component 19-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_053": ClinicalConcept_19(
        concept_id="CONCEPT_19_053",
        loinc_num="29053-8",
        snomed_ct="101900053",
        component="Diagnostic Analyte Component 19-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_054": ClinicalConcept_19(
        concept_id="CONCEPT_19_054",
        loinc_num="29054-0",
        snomed_ct="101900054",
        component="Diagnostic Analyte Component 19-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_055": ClinicalConcept_19(
        concept_id="CONCEPT_19_055",
        loinc_num="29055-1",
        snomed_ct="101900055",
        component="Diagnostic Analyte Component 19-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_056": ClinicalConcept_19(
        concept_id="CONCEPT_19_056",
        loinc_num="29056-2",
        snomed_ct="101900056",
        component="Diagnostic Analyte Component 19-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_057": ClinicalConcept_19(
        concept_id="CONCEPT_19_057",
        loinc_num="29057-3",
        snomed_ct="101900057",
        component="Diagnostic Analyte Component 19-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_058": ClinicalConcept_19(
        concept_id="CONCEPT_19_058",
        loinc_num="29058-4",
        snomed_ct="101900058",
        component="Diagnostic Analyte Component 19-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_059": ClinicalConcept_19(
        concept_id="CONCEPT_19_059",
        loinc_num="29059-5",
        snomed_ct="101900059",
        component="Diagnostic Analyte Component 19-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_060": ClinicalConcept_19(
        concept_id="CONCEPT_19_060",
        loinc_num="29060-6",
        snomed_ct="101900060",
        component="Diagnostic Analyte Component 19-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_061": ClinicalConcept_19(
        concept_id="CONCEPT_19_061",
        loinc_num="29061-7",
        snomed_ct="101900061",
        component="Diagnostic Analyte Component 19-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_062": ClinicalConcept_19(
        concept_id="CONCEPT_19_062",
        loinc_num="29062-8",
        snomed_ct="101900062",
        component="Diagnostic Analyte Component 19-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_063": ClinicalConcept_19(
        concept_id="CONCEPT_19_063",
        loinc_num="29063-0",
        snomed_ct="101900063",
        component="Diagnostic Analyte Component 19-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_064": ClinicalConcept_19(
        concept_id="CONCEPT_19_064",
        loinc_num="29064-1",
        snomed_ct="101900064",
        component="Diagnostic Analyte Component 19-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_065": ClinicalConcept_19(
        concept_id="CONCEPT_19_065",
        loinc_num="29065-2",
        snomed_ct="101900065",
        component="Diagnostic Analyte Component 19-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_066": ClinicalConcept_19(
        concept_id="CONCEPT_19_066",
        loinc_num="29066-3",
        snomed_ct="101900066",
        component="Diagnostic Analyte Component 19-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_067": ClinicalConcept_19(
        concept_id="CONCEPT_19_067",
        loinc_num="29067-4",
        snomed_ct="101900067",
        component="Diagnostic Analyte Component 19-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_068": ClinicalConcept_19(
        concept_id="CONCEPT_19_068",
        loinc_num="29068-5",
        snomed_ct="101900068",
        component="Diagnostic Analyte Component 19-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_069": ClinicalConcept_19(
        concept_id="CONCEPT_19_069",
        loinc_num="29069-6",
        snomed_ct="101900069",
        component="Diagnostic Analyte Component 19-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_070": ClinicalConcept_19(
        concept_id="CONCEPT_19_070",
        loinc_num="29070-7",
        snomed_ct="101900070",
        component="Diagnostic Analyte Component 19-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_071": ClinicalConcept_19(
        concept_id="CONCEPT_19_071",
        loinc_num="29071-8",
        snomed_ct="101900071",
        component="Diagnostic Analyte Component 19-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_072": ClinicalConcept_19(
        concept_id="CONCEPT_19_072",
        loinc_num="29072-0",
        snomed_ct="101900072",
        component="Diagnostic Analyte Component 19-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_073": ClinicalConcept_19(
        concept_id="CONCEPT_19_073",
        loinc_num="29073-1",
        snomed_ct="101900073",
        component="Diagnostic Analyte Component 19-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_074": ClinicalConcept_19(
        concept_id="CONCEPT_19_074",
        loinc_num="29074-2",
        snomed_ct="101900074",
        component="Diagnostic Analyte Component 19-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_075": ClinicalConcept_19(
        concept_id="CONCEPT_19_075",
        loinc_num="29075-3",
        snomed_ct="101900075",
        component="Diagnostic Analyte Component 19-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_076": ClinicalConcept_19(
        concept_id="CONCEPT_19_076",
        loinc_num="29076-4",
        snomed_ct="101900076",
        component="Diagnostic Analyte Component 19-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_077": ClinicalConcept_19(
        concept_id="CONCEPT_19_077",
        loinc_num="29077-5",
        snomed_ct="101900077",
        component="Diagnostic Analyte Component 19-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_078": ClinicalConcept_19(
        concept_id="CONCEPT_19_078",
        loinc_num="29078-6",
        snomed_ct="101900078",
        component="Diagnostic Analyte Component 19-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_079": ClinicalConcept_19(
        concept_id="CONCEPT_19_079",
        loinc_num="29079-7",
        snomed_ct="101900079",
        component="Diagnostic Analyte Component 19-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_080": ClinicalConcept_19(
        concept_id="CONCEPT_19_080",
        loinc_num="29080-8",
        snomed_ct="101900080",
        component="Diagnostic Analyte Component 19-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_081": ClinicalConcept_19(
        concept_id="CONCEPT_19_081",
        loinc_num="29081-0",
        snomed_ct="101900081",
        component="Diagnostic Analyte Component 19-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_082": ClinicalConcept_19(
        concept_id="CONCEPT_19_082",
        loinc_num="29082-1",
        snomed_ct="101900082",
        component="Diagnostic Analyte Component 19-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_083": ClinicalConcept_19(
        concept_id="CONCEPT_19_083",
        loinc_num="29083-2",
        snomed_ct="101900083",
        component="Diagnostic Analyte Component 19-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_084": ClinicalConcept_19(
        concept_id="CONCEPT_19_084",
        loinc_num="29084-3",
        snomed_ct="101900084",
        component="Diagnostic Analyte Component 19-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_085": ClinicalConcept_19(
        concept_id="CONCEPT_19_085",
        loinc_num="29085-4",
        snomed_ct="101900085",
        component="Diagnostic Analyte Component 19-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_086": ClinicalConcept_19(
        concept_id="CONCEPT_19_086",
        loinc_num="29086-5",
        snomed_ct="101900086",
        component="Diagnostic Analyte Component 19-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_087": ClinicalConcept_19(
        concept_id="CONCEPT_19_087",
        loinc_num="29087-6",
        snomed_ct="101900087",
        component="Diagnostic Analyte Component 19-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_088": ClinicalConcept_19(
        concept_id="CONCEPT_19_088",
        loinc_num="29088-7",
        snomed_ct="101900088",
        component="Diagnostic Analyte Component 19-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_089": ClinicalConcept_19(
        concept_id="CONCEPT_19_089",
        loinc_num="29089-8",
        snomed_ct="101900089",
        component="Diagnostic Analyte Component 19-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_090": ClinicalConcept_19(
        concept_id="CONCEPT_19_090",
        loinc_num="29090-0",
        snomed_ct="101900090",
        component="Diagnostic Analyte Component 19-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_091": ClinicalConcept_19(
        concept_id="CONCEPT_19_091",
        loinc_num="29091-1",
        snomed_ct="101900091",
        component="Diagnostic Analyte Component 19-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_092": ClinicalConcept_19(
        concept_id="CONCEPT_19_092",
        loinc_num="29092-2",
        snomed_ct="101900092",
        component="Diagnostic Analyte Component 19-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_093": ClinicalConcept_19(
        concept_id="CONCEPT_19_093",
        loinc_num="29093-3",
        snomed_ct="101900093",
        component="Diagnostic Analyte Component 19-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_094": ClinicalConcept_19(
        concept_id="CONCEPT_19_094",
        loinc_num="29094-4",
        snomed_ct="101900094",
        component="Diagnostic Analyte Component 19-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_095": ClinicalConcept_19(
        concept_id="CONCEPT_19_095",
        loinc_num="29095-5",
        snomed_ct="101900095",
        component="Diagnostic Analyte Component 19-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_096": ClinicalConcept_19(
        concept_id="CONCEPT_19_096",
        loinc_num="29096-6",
        snomed_ct="101900096",
        component="Diagnostic Analyte Component 19-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_097": ClinicalConcept_19(
        concept_id="CONCEPT_19_097",
        loinc_num="29097-7",
        snomed_ct="101900097",
        component="Diagnostic Analyte Component 19-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_098": ClinicalConcept_19(
        concept_id="CONCEPT_19_098",
        loinc_num="29098-8",
        snomed_ct="101900098",
        component="Diagnostic Analyte Component 19-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_099": ClinicalConcept_19(
        concept_id="CONCEPT_19_099",
        loinc_num="29099-0",
        snomed_ct="101900099",
        component="Diagnostic Analyte Component 19-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_100": ClinicalConcept_19(
        concept_id="CONCEPT_19_100",
        loinc_num="29100-1",
        snomed_ct="101900100",
        component="Diagnostic Analyte Component 19-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_101": ClinicalConcept_19(
        concept_id="CONCEPT_19_101",
        loinc_num="29101-2",
        snomed_ct="101900101",
        component="Diagnostic Analyte Component 19-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_102": ClinicalConcept_19(
        concept_id="CONCEPT_19_102",
        loinc_num="29102-3",
        snomed_ct="101900102",
        component="Diagnostic Analyte Component 19-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_103": ClinicalConcept_19(
        concept_id="CONCEPT_19_103",
        loinc_num="29103-4",
        snomed_ct="101900103",
        component="Diagnostic Analyte Component 19-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_104": ClinicalConcept_19(
        concept_id="CONCEPT_19_104",
        loinc_num="29104-5",
        snomed_ct="101900104",
        component="Diagnostic Analyte Component 19-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_105": ClinicalConcept_19(
        concept_id="CONCEPT_19_105",
        loinc_num="29105-6",
        snomed_ct="101900105",
        component="Diagnostic Analyte Component 19-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_106": ClinicalConcept_19(
        concept_id="CONCEPT_19_106",
        loinc_num="29106-7",
        snomed_ct="101900106",
        component="Diagnostic Analyte Component 19-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_107": ClinicalConcept_19(
        concept_id="CONCEPT_19_107",
        loinc_num="29107-8",
        snomed_ct="101900107",
        component="Diagnostic Analyte Component 19-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_108": ClinicalConcept_19(
        concept_id="CONCEPT_19_108",
        loinc_num="29108-0",
        snomed_ct="101900108",
        component="Diagnostic Analyte Component 19-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_109": ClinicalConcept_19(
        concept_id="CONCEPT_19_109",
        loinc_num="29109-1",
        snomed_ct="101900109",
        component="Diagnostic Analyte Component 19-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_110": ClinicalConcept_19(
        concept_id="CONCEPT_19_110",
        loinc_num="29110-2",
        snomed_ct="101900110",
        component="Diagnostic Analyte Component 19-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_111": ClinicalConcept_19(
        concept_id="CONCEPT_19_111",
        loinc_num="29111-3",
        snomed_ct="101900111",
        component="Diagnostic Analyte Component 19-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_112": ClinicalConcept_19(
        concept_id="CONCEPT_19_112",
        loinc_num="29112-4",
        snomed_ct="101900112",
        component="Diagnostic Analyte Component 19-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_113": ClinicalConcept_19(
        concept_id="CONCEPT_19_113",
        loinc_num="29113-5",
        snomed_ct="101900113",
        component="Diagnostic Analyte Component 19-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_114": ClinicalConcept_19(
        concept_id="CONCEPT_19_114",
        loinc_num="29114-6",
        snomed_ct="101900114",
        component="Diagnostic Analyte Component 19-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_115": ClinicalConcept_19(
        concept_id="CONCEPT_19_115",
        loinc_num="29115-7",
        snomed_ct="101900115",
        component="Diagnostic Analyte Component 19-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_116": ClinicalConcept_19(
        concept_id="CONCEPT_19_116",
        loinc_num="29116-8",
        snomed_ct="101900116",
        component="Diagnostic Analyte Component 19-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_117": ClinicalConcept_19(
        concept_id="CONCEPT_19_117",
        loinc_num="29117-0",
        snomed_ct="101900117",
        component="Diagnostic Analyte Component 19-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_118": ClinicalConcept_19(
        concept_id="CONCEPT_19_118",
        loinc_num="29118-1",
        snomed_ct="101900118",
        component="Diagnostic Analyte Component 19-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_119": ClinicalConcept_19(
        concept_id="CONCEPT_19_119",
        loinc_num="29119-2",
        snomed_ct="101900119",
        component="Diagnostic Analyte Component 19-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_120": ClinicalConcept_19(
        concept_id="CONCEPT_19_120",
        loinc_num="29120-3",
        snomed_ct="101900120",
        component="Diagnostic Analyte Component 19-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_121": ClinicalConcept_19(
        concept_id="CONCEPT_19_121",
        loinc_num="29121-4",
        snomed_ct="101900121",
        component="Diagnostic Analyte Component 19-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_122": ClinicalConcept_19(
        concept_id="CONCEPT_19_122",
        loinc_num="29122-5",
        snomed_ct="101900122",
        component="Diagnostic Analyte Component 19-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_123": ClinicalConcept_19(
        concept_id="CONCEPT_19_123",
        loinc_num="29123-6",
        snomed_ct="101900123",
        component="Diagnostic Analyte Component 19-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_124": ClinicalConcept_19(
        concept_id="CONCEPT_19_124",
        loinc_num="29124-7",
        snomed_ct="101900124",
        component="Diagnostic Analyte Component 19-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_125": ClinicalConcept_19(
        concept_id="CONCEPT_19_125",
        loinc_num="29125-8",
        snomed_ct="101900125",
        component="Diagnostic Analyte Component 19-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_126": ClinicalConcept_19(
        concept_id="CONCEPT_19_126",
        loinc_num="29126-0",
        snomed_ct="101900126",
        component="Diagnostic Analyte Component 19-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_127": ClinicalConcept_19(
        concept_id="CONCEPT_19_127",
        loinc_num="29127-1",
        snomed_ct="101900127",
        component="Diagnostic Analyte Component 19-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_128": ClinicalConcept_19(
        concept_id="CONCEPT_19_128",
        loinc_num="29128-2",
        snomed_ct="101900128",
        component="Diagnostic Analyte Component 19-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_129": ClinicalConcept_19(
        concept_id="CONCEPT_19_129",
        loinc_num="29129-3",
        snomed_ct="101900129",
        component="Diagnostic Analyte Component 19-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_130": ClinicalConcept_19(
        concept_id="CONCEPT_19_130",
        loinc_num="29130-4",
        snomed_ct="101900130",
        component="Diagnostic Analyte Component 19-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_131": ClinicalConcept_19(
        concept_id="CONCEPT_19_131",
        loinc_num="29131-5",
        snomed_ct="101900131",
        component="Diagnostic Analyte Component 19-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_132": ClinicalConcept_19(
        concept_id="CONCEPT_19_132",
        loinc_num="29132-6",
        snomed_ct="101900132",
        component="Diagnostic Analyte Component 19-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_133": ClinicalConcept_19(
        concept_id="CONCEPT_19_133",
        loinc_num="29133-7",
        snomed_ct="101900133",
        component="Diagnostic Analyte Component 19-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_134": ClinicalConcept_19(
        concept_id="CONCEPT_19_134",
        loinc_num="29134-8",
        snomed_ct="101900134",
        component="Diagnostic Analyte Component 19-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_135": ClinicalConcept_19(
        concept_id="CONCEPT_19_135",
        loinc_num="29135-0",
        snomed_ct="101900135",
        component="Diagnostic Analyte Component 19-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_136": ClinicalConcept_19(
        concept_id="CONCEPT_19_136",
        loinc_num="29136-1",
        snomed_ct="101900136",
        component="Diagnostic Analyte Component 19-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_137": ClinicalConcept_19(
        concept_id="CONCEPT_19_137",
        loinc_num="29137-2",
        snomed_ct="101900137",
        component="Diagnostic Analyte Component 19-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_138": ClinicalConcept_19(
        concept_id="CONCEPT_19_138",
        loinc_num="29138-3",
        snomed_ct="101900138",
        component="Diagnostic Analyte Component 19-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_139": ClinicalConcept_19(
        concept_id="CONCEPT_19_139",
        loinc_num="29139-4",
        snomed_ct="101900139",
        component="Diagnostic Analyte Component 19-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_140": ClinicalConcept_19(
        concept_id="CONCEPT_19_140",
        loinc_num="29140-5",
        snomed_ct="101900140",
        component="Diagnostic Analyte Component 19-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_141": ClinicalConcept_19(
        concept_id="CONCEPT_19_141",
        loinc_num="29141-6",
        snomed_ct="101900141",
        component="Diagnostic Analyte Component 19-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_142": ClinicalConcept_19(
        concept_id="CONCEPT_19_142",
        loinc_num="29142-7",
        snomed_ct="101900142",
        component="Diagnostic Analyte Component 19-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_143": ClinicalConcept_19(
        concept_id="CONCEPT_19_143",
        loinc_num="29143-8",
        snomed_ct="101900143",
        component="Diagnostic Analyte Component 19-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_144": ClinicalConcept_19(
        concept_id="CONCEPT_19_144",
        loinc_num="29144-0",
        snomed_ct="101900144",
        component="Diagnostic Analyte Component 19-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_145": ClinicalConcept_19(
        concept_id="CONCEPT_19_145",
        loinc_num="29145-1",
        snomed_ct="101900145",
        component="Diagnostic Analyte Component 19-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_146": ClinicalConcept_19(
        concept_id="CONCEPT_19_146",
        loinc_num="29146-2",
        snomed_ct="101900146",
        component="Diagnostic Analyte Component 19-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_147": ClinicalConcept_19(
        concept_id="CONCEPT_19_147",
        loinc_num="29147-3",
        snomed_ct="101900147",
        component="Diagnostic Analyte Component 19-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_148": ClinicalConcept_19(
        concept_id="CONCEPT_19_148",
        loinc_num="29148-4",
        snomed_ct="101900148",
        component="Diagnostic Analyte Component 19-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_149": ClinicalConcept_19(
        concept_id="CONCEPT_19_149",
        loinc_num="29149-5",
        snomed_ct="101900149",
        component="Diagnostic Analyte Component 19-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_150": ClinicalConcept_19(
        concept_id="CONCEPT_19_150",
        loinc_num="29150-6",
        snomed_ct="101900150",
        component="Diagnostic Analyte Component 19-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_151": ClinicalConcept_19(
        concept_id="CONCEPT_19_151",
        loinc_num="29151-7",
        snomed_ct="101900151",
        component="Diagnostic Analyte Component 19-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_152": ClinicalConcept_19(
        concept_id="CONCEPT_19_152",
        loinc_num="29152-8",
        snomed_ct="101900152",
        component="Diagnostic Analyte Component 19-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_153": ClinicalConcept_19(
        concept_id="CONCEPT_19_153",
        loinc_num="29153-0",
        snomed_ct="101900153",
        component="Diagnostic Analyte Component 19-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_154": ClinicalConcept_19(
        concept_id="CONCEPT_19_154",
        loinc_num="29154-1",
        snomed_ct="101900154",
        component="Diagnostic Analyte Component 19-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_155": ClinicalConcept_19(
        concept_id="CONCEPT_19_155",
        loinc_num="29155-2",
        snomed_ct="101900155",
        component="Diagnostic Analyte Component 19-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_156": ClinicalConcept_19(
        concept_id="CONCEPT_19_156",
        loinc_num="29156-3",
        snomed_ct="101900156",
        component="Diagnostic Analyte Component 19-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_157": ClinicalConcept_19(
        concept_id="CONCEPT_19_157",
        loinc_num="29157-4",
        snomed_ct="101900157",
        component="Diagnostic Analyte Component 19-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_158": ClinicalConcept_19(
        concept_id="CONCEPT_19_158",
        loinc_num="29158-5",
        snomed_ct="101900158",
        component="Diagnostic Analyte Component 19-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_159": ClinicalConcept_19(
        concept_id="CONCEPT_19_159",
        loinc_num="29159-6",
        snomed_ct="101900159",
        component="Diagnostic Analyte Component 19-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_160": ClinicalConcept_19(
        concept_id="CONCEPT_19_160",
        loinc_num="29160-7",
        snomed_ct="101900160",
        component="Diagnostic Analyte Component 19-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_161": ClinicalConcept_19(
        concept_id="CONCEPT_19_161",
        loinc_num="29161-8",
        snomed_ct="101900161",
        component="Diagnostic Analyte Component 19-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_162": ClinicalConcept_19(
        concept_id="CONCEPT_19_162",
        loinc_num="29162-0",
        snomed_ct="101900162",
        component="Diagnostic Analyte Component 19-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_163": ClinicalConcept_19(
        concept_id="CONCEPT_19_163",
        loinc_num="29163-1",
        snomed_ct="101900163",
        component="Diagnostic Analyte Component 19-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_164": ClinicalConcept_19(
        concept_id="CONCEPT_19_164",
        loinc_num="29164-2",
        snomed_ct="101900164",
        component="Diagnostic Analyte Component 19-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_165": ClinicalConcept_19(
        concept_id="CONCEPT_19_165",
        loinc_num="29165-3",
        snomed_ct="101900165",
        component="Diagnostic Analyte Component 19-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_166": ClinicalConcept_19(
        concept_id="CONCEPT_19_166",
        loinc_num="29166-4",
        snomed_ct="101900166",
        component="Diagnostic Analyte Component 19-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_167": ClinicalConcept_19(
        concept_id="CONCEPT_19_167",
        loinc_num="29167-5",
        snomed_ct="101900167",
        component="Diagnostic Analyte Component 19-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_168": ClinicalConcept_19(
        concept_id="CONCEPT_19_168",
        loinc_num="29168-6",
        snomed_ct="101900168",
        component="Diagnostic Analyte Component 19-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_169": ClinicalConcept_19(
        concept_id="CONCEPT_19_169",
        loinc_num="29169-7",
        snomed_ct="101900169",
        component="Diagnostic Analyte Component 19-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_170": ClinicalConcept_19(
        concept_id="CONCEPT_19_170",
        loinc_num="29170-8",
        snomed_ct="101900170",
        component="Diagnostic Analyte Component 19-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_171": ClinicalConcept_19(
        concept_id="CONCEPT_19_171",
        loinc_num="29171-0",
        snomed_ct="101900171",
        component="Diagnostic Analyte Component 19-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_172": ClinicalConcept_19(
        concept_id="CONCEPT_19_172",
        loinc_num="29172-1",
        snomed_ct="101900172",
        component="Diagnostic Analyte Component 19-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_173": ClinicalConcept_19(
        concept_id="CONCEPT_19_173",
        loinc_num="29173-2",
        snomed_ct="101900173",
        component="Diagnostic Analyte Component 19-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_174": ClinicalConcept_19(
        concept_id="CONCEPT_19_174",
        loinc_num="29174-3",
        snomed_ct="101900174",
        component="Diagnostic Analyte Component 19-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_175": ClinicalConcept_19(
        concept_id="CONCEPT_19_175",
        loinc_num="29175-4",
        snomed_ct="101900175",
        component="Diagnostic Analyte Component 19-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_176": ClinicalConcept_19(
        concept_id="CONCEPT_19_176",
        loinc_num="29176-5",
        snomed_ct="101900176",
        component="Diagnostic Analyte Component 19-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_177": ClinicalConcept_19(
        concept_id="CONCEPT_19_177",
        loinc_num="29177-6",
        snomed_ct="101900177",
        component="Diagnostic Analyte Component 19-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_178": ClinicalConcept_19(
        concept_id="CONCEPT_19_178",
        loinc_num="29178-7",
        snomed_ct="101900178",
        component="Diagnostic Analyte Component 19-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_179": ClinicalConcept_19(
        concept_id="CONCEPT_19_179",
        loinc_num="29179-8",
        snomed_ct="101900179",
        component="Diagnostic Analyte Component 19-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_180": ClinicalConcept_19(
        concept_id="CONCEPT_19_180",
        loinc_num="29180-0",
        snomed_ct="101900180",
        component="Diagnostic Analyte Component 19-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_181": ClinicalConcept_19(
        concept_id="CONCEPT_19_181",
        loinc_num="29181-1",
        snomed_ct="101900181",
        component="Diagnostic Analyte Component 19-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_182": ClinicalConcept_19(
        concept_id="CONCEPT_19_182",
        loinc_num="29182-2",
        snomed_ct="101900182",
        component="Diagnostic Analyte Component 19-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_183": ClinicalConcept_19(
        concept_id="CONCEPT_19_183",
        loinc_num="29183-3",
        snomed_ct="101900183",
        component="Diagnostic Analyte Component 19-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_184": ClinicalConcept_19(
        concept_id="CONCEPT_19_184",
        loinc_num="29184-4",
        snomed_ct="101900184",
        component="Diagnostic Analyte Component 19-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_185": ClinicalConcept_19(
        concept_id="CONCEPT_19_185",
        loinc_num="29185-5",
        snomed_ct="101900185",
        component="Diagnostic Analyte Component 19-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_186": ClinicalConcept_19(
        concept_id="CONCEPT_19_186",
        loinc_num="29186-6",
        snomed_ct="101900186",
        component="Diagnostic Analyte Component 19-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_187": ClinicalConcept_19(
        concept_id="CONCEPT_19_187",
        loinc_num="29187-7",
        snomed_ct="101900187",
        component="Diagnostic Analyte Component 19-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_188": ClinicalConcept_19(
        concept_id="CONCEPT_19_188",
        loinc_num="29188-8",
        snomed_ct="101900188",
        component="Diagnostic Analyte Component 19-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_189": ClinicalConcept_19(
        concept_id="CONCEPT_19_189",
        loinc_num="29189-0",
        snomed_ct="101900189",
        component="Diagnostic Analyte Component 19-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_190": ClinicalConcept_19(
        concept_id="CONCEPT_19_190",
        loinc_num="29190-1",
        snomed_ct="101900190",
        component="Diagnostic Analyte Component 19-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_191": ClinicalConcept_19(
        concept_id="CONCEPT_19_191",
        loinc_num="29191-2",
        snomed_ct="101900191",
        component="Diagnostic Analyte Component 19-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_192": ClinicalConcept_19(
        concept_id="CONCEPT_19_192",
        loinc_num="29192-3",
        snomed_ct="101900192",
        component="Diagnostic Analyte Component 19-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_193": ClinicalConcept_19(
        concept_id="CONCEPT_19_193",
        loinc_num="29193-4",
        snomed_ct="101900193",
        component="Diagnostic Analyte Component 19-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_194": ClinicalConcept_19(
        concept_id="CONCEPT_19_194",
        loinc_num="29194-5",
        snomed_ct="101900194",
        component="Diagnostic Analyte Component 19-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_195": ClinicalConcept_19(
        concept_id="CONCEPT_19_195",
        loinc_num="29195-6",
        snomed_ct="101900195",
        component="Diagnostic Analyte Component 19-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_196": ClinicalConcept_19(
        concept_id="CONCEPT_19_196",
        loinc_num="29196-7",
        snomed_ct="101900196",
        component="Diagnostic Analyte Component 19-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_197": ClinicalConcept_19(
        concept_id="CONCEPT_19_197",
        loinc_num="29197-8",
        snomed_ct="101900197",
        component="Diagnostic Analyte Component 19-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_198": ClinicalConcept_19(
        concept_id="CONCEPT_19_198",
        loinc_num="29198-0",
        snomed_ct="101900198",
        component="Diagnostic Analyte Component 19-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_19_199": ClinicalConcept_19(
        concept_id="CONCEPT_19_199",
        loinc_num="29199-1",
        snomed_ct="101900199",
        component="Diagnostic Analyte Component 19-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
