"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 24"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_24:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_24 = {
    "CONCEPT_24_001": ClinicalConcept_24(
        concept_id="CONCEPT_24_001",
        loinc_num="34001-1",
        snomed_ct="102400001",
        component="Diagnostic Analyte Component 24-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_002": ClinicalConcept_24(
        concept_id="CONCEPT_24_002",
        loinc_num="34002-2",
        snomed_ct="102400002",
        component="Diagnostic Analyte Component 24-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_003": ClinicalConcept_24(
        concept_id="CONCEPT_24_003",
        loinc_num="34003-3",
        snomed_ct="102400003",
        component="Diagnostic Analyte Component 24-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_004": ClinicalConcept_24(
        concept_id="CONCEPT_24_004",
        loinc_num="34004-4",
        snomed_ct="102400004",
        component="Diagnostic Analyte Component 24-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_005": ClinicalConcept_24(
        concept_id="CONCEPT_24_005",
        loinc_num="34005-5",
        snomed_ct="102400005",
        component="Diagnostic Analyte Component 24-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_006": ClinicalConcept_24(
        concept_id="CONCEPT_24_006",
        loinc_num="34006-6",
        snomed_ct="102400006",
        component="Diagnostic Analyte Component 24-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_007": ClinicalConcept_24(
        concept_id="CONCEPT_24_007",
        loinc_num="34007-7",
        snomed_ct="102400007",
        component="Diagnostic Analyte Component 24-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_008": ClinicalConcept_24(
        concept_id="CONCEPT_24_008",
        loinc_num="34008-8",
        snomed_ct="102400008",
        component="Diagnostic Analyte Component 24-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_009": ClinicalConcept_24(
        concept_id="CONCEPT_24_009",
        loinc_num="34009-0",
        snomed_ct="102400009",
        component="Diagnostic Analyte Component 24-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_010": ClinicalConcept_24(
        concept_id="CONCEPT_24_010",
        loinc_num="34010-1",
        snomed_ct="102400010",
        component="Diagnostic Analyte Component 24-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_011": ClinicalConcept_24(
        concept_id="CONCEPT_24_011",
        loinc_num="34011-2",
        snomed_ct="102400011",
        component="Diagnostic Analyte Component 24-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_012": ClinicalConcept_24(
        concept_id="CONCEPT_24_012",
        loinc_num="34012-3",
        snomed_ct="102400012",
        component="Diagnostic Analyte Component 24-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_013": ClinicalConcept_24(
        concept_id="CONCEPT_24_013",
        loinc_num="34013-4",
        snomed_ct="102400013",
        component="Diagnostic Analyte Component 24-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_014": ClinicalConcept_24(
        concept_id="CONCEPT_24_014",
        loinc_num="34014-5",
        snomed_ct="102400014",
        component="Diagnostic Analyte Component 24-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_015": ClinicalConcept_24(
        concept_id="CONCEPT_24_015",
        loinc_num="34015-6",
        snomed_ct="102400015",
        component="Diagnostic Analyte Component 24-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_016": ClinicalConcept_24(
        concept_id="CONCEPT_24_016",
        loinc_num="34016-7",
        snomed_ct="102400016",
        component="Diagnostic Analyte Component 24-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_017": ClinicalConcept_24(
        concept_id="CONCEPT_24_017",
        loinc_num="34017-8",
        snomed_ct="102400017",
        component="Diagnostic Analyte Component 24-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_018": ClinicalConcept_24(
        concept_id="CONCEPT_24_018",
        loinc_num="34018-0",
        snomed_ct="102400018",
        component="Diagnostic Analyte Component 24-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_019": ClinicalConcept_24(
        concept_id="CONCEPT_24_019",
        loinc_num="34019-1",
        snomed_ct="102400019",
        component="Diagnostic Analyte Component 24-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_020": ClinicalConcept_24(
        concept_id="CONCEPT_24_020",
        loinc_num="34020-2",
        snomed_ct="102400020",
        component="Diagnostic Analyte Component 24-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_021": ClinicalConcept_24(
        concept_id="CONCEPT_24_021",
        loinc_num="34021-3",
        snomed_ct="102400021",
        component="Diagnostic Analyte Component 24-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_022": ClinicalConcept_24(
        concept_id="CONCEPT_24_022",
        loinc_num="34022-4",
        snomed_ct="102400022",
        component="Diagnostic Analyte Component 24-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_023": ClinicalConcept_24(
        concept_id="CONCEPT_24_023",
        loinc_num="34023-5",
        snomed_ct="102400023",
        component="Diagnostic Analyte Component 24-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_024": ClinicalConcept_24(
        concept_id="CONCEPT_24_024",
        loinc_num="34024-6",
        snomed_ct="102400024",
        component="Diagnostic Analyte Component 24-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_025": ClinicalConcept_24(
        concept_id="CONCEPT_24_025",
        loinc_num="34025-7",
        snomed_ct="102400025",
        component="Diagnostic Analyte Component 24-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_026": ClinicalConcept_24(
        concept_id="CONCEPT_24_026",
        loinc_num="34026-8",
        snomed_ct="102400026",
        component="Diagnostic Analyte Component 24-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_027": ClinicalConcept_24(
        concept_id="CONCEPT_24_027",
        loinc_num="34027-0",
        snomed_ct="102400027",
        component="Diagnostic Analyte Component 24-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_028": ClinicalConcept_24(
        concept_id="CONCEPT_24_028",
        loinc_num="34028-1",
        snomed_ct="102400028",
        component="Diagnostic Analyte Component 24-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_029": ClinicalConcept_24(
        concept_id="CONCEPT_24_029",
        loinc_num="34029-2",
        snomed_ct="102400029",
        component="Diagnostic Analyte Component 24-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_030": ClinicalConcept_24(
        concept_id="CONCEPT_24_030",
        loinc_num="34030-3",
        snomed_ct="102400030",
        component="Diagnostic Analyte Component 24-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_031": ClinicalConcept_24(
        concept_id="CONCEPT_24_031",
        loinc_num="34031-4",
        snomed_ct="102400031",
        component="Diagnostic Analyte Component 24-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_032": ClinicalConcept_24(
        concept_id="CONCEPT_24_032",
        loinc_num="34032-5",
        snomed_ct="102400032",
        component="Diagnostic Analyte Component 24-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_033": ClinicalConcept_24(
        concept_id="CONCEPT_24_033",
        loinc_num="34033-6",
        snomed_ct="102400033",
        component="Diagnostic Analyte Component 24-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_034": ClinicalConcept_24(
        concept_id="CONCEPT_24_034",
        loinc_num="34034-7",
        snomed_ct="102400034",
        component="Diagnostic Analyte Component 24-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_035": ClinicalConcept_24(
        concept_id="CONCEPT_24_035",
        loinc_num="34035-8",
        snomed_ct="102400035",
        component="Diagnostic Analyte Component 24-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_036": ClinicalConcept_24(
        concept_id="CONCEPT_24_036",
        loinc_num="34036-0",
        snomed_ct="102400036",
        component="Diagnostic Analyte Component 24-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_037": ClinicalConcept_24(
        concept_id="CONCEPT_24_037",
        loinc_num="34037-1",
        snomed_ct="102400037",
        component="Diagnostic Analyte Component 24-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_038": ClinicalConcept_24(
        concept_id="CONCEPT_24_038",
        loinc_num="34038-2",
        snomed_ct="102400038",
        component="Diagnostic Analyte Component 24-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_039": ClinicalConcept_24(
        concept_id="CONCEPT_24_039",
        loinc_num="34039-3",
        snomed_ct="102400039",
        component="Diagnostic Analyte Component 24-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_040": ClinicalConcept_24(
        concept_id="CONCEPT_24_040",
        loinc_num="34040-4",
        snomed_ct="102400040",
        component="Diagnostic Analyte Component 24-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_041": ClinicalConcept_24(
        concept_id="CONCEPT_24_041",
        loinc_num="34041-5",
        snomed_ct="102400041",
        component="Diagnostic Analyte Component 24-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_042": ClinicalConcept_24(
        concept_id="CONCEPT_24_042",
        loinc_num="34042-6",
        snomed_ct="102400042",
        component="Diagnostic Analyte Component 24-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_043": ClinicalConcept_24(
        concept_id="CONCEPT_24_043",
        loinc_num="34043-7",
        snomed_ct="102400043",
        component="Diagnostic Analyte Component 24-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_044": ClinicalConcept_24(
        concept_id="CONCEPT_24_044",
        loinc_num="34044-8",
        snomed_ct="102400044",
        component="Diagnostic Analyte Component 24-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_045": ClinicalConcept_24(
        concept_id="CONCEPT_24_045",
        loinc_num="34045-0",
        snomed_ct="102400045",
        component="Diagnostic Analyte Component 24-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_046": ClinicalConcept_24(
        concept_id="CONCEPT_24_046",
        loinc_num="34046-1",
        snomed_ct="102400046",
        component="Diagnostic Analyte Component 24-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_047": ClinicalConcept_24(
        concept_id="CONCEPT_24_047",
        loinc_num="34047-2",
        snomed_ct="102400047",
        component="Diagnostic Analyte Component 24-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_048": ClinicalConcept_24(
        concept_id="CONCEPT_24_048",
        loinc_num="34048-3",
        snomed_ct="102400048",
        component="Diagnostic Analyte Component 24-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_049": ClinicalConcept_24(
        concept_id="CONCEPT_24_049",
        loinc_num="34049-4",
        snomed_ct="102400049",
        component="Diagnostic Analyte Component 24-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_050": ClinicalConcept_24(
        concept_id="CONCEPT_24_050",
        loinc_num="34050-5",
        snomed_ct="102400050",
        component="Diagnostic Analyte Component 24-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_051": ClinicalConcept_24(
        concept_id="CONCEPT_24_051",
        loinc_num="34051-6",
        snomed_ct="102400051",
        component="Diagnostic Analyte Component 24-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_052": ClinicalConcept_24(
        concept_id="CONCEPT_24_052",
        loinc_num="34052-7",
        snomed_ct="102400052",
        component="Diagnostic Analyte Component 24-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_053": ClinicalConcept_24(
        concept_id="CONCEPT_24_053",
        loinc_num="34053-8",
        snomed_ct="102400053",
        component="Diagnostic Analyte Component 24-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_054": ClinicalConcept_24(
        concept_id="CONCEPT_24_054",
        loinc_num="34054-0",
        snomed_ct="102400054",
        component="Diagnostic Analyte Component 24-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_055": ClinicalConcept_24(
        concept_id="CONCEPT_24_055",
        loinc_num="34055-1",
        snomed_ct="102400055",
        component="Diagnostic Analyte Component 24-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_056": ClinicalConcept_24(
        concept_id="CONCEPT_24_056",
        loinc_num="34056-2",
        snomed_ct="102400056",
        component="Diagnostic Analyte Component 24-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_057": ClinicalConcept_24(
        concept_id="CONCEPT_24_057",
        loinc_num="34057-3",
        snomed_ct="102400057",
        component="Diagnostic Analyte Component 24-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_058": ClinicalConcept_24(
        concept_id="CONCEPT_24_058",
        loinc_num="34058-4",
        snomed_ct="102400058",
        component="Diagnostic Analyte Component 24-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_059": ClinicalConcept_24(
        concept_id="CONCEPT_24_059",
        loinc_num="34059-5",
        snomed_ct="102400059",
        component="Diagnostic Analyte Component 24-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_060": ClinicalConcept_24(
        concept_id="CONCEPT_24_060",
        loinc_num="34060-6",
        snomed_ct="102400060",
        component="Diagnostic Analyte Component 24-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_061": ClinicalConcept_24(
        concept_id="CONCEPT_24_061",
        loinc_num="34061-7",
        snomed_ct="102400061",
        component="Diagnostic Analyte Component 24-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_062": ClinicalConcept_24(
        concept_id="CONCEPT_24_062",
        loinc_num="34062-8",
        snomed_ct="102400062",
        component="Diagnostic Analyte Component 24-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_063": ClinicalConcept_24(
        concept_id="CONCEPT_24_063",
        loinc_num="34063-0",
        snomed_ct="102400063",
        component="Diagnostic Analyte Component 24-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_064": ClinicalConcept_24(
        concept_id="CONCEPT_24_064",
        loinc_num="34064-1",
        snomed_ct="102400064",
        component="Diagnostic Analyte Component 24-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_065": ClinicalConcept_24(
        concept_id="CONCEPT_24_065",
        loinc_num="34065-2",
        snomed_ct="102400065",
        component="Diagnostic Analyte Component 24-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_066": ClinicalConcept_24(
        concept_id="CONCEPT_24_066",
        loinc_num="34066-3",
        snomed_ct="102400066",
        component="Diagnostic Analyte Component 24-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_067": ClinicalConcept_24(
        concept_id="CONCEPT_24_067",
        loinc_num="34067-4",
        snomed_ct="102400067",
        component="Diagnostic Analyte Component 24-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_068": ClinicalConcept_24(
        concept_id="CONCEPT_24_068",
        loinc_num="34068-5",
        snomed_ct="102400068",
        component="Diagnostic Analyte Component 24-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_069": ClinicalConcept_24(
        concept_id="CONCEPT_24_069",
        loinc_num="34069-6",
        snomed_ct="102400069",
        component="Diagnostic Analyte Component 24-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_070": ClinicalConcept_24(
        concept_id="CONCEPT_24_070",
        loinc_num="34070-7",
        snomed_ct="102400070",
        component="Diagnostic Analyte Component 24-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_071": ClinicalConcept_24(
        concept_id="CONCEPT_24_071",
        loinc_num="34071-8",
        snomed_ct="102400071",
        component="Diagnostic Analyte Component 24-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_072": ClinicalConcept_24(
        concept_id="CONCEPT_24_072",
        loinc_num="34072-0",
        snomed_ct="102400072",
        component="Diagnostic Analyte Component 24-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_073": ClinicalConcept_24(
        concept_id="CONCEPT_24_073",
        loinc_num="34073-1",
        snomed_ct="102400073",
        component="Diagnostic Analyte Component 24-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_074": ClinicalConcept_24(
        concept_id="CONCEPT_24_074",
        loinc_num="34074-2",
        snomed_ct="102400074",
        component="Diagnostic Analyte Component 24-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_075": ClinicalConcept_24(
        concept_id="CONCEPT_24_075",
        loinc_num="34075-3",
        snomed_ct="102400075",
        component="Diagnostic Analyte Component 24-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_076": ClinicalConcept_24(
        concept_id="CONCEPT_24_076",
        loinc_num="34076-4",
        snomed_ct="102400076",
        component="Diagnostic Analyte Component 24-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_077": ClinicalConcept_24(
        concept_id="CONCEPT_24_077",
        loinc_num="34077-5",
        snomed_ct="102400077",
        component="Diagnostic Analyte Component 24-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_078": ClinicalConcept_24(
        concept_id="CONCEPT_24_078",
        loinc_num="34078-6",
        snomed_ct="102400078",
        component="Diagnostic Analyte Component 24-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_079": ClinicalConcept_24(
        concept_id="CONCEPT_24_079",
        loinc_num="34079-7",
        snomed_ct="102400079",
        component="Diagnostic Analyte Component 24-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_080": ClinicalConcept_24(
        concept_id="CONCEPT_24_080",
        loinc_num="34080-8",
        snomed_ct="102400080",
        component="Diagnostic Analyte Component 24-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_081": ClinicalConcept_24(
        concept_id="CONCEPT_24_081",
        loinc_num="34081-0",
        snomed_ct="102400081",
        component="Diagnostic Analyte Component 24-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_082": ClinicalConcept_24(
        concept_id="CONCEPT_24_082",
        loinc_num="34082-1",
        snomed_ct="102400082",
        component="Diagnostic Analyte Component 24-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_083": ClinicalConcept_24(
        concept_id="CONCEPT_24_083",
        loinc_num="34083-2",
        snomed_ct="102400083",
        component="Diagnostic Analyte Component 24-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_084": ClinicalConcept_24(
        concept_id="CONCEPT_24_084",
        loinc_num="34084-3",
        snomed_ct="102400084",
        component="Diagnostic Analyte Component 24-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_085": ClinicalConcept_24(
        concept_id="CONCEPT_24_085",
        loinc_num="34085-4",
        snomed_ct="102400085",
        component="Diagnostic Analyte Component 24-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_086": ClinicalConcept_24(
        concept_id="CONCEPT_24_086",
        loinc_num="34086-5",
        snomed_ct="102400086",
        component="Diagnostic Analyte Component 24-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_087": ClinicalConcept_24(
        concept_id="CONCEPT_24_087",
        loinc_num="34087-6",
        snomed_ct="102400087",
        component="Diagnostic Analyte Component 24-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_088": ClinicalConcept_24(
        concept_id="CONCEPT_24_088",
        loinc_num="34088-7",
        snomed_ct="102400088",
        component="Diagnostic Analyte Component 24-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_089": ClinicalConcept_24(
        concept_id="CONCEPT_24_089",
        loinc_num="34089-8",
        snomed_ct="102400089",
        component="Diagnostic Analyte Component 24-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_090": ClinicalConcept_24(
        concept_id="CONCEPT_24_090",
        loinc_num="34090-0",
        snomed_ct="102400090",
        component="Diagnostic Analyte Component 24-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_091": ClinicalConcept_24(
        concept_id="CONCEPT_24_091",
        loinc_num="34091-1",
        snomed_ct="102400091",
        component="Diagnostic Analyte Component 24-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_092": ClinicalConcept_24(
        concept_id="CONCEPT_24_092",
        loinc_num="34092-2",
        snomed_ct="102400092",
        component="Diagnostic Analyte Component 24-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_093": ClinicalConcept_24(
        concept_id="CONCEPT_24_093",
        loinc_num="34093-3",
        snomed_ct="102400093",
        component="Diagnostic Analyte Component 24-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_094": ClinicalConcept_24(
        concept_id="CONCEPT_24_094",
        loinc_num="34094-4",
        snomed_ct="102400094",
        component="Diagnostic Analyte Component 24-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_095": ClinicalConcept_24(
        concept_id="CONCEPT_24_095",
        loinc_num="34095-5",
        snomed_ct="102400095",
        component="Diagnostic Analyte Component 24-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_096": ClinicalConcept_24(
        concept_id="CONCEPT_24_096",
        loinc_num="34096-6",
        snomed_ct="102400096",
        component="Diagnostic Analyte Component 24-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_097": ClinicalConcept_24(
        concept_id="CONCEPT_24_097",
        loinc_num="34097-7",
        snomed_ct="102400097",
        component="Diagnostic Analyte Component 24-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_098": ClinicalConcept_24(
        concept_id="CONCEPT_24_098",
        loinc_num="34098-8",
        snomed_ct="102400098",
        component="Diagnostic Analyte Component 24-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_099": ClinicalConcept_24(
        concept_id="CONCEPT_24_099",
        loinc_num="34099-0",
        snomed_ct="102400099",
        component="Diagnostic Analyte Component 24-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_100": ClinicalConcept_24(
        concept_id="CONCEPT_24_100",
        loinc_num="34100-1",
        snomed_ct="102400100",
        component="Diagnostic Analyte Component 24-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_101": ClinicalConcept_24(
        concept_id="CONCEPT_24_101",
        loinc_num="34101-2",
        snomed_ct="102400101",
        component="Diagnostic Analyte Component 24-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_102": ClinicalConcept_24(
        concept_id="CONCEPT_24_102",
        loinc_num="34102-3",
        snomed_ct="102400102",
        component="Diagnostic Analyte Component 24-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_103": ClinicalConcept_24(
        concept_id="CONCEPT_24_103",
        loinc_num="34103-4",
        snomed_ct="102400103",
        component="Diagnostic Analyte Component 24-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_104": ClinicalConcept_24(
        concept_id="CONCEPT_24_104",
        loinc_num="34104-5",
        snomed_ct="102400104",
        component="Diagnostic Analyte Component 24-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_105": ClinicalConcept_24(
        concept_id="CONCEPT_24_105",
        loinc_num="34105-6",
        snomed_ct="102400105",
        component="Diagnostic Analyte Component 24-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_106": ClinicalConcept_24(
        concept_id="CONCEPT_24_106",
        loinc_num="34106-7",
        snomed_ct="102400106",
        component="Diagnostic Analyte Component 24-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_107": ClinicalConcept_24(
        concept_id="CONCEPT_24_107",
        loinc_num="34107-8",
        snomed_ct="102400107",
        component="Diagnostic Analyte Component 24-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_108": ClinicalConcept_24(
        concept_id="CONCEPT_24_108",
        loinc_num="34108-0",
        snomed_ct="102400108",
        component="Diagnostic Analyte Component 24-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_109": ClinicalConcept_24(
        concept_id="CONCEPT_24_109",
        loinc_num="34109-1",
        snomed_ct="102400109",
        component="Diagnostic Analyte Component 24-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_110": ClinicalConcept_24(
        concept_id="CONCEPT_24_110",
        loinc_num="34110-2",
        snomed_ct="102400110",
        component="Diagnostic Analyte Component 24-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_111": ClinicalConcept_24(
        concept_id="CONCEPT_24_111",
        loinc_num="34111-3",
        snomed_ct="102400111",
        component="Diagnostic Analyte Component 24-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_112": ClinicalConcept_24(
        concept_id="CONCEPT_24_112",
        loinc_num="34112-4",
        snomed_ct="102400112",
        component="Diagnostic Analyte Component 24-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_113": ClinicalConcept_24(
        concept_id="CONCEPT_24_113",
        loinc_num="34113-5",
        snomed_ct="102400113",
        component="Diagnostic Analyte Component 24-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_114": ClinicalConcept_24(
        concept_id="CONCEPT_24_114",
        loinc_num="34114-6",
        snomed_ct="102400114",
        component="Diagnostic Analyte Component 24-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_115": ClinicalConcept_24(
        concept_id="CONCEPT_24_115",
        loinc_num="34115-7",
        snomed_ct="102400115",
        component="Diagnostic Analyte Component 24-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_116": ClinicalConcept_24(
        concept_id="CONCEPT_24_116",
        loinc_num="34116-8",
        snomed_ct="102400116",
        component="Diagnostic Analyte Component 24-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_117": ClinicalConcept_24(
        concept_id="CONCEPT_24_117",
        loinc_num="34117-0",
        snomed_ct="102400117",
        component="Diagnostic Analyte Component 24-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_118": ClinicalConcept_24(
        concept_id="CONCEPT_24_118",
        loinc_num="34118-1",
        snomed_ct="102400118",
        component="Diagnostic Analyte Component 24-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_119": ClinicalConcept_24(
        concept_id="CONCEPT_24_119",
        loinc_num="34119-2",
        snomed_ct="102400119",
        component="Diagnostic Analyte Component 24-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_120": ClinicalConcept_24(
        concept_id="CONCEPT_24_120",
        loinc_num="34120-3",
        snomed_ct="102400120",
        component="Diagnostic Analyte Component 24-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_121": ClinicalConcept_24(
        concept_id="CONCEPT_24_121",
        loinc_num="34121-4",
        snomed_ct="102400121",
        component="Diagnostic Analyte Component 24-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_122": ClinicalConcept_24(
        concept_id="CONCEPT_24_122",
        loinc_num="34122-5",
        snomed_ct="102400122",
        component="Diagnostic Analyte Component 24-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_123": ClinicalConcept_24(
        concept_id="CONCEPT_24_123",
        loinc_num="34123-6",
        snomed_ct="102400123",
        component="Diagnostic Analyte Component 24-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_124": ClinicalConcept_24(
        concept_id="CONCEPT_24_124",
        loinc_num="34124-7",
        snomed_ct="102400124",
        component="Diagnostic Analyte Component 24-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_125": ClinicalConcept_24(
        concept_id="CONCEPT_24_125",
        loinc_num="34125-8",
        snomed_ct="102400125",
        component="Diagnostic Analyte Component 24-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_126": ClinicalConcept_24(
        concept_id="CONCEPT_24_126",
        loinc_num="34126-0",
        snomed_ct="102400126",
        component="Diagnostic Analyte Component 24-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_127": ClinicalConcept_24(
        concept_id="CONCEPT_24_127",
        loinc_num="34127-1",
        snomed_ct="102400127",
        component="Diagnostic Analyte Component 24-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_128": ClinicalConcept_24(
        concept_id="CONCEPT_24_128",
        loinc_num="34128-2",
        snomed_ct="102400128",
        component="Diagnostic Analyte Component 24-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_129": ClinicalConcept_24(
        concept_id="CONCEPT_24_129",
        loinc_num="34129-3",
        snomed_ct="102400129",
        component="Diagnostic Analyte Component 24-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_130": ClinicalConcept_24(
        concept_id="CONCEPT_24_130",
        loinc_num="34130-4",
        snomed_ct="102400130",
        component="Diagnostic Analyte Component 24-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_131": ClinicalConcept_24(
        concept_id="CONCEPT_24_131",
        loinc_num="34131-5",
        snomed_ct="102400131",
        component="Diagnostic Analyte Component 24-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_132": ClinicalConcept_24(
        concept_id="CONCEPT_24_132",
        loinc_num="34132-6",
        snomed_ct="102400132",
        component="Diagnostic Analyte Component 24-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_133": ClinicalConcept_24(
        concept_id="CONCEPT_24_133",
        loinc_num="34133-7",
        snomed_ct="102400133",
        component="Diagnostic Analyte Component 24-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_134": ClinicalConcept_24(
        concept_id="CONCEPT_24_134",
        loinc_num="34134-8",
        snomed_ct="102400134",
        component="Diagnostic Analyte Component 24-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_135": ClinicalConcept_24(
        concept_id="CONCEPT_24_135",
        loinc_num="34135-0",
        snomed_ct="102400135",
        component="Diagnostic Analyte Component 24-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_136": ClinicalConcept_24(
        concept_id="CONCEPT_24_136",
        loinc_num="34136-1",
        snomed_ct="102400136",
        component="Diagnostic Analyte Component 24-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_137": ClinicalConcept_24(
        concept_id="CONCEPT_24_137",
        loinc_num="34137-2",
        snomed_ct="102400137",
        component="Diagnostic Analyte Component 24-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_138": ClinicalConcept_24(
        concept_id="CONCEPT_24_138",
        loinc_num="34138-3",
        snomed_ct="102400138",
        component="Diagnostic Analyte Component 24-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_139": ClinicalConcept_24(
        concept_id="CONCEPT_24_139",
        loinc_num="34139-4",
        snomed_ct="102400139",
        component="Diagnostic Analyte Component 24-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_140": ClinicalConcept_24(
        concept_id="CONCEPT_24_140",
        loinc_num="34140-5",
        snomed_ct="102400140",
        component="Diagnostic Analyte Component 24-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_141": ClinicalConcept_24(
        concept_id="CONCEPT_24_141",
        loinc_num="34141-6",
        snomed_ct="102400141",
        component="Diagnostic Analyte Component 24-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_142": ClinicalConcept_24(
        concept_id="CONCEPT_24_142",
        loinc_num="34142-7",
        snomed_ct="102400142",
        component="Diagnostic Analyte Component 24-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_143": ClinicalConcept_24(
        concept_id="CONCEPT_24_143",
        loinc_num="34143-8",
        snomed_ct="102400143",
        component="Diagnostic Analyte Component 24-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_144": ClinicalConcept_24(
        concept_id="CONCEPT_24_144",
        loinc_num="34144-0",
        snomed_ct="102400144",
        component="Diagnostic Analyte Component 24-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_145": ClinicalConcept_24(
        concept_id="CONCEPT_24_145",
        loinc_num="34145-1",
        snomed_ct="102400145",
        component="Diagnostic Analyte Component 24-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_146": ClinicalConcept_24(
        concept_id="CONCEPT_24_146",
        loinc_num="34146-2",
        snomed_ct="102400146",
        component="Diagnostic Analyte Component 24-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_147": ClinicalConcept_24(
        concept_id="CONCEPT_24_147",
        loinc_num="34147-3",
        snomed_ct="102400147",
        component="Diagnostic Analyte Component 24-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_148": ClinicalConcept_24(
        concept_id="CONCEPT_24_148",
        loinc_num="34148-4",
        snomed_ct="102400148",
        component="Diagnostic Analyte Component 24-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_149": ClinicalConcept_24(
        concept_id="CONCEPT_24_149",
        loinc_num="34149-5",
        snomed_ct="102400149",
        component="Diagnostic Analyte Component 24-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_150": ClinicalConcept_24(
        concept_id="CONCEPT_24_150",
        loinc_num="34150-6",
        snomed_ct="102400150",
        component="Diagnostic Analyte Component 24-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_151": ClinicalConcept_24(
        concept_id="CONCEPT_24_151",
        loinc_num="34151-7",
        snomed_ct="102400151",
        component="Diagnostic Analyte Component 24-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_152": ClinicalConcept_24(
        concept_id="CONCEPT_24_152",
        loinc_num="34152-8",
        snomed_ct="102400152",
        component="Diagnostic Analyte Component 24-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_153": ClinicalConcept_24(
        concept_id="CONCEPT_24_153",
        loinc_num="34153-0",
        snomed_ct="102400153",
        component="Diagnostic Analyte Component 24-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_154": ClinicalConcept_24(
        concept_id="CONCEPT_24_154",
        loinc_num="34154-1",
        snomed_ct="102400154",
        component="Diagnostic Analyte Component 24-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_155": ClinicalConcept_24(
        concept_id="CONCEPT_24_155",
        loinc_num="34155-2",
        snomed_ct="102400155",
        component="Diagnostic Analyte Component 24-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_156": ClinicalConcept_24(
        concept_id="CONCEPT_24_156",
        loinc_num="34156-3",
        snomed_ct="102400156",
        component="Diagnostic Analyte Component 24-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_157": ClinicalConcept_24(
        concept_id="CONCEPT_24_157",
        loinc_num="34157-4",
        snomed_ct="102400157",
        component="Diagnostic Analyte Component 24-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_158": ClinicalConcept_24(
        concept_id="CONCEPT_24_158",
        loinc_num="34158-5",
        snomed_ct="102400158",
        component="Diagnostic Analyte Component 24-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_159": ClinicalConcept_24(
        concept_id="CONCEPT_24_159",
        loinc_num="34159-6",
        snomed_ct="102400159",
        component="Diagnostic Analyte Component 24-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_160": ClinicalConcept_24(
        concept_id="CONCEPT_24_160",
        loinc_num="34160-7",
        snomed_ct="102400160",
        component="Diagnostic Analyte Component 24-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_161": ClinicalConcept_24(
        concept_id="CONCEPT_24_161",
        loinc_num="34161-8",
        snomed_ct="102400161",
        component="Diagnostic Analyte Component 24-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_162": ClinicalConcept_24(
        concept_id="CONCEPT_24_162",
        loinc_num="34162-0",
        snomed_ct="102400162",
        component="Diagnostic Analyte Component 24-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_163": ClinicalConcept_24(
        concept_id="CONCEPT_24_163",
        loinc_num="34163-1",
        snomed_ct="102400163",
        component="Diagnostic Analyte Component 24-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_164": ClinicalConcept_24(
        concept_id="CONCEPT_24_164",
        loinc_num="34164-2",
        snomed_ct="102400164",
        component="Diagnostic Analyte Component 24-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_165": ClinicalConcept_24(
        concept_id="CONCEPT_24_165",
        loinc_num="34165-3",
        snomed_ct="102400165",
        component="Diagnostic Analyte Component 24-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_166": ClinicalConcept_24(
        concept_id="CONCEPT_24_166",
        loinc_num="34166-4",
        snomed_ct="102400166",
        component="Diagnostic Analyte Component 24-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_167": ClinicalConcept_24(
        concept_id="CONCEPT_24_167",
        loinc_num="34167-5",
        snomed_ct="102400167",
        component="Diagnostic Analyte Component 24-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_168": ClinicalConcept_24(
        concept_id="CONCEPT_24_168",
        loinc_num="34168-6",
        snomed_ct="102400168",
        component="Diagnostic Analyte Component 24-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_169": ClinicalConcept_24(
        concept_id="CONCEPT_24_169",
        loinc_num="34169-7",
        snomed_ct="102400169",
        component="Diagnostic Analyte Component 24-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_170": ClinicalConcept_24(
        concept_id="CONCEPT_24_170",
        loinc_num="34170-8",
        snomed_ct="102400170",
        component="Diagnostic Analyte Component 24-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_171": ClinicalConcept_24(
        concept_id="CONCEPT_24_171",
        loinc_num="34171-0",
        snomed_ct="102400171",
        component="Diagnostic Analyte Component 24-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_172": ClinicalConcept_24(
        concept_id="CONCEPT_24_172",
        loinc_num="34172-1",
        snomed_ct="102400172",
        component="Diagnostic Analyte Component 24-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_173": ClinicalConcept_24(
        concept_id="CONCEPT_24_173",
        loinc_num="34173-2",
        snomed_ct="102400173",
        component="Diagnostic Analyte Component 24-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_174": ClinicalConcept_24(
        concept_id="CONCEPT_24_174",
        loinc_num="34174-3",
        snomed_ct="102400174",
        component="Diagnostic Analyte Component 24-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_175": ClinicalConcept_24(
        concept_id="CONCEPT_24_175",
        loinc_num="34175-4",
        snomed_ct="102400175",
        component="Diagnostic Analyte Component 24-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_176": ClinicalConcept_24(
        concept_id="CONCEPT_24_176",
        loinc_num="34176-5",
        snomed_ct="102400176",
        component="Diagnostic Analyte Component 24-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_177": ClinicalConcept_24(
        concept_id="CONCEPT_24_177",
        loinc_num="34177-6",
        snomed_ct="102400177",
        component="Diagnostic Analyte Component 24-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_178": ClinicalConcept_24(
        concept_id="CONCEPT_24_178",
        loinc_num="34178-7",
        snomed_ct="102400178",
        component="Diagnostic Analyte Component 24-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_179": ClinicalConcept_24(
        concept_id="CONCEPT_24_179",
        loinc_num="34179-8",
        snomed_ct="102400179",
        component="Diagnostic Analyte Component 24-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_180": ClinicalConcept_24(
        concept_id="CONCEPT_24_180",
        loinc_num="34180-0",
        snomed_ct="102400180",
        component="Diagnostic Analyte Component 24-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_181": ClinicalConcept_24(
        concept_id="CONCEPT_24_181",
        loinc_num="34181-1",
        snomed_ct="102400181",
        component="Diagnostic Analyte Component 24-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_182": ClinicalConcept_24(
        concept_id="CONCEPT_24_182",
        loinc_num="34182-2",
        snomed_ct="102400182",
        component="Diagnostic Analyte Component 24-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_183": ClinicalConcept_24(
        concept_id="CONCEPT_24_183",
        loinc_num="34183-3",
        snomed_ct="102400183",
        component="Diagnostic Analyte Component 24-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_184": ClinicalConcept_24(
        concept_id="CONCEPT_24_184",
        loinc_num="34184-4",
        snomed_ct="102400184",
        component="Diagnostic Analyte Component 24-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_185": ClinicalConcept_24(
        concept_id="CONCEPT_24_185",
        loinc_num="34185-5",
        snomed_ct="102400185",
        component="Diagnostic Analyte Component 24-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_186": ClinicalConcept_24(
        concept_id="CONCEPT_24_186",
        loinc_num="34186-6",
        snomed_ct="102400186",
        component="Diagnostic Analyte Component 24-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_187": ClinicalConcept_24(
        concept_id="CONCEPT_24_187",
        loinc_num="34187-7",
        snomed_ct="102400187",
        component="Diagnostic Analyte Component 24-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_188": ClinicalConcept_24(
        concept_id="CONCEPT_24_188",
        loinc_num="34188-8",
        snomed_ct="102400188",
        component="Diagnostic Analyte Component 24-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_189": ClinicalConcept_24(
        concept_id="CONCEPT_24_189",
        loinc_num="34189-0",
        snomed_ct="102400189",
        component="Diagnostic Analyte Component 24-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_190": ClinicalConcept_24(
        concept_id="CONCEPT_24_190",
        loinc_num="34190-1",
        snomed_ct="102400190",
        component="Diagnostic Analyte Component 24-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_191": ClinicalConcept_24(
        concept_id="CONCEPT_24_191",
        loinc_num="34191-2",
        snomed_ct="102400191",
        component="Diagnostic Analyte Component 24-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_192": ClinicalConcept_24(
        concept_id="CONCEPT_24_192",
        loinc_num="34192-3",
        snomed_ct="102400192",
        component="Diagnostic Analyte Component 24-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_193": ClinicalConcept_24(
        concept_id="CONCEPT_24_193",
        loinc_num="34193-4",
        snomed_ct="102400193",
        component="Diagnostic Analyte Component 24-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_194": ClinicalConcept_24(
        concept_id="CONCEPT_24_194",
        loinc_num="34194-5",
        snomed_ct="102400194",
        component="Diagnostic Analyte Component 24-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_195": ClinicalConcept_24(
        concept_id="CONCEPT_24_195",
        loinc_num="34195-6",
        snomed_ct="102400195",
        component="Diagnostic Analyte Component 24-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_196": ClinicalConcept_24(
        concept_id="CONCEPT_24_196",
        loinc_num="34196-7",
        snomed_ct="102400196",
        component="Diagnostic Analyte Component 24-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_197": ClinicalConcept_24(
        concept_id="CONCEPT_24_197",
        loinc_num="34197-8",
        snomed_ct="102400197",
        component="Diagnostic Analyte Component 24-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_198": ClinicalConcept_24(
        concept_id="CONCEPT_24_198",
        loinc_num="34198-0",
        snomed_ct="102400198",
        component="Diagnostic Analyte Component 24-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_24_199": ClinicalConcept_24(
        concept_id="CONCEPT_24_199",
        loinc_num="34199-1",
        snomed_ct="102400199",
        component="Diagnostic Analyte Component 24-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
