"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 21"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_21:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_21 = {
    "CONCEPT_21_001": ClinicalConcept_21(
        concept_id="CONCEPT_21_001",
        loinc_num="31001-1",
        snomed_ct="102100001",
        component="Diagnostic Analyte Component 21-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_002": ClinicalConcept_21(
        concept_id="CONCEPT_21_002",
        loinc_num="31002-2",
        snomed_ct="102100002",
        component="Diagnostic Analyte Component 21-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_003": ClinicalConcept_21(
        concept_id="CONCEPT_21_003",
        loinc_num="31003-3",
        snomed_ct="102100003",
        component="Diagnostic Analyte Component 21-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_004": ClinicalConcept_21(
        concept_id="CONCEPT_21_004",
        loinc_num="31004-4",
        snomed_ct="102100004",
        component="Diagnostic Analyte Component 21-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_005": ClinicalConcept_21(
        concept_id="CONCEPT_21_005",
        loinc_num="31005-5",
        snomed_ct="102100005",
        component="Diagnostic Analyte Component 21-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_006": ClinicalConcept_21(
        concept_id="CONCEPT_21_006",
        loinc_num="31006-6",
        snomed_ct="102100006",
        component="Diagnostic Analyte Component 21-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_007": ClinicalConcept_21(
        concept_id="CONCEPT_21_007",
        loinc_num="31007-7",
        snomed_ct="102100007",
        component="Diagnostic Analyte Component 21-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_008": ClinicalConcept_21(
        concept_id="CONCEPT_21_008",
        loinc_num="31008-8",
        snomed_ct="102100008",
        component="Diagnostic Analyte Component 21-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_009": ClinicalConcept_21(
        concept_id="CONCEPT_21_009",
        loinc_num="31009-0",
        snomed_ct="102100009",
        component="Diagnostic Analyte Component 21-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_010": ClinicalConcept_21(
        concept_id="CONCEPT_21_010",
        loinc_num="31010-1",
        snomed_ct="102100010",
        component="Diagnostic Analyte Component 21-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_011": ClinicalConcept_21(
        concept_id="CONCEPT_21_011",
        loinc_num="31011-2",
        snomed_ct="102100011",
        component="Diagnostic Analyte Component 21-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_012": ClinicalConcept_21(
        concept_id="CONCEPT_21_012",
        loinc_num="31012-3",
        snomed_ct="102100012",
        component="Diagnostic Analyte Component 21-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_013": ClinicalConcept_21(
        concept_id="CONCEPT_21_013",
        loinc_num="31013-4",
        snomed_ct="102100013",
        component="Diagnostic Analyte Component 21-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_014": ClinicalConcept_21(
        concept_id="CONCEPT_21_014",
        loinc_num="31014-5",
        snomed_ct="102100014",
        component="Diagnostic Analyte Component 21-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_015": ClinicalConcept_21(
        concept_id="CONCEPT_21_015",
        loinc_num="31015-6",
        snomed_ct="102100015",
        component="Diagnostic Analyte Component 21-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_016": ClinicalConcept_21(
        concept_id="CONCEPT_21_016",
        loinc_num="31016-7",
        snomed_ct="102100016",
        component="Diagnostic Analyte Component 21-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_017": ClinicalConcept_21(
        concept_id="CONCEPT_21_017",
        loinc_num="31017-8",
        snomed_ct="102100017",
        component="Diagnostic Analyte Component 21-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_018": ClinicalConcept_21(
        concept_id="CONCEPT_21_018",
        loinc_num="31018-0",
        snomed_ct="102100018",
        component="Diagnostic Analyte Component 21-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_019": ClinicalConcept_21(
        concept_id="CONCEPT_21_019",
        loinc_num="31019-1",
        snomed_ct="102100019",
        component="Diagnostic Analyte Component 21-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_020": ClinicalConcept_21(
        concept_id="CONCEPT_21_020",
        loinc_num="31020-2",
        snomed_ct="102100020",
        component="Diagnostic Analyte Component 21-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_021": ClinicalConcept_21(
        concept_id="CONCEPT_21_021",
        loinc_num="31021-3",
        snomed_ct="102100021",
        component="Diagnostic Analyte Component 21-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_022": ClinicalConcept_21(
        concept_id="CONCEPT_21_022",
        loinc_num="31022-4",
        snomed_ct="102100022",
        component="Diagnostic Analyte Component 21-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_023": ClinicalConcept_21(
        concept_id="CONCEPT_21_023",
        loinc_num="31023-5",
        snomed_ct="102100023",
        component="Diagnostic Analyte Component 21-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_024": ClinicalConcept_21(
        concept_id="CONCEPT_21_024",
        loinc_num="31024-6",
        snomed_ct="102100024",
        component="Diagnostic Analyte Component 21-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_025": ClinicalConcept_21(
        concept_id="CONCEPT_21_025",
        loinc_num="31025-7",
        snomed_ct="102100025",
        component="Diagnostic Analyte Component 21-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_026": ClinicalConcept_21(
        concept_id="CONCEPT_21_026",
        loinc_num="31026-8",
        snomed_ct="102100026",
        component="Diagnostic Analyte Component 21-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_027": ClinicalConcept_21(
        concept_id="CONCEPT_21_027",
        loinc_num="31027-0",
        snomed_ct="102100027",
        component="Diagnostic Analyte Component 21-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_028": ClinicalConcept_21(
        concept_id="CONCEPT_21_028",
        loinc_num="31028-1",
        snomed_ct="102100028",
        component="Diagnostic Analyte Component 21-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_029": ClinicalConcept_21(
        concept_id="CONCEPT_21_029",
        loinc_num="31029-2",
        snomed_ct="102100029",
        component="Diagnostic Analyte Component 21-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_030": ClinicalConcept_21(
        concept_id="CONCEPT_21_030",
        loinc_num="31030-3",
        snomed_ct="102100030",
        component="Diagnostic Analyte Component 21-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_031": ClinicalConcept_21(
        concept_id="CONCEPT_21_031",
        loinc_num="31031-4",
        snomed_ct="102100031",
        component="Diagnostic Analyte Component 21-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_032": ClinicalConcept_21(
        concept_id="CONCEPT_21_032",
        loinc_num="31032-5",
        snomed_ct="102100032",
        component="Diagnostic Analyte Component 21-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_033": ClinicalConcept_21(
        concept_id="CONCEPT_21_033",
        loinc_num="31033-6",
        snomed_ct="102100033",
        component="Diagnostic Analyte Component 21-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_034": ClinicalConcept_21(
        concept_id="CONCEPT_21_034",
        loinc_num="31034-7",
        snomed_ct="102100034",
        component="Diagnostic Analyte Component 21-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_035": ClinicalConcept_21(
        concept_id="CONCEPT_21_035",
        loinc_num="31035-8",
        snomed_ct="102100035",
        component="Diagnostic Analyte Component 21-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_036": ClinicalConcept_21(
        concept_id="CONCEPT_21_036",
        loinc_num="31036-0",
        snomed_ct="102100036",
        component="Diagnostic Analyte Component 21-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_037": ClinicalConcept_21(
        concept_id="CONCEPT_21_037",
        loinc_num="31037-1",
        snomed_ct="102100037",
        component="Diagnostic Analyte Component 21-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_038": ClinicalConcept_21(
        concept_id="CONCEPT_21_038",
        loinc_num="31038-2",
        snomed_ct="102100038",
        component="Diagnostic Analyte Component 21-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_039": ClinicalConcept_21(
        concept_id="CONCEPT_21_039",
        loinc_num="31039-3",
        snomed_ct="102100039",
        component="Diagnostic Analyte Component 21-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_040": ClinicalConcept_21(
        concept_id="CONCEPT_21_040",
        loinc_num="31040-4",
        snomed_ct="102100040",
        component="Diagnostic Analyte Component 21-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_041": ClinicalConcept_21(
        concept_id="CONCEPT_21_041",
        loinc_num="31041-5",
        snomed_ct="102100041",
        component="Diagnostic Analyte Component 21-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_042": ClinicalConcept_21(
        concept_id="CONCEPT_21_042",
        loinc_num="31042-6",
        snomed_ct="102100042",
        component="Diagnostic Analyte Component 21-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_043": ClinicalConcept_21(
        concept_id="CONCEPT_21_043",
        loinc_num="31043-7",
        snomed_ct="102100043",
        component="Diagnostic Analyte Component 21-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_044": ClinicalConcept_21(
        concept_id="CONCEPT_21_044",
        loinc_num="31044-8",
        snomed_ct="102100044",
        component="Diagnostic Analyte Component 21-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_045": ClinicalConcept_21(
        concept_id="CONCEPT_21_045",
        loinc_num="31045-0",
        snomed_ct="102100045",
        component="Diagnostic Analyte Component 21-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_046": ClinicalConcept_21(
        concept_id="CONCEPT_21_046",
        loinc_num="31046-1",
        snomed_ct="102100046",
        component="Diagnostic Analyte Component 21-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_047": ClinicalConcept_21(
        concept_id="CONCEPT_21_047",
        loinc_num="31047-2",
        snomed_ct="102100047",
        component="Diagnostic Analyte Component 21-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_048": ClinicalConcept_21(
        concept_id="CONCEPT_21_048",
        loinc_num="31048-3",
        snomed_ct="102100048",
        component="Diagnostic Analyte Component 21-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_049": ClinicalConcept_21(
        concept_id="CONCEPT_21_049",
        loinc_num="31049-4",
        snomed_ct="102100049",
        component="Diagnostic Analyte Component 21-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_050": ClinicalConcept_21(
        concept_id="CONCEPT_21_050",
        loinc_num="31050-5",
        snomed_ct="102100050",
        component="Diagnostic Analyte Component 21-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_051": ClinicalConcept_21(
        concept_id="CONCEPT_21_051",
        loinc_num="31051-6",
        snomed_ct="102100051",
        component="Diagnostic Analyte Component 21-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_052": ClinicalConcept_21(
        concept_id="CONCEPT_21_052",
        loinc_num="31052-7",
        snomed_ct="102100052",
        component="Diagnostic Analyte Component 21-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_053": ClinicalConcept_21(
        concept_id="CONCEPT_21_053",
        loinc_num="31053-8",
        snomed_ct="102100053",
        component="Diagnostic Analyte Component 21-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_054": ClinicalConcept_21(
        concept_id="CONCEPT_21_054",
        loinc_num="31054-0",
        snomed_ct="102100054",
        component="Diagnostic Analyte Component 21-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_055": ClinicalConcept_21(
        concept_id="CONCEPT_21_055",
        loinc_num="31055-1",
        snomed_ct="102100055",
        component="Diagnostic Analyte Component 21-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_056": ClinicalConcept_21(
        concept_id="CONCEPT_21_056",
        loinc_num="31056-2",
        snomed_ct="102100056",
        component="Diagnostic Analyte Component 21-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_057": ClinicalConcept_21(
        concept_id="CONCEPT_21_057",
        loinc_num="31057-3",
        snomed_ct="102100057",
        component="Diagnostic Analyte Component 21-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_058": ClinicalConcept_21(
        concept_id="CONCEPT_21_058",
        loinc_num="31058-4",
        snomed_ct="102100058",
        component="Diagnostic Analyte Component 21-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_059": ClinicalConcept_21(
        concept_id="CONCEPT_21_059",
        loinc_num="31059-5",
        snomed_ct="102100059",
        component="Diagnostic Analyte Component 21-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_060": ClinicalConcept_21(
        concept_id="CONCEPT_21_060",
        loinc_num="31060-6",
        snomed_ct="102100060",
        component="Diagnostic Analyte Component 21-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_061": ClinicalConcept_21(
        concept_id="CONCEPT_21_061",
        loinc_num="31061-7",
        snomed_ct="102100061",
        component="Diagnostic Analyte Component 21-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_062": ClinicalConcept_21(
        concept_id="CONCEPT_21_062",
        loinc_num="31062-8",
        snomed_ct="102100062",
        component="Diagnostic Analyte Component 21-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_063": ClinicalConcept_21(
        concept_id="CONCEPT_21_063",
        loinc_num="31063-0",
        snomed_ct="102100063",
        component="Diagnostic Analyte Component 21-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_064": ClinicalConcept_21(
        concept_id="CONCEPT_21_064",
        loinc_num="31064-1",
        snomed_ct="102100064",
        component="Diagnostic Analyte Component 21-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_065": ClinicalConcept_21(
        concept_id="CONCEPT_21_065",
        loinc_num="31065-2",
        snomed_ct="102100065",
        component="Diagnostic Analyte Component 21-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_066": ClinicalConcept_21(
        concept_id="CONCEPT_21_066",
        loinc_num="31066-3",
        snomed_ct="102100066",
        component="Diagnostic Analyte Component 21-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_067": ClinicalConcept_21(
        concept_id="CONCEPT_21_067",
        loinc_num="31067-4",
        snomed_ct="102100067",
        component="Diagnostic Analyte Component 21-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_068": ClinicalConcept_21(
        concept_id="CONCEPT_21_068",
        loinc_num="31068-5",
        snomed_ct="102100068",
        component="Diagnostic Analyte Component 21-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_069": ClinicalConcept_21(
        concept_id="CONCEPT_21_069",
        loinc_num="31069-6",
        snomed_ct="102100069",
        component="Diagnostic Analyte Component 21-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_070": ClinicalConcept_21(
        concept_id="CONCEPT_21_070",
        loinc_num="31070-7",
        snomed_ct="102100070",
        component="Diagnostic Analyte Component 21-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_071": ClinicalConcept_21(
        concept_id="CONCEPT_21_071",
        loinc_num="31071-8",
        snomed_ct="102100071",
        component="Diagnostic Analyte Component 21-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_072": ClinicalConcept_21(
        concept_id="CONCEPT_21_072",
        loinc_num="31072-0",
        snomed_ct="102100072",
        component="Diagnostic Analyte Component 21-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_073": ClinicalConcept_21(
        concept_id="CONCEPT_21_073",
        loinc_num="31073-1",
        snomed_ct="102100073",
        component="Diagnostic Analyte Component 21-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_074": ClinicalConcept_21(
        concept_id="CONCEPT_21_074",
        loinc_num="31074-2",
        snomed_ct="102100074",
        component="Diagnostic Analyte Component 21-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_075": ClinicalConcept_21(
        concept_id="CONCEPT_21_075",
        loinc_num="31075-3",
        snomed_ct="102100075",
        component="Diagnostic Analyte Component 21-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_076": ClinicalConcept_21(
        concept_id="CONCEPT_21_076",
        loinc_num="31076-4",
        snomed_ct="102100076",
        component="Diagnostic Analyte Component 21-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_077": ClinicalConcept_21(
        concept_id="CONCEPT_21_077",
        loinc_num="31077-5",
        snomed_ct="102100077",
        component="Diagnostic Analyte Component 21-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_078": ClinicalConcept_21(
        concept_id="CONCEPT_21_078",
        loinc_num="31078-6",
        snomed_ct="102100078",
        component="Diagnostic Analyte Component 21-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_079": ClinicalConcept_21(
        concept_id="CONCEPT_21_079",
        loinc_num="31079-7",
        snomed_ct="102100079",
        component="Diagnostic Analyte Component 21-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_080": ClinicalConcept_21(
        concept_id="CONCEPT_21_080",
        loinc_num="31080-8",
        snomed_ct="102100080",
        component="Diagnostic Analyte Component 21-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_081": ClinicalConcept_21(
        concept_id="CONCEPT_21_081",
        loinc_num="31081-0",
        snomed_ct="102100081",
        component="Diagnostic Analyte Component 21-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_082": ClinicalConcept_21(
        concept_id="CONCEPT_21_082",
        loinc_num="31082-1",
        snomed_ct="102100082",
        component="Diagnostic Analyte Component 21-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_083": ClinicalConcept_21(
        concept_id="CONCEPT_21_083",
        loinc_num="31083-2",
        snomed_ct="102100083",
        component="Diagnostic Analyte Component 21-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_084": ClinicalConcept_21(
        concept_id="CONCEPT_21_084",
        loinc_num="31084-3",
        snomed_ct="102100084",
        component="Diagnostic Analyte Component 21-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_085": ClinicalConcept_21(
        concept_id="CONCEPT_21_085",
        loinc_num="31085-4",
        snomed_ct="102100085",
        component="Diagnostic Analyte Component 21-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_086": ClinicalConcept_21(
        concept_id="CONCEPT_21_086",
        loinc_num="31086-5",
        snomed_ct="102100086",
        component="Diagnostic Analyte Component 21-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_087": ClinicalConcept_21(
        concept_id="CONCEPT_21_087",
        loinc_num="31087-6",
        snomed_ct="102100087",
        component="Diagnostic Analyte Component 21-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_088": ClinicalConcept_21(
        concept_id="CONCEPT_21_088",
        loinc_num="31088-7",
        snomed_ct="102100088",
        component="Diagnostic Analyte Component 21-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_089": ClinicalConcept_21(
        concept_id="CONCEPT_21_089",
        loinc_num="31089-8",
        snomed_ct="102100089",
        component="Diagnostic Analyte Component 21-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_090": ClinicalConcept_21(
        concept_id="CONCEPT_21_090",
        loinc_num="31090-0",
        snomed_ct="102100090",
        component="Diagnostic Analyte Component 21-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_091": ClinicalConcept_21(
        concept_id="CONCEPT_21_091",
        loinc_num="31091-1",
        snomed_ct="102100091",
        component="Diagnostic Analyte Component 21-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_092": ClinicalConcept_21(
        concept_id="CONCEPT_21_092",
        loinc_num="31092-2",
        snomed_ct="102100092",
        component="Diagnostic Analyte Component 21-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_093": ClinicalConcept_21(
        concept_id="CONCEPT_21_093",
        loinc_num="31093-3",
        snomed_ct="102100093",
        component="Diagnostic Analyte Component 21-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_094": ClinicalConcept_21(
        concept_id="CONCEPT_21_094",
        loinc_num="31094-4",
        snomed_ct="102100094",
        component="Diagnostic Analyte Component 21-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_095": ClinicalConcept_21(
        concept_id="CONCEPT_21_095",
        loinc_num="31095-5",
        snomed_ct="102100095",
        component="Diagnostic Analyte Component 21-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_096": ClinicalConcept_21(
        concept_id="CONCEPT_21_096",
        loinc_num="31096-6",
        snomed_ct="102100096",
        component="Diagnostic Analyte Component 21-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_097": ClinicalConcept_21(
        concept_id="CONCEPT_21_097",
        loinc_num="31097-7",
        snomed_ct="102100097",
        component="Diagnostic Analyte Component 21-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_098": ClinicalConcept_21(
        concept_id="CONCEPT_21_098",
        loinc_num="31098-8",
        snomed_ct="102100098",
        component="Diagnostic Analyte Component 21-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_099": ClinicalConcept_21(
        concept_id="CONCEPT_21_099",
        loinc_num="31099-0",
        snomed_ct="102100099",
        component="Diagnostic Analyte Component 21-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_100": ClinicalConcept_21(
        concept_id="CONCEPT_21_100",
        loinc_num="31100-1",
        snomed_ct="102100100",
        component="Diagnostic Analyte Component 21-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_101": ClinicalConcept_21(
        concept_id="CONCEPT_21_101",
        loinc_num="31101-2",
        snomed_ct="102100101",
        component="Diagnostic Analyte Component 21-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_102": ClinicalConcept_21(
        concept_id="CONCEPT_21_102",
        loinc_num="31102-3",
        snomed_ct="102100102",
        component="Diagnostic Analyte Component 21-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_103": ClinicalConcept_21(
        concept_id="CONCEPT_21_103",
        loinc_num="31103-4",
        snomed_ct="102100103",
        component="Diagnostic Analyte Component 21-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_104": ClinicalConcept_21(
        concept_id="CONCEPT_21_104",
        loinc_num="31104-5",
        snomed_ct="102100104",
        component="Diagnostic Analyte Component 21-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_105": ClinicalConcept_21(
        concept_id="CONCEPT_21_105",
        loinc_num="31105-6",
        snomed_ct="102100105",
        component="Diagnostic Analyte Component 21-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_106": ClinicalConcept_21(
        concept_id="CONCEPT_21_106",
        loinc_num="31106-7",
        snomed_ct="102100106",
        component="Diagnostic Analyte Component 21-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_107": ClinicalConcept_21(
        concept_id="CONCEPT_21_107",
        loinc_num="31107-8",
        snomed_ct="102100107",
        component="Diagnostic Analyte Component 21-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_108": ClinicalConcept_21(
        concept_id="CONCEPT_21_108",
        loinc_num="31108-0",
        snomed_ct="102100108",
        component="Diagnostic Analyte Component 21-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_109": ClinicalConcept_21(
        concept_id="CONCEPT_21_109",
        loinc_num="31109-1",
        snomed_ct="102100109",
        component="Diagnostic Analyte Component 21-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_110": ClinicalConcept_21(
        concept_id="CONCEPT_21_110",
        loinc_num="31110-2",
        snomed_ct="102100110",
        component="Diagnostic Analyte Component 21-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_111": ClinicalConcept_21(
        concept_id="CONCEPT_21_111",
        loinc_num="31111-3",
        snomed_ct="102100111",
        component="Diagnostic Analyte Component 21-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_112": ClinicalConcept_21(
        concept_id="CONCEPT_21_112",
        loinc_num="31112-4",
        snomed_ct="102100112",
        component="Diagnostic Analyte Component 21-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_113": ClinicalConcept_21(
        concept_id="CONCEPT_21_113",
        loinc_num="31113-5",
        snomed_ct="102100113",
        component="Diagnostic Analyte Component 21-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_114": ClinicalConcept_21(
        concept_id="CONCEPT_21_114",
        loinc_num="31114-6",
        snomed_ct="102100114",
        component="Diagnostic Analyte Component 21-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_115": ClinicalConcept_21(
        concept_id="CONCEPT_21_115",
        loinc_num="31115-7",
        snomed_ct="102100115",
        component="Diagnostic Analyte Component 21-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_116": ClinicalConcept_21(
        concept_id="CONCEPT_21_116",
        loinc_num="31116-8",
        snomed_ct="102100116",
        component="Diagnostic Analyte Component 21-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_117": ClinicalConcept_21(
        concept_id="CONCEPT_21_117",
        loinc_num="31117-0",
        snomed_ct="102100117",
        component="Diagnostic Analyte Component 21-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_118": ClinicalConcept_21(
        concept_id="CONCEPT_21_118",
        loinc_num="31118-1",
        snomed_ct="102100118",
        component="Diagnostic Analyte Component 21-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_119": ClinicalConcept_21(
        concept_id="CONCEPT_21_119",
        loinc_num="31119-2",
        snomed_ct="102100119",
        component="Diagnostic Analyte Component 21-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_120": ClinicalConcept_21(
        concept_id="CONCEPT_21_120",
        loinc_num="31120-3",
        snomed_ct="102100120",
        component="Diagnostic Analyte Component 21-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_121": ClinicalConcept_21(
        concept_id="CONCEPT_21_121",
        loinc_num="31121-4",
        snomed_ct="102100121",
        component="Diagnostic Analyte Component 21-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_122": ClinicalConcept_21(
        concept_id="CONCEPT_21_122",
        loinc_num="31122-5",
        snomed_ct="102100122",
        component="Diagnostic Analyte Component 21-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_123": ClinicalConcept_21(
        concept_id="CONCEPT_21_123",
        loinc_num="31123-6",
        snomed_ct="102100123",
        component="Diagnostic Analyte Component 21-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_124": ClinicalConcept_21(
        concept_id="CONCEPT_21_124",
        loinc_num="31124-7",
        snomed_ct="102100124",
        component="Diagnostic Analyte Component 21-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_125": ClinicalConcept_21(
        concept_id="CONCEPT_21_125",
        loinc_num="31125-8",
        snomed_ct="102100125",
        component="Diagnostic Analyte Component 21-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_126": ClinicalConcept_21(
        concept_id="CONCEPT_21_126",
        loinc_num="31126-0",
        snomed_ct="102100126",
        component="Diagnostic Analyte Component 21-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_127": ClinicalConcept_21(
        concept_id="CONCEPT_21_127",
        loinc_num="31127-1",
        snomed_ct="102100127",
        component="Diagnostic Analyte Component 21-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_128": ClinicalConcept_21(
        concept_id="CONCEPT_21_128",
        loinc_num="31128-2",
        snomed_ct="102100128",
        component="Diagnostic Analyte Component 21-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_129": ClinicalConcept_21(
        concept_id="CONCEPT_21_129",
        loinc_num="31129-3",
        snomed_ct="102100129",
        component="Diagnostic Analyte Component 21-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_130": ClinicalConcept_21(
        concept_id="CONCEPT_21_130",
        loinc_num="31130-4",
        snomed_ct="102100130",
        component="Diagnostic Analyte Component 21-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_131": ClinicalConcept_21(
        concept_id="CONCEPT_21_131",
        loinc_num="31131-5",
        snomed_ct="102100131",
        component="Diagnostic Analyte Component 21-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_132": ClinicalConcept_21(
        concept_id="CONCEPT_21_132",
        loinc_num="31132-6",
        snomed_ct="102100132",
        component="Diagnostic Analyte Component 21-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_133": ClinicalConcept_21(
        concept_id="CONCEPT_21_133",
        loinc_num="31133-7",
        snomed_ct="102100133",
        component="Diagnostic Analyte Component 21-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_134": ClinicalConcept_21(
        concept_id="CONCEPT_21_134",
        loinc_num="31134-8",
        snomed_ct="102100134",
        component="Diagnostic Analyte Component 21-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_135": ClinicalConcept_21(
        concept_id="CONCEPT_21_135",
        loinc_num="31135-0",
        snomed_ct="102100135",
        component="Diagnostic Analyte Component 21-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_136": ClinicalConcept_21(
        concept_id="CONCEPT_21_136",
        loinc_num="31136-1",
        snomed_ct="102100136",
        component="Diagnostic Analyte Component 21-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_137": ClinicalConcept_21(
        concept_id="CONCEPT_21_137",
        loinc_num="31137-2",
        snomed_ct="102100137",
        component="Diagnostic Analyte Component 21-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_138": ClinicalConcept_21(
        concept_id="CONCEPT_21_138",
        loinc_num="31138-3",
        snomed_ct="102100138",
        component="Diagnostic Analyte Component 21-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_139": ClinicalConcept_21(
        concept_id="CONCEPT_21_139",
        loinc_num="31139-4",
        snomed_ct="102100139",
        component="Diagnostic Analyte Component 21-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_140": ClinicalConcept_21(
        concept_id="CONCEPT_21_140",
        loinc_num="31140-5",
        snomed_ct="102100140",
        component="Diagnostic Analyte Component 21-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_141": ClinicalConcept_21(
        concept_id="CONCEPT_21_141",
        loinc_num="31141-6",
        snomed_ct="102100141",
        component="Diagnostic Analyte Component 21-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_142": ClinicalConcept_21(
        concept_id="CONCEPT_21_142",
        loinc_num="31142-7",
        snomed_ct="102100142",
        component="Diagnostic Analyte Component 21-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_143": ClinicalConcept_21(
        concept_id="CONCEPT_21_143",
        loinc_num="31143-8",
        snomed_ct="102100143",
        component="Diagnostic Analyte Component 21-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_144": ClinicalConcept_21(
        concept_id="CONCEPT_21_144",
        loinc_num="31144-0",
        snomed_ct="102100144",
        component="Diagnostic Analyte Component 21-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_145": ClinicalConcept_21(
        concept_id="CONCEPT_21_145",
        loinc_num="31145-1",
        snomed_ct="102100145",
        component="Diagnostic Analyte Component 21-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_146": ClinicalConcept_21(
        concept_id="CONCEPT_21_146",
        loinc_num="31146-2",
        snomed_ct="102100146",
        component="Diagnostic Analyte Component 21-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_147": ClinicalConcept_21(
        concept_id="CONCEPT_21_147",
        loinc_num="31147-3",
        snomed_ct="102100147",
        component="Diagnostic Analyte Component 21-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_148": ClinicalConcept_21(
        concept_id="CONCEPT_21_148",
        loinc_num="31148-4",
        snomed_ct="102100148",
        component="Diagnostic Analyte Component 21-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_149": ClinicalConcept_21(
        concept_id="CONCEPT_21_149",
        loinc_num="31149-5",
        snomed_ct="102100149",
        component="Diagnostic Analyte Component 21-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_150": ClinicalConcept_21(
        concept_id="CONCEPT_21_150",
        loinc_num="31150-6",
        snomed_ct="102100150",
        component="Diagnostic Analyte Component 21-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_151": ClinicalConcept_21(
        concept_id="CONCEPT_21_151",
        loinc_num="31151-7",
        snomed_ct="102100151",
        component="Diagnostic Analyte Component 21-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_152": ClinicalConcept_21(
        concept_id="CONCEPT_21_152",
        loinc_num="31152-8",
        snomed_ct="102100152",
        component="Diagnostic Analyte Component 21-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_153": ClinicalConcept_21(
        concept_id="CONCEPT_21_153",
        loinc_num="31153-0",
        snomed_ct="102100153",
        component="Diagnostic Analyte Component 21-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_154": ClinicalConcept_21(
        concept_id="CONCEPT_21_154",
        loinc_num="31154-1",
        snomed_ct="102100154",
        component="Diagnostic Analyte Component 21-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_155": ClinicalConcept_21(
        concept_id="CONCEPT_21_155",
        loinc_num="31155-2",
        snomed_ct="102100155",
        component="Diagnostic Analyte Component 21-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_156": ClinicalConcept_21(
        concept_id="CONCEPT_21_156",
        loinc_num="31156-3",
        snomed_ct="102100156",
        component="Diagnostic Analyte Component 21-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_157": ClinicalConcept_21(
        concept_id="CONCEPT_21_157",
        loinc_num="31157-4",
        snomed_ct="102100157",
        component="Diagnostic Analyte Component 21-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_158": ClinicalConcept_21(
        concept_id="CONCEPT_21_158",
        loinc_num="31158-5",
        snomed_ct="102100158",
        component="Diagnostic Analyte Component 21-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_159": ClinicalConcept_21(
        concept_id="CONCEPT_21_159",
        loinc_num="31159-6",
        snomed_ct="102100159",
        component="Diagnostic Analyte Component 21-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_160": ClinicalConcept_21(
        concept_id="CONCEPT_21_160",
        loinc_num="31160-7",
        snomed_ct="102100160",
        component="Diagnostic Analyte Component 21-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_161": ClinicalConcept_21(
        concept_id="CONCEPT_21_161",
        loinc_num="31161-8",
        snomed_ct="102100161",
        component="Diagnostic Analyte Component 21-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_162": ClinicalConcept_21(
        concept_id="CONCEPT_21_162",
        loinc_num="31162-0",
        snomed_ct="102100162",
        component="Diagnostic Analyte Component 21-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_163": ClinicalConcept_21(
        concept_id="CONCEPT_21_163",
        loinc_num="31163-1",
        snomed_ct="102100163",
        component="Diagnostic Analyte Component 21-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_164": ClinicalConcept_21(
        concept_id="CONCEPT_21_164",
        loinc_num="31164-2",
        snomed_ct="102100164",
        component="Diagnostic Analyte Component 21-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_165": ClinicalConcept_21(
        concept_id="CONCEPT_21_165",
        loinc_num="31165-3",
        snomed_ct="102100165",
        component="Diagnostic Analyte Component 21-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_166": ClinicalConcept_21(
        concept_id="CONCEPT_21_166",
        loinc_num="31166-4",
        snomed_ct="102100166",
        component="Diagnostic Analyte Component 21-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_167": ClinicalConcept_21(
        concept_id="CONCEPT_21_167",
        loinc_num="31167-5",
        snomed_ct="102100167",
        component="Diagnostic Analyte Component 21-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_168": ClinicalConcept_21(
        concept_id="CONCEPT_21_168",
        loinc_num="31168-6",
        snomed_ct="102100168",
        component="Diagnostic Analyte Component 21-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_169": ClinicalConcept_21(
        concept_id="CONCEPT_21_169",
        loinc_num="31169-7",
        snomed_ct="102100169",
        component="Diagnostic Analyte Component 21-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_170": ClinicalConcept_21(
        concept_id="CONCEPT_21_170",
        loinc_num="31170-8",
        snomed_ct="102100170",
        component="Diagnostic Analyte Component 21-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_171": ClinicalConcept_21(
        concept_id="CONCEPT_21_171",
        loinc_num="31171-0",
        snomed_ct="102100171",
        component="Diagnostic Analyte Component 21-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_172": ClinicalConcept_21(
        concept_id="CONCEPT_21_172",
        loinc_num="31172-1",
        snomed_ct="102100172",
        component="Diagnostic Analyte Component 21-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_173": ClinicalConcept_21(
        concept_id="CONCEPT_21_173",
        loinc_num="31173-2",
        snomed_ct="102100173",
        component="Diagnostic Analyte Component 21-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_174": ClinicalConcept_21(
        concept_id="CONCEPT_21_174",
        loinc_num="31174-3",
        snomed_ct="102100174",
        component="Diagnostic Analyte Component 21-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_175": ClinicalConcept_21(
        concept_id="CONCEPT_21_175",
        loinc_num="31175-4",
        snomed_ct="102100175",
        component="Diagnostic Analyte Component 21-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_176": ClinicalConcept_21(
        concept_id="CONCEPT_21_176",
        loinc_num="31176-5",
        snomed_ct="102100176",
        component="Diagnostic Analyte Component 21-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_177": ClinicalConcept_21(
        concept_id="CONCEPT_21_177",
        loinc_num="31177-6",
        snomed_ct="102100177",
        component="Diagnostic Analyte Component 21-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_178": ClinicalConcept_21(
        concept_id="CONCEPT_21_178",
        loinc_num="31178-7",
        snomed_ct="102100178",
        component="Diagnostic Analyte Component 21-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_179": ClinicalConcept_21(
        concept_id="CONCEPT_21_179",
        loinc_num="31179-8",
        snomed_ct="102100179",
        component="Diagnostic Analyte Component 21-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_180": ClinicalConcept_21(
        concept_id="CONCEPT_21_180",
        loinc_num="31180-0",
        snomed_ct="102100180",
        component="Diagnostic Analyte Component 21-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_181": ClinicalConcept_21(
        concept_id="CONCEPT_21_181",
        loinc_num="31181-1",
        snomed_ct="102100181",
        component="Diagnostic Analyte Component 21-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_182": ClinicalConcept_21(
        concept_id="CONCEPT_21_182",
        loinc_num="31182-2",
        snomed_ct="102100182",
        component="Diagnostic Analyte Component 21-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_183": ClinicalConcept_21(
        concept_id="CONCEPT_21_183",
        loinc_num="31183-3",
        snomed_ct="102100183",
        component="Diagnostic Analyte Component 21-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_184": ClinicalConcept_21(
        concept_id="CONCEPT_21_184",
        loinc_num="31184-4",
        snomed_ct="102100184",
        component="Diagnostic Analyte Component 21-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_185": ClinicalConcept_21(
        concept_id="CONCEPT_21_185",
        loinc_num="31185-5",
        snomed_ct="102100185",
        component="Diagnostic Analyte Component 21-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_186": ClinicalConcept_21(
        concept_id="CONCEPT_21_186",
        loinc_num="31186-6",
        snomed_ct="102100186",
        component="Diagnostic Analyte Component 21-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_187": ClinicalConcept_21(
        concept_id="CONCEPT_21_187",
        loinc_num="31187-7",
        snomed_ct="102100187",
        component="Diagnostic Analyte Component 21-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_188": ClinicalConcept_21(
        concept_id="CONCEPT_21_188",
        loinc_num="31188-8",
        snomed_ct="102100188",
        component="Diagnostic Analyte Component 21-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_189": ClinicalConcept_21(
        concept_id="CONCEPT_21_189",
        loinc_num="31189-0",
        snomed_ct="102100189",
        component="Diagnostic Analyte Component 21-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_190": ClinicalConcept_21(
        concept_id="CONCEPT_21_190",
        loinc_num="31190-1",
        snomed_ct="102100190",
        component="Diagnostic Analyte Component 21-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_191": ClinicalConcept_21(
        concept_id="CONCEPT_21_191",
        loinc_num="31191-2",
        snomed_ct="102100191",
        component="Diagnostic Analyte Component 21-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_192": ClinicalConcept_21(
        concept_id="CONCEPT_21_192",
        loinc_num="31192-3",
        snomed_ct="102100192",
        component="Diagnostic Analyte Component 21-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_193": ClinicalConcept_21(
        concept_id="CONCEPT_21_193",
        loinc_num="31193-4",
        snomed_ct="102100193",
        component="Diagnostic Analyte Component 21-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_194": ClinicalConcept_21(
        concept_id="CONCEPT_21_194",
        loinc_num="31194-5",
        snomed_ct="102100194",
        component="Diagnostic Analyte Component 21-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_195": ClinicalConcept_21(
        concept_id="CONCEPT_21_195",
        loinc_num="31195-6",
        snomed_ct="102100195",
        component="Diagnostic Analyte Component 21-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_196": ClinicalConcept_21(
        concept_id="CONCEPT_21_196",
        loinc_num="31196-7",
        snomed_ct="102100196",
        component="Diagnostic Analyte Component 21-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_197": ClinicalConcept_21(
        concept_id="CONCEPT_21_197",
        loinc_num="31197-8",
        snomed_ct="102100197",
        component="Diagnostic Analyte Component 21-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_198": ClinicalConcept_21(
        concept_id="CONCEPT_21_198",
        loinc_num="31198-0",
        snomed_ct="102100198",
        component="Diagnostic Analyte Component 21-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_21_199": ClinicalConcept_21(
        concept_id="CONCEPT_21_199",
        loinc_num="31199-1",
        snomed_ct="102100199",
        component="Diagnostic Analyte Component 21-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
