"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 10"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_10:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_10 = {
    "CONCEPT_10_001": ClinicalConcept_10(
        concept_id="CONCEPT_10_001",
        loinc_num="20001-1",
        snomed_ct="101000001",
        component="Diagnostic Analyte Component 10-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_002": ClinicalConcept_10(
        concept_id="CONCEPT_10_002",
        loinc_num="20002-2",
        snomed_ct="101000002",
        component="Diagnostic Analyte Component 10-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_003": ClinicalConcept_10(
        concept_id="CONCEPT_10_003",
        loinc_num="20003-3",
        snomed_ct="101000003",
        component="Diagnostic Analyte Component 10-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_004": ClinicalConcept_10(
        concept_id="CONCEPT_10_004",
        loinc_num="20004-4",
        snomed_ct="101000004",
        component="Diagnostic Analyte Component 10-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_005": ClinicalConcept_10(
        concept_id="CONCEPT_10_005",
        loinc_num="20005-5",
        snomed_ct="101000005",
        component="Diagnostic Analyte Component 10-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_006": ClinicalConcept_10(
        concept_id="CONCEPT_10_006",
        loinc_num="20006-6",
        snomed_ct="101000006",
        component="Diagnostic Analyte Component 10-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_007": ClinicalConcept_10(
        concept_id="CONCEPT_10_007",
        loinc_num="20007-7",
        snomed_ct="101000007",
        component="Diagnostic Analyte Component 10-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_008": ClinicalConcept_10(
        concept_id="CONCEPT_10_008",
        loinc_num="20008-8",
        snomed_ct="101000008",
        component="Diagnostic Analyte Component 10-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_009": ClinicalConcept_10(
        concept_id="CONCEPT_10_009",
        loinc_num="20009-0",
        snomed_ct="101000009",
        component="Diagnostic Analyte Component 10-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_010": ClinicalConcept_10(
        concept_id="CONCEPT_10_010",
        loinc_num="20010-1",
        snomed_ct="101000010",
        component="Diagnostic Analyte Component 10-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_011": ClinicalConcept_10(
        concept_id="CONCEPT_10_011",
        loinc_num="20011-2",
        snomed_ct="101000011",
        component="Diagnostic Analyte Component 10-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_012": ClinicalConcept_10(
        concept_id="CONCEPT_10_012",
        loinc_num="20012-3",
        snomed_ct="101000012",
        component="Diagnostic Analyte Component 10-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_013": ClinicalConcept_10(
        concept_id="CONCEPT_10_013",
        loinc_num="20013-4",
        snomed_ct="101000013",
        component="Diagnostic Analyte Component 10-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_014": ClinicalConcept_10(
        concept_id="CONCEPT_10_014",
        loinc_num="20014-5",
        snomed_ct="101000014",
        component="Diagnostic Analyte Component 10-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_015": ClinicalConcept_10(
        concept_id="CONCEPT_10_015",
        loinc_num="20015-6",
        snomed_ct="101000015",
        component="Diagnostic Analyte Component 10-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_016": ClinicalConcept_10(
        concept_id="CONCEPT_10_016",
        loinc_num="20016-7",
        snomed_ct="101000016",
        component="Diagnostic Analyte Component 10-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_017": ClinicalConcept_10(
        concept_id="CONCEPT_10_017",
        loinc_num="20017-8",
        snomed_ct="101000017",
        component="Diagnostic Analyte Component 10-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_018": ClinicalConcept_10(
        concept_id="CONCEPT_10_018",
        loinc_num="20018-0",
        snomed_ct="101000018",
        component="Diagnostic Analyte Component 10-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_019": ClinicalConcept_10(
        concept_id="CONCEPT_10_019",
        loinc_num="20019-1",
        snomed_ct="101000019",
        component="Diagnostic Analyte Component 10-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_020": ClinicalConcept_10(
        concept_id="CONCEPT_10_020",
        loinc_num="20020-2",
        snomed_ct="101000020",
        component="Diagnostic Analyte Component 10-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_021": ClinicalConcept_10(
        concept_id="CONCEPT_10_021",
        loinc_num="20021-3",
        snomed_ct="101000021",
        component="Diagnostic Analyte Component 10-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_022": ClinicalConcept_10(
        concept_id="CONCEPT_10_022",
        loinc_num="20022-4",
        snomed_ct="101000022",
        component="Diagnostic Analyte Component 10-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_023": ClinicalConcept_10(
        concept_id="CONCEPT_10_023",
        loinc_num="20023-5",
        snomed_ct="101000023",
        component="Diagnostic Analyte Component 10-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_024": ClinicalConcept_10(
        concept_id="CONCEPT_10_024",
        loinc_num="20024-6",
        snomed_ct="101000024",
        component="Diagnostic Analyte Component 10-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_025": ClinicalConcept_10(
        concept_id="CONCEPT_10_025",
        loinc_num="20025-7",
        snomed_ct="101000025",
        component="Diagnostic Analyte Component 10-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_026": ClinicalConcept_10(
        concept_id="CONCEPT_10_026",
        loinc_num="20026-8",
        snomed_ct="101000026",
        component="Diagnostic Analyte Component 10-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_027": ClinicalConcept_10(
        concept_id="CONCEPT_10_027",
        loinc_num="20027-0",
        snomed_ct="101000027",
        component="Diagnostic Analyte Component 10-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_028": ClinicalConcept_10(
        concept_id="CONCEPT_10_028",
        loinc_num="20028-1",
        snomed_ct="101000028",
        component="Diagnostic Analyte Component 10-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_029": ClinicalConcept_10(
        concept_id="CONCEPT_10_029",
        loinc_num="20029-2",
        snomed_ct="101000029",
        component="Diagnostic Analyte Component 10-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_030": ClinicalConcept_10(
        concept_id="CONCEPT_10_030",
        loinc_num="20030-3",
        snomed_ct="101000030",
        component="Diagnostic Analyte Component 10-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_031": ClinicalConcept_10(
        concept_id="CONCEPT_10_031",
        loinc_num="20031-4",
        snomed_ct="101000031",
        component="Diagnostic Analyte Component 10-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_032": ClinicalConcept_10(
        concept_id="CONCEPT_10_032",
        loinc_num="20032-5",
        snomed_ct="101000032",
        component="Diagnostic Analyte Component 10-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_033": ClinicalConcept_10(
        concept_id="CONCEPT_10_033",
        loinc_num="20033-6",
        snomed_ct="101000033",
        component="Diagnostic Analyte Component 10-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_034": ClinicalConcept_10(
        concept_id="CONCEPT_10_034",
        loinc_num="20034-7",
        snomed_ct="101000034",
        component="Diagnostic Analyte Component 10-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_035": ClinicalConcept_10(
        concept_id="CONCEPT_10_035",
        loinc_num="20035-8",
        snomed_ct="101000035",
        component="Diagnostic Analyte Component 10-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_036": ClinicalConcept_10(
        concept_id="CONCEPT_10_036",
        loinc_num="20036-0",
        snomed_ct="101000036",
        component="Diagnostic Analyte Component 10-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_037": ClinicalConcept_10(
        concept_id="CONCEPT_10_037",
        loinc_num="20037-1",
        snomed_ct="101000037",
        component="Diagnostic Analyte Component 10-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_038": ClinicalConcept_10(
        concept_id="CONCEPT_10_038",
        loinc_num="20038-2",
        snomed_ct="101000038",
        component="Diagnostic Analyte Component 10-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_039": ClinicalConcept_10(
        concept_id="CONCEPT_10_039",
        loinc_num="20039-3",
        snomed_ct="101000039",
        component="Diagnostic Analyte Component 10-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_040": ClinicalConcept_10(
        concept_id="CONCEPT_10_040",
        loinc_num="20040-4",
        snomed_ct="101000040",
        component="Diagnostic Analyte Component 10-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_041": ClinicalConcept_10(
        concept_id="CONCEPT_10_041",
        loinc_num="20041-5",
        snomed_ct="101000041",
        component="Diagnostic Analyte Component 10-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_042": ClinicalConcept_10(
        concept_id="CONCEPT_10_042",
        loinc_num="20042-6",
        snomed_ct="101000042",
        component="Diagnostic Analyte Component 10-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_043": ClinicalConcept_10(
        concept_id="CONCEPT_10_043",
        loinc_num="20043-7",
        snomed_ct="101000043",
        component="Diagnostic Analyte Component 10-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_044": ClinicalConcept_10(
        concept_id="CONCEPT_10_044",
        loinc_num="20044-8",
        snomed_ct="101000044",
        component="Diagnostic Analyte Component 10-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_045": ClinicalConcept_10(
        concept_id="CONCEPT_10_045",
        loinc_num="20045-0",
        snomed_ct="101000045",
        component="Diagnostic Analyte Component 10-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_046": ClinicalConcept_10(
        concept_id="CONCEPT_10_046",
        loinc_num="20046-1",
        snomed_ct="101000046",
        component="Diagnostic Analyte Component 10-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_047": ClinicalConcept_10(
        concept_id="CONCEPT_10_047",
        loinc_num="20047-2",
        snomed_ct="101000047",
        component="Diagnostic Analyte Component 10-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_048": ClinicalConcept_10(
        concept_id="CONCEPT_10_048",
        loinc_num="20048-3",
        snomed_ct="101000048",
        component="Diagnostic Analyte Component 10-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_049": ClinicalConcept_10(
        concept_id="CONCEPT_10_049",
        loinc_num="20049-4",
        snomed_ct="101000049",
        component="Diagnostic Analyte Component 10-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_050": ClinicalConcept_10(
        concept_id="CONCEPT_10_050",
        loinc_num="20050-5",
        snomed_ct="101000050",
        component="Diagnostic Analyte Component 10-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_051": ClinicalConcept_10(
        concept_id="CONCEPT_10_051",
        loinc_num="20051-6",
        snomed_ct="101000051",
        component="Diagnostic Analyte Component 10-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_052": ClinicalConcept_10(
        concept_id="CONCEPT_10_052",
        loinc_num="20052-7",
        snomed_ct="101000052",
        component="Diagnostic Analyte Component 10-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_053": ClinicalConcept_10(
        concept_id="CONCEPT_10_053",
        loinc_num="20053-8",
        snomed_ct="101000053",
        component="Diagnostic Analyte Component 10-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_054": ClinicalConcept_10(
        concept_id="CONCEPT_10_054",
        loinc_num="20054-0",
        snomed_ct="101000054",
        component="Diagnostic Analyte Component 10-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_055": ClinicalConcept_10(
        concept_id="CONCEPT_10_055",
        loinc_num="20055-1",
        snomed_ct="101000055",
        component="Diagnostic Analyte Component 10-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_056": ClinicalConcept_10(
        concept_id="CONCEPT_10_056",
        loinc_num="20056-2",
        snomed_ct="101000056",
        component="Diagnostic Analyte Component 10-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_057": ClinicalConcept_10(
        concept_id="CONCEPT_10_057",
        loinc_num="20057-3",
        snomed_ct="101000057",
        component="Diagnostic Analyte Component 10-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_058": ClinicalConcept_10(
        concept_id="CONCEPT_10_058",
        loinc_num="20058-4",
        snomed_ct="101000058",
        component="Diagnostic Analyte Component 10-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_059": ClinicalConcept_10(
        concept_id="CONCEPT_10_059",
        loinc_num="20059-5",
        snomed_ct="101000059",
        component="Diagnostic Analyte Component 10-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_060": ClinicalConcept_10(
        concept_id="CONCEPT_10_060",
        loinc_num="20060-6",
        snomed_ct="101000060",
        component="Diagnostic Analyte Component 10-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_061": ClinicalConcept_10(
        concept_id="CONCEPT_10_061",
        loinc_num="20061-7",
        snomed_ct="101000061",
        component="Diagnostic Analyte Component 10-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_062": ClinicalConcept_10(
        concept_id="CONCEPT_10_062",
        loinc_num="20062-8",
        snomed_ct="101000062",
        component="Diagnostic Analyte Component 10-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_063": ClinicalConcept_10(
        concept_id="CONCEPT_10_063",
        loinc_num="20063-0",
        snomed_ct="101000063",
        component="Diagnostic Analyte Component 10-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_064": ClinicalConcept_10(
        concept_id="CONCEPT_10_064",
        loinc_num="20064-1",
        snomed_ct="101000064",
        component="Diagnostic Analyte Component 10-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_065": ClinicalConcept_10(
        concept_id="CONCEPT_10_065",
        loinc_num="20065-2",
        snomed_ct="101000065",
        component="Diagnostic Analyte Component 10-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_066": ClinicalConcept_10(
        concept_id="CONCEPT_10_066",
        loinc_num="20066-3",
        snomed_ct="101000066",
        component="Diagnostic Analyte Component 10-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_067": ClinicalConcept_10(
        concept_id="CONCEPT_10_067",
        loinc_num="20067-4",
        snomed_ct="101000067",
        component="Diagnostic Analyte Component 10-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_068": ClinicalConcept_10(
        concept_id="CONCEPT_10_068",
        loinc_num="20068-5",
        snomed_ct="101000068",
        component="Diagnostic Analyte Component 10-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_069": ClinicalConcept_10(
        concept_id="CONCEPT_10_069",
        loinc_num="20069-6",
        snomed_ct="101000069",
        component="Diagnostic Analyte Component 10-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_070": ClinicalConcept_10(
        concept_id="CONCEPT_10_070",
        loinc_num="20070-7",
        snomed_ct="101000070",
        component="Diagnostic Analyte Component 10-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_071": ClinicalConcept_10(
        concept_id="CONCEPT_10_071",
        loinc_num="20071-8",
        snomed_ct="101000071",
        component="Diagnostic Analyte Component 10-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_072": ClinicalConcept_10(
        concept_id="CONCEPT_10_072",
        loinc_num="20072-0",
        snomed_ct="101000072",
        component="Diagnostic Analyte Component 10-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_073": ClinicalConcept_10(
        concept_id="CONCEPT_10_073",
        loinc_num="20073-1",
        snomed_ct="101000073",
        component="Diagnostic Analyte Component 10-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_074": ClinicalConcept_10(
        concept_id="CONCEPT_10_074",
        loinc_num="20074-2",
        snomed_ct="101000074",
        component="Diagnostic Analyte Component 10-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_075": ClinicalConcept_10(
        concept_id="CONCEPT_10_075",
        loinc_num="20075-3",
        snomed_ct="101000075",
        component="Diagnostic Analyte Component 10-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_076": ClinicalConcept_10(
        concept_id="CONCEPT_10_076",
        loinc_num="20076-4",
        snomed_ct="101000076",
        component="Diagnostic Analyte Component 10-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_077": ClinicalConcept_10(
        concept_id="CONCEPT_10_077",
        loinc_num="20077-5",
        snomed_ct="101000077",
        component="Diagnostic Analyte Component 10-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_078": ClinicalConcept_10(
        concept_id="CONCEPT_10_078",
        loinc_num="20078-6",
        snomed_ct="101000078",
        component="Diagnostic Analyte Component 10-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_079": ClinicalConcept_10(
        concept_id="CONCEPT_10_079",
        loinc_num="20079-7",
        snomed_ct="101000079",
        component="Diagnostic Analyte Component 10-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_080": ClinicalConcept_10(
        concept_id="CONCEPT_10_080",
        loinc_num="20080-8",
        snomed_ct="101000080",
        component="Diagnostic Analyte Component 10-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_081": ClinicalConcept_10(
        concept_id="CONCEPT_10_081",
        loinc_num="20081-0",
        snomed_ct="101000081",
        component="Diagnostic Analyte Component 10-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_082": ClinicalConcept_10(
        concept_id="CONCEPT_10_082",
        loinc_num="20082-1",
        snomed_ct="101000082",
        component="Diagnostic Analyte Component 10-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_083": ClinicalConcept_10(
        concept_id="CONCEPT_10_083",
        loinc_num="20083-2",
        snomed_ct="101000083",
        component="Diagnostic Analyte Component 10-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_084": ClinicalConcept_10(
        concept_id="CONCEPT_10_084",
        loinc_num="20084-3",
        snomed_ct="101000084",
        component="Diagnostic Analyte Component 10-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_085": ClinicalConcept_10(
        concept_id="CONCEPT_10_085",
        loinc_num="20085-4",
        snomed_ct="101000085",
        component="Diagnostic Analyte Component 10-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_086": ClinicalConcept_10(
        concept_id="CONCEPT_10_086",
        loinc_num="20086-5",
        snomed_ct="101000086",
        component="Diagnostic Analyte Component 10-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_087": ClinicalConcept_10(
        concept_id="CONCEPT_10_087",
        loinc_num="20087-6",
        snomed_ct="101000087",
        component="Diagnostic Analyte Component 10-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_088": ClinicalConcept_10(
        concept_id="CONCEPT_10_088",
        loinc_num="20088-7",
        snomed_ct="101000088",
        component="Diagnostic Analyte Component 10-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_089": ClinicalConcept_10(
        concept_id="CONCEPT_10_089",
        loinc_num="20089-8",
        snomed_ct="101000089",
        component="Diagnostic Analyte Component 10-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_090": ClinicalConcept_10(
        concept_id="CONCEPT_10_090",
        loinc_num="20090-0",
        snomed_ct="101000090",
        component="Diagnostic Analyte Component 10-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_091": ClinicalConcept_10(
        concept_id="CONCEPT_10_091",
        loinc_num="20091-1",
        snomed_ct="101000091",
        component="Diagnostic Analyte Component 10-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_092": ClinicalConcept_10(
        concept_id="CONCEPT_10_092",
        loinc_num="20092-2",
        snomed_ct="101000092",
        component="Diagnostic Analyte Component 10-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_093": ClinicalConcept_10(
        concept_id="CONCEPT_10_093",
        loinc_num="20093-3",
        snomed_ct="101000093",
        component="Diagnostic Analyte Component 10-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_094": ClinicalConcept_10(
        concept_id="CONCEPT_10_094",
        loinc_num="20094-4",
        snomed_ct="101000094",
        component="Diagnostic Analyte Component 10-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_095": ClinicalConcept_10(
        concept_id="CONCEPT_10_095",
        loinc_num="20095-5",
        snomed_ct="101000095",
        component="Diagnostic Analyte Component 10-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_096": ClinicalConcept_10(
        concept_id="CONCEPT_10_096",
        loinc_num="20096-6",
        snomed_ct="101000096",
        component="Diagnostic Analyte Component 10-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_097": ClinicalConcept_10(
        concept_id="CONCEPT_10_097",
        loinc_num="20097-7",
        snomed_ct="101000097",
        component="Diagnostic Analyte Component 10-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_098": ClinicalConcept_10(
        concept_id="CONCEPT_10_098",
        loinc_num="20098-8",
        snomed_ct="101000098",
        component="Diagnostic Analyte Component 10-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_099": ClinicalConcept_10(
        concept_id="CONCEPT_10_099",
        loinc_num="20099-0",
        snomed_ct="101000099",
        component="Diagnostic Analyte Component 10-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_100": ClinicalConcept_10(
        concept_id="CONCEPT_10_100",
        loinc_num="20100-1",
        snomed_ct="101000100",
        component="Diagnostic Analyte Component 10-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_101": ClinicalConcept_10(
        concept_id="CONCEPT_10_101",
        loinc_num="20101-2",
        snomed_ct="101000101",
        component="Diagnostic Analyte Component 10-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_102": ClinicalConcept_10(
        concept_id="CONCEPT_10_102",
        loinc_num="20102-3",
        snomed_ct="101000102",
        component="Diagnostic Analyte Component 10-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_103": ClinicalConcept_10(
        concept_id="CONCEPT_10_103",
        loinc_num="20103-4",
        snomed_ct="101000103",
        component="Diagnostic Analyte Component 10-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_104": ClinicalConcept_10(
        concept_id="CONCEPT_10_104",
        loinc_num="20104-5",
        snomed_ct="101000104",
        component="Diagnostic Analyte Component 10-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_105": ClinicalConcept_10(
        concept_id="CONCEPT_10_105",
        loinc_num="20105-6",
        snomed_ct="101000105",
        component="Diagnostic Analyte Component 10-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_106": ClinicalConcept_10(
        concept_id="CONCEPT_10_106",
        loinc_num="20106-7",
        snomed_ct="101000106",
        component="Diagnostic Analyte Component 10-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_107": ClinicalConcept_10(
        concept_id="CONCEPT_10_107",
        loinc_num="20107-8",
        snomed_ct="101000107",
        component="Diagnostic Analyte Component 10-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_108": ClinicalConcept_10(
        concept_id="CONCEPT_10_108",
        loinc_num="20108-0",
        snomed_ct="101000108",
        component="Diagnostic Analyte Component 10-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_109": ClinicalConcept_10(
        concept_id="CONCEPT_10_109",
        loinc_num="20109-1",
        snomed_ct="101000109",
        component="Diagnostic Analyte Component 10-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_110": ClinicalConcept_10(
        concept_id="CONCEPT_10_110",
        loinc_num="20110-2",
        snomed_ct="101000110",
        component="Diagnostic Analyte Component 10-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_111": ClinicalConcept_10(
        concept_id="CONCEPT_10_111",
        loinc_num="20111-3",
        snomed_ct="101000111",
        component="Diagnostic Analyte Component 10-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_112": ClinicalConcept_10(
        concept_id="CONCEPT_10_112",
        loinc_num="20112-4",
        snomed_ct="101000112",
        component="Diagnostic Analyte Component 10-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_113": ClinicalConcept_10(
        concept_id="CONCEPT_10_113",
        loinc_num="20113-5",
        snomed_ct="101000113",
        component="Diagnostic Analyte Component 10-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_114": ClinicalConcept_10(
        concept_id="CONCEPT_10_114",
        loinc_num="20114-6",
        snomed_ct="101000114",
        component="Diagnostic Analyte Component 10-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_115": ClinicalConcept_10(
        concept_id="CONCEPT_10_115",
        loinc_num="20115-7",
        snomed_ct="101000115",
        component="Diagnostic Analyte Component 10-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_116": ClinicalConcept_10(
        concept_id="CONCEPT_10_116",
        loinc_num="20116-8",
        snomed_ct="101000116",
        component="Diagnostic Analyte Component 10-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_117": ClinicalConcept_10(
        concept_id="CONCEPT_10_117",
        loinc_num="20117-0",
        snomed_ct="101000117",
        component="Diagnostic Analyte Component 10-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_118": ClinicalConcept_10(
        concept_id="CONCEPT_10_118",
        loinc_num="20118-1",
        snomed_ct="101000118",
        component="Diagnostic Analyte Component 10-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_119": ClinicalConcept_10(
        concept_id="CONCEPT_10_119",
        loinc_num="20119-2",
        snomed_ct="101000119",
        component="Diagnostic Analyte Component 10-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_120": ClinicalConcept_10(
        concept_id="CONCEPT_10_120",
        loinc_num="20120-3",
        snomed_ct="101000120",
        component="Diagnostic Analyte Component 10-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_121": ClinicalConcept_10(
        concept_id="CONCEPT_10_121",
        loinc_num="20121-4",
        snomed_ct="101000121",
        component="Diagnostic Analyte Component 10-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_122": ClinicalConcept_10(
        concept_id="CONCEPT_10_122",
        loinc_num="20122-5",
        snomed_ct="101000122",
        component="Diagnostic Analyte Component 10-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_123": ClinicalConcept_10(
        concept_id="CONCEPT_10_123",
        loinc_num="20123-6",
        snomed_ct="101000123",
        component="Diagnostic Analyte Component 10-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_124": ClinicalConcept_10(
        concept_id="CONCEPT_10_124",
        loinc_num="20124-7",
        snomed_ct="101000124",
        component="Diagnostic Analyte Component 10-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_125": ClinicalConcept_10(
        concept_id="CONCEPT_10_125",
        loinc_num="20125-8",
        snomed_ct="101000125",
        component="Diagnostic Analyte Component 10-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_126": ClinicalConcept_10(
        concept_id="CONCEPT_10_126",
        loinc_num="20126-0",
        snomed_ct="101000126",
        component="Diagnostic Analyte Component 10-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_127": ClinicalConcept_10(
        concept_id="CONCEPT_10_127",
        loinc_num="20127-1",
        snomed_ct="101000127",
        component="Diagnostic Analyte Component 10-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_128": ClinicalConcept_10(
        concept_id="CONCEPT_10_128",
        loinc_num="20128-2",
        snomed_ct="101000128",
        component="Diagnostic Analyte Component 10-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_129": ClinicalConcept_10(
        concept_id="CONCEPT_10_129",
        loinc_num="20129-3",
        snomed_ct="101000129",
        component="Diagnostic Analyte Component 10-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_130": ClinicalConcept_10(
        concept_id="CONCEPT_10_130",
        loinc_num="20130-4",
        snomed_ct="101000130",
        component="Diagnostic Analyte Component 10-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_131": ClinicalConcept_10(
        concept_id="CONCEPT_10_131",
        loinc_num="20131-5",
        snomed_ct="101000131",
        component="Diagnostic Analyte Component 10-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_132": ClinicalConcept_10(
        concept_id="CONCEPT_10_132",
        loinc_num="20132-6",
        snomed_ct="101000132",
        component="Diagnostic Analyte Component 10-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_133": ClinicalConcept_10(
        concept_id="CONCEPT_10_133",
        loinc_num="20133-7",
        snomed_ct="101000133",
        component="Diagnostic Analyte Component 10-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_134": ClinicalConcept_10(
        concept_id="CONCEPT_10_134",
        loinc_num="20134-8",
        snomed_ct="101000134",
        component="Diagnostic Analyte Component 10-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_135": ClinicalConcept_10(
        concept_id="CONCEPT_10_135",
        loinc_num="20135-0",
        snomed_ct="101000135",
        component="Diagnostic Analyte Component 10-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_136": ClinicalConcept_10(
        concept_id="CONCEPT_10_136",
        loinc_num="20136-1",
        snomed_ct="101000136",
        component="Diagnostic Analyte Component 10-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_137": ClinicalConcept_10(
        concept_id="CONCEPT_10_137",
        loinc_num="20137-2",
        snomed_ct="101000137",
        component="Diagnostic Analyte Component 10-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_138": ClinicalConcept_10(
        concept_id="CONCEPT_10_138",
        loinc_num="20138-3",
        snomed_ct="101000138",
        component="Diagnostic Analyte Component 10-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_139": ClinicalConcept_10(
        concept_id="CONCEPT_10_139",
        loinc_num="20139-4",
        snomed_ct="101000139",
        component="Diagnostic Analyte Component 10-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_140": ClinicalConcept_10(
        concept_id="CONCEPT_10_140",
        loinc_num="20140-5",
        snomed_ct="101000140",
        component="Diagnostic Analyte Component 10-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_141": ClinicalConcept_10(
        concept_id="CONCEPT_10_141",
        loinc_num="20141-6",
        snomed_ct="101000141",
        component="Diagnostic Analyte Component 10-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_142": ClinicalConcept_10(
        concept_id="CONCEPT_10_142",
        loinc_num="20142-7",
        snomed_ct="101000142",
        component="Diagnostic Analyte Component 10-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_143": ClinicalConcept_10(
        concept_id="CONCEPT_10_143",
        loinc_num="20143-8",
        snomed_ct="101000143",
        component="Diagnostic Analyte Component 10-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_144": ClinicalConcept_10(
        concept_id="CONCEPT_10_144",
        loinc_num="20144-0",
        snomed_ct="101000144",
        component="Diagnostic Analyte Component 10-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_145": ClinicalConcept_10(
        concept_id="CONCEPT_10_145",
        loinc_num="20145-1",
        snomed_ct="101000145",
        component="Diagnostic Analyte Component 10-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_146": ClinicalConcept_10(
        concept_id="CONCEPT_10_146",
        loinc_num="20146-2",
        snomed_ct="101000146",
        component="Diagnostic Analyte Component 10-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_147": ClinicalConcept_10(
        concept_id="CONCEPT_10_147",
        loinc_num="20147-3",
        snomed_ct="101000147",
        component="Diagnostic Analyte Component 10-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_148": ClinicalConcept_10(
        concept_id="CONCEPT_10_148",
        loinc_num="20148-4",
        snomed_ct="101000148",
        component="Diagnostic Analyte Component 10-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_149": ClinicalConcept_10(
        concept_id="CONCEPT_10_149",
        loinc_num="20149-5",
        snomed_ct="101000149",
        component="Diagnostic Analyte Component 10-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_150": ClinicalConcept_10(
        concept_id="CONCEPT_10_150",
        loinc_num="20150-6",
        snomed_ct="101000150",
        component="Diagnostic Analyte Component 10-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_151": ClinicalConcept_10(
        concept_id="CONCEPT_10_151",
        loinc_num="20151-7",
        snomed_ct="101000151",
        component="Diagnostic Analyte Component 10-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_152": ClinicalConcept_10(
        concept_id="CONCEPT_10_152",
        loinc_num="20152-8",
        snomed_ct="101000152",
        component="Diagnostic Analyte Component 10-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_153": ClinicalConcept_10(
        concept_id="CONCEPT_10_153",
        loinc_num="20153-0",
        snomed_ct="101000153",
        component="Diagnostic Analyte Component 10-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_154": ClinicalConcept_10(
        concept_id="CONCEPT_10_154",
        loinc_num="20154-1",
        snomed_ct="101000154",
        component="Diagnostic Analyte Component 10-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_155": ClinicalConcept_10(
        concept_id="CONCEPT_10_155",
        loinc_num="20155-2",
        snomed_ct="101000155",
        component="Diagnostic Analyte Component 10-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_156": ClinicalConcept_10(
        concept_id="CONCEPT_10_156",
        loinc_num="20156-3",
        snomed_ct="101000156",
        component="Diagnostic Analyte Component 10-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_157": ClinicalConcept_10(
        concept_id="CONCEPT_10_157",
        loinc_num="20157-4",
        snomed_ct="101000157",
        component="Diagnostic Analyte Component 10-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_158": ClinicalConcept_10(
        concept_id="CONCEPT_10_158",
        loinc_num="20158-5",
        snomed_ct="101000158",
        component="Diagnostic Analyte Component 10-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_159": ClinicalConcept_10(
        concept_id="CONCEPT_10_159",
        loinc_num="20159-6",
        snomed_ct="101000159",
        component="Diagnostic Analyte Component 10-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_160": ClinicalConcept_10(
        concept_id="CONCEPT_10_160",
        loinc_num="20160-7",
        snomed_ct="101000160",
        component="Diagnostic Analyte Component 10-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_161": ClinicalConcept_10(
        concept_id="CONCEPT_10_161",
        loinc_num="20161-8",
        snomed_ct="101000161",
        component="Diagnostic Analyte Component 10-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_162": ClinicalConcept_10(
        concept_id="CONCEPT_10_162",
        loinc_num="20162-0",
        snomed_ct="101000162",
        component="Diagnostic Analyte Component 10-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_163": ClinicalConcept_10(
        concept_id="CONCEPT_10_163",
        loinc_num="20163-1",
        snomed_ct="101000163",
        component="Diagnostic Analyte Component 10-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_164": ClinicalConcept_10(
        concept_id="CONCEPT_10_164",
        loinc_num="20164-2",
        snomed_ct="101000164",
        component="Diagnostic Analyte Component 10-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_165": ClinicalConcept_10(
        concept_id="CONCEPT_10_165",
        loinc_num="20165-3",
        snomed_ct="101000165",
        component="Diagnostic Analyte Component 10-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_166": ClinicalConcept_10(
        concept_id="CONCEPT_10_166",
        loinc_num="20166-4",
        snomed_ct="101000166",
        component="Diagnostic Analyte Component 10-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_167": ClinicalConcept_10(
        concept_id="CONCEPT_10_167",
        loinc_num="20167-5",
        snomed_ct="101000167",
        component="Diagnostic Analyte Component 10-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_168": ClinicalConcept_10(
        concept_id="CONCEPT_10_168",
        loinc_num="20168-6",
        snomed_ct="101000168",
        component="Diagnostic Analyte Component 10-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_169": ClinicalConcept_10(
        concept_id="CONCEPT_10_169",
        loinc_num="20169-7",
        snomed_ct="101000169",
        component="Diagnostic Analyte Component 10-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_170": ClinicalConcept_10(
        concept_id="CONCEPT_10_170",
        loinc_num="20170-8",
        snomed_ct="101000170",
        component="Diagnostic Analyte Component 10-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_171": ClinicalConcept_10(
        concept_id="CONCEPT_10_171",
        loinc_num="20171-0",
        snomed_ct="101000171",
        component="Diagnostic Analyte Component 10-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_172": ClinicalConcept_10(
        concept_id="CONCEPT_10_172",
        loinc_num="20172-1",
        snomed_ct="101000172",
        component="Diagnostic Analyte Component 10-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_173": ClinicalConcept_10(
        concept_id="CONCEPT_10_173",
        loinc_num="20173-2",
        snomed_ct="101000173",
        component="Diagnostic Analyte Component 10-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_174": ClinicalConcept_10(
        concept_id="CONCEPT_10_174",
        loinc_num="20174-3",
        snomed_ct="101000174",
        component="Diagnostic Analyte Component 10-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_175": ClinicalConcept_10(
        concept_id="CONCEPT_10_175",
        loinc_num="20175-4",
        snomed_ct="101000175",
        component="Diagnostic Analyte Component 10-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_176": ClinicalConcept_10(
        concept_id="CONCEPT_10_176",
        loinc_num="20176-5",
        snomed_ct="101000176",
        component="Diagnostic Analyte Component 10-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_177": ClinicalConcept_10(
        concept_id="CONCEPT_10_177",
        loinc_num="20177-6",
        snomed_ct="101000177",
        component="Diagnostic Analyte Component 10-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_178": ClinicalConcept_10(
        concept_id="CONCEPT_10_178",
        loinc_num="20178-7",
        snomed_ct="101000178",
        component="Diagnostic Analyte Component 10-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_179": ClinicalConcept_10(
        concept_id="CONCEPT_10_179",
        loinc_num="20179-8",
        snomed_ct="101000179",
        component="Diagnostic Analyte Component 10-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_180": ClinicalConcept_10(
        concept_id="CONCEPT_10_180",
        loinc_num="20180-0",
        snomed_ct="101000180",
        component="Diagnostic Analyte Component 10-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_181": ClinicalConcept_10(
        concept_id="CONCEPT_10_181",
        loinc_num="20181-1",
        snomed_ct="101000181",
        component="Diagnostic Analyte Component 10-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_182": ClinicalConcept_10(
        concept_id="CONCEPT_10_182",
        loinc_num="20182-2",
        snomed_ct="101000182",
        component="Diagnostic Analyte Component 10-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_183": ClinicalConcept_10(
        concept_id="CONCEPT_10_183",
        loinc_num="20183-3",
        snomed_ct="101000183",
        component="Diagnostic Analyte Component 10-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_184": ClinicalConcept_10(
        concept_id="CONCEPT_10_184",
        loinc_num="20184-4",
        snomed_ct="101000184",
        component="Diagnostic Analyte Component 10-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_185": ClinicalConcept_10(
        concept_id="CONCEPT_10_185",
        loinc_num="20185-5",
        snomed_ct="101000185",
        component="Diagnostic Analyte Component 10-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_186": ClinicalConcept_10(
        concept_id="CONCEPT_10_186",
        loinc_num="20186-6",
        snomed_ct="101000186",
        component="Diagnostic Analyte Component 10-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_187": ClinicalConcept_10(
        concept_id="CONCEPT_10_187",
        loinc_num="20187-7",
        snomed_ct="101000187",
        component="Diagnostic Analyte Component 10-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_188": ClinicalConcept_10(
        concept_id="CONCEPT_10_188",
        loinc_num="20188-8",
        snomed_ct="101000188",
        component="Diagnostic Analyte Component 10-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_189": ClinicalConcept_10(
        concept_id="CONCEPT_10_189",
        loinc_num="20189-0",
        snomed_ct="101000189",
        component="Diagnostic Analyte Component 10-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_190": ClinicalConcept_10(
        concept_id="CONCEPT_10_190",
        loinc_num="20190-1",
        snomed_ct="101000190",
        component="Diagnostic Analyte Component 10-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_191": ClinicalConcept_10(
        concept_id="CONCEPT_10_191",
        loinc_num="20191-2",
        snomed_ct="101000191",
        component="Diagnostic Analyte Component 10-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_192": ClinicalConcept_10(
        concept_id="CONCEPT_10_192",
        loinc_num="20192-3",
        snomed_ct="101000192",
        component="Diagnostic Analyte Component 10-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_193": ClinicalConcept_10(
        concept_id="CONCEPT_10_193",
        loinc_num="20193-4",
        snomed_ct="101000193",
        component="Diagnostic Analyte Component 10-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_194": ClinicalConcept_10(
        concept_id="CONCEPT_10_194",
        loinc_num="20194-5",
        snomed_ct="101000194",
        component="Diagnostic Analyte Component 10-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_195": ClinicalConcept_10(
        concept_id="CONCEPT_10_195",
        loinc_num="20195-6",
        snomed_ct="101000195",
        component="Diagnostic Analyte Component 10-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_196": ClinicalConcept_10(
        concept_id="CONCEPT_10_196",
        loinc_num="20196-7",
        snomed_ct="101000196",
        component="Diagnostic Analyte Component 10-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_197": ClinicalConcept_10(
        concept_id="CONCEPT_10_197",
        loinc_num="20197-8",
        snomed_ct="101000197",
        component="Diagnostic Analyte Component 10-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_198": ClinicalConcept_10(
        concept_id="CONCEPT_10_198",
        loinc_num="20198-0",
        snomed_ct="101000198",
        component="Diagnostic Analyte Component 10-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_10_199": ClinicalConcept_10(
        concept_id="CONCEPT_10_199",
        loinc_num="20199-1",
        snomed_ct="101000199",
        component="Diagnostic Analyte Component 10-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
