"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 12"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_12:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_12 = {
    "CONCEPT_12_001": ClinicalConcept_12(
        concept_id="CONCEPT_12_001",
        loinc_num="22001-1",
        snomed_ct="101200001",
        component="Diagnostic Analyte Component 12-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_002": ClinicalConcept_12(
        concept_id="CONCEPT_12_002",
        loinc_num="22002-2",
        snomed_ct="101200002",
        component="Diagnostic Analyte Component 12-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_003": ClinicalConcept_12(
        concept_id="CONCEPT_12_003",
        loinc_num="22003-3",
        snomed_ct="101200003",
        component="Diagnostic Analyte Component 12-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_004": ClinicalConcept_12(
        concept_id="CONCEPT_12_004",
        loinc_num="22004-4",
        snomed_ct="101200004",
        component="Diagnostic Analyte Component 12-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_005": ClinicalConcept_12(
        concept_id="CONCEPT_12_005",
        loinc_num="22005-5",
        snomed_ct="101200005",
        component="Diagnostic Analyte Component 12-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_006": ClinicalConcept_12(
        concept_id="CONCEPT_12_006",
        loinc_num="22006-6",
        snomed_ct="101200006",
        component="Diagnostic Analyte Component 12-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_007": ClinicalConcept_12(
        concept_id="CONCEPT_12_007",
        loinc_num="22007-7",
        snomed_ct="101200007",
        component="Diagnostic Analyte Component 12-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_008": ClinicalConcept_12(
        concept_id="CONCEPT_12_008",
        loinc_num="22008-8",
        snomed_ct="101200008",
        component="Diagnostic Analyte Component 12-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_009": ClinicalConcept_12(
        concept_id="CONCEPT_12_009",
        loinc_num="22009-0",
        snomed_ct="101200009",
        component="Diagnostic Analyte Component 12-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_010": ClinicalConcept_12(
        concept_id="CONCEPT_12_010",
        loinc_num="22010-1",
        snomed_ct="101200010",
        component="Diagnostic Analyte Component 12-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_011": ClinicalConcept_12(
        concept_id="CONCEPT_12_011",
        loinc_num="22011-2",
        snomed_ct="101200011",
        component="Diagnostic Analyte Component 12-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_012": ClinicalConcept_12(
        concept_id="CONCEPT_12_012",
        loinc_num="22012-3",
        snomed_ct="101200012",
        component="Diagnostic Analyte Component 12-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_013": ClinicalConcept_12(
        concept_id="CONCEPT_12_013",
        loinc_num="22013-4",
        snomed_ct="101200013",
        component="Diagnostic Analyte Component 12-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_014": ClinicalConcept_12(
        concept_id="CONCEPT_12_014",
        loinc_num="22014-5",
        snomed_ct="101200014",
        component="Diagnostic Analyte Component 12-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_015": ClinicalConcept_12(
        concept_id="CONCEPT_12_015",
        loinc_num="22015-6",
        snomed_ct="101200015",
        component="Diagnostic Analyte Component 12-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_016": ClinicalConcept_12(
        concept_id="CONCEPT_12_016",
        loinc_num="22016-7",
        snomed_ct="101200016",
        component="Diagnostic Analyte Component 12-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_017": ClinicalConcept_12(
        concept_id="CONCEPT_12_017",
        loinc_num="22017-8",
        snomed_ct="101200017",
        component="Diagnostic Analyte Component 12-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_018": ClinicalConcept_12(
        concept_id="CONCEPT_12_018",
        loinc_num="22018-0",
        snomed_ct="101200018",
        component="Diagnostic Analyte Component 12-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_019": ClinicalConcept_12(
        concept_id="CONCEPT_12_019",
        loinc_num="22019-1",
        snomed_ct="101200019",
        component="Diagnostic Analyte Component 12-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_020": ClinicalConcept_12(
        concept_id="CONCEPT_12_020",
        loinc_num="22020-2",
        snomed_ct="101200020",
        component="Diagnostic Analyte Component 12-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_021": ClinicalConcept_12(
        concept_id="CONCEPT_12_021",
        loinc_num="22021-3",
        snomed_ct="101200021",
        component="Diagnostic Analyte Component 12-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_022": ClinicalConcept_12(
        concept_id="CONCEPT_12_022",
        loinc_num="22022-4",
        snomed_ct="101200022",
        component="Diagnostic Analyte Component 12-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_023": ClinicalConcept_12(
        concept_id="CONCEPT_12_023",
        loinc_num="22023-5",
        snomed_ct="101200023",
        component="Diagnostic Analyte Component 12-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_024": ClinicalConcept_12(
        concept_id="CONCEPT_12_024",
        loinc_num="22024-6",
        snomed_ct="101200024",
        component="Diagnostic Analyte Component 12-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_025": ClinicalConcept_12(
        concept_id="CONCEPT_12_025",
        loinc_num="22025-7",
        snomed_ct="101200025",
        component="Diagnostic Analyte Component 12-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_026": ClinicalConcept_12(
        concept_id="CONCEPT_12_026",
        loinc_num="22026-8",
        snomed_ct="101200026",
        component="Diagnostic Analyte Component 12-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_027": ClinicalConcept_12(
        concept_id="CONCEPT_12_027",
        loinc_num="22027-0",
        snomed_ct="101200027",
        component="Diagnostic Analyte Component 12-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_028": ClinicalConcept_12(
        concept_id="CONCEPT_12_028",
        loinc_num="22028-1",
        snomed_ct="101200028",
        component="Diagnostic Analyte Component 12-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_029": ClinicalConcept_12(
        concept_id="CONCEPT_12_029",
        loinc_num="22029-2",
        snomed_ct="101200029",
        component="Diagnostic Analyte Component 12-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_030": ClinicalConcept_12(
        concept_id="CONCEPT_12_030",
        loinc_num="22030-3",
        snomed_ct="101200030",
        component="Diagnostic Analyte Component 12-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_031": ClinicalConcept_12(
        concept_id="CONCEPT_12_031",
        loinc_num="22031-4",
        snomed_ct="101200031",
        component="Diagnostic Analyte Component 12-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_032": ClinicalConcept_12(
        concept_id="CONCEPT_12_032",
        loinc_num="22032-5",
        snomed_ct="101200032",
        component="Diagnostic Analyte Component 12-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_033": ClinicalConcept_12(
        concept_id="CONCEPT_12_033",
        loinc_num="22033-6",
        snomed_ct="101200033",
        component="Diagnostic Analyte Component 12-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_034": ClinicalConcept_12(
        concept_id="CONCEPT_12_034",
        loinc_num="22034-7",
        snomed_ct="101200034",
        component="Diagnostic Analyte Component 12-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_035": ClinicalConcept_12(
        concept_id="CONCEPT_12_035",
        loinc_num="22035-8",
        snomed_ct="101200035",
        component="Diagnostic Analyte Component 12-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_036": ClinicalConcept_12(
        concept_id="CONCEPT_12_036",
        loinc_num="22036-0",
        snomed_ct="101200036",
        component="Diagnostic Analyte Component 12-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_037": ClinicalConcept_12(
        concept_id="CONCEPT_12_037",
        loinc_num="22037-1",
        snomed_ct="101200037",
        component="Diagnostic Analyte Component 12-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_038": ClinicalConcept_12(
        concept_id="CONCEPT_12_038",
        loinc_num="22038-2",
        snomed_ct="101200038",
        component="Diagnostic Analyte Component 12-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_039": ClinicalConcept_12(
        concept_id="CONCEPT_12_039",
        loinc_num="22039-3",
        snomed_ct="101200039",
        component="Diagnostic Analyte Component 12-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_040": ClinicalConcept_12(
        concept_id="CONCEPT_12_040",
        loinc_num="22040-4",
        snomed_ct="101200040",
        component="Diagnostic Analyte Component 12-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_041": ClinicalConcept_12(
        concept_id="CONCEPT_12_041",
        loinc_num="22041-5",
        snomed_ct="101200041",
        component="Diagnostic Analyte Component 12-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_042": ClinicalConcept_12(
        concept_id="CONCEPT_12_042",
        loinc_num="22042-6",
        snomed_ct="101200042",
        component="Diagnostic Analyte Component 12-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_043": ClinicalConcept_12(
        concept_id="CONCEPT_12_043",
        loinc_num="22043-7",
        snomed_ct="101200043",
        component="Diagnostic Analyte Component 12-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_044": ClinicalConcept_12(
        concept_id="CONCEPT_12_044",
        loinc_num="22044-8",
        snomed_ct="101200044",
        component="Diagnostic Analyte Component 12-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_045": ClinicalConcept_12(
        concept_id="CONCEPT_12_045",
        loinc_num="22045-0",
        snomed_ct="101200045",
        component="Diagnostic Analyte Component 12-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_046": ClinicalConcept_12(
        concept_id="CONCEPT_12_046",
        loinc_num="22046-1",
        snomed_ct="101200046",
        component="Diagnostic Analyte Component 12-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_047": ClinicalConcept_12(
        concept_id="CONCEPT_12_047",
        loinc_num="22047-2",
        snomed_ct="101200047",
        component="Diagnostic Analyte Component 12-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_048": ClinicalConcept_12(
        concept_id="CONCEPT_12_048",
        loinc_num="22048-3",
        snomed_ct="101200048",
        component="Diagnostic Analyte Component 12-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_049": ClinicalConcept_12(
        concept_id="CONCEPT_12_049",
        loinc_num="22049-4",
        snomed_ct="101200049",
        component="Diagnostic Analyte Component 12-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_050": ClinicalConcept_12(
        concept_id="CONCEPT_12_050",
        loinc_num="22050-5",
        snomed_ct="101200050",
        component="Diagnostic Analyte Component 12-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_051": ClinicalConcept_12(
        concept_id="CONCEPT_12_051",
        loinc_num="22051-6",
        snomed_ct="101200051",
        component="Diagnostic Analyte Component 12-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_052": ClinicalConcept_12(
        concept_id="CONCEPT_12_052",
        loinc_num="22052-7",
        snomed_ct="101200052",
        component="Diagnostic Analyte Component 12-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_053": ClinicalConcept_12(
        concept_id="CONCEPT_12_053",
        loinc_num="22053-8",
        snomed_ct="101200053",
        component="Diagnostic Analyte Component 12-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_054": ClinicalConcept_12(
        concept_id="CONCEPT_12_054",
        loinc_num="22054-0",
        snomed_ct="101200054",
        component="Diagnostic Analyte Component 12-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_055": ClinicalConcept_12(
        concept_id="CONCEPT_12_055",
        loinc_num="22055-1",
        snomed_ct="101200055",
        component="Diagnostic Analyte Component 12-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_056": ClinicalConcept_12(
        concept_id="CONCEPT_12_056",
        loinc_num="22056-2",
        snomed_ct="101200056",
        component="Diagnostic Analyte Component 12-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_057": ClinicalConcept_12(
        concept_id="CONCEPT_12_057",
        loinc_num="22057-3",
        snomed_ct="101200057",
        component="Diagnostic Analyte Component 12-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_058": ClinicalConcept_12(
        concept_id="CONCEPT_12_058",
        loinc_num="22058-4",
        snomed_ct="101200058",
        component="Diagnostic Analyte Component 12-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_059": ClinicalConcept_12(
        concept_id="CONCEPT_12_059",
        loinc_num="22059-5",
        snomed_ct="101200059",
        component="Diagnostic Analyte Component 12-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_060": ClinicalConcept_12(
        concept_id="CONCEPT_12_060",
        loinc_num="22060-6",
        snomed_ct="101200060",
        component="Diagnostic Analyte Component 12-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_061": ClinicalConcept_12(
        concept_id="CONCEPT_12_061",
        loinc_num="22061-7",
        snomed_ct="101200061",
        component="Diagnostic Analyte Component 12-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_062": ClinicalConcept_12(
        concept_id="CONCEPT_12_062",
        loinc_num="22062-8",
        snomed_ct="101200062",
        component="Diagnostic Analyte Component 12-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_063": ClinicalConcept_12(
        concept_id="CONCEPT_12_063",
        loinc_num="22063-0",
        snomed_ct="101200063",
        component="Diagnostic Analyte Component 12-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_064": ClinicalConcept_12(
        concept_id="CONCEPT_12_064",
        loinc_num="22064-1",
        snomed_ct="101200064",
        component="Diagnostic Analyte Component 12-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_065": ClinicalConcept_12(
        concept_id="CONCEPT_12_065",
        loinc_num="22065-2",
        snomed_ct="101200065",
        component="Diagnostic Analyte Component 12-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_066": ClinicalConcept_12(
        concept_id="CONCEPT_12_066",
        loinc_num="22066-3",
        snomed_ct="101200066",
        component="Diagnostic Analyte Component 12-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_067": ClinicalConcept_12(
        concept_id="CONCEPT_12_067",
        loinc_num="22067-4",
        snomed_ct="101200067",
        component="Diagnostic Analyte Component 12-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_068": ClinicalConcept_12(
        concept_id="CONCEPT_12_068",
        loinc_num="22068-5",
        snomed_ct="101200068",
        component="Diagnostic Analyte Component 12-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_069": ClinicalConcept_12(
        concept_id="CONCEPT_12_069",
        loinc_num="22069-6",
        snomed_ct="101200069",
        component="Diagnostic Analyte Component 12-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_070": ClinicalConcept_12(
        concept_id="CONCEPT_12_070",
        loinc_num="22070-7",
        snomed_ct="101200070",
        component="Diagnostic Analyte Component 12-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_071": ClinicalConcept_12(
        concept_id="CONCEPT_12_071",
        loinc_num="22071-8",
        snomed_ct="101200071",
        component="Diagnostic Analyte Component 12-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_072": ClinicalConcept_12(
        concept_id="CONCEPT_12_072",
        loinc_num="22072-0",
        snomed_ct="101200072",
        component="Diagnostic Analyte Component 12-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_073": ClinicalConcept_12(
        concept_id="CONCEPT_12_073",
        loinc_num="22073-1",
        snomed_ct="101200073",
        component="Diagnostic Analyte Component 12-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_074": ClinicalConcept_12(
        concept_id="CONCEPT_12_074",
        loinc_num="22074-2",
        snomed_ct="101200074",
        component="Diagnostic Analyte Component 12-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_075": ClinicalConcept_12(
        concept_id="CONCEPT_12_075",
        loinc_num="22075-3",
        snomed_ct="101200075",
        component="Diagnostic Analyte Component 12-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_076": ClinicalConcept_12(
        concept_id="CONCEPT_12_076",
        loinc_num="22076-4",
        snomed_ct="101200076",
        component="Diagnostic Analyte Component 12-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_077": ClinicalConcept_12(
        concept_id="CONCEPT_12_077",
        loinc_num="22077-5",
        snomed_ct="101200077",
        component="Diagnostic Analyte Component 12-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_078": ClinicalConcept_12(
        concept_id="CONCEPT_12_078",
        loinc_num="22078-6",
        snomed_ct="101200078",
        component="Diagnostic Analyte Component 12-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_079": ClinicalConcept_12(
        concept_id="CONCEPT_12_079",
        loinc_num="22079-7",
        snomed_ct="101200079",
        component="Diagnostic Analyte Component 12-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_080": ClinicalConcept_12(
        concept_id="CONCEPT_12_080",
        loinc_num="22080-8",
        snomed_ct="101200080",
        component="Diagnostic Analyte Component 12-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_081": ClinicalConcept_12(
        concept_id="CONCEPT_12_081",
        loinc_num="22081-0",
        snomed_ct="101200081",
        component="Diagnostic Analyte Component 12-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_082": ClinicalConcept_12(
        concept_id="CONCEPT_12_082",
        loinc_num="22082-1",
        snomed_ct="101200082",
        component="Diagnostic Analyte Component 12-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_083": ClinicalConcept_12(
        concept_id="CONCEPT_12_083",
        loinc_num="22083-2",
        snomed_ct="101200083",
        component="Diagnostic Analyte Component 12-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_084": ClinicalConcept_12(
        concept_id="CONCEPT_12_084",
        loinc_num="22084-3",
        snomed_ct="101200084",
        component="Diagnostic Analyte Component 12-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_085": ClinicalConcept_12(
        concept_id="CONCEPT_12_085",
        loinc_num="22085-4",
        snomed_ct="101200085",
        component="Diagnostic Analyte Component 12-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_086": ClinicalConcept_12(
        concept_id="CONCEPT_12_086",
        loinc_num="22086-5",
        snomed_ct="101200086",
        component="Diagnostic Analyte Component 12-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_087": ClinicalConcept_12(
        concept_id="CONCEPT_12_087",
        loinc_num="22087-6",
        snomed_ct="101200087",
        component="Diagnostic Analyte Component 12-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_088": ClinicalConcept_12(
        concept_id="CONCEPT_12_088",
        loinc_num="22088-7",
        snomed_ct="101200088",
        component="Diagnostic Analyte Component 12-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_089": ClinicalConcept_12(
        concept_id="CONCEPT_12_089",
        loinc_num="22089-8",
        snomed_ct="101200089",
        component="Diagnostic Analyte Component 12-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_090": ClinicalConcept_12(
        concept_id="CONCEPT_12_090",
        loinc_num="22090-0",
        snomed_ct="101200090",
        component="Diagnostic Analyte Component 12-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_091": ClinicalConcept_12(
        concept_id="CONCEPT_12_091",
        loinc_num="22091-1",
        snomed_ct="101200091",
        component="Diagnostic Analyte Component 12-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_092": ClinicalConcept_12(
        concept_id="CONCEPT_12_092",
        loinc_num="22092-2",
        snomed_ct="101200092",
        component="Diagnostic Analyte Component 12-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_093": ClinicalConcept_12(
        concept_id="CONCEPT_12_093",
        loinc_num="22093-3",
        snomed_ct="101200093",
        component="Diagnostic Analyte Component 12-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_094": ClinicalConcept_12(
        concept_id="CONCEPT_12_094",
        loinc_num="22094-4",
        snomed_ct="101200094",
        component="Diagnostic Analyte Component 12-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_095": ClinicalConcept_12(
        concept_id="CONCEPT_12_095",
        loinc_num="22095-5",
        snomed_ct="101200095",
        component="Diagnostic Analyte Component 12-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_096": ClinicalConcept_12(
        concept_id="CONCEPT_12_096",
        loinc_num="22096-6",
        snomed_ct="101200096",
        component="Diagnostic Analyte Component 12-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_097": ClinicalConcept_12(
        concept_id="CONCEPT_12_097",
        loinc_num="22097-7",
        snomed_ct="101200097",
        component="Diagnostic Analyte Component 12-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_098": ClinicalConcept_12(
        concept_id="CONCEPT_12_098",
        loinc_num="22098-8",
        snomed_ct="101200098",
        component="Diagnostic Analyte Component 12-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_099": ClinicalConcept_12(
        concept_id="CONCEPT_12_099",
        loinc_num="22099-0",
        snomed_ct="101200099",
        component="Diagnostic Analyte Component 12-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_100": ClinicalConcept_12(
        concept_id="CONCEPT_12_100",
        loinc_num="22100-1",
        snomed_ct="101200100",
        component="Diagnostic Analyte Component 12-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_101": ClinicalConcept_12(
        concept_id="CONCEPT_12_101",
        loinc_num="22101-2",
        snomed_ct="101200101",
        component="Diagnostic Analyte Component 12-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_102": ClinicalConcept_12(
        concept_id="CONCEPT_12_102",
        loinc_num="22102-3",
        snomed_ct="101200102",
        component="Diagnostic Analyte Component 12-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_103": ClinicalConcept_12(
        concept_id="CONCEPT_12_103",
        loinc_num="22103-4",
        snomed_ct="101200103",
        component="Diagnostic Analyte Component 12-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_104": ClinicalConcept_12(
        concept_id="CONCEPT_12_104",
        loinc_num="22104-5",
        snomed_ct="101200104",
        component="Diagnostic Analyte Component 12-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_105": ClinicalConcept_12(
        concept_id="CONCEPT_12_105",
        loinc_num="22105-6",
        snomed_ct="101200105",
        component="Diagnostic Analyte Component 12-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_106": ClinicalConcept_12(
        concept_id="CONCEPT_12_106",
        loinc_num="22106-7",
        snomed_ct="101200106",
        component="Diagnostic Analyte Component 12-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_107": ClinicalConcept_12(
        concept_id="CONCEPT_12_107",
        loinc_num="22107-8",
        snomed_ct="101200107",
        component="Diagnostic Analyte Component 12-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_108": ClinicalConcept_12(
        concept_id="CONCEPT_12_108",
        loinc_num="22108-0",
        snomed_ct="101200108",
        component="Diagnostic Analyte Component 12-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_109": ClinicalConcept_12(
        concept_id="CONCEPT_12_109",
        loinc_num="22109-1",
        snomed_ct="101200109",
        component="Diagnostic Analyte Component 12-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_110": ClinicalConcept_12(
        concept_id="CONCEPT_12_110",
        loinc_num="22110-2",
        snomed_ct="101200110",
        component="Diagnostic Analyte Component 12-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_111": ClinicalConcept_12(
        concept_id="CONCEPT_12_111",
        loinc_num="22111-3",
        snomed_ct="101200111",
        component="Diagnostic Analyte Component 12-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_112": ClinicalConcept_12(
        concept_id="CONCEPT_12_112",
        loinc_num="22112-4",
        snomed_ct="101200112",
        component="Diagnostic Analyte Component 12-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_113": ClinicalConcept_12(
        concept_id="CONCEPT_12_113",
        loinc_num="22113-5",
        snomed_ct="101200113",
        component="Diagnostic Analyte Component 12-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_114": ClinicalConcept_12(
        concept_id="CONCEPT_12_114",
        loinc_num="22114-6",
        snomed_ct="101200114",
        component="Diagnostic Analyte Component 12-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_115": ClinicalConcept_12(
        concept_id="CONCEPT_12_115",
        loinc_num="22115-7",
        snomed_ct="101200115",
        component="Diagnostic Analyte Component 12-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_116": ClinicalConcept_12(
        concept_id="CONCEPT_12_116",
        loinc_num="22116-8",
        snomed_ct="101200116",
        component="Diagnostic Analyte Component 12-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_117": ClinicalConcept_12(
        concept_id="CONCEPT_12_117",
        loinc_num="22117-0",
        snomed_ct="101200117",
        component="Diagnostic Analyte Component 12-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_118": ClinicalConcept_12(
        concept_id="CONCEPT_12_118",
        loinc_num="22118-1",
        snomed_ct="101200118",
        component="Diagnostic Analyte Component 12-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_119": ClinicalConcept_12(
        concept_id="CONCEPT_12_119",
        loinc_num="22119-2",
        snomed_ct="101200119",
        component="Diagnostic Analyte Component 12-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_120": ClinicalConcept_12(
        concept_id="CONCEPT_12_120",
        loinc_num="22120-3",
        snomed_ct="101200120",
        component="Diagnostic Analyte Component 12-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_121": ClinicalConcept_12(
        concept_id="CONCEPT_12_121",
        loinc_num="22121-4",
        snomed_ct="101200121",
        component="Diagnostic Analyte Component 12-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_122": ClinicalConcept_12(
        concept_id="CONCEPT_12_122",
        loinc_num="22122-5",
        snomed_ct="101200122",
        component="Diagnostic Analyte Component 12-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_123": ClinicalConcept_12(
        concept_id="CONCEPT_12_123",
        loinc_num="22123-6",
        snomed_ct="101200123",
        component="Diagnostic Analyte Component 12-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_124": ClinicalConcept_12(
        concept_id="CONCEPT_12_124",
        loinc_num="22124-7",
        snomed_ct="101200124",
        component="Diagnostic Analyte Component 12-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_125": ClinicalConcept_12(
        concept_id="CONCEPT_12_125",
        loinc_num="22125-8",
        snomed_ct="101200125",
        component="Diagnostic Analyte Component 12-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_126": ClinicalConcept_12(
        concept_id="CONCEPT_12_126",
        loinc_num="22126-0",
        snomed_ct="101200126",
        component="Diagnostic Analyte Component 12-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_127": ClinicalConcept_12(
        concept_id="CONCEPT_12_127",
        loinc_num="22127-1",
        snomed_ct="101200127",
        component="Diagnostic Analyte Component 12-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_128": ClinicalConcept_12(
        concept_id="CONCEPT_12_128",
        loinc_num="22128-2",
        snomed_ct="101200128",
        component="Diagnostic Analyte Component 12-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_129": ClinicalConcept_12(
        concept_id="CONCEPT_12_129",
        loinc_num="22129-3",
        snomed_ct="101200129",
        component="Diagnostic Analyte Component 12-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_130": ClinicalConcept_12(
        concept_id="CONCEPT_12_130",
        loinc_num="22130-4",
        snomed_ct="101200130",
        component="Diagnostic Analyte Component 12-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_131": ClinicalConcept_12(
        concept_id="CONCEPT_12_131",
        loinc_num="22131-5",
        snomed_ct="101200131",
        component="Diagnostic Analyte Component 12-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_132": ClinicalConcept_12(
        concept_id="CONCEPT_12_132",
        loinc_num="22132-6",
        snomed_ct="101200132",
        component="Diagnostic Analyte Component 12-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_133": ClinicalConcept_12(
        concept_id="CONCEPT_12_133",
        loinc_num="22133-7",
        snomed_ct="101200133",
        component="Diagnostic Analyte Component 12-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_134": ClinicalConcept_12(
        concept_id="CONCEPT_12_134",
        loinc_num="22134-8",
        snomed_ct="101200134",
        component="Diagnostic Analyte Component 12-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_135": ClinicalConcept_12(
        concept_id="CONCEPT_12_135",
        loinc_num="22135-0",
        snomed_ct="101200135",
        component="Diagnostic Analyte Component 12-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_136": ClinicalConcept_12(
        concept_id="CONCEPT_12_136",
        loinc_num="22136-1",
        snomed_ct="101200136",
        component="Diagnostic Analyte Component 12-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_137": ClinicalConcept_12(
        concept_id="CONCEPT_12_137",
        loinc_num="22137-2",
        snomed_ct="101200137",
        component="Diagnostic Analyte Component 12-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_138": ClinicalConcept_12(
        concept_id="CONCEPT_12_138",
        loinc_num="22138-3",
        snomed_ct="101200138",
        component="Diagnostic Analyte Component 12-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_139": ClinicalConcept_12(
        concept_id="CONCEPT_12_139",
        loinc_num="22139-4",
        snomed_ct="101200139",
        component="Diagnostic Analyte Component 12-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_140": ClinicalConcept_12(
        concept_id="CONCEPT_12_140",
        loinc_num="22140-5",
        snomed_ct="101200140",
        component="Diagnostic Analyte Component 12-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_141": ClinicalConcept_12(
        concept_id="CONCEPT_12_141",
        loinc_num="22141-6",
        snomed_ct="101200141",
        component="Diagnostic Analyte Component 12-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_142": ClinicalConcept_12(
        concept_id="CONCEPT_12_142",
        loinc_num="22142-7",
        snomed_ct="101200142",
        component="Diagnostic Analyte Component 12-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_143": ClinicalConcept_12(
        concept_id="CONCEPT_12_143",
        loinc_num="22143-8",
        snomed_ct="101200143",
        component="Diagnostic Analyte Component 12-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_144": ClinicalConcept_12(
        concept_id="CONCEPT_12_144",
        loinc_num="22144-0",
        snomed_ct="101200144",
        component="Diagnostic Analyte Component 12-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_145": ClinicalConcept_12(
        concept_id="CONCEPT_12_145",
        loinc_num="22145-1",
        snomed_ct="101200145",
        component="Diagnostic Analyte Component 12-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_146": ClinicalConcept_12(
        concept_id="CONCEPT_12_146",
        loinc_num="22146-2",
        snomed_ct="101200146",
        component="Diagnostic Analyte Component 12-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_147": ClinicalConcept_12(
        concept_id="CONCEPT_12_147",
        loinc_num="22147-3",
        snomed_ct="101200147",
        component="Diagnostic Analyte Component 12-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_148": ClinicalConcept_12(
        concept_id="CONCEPT_12_148",
        loinc_num="22148-4",
        snomed_ct="101200148",
        component="Diagnostic Analyte Component 12-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_149": ClinicalConcept_12(
        concept_id="CONCEPT_12_149",
        loinc_num="22149-5",
        snomed_ct="101200149",
        component="Diagnostic Analyte Component 12-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_150": ClinicalConcept_12(
        concept_id="CONCEPT_12_150",
        loinc_num="22150-6",
        snomed_ct="101200150",
        component="Diagnostic Analyte Component 12-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_151": ClinicalConcept_12(
        concept_id="CONCEPT_12_151",
        loinc_num="22151-7",
        snomed_ct="101200151",
        component="Diagnostic Analyte Component 12-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_152": ClinicalConcept_12(
        concept_id="CONCEPT_12_152",
        loinc_num="22152-8",
        snomed_ct="101200152",
        component="Diagnostic Analyte Component 12-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_153": ClinicalConcept_12(
        concept_id="CONCEPT_12_153",
        loinc_num="22153-0",
        snomed_ct="101200153",
        component="Diagnostic Analyte Component 12-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_154": ClinicalConcept_12(
        concept_id="CONCEPT_12_154",
        loinc_num="22154-1",
        snomed_ct="101200154",
        component="Diagnostic Analyte Component 12-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_155": ClinicalConcept_12(
        concept_id="CONCEPT_12_155",
        loinc_num="22155-2",
        snomed_ct="101200155",
        component="Diagnostic Analyte Component 12-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_156": ClinicalConcept_12(
        concept_id="CONCEPT_12_156",
        loinc_num="22156-3",
        snomed_ct="101200156",
        component="Diagnostic Analyte Component 12-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_157": ClinicalConcept_12(
        concept_id="CONCEPT_12_157",
        loinc_num="22157-4",
        snomed_ct="101200157",
        component="Diagnostic Analyte Component 12-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_158": ClinicalConcept_12(
        concept_id="CONCEPT_12_158",
        loinc_num="22158-5",
        snomed_ct="101200158",
        component="Diagnostic Analyte Component 12-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_159": ClinicalConcept_12(
        concept_id="CONCEPT_12_159",
        loinc_num="22159-6",
        snomed_ct="101200159",
        component="Diagnostic Analyte Component 12-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_160": ClinicalConcept_12(
        concept_id="CONCEPT_12_160",
        loinc_num="22160-7",
        snomed_ct="101200160",
        component="Diagnostic Analyte Component 12-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_161": ClinicalConcept_12(
        concept_id="CONCEPT_12_161",
        loinc_num="22161-8",
        snomed_ct="101200161",
        component="Diagnostic Analyte Component 12-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_162": ClinicalConcept_12(
        concept_id="CONCEPT_12_162",
        loinc_num="22162-0",
        snomed_ct="101200162",
        component="Diagnostic Analyte Component 12-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_163": ClinicalConcept_12(
        concept_id="CONCEPT_12_163",
        loinc_num="22163-1",
        snomed_ct="101200163",
        component="Diagnostic Analyte Component 12-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_164": ClinicalConcept_12(
        concept_id="CONCEPT_12_164",
        loinc_num="22164-2",
        snomed_ct="101200164",
        component="Diagnostic Analyte Component 12-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_165": ClinicalConcept_12(
        concept_id="CONCEPT_12_165",
        loinc_num="22165-3",
        snomed_ct="101200165",
        component="Diagnostic Analyte Component 12-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_166": ClinicalConcept_12(
        concept_id="CONCEPT_12_166",
        loinc_num="22166-4",
        snomed_ct="101200166",
        component="Diagnostic Analyte Component 12-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_167": ClinicalConcept_12(
        concept_id="CONCEPT_12_167",
        loinc_num="22167-5",
        snomed_ct="101200167",
        component="Diagnostic Analyte Component 12-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_168": ClinicalConcept_12(
        concept_id="CONCEPT_12_168",
        loinc_num="22168-6",
        snomed_ct="101200168",
        component="Diagnostic Analyte Component 12-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_169": ClinicalConcept_12(
        concept_id="CONCEPT_12_169",
        loinc_num="22169-7",
        snomed_ct="101200169",
        component="Diagnostic Analyte Component 12-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_170": ClinicalConcept_12(
        concept_id="CONCEPT_12_170",
        loinc_num="22170-8",
        snomed_ct="101200170",
        component="Diagnostic Analyte Component 12-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_171": ClinicalConcept_12(
        concept_id="CONCEPT_12_171",
        loinc_num="22171-0",
        snomed_ct="101200171",
        component="Diagnostic Analyte Component 12-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_172": ClinicalConcept_12(
        concept_id="CONCEPT_12_172",
        loinc_num="22172-1",
        snomed_ct="101200172",
        component="Diagnostic Analyte Component 12-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_173": ClinicalConcept_12(
        concept_id="CONCEPT_12_173",
        loinc_num="22173-2",
        snomed_ct="101200173",
        component="Diagnostic Analyte Component 12-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_174": ClinicalConcept_12(
        concept_id="CONCEPT_12_174",
        loinc_num="22174-3",
        snomed_ct="101200174",
        component="Diagnostic Analyte Component 12-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_175": ClinicalConcept_12(
        concept_id="CONCEPT_12_175",
        loinc_num="22175-4",
        snomed_ct="101200175",
        component="Diagnostic Analyte Component 12-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_176": ClinicalConcept_12(
        concept_id="CONCEPT_12_176",
        loinc_num="22176-5",
        snomed_ct="101200176",
        component="Diagnostic Analyte Component 12-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_177": ClinicalConcept_12(
        concept_id="CONCEPT_12_177",
        loinc_num="22177-6",
        snomed_ct="101200177",
        component="Diagnostic Analyte Component 12-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_178": ClinicalConcept_12(
        concept_id="CONCEPT_12_178",
        loinc_num="22178-7",
        snomed_ct="101200178",
        component="Diagnostic Analyte Component 12-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_179": ClinicalConcept_12(
        concept_id="CONCEPT_12_179",
        loinc_num="22179-8",
        snomed_ct="101200179",
        component="Diagnostic Analyte Component 12-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_180": ClinicalConcept_12(
        concept_id="CONCEPT_12_180",
        loinc_num="22180-0",
        snomed_ct="101200180",
        component="Diagnostic Analyte Component 12-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_181": ClinicalConcept_12(
        concept_id="CONCEPT_12_181",
        loinc_num="22181-1",
        snomed_ct="101200181",
        component="Diagnostic Analyte Component 12-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_182": ClinicalConcept_12(
        concept_id="CONCEPT_12_182",
        loinc_num="22182-2",
        snomed_ct="101200182",
        component="Diagnostic Analyte Component 12-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_183": ClinicalConcept_12(
        concept_id="CONCEPT_12_183",
        loinc_num="22183-3",
        snomed_ct="101200183",
        component="Diagnostic Analyte Component 12-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_184": ClinicalConcept_12(
        concept_id="CONCEPT_12_184",
        loinc_num="22184-4",
        snomed_ct="101200184",
        component="Diagnostic Analyte Component 12-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_185": ClinicalConcept_12(
        concept_id="CONCEPT_12_185",
        loinc_num="22185-5",
        snomed_ct="101200185",
        component="Diagnostic Analyte Component 12-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_186": ClinicalConcept_12(
        concept_id="CONCEPT_12_186",
        loinc_num="22186-6",
        snomed_ct="101200186",
        component="Diagnostic Analyte Component 12-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_187": ClinicalConcept_12(
        concept_id="CONCEPT_12_187",
        loinc_num="22187-7",
        snomed_ct="101200187",
        component="Diagnostic Analyte Component 12-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_188": ClinicalConcept_12(
        concept_id="CONCEPT_12_188",
        loinc_num="22188-8",
        snomed_ct="101200188",
        component="Diagnostic Analyte Component 12-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_189": ClinicalConcept_12(
        concept_id="CONCEPT_12_189",
        loinc_num="22189-0",
        snomed_ct="101200189",
        component="Diagnostic Analyte Component 12-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_190": ClinicalConcept_12(
        concept_id="CONCEPT_12_190",
        loinc_num="22190-1",
        snomed_ct="101200190",
        component="Diagnostic Analyte Component 12-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_191": ClinicalConcept_12(
        concept_id="CONCEPT_12_191",
        loinc_num="22191-2",
        snomed_ct="101200191",
        component="Diagnostic Analyte Component 12-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_192": ClinicalConcept_12(
        concept_id="CONCEPT_12_192",
        loinc_num="22192-3",
        snomed_ct="101200192",
        component="Diagnostic Analyte Component 12-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_193": ClinicalConcept_12(
        concept_id="CONCEPT_12_193",
        loinc_num="22193-4",
        snomed_ct="101200193",
        component="Diagnostic Analyte Component 12-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_194": ClinicalConcept_12(
        concept_id="CONCEPT_12_194",
        loinc_num="22194-5",
        snomed_ct="101200194",
        component="Diagnostic Analyte Component 12-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_195": ClinicalConcept_12(
        concept_id="CONCEPT_12_195",
        loinc_num="22195-6",
        snomed_ct="101200195",
        component="Diagnostic Analyte Component 12-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_196": ClinicalConcept_12(
        concept_id="CONCEPT_12_196",
        loinc_num="22196-7",
        snomed_ct="101200196",
        component="Diagnostic Analyte Component 12-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_197": ClinicalConcept_12(
        concept_id="CONCEPT_12_197",
        loinc_num="22197-8",
        snomed_ct="101200197",
        component="Diagnostic Analyte Component 12-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_198": ClinicalConcept_12(
        concept_id="CONCEPT_12_198",
        loinc_num="22198-0",
        snomed_ct="101200198",
        component="Diagnostic Analyte Component 12-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_12_199": ClinicalConcept_12(
        concept_id="CONCEPT_12_199",
        loinc_num="22199-1",
        snomed_ct="101200199",
        component="Diagnostic Analyte Component 12-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
