"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 18"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_18:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_18 = {
    "CONCEPT_18_001": ClinicalConcept_18(
        concept_id="CONCEPT_18_001",
        loinc_num="28001-1",
        snomed_ct="101800001",
        component="Diagnostic Analyte Component 18-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_002": ClinicalConcept_18(
        concept_id="CONCEPT_18_002",
        loinc_num="28002-2",
        snomed_ct="101800002",
        component="Diagnostic Analyte Component 18-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_003": ClinicalConcept_18(
        concept_id="CONCEPT_18_003",
        loinc_num="28003-3",
        snomed_ct="101800003",
        component="Diagnostic Analyte Component 18-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_004": ClinicalConcept_18(
        concept_id="CONCEPT_18_004",
        loinc_num="28004-4",
        snomed_ct="101800004",
        component="Diagnostic Analyte Component 18-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_005": ClinicalConcept_18(
        concept_id="CONCEPT_18_005",
        loinc_num="28005-5",
        snomed_ct="101800005",
        component="Diagnostic Analyte Component 18-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_006": ClinicalConcept_18(
        concept_id="CONCEPT_18_006",
        loinc_num="28006-6",
        snomed_ct="101800006",
        component="Diagnostic Analyte Component 18-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_007": ClinicalConcept_18(
        concept_id="CONCEPT_18_007",
        loinc_num="28007-7",
        snomed_ct="101800007",
        component="Diagnostic Analyte Component 18-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_008": ClinicalConcept_18(
        concept_id="CONCEPT_18_008",
        loinc_num="28008-8",
        snomed_ct="101800008",
        component="Diagnostic Analyte Component 18-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_009": ClinicalConcept_18(
        concept_id="CONCEPT_18_009",
        loinc_num="28009-0",
        snomed_ct="101800009",
        component="Diagnostic Analyte Component 18-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_010": ClinicalConcept_18(
        concept_id="CONCEPT_18_010",
        loinc_num="28010-1",
        snomed_ct="101800010",
        component="Diagnostic Analyte Component 18-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_011": ClinicalConcept_18(
        concept_id="CONCEPT_18_011",
        loinc_num="28011-2",
        snomed_ct="101800011",
        component="Diagnostic Analyte Component 18-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_012": ClinicalConcept_18(
        concept_id="CONCEPT_18_012",
        loinc_num="28012-3",
        snomed_ct="101800012",
        component="Diagnostic Analyte Component 18-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_013": ClinicalConcept_18(
        concept_id="CONCEPT_18_013",
        loinc_num="28013-4",
        snomed_ct="101800013",
        component="Diagnostic Analyte Component 18-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_014": ClinicalConcept_18(
        concept_id="CONCEPT_18_014",
        loinc_num="28014-5",
        snomed_ct="101800014",
        component="Diagnostic Analyte Component 18-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_015": ClinicalConcept_18(
        concept_id="CONCEPT_18_015",
        loinc_num="28015-6",
        snomed_ct="101800015",
        component="Diagnostic Analyte Component 18-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_016": ClinicalConcept_18(
        concept_id="CONCEPT_18_016",
        loinc_num="28016-7",
        snomed_ct="101800016",
        component="Diagnostic Analyte Component 18-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_017": ClinicalConcept_18(
        concept_id="CONCEPT_18_017",
        loinc_num="28017-8",
        snomed_ct="101800017",
        component="Diagnostic Analyte Component 18-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_018": ClinicalConcept_18(
        concept_id="CONCEPT_18_018",
        loinc_num="28018-0",
        snomed_ct="101800018",
        component="Diagnostic Analyte Component 18-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_019": ClinicalConcept_18(
        concept_id="CONCEPT_18_019",
        loinc_num="28019-1",
        snomed_ct="101800019",
        component="Diagnostic Analyte Component 18-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_020": ClinicalConcept_18(
        concept_id="CONCEPT_18_020",
        loinc_num="28020-2",
        snomed_ct="101800020",
        component="Diagnostic Analyte Component 18-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_021": ClinicalConcept_18(
        concept_id="CONCEPT_18_021",
        loinc_num="28021-3",
        snomed_ct="101800021",
        component="Diagnostic Analyte Component 18-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_022": ClinicalConcept_18(
        concept_id="CONCEPT_18_022",
        loinc_num="28022-4",
        snomed_ct="101800022",
        component="Diagnostic Analyte Component 18-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_023": ClinicalConcept_18(
        concept_id="CONCEPT_18_023",
        loinc_num="28023-5",
        snomed_ct="101800023",
        component="Diagnostic Analyte Component 18-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_024": ClinicalConcept_18(
        concept_id="CONCEPT_18_024",
        loinc_num="28024-6",
        snomed_ct="101800024",
        component="Diagnostic Analyte Component 18-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_025": ClinicalConcept_18(
        concept_id="CONCEPT_18_025",
        loinc_num="28025-7",
        snomed_ct="101800025",
        component="Diagnostic Analyte Component 18-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_026": ClinicalConcept_18(
        concept_id="CONCEPT_18_026",
        loinc_num="28026-8",
        snomed_ct="101800026",
        component="Diagnostic Analyte Component 18-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_027": ClinicalConcept_18(
        concept_id="CONCEPT_18_027",
        loinc_num="28027-0",
        snomed_ct="101800027",
        component="Diagnostic Analyte Component 18-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_028": ClinicalConcept_18(
        concept_id="CONCEPT_18_028",
        loinc_num="28028-1",
        snomed_ct="101800028",
        component="Diagnostic Analyte Component 18-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_029": ClinicalConcept_18(
        concept_id="CONCEPT_18_029",
        loinc_num="28029-2",
        snomed_ct="101800029",
        component="Diagnostic Analyte Component 18-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_030": ClinicalConcept_18(
        concept_id="CONCEPT_18_030",
        loinc_num="28030-3",
        snomed_ct="101800030",
        component="Diagnostic Analyte Component 18-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_031": ClinicalConcept_18(
        concept_id="CONCEPT_18_031",
        loinc_num="28031-4",
        snomed_ct="101800031",
        component="Diagnostic Analyte Component 18-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_032": ClinicalConcept_18(
        concept_id="CONCEPT_18_032",
        loinc_num="28032-5",
        snomed_ct="101800032",
        component="Diagnostic Analyte Component 18-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_033": ClinicalConcept_18(
        concept_id="CONCEPT_18_033",
        loinc_num="28033-6",
        snomed_ct="101800033",
        component="Diagnostic Analyte Component 18-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_034": ClinicalConcept_18(
        concept_id="CONCEPT_18_034",
        loinc_num="28034-7",
        snomed_ct="101800034",
        component="Diagnostic Analyte Component 18-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_035": ClinicalConcept_18(
        concept_id="CONCEPT_18_035",
        loinc_num="28035-8",
        snomed_ct="101800035",
        component="Diagnostic Analyte Component 18-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_036": ClinicalConcept_18(
        concept_id="CONCEPT_18_036",
        loinc_num="28036-0",
        snomed_ct="101800036",
        component="Diagnostic Analyte Component 18-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_037": ClinicalConcept_18(
        concept_id="CONCEPT_18_037",
        loinc_num="28037-1",
        snomed_ct="101800037",
        component="Diagnostic Analyte Component 18-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_038": ClinicalConcept_18(
        concept_id="CONCEPT_18_038",
        loinc_num="28038-2",
        snomed_ct="101800038",
        component="Diagnostic Analyte Component 18-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_039": ClinicalConcept_18(
        concept_id="CONCEPT_18_039",
        loinc_num="28039-3",
        snomed_ct="101800039",
        component="Diagnostic Analyte Component 18-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_040": ClinicalConcept_18(
        concept_id="CONCEPT_18_040",
        loinc_num="28040-4",
        snomed_ct="101800040",
        component="Diagnostic Analyte Component 18-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_041": ClinicalConcept_18(
        concept_id="CONCEPT_18_041",
        loinc_num="28041-5",
        snomed_ct="101800041",
        component="Diagnostic Analyte Component 18-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_042": ClinicalConcept_18(
        concept_id="CONCEPT_18_042",
        loinc_num="28042-6",
        snomed_ct="101800042",
        component="Diagnostic Analyte Component 18-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_043": ClinicalConcept_18(
        concept_id="CONCEPT_18_043",
        loinc_num="28043-7",
        snomed_ct="101800043",
        component="Diagnostic Analyte Component 18-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_044": ClinicalConcept_18(
        concept_id="CONCEPT_18_044",
        loinc_num="28044-8",
        snomed_ct="101800044",
        component="Diagnostic Analyte Component 18-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_045": ClinicalConcept_18(
        concept_id="CONCEPT_18_045",
        loinc_num="28045-0",
        snomed_ct="101800045",
        component="Diagnostic Analyte Component 18-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_046": ClinicalConcept_18(
        concept_id="CONCEPT_18_046",
        loinc_num="28046-1",
        snomed_ct="101800046",
        component="Diagnostic Analyte Component 18-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_047": ClinicalConcept_18(
        concept_id="CONCEPT_18_047",
        loinc_num="28047-2",
        snomed_ct="101800047",
        component="Diagnostic Analyte Component 18-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_048": ClinicalConcept_18(
        concept_id="CONCEPT_18_048",
        loinc_num="28048-3",
        snomed_ct="101800048",
        component="Diagnostic Analyte Component 18-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_049": ClinicalConcept_18(
        concept_id="CONCEPT_18_049",
        loinc_num="28049-4",
        snomed_ct="101800049",
        component="Diagnostic Analyte Component 18-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_050": ClinicalConcept_18(
        concept_id="CONCEPT_18_050",
        loinc_num="28050-5",
        snomed_ct="101800050",
        component="Diagnostic Analyte Component 18-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_051": ClinicalConcept_18(
        concept_id="CONCEPT_18_051",
        loinc_num="28051-6",
        snomed_ct="101800051",
        component="Diagnostic Analyte Component 18-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_052": ClinicalConcept_18(
        concept_id="CONCEPT_18_052",
        loinc_num="28052-7",
        snomed_ct="101800052",
        component="Diagnostic Analyte Component 18-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_053": ClinicalConcept_18(
        concept_id="CONCEPT_18_053",
        loinc_num="28053-8",
        snomed_ct="101800053",
        component="Diagnostic Analyte Component 18-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_054": ClinicalConcept_18(
        concept_id="CONCEPT_18_054",
        loinc_num="28054-0",
        snomed_ct="101800054",
        component="Diagnostic Analyte Component 18-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_055": ClinicalConcept_18(
        concept_id="CONCEPT_18_055",
        loinc_num="28055-1",
        snomed_ct="101800055",
        component="Diagnostic Analyte Component 18-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_056": ClinicalConcept_18(
        concept_id="CONCEPT_18_056",
        loinc_num="28056-2",
        snomed_ct="101800056",
        component="Diagnostic Analyte Component 18-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_057": ClinicalConcept_18(
        concept_id="CONCEPT_18_057",
        loinc_num="28057-3",
        snomed_ct="101800057",
        component="Diagnostic Analyte Component 18-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_058": ClinicalConcept_18(
        concept_id="CONCEPT_18_058",
        loinc_num="28058-4",
        snomed_ct="101800058",
        component="Diagnostic Analyte Component 18-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_059": ClinicalConcept_18(
        concept_id="CONCEPT_18_059",
        loinc_num="28059-5",
        snomed_ct="101800059",
        component="Diagnostic Analyte Component 18-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_060": ClinicalConcept_18(
        concept_id="CONCEPT_18_060",
        loinc_num="28060-6",
        snomed_ct="101800060",
        component="Diagnostic Analyte Component 18-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_061": ClinicalConcept_18(
        concept_id="CONCEPT_18_061",
        loinc_num="28061-7",
        snomed_ct="101800061",
        component="Diagnostic Analyte Component 18-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_062": ClinicalConcept_18(
        concept_id="CONCEPT_18_062",
        loinc_num="28062-8",
        snomed_ct="101800062",
        component="Diagnostic Analyte Component 18-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_063": ClinicalConcept_18(
        concept_id="CONCEPT_18_063",
        loinc_num="28063-0",
        snomed_ct="101800063",
        component="Diagnostic Analyte Component 18-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_064": ClinicalConcept_18(
        concept_id="CONCEPT_18_064",
        loinc_num="28064-1",
        snomed_ct="101800064",
        component="Diagnostic Analyte Component 18-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_065": ClinicalConcept_18(
        concept_id="CONCEPT_18_065",
        loinc_num="28065-2",
        snomed_ct="101800065",
        component="Diagnostic Analyte Component 18-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_066": ClinicalConcept_18(
        concept_id="CONCEPT_18_066",
        loinc_num="28066-3",
        snomed_ct="101800066",
        component="Diagnostic Analyte Component 18-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_067": ClinicalConcept_18(
        concept_id="CONCEPT_18_067",
        loinc_num="28067-4",
        snomed_ct="101800067",
        component="Diagnostic Analyte Component 18-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_068": ClinicalConcept_18(
        concept_id="CONCEPT_18_068",
        loinc_num="28068-5",
        snomed_ct="101800068",
        component="Diagnostic Analyte Component 18-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_069": ClinicalConcept_18(
        concept_id="CONCEPT_18_069",
        loinc_num="28069-6",
        snomed_ct="101800069",
        component="Diagnostic Analyte Component 18-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_070": ClinicalConcept_18(
        concept_id="CONCEPT_18_070",
        loinc_num="28070-7",
        snomed_ct="101800070",
        component="Diagnostic Analyte Component 18-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_071": ClinicalConcept_18(
        concept_id="CONCEPT_18_071",
        loinc_num="28071-8",
        snomed_ct="101800071",
        component="Diagnostic Analyte Component 18-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_072": ClinicalConcept_18(
        concept_id="CONCEPT_18_072",
        loinc_num="28072-0",
        snomed_ct="101800072",
        component="Diagnostic Analyte Component 18-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_073": ClinicalConcept_18(
        concept_id="CONCEPT_18_073",
        loinc_num="28073-1",
        snomed_ct="101800073",
        component="Diagnostic Analyte Component 18-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_074": ClinicalConcept_18(
        concept_id="CONCEPT_18_074",
        loinc_num="28074-2",
        snomed_ct="101800074",
        component="Diagnostic Analyte Component 18-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_075": ClinicalConcept_18(
        concept_id="CONCEPT_18_075",
        loinc_num="28075-3",
        snomed_ct="101800075",
        component="Diagnostic Analyte Component 18-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_076": ClinicalConcept_18(
        concept_id="CONCEPT_18_076",
        loinc_num="28076-4",
        snomed_ct="101800076",
        component="Diagnostic Analyte Component 18-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_077": ClinicalConcept_18(
        concept_id="CONCEPT_18_077",
        loinc_num="28077-5",
        snomed_ct="101800077",
        component="Diagnostic Analyte Component 18-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_078": ClinicalConcept_18(
        concept_id="CONCEPT_18_078",
        loinc_num="28078-6",
        snomed_ct="101800078",
        component="Diagnostic Analyte Component 18-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_079": ClinicalConcept_18(
        concept_id="CONCEPT_18_079",
        loinc_num="28079-7",
        snomed_ct="101800079",
        component="Diagnostic Analyte Component 18-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_080": ClinicalConcept_18(
        concept_id="CONCEPT_18_080",
        loinc_num="28080-8",
        snomed_ct="101800080",
        component="Diagnostic Analyte Component 18-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_081": ClinicalConcept_18(
        concept_id="CONCEPT_18_081",
        loinc_num="28081-0",
        snomed_ct="101800081",
        component="Diagnostic Analyte Component 18-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_082": ClinicalConcept_18(
        concept_id="CONCEPT_18_082",
        loinc_num="28082-1",
        snomed_ct="101800082",
        component="Diagnostic Analyte Component 18-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_083": ClinicalConcept_18(
        concept_id="CONCEPT_18_083",
        loinc_num="28083-2",
        snomed_ct="101800083",
        component="Diagnostic Analyte Component 18-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_084": ClinicalConcept_18(
        concept_id="CONCEPT_18_084",
        loinc_num="28084-3",
        snomed_ct="101800084",
        component="Diagnostic Analyte Component 18-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_085": ClinicalConcept_18(
        concept_id="CONCEPT_18_085",
        loinc_num="28085-4",
        snomed_ct="101800085",
        component="Diagnostic Analyte Component 18-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_086": ClinicalConcept_18(
        concept_id="CONCEPT_18_086",
        loinc_num="28086-5",
        snomed_ct="101800086",
        component="Diagnostic Analyte Component 18-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_087": ClinicalConcept_18(
        concept_id="CONCEPT_18_087",
        loinc_num="28087-6",
        snomed_ct="101800087",
        component="Diagnostic Analyte Component 18-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_088": ClinicalConcept_18(
        concept_id="CONCEPT_18_088",
        loinc_num="28088-7",
        snomed_ct="101800088",
        component="Diagnostic Analyte Component 18-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_089": ClinicalConcept_18(
        concept_id="CONCEPT_18_089",
        loinc_num="28089-8",
        snomed_ct="101800089",
        component="Diagnostic Analyte Component 18-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_090": ClinicalConcept_18(
        concept_id="CONCEPT_18_090",
        loinc_num="28090-0",
        snomed_ct="101800090",
        component="Diagnostic Analyte Component 18-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_091": ClinicalConcept_18(
        concept_id="CONCEPT_18_091",
        loinc_num="28091-1",
        snomed_ct="101800091",
        component="Diagnostic Analyte Component 18-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_092": ClinicalConcept_18(
        concept_id="CONCEPT_18_092",
        loinc_num="28092-2",
        snomed_ct="101800092",
        component="Diagnostic Analyte Component 18-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_093": ClinicalConcept_18(
        concept_id="CONCEPT_18_093",
        loinc_num="28093-3",
        snomed_ct="101800093",
        component="Diagnostic Analyte Component 18-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_094": ClinicalConcept_18(
        concept_id="CONCEPT_18_094",
        loinc_num="28094-4",
        snomed_ct="101800094",
        component="Diagnostic Analyte Component 18-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_095": ClinicalConcept_18(
        concept_id="CONCEPT_18_095",
        loinc_num="28095-5",
        snomed_ct="101800095",
        component="Diagnostic Analyte Component 18-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_096": ClinicalConcept_18(
        concept_id="CONCEPT_18_096",
        loinc_num="28096-6",
        snomed_ct="101800096",
        component="Diagnostic Analyte Component 18-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_097": ClinicalConcept_18(
        concept_id="CONCEPT_18_097",
        loinc_num="28097-7",
        snomed_ct="101800097",
        component="Diagnostic Analyte Component 18-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_098": ClinicalConcept_18(
        concept_id="CONCEPT_18_098",
        loinc_num="28098-8",
        snomed_ct="101800098",
        component="Diagnostic Analyte Component 18-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_099": ClinicalConcept_18(
        concept_id="CONCEPT_18_099",
        loinc_num="28099-0",
        snomed_ct="101800099",
        component="Diagnostic Analyte Component 18-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_100": ClinicalConcept_18(
        concept_id="CONCEPT_18_100",
        loinc_num="28100-1",
        snomed_ct="101800100",
        component="Diagnostic Analyte Component 18-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_101": ClinicalConcept_18(
        concept_id="CONCEPT_18_101",
        loinc_num="28101-2",
        snomed_ct="101800101",
        component="Diagnostic Analyte Component 18-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_102": ClinicalConcept_18(
        concept_id="CONCEPT_18_102",
        loinc_num="28102-3",
        snomed_ct="101800102",
        component="Diagnostic Analyte Component 18-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_103": ClinicalConcept_18(
        concept_id="CONCEPT_18_103",
        loinc_num="28103-4",
        snomed_ct="101800103",
        component="Diagnostic Analyte Component 18-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_104": ClinicalConcept_18(
        concept_id="CONCEPT_18_104",
        loinc_num="28104-5",
        snomed_ct="101800104",
        component="Diagnostic Analyte Component 18-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_105": ClinicalConcept_18(
        concept_id="CONCEPT_18_105",
        loinc_num="28105-6",
        snomed_ct="101800105",
        component="Diagnostic Analyte Component 18-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_106": ClinicalConcept_18(
        concept_id="CONCEPT_18_106",
        loinc_num="28106-7",
        snomed_ct="101800106",
        component="Diagnostic Analyte Component 18-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_107": ClinicalConcept_18(
        concept_id="CONCEPT_18_107",
        loinc_num="28107-8",
        snomed_ct="101800107",
        component="Diagnostic Analyte Component 18-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_108": ClinicalConcept_18(
        concept_id="CONCEPT_18_108",
        loinc_num="28108-0",
        snomed_ct="101800108",
        component="Diagnostic Analyte Component 18-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_109": ClinicalConcept_18(
        concept_id="CONCEPT_18_109",
        loinc_num="28109-1",
        snomed_ct="101800109",
        component="Diagnostic Analyte Component 18-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_110": ClinicalConcept_18(
        concept_id="CONCEPT_18_110",
        loinc_num="28110-2",
        snomed_ct="101800110",
        component="Diagnostic Analyte Component 18-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_111": ClinicalConcept_18(
        concept_id="CONCEPT_18_111",
        loinc_num="28111-3",
        snomed_ct="101800111",
        component="Diagnostic Analyte Component 18-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_112": ClinicalConcept_18(
        concept_id="CONCEPT_18_112",
        loinc_num="28112-4",
        snomed_ct="101800112",
        component="Diagnostic Analyte Component 18-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_113": ClinicalConcept_18(
        concept_id="CONCEPT_18_113",
        loinc_num="28113-5",
        snomed_ct="101800113",
        component="Diagnostic Analyte Component 18-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_114": ClinicalConcept_18(
        concept_id="CONCEPT_18_114",
        loinc_num="28114-6",
        snomed_ct="101800114",
        component="Diagnostic Analyte Component 18-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_115": ClinicalConcept_18(
        concept_id="CONCEPT_18_115",
        loinc_num="28115-7",
        snomed_ct="101800115",
        component="Diagnostic Analyte Component 18-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_116": ClinicalConcept_18(
        concept_id="CONCEPT_18_116",
        loinc_num="28116-8",
        snomed_ct="101800116",
        component="Diagnostic Analyte Component 18-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_117": ClinicalConcept_18(
        concept_id="CONCEPT_18_117",
        loinc_num="28117-0",
        snomed_ct="101800117",
        component="Diagnostic Analyte Component 18-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_118": ClinicalConcept_18(
        concept_id="CONCEPT_18_118",
        loinc_num="28118-1",
        snomed_ct="101800118",
        component="Diagnostic Analyte Component 18-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_119": ClinicalConcept_18(
        concept_id="CONCEPT_18_119",
        loinc_num="28119-2",
        snomed_ct="101800119",
        component="Diagnostic Analyte Component 18-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_120": ClinicalConcept_18(
        concept_id="CONCEPT_18_120",
        loinc_num="28120-3",
        snomed_ct="101800120",
        component="Diagnostic Analyte Component 18-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_121": ClinicalConcept_18(
        concept_id="CONCEPT_18_121",
        loinc_num="28121-4",
        snomed_ct="101800121",
        component="Diagnostic Analyte Component 18-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_122": ClinicalConcept_18(
        concept_id="CONCEPT_18_122",
        loinc_num="28122-5",
        snomed_ct="101800122",
        component="Diagnostic Analyte Component 18-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_123": ClinicalConcept_18(
        concept_id="CONCEPT_18_123",
        loinc_num="28123-6",
        snomed_ct="101800123",
        component="Diagnostic Analyte Component 18-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_124": ClinicalConcept_18(
        concept_id="CONCEPT_18_124",
        loinc_num="28124-7",
        snomed_ct="101800124",
        component="Diagnostic Analyte Component 18-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_125": ClinicalConcept_18(
        concept_id="CONCEPT_18_125",
        loinc_num="28125-8",
        snomed_ct="101800125",
        component="Diagnostic Analyte Component 18-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_126": ClinicalConcept_18(
        concept_id="CONCEPT_18_126",
        loinc_num="28126-0",
        snomed_ct="101800126",
        component="Diagnostic Analyte Component 18-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_127": ClinicalConcept_18(
        concept_id="CONCEPT_18_127",
        loinc_num="28127-1",
        snomed_ct="101800127",
        component="Diagnostic Analyte Component 18-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_128": ClinicalConcept_18(
        concept_id="CONCEPT_18_128",
        loinc_num="28128-2",
        snomed_ct="101800128",
        component="Diagnostic Analyte Component 18-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_129": ClinicalConcept_18(
        concept_id="CONCEPT_18_129",
        loinc_num="28129-3",
        snomed_ct="101800129",
        component="Diagnostic Analyte Component 18-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_130": ClinicalConcept_18(
        concept_id="CONCEPT_18_130",
        loinc_num="28130-4",
        snomed_ct="101800130",
        component="Diagnostic Analyte Component 18-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_131": ClinicalConcept_18(
        concept_id="CONCEPT_18_131",
        loinc_num="28131-5",
        snomed_ct="101800131",
        component="Diagnostic Analyte Component 18-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_132": ClinicalConcept_18(
        concept_id="CONCEPT_18_132",
        loinc_num="28132-6",
        snomed_ct="101800132",
        component="Diagnostic Analyte Component 18-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_133": ClinicalConcept_18(
        concept_id="CONCEPT_18_133",
        loinc_num="28133-7",
        snomed_ct="101800133",
        component="Diagnostic Analyte Component 18-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_134": ClinicalConcept_18(
        concept_id="CONCEPT_18_134",
        loinc_num="28134-8",
        snomed_ct="101800134",
        component="Diagnostic Analyte Component 18-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_135": ClinicalConcept_18(
        concept_id="CONCEPT_18_135",
        loinc_num="28135-0",
        snomed_ct="101800135",
        component="Diagnostic Analyte Component 18-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_136": ClinicalConcept_18(
        concept_id="CONCEPT_18_136",
        loinc_num="28136-1",
        snomed_ct="101800136",
        component="Diagnostic Analyte Component 18-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_137": ClinicalConcept_18(
        concept_id="CONCEPT_18_137",
        loinc_num="28137-2",
        snomed_ct="101800137",
        component="Diagnostic Analyte Component 18-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_138": ClinicalConcept_18(
        concept_id="CONCEPT_18_138",
        loinc_num="28138-3",
        snomed_ct="101800138",
        component="Diagnostic Analyte Component 18-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_139": ClinicalConcept_18(
        concept_id="CONCEPT_18_139",
        loinc_num="28139-4",
        snomed_ct="101800139",
        component="Diagnostic Analyte Component 18-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_140": ClinicalConcept_18(
        concept_id="CONCEPT_18_140",
        loinc_num="28140-5",
        snomed_ct="101800140",
        component="Diagnostic Analyte Component 18-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_141": ClinicalConcept_18(
        concept_id="CONCEPT_18_141",
        loinc_num="28141-6",
        snomed_ct="101800141",
        component="Diagnostic Analyte Component 18-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_142": ClinicalConcept_18(
        concept_id="CONCEPT_18_142",
        loinc_num="28142-7",
        snomed_ct="101800142",
        component="Diagnostic Analyte Component 18-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_143": ClinicalConcept_18(
        concept_id="CONCEPT_18_143",
        loinc_num="28143-8",
        snomed_ct="101800143",
        component="Diagnostic Analyte Component 18-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_144": ClinicalConcept_18(
        concept_id="CONCEPT_18_144",
        loinc_num="28144-0",
        snomed_ct="101800144",
        component="Diagnostic Analyte Component 18-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_145": ClinicalConcept_18(
        concept_id="CONCEPT_18_145",
        loinc_num="28145-1",
        snomed_ct="101800145",
        component="Diagnostic Analyte Component 18-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_146": ClinicalConcept_18(
        concept_id="CONCEPT_18_146",
        loinc_num="28146-2",
        snomed_ct="101800146",
        component="Diagnostic Analyte Component 18-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_147": ClinicalConcept_18(
        concept_id="CONCEPT_18_147",
        loinc_num="28147-3",
        snomed_ct="101800147",
        component="Diagnostic Analyte Component 18-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_148": ClinicalConcept_18(
        concept_id="CONCEPT_18_148",
        loinc_num="28148-4",
        snomed_ct="101800148",
        component="Diagnostic Analyte Component 18-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_149": ClinicalConcept_18(
        concept_id="CONCEPT_18_149",
        loinc_num="28149-5",
        snomed_ct="101800149",
        component="Diagnostic Analyte Component 18-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_150": ClinicalConcept_18(
        concept_id="CONCEPT_18_150",
        loinc_num="28150-6",
        snomed_ct="101800150",
        component="Diagnostic Analyte Component 18-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_151": ClinicalConcept_18(
        concept_id="CONCEPT_18_151",
        loinc_num="28151-7",
        snomed_ct="101800151",
        component="Diagnostic Analyte Component 18-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_152": ClinicalConcept_18(
        concept_id="CONCEPT_18_152",
        loinc_num="28152-8",
        snomed_ct="101800152",
        component="Diagnostic Analyte Component 18-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_153": ClinicalConcept_18(
        concept_id="CONCEPT_18_153",
        loinc_num="28153-0",
        snomed_ct="101800153",
        component="Diagnostic Analyte Component 18-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_154": ClinicalConcept_18(
        concept_id="CONCEPT_18_154",
        loinc_num="28154-1",
        snomed_ct="101800154",
        component="Diagnostic Analyte Component 18-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_155": ClinicalConcept_18(
        concept_id="CONCEPT_18_155",
        loinc_num="28155-2",
        snomed_ct="101800155",
        component="Diagnostic Analyte Component 18-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_156": ClinicalConcept_18(
        concept_id="CONCEPT_18_156",
        loinc_num="28156-3",
        snomed_ct="101800156",
        component="Diagnostic Analyte Component 18-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_157": ClinicalConcept_18(
        concept_id="CONCEPT_18_157",
        loinc_num="28157-4",
        snomed_ct="101800157",
        component="Diagnostic Analyte Component 18-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_158": ClinicalConcept_18(
        concept_id="CONCEPT_18_158",
        loinc_num="28158-5",
        snomed_ct="101800158",
        component="Diagnostic Analyte Component 18-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_159": ClinicalConcept_18(
        concept_id="CONCEPT_18_159",
        loinc_num="28159-6",
        snomed_ct="101800159",
        component="Diagnostic Analyte Component 18-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_160": ClinicalConcept_18(
        concept_id="CONCEPT_18_160",
        loinc_num="28160-7",
        snomed_ct="101800160",
        component="Diagnostic Analyte Component 18-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_161": ClinicalConcept_18(
        concept_id="CONCEPT_18_161",
        loinc_num="28161-8",
        snomed_ct="101800161",
        component="Diagnostic Analyte Component 18-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_162": ClinicalConcept_18(
        concept_id="CONCEPT_18_162",
        loinc_num="28162-0",
        snomed_ct="101800162",
        component="Diagnostic Analyte Component 18-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_163": ClinicalConcept_18(
        concept_id="CONCEPT_18_163",
        loinc_num="28163-1",
        snomed_ct="101800163",
        component="Diagnostic Analyte Component 18-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_164": ClinicalConcept_18(
        concept_id="CONCEPT_18_164",
        loinc_num="28164-2",
        snomed_ct="101800164",
        component="Diagnostic Analyte Component 18-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_165": ClinicalConcept_18(
        concept_id="CONCEPT_18_165",
        loinc_num="28165-3",
        snomed_ct="101800165",
        component="Diagnostic Analyte Component 18-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_166": ClinicalConcept_18(
        concept_id="CONCEPT_18_166",
        loinc_num="28166-4",
        snomed_ct="101800166",
        component="Diagnostic Analyte Component 18-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_167": ClinicalConcept_18(
        concept_id="CONCEPT_18_167",
        loinc_num="28167-5",
        snomed_ct="101800167",
        component="Diagnostic Analyte Component 18-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_168": ClinicalConcept_18(
        concept_id="CONCEPT_18_168",
        loinc_num="28168-6",
        snomed_ct="101800168",
        component="Diagnostic Analyte Component 18-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_169": ClinicalConcept_18(
        concept_id="CONCEPT_18_169",
        loinc_num="28169-7",
        snomed_ct="101800169",
        component="Diagnostic Analyte Component 18-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_170": ClinicalConcept_18(
        concept_id="CONCEPT_18_170",
        loinc_num="28170-8",
        snomed_ct="101800170",
        component="Diagnostic Analyte Component 18-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_171": ClinicalConcept_18(
        concept_id="CONCEPT_18_171",
        loinc_num="28171-0",
        snomed_ct="101800171",
        component="Diagnostic Analyte Component 18-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_172": ClinicalConcept_18(
        concept_id="CONCEPT_18_172",
        loinc_num="28172-1",
        snomed_ct="101800172",
        component="Diagnostic Analyte Component 18-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_173": ClinicalConcept_18(
        concept_id="CONCEPT_18_173",
        loinc_num="28173-2",
        snomed_ct="101800173",
        component="Diagnostic Analyte Component 18-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_174": ClinicalConcept_18(
        concept_id="CONCEPT_18_174",
        loinc_num="28174-3",
        snomed_ct="101800174",
        component="Diagnostic Analyte Component 18-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_175": ClinicalConcept_18(
        concept_id="CONCEPT_18_175",
        loinc_num="28175-4",
        snomed_ct="101800175",
        component="Diagnostic Analyte Component 18-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_176": ClinicalConcept_18(
        concept_id="CONCEPT_18_176",
        loinc_num="28176-5",
        snomed_ct="101800176",
        component="Diagnostic Analyte Component 18-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_177": ClinicalConcept_18(
        concept_id="CONCEPT_18_177",
        loinc_num="28177-6",
        snomed_ct="101800177",
        component="Diagnostic Analyte Component 18-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_178": ClinicalConcept_18(
        concept_id="CONCEPT_18_178",
        loinc_num="28178-7",
        snomed_ct="101800178",
        component="Diagnostic Analyte Component 18-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_179": ClinicalConcept_18(
        concept_id="CONCEPT_18_179",
        loinc_num="28179-8",
        snomed_ct="101800179",
        component="Diagnostic Analyte Component 18-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_180": ClinicalConcept_18(
        concept_id="CONCEPT_18_180",
        loinc_num="28180-0",
        snomed_ct="101800180",
        component="Diagnostic Analyte Component 18-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_181": ClinicalConcept_18(
        concept_id="CONCEPT_18_181",
        loinc_num="28181-1",
        snomed_ct="101800181",
        component="Diagnostic Analyte Component 18-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_182": ClinicalConcept_18(
        concept_id="CONCEPT_18_182",
        loinc_num="28182-2",
        snomed_ct="101800182",
        component="Diagnostic Analyte Component 18-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_183": ClinicalConcept_18(
        concept_id="CONCEPT_18_183",
        loinc_num="28183-3",
        snomed_ct="101800183",
        component="Diagnostic Analyte Component 18-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_184": ClinicalConcept_18(
        concept_id="CONCEPT_18_184",
        loinc_num="28184-4",
        snomed_ct="101800184",
        component="Diagnostic Analyte Component 18-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_185": ClinicalConcept_18(
        concept_id="CONCEPT_18_185",
        loinc_num="28185-5",
        snomed_ct="101800185",
        component="Diagnostic Analyte Component 18-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_186": ClinicalConcept_18(
        concept_id="CONCEPT_18_186",
        loinc_num="28186-6",
        snomed_ct="101800186",
        component="Diagnostic Analyte Component 18-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_187": ClinicalConcept_18(
        concept_id="CONCEPT_18_187",
        loinc_num="28187-7",
        snomed_ct="101800187",
        component="Diagnostic Analyte Component 18-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_188": ClinicalConcept_18(
        concept_id="CONCEPT_18_188",
        loinc_num="28188-8",
        snomed_ct="101800188",
        component="Diagnostic Analyte Component 18-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_189": ClinicalConcept_18(
        concept_id="CONCEPT_18_189",
        loinc_num="28189-0",
        snomed_ct="101800189",
        component="Diagnostic Analyte Component 18-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_190": ClinicalConcept_18(
        concept_id="CONCEPT_18_190",
        loinc_num="28190-1",
        snomed_ct="101800190",
        component="Diagnostic Analyte Component 18-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_191": ClinicalConcept_18(
        concept_id="CONCEPT_18_191",
        loinc_num="28191-2",
        snomed_ct="101800191",
        component="Diagnostic Analyte Component 18-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_192": ClinicalConcept_18(
        concept_id="CONCEPT_18_192",
        loinc_num="28192-3",
        snomed_ct="101800192",
        component="Diagnostic Analyte Component 18-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_193": ClinicalConcept_18(
        concept_id="CONCEPT_18_193",
        loinc_num="28193-4",
        snomed_ct="101800193",
        component="Diagnostic Analyte Component 18-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_194": ClinicalConcept_18(
        concept_id="CONCEPT_18_194",
        loinc_num="28194-5",
        snomed_ct="101800194",
        component="Diagnostic Analyte Component 18-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_195": ClinicalConcept_18(
        concept_id="CONCEPT_18_195",
        loinc_num="28195-6",
        snomed_ct="101800195",
        component="Diagnostic Analyte Component 18-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_196": ClinicalConcept_18(
        concept_id="CONCEPT_18_196",
        loinc_num="28196-7",
        snomed_ct="101800196",
        component="Diagnostic Analyte Component 18-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_197": ClinicalConcept_18(
        concept_id="CONCEPT_18_197",
        loinc_num="28197-8",
        snomed_ct="101800197",
        component="Diagnostic Analyte Component 18-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_198": ClinicalConcept_18(
        concept_id="CONCEPT_18_198",
        loinc_num="28198-0",
        snomed_ct="101800198",
        component="Diagnostic Analyte Component 18-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_18_199": ClinicalConcept_18(
        concept_id="CONCEPT_18_199",
        loinc_num="28199-1",
        snomed_ct="101800199",
        component="Diagnostic Analyte Component 18-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
