"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 25"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_25:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_25 = {
    "CONCEPT_25_001": ClinicalConcept_25(
        concept_id="CONCEPT_25_001",
        loinc_num="35001-1",
        snomed_ct="102500001",
        component="Diagnostic Analyte Component 25-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_002": ClinicalConcept_25(
        concept_id="CONCEPT_25_002",
        loinc_num="35002-2",
        snomed_ct="102500002",
        component="Diagnostic Analyte Component 25-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_003": ClinicalConcept_25(
        concept_id="CONCEPT_25_003",
        loinc_num="35003-3",
        snomed_ct="102500003",
        component="Diagnostic Analyte Component 25-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_004": ClinicalConcept_25(
        concept_id="CONCEPT_25_004",
        loinc_num="35004-4",
        snomed_ct="102500004",
        component="Diagnostic Analyte Component 25-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_005": ClinicalConcept_25(
        concept_id="CONCEPT_25_005",
        loinc_num="35005-5",
        snomed_ct="102500005",
        component="Diagnostic Analyte Component 25-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_006": ClinicalConcept_25(
        concept_id="CONCEPT_25_006",
        loinc_num="35006-6",
        snomed_ct="102500006",
        component="Diagnostic Analyte Component 25-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_007": ClinicalConcept_25(
        concept_id="CONCEPT_25_007",
        loinc_num="35007-7",
        snomed_ct="102500007",
        component="Diagnostic Analyte Component 25-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_008": ClinicalConcept_25(
        concept_id="CONCEPT_25_008",
        loinc_num="35008-8",
        snomed_ct="102500008",
        component="Diagnostic Analyte Component 25-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_009": ClinicalConcept_25(
        concept_id="CONCEPT_25_009",
        loinc_num="35009-0",
        snomed_ct="102500009",
        component="Diagnostic Analyte Component 25-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_010": ClinicalConcept_25(
        concept_id="CONCEPT_25_010",
        loinc_num="35010-1",
        snomed_ct="102500010",
        component="Diagnostic Analyte Component 25-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_011": ClinicalConcept_25(
        concept_id="CONCEPT_25_011",
        loinc_num="35011-2",
        snomed_ct="102500011",
        component="Diagnostic Analyte Component 25-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_012": ClinicalConcept_25(
        concept_id="CONCEPT_25_012",
        loinc_num="35012-3",
        snomed_ct="102500012",
        component="Diagnostic Analyte Component 25-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_013": ClinicalConcept_25(
        concept_id="CONCEPT_25_013",
        loinc_num="35013-4",
        snomed_ct="102500013",
        component="Diagnostic Analyte Component 25-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_014": ClinicalConcept_25(
        concept_id="CONCEPT_25_014",
        loinc_num="35014-5",
        snomed_ct="102500014",
        component="Diagnostic Analyte Component 25-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_015": ClinicalConcept_25(
        concept_id="CONCEPT_25_015",
        loinc_num="35015-6",
        snomed_ct="102500015",
        component="Diagnostic Analyte Component 25-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_016": ClinicalConcept_25(
        concept_id="CONCEPT_25_016",
        loinc_num="35016-7",
        snomed_ct="102500016",
        component="Diagnostic Analyte Component 25-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_017": ClinicalConcept_25(
        concept_id="CONCEPT_25_017",
        loinc_num="35017-8",
        snomed_ct="102500017",
        component="Diagnostic Analyte Component 25-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_018": ClinicalConcept_25(
        concept_id="CONCEPT_25_018",
        loinc_num="35018-0",
        snomed_ct="102500018",
        component="Diagnostic Analyte Component 25-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_019": ClinicalConcept_25(
        concept_id="CONCEPT_25_019",
        loinc_num="35019-1",
        snomed_ct="102500019",
        component="Diagnostic Analyte Component 25-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_020": ClinicalConcept_25(
        concept_id="CONCEPT_25_020",
        loinc_num="35020-2",
        snomed_ct="102500020",
        component="Diagnostic Analyte Component 25-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_021": ClinicalConcept_25(
        concept_id="CONCEPT_25_021",
        loinc_num="35021-3",
        snomed_ct="102500021",
        component="Diagnostic Analyte Component 25-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_022": ClinicalConcept_25(
        concept_id="CONCEPT_25_022",
        loinc_num="35022-4",
        snomed_ct="102500022",
        component="Diagnostic Analyte Component 25-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_023": ClinicalConcept_25(
        concept_id="CONCEPT_25_023",
        loinc_num="35023-5",
        snomed_ct="102500023",
        component="Diagnostic Analyte Component 25-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_024": ClinicalConcept_25(
        concept_id="CONCEPT_25_024",
        loinc_num="35024-6",
        snomed_ct="102500024",
        component="Diagnostic Analyte Component 25-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_025": ClinicalConcept_25(
        concept_id="CONCEPT_25_025",
        loinc_num="35025-7",
        snomed_ct="102500025",
        component="Diagnostic Analyte Component 25-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_026": ClinicalConcept_25(
        concept_id="CONCEPT_25_026",
        loinc_num="35026-8",
        snomed_ct="102500026",
        component="Diagnostic Analyte Component 25-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_027": ClinicalConcept_25(
        concept_id="CONCEPT_25_027",
        loinc_num="35027-0",
        snomed_ct="102500027",
        component="Diagnostic Analyte Component 25-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_028": ClinicalConcept_25(
        concept_id="CONCEPT_25_028",
        loinc_num="35028-1",
        snomed_ct="102500028",
        component="Diagnostic Analyte Component 25-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_029": ClinicalConcept_25(
        concept_id="CONCEPT_25_029",
        loinc_num="35029-2",
        snomed_ct="102500029",
        component="Diagnostic Analyte Component 25-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_030": ClinicalConcept_25(
        concept_id="CONCEPT_25_030",
        loinc_num="35030-3",
        snomed_ct="102500030",
        component="Diagnostic Analyte Component 25-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_031": ClinicalConcept_25(
        concept_id="CONCEPT_25_031",
        loinc_num="35031-4",
        snomed_ct="102500031",
        component="Diagnostic Analyte Component 25-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_032": ClinicalConcept_25(
        concept_id="CONCEPT_25_032",
        loinc_num="35032-5",
        snomed_ct="102500032",
        component="Diagnostic Analyte Component 25-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_033": ClinicalConcept_25(
        concept_id="CONCEPT_25_033",
        loinc_num="35033-6",
        snomed_ct="102500033",
        component="Diagnostic Analyte Component 25-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_034": ClinicalConcept_25(
        concept_id="CONCEPT_25_034",
        loinc_num="35034-7",
        snomed_ct="102500034",
        component="Diagnostic Analyte Component 25-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_035": ClinicalConcept_25(
        concept_id="CONCEPT_25_035",
        loinc_num="35035-8",
        snomed_ct="102500035",
        component="Diagnostic Analyte Component 25-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_036": ClinicalConcept_25(
        concept_id="CONCEPT_25_036",
        loinc_num="35036-0",
        snomed_ct="102500036",
        component="Diagnostic Analyte Component 25-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_037": ClinicalConcept_25(
        concept_id="CONCEPT_25_037",
        loinc_num="35037-1",
        snomed_ct="102500037",
        component="Diagnostic Analyte Component 25-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_038": ClinicalConcept_25(
        concept_id="CONCEPT_25_038",
        loinc_num="35038-2",
        snomed_ct="102500038",
        component="Diagnostic Analyte Component 25-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_039": ClinicalConcept_25(
        concept_id="CONCEPT_25_039",
        loinc_num="35039-3",
        snomed_ct="102500039",
        component="Diagnostic Analyte Component 25-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_040": ClinicalConcept_25(
        concept_id="CONCEPT_25_040",
        loinc_num="35040-4",
        snomed_ct="102500040",
        component="Diagnostic Analyte Component 25-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_041": ClinicalConcept_25(
        concept_id="CONCEPT_25_041",
        loinc_num="35041-5",
        snomed_ct="102500041",
        component="Diagnostic Analyte Component 25-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_042": ClinicalConcept_25(
        concept_id="CONCEPT_25_042",
        loinc_num="35042-6",
        snomed_ct="102500042",
        component="Diagnostic Analyte Component 25-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_043": ClinicalConcept_25(
        concept_id="CONCEPT_25_043",
        loinc_num="35043-7",
        snomed_ct="102500043",
        component="Diagnostic Analyte Component 25-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_044": ClinicalConcept_25(
        concept_id="CONCEPT_25_044",
        loinc_num="35044-8",
        snomed_ct="102500044",
        component="Diagnostic Analyte Component 25-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_045": ClinicalConcept_25(
        concept_id="CONCEPT_25_045",
        loinc_num="35045-0",
        snomed_ct="102500045",
        component="Diagnostic Analyte Component 25-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_046": ClinicalConcept_25(
        concept_id="CONCEPT_25_046",
        loinc_num="35046-1",
        snomed_ct="102500046",
        component="Diagnostic Analyte Component 25-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_047": ClinicalConcept_25(
        concept_id="CONCEPT_25_047",
        loinc_num="35047-2",
        snomed_ct="102500047",
        component="Diagnostic Analyte Component 25-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_048": ClinicalConcept_25(
        concept_id="CONCEPT_25_048",
        loinc_num="35048-3",
        snomed_ct="102500048",
        component="Diagnostic Analyte Component 25-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_049": ClinicalConcept_25(
        concept_id="CONCEPT_25_049",
        loinc_num="35049-4",
        snomed_ct="102500049",
        component="Diagnostic Analyte Component 25-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_050": ClinicalConcept_25(
        concept_id="CONCEPT_25_050",
        loinc_num="35050-5",
        snomed_ct="102500050",
        component="Diagnostic Analyte Component 25-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_051": ClinicalConcept_25(
        concept_id="CONCEPT_25_051",
        loinc_num="35051-6",
        snomed_ct="102500051",
        component="Diagnostic Analyte Component 25-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_052": ClinicalConcept_25(
        concept_id="CONCEPT_25_052",
        loinc_num="35052-7",
        snomed_ct="102500052",
        component="Diagnostic Analyte Component 25-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_053": ClinicalConcept_25(
        concept_id="CONCEPT_25_053",
        loinc_num="35053-8",
        snomed_ct="102500053",
        component="Diagnostic Analyte Component 25-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_054": ClinicalConcept_25(
        concept_id="CONCEPT_25_054",
        loinc_num="35054-0",
        snomed_ct="102500054",
        component="Diagnostic Analyte Component 25-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_055": ClinicalConcept_25(
        concept_id="CONCEPT_25_055",
        loinc_num="35055-1",
        snomed_ct="102500055",
        component="Diagnostic Analyte Component 25-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_056": ClinicalConcept_25(
        concept_id="CONCEPT_25_056",
        loinc_num="35056-2",
        snomed_ct="102500056",
        component="Diagnostic Analyte Component 25-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_057": ClinicalConcept_25(
        concept_id="CONCEPT_25_057",
        loinc_num="35057-3",
        snomed_ct="102500057",
        component="Diagnostic Analyte Component 25-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_058": ClinicalConcept_25(
        concept_id="CONCEPT_25_058",
        loinc_num="35058-4",
        snomed_ct="102500058",
        component="Diagnostic Analyte Component 25-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_059": ClinicalConcept_25(
        concept_id="CONCEPT_25_059",
        loinc_num="35059-5",
        snomed_ct="102500059",
        component="Diagnostic Analyte Component 25-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_060": ClinicalConcept_25(
        concept_id="CONCEPT_25_060",
        loinc_num="35060-6",
        snomed_ct="102500060",
        component="Diagnostic Analyte Component 25-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_061": ClinicalConcept_25(
        concept_id="CONCEPT_25_061",
        loinc_num="35061-7",
        snomed_ct="102500061",
        component="Diagnostic Analyte Component 25-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_062": ClinicalConcept_25(
        concept_id="CONCEPT_25_062",
        loinc_num="35062-8",
        snomed_ct="102500062",
        component="Diagnostic Analyte Component 25-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_063": ClinicalConcept_25(
        concept_id="CONCEPT_25_063",
        loinc_num="35063-0",
        snomed_ct="102500063",
        component="Diagnostic Analyte Component 25-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_064": ClinicalConcept_25(
        concept_id="CONCEPT_25_064",
        loinc_num="35064-1",
        snomed_ct="102500064",
        component="Diagnostic Analyte Component 25-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_065": ClinicalConcept_25(
        concept_id="CONCEPT_25_065",
        loinc_num="35065-2",
        snomed_ct="102500065",
        component="Diagnostic Analyte Component 25-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_066": ClinicalConcept_25(
        concept_id="CONCEPT_25_066",
        loinc_num="35066-3",
        snomed_ct="102500066",
        component="Diagnostic Analyte Component 25-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_067": ClinicalConcept_25(
        concept_id="CONCEPT_25_067",
        loinc_num="35067-4",
        snomed_ct="102500067",
        component="Diagnostic Analyte Component 25-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_068": ClinicalConcept_25(
        concept_id="CONCEPT_25_068",
        loinc_num="35068-5",
        snomed_ct="102500068",
        component="Diagnostic Analyte Component 25-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_069": ClinicalConcept_25(
        concept_id="CONCEPT_25_069",
        loinc_num="35069-6",
        snomed_ct="102500069",
        component="Diagnostic Analyte Component 25-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_070": ClinicalConcept_25(
        concept_id="CONCEPT_25_070",
        loinc_num="35070-7",
        snomed_ct="102500070",
        component="Diagnostic Analyte Component 25-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_071": ClinicalConcept_25(
        concept_id="CONCEPT_25_071",
        loinc_num="35071-8",
        snomed_ct="102500071",
        component="Diagnostic Analyte Component 25-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_072": ClinicalConcept_25(
        concept_id="CONCEPT_25_072",
        loinc_num="35072-0",
        snomed_ct="102500072",
        component="Diagnostic Analyte Component 25-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_073": ClinicalConcept_25(
        concept_id="CONCEPT_25_073",
        loinc_num="35073-1",
        snomed_ct="102500073",
        component="Diagnostic Analyte Component 25-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_074": ClinicalConcept_25(
        concept_id="CONCEPT_25_074",
        loinc_num="35074-2",
        snomed_ct="102500074",
        component="Diagnostic Analyte Component 25-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_075": ClinicalConcept_25(
        concept_id="CONCEPT_25_075",
        loinc_num="35075-3",
        snomed_ct="102500075",
        component="Diagnostic Analyte Component 25-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_076": ClinicalConcept_25(
        concept_id="CONCEPT_25_076",
        loinc_num="35076-4",
        snomed_ct="102500076",
        component="Diagnostic Analyte Component 25-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_077": ClinicalConcept_25(
        concept_id="CONCEPT_25_077",
        loinc_num="35077-5",
        snomed_ct="102500077",
        component="Diagnostic Analyte Component 25-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_078": ClinicalConcept_25(
        concept_id="CONCEPT_25_078",
        loinc_num="35078-6",
        snomed_ct="102500078",
        component="Diagnostic Analyte Component 25-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_079": ClinicalConcept_25(
        concept_id="CONCEPT_25_079",
        loinc_num="35079-7",
        snomed_ct="102500079",
        component="Diagnostic Analyte Component 25-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_080": ClinicalConcept_25(
        concept_id="CONCEPT_25_080",
        loinc_num="35080-8",
        snomed_ct="102500080",
        component="Diagnostic Analyte Component 25-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_081": ClinicalConcept_25(
        concept_id="CONCEPT_25_081",
        loinc_num="35081-0",
        snomed_ct="102500081",
        component="Diagnostic Analyte Component 25-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_082": ClinicalConcept_25(
        concept_id="CONCEPT_25_082",
        loinc_num="35082-1",
        snomed_ct="102500082",
        component="Diagnostic Analyte Component 25-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_083": ClinicalConcept_25(
        concept_id="CONCEPT_25_083",
        loinc_num="35083-2",
        snomed_ct="102500083",
        component="Diagnostic Analyte Component 25-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_084": ClinicalConcept_25(
        concept_id="CONCEPT_25_084",
        loinc_num="35084-3",
        snomed_ct="102500084",
        component="Diagnostic Analyte Component 25-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_085": ClinicalConcept_25(
        concept_id="CONCEPT_25_085",
        loinc_num="35085-4",
        snomed_ct="102500085",
        component="Diagnostic Analyte Component 25-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_086": ClinicalConcept_25(
        concept_id="CONCEPT_25_086",
        loinc_num="35086-5",
        snomed_ct="102500086",
        component="Diagnostic Analyte Component 25-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_087": ClinicalConcept_25(
        concept_id="CONCEPT_25_087",
        loinc_num="35087-6",
        snomed_ct="102500087",
        component="Diagnostic Analyte Component 25-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_088": ClinicalConcept_25(
        concept_id="CONCEPT_25_088",
        loinc_num="35088-7",
        snomed_ct="102500088",
        component="Diagnostic Analyte Component 25-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_089": ClinicalConcept_25(
        concept_id="CONCEPT_25_089",
        loinc_num="35089-8",
        snomed_ct="102500089",
        component="Diagnostic Analyte Component 25-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_090": ClinicalConcept_25(
        concept_id="CONCEPT_25_090",
        loinc_num="35090-0",
        snomed_ct="102500090",
        component="Diagnostic Analyte Component 25-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_091": ClinicalConcept_25(
        concept_id="CONCEPT_25_091",
        loinc_num="35091-1",
        snomed_ct="102500091",
        component="Diagnostic Analyte Component 25-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_092": ClinicalConcept_25(
        concept_id="CONCEPT_25_092",
        loinc_num="35092-2",
        snomed_ct="102500092",
        component="Diagnostic Analyte Component 25-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_093": ClinicalConcept_25(
        concept_id="CONCEPT_25_093",
        loinc_num="35093-3",
        snomed_ct="102500093",
        component="Diagnostic Analyte Component 25-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_094": ClinicalConcept_25(
        concept_id="CONCEPT_25_094",
        loinc_num="35094-4",
        snomed_ct="102500094",
        component="Diagnostic Analyte Component 25-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_095": ClinicalConcept_25(
        concept_id="CONCEPT_25_095",
        loinc_num="35095-5",
        snomed_ct="102500095",
        component="Diagnostic Analyte Component 25-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_096": ClinicalConcept_25(
        concept_id="CONCEPT_25_096",
        loinc_num="35096-6",
        snomed_ct="102500096",
        component="Diagnostic Analyte Component 25-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_097": ClinicalConcept_25(
        concept_id="CONCEPT_25_097",
        loinc_num="35097-7",
        snomed_ct="102500097",
        component="Diagnostic Analyte Component 25-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_098": ClinicalConcept_25(
        concept_id="CONCEPT_25_098",
        loinc_num="35098-8",
        snomed_ct="102500098",
        component="Diagnostic Analyte Component 25-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_099": ClinicalConcept_25(
        concept_id="CONCEPT_25_099",
        loinc_num="35099-0",
        snomed_ct="102500099",
        component="Diagnostic Analyte Component 25-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_100": ClinicalConcept_25(
        concept_id="CONCEPT_25_100",
        loinc_num="35100-1",
        snomed_ct="102500100",
        component="Diagnostic Analyte Component 25-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_101": ClinicalConcept_25(
        concept_id="CONCEPT_25_101",
        loinc_num="35101-2",
        snomed_ct="102500101",
        component="Diagnostic Analyte Component 25-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_102": ClinicalConcept_25(
        concept_id="CONCEPT_25_102",
        loinc_num="35102-3",
        snomed_ct="102500102",
        component="Diagnostic Analyte Component 25-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_103": ClinicalConcept_25(
        concept_id="CONCEPT_25_103",
        loinc_num="35103-4",
        snomed_ct="102500103",
        component="Diagnostic Analyte Component 25-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_104": ClinicalConcept_25(
        concept_id="CONCEPT_25_104",
        loinc_num="35104-5",
        snomed_ct="102500104",
        component="Diagnostic Analyte Component 25-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_105": ClinicalConcept_25(
        concept_id="CONCEPT_25_105",
        loinc_num="35105-6",
        snomed_ct="102500105",
        component="Diagnostic Analyte Component 25-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_106": ClinicalConcept_25(
        concept_id="CONCEPT_25_106",
        loinc_num="35106-7",
        snomed_ct="102500106",
        component="Diagnostic Analyte Component 25-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_107": ClinicalConcept_25(
        concept_id="CONCEPT_25_107",
        loinc_num="35107-8",
        snomed_ct="102500107",
        component="Diagnostic Analyte Component 25-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_108": ClinicalConcept_25(
        concept_id="CONCEPT_25_108",
        loinc_num="35108-0",
        snomed_ct="102500108",
        component="Diagnostic Analyte Component 25-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_109": ClinicalConcept_25(
        concept_id="CONCEPT_25_109",
        loinc_num="35109-1",
        snomed_ct="102500109",
        component="Diagnostic Analyte Component 25-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_110": ClinicalConcept_25(
        concept_id="CONCEPT_25_110",
        loinc_num="35110-2",
        snomed_ct="102500110",
        component="Diagnostic Analyte Component 25-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_111": ClinicalConcept_25(
        concept_id="CONCEPT_25_111",
        loinc_num="35111-3",
        snomed_ct="102500111",
        component="Diagnostic Analyte Component 25-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_112": ClinicalConcept_25(
        concept_id="CONCEPT_25_112",
        loinc_num="35112-4",
        snomed_ct="102500112",
        component="Diagnostic Analyte Component 25-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_113": ClinicalConcept_25(
        concept_id="CONCEPT_25_113",
        loinc_num="35113-5",
        snomed_ct="102500113",
        component="Diagnostic Analyte Component 25-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_114": ClinicalConcept_25(
        concept_id="CONCEPT_25_114",
        loinc_num="35114-6",
        snomed_ct="102500114",
        component="Diagnostic Analyte Component 25-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_115": ClinicalConcept_25(
        concept_id="CONCEPT_25_115",
        loinc_num="35115-7",
        snomed_ct="102500115",
        component="Diagnostic Analyte Component 25-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_116": ClinicalConcept_25(
        concept_id="CONCEPT_25_116",
        loinc_num="35116-8",
        snomed_ct="102500116",
        component="Diagnostic Analyte Component 25-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_117": ClinicalConcept_25(
        concept_id="CONCEPT_25_117",
        loinc_num="35117-0",
        snomed_ct="102500117",
        component="Diagnostic Analyte Component 25-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_118": ClinicalConcept_25(
        concept_id="CONCEPT_25_118",
        loinc_num="35118-1",
        snomed_ct="102500118",
        component="Diagnostic Analyte Component 25-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_119": ClinicalConcept_25(
        concept_id="CONCEPT_25_119",
        loinc_num="35119-2",
        snomed_ct="102500119",
        component="Diagnostic Analyte Component 25-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_120": ClinicalConcept_25(
        concept_id="CONCEPT_25_120",
        loinc_num="35120-3",
        snomed_ct="102500120",
        component="Diagnostic Analyte Component 25-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_121": ClinicalConcept_25(
        concept_id="CONCEPT_25_121",
        loinc_num="35121-4",
        snomed_ct="102500121",
        component="Diagnostic Analyte Component 25-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_122": ClinicalConcept_25(
        concept_id="CONCEPT_25_122",
        loinc_num="35122-5",
        snomed_ct="102500122",
        component="Diagnostic Analyte Component 25-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_123": ClinicalConcept_25(
        concept_id="CONCEPT_25_123",
        loinc_num="35123-6",
        snomed_ct="102500123",
        component="Diagnostic Analyte Component 25-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_124": ClinicalConcept_25(
        concept_id="CONCEPT_25_124",
        loinc_num="35124-7",
        snomed_ct="102500124",
        component="Diagnostic Analyte Component 25-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_125": ClinicalConcept_25(
        concept_id="CONCEPT_25_125",
        loinc_num="35125-8",
        snomed_ct="102500125",
        component="Diagnostic Analyte Component 25-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_126": ClinicalConcept_25(
        concept_id="CONCEPT_25_126",
        loinc_num="35126-0",
        snomed_ct="102500126",
        component="Diagnostic Analyte Component 25-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_127": ClinicalConcept_25(
        concept_id="CONCEPT_25_127",
        loinc_num="35127-1",
        snomed_ct="102500127",
        component="Diagnostic Analyte Component 25-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_128": ClinicalConcept_25(
        concept_id="CONCEPT_25_128",
        loinc_num="35128-2",
        snomed_ct="102500128",
        component="Diagnostic Analyte Component 25-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_129": ClinicalConcept_25(
        concept_id="CONCEPT_25_129",
        loinc_num="35129-3",
        snomed_ct="102500129",
        component="Diagnostic Analyte Component 25-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_130": ClinicalConcept_25(
        concept_id="CONCEPT_25_130",
        loinc_num="35130-4",
        snomed_ct="102500130",
        component="Diagnostic Analyte Component 25-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_131": ClinicalConcept_25(
        concept_id="CONCEPT_25_131",
        loinc_num="35131-5",
        snomed_ct="102500131",
        component="Diagnostic Analyte Component 25-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_132": ClinicalConcept_25(
        concept_id="CONCEPT_25_132",
        loinc_num="35132-6",
        snomed_ct="102500132",
        component="Diagnostic Analyte Component 25-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_133": ClinicalConcept_25(
        concept_id="CONCEPT_25_133",
        loinc_num="35133-7",
        snomed_ct="102500133",
        component="Diagnostic Analyte Component 25-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_134": ClinicalConcept_25(
        concept_id="CONCEPT_25_134",
        loinc_num="35134-8",
        snomed_ct="102500134",
        component="Diagnostic Analyte Component 25-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_135": ClinicalConcept_25(
        concept_id="CONCEPT_25_135",
        loinc_num="35135-0",
        snomed_ct="102500135",
        component="Diagnostic Analyte Component 25-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_136": ClinicalConcept_25(
        concept_id="CONCEPT_25_136",
        loinc_num="35136-1",
        snomed_ct="102500136",
        component="Diagnostic Analyte Component 25-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_137": ClinicalConcept_25(
        concept_id="CONCEPT_25_137",
        loinc_num="35137-2",
        snomed_ct="102500137",
        component="Diagnostic Analyte Component 25-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_138": ClinicalConcept_25(
        concept_id="CONCEPT_25_138",
        loinc_num="35138-3",
        snomed_ct="102500138",
        component="Diagnostic Analyte Component 25-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_139": ClinicalConcept_25(
        concept_id="CONCEPT_25_139",
        loinc_num="35139-4",
        snomed_ct="102500139",
        component="Diagnostic Analyte Component 25-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_140": ClinicalConcept_25(
        concept_id="CONCEPT_25_140",
        loinc_num="35140-5",
        snomed_ct="102500140",
        component="Diagnostic Analyte Component 25-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_141": ClinicalConcept_25(
        concept_id="CONCEPT_25_141",
        loinc_num="35141-6",
        snomed_ct="102500141",
        component="Diagnostic Analyte Component 25-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_142": ClinicalConcept_25(
        concept_id="CONCEPT_25_142",
        loinc_num="35142-7",
        snomed_ct="102500142",
        component="Diagnostic Analyte Component 25-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_143": ClinicalConcept_25(
        concept_id="CONCEPT_25_143",
        loinc_num="35143-8",
        snomed_ct="102500143",
        component="Diagnostic Analyte Component 25-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_144": ClinicalConcept_25(
        concept_id="CONCEPT_25_144",
        loinc_num="35144-0",
        snomed_ct="102500144",
        component="Diagnostic Analyte Component 25-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_145": ClinicalConcept_25(
        concept_id="CONCEPT_25_145",
        loinc_num="35145-1",
        snomed_ct="102500145",
        component="Diagnostic Analyte Component 25-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_146": ClinicalConcept_25(
        concept_id="CONCEPT_25_146",
        loinc_num="35146-2",
        snomed_ct="102500146",
        component="Diagnostic Analyte Component 25-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_147": ClinicalConcept_25(
        concept_id="CONCEPT_25_147",
        loinc_num="35147-3",
        snomed_ct="102500147",
        component="Diagnostic Analyte Component 25-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_148": ClinicalConcept_25(
        concept_id="CONCEPT_25_148",
        loinc_num="35148-4",
        snomed_ct="102500148",
        component="Diagnostic Analyte Component 25-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_149": ClinicalConcept_25(
        concept_id="CONCEPT_25_149",
        loinc_num="35149-5",
        snomed_ct="102500149",
        component="Diagnostic Analyte Component 25-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_150": ClinicalConcept_25(
        concept_id="CONCEPT_25_150",
        loinc_num="35150-6",
        snomed_ct="102500150",
        component="Diagnostic Analyte Component 25-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_151": ClinicalConcept_25(
        concept_id="CONCEPT_25_151",
        loinc_num="35151-7",
        snomed_ct="102500151",
        component="Diagnostic Analyte Component 25-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_152": ClinicalConcept_25(
        concept_id="CONCEPT_25_152",
        loinc_num="35152-8",
        snomed_ct="102500152",
        component="Diagnostic Analyte Component 25-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_153": ClinicalConcept_25(
        concept_id="CONCEPT_25_153",
        loinc_num="35153-0",
        snomed_ct="102500153",
        component="Diagnostic Analyte Component 25-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_154": ClinicalConcept_25(
        concept_id="CONCEPT_25_154",
        loinc_num="35154-1",
        snomed_ct="102500154",
        component="Diagnostic Analyte Component 25-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_155": ClinicalConcept_25(
        concept_id="CONCEPT_25_155",
        loinc_num="35155-2",
        snomed_ct="102500155",
        component="Diagnostic Analyte Component 25-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_156": ClinicalConcept_25(
        concept_id="CONCEPT_25_156",
        loinc_num="35156-3",
        snomed_ct="102500156",
        component="Diagnostic Analyte Component 25-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_157": ClinicalConcept_25(
        concept_id="CONCEPT_25_157",
        loinc_num="35157-4",
        snomed_ct="102500157",
        component="Diagnostic Analyte Component 25-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_158": ClinicalConcept_25(
        concept_id="CONCEPT_25_158",
        loinc_num="35158-5",
        snomed_ct="102500158",
        component="Diagnostic Analyte Component 25-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_159": ClinicalConcept_25(
        concept_id="CONCEPT_25_159",
        loinc_num="35159-6",
        snomed_ct="102500159",
        component="Diagnostic Analyte Component 25-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_160": ClinicalConcept_25(
        concept_id="CONCEPT_25_160",
        loinc_num="35160-7",
        snomed_ct="102500160",
        component="Diagnostic Analyte Component 25-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_161": ClinicalConcept_25(
        concept_id="CONCEPT_25_161",
        loinc_num="35161-8",
        snomed_ct="102500161",
        component="Diagnostic Analyte Component 25-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_162": ClinicalConcept_25(
        concept_id="CONCEPT_25_162",
        loinc_num="35162-0",
        snomed_ct="102500162",
        component="Diagnostic Analyte Component 25-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_163": ClinicalConcept_25(
        concept_id="CONCEPT_25_163",
        loinc_num="35163-1",
        snomed_ct="102500163",
        component="Diagnostic Analyte Component 25-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_164": ClinicalConcept_25(
        concept_id="CONCEPT_25_164",
        loinc_num="35164-2",
        snomed_ct="102500164",
        component="Diagnostic Analyte Component 25-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_165": ClinicalConcept_25(
        concept_id="CONCEPT_25_165",
        loinc_num="35165-3",
        snomed_ct="102500165",
        component="Diagnostic Analyte Component 25-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_166": ClinicalConcept_25(
        concept_id="CONCEPT_25_166",
        loinc_num="35166-4",
        snomed_ct="102500166",
        component="Diagnostic Analyte Component 25-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_167": ClinicalConcept_25(
        concept_id="CONCEPT_25_167",
        loinc_num="35167-5",
        snomed_ct="102500167",
        component="Diagnostic Analyte Component 25-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_168": ClinicalConcept_25(
        concept_id="CONCEPT_25_168",
        loinc_num="35168-6",
        snomed_ct="102500168",
        component="Diagnostic Analyte Component 25-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_169": ClinicalConcept_25(
        concept_id="CONCEPT_25_169",
        loinc_num="35169-7",
        snomed_ct="102500169",
        component="Diagnostic Analyte Component 25-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_170": ClinicalConcept_25(
        concept_id="CONCEPT_25_170",
        loinc_num="35170-8",
        snomed_ct="102500170",
        component="Diagnostic Analyte Component 25-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_171": ClinicalConcept_25(
        concept_id="CONCEPT_25_171",
        loinc_num="35171-0",
        snomed_ct="102500171",
        component="Diagnostic Analyte Component 25-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_172": ClinicalConcept_25(
        concept_id="CONCEPT_25_172",
        loinc_num="35172-1",
        snomed_ct="102500172",
        component="Diagnostic Analyte Component 25-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_173": ClinicalConcept_25(
        concept_id="CONCEPT_25_173",
        loinc_num="35173-2",
        snomed_ct="102500173",
        component="Diagnostic Analyte Component 25-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_174": ClinicalConcept_25(
        concept_id="CONCEPT_25_174",
        loinc_num="35174-3",
        snomed_ct="102500174",
        component="Diagnostic Analyte Component 25-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_175": ClinicalConcept_25(
        concept_id="CONCEPT_25_175",
        loinc_num="35175-4",
        snomed_ct="102500175",
        component="Diagnostic Analyte Component 25-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_176": ClinicalConcept_25(
        concept_id="CONCEPT_25_176",
        loinc_num="35176-5",
        snomed_ct="102500176",
        component="Diagnostic Analyte Component 25-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_177": ClinicalConcept_25(
        concept_id="CONCEPT_25_177",
        loinc_num="35177-6",
        snomed_ct="102500177",
        component="Diagnostic Analyte Component 25-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_178": ClinicalConcept_25(
        concept_id="CONCEPT_25_178",
        loinc_num="35178-7",
        snomed_ct="102500178",
        component="Diagnostic Analyte Component 25-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_179": ClinicalConcept_25(
        concept_id="CONCEPT_25_179",
        loinc_num="35179-8",
        snomed_ct="102500179",
        component="Diagnostic Analyte Component 25-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_180": ClinicalConcept_25(
        concept_id="CONCEPT_25_180",
        loinc_num="35180-0",
        snomed_ct="102500180",
        component="Diagnostic Analyte Component 25-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_181": ClinicalConcept_25(
        concept_id="CONCEPT_25_181",
        loinc_num="35181-1",
        snomed_ct="102500181",
        component="Diagnostic Analyte Component 25-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_182": ClinicalConcept_25(
        concept_id="CONCEPT_25_182",
        loinc_num="35182-2",
        snomed_ct="102500182",
        component="Diagnostic Analyte Component 25-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_183": ClinicalConcept_25(
        concept_id="CONCEPT_25_183",
        loinc_num="35183-3",
        snomed_ct="102500183",
        component="Diagnostic Analyte Component 25-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_184": ClinicalConcept_25(
        concept_id="CONCEPT_25_184",
        loinc_num="35184-4",
        snomed_ct="102500184",
        component="Diagnostic Analyte Component 25-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_185": ClinicalConcept_25(
        concept_id="CONCEPT_25_185",
        loinc_num="35185-5",
        snomed_ct="102500185",
        component="Diagnostic Analyte Component 25-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_186": ClinicalConcept_25(
        concept_id="CONCEPT_25_186",
        loinc_num="35186-6",
        snomed_ct="102500186",
        component="Diagnostic Analyte Component 25-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_187": ClinicalConcept_25(
        concept_id="CONCEPT_25_187",
        loinc_num="35187-7",
        snomed_ct="102500187",
        component="Diagnostic Analyte Component 25-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_188": ClinicalConcept_25(
        concept_id="CONCEPT_25_188",
        loinc_num="35188-8",
        snomed_ct="102500188",
        component="Diagnostic Analyte Component 25-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_189": ClinicalConcept_25(
        concept_id="CONCEPT_25_189",
        loinc_num="35189-0",
        snomed_ct="102500189",
        component="Diagnostic Analyte Component 25-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_190": ClinicalConcept_25(
        concept_id="CONCEPT_25_190",
        loinc_num="35190-1",
        snomed_ct="102500190",
        component="Diagnostic Analyte Component 25-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_191": ClinicalConcept_25(
        concept_id="CONCEPT_25_191",
        loinc_num="35191-2",
        snomed_ct="102500191",
        component="Diagnostic Analyte Component 25-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_192": ClinicalConcept_25(
        concept_id="CONCEPT_25_192",
        loinc_num="35192-3",
        snomed_ct="102500192",
        component="Diagnostic Analyte Component 25-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_193": ClinicalConcept_25(
        concept_id="CONCEPT_25_193",
        loinc_num="35193-4",
        snomed_ct="102500193",
        component="Diagnostic Analyte Component 25-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_194": ClinicalConcept_25(
        concept_id="CONCEPT_25_194",
        loinc_num="35194-5",
        snomed_ct="102500194",
        component="Diagnostic Analyte Component 25-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_195": ClinicalConcept_25(
        concept_id="CONCEPT_25_195",
        loinc_num="35195-6",
        snomed_ct="102500195",
        component="Diagnostic Analyte Component 25-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_196": ClinicalConcept_25(
        concept_id="CONCEPT_25_196",
        loinc_num="35196-7",
        snomed_ct="102500196",
        component="Diagnostic Analyte Component 25-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_197": ClinicalConcept_25(
        concept_id="CONCEPT_25_197",
        loinc_num="35197-8",
        snomed_ct="102500197",
        component="Diagnostic Analyte Component 25-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_198": ClinicalConcept_25(
        concept_id="CONCEPT_25_198",
        loinc_num="35198-0",
        snomed_ct="102500198",
        component="Diagnostic Analyte Component 25-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_25_199": ClinicalConcept_25(
        concept_id="CONCEPT_25_199",
        loinc_num="35199-1",
        snomed_ct="102500199",
        component="Diagnostic Analyte Component 25-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
