"""AcuPath Enterprise LIS - Master Clinical Laboratory Ontology Dictionary Matrix 22"""
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class ClinicalConcept_22:
    concept_id: str
    loinc_num: str
    snomed_ct: str
    component: str
    property_type: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: str
    class_type: str

CLINICAL_ONTOLOGY_MATRIX_22 = {
    "CONCEPT_22_001": ClinicalConcept_22(
        concept_id="CONCEPT_22_001",
        loinc_num="32001-1",
        snomed_ct="102200001",
        component="Diagnostic Analyte Component 22-001",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_002": ClinicalConcept_22(
        concept_id="CONCEPT_22_002",
        loinc_num="32002-2",
        snomed_ct="102200002",
        component="Diagnostic Analyte Component 22-002",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_003": ClinicalConcept_22(
        concept_id="CONCEPT_22_003",
        loinc_num="32003-3",
        snomed_ct="102200003",
        component="Diagnostic Analyte Component 22-003",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_004": ClinicalConcept_22(
        concept_id="CONCEPT_22_004",
        loinc_num="32004-4",
        snomed_ct="102200004",
        component="Diagnostic Analyte Component 22-004",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_005": ClinicalConcept_22(
        concept_id="CONCEPT_22_005",
        loinc_num="32005-5",
        snomed_ct="102200005",
        component="Diagnostic Analyte Component 22-005",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_006": ClinicalConcept_22(
        concept_id="CONCEPT_22_006",
        loinc_num="32006-6",
        snomed_ct="102200006",
        component="Diagnostic Analyte Component 22-006",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_007": ClinicalConcept_22(
        concept_id="CONCEPT_22_007",
        loinc_num="32007-7",
        snomed_ct="102200007",
        component="Diagnostic Analyte Component 22-007",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_008": ClinicalConcept_22(
        concept_id="CONCEPT_22_008",
        loinc_num="32008-8",
        snomed_ct="102200008",
        component="Diagnostic Analyte Component 22-008",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_009": ClinicalConcept_22(
        concept_id="CONCEPT_22_009",
        loinc_num="32009-0",
        snomed_ct="102200009",
        component="Diagnostic Analyte Component 22-009",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_010": ClinicalConcept_22(
        concept_id="CONCEPT_22_010",
        loinc_num="32010-1",
        snomed_ct="102200010",
        component="Diagnostic Analyte Component 22-010",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_011": ClinicalConcept_22(
        concept_id="CONCEPT_22_011",
        loinc_num="32011-2",
        snomed_ct="102200011",
        component="Diagnostic Analyte Component 22-011",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_012": ClinicalConcept_22(
        concept_id="CONCEPT_22_012",
        loinc_num="32012-3",
        snomed_ct="102200012",
        component="Diagnostic Analyte Component 22-012",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_013": ClinicalConcept_22(
        concept_id="CONCEPT_22_013",
        loinc_num="32013-4",
        snomed_ct="102200013",
        component="Diagnostic Analyte Component 22-013",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_014": ClinicalConcept_22(
        concept_id="CONCEPT_22_014",
        loinc_num="32014-5",
        snomed_ct="102200014",
        component="Diagnostic Analyte Component 22-014",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_015": ClinicalConcept_22(
        concept_id="CONCEPT_22_015",
        loinc_num="32015-6",
        snomed_ct="102200015",
        component="Diagnostic Analyte Component 22-015",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_016": ClinicalConcept_22(
        concept_id="CONCEPT_22_016",
        loinc_num="32016-7",
        snomed_ct="102200016",
        component="Diagnostic Analyte Component 22-016",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_017": ClinicalConcept_22(
        concept_id="CONCEPT_22_017",
        loinc_num="32017-8",
        snomed_ct="102200017",
        component="Diagnostic Analyte Component 22-017",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_018": ClinicalConcept_22(
        concept_id="CONCEPT_22_018",
        loinc_num="32018-0",
        snomed_ct="102200018",
        component="Diagnostic Analyte Component 22-018",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_019": ClinicalConcept_22(
        concept_id="CONCEPT_22_019",
        loinc_num="32019-1",
        snomed_ct="102200019",
        component="Diagnostic Analyte Component 22-019",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_020": ClinicalConcept_22(
        concept_id="CONCEPT_22_020",
        loinc_num="32020-2",
        snomed_ct="102200020",
        component="Diagnostic Analyte Component 22-020",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_021": ClinicalConcept_22(
        concept_id="CONCEPT_22_021",
        loinc_num="32021-3",
        snomed_ct="102200021",
        component="Diagnostic Analyte Component 22-021",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_022": ClinicalConcept_22(
        concept_id="CONCEPT_22_022",
        loinc_num="32022-4",
        snomed_ct="102200022",
        component="Diagnostic Analyte Component 22-022",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_023": ClinicalConcept_22(
        concept_id="CONCEPT_22_023",
        loinc_num="32023-5",
        snomed_ct="102200023",
        component="Diagnostic Analyte Component 22-023",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_024": ClinicalConcept_22(
        concept_id="CONCEPT_22_024",
        loinc_num="32024-6",
        snomed_ct="102200024",
        component="Diagnostic Analyte Component 22-024",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_025": ClinicalConcept_22(
        concept_id="CONCEPT_22_025",
        loinc_num="32025-7",
        snomed_ct="102200025",
        component="Diagnostic Analyte Component 22-025",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_026": ClinicalConcept_22(
        concept_id="CONCEPT_22_026",
        loinc_num="32026-8",
        snomed_ct="102200026",
        component="Diagnostic Analyte Component 22-026",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_027": ClinicalConcept_22(
        concept_id="CONCEPT_22_027",
        loinc_num="32027-0",
        snomed_ct="102200027",
        component="Diagnostic Analyte Component 22-027",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_028": ClinicalConcept_22(
        concept_id="CONCEPT_22_028",
        loinc_num="32028-1",
        snomed_ct="102200028",
        component="Diagnostic Analyte Component 22-028",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_029": ClinicalConcept_22(
        concept_id="CONCEPT_22_029",
        loinc_num="32029-2",
        snomed_ct="102200029",
        component="Diagnostic Analyte Component 22-029",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_030": ClinicalConcept_22(
        concept_id="CONCEPT_22_030",
        loinc_num="32030-3",
        snomed_ct="102200030",
        component="Diagnostic Analyte Component 22-030",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_031": ClinicalConcept_22(
        concept_id="CONCEPT_22_031",
        loinc_num="32031-4",
        snomed_ct="102200031",
        component="Diagnostic Analyte Component 22-031",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_032": ClinicalConcept_22(
        concept_id="CONCEPT_22_032",
        loinc_num="32032-5",
        snomed_ct="102200032",
        component="Diagnostic Analyte Component 22-032",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_033": ClinicalConcept_22(
        concept_id="CONCEPT_22_033",
        loinc_num="32033-6",
        snomed_ct="102200033",
        component="Diagnostic Analyte Component 22-033",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_034": ClinicalConcept_22(
        concept_id="CONCEPT_22_034",
        loinc_num="32034-7",
        snomed_ct="102200034",
        component="Diagnostic Analyte Component 22-034",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_035": ClinicalConcept_22(
        concept_id="CONCEPT_22_035",
        loinc_num="32035-8",
        snomed_ct="102200035",
        component="Diagnostic Analyte Component 22-035",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_036": ClinicalConcept_22(
        concept_id="CONCEPT_22_036",
        loinc_num="32036-0",
        snomed_ct="102200036",
        component="Diagnostic Analyte Component 22-036",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_037": ClinicalConcept_22(
        concept_id="CONCEPT_22_037",
        loinc_num="32037-1",
        snomed_ct="102200037",
        component="Diagnostic Analyte Component 22-037",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_038": ClinicalConcept_22(
        concept_id="CONCEPT_22_038",
        loinc_num="32038-2",
        snomed_ct="102200038",
        component="Diagnostic Analyte Component 22-038",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_039": ClinicalConcept_22(
        concept_id="CONCEPT_22_039",
        loinc_num="32039-3",
        snomed_ct="102200039",
        component="Diagnostic Analyte Component 22-039",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_040": ClinicalConcept_22(
        concept_id="CONCEPT_22_040",
        loinc_num="32040-4",
        snomed_ct="102200040",
        component="Diagnostic Analyte Component 22-040",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_041": ClinicalConcept_22(
        concept_id="CONCEPT_22_041",
        loinc_num="32041-5",
        snomed_ct="102200041",
        component="Diagnostic Analyte Component 22-041",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_042": ClinicalConcept_22(
        concept_id="CONCEPT_22_042",
        loinc_num="32042-6",
        snomed_ct="102200042",
        component="Diagnostic Analyte Component 22-042",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_043": ClinicalConcept_22(
        concept_id="CONCEPT_22_043",
        loinc_num="32043-7",
        snomed_ct="102200043",
        component="Diagnostic Analyte Component 22-043",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_044": ClinicalConcept_22(
        concept_id="CONCEPT_22_044",
        loinc_num="32044-8",
        snomed_ct="102200044",
        component="Diagnostic Analyte Component 22-044",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_045": ClinicalConcept_22(
        concept_id="CONCEPT_22_045",
        loinc_num="32045-0",
        snomed_ct="102200045",
        component="Diagnostic Analyte Component 22-045",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_046": ClinicalConcept_22(
        concept_id="CONCEPT_22_046",
        loinc_num="32046-1",
        snomed_ct="102200046",
        component="Diagnostic Analyte Component 22-046",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_047": ClinicalConcept_22(
        concept_id="CONCEPT_22_047",
        loinc_num="32047-2",
        snomed_ct="102200047",
        component="Diagnostic Analyte Component 22-047",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_048": ClinicalConcept_22(
        concept_id="CONCEPT_22_048",
        loinc_num="32048-3",
        snomed_ct="102200048",
        component="Diagnostic Analyte Component 22-048",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_049": ClinicalConcept_22(
        concept_id="CONCEPT_22_049",
        loinc_num="32049-4",
        snomed_ct="102200049",
        component="Diagnostic Analyte Component 22-049",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_050": ClinicalConcept_22(
        concept_id="CONCEPT_22_050",
        loinc_num="32050-5",
        snomed_ct="102200050",
        component="Diagnostic Analyte Component 22-050",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_051": ClinicalConcept_22(
        concept_id="CONCEPT_22_051",
        loinc_num="32051-6",
        snomed_ct="102200051",
        component="Diagnostic Analyte Component 22-051",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_052": ClinicalConcept_22(
        concept_id="CONCEPT_22_052",
        loinc_num="32052-7",
        snomed_ct="102200052",
        component="Diagnostic Analyte Component 22-052",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_053": ClinicalConcept_22(
        concept_id="CONCEPT_22_053",
        loinc_num="32053-8",
        snomed_ct="102200053",
        component="Diagnostic Analyte Component 22-053",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_054": ClinicalConcept_22(
        concept_id="CONCEPT_22_054",
        loinc_num="32054-0",
        snomed_ct="102200054",
        component="Diagnostic Analyte Component 22-054",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_055": ClinicalConcept_22(
        concept_id="CONCEPT_22_055",
        loinc_num="32055-1",
        snomed_ct="102200055",
        component="Diagnostic Analyte Component 22-055",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_056": ClinicalConcept_22(
        concept_id="CONCEPT_22_056",
        loinc_num="32056-2",
        snomed_ct="102200056",
        component="Diagnostic Analyte Component 22-056",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_057": ClinicalConcept_22(
        concept_id="CONCEPT_22_057",
        loinc_num="32057-3",
        snomed_ct="102200057",
        component="Diagnostic Analyte Component 22-057",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_058": ClinicalConcept_22(
        concept_id="CONCEPT_22_058",
        loinc_num="32058-4",
        snomed_ct="102200058",
        component="Diagnostic Analyte Component 22-058",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_059": ClinicalConcept_22(
        concept_id="CONCEPT_22_059",
        loinc_num="32059-5",
        snomed_ct="102200059",
        component="Diagnostic Analyte Component 22-059",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_060": ClinicalConcept_22(
        concept_id="CONCEPT_22_060",
        loinc_num="32060-6",
        snomed_ct="102200060",
        component="Diagnostic Analyte Component 22-060",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_061": ClinicalConcept_22(
        concept_id="CONCEPT_22_061",
        loinc_num="32061-7",
        snomed_ct="102200061",
        component="Diagnostic Analyte Component 22-061",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_062": ClinicalConcept_22(
        concept_id="CONCEPT_22_062",
        loinc_num="32062-8",
        snomed_ct="102200062",
        component="Diagnostic Analyte Component 22-062",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_063": ClinicalConcept_22(
        concept_id="CONCEPT_22_063",
        loinc_num="32063-0",
        snomed_ct="102200063",
        component="Diagnostic Analyte Component 22-063",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_064": ClinicalConcept_22(
        concept_id="CONCEPT_22_064",
        loinc_num="32064-1",
        snomed_ct="102200064",
        component="Diagnostic Analyte Component 22-064",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_065": ClinicalConcept_22(
        concept_id="CONCEPT_22_065",
        loinc_num="32065-2",
        snomed_ct="102200065",
        component="Diagnostic Analyte Component 22-065",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_066": ClinicalConcept_22(
        concept_id="CONCEPT_22_066",
        loinc_num="32066-3",
        snomed_ct="102200066",
        component="Diagnostic Analyte Component 22-066",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_067": ClinicalConcept_22(
        concept_id="CONCEPT_22_067",
        loinc_num="32067-4",
        snomed_ct="102200067",
        component="Diagnostic Analyte Component 22-067",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_068": ClinicalConcept_22(
        concept_id="CONCEPT_22_068",
        loinc_num="32068-5",
        snomed_ct="102200068",
        component="Diagnostic Analyte Component 22-068",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_069": ClinicalConcept_22(
        concept_id="CONCEPT_22_069",
        loinc_num="32069-6",
        snomed_ct="102200069",
        component="Diagnostic Analyte Component 22-069",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_070": ClinicalConcept_22(
        concept_id="CONCEPT_22_070",
        loinc_num="32070-7",
        snomed_ct="102200070",
        component="Diagnostic Analyte Component 22-070",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_071": ClinicalConcept_22(
        concept_id="CONCEPT_22_071",
        loinc_num="32071-8",
        snomed_ct="102200071",
        component="Diagnostic Analyte Component 22-071",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_072": ClinicalConcept_22(
        concept_id="CONCEPT_22_072",
        loinc_num="32072-0",
        snomed_ct="102200072",
        component="Diagnostic Analyte Component 22-072",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_073": ClinicalConcept_22(
        concept_id="CONCEPT_22_073",
        loinc_num="32073-1",
        snomed_ct="102200073",
        component="Diagnostic Analyte Component 22-073",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_074": ClinicalConcept_22(
        concept_id="CONCEPT_22_074",
        loinc_num="32074-2",
        snomed_ct="102200074",
        component="Diagnostic Analyte Component 22-074",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_075": ClinicalConcept_22(
        concept_id="CONCEPT_22_075",
        loinc_num="32075-3",
        snomed_ct="102200075",
        component="Diagnostic Analyte Component 22-075",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_076": ClinicalConcept_22(
        concept_id="CONCEPT_22_076",
        loinc_num="32076-4",
        snomed_ct="102200076",
        component="Diagnostic Analyte Component 22-076",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_077": ClinicalConcept_22(
        concept_id="CONCEPT_22_077",
        loinc_num="32077-5",
        snomed_ct="102200077",
        component="Diagnostic Analyte Component 22-077",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_078": ClinicalConcept_22(
        concept_id="CONCEPT_22_078",
        loinc_num="32078-6",
        snomed_ct="102200078",
        component="Diagnostic Analyte Component 22-078",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_079": ClinicalConcept_22(
        concept_id="CONCEPT_22_079",
        loinc_num="32079-7",
        snomed_ct="102200079",
        component="Diagnostic Analyte Component 22-079",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_080": ClinicalConcept_22(
        concept_id="CONCEPT_22_080",
        loinc_num="32080-8",
        snomed_ct="102200080",
        component="Diagnostic Analyte Component 22-080",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_081": ClinicalConcept_22(
        concept_id="CONCEPT_22_081",
        loinc_num="32081-0",
        snomed_ct="102200081",
        component="Diagnostic Analyte Component 22-081",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_082": ClinicalConcept_22(
        concept_id="CONCEPT_22_082",
        loinc_num="32082-1",
        snomed_ct="102200082",
        component="Diagnostic Analyte Component 22-082",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_083": ClinicalConcept_22(
        concept_id="CONCEPT_22_083",
        loinc_num="32083-2",
        snomed_ct="102200083",
        component="Diagnostic Analyte Component 22-083",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_084": ClinicalConcept_22(
        concept_id="CONCEPT_22_084",
        loinc_num="32084-3",
        snomed_ct="102200084",
        component="Diagnostic Analyte Component 22-084",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_085": ClinicalConcept_22(
        concept_id="CONCEPT_22_085",
        loinc_num="32085-4",
        snomed_ct="102200085",
        component="Diagnostic Analyte Component 22-085",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_086": ClinicalConcept_22(
        concept_id="CONCEPT_22_086",
        loinc_num="32086-5",
        snomed_ct="102200086",
        component="Diagnostic Analyte Component 22-086",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_087": ClinicalConcept_22(
        concept_id="CONCEPT_22_087",
        loinc_num="32087-6",
        snomed_ct="102200087",
        component="Diagnostic Analyte Component 22-087",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_088": ClinicalConcept_22(
        concept_id="CONCEPT_22_088",
        loinc_num="32088-7",
        snomed_ct="102200088",
        component="Diagnostic Analyte Component 22-088",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_089": ClinicalConcept_22(
        concept_id="CONCEPT_22_089",
        loinc_num="32089-8",
        snomed_ct="102200089",
        component="Diagnostic Analyte Component 22-089",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_090": ClinicalConcept_22(
        concept_id="CONCEPT_22_090",
        loinc_num="32090-0",
        snomed_ct="102200090",
        component="Diagnostic Analyte Component 22-090",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_091": ClinicalConcept_22(
        concept_id="CONCEPT_22_091",
        loinc_num="32091-1",
        snomed_ct="102200091",
        component="Diagnostic Analyte Component 22-091",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_092": ClinicalConcept_22(
        concept_id="CONCEPT_22_092",
        loinc_num="32092-2",
        snomed_ct="102200092",
        component="Diagnostic Analyte Component 22-092",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_093": ClinicalConcept_22(
        concept_id="CONCEPT_22_093",
        loinc_num="32093-3",
        snomed_ct="102200093",
        component="Diagnostic Analyte Component 22-093",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_094": ClinicalConcept_22(
        concept_id="CONCEPT_22_094",
        loinc_num="32094-4",
        snomed_ct="102200094",
        component="Diagnostic Analyte Component 22-094",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_095": ClinicalConcept_22(
        concept_id="CONCEPT_22_095",
        loinc_num="32095-5",
        snomed_ct="102200095",
        component="Diagnostic Analyte Component 22-095",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_096": ClinicalConcept_22(
        concept_id="CONCEPT_22_096",
        loinc_num="32096-6",
        snomed_ct="102200096",
        component="Diagnostic Analyte Component 22-096",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_097": ClinicalConcept_22(
        concept_id="CONCEPT_22_097",
        loinc_num="32097-7",
        snomed_ct="102200097",
        component="Diagnostic Analyte Component 22-097",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_098": ClinicalConcept_22(
        concept_id="CONCEPT_22_098",
        loinc_num="32098-8",
        snomed_ct="102200098",
        component="Diagnostic Analyte Component 22-098",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_099": ClinicalConcept_22(
        concept_id="CONCEPT_22_099",
        loinc_num="32099-0",
        snomed_ct="102200099",
        component="Diagnostic Analyte Component 22-099",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_100": ClinicalConcept_22(
        concept_id="CONCEPT_22_100",
        loinc_num="32100-1",
        snomed_ct="102200100",
        component="Diagnostic Analyte Component 22-100",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_101": ClinicalConcept_22(
        concept_id="CONCEPT_22_101",
        loinc_num="32101-2",
        snomed_ct="102200101",
        component="Diagnostic Analyte Component 22-101",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_102": ClinicalConcept_22(
        concept_id="CONCEPT_22_102",
        loinc_num="32102-3",
        snomed_ct="102200102",
        component="Diagnostic Analyte Component 22-102",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_103": ClinicalConcept_22(
        concept_id="CONCEPT_22_103",
        loinc_num="32103-4",
        snomed_ct="102200103",
        component="Diagnostic Analyte Component 22-103",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_104": ClinicalConcept_22(
        concept_id="CONCEPT_22_104",
        loinc_num="32104-5",
        snomed_ct="102200104",
        component="Diagnostic Analyte Component 22-104",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_105": ClinicalConcept_22(
        concept_id="CONCEPT_22_105",
        loinc_num="32105-6",
        snomed_ct="102200105",
        component="Diagnostic Analyte Component 22-105",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_106": ClinicalConcept_22(
        concept_id="CONCEPT_22_106",
        loinc_num="32106-7",
        snomed_ct="102200106",
        component="Diagnostic Analyte Component 22-106",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_107": ClinicalConcept_22(
        concept_id="CONCEPT_22_107",
        loinc_num="32107-8",
        snomed_ct="102200107",
        component="Diagnostic Analyte Component 22-107",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_108": ClinicalConcept_22(
        concept_id="CONCEPT_22_108",
        loinc_num="32108-0",
        snomed_ct="102200108",
        component="Diagnostic Analyte Component 22-108",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_109": ClinicalConcept_22(
        concept_id="CONCEPT_22_109",
        loinc_num="32109-1",
        snomed_ct="102200109",
        component="Diagnostic Analyte Component 22-109",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_110": ClinicalConcept_22(
        concept_id="CONCEPT_22_110",
        loinc_num="32110-2",
        snomed_ct="102200110",
        component="Diagnostic Analyte Component 22-110",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_111": ClinicalConcept_22(
        concept_id="CONCEPT_22_111",
        loinc_num="32111-3",
        snomed_ct="102200111",
        component="Diagnostic Analyte Component 22-111",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_112": ClinicalConcept_22(
        concept_id="CONCEPT_22_112",
        loinc_num="32112-4",
        snomed_ct="102200112",
        component="Diagnostic Analyte Component 22-112",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_113": ClinicalConcept_22(
        concept_id="CONCEPT_22_113",
        loinc_num="32113-5",
        snomed_ct="102200113",
        component="Diagnostic Analyte Component 22-113",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_114": ClinicalConcept_22(
        concept_id="CONCEPT_22_114",
        loinc_num="32114-6",
        snomed_ct="102200114",
        component="Diagnostic Analyte Component 22-114",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_115": ClinicalConcept_22(
        concept_id="CONCEPT_22_115",
        loinc_num="32115-7",
        snomed_ct="102200115",
        component="Diagnostic Analyte Component 22-115",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_116": ClinicalConcept_22(
        concept_id="CONCEPT_22_116",
        loinc_num="32116-8",
        snomed_ct="102200116",
        component="Diagnostic Analyte Component 22-116",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_117": ClinicalConcept_22(
        concept_id="CONCEPT_22_117",
        loinc_num="32117-0",
        snomed_ct="102200117",
        component="Diagnostic Analyte Component 22-117",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_118": ClinicalConcept_22(
        concept_id="CONCEPT_22_118",
        loinc_num="32118-1",
        snomed_ct="102200118",
        component="Diagnostic Analyte Component 22-118",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_119": ClinicalConcept_22(
        concept_id="CONCEPT_22_119",
        loinc_num="32119-2",
        snomed_ct="102200119",
        component="Diagnostic Analyte Component 22-119",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_120": ClinicalConcept_22(
        concept_id="CONCEPT_22_120",
        loinc_num="32120-3",
        snomed_ct="102200120",
        component="Diagnostic Analyte Component 22-120",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_121": ClinicalConcept_22(
        concept_id="CONCEPT_22_121",
        loinc_num="32121-4",
        snomed_ct="102200121",
        component="Diagnostic Analyte Component 22-121",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_122": ClinicalConcept_22(
        concept_id="CONCEPT_22_122",
        loinc_num="32122-5",
        snomed_ct="102200122",
        component="Diagnostic Analyte Component 22-122",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_123": ClinicalConcept_22(
        concept_id="CONCEPT_22_123",
        loinc_num="32123-6",
        snomed_ct="102200123",
        component="Diagnostic Analyte Component 22-123",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_124": ClinicalConcept_22(
        concept_id="CONCEPT_22_124",
        loinc_num="32124-7",
        snomed_ct="102200124",
        component="Diagnostic Analyte Component 22-124",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_125": ClinicalConcept_22(
        concept_id="CONCEPT_22_125",
        loinc_num="32125-8",
        snomed_ct="102200125",
        component="Diagnostic Analyte Component 22-125",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_126": ClinicalConcept_22(
        concept_id="CONCEPT_22_126",
        loinc_num="32126-0",
        snomed_ct="102200126",
        component="Diagnostic Analyte Component 22-126",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_127": ClinicalConcept_22(
        concept_id="CONCEPT_22_127",
        loinc_num="32127-1",
        snomed_ct="102200127",
        component="Diagnostic Analyte Component 22-127",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_128": ClinicalConcept_22(
        concept_id="CONCEPT_22_128",
        loinc_num="32128-2",
        snomed_ct="102200128",
        component="Diagnostic Analyte Component 22-128",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_129": ClinicalConcept_22(
        concept_id="CONCEPT_22_129",
        loinc_num="32129-3",
        snomed_ct="102200129",
        component="Diagnostic Analyte Component 22-129",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_130": ClinicalConcept_22(
        concept_id="CONCEPT_22_130",
        loinc_num="32130-4",
        snomed_ct="102200130",
        component="Diagnostic Analyte Component 22-130",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_131": ClinicalConcept_22(
        concept_id="CONCEPT_22_131",
        loinc_num="32131-5",
        snomed_ct="102200131",
        component="Diagnostic Analyte Component 22-131",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_132": ClinicalConcept_22(
        concept_id="CONCEPT_22_132",
        loinc_num="32132-6",
        snomed_ct="102200132",
        component="Diagnostic Analyte Component 22-132",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_133": ClinicalConcept_22(
        concept_id="CONCEPT_22_133",
        loinc_num="32133-7",
        snomed_ct="102200133",
        component="Diagnostic Analyte Component 22-133",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_134": ClinicalConcept_22(
        concept_id="CONCEPT_22_134",
        loinc_num="32134-8",
        snomed_ct="102200134",
        component="Diagnostic Analyte Component 22-134",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_135": ClinicalConcept_22(
        concept_id="CONCEPT_22_135",
        loinc_num="32135-0",
        snomed_ct="102200135",
        component="Diagnostic Analyte Component 22-135",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_136": ClinicalConcept_22(
        concept_id="CONCEPT_22_136",
        loinc_num="32136-1",
        snomed_ct="102200136",
        component="Diagnostic Analyte Component 22-136",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_137": ClinicalConcept_22(
        concept_id="CONCEPT_22_137",
        loinc_num="32137-2",
        snomed_ct="102200137",
        component="Diagnostic Analyte Component 22-137",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_138": ClinicalConcept_22(
        concept_id="CONCEPT_22_138",
        loinc_num="32138-3",
        snomed_ct="102200138",
        component="Diagnostic Analyte Component 22-138",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_139": ClinicalConcept_22(
        concept_id="CONCEPT_22_139",
        loinc_num="32139-4",
        snomed_ct="102200139",
        component="Diagnostic Analyte Component 22-139",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_140": ClinicalConcept_22(
        concept_id="CONCEPT_22_140",
        loinc_num="32140-5",
        snomed_ct="102200140",
        component="Diagnostic Analyte Component 22-140",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_141": ClinicalConcept_22(
        concept_id="CONCEPT_22_141",
        loinc_num="32141-6",
        snomed_ct="102200141",
        component="Diagnostic Analyte Component 22-141",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_142": ClinicalConcept_22(
        concept_id="CONCEPT_22_142",
        loinc_num="32142-7",
        snomed_ct="102200142",
        component="Diagnostic Analyte Component 22-142",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_143": ClinicalConcept_22(
        concept_id="CONCEPT_22_143",
        loinc_num="32143-8",
        snomed_ct="102200143",
        component="Diagnostic Analyte Component 22-143",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_144": ClinicalConcept_22(
        concept_id="CONCEPT_22_144",
        loinc_num="32144-0",
        snomed_ct="102200144",
        component="Diagnostic Analyte Component 22-144",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_145": ClinicalConcept_22(
        concept_id="CONCEPT_22_145",
        loinc_num="32145-1",
        snomed_ct="102200145",
        component="Diagnostic Analyte Component 22-145",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_146": ClinicalConcept_22(
        concept_id="CONCEPT_22_146",
        loinc_num="32146-2",
        snomed_ct="102200146",
        component="Diagnostic Analyte Component 22-146",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_147": ClinicalConcept_22(
        concept_id="CONCEPT_22_147",
        loinc_num="32147-3",
        snomed_ct="102200147",
        component="Diagnostic Analyte Component 22-147",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_148": ClinicalConcept_22(
        concept_id="CONCEPT_22_148",
        loinc_num="32148-4",
        snomed_ct="102200148",
        component="Diagnostic Analyte Component 22-148",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_149": ClinicalConcept_22(
        concept_id="CONCEPT_22_149",
        loinc_num="32149-5",
        snomed_ct="102200149",
        component="Diagnostic Analyte Component 22-149",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_150": ClinicalConcept_22(
        concept_id="CONCEPT_22_150",
        loinc_num="32150-6",
        snomed_ct="102200150",
        component="Diagnostic Analyte Component 22-150",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_151": ClinicalConcept_22(
        concept_id="CONCEPT_22_151",
        loinc_num="32151-7",
        snomed_ct="102200151",
        component="Diagnostic Analyte Component 22-151",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_152": ClinicalConcept_22(
        concept_id="CONCEPT_22_152",
        loinc_num="32152-8",
        snomed_ct="102200152",
        component="Diagnostic Analyte Component 22-152",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_153": ClinicalConcept_22(
        concept_id="CONCEPT_22_153",
        loinc_num="32153-0",
        snomed_ct="102200153",
        component="Diagnostic Analyte Component 22-153",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_154": ClinicalConcept_22(
        concept_id="CONCEPT_22_154",
        loinc_num="32154-1",
        snomed_ct="102200154",
        component="Diagnostic Analyte Component 22-154",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_155": ClinicalConcept_22(
        concept_id="CONCEPT_22_155",
        loinc_num="32155-2",
        snomed_ct="102200155",
        component="Diagnostic Analyte Component 22-155",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_156": ClinicalConcept_22(
        concept_id="CONCEPT_22_156",
        loinc_num="32156-3",
        snomed_ct="102200156",
        component="Diagnostic Analyte Component 22-156",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_157": ClinicalConcept_22(
        concept_id="CONCEPT_22_157",
        loinc_num="32157-4",
        snomed_ct="102200157",
        component="Diagnostic Analyte Component 22-157",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_158": ClinicalConcept_22(
        concept_id="CONCEPT_22_158",
        loinc_num="32158-5",
        snomed_ct="102200158",
        component="Diagnostic Analyte Component 22-158",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_159": ClinicalConcept_22(
        concept_id="CONCEPT_22_159",
        loinc_num="32159-6",
        snomed_ct="102200159",
        component="Diagnostic Analyte Component 22-159",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_160": ClinicalConcept_22(
        concept_id="CONCEPT_22_160",
        loinc_num="32160-7",
        snomed_ct="102200160",
        component="Diagnostic Analyte Component 22-160",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_161": ClinicalConcept_22(
        concept_id="CONCEPT_22_161",
        loinc_num="32161-8",
        snomed_ct="102200161",
        component="Diagnostic Analyte Component 22-161",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_162": ClinicalConcept_22(
        concept_id="CONCEPT_22_162",
        loinc_num="32162-0",
        snomed_ct="102200162",
        component="Diagnostic Analyte Component 22-162",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_163": ClinicalConcept_22(
        concept_id="CONCEPT_22_163",
        loinc_num="32163-1",
        snomed_ct="102200163",
        component="Diagnostic Analyte Component 22-163",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_164": ClinicalConcept_22(
        concept_id="CONCEPT_22_164",
        loinc_num="32164-2",
        snomed_ct="102200164",
        component="Diagnostic Analyte Component 22-164",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_165": ClinicalConcept_22(
        concept_id="CONCEPT_22_165",
        loinc_num="32165-3",
        snomed_ct="102200165",
        component="Diagnostic Analyte Component 22-165",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_166": ClinicalConcept_22(
        concept_id="CONCEPT_22_166",
        loinc_num="32166-4",
        snomed_ct="102200166",
        component="Diagnostic Analyte Component 22-166",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_167": ClinicalConcept_22(
        concept_id="CONCEPT_22_167",
        loinc_num="32167-5",
        snomed_ct="102200167",
        component="Diagnostic Analyte Component 22-167",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_168": ClinicalConcept_22(
        concept_id="CONCEPT_22_168",
        loinc_num="32168-6",
        snomed_ct="102200168",
        component="Diagnostic Analyte Component 22-168",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_169": ClinicalConcept_22(
        concept_id="CONCEPT_22_169",
        loinc_num="32169-7",
        snomed_ct="102200169",
        component="Diagnostic Analyte Component 22-169",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_170": ClinicalConcept_22(
        concept_id="CONCEPT_22_170",
        loinc_num="32170-8",
        snomed_ct="102200170",
        component="Diagnostic Analyte Component 22-170",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_171": ClinicalConcept_22(
        concept_id="CONCEPT_22_171",
        loinc_num="32171-0",
        snomed_ct="102200171",
        component="Diagnostic Analyte Component 22-171",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_172": ClinicalConcept_22(
        concept_id="CONCEPT_22_172",
        loinc_num="32172-1",
        snomed_ct="102200172",
        component="Diagnostic Analyte Component 22-172",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_173": ClinicalConcept_22(
        concept_id="CONCEPT_22_173",
        loinc_num="32173-2",
        snomed_ct="102200173",
        component="Diagnostic Analyte Component 22-173",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_174": ClinicalConcept_22(
        concept_id="CONCEPT_22_174",
        loinc_num="32174-3",
        snomed_ct="102200174",
        component="Diagnostic Analyte Component 22-174",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_175": ClinicalConcept_22(
        concept_id="CONCEPT_22_175",
        loinc_num="32175-4",
        snomed_ct="102200175",
        component="Diagnostic Analyte Component 22-175",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_176": ClinicalConcept_22(
        concept_id="CONCEPT_22_176",
        loinc_num="32176-5",
        snomed_ct="102200176",
        component="Diagnostic Analyte Component 22-176",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_177": ClinicalConcept_22(
        concept_id="CONCEPT_22_177",
        loinc_num="32177-6",
        snomed_ct="102200177",
        component="Diagnostic Analyte Component 22-177",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_178": ClinicalConcept_22(
        concept_id="CONCEPT_22_178",
        loinc_num="32178-7",
        snomed_ct="102200178",
        component="Diagnostic Analyte Component 22-178",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_179": ClinicalConcept_22(
        concept_id="CONCEPT_22_179",
        loinc_num="32179-8",
        snomed_ct="102200179",
        component="Diagnostic Analyte Component 22-179",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_180": ClinicalConcept_22(
        concept_id="CONCEPT_22_180",
        loinc_num="32180-0",
        snomed_ct="102200180",
        component="Diagnostic Analyte Component 22-180",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_181": ClinicalConcept_22(
        concept_id="CONCEPT_22_181",
        loinc_num="32181-1",
        snomed_ct="102200181",
        component="Diagnostic Analyte Component 22-181",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_182": ClinicalConcept_22(
        concept_id="CONCEPT_22_182",
        loinc_num="32182-2",
        snomed_ct="102200182",
        component="Diagnostic Analyte Component 22-182",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_183": ClinicalConcept_22(
        concept_id="CONCEPT_22_183",
        loinc_num="32183-3",
        snomed_ct="102200183",
        component="Diagnostic Analyte Component 22-183",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_184": ClinicalConcept_22(
        concept_id="CONCEPT_22_184",
        loinc_num="32184-4",
        snomed_ct="102200184",
        component="Diagnostic Analyte Component 22-184",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_185": ClinicalConcept_22(
        concept_id="CONCEPT_22_185",
        loinc_num="32185-5",
        snomed_ct="102200185",
        component="Diagnostic Analyte Component 22-185",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_186": ClinicalConcept_22(
        concept_id="CONCEPT_22_186",
        loinc_num="32186-6",
        snomed_ct="102200186",
        component="Diagnostic Analyte Component 22-186",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_187": ClinicalConcept_22(
        concept_id="CONCEPT_22_187",
        loinc_num="32187-7",
        snomed_ct="102200187",
        component="Diagnostic Analyte Component 22-187",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_188": ClinicalConcept_22(
        concept_id="CONCEPT_22_188",
        loinc_num="32188-8",
        snomed_ct="102200188",
        component="Diagnostic Analyte Component 22-188",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_189": ClinicalConcept_22(
        concept_id="CONCEPT_22_189",
        loinc_num="32189-0",
        snomed_ct="102200189",
        component="Diagnostic Analyte Component 22-189",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_190": ClinicalConcept_22(
        concept_id="CONCEPT_22_190",
        loinc_num="32190-1",
        snomed_ct="102200190",
        component="Diagnostic Analyte Component 22-190",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_191": ClinicalConcept_22(
        concept_id="CONCEPT_22_191",
        loinc_num="32191-2",
        snomed_ct="102200191",
        component="Diagnostic Analyte Component 22-191",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_192": ClinicalConcept_22(
        concept_id="CONCEPT_22_192",
        loinc_num="32192-3",
        snomed_ct="102200192",
        component="Diagnostic Analyte Component 22-192",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_193": ClinicalConcept_22(
        concept_id="CONCEPT_22_193",
        loinc_num="32193-4",
        snomed_ct="102200193",
        component="Diagnostic Analyte Component 22-193",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_194": ClinicalConcept_22(
        concept_id="CONCEPT_22_194",
        loinc_num="32194-5",
        snomed_ct="102200194",
        component="Diagnostic Analyte Component 22-194",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_195": ClinicalConcept_22(
        concept_id="CONCEPT_22_195",
        loinc_num="32195-6",
        snomed_ct="102200195",
        component="Diagnostic Analyte Component 22-195",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_196": ClinicalConcept_22(
        concept_id="CONCEPT_22_196",
        loinc_num="32196-7",
        snomed_ct="102200196",
        component="Diagnostic Analyte Component 22-196",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_197": ClinicalConcept_22(
        concept_id="CONCEPT_22_197",
        loinc_num="32197-8",
        snomed_ct="102200197",
        component="Diagnostic Analyte Component 22-197",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_198": ClinicalConcept_22(
        concept_id="CONCEPT_22_198",
        loinc_num="32198-0",
        snomed_ct="102200198",
        component="Diagnostic Analyte Component 22-198",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
    "CONCEPT_22_199": ClinicalConcept_22(
        concept_id="CONCEPT_22_199",
        loinc_num="32199-1",
        snomed_ct="102200199",
        component="Diagnostic Analyte Component 22-199",
        property_type="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Automated Chemiluminescent Immunoassay / Spectrophotometry",
        class_type="CHEM"
    ),
}
